// attributes.proto - Unified Attributes Service for Listings Microservice
// Version: v1
// Created: 2025-11-13
// Description: gRPC service for managing attributes, category relationships, and listing values

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: api/proto/attributes/v1/attributes.proto

package attributesv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AttributeService_CreateAttribute_FullMethodName              = "/attributes.v1.AttributeService/CreateAttribute"
	AttributeService_UpdateAttribute_FullMethodName              = "/attributes.v1.AttributeService/UpdateAttribute"
	AttributeService_DeleteAttribute_FullMethodName              = "/attributes.v1.AttributeService/DeleteAttribute"
	AttributeService_GetAttribute_FullMethodName                 = "/attributes.v1.AttributeService/GetAttribute"
	AttributeService_ListAttributes_FullMethodName               = "/attributes.v1.AttributeService/ListAttributes"
	AttributeService_LinkAttributeToCategory_FullMethodName      = "/attributes.v1.AttributeService/LinkAttributeToCategory"
	AttributeService_UpdateCategoryAttribute_FullMethodName      = "/attributes.v1.AttributeService/UpdateCategoryAttribute"
	AttributeService_UnlinkAttributeFromCategory_FullMethodName  = "/attributes.v1.AttributeService/UnlinkAttributeFromCategory"
	AttributeService_GetCategoryAttributes_FullMethodName        = "/attributes.v1.AttributeService/GetCategoryAttributes"
	AttributeService_GetCategoryVariantAttributes_FullMethodName = "/attributes.v1.AttributeService/GetCategoryVariantAttributes"
	AttributeService_GetListingAttributes_FullMethodName         = "/attributes.v1.AttributeService/GetListingAttributes"
	AttributeService_SetListingAttributes_FullMethodName         = "/attributes.v1.AttributeService/SetListingAttributes"
	AttributeService_ValidateAttributeValues_FullMethodName      = "/attributes.v1.AttributeService/ValidateAttributeValues"
	AttributeService_BulkImportAttributes_FullMethodName         = "/attributes.v1.AttributeService/BulkImportAttributes"
)

// AttributeServiceClient is the client API for AttributeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ============================================================================
// AttributeService - Unified Attributes Management
// ============================================================================
type AttributeServiceClient interface {
	// CreateAttribute creates a new attribute definition
	CreateAttribute(ctx context.Context, in *CreateAttributeRequest, opts ...grpc.CallOption) (*CreateAttributeResponse, error)
	// UpdateAttribute updates an existing attribute
	UpdateAttribute(ctx context.Context, in *UpdateAttributeRequest, opts ...grpc.CallOption) (*UpdateAttributeResponse, error)
	// DeleteAttribute soft-deletes an attribute (sets is_active=false)
	DeleteAttribute(ctx context.Context, in *DeleteAttributeRequest, opts ...grpc.CallOption) (*DeleteAttributeResponse, error)
	// GetAttribute retrieves a single attribute by ID or code
	GetAttribute(ctx context.Context, in *GetAttributeRequest, opts ...grpc.CallOption) (*GetAttributeResponse, error)
	// ListAttributes lists all attributes with optional filtering
	ListAttributes(ctx context.Context, in *ListAttributesRequest, opts ...grpc.CallOption) (*ListAttributesResponse, error)
	// LinkAttributeToCategory links an attribute to a category with optional overrides
	LinkAttributeToCategory(ctx context.Context, in *LinkAttributeToCategoryRequest, opts ...grpc.CallOption) (*LinkAttributeToCategoryResponse, error)
	// UpdateCategoryAttribute updates category-specific attribute settings
	UpdateCategoryAttribute(ctx context.Context, in *UpdateCategoryAttributeRequest, opts ...grpc.CallOption) (*UpdateCategoryAttributeResponse, error)
	// UnlinkAttributeFromCategory removes the attribute-category relationship
	UnlinkAttributeFromCategory(ctx context.Context, in *UnlinkAttributeFromCategoryRequest, opts ...grpc.CallOption) (*UnlinkAttributeFromCategoryResponse, error)
	// GetCategoryAttributes retrieves all attributes for a specific category
	GetCategoryAttributes(ctx context.Context, in *GetCategoryAttributesRequest, opts ...grpc.CallOption) (*GetCategoryAttributesResponse, error)
	// GetCategoryVariantAttributes retrieves variant attributes for a category
	GetCategoryVariantAttributes(ctx context.Context, in *GetCategoryVariantAttributesRequest, opts ...grpc.CallOption) (*GetCategoryVariantAttributesResponse, error)
	// GetListingAttributes retrieves all attribute values for a listing
	GetListingAttributes(ctx context.Context, in *GetListingAttributesRequest, opts ...grpc.CallOption) (*GetListingAttributesResponse, error)
	// SetListingAttributes sets/updates attribute values for a listing
	SetListingAttributes(ctx context.Context, in *SetListingAttributesRequest, opts ...grpc.CallOption) (*SetListingAttributesResponse, error)
	// ValidateAttributeValues validates attribute values before saving
	ValidateAttributeValues(ctx context.Context, in *ValidateAttributeValuesRequest, opts ...grpc.CallOption) (*ValidateAttributeValuesResponse, error)
	// BulkImportAttributes imports multiple attributes at once (for migration)
	BulkImportAttributes(ctx context.Context, in *BulkImportAttributesRequest, opts ...grpc.CallOption) (*BulkImportAttributesResponse, error)
}

type attributeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAttributeServiceClient(cc grpc.ClientConnInterface) AttributeServiceClient {
	return &attributeServiceClient{cc}
}

func (c *attributeServiceClient) CreateAttribute(ctx context.Context, in *CreateAttributeRequest, opts ...grpc.CallOption) (*CreateAttributeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAttributeResponse)
	err := c.cc.Invoke(ctx, AttributeService_CreateAttribute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *attributeServiceClient) UpdateAttribute(ctx context.Context, in *UpdateAttributeRequest, opts ...grpc.CallOption) (*UpdateAttributeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateAttributeResponse)
	err := c.cc.Invoke(ctx, AttributeService_UpdateAttribute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *attributeServiceClient) DeleteAttribute(ctx context.Context, in *DeleteAttributeRequest, opts ...grpc.CallOption) (*DeleteAttributeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteAttributeResponse)
	err := c.cc.Invoke(ctx, AttributeService_DeleteAttribute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *attributeServiceClient) GetAttribute(ctx context.Context, in *GetAttributeRequest, opts ...grpc.CallOption) (*GetAttributeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAttributeResponse)
	err := c.cc.Invoke(ctx, AttributeService_GetAttribute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *attributeServiceClient) ListAttributes(ctx context.Context, in *ListAttributesRequest, opts ...grpc.CallOption) (*ListAttributesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAttributesResponse)
	err := c.cc.Invoke(ctx, AttributeService_ListAttributes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *attributeServiceClient) LinkAttributeToCategory(ctx context.Context, in *LinkAttributeToCategoryRequest, opts ...grpc.CallOption) (*LinkAttributeToCategoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LinkAttributeToCategoryResponse)
	err := c.cc.Invoke(ctx, AttributeService_LinkAttributeToCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *attributeServiceClient) UpdateCategoryAttribute(ctx context.Context, in *UpdateCategoryAttributeRequest, opts ...grpc.CallOption) (*UpdateCategoryAttributeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateCategoryAttributeResponse)
	err := c.cc.Invoke(ctx, AttributeService_UpdateCategoryAttribute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *attributeServiceClient) UnlinkAttributeFromCategory(ctx context.Context, in *UnlinkAttributeFromCategoryRequest, opts ...grpc.CallOption) (*UnlinkAttributeFromCategoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnlinkAttributeFromCategoryResponse)
	err := c.cc.Invoke(ctx, AttributeService_UnlinkAttributeFromCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *attributeServiceClient) GetCategoryAttributes(ctx context.Context, in *GetCategoryAttributesRequest, opts ...grpc.CallOption) (*GetCategoryAttributesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCategoryAttributesResponse)
	err := c.cc.Invoke(ctx, AttributeService_GetCategoryAttributes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *attributeServiceClient) GetCategoryVariantAttributes(ctx context.Context, in *GetCategoryVariantAttributesRequest, opts ...grpc.CallOption) (*GetCategoryVariantAttributesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCategoryVariantAttributesResponse)
	err := c.cc.Invoke(ctx, AttributeService_GetCategoryVariantAttributes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *attributeServiceClient) GetListingAttributes(ctx context.Context, in *GetListingAttributesRequest, opts ...grpc.CallOption) (*GetListingAttributesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetListingAttributesResponse)
	err := c.cc.Invoke(ctx, AttributeService_GetListingAttributes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *attributeServiceClient) SetListingAttributes(ctx context.Context, in *SetListingAttributesRequest, opts ...grpc.CallOption) (*SetListingAttributesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetListingAttributesResponse)
	err := c.cc.Invoke(ctx, AttributeService_SetListingAttributes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *attributeServiceClient) ValidateAttributeValues(ctx context.Context, in *ValidateAttributeValuesRequest, opts ...grpc.CallOption) (*ValidateAttributeValuesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateAttributeValuesResponse)
	err := c.cc.Invoke(ctx, AttributeService_ValidateAttributeValues_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *attributeServiceClient) BulkImportAttributes(ctx context.Context, in *BulkImportAttributesRequest, opts ...grpc.CallOption) (*BulkImportAttributesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BulkImportAttributesResponse)
	err := c.cc.Invoke(ctx, AttributeService_BulkImportAttributes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AttributeServiceServer is the server API for AttributeService service.
// All implementations must embed UnimplementedAttributeServiceServer
// for forward compatibility.
//
// ============================================================================
// AttributeService - Unified Attributes Management
// ============================================================================
type AttributeServiceServer interface {
	// CreateAttribute creates a new attribute definition
	CreateAttribute(context.Context, *CreateAttributeRequest) (*CreateAttributeResponse, error)
	// UpdateAttribute updates an existing attribute
	UpdateAttribute(context.Context, *UpdateAttributeRequest) (*UpdateAttributeResponse, error)
	// DeleteAttribute soft-deletes an attribute (sets is_active=false)
	DeleteAttribute(context.Context, *DeleteAttributeRequest) (*DeleteAttributeResponse, error)
	// GetAttribute retrieves a single attribute by ID or code
	GetAttribute(context.Context, *GetAttributeRequest) (*GetAttributeResponse, error)
	// ListAttributes lists all attributes with optional filtering
	ListAttributes(context.Context, *ListAttributesRequest) (*ListAttributesResponse, error)
	// LinkAttributeToCategory links an attribute to a category with optional overrides
	LinkAttributeToCategory(context.Context, *LinkAttributeToCategoryRequest) (*LinkAttributeToCategoryResponse, error)
	// UpdateCategoryAttribute updates category-specific attribute settings
	UpdateCategoryAttribute(context.Context, *UpdateCategoryAttributeRequest) (*UpdateCategoryAttributeResponse, error)
	// UnlinkAttributeFromCategory removes the attribute-category relationship
	UnlinkAttributeFromCategory(context.Context, *UnlinkAttributeFromCategoryRequest) (*UnlinkAttributeFromCategoryResponse, error)
	// GetCategoryAttributes retrieves all attributes for a specific category
	GetCategoryAttributes(context.Context, *GetCategoryAttributesRequest) (*GetCategoryAttributesResponse, error)
	// GetCategoryVariantAttributes retrieves variant attributes for a category
	GetCategoryVariantAttributes(context.Context, *GetCategoryVariantAttributesRequest) (*GetCategoryVariantAttributesResponse, error)
	// GetListingAttributes retrieves all attribute values for a listing
	GetListingAttributes(context.Context, *GetListingAttributesRequest) (*GetListingAttributesResponse, error)
	// SetListingAttributes sets/updates attribute values for a listing
	SetListingAttributes(context.Context, *SetListingAttributesRequest) (*SetListingAttributesResponse, error)
	// ValidateAttributeValues validates attribute values before saving
	ValidateAttributeValues(context.Context, *ValidateAttributeValuesRequest) (*ValidateAttributeValuesResponse, error)
	// BulkImportAttributes imports multiple attributes at once (for migration)
	BulkImportAttributes(context.Context, *BulkImportAttributesRequest) (*BulkImportAttributesResponse, error)
	mustEmbedUnimplementedAttributeServiceServer()
}

// UnimplementedAttributeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAttributeServiceServer struct{}

func (UnimplementedAttributeServiceServer) CreateAttribute(context.Context, *CreateAttributeRequest) (*CreateAttributeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAttribute not implemented")
}
func (UnimplementedAttributeServiceServer) UpdateAttribute(context.Context, *UpdateAttributeRequest) (*UpdateAttributeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAttribute not implemented")
}
func (UnimplementedAttributeServiceServer) DeleteAttribute(context.Context, *DeleteAttributeRequest) (*DeleteAttributeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAttribute not implemented")
}
func (UnimplementedAttributeServiceServer) GetAttribute(context.Context, *GetAttributeRequest) (*GetAttributeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAttribute not implemented")
}
func (UnimplementedAttributeServiceServer) ListAttributes(context.Context, *ListAttributesRequest) (*ListAttributesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAttributes not implemented")
}
func (UnimplementedAttributeServiceServer) LinkAttributeToCategory(context.Context, *LinkAttributeToCategoryRequest) (*LinkAttributeToCategoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LinkAttributeToCategory not implemented")
}
func (UnimplementedAttributeServiceServer) UpdateCategoryAttribute(context.Context, *UpdateCategoryAttributeRequest) (*UpdateCategoryAttributeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCategoryAttribute not implemented")
}
func (UnimplementedAttributeServiceServer) UnlinkAttributeFromCategory(context.Context, *UnlinkAttributeFromCategoryRequest) (*UnlinkAttributeFromCategoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnlinkAttributeFromCategory not implemented")
}
func (UnimplementedAttributeServiceServer) GetCategoryAttributes(context.Context, *GetCategoryAttributesRequest) (*GetCategoryAttributesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCategoryAttributes not implemented")
}
func (UnimplementedAttributeServiceServer) GetCategoryVariantAttributes(context.Context, *GetCategoryVariantAttributesRequest) (*GetCategoryVariantAttributesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCategoryVariantAttributes not implemented")
}
func (UnimplementedAttributeServiceServer) GetListingAttributes(context.Context, *GetListingAttributesRequest) (*GetListingAttributesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetListingAttributes not implemented")
}
func (UnimplementedAttributeServiceServer) SetListingAttributes(context.Context, *SetListingAttributesRequest) (*SetListingAttributesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetListingAttributes not implemented")
}
func (UnimplementedAttributeServiceServer) ValidateAttributeValues(context.Context, *ValidateAttributeValuesRequest) (*ValidateAttributeValuesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateAttributeValues not implemented")
}
func (UnimplementedAttributeServiceServer) BulkImportAttributes(context.Context, *BulkImportAttributesRequest) (*BulkImportAttributesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BulkImportAttributes not implemented")
}
func (UnimplementedAttributeServiceServer) mustEmbedUnimplementedAttributeServiceServer() {}
func (UnimplementedAttributeServiceServer) testEmbeddedByValue()                          {}

// UnsafeAttributeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AttributeServiceServer will
// result in compilation errors.
type UnsafeAttributeServiceServer interface {
	mustEmbedUnimplementedAttributeServiceServer()
}

func RegisterAttributeServiceServer(s grpc.ServiceRegistrar, srv AttributeServiceServer) {
	// If the following call pancis, it indicates UnimplementedAttributeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AttributeService_ServiceDesc, srv)
}

func _AttributeService_CreateAttribute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAttributeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttributeServiceServer).CreateAttribute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttributeService_CreateAttribute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttributeServiceServer).CreateAttribute(ctx, req.(*CreateAttributeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AttributeService_UpdateAttribute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAttributeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttributeServiceServer).UpdateAttribute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttributeService_UpdateAttribute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttributeServiceServer).UpdateAttribute(ctx, req.(*UpdateAttributeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AttributeService_DeleteAttribute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAttributeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttributeServiceServer).DeleteAttribute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttributeService_DeleteAttribute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttributeServiceServer).DeleteAttribute(ctx, req.(*DeleteAttributeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AttributeService_GetAttribute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAttributeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttributeServiceServer).GetAttribute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttributeService_GetAttribute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttributeServiceServer).GetAttribute(ctx, req.(*GetAttributeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AttributeService_ListAttributes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAttributesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttributeServiceServer).ListAttributes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttributeService_ListAttributes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttributeServiceServer).ListAttributes(ctx, req.(*ListAttributesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AttributeService_LinkAttributeToCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LinkAttributeToCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttributeServiceServer).LinkAttributeToCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttributeService_LinkAttributeToCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttributeServiceServer).LinkAttributeToCategory(ctx, req.(*LinkAttributeToCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AttributeService_UpdateCategoryAttribute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCategoryAttributeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttributeServiceServer).UpdateCategoryAttribute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttributeService_UpdateCategoryAttribute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttributeServiceServer).UpdateCategoryAttribute(ctx, req.(*UpdateCategoryAttributeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AttributeService_UnlinkAttributeFromCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnlinkAttributeFromCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttributeServiceServer).UnlinkAttributeFromCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttributeService_UnlinkAttributeFromCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttributeServiceServer).UnlinkAttributeFromCategory(ctx, req.(*UnlinkAttributeFromCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AttributeService_GetCategoryAttributes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCategoryAttributesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttributeServiceServer).GetCategoryAttributes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttributeService_GetCategoryAttributes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttributeServiceServer).GetCategoryAttributes(ctx, req.(*GetCategoryAttributesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AttributeService_GetCategoryVariantAttributes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCategoryVariantAttributesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttributeServiceServer).GetCategoryVariantAttributes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttributeService_GetCategoryVariantAttributes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttributeServiceServer).GetCategoryVariantAttributes(ctx, req.(*GetCategoryVariantAttributesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AttributeService_GetListingAttributes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetListingAttributesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttributeServiceServer).GetListingAttributes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttributeService_GetListingAttributes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttributeServiceServer).GetListingAttributes(ctx, req.(*GetListingAttributesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AttributeService_SetListingAttributes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetListingAttributesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttributeServiceServer).SetListingAttributes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttributeService_SetListingAttributes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttributeServiceServer).SetListingAttributes(ctx, req.(*SetListingAttributesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AttributeService_ValidateAttributeValues_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateAttributeValuesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttributeServiceServer).ValidateAttributeValues(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttributeService_ValidateAttributeValues_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttributeServiceServer).ValidateAttributeValues(ctx, req.(*ValidateAttributeValuesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AttributeService_BulkImportAttributes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BulkImportAttributesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttributeServiceServer).BulkImportAttributes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttributeService_BulkImportAttributes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttributeServiceServer).BulkImportAttributes(ctx, req.(*BulkImportAttributesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AttributeService_ServiceDesc is the grpc.ServiceDesc for AttributeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AttributeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "attributes.v1.AttributeService",
	HandlerType: (*AttributeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAttribute",
			Handler:    _AttributeService_CreateAttribute_Handler,
		},
		{
			MethodName: "UpdateAttribute",
			Handler:    _AttributeService_UpdateAttribute_Handler,
		},
		{
			MethodName: "DeleteAttribute",
			Handler:    _AttributeService_DeleteAttribute_Handler,
		},
		{
			MethodName: "GetAttribute",
			Handler:    _AttributeService_GetAttribute_Handler,
		},
		{
			MethodName: "ListAttributes",
			Handler:    _AttributeService_ListAttributes_Handler,
		},
		{
			MethodName: "LinkAttributeToCategory",
			Handler:    _AttributeService_LinkAttributeToCategory_Handler,
		},
		{
			MethodName: "UpdateCategoryAttribute",
			Handler:    _AttributeService_UpdateCategoryAttribute_Handler,
		},
		{
			MethodName: "UnlinkAttributeFromCategory",
			Handler:    _AttributeService_UnlinkAttributeFromCategory_Handler,
		},
		{
			MethodName: "GetCategoryAttributes",
			Handler:    _AttributeService_GetCategoryAttributes_Handler,
		},
		{
			MethodName: "GetCategoryVariantAttributes",
			Handler:    _AttributeService_GetCategoryVariantAttributes_Handler,
		},
		{
			MethodName: "GetListingAttributes",
			Handler:    _AttributeService_GetListingAttributes_Handler,
		},
		{
			MethodName: "SetListingAttributes",
			Handler:    _AttributeService_SetListingAttributes_Handler,
		},
		{
			MethodName: "ValidateAttributeValues",
			Handler:    _AttributeService_ValidateAttributeValues_Handler,
		},
		{
			MethodName: "BulkImportAttributes",
			Handler:    _AttributeService_BulkImportAttributes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/attributes/v1/attributes.proto",
}
