// attributes_phase2.proto - Phase 2 Extension for Attribute Service
// Version: v1
// Created: 2025-12-17
// Description: Additional RPC methods for Phase 2 (GetAttributesByCategory, GetAttributeValues)

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: api/proto/attributessvc/v1/attributes_phase2.proto

package attributessvcv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AttributeService_GetAttributesByCategory_FullMethodName = "/attributessvc.v1.AttributeService/GetAttributesByCategory"
	AttributeService_GetAttributeValues_FullMethodName      = "/attributessvc.v1.AttributeService/GetAttributeValues"
)

// AttributeServiceClient is the client API for AttributeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ============================================================================
// AttributeService - Phase 2 Extension
// ============================================================================
type AttributeServiceClient interface {
	// GetAttributesByCategory получает атрибуты для категории (с наследованием)
	GetAttributesByCategory(ctx context.Context, in *GetAttributesByCategoryRequest, opts ...grpc.CallOption) (*GetAttributesByCategoryResponse, error)
	// GetAttributeValues получает предопределённые значения атрибута
	GetAttributeValues(ctx context.Context, in *GetAttributeValuesRequest, opts ...grpc.CallOption) (*GetAttributeValuesResponse, error)
}

type attributeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAttributeServiceClient(cc grpc.ClientConnInterface) AttributeServiceClient {
	return &attributeServiceClient{cc}
}

func (c *attributeServiceClient) GetAttributesByCategory(ctx context.Context, in *GetAttributesByCategoryRequest, opts ...grpc.CallOption) (*GetAttributesByCategoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAttributesByCategoryResponse)
	err := c.cc.Invoke(ctx, AttributeService_GetAttributesByCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *attributeServiceClient) GetAttributeValues(ctx context.Context, in *GetAttributeValuesRequest, opts ...grpc.CallOption) (*GetAttributeValuesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAttributeValuesResponse)
	err := c.cc.Invoke(ctx, AttributeService_GetAttributeValues_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AttributeServiceServer is the server API for AttributeService service.
// All implementations must embed UnimplementedAttributeServiceServer
// for forward compatibility.
//
// ============================================================================
// AttributeService - Phase 2 Extension
// ============================================================================
type AttributeServiceServer interface {
	// GetAttributesByCategory получает атрибуты для категории (с наследованием)
	GetAttributesByCategory(context.Context, *GetAttributesByCategoryRequest) (*GetAttributesByCategoryResponse, error)
	// GetAttributeValues получает предопределённые значения атрибута
	GetAttributeValues(context.Context, *GetAttributeValuesRequest) (*GetAttributeValuesResponse, error)
	mustEmbedUnimplementedAttributeServiceServer()
}

// UnimplementedAttributeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAttributeServiceServer struct{}

func (UnimplementedAttributeServiceServer) GetAttributesByCategory(context.Context, *GetAttributesByCategoryRequest) (*GetAttributesByCategoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAttributesByCategory not implemented")
}
func (UnimplementedAttributeServiceServer) GetAttributeValues(context.Context, *GetAttributeValuesRequest) (*GetAttributeValuesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAttributeValues not implemented")
}
func (UnimplementedAttributeServiceServer) mustEmbedUnimplementedAttributeServiceServer() {}
func (UnimplementedAttributeServiceServer) testEmbeddedByValue()                          {}

// UnsafeAttributeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AttributeServiceServer will
// result in compilation errors.
type UnsafeAttributeServiceServer interface {
	mustEmbedUnimplementedAttributeServiceServer()
}

func RegisterAttributeServiceServer(s grpc.ServiceRegistrar, srv AttributeServiceServer) {
	// If the following call panics, it indicates UnimplementedAttributeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AttributeService_ServiceDesc, srv)
}

func _AttributeService_GetAttributesByCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAttributesByCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttributeServiceServer).GetAttributesByCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttributeService_GetAttributesByCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttributeServiceServer).GetAttributesByCategory(ctx, req.(*GetAttributesByCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AttributeService_GetAttributeValues_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAttributeValuesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttributeServiceServer).GetAttributeValues(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttributeService_GetAttributeValues_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttributeServiceServer).GetAttributeValues(ctx, req.(*GetAttributeValuesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AttributeService_ServiceDesc is the grpc.ServiceDesc for AttributeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AttributeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "attributessvc.v1.AttributeService",
	HandlerType: (*AttributeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAttributesByCategory",
			Handler:    _AttributeService_GetAttributesByCategory_Handler,
		},
		{
			MethodName: "GetAttributeValues",
			Handler:    _AttributeService_GetAttributeValues_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/attributessvc/v1/attributes_phase2.proto",
}
