version: 2

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - misspell
    - revive

linters-settings:
  errcheck:
    check-blank: true

  revive:
    rules:
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: blank-imports
      - name: context-as-argument
      - name: dot-imports

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - errcheck
