# golangci-lint configuration for listings microservice
# Documentation: https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  tests: true
  build-tags:
    - integration
  modules-download-mode: readonly
  allow-parallel-runners: true

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

linters:
  disable-all: true
  enable:
    # Default linters
    - errcheck      # Checks for unchecked errors
    - gosimple      # Simplifies code
    - govet         # Reports suspicious constructs
    - ineffassign   # Detects ineffectual assignments
    - staticcheck   # Advanced static analysis
    - unused        # Checks for unused code
    - gofmt         # Checks code formatting

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
    exclude-functions:
      - (*database/sql.Rows).Close
      - (*database/sql.DB).Close

  govet:
    enable-all: true
    disable:
      - shadow    # Can be too strict
      - fieldalignment  # Memory optimization, not critical

  gocyclo:
    min-complexity: 15  # Functions with cyclomatic complexity > 15 are flagged

  dupl:
    threshold: 150  # Minimum token count for duplicate code detection

  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - unnamedResult  # Can be useful for documentation
      - hugeParam      # Can be too strict

  revive:
    severity: warning
    confidence: 0.8
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id

  gosec:
    severity: medium
    confidence: medium
    excludes:
      - G404  # Use of weak random number generator (we use it for non-security purposes)

  stylecheck:
    checks: ["all", "-ST1000", "-ST1003"]  # Disable some overly strict checks
    dot-import-whitelist: []
    initialisms: ["ACL", "API", "ASCII", "CPU", "CSS", "DNS", "EOF", "GUID", "HTML", "HTTP", "HTTPS", "ID", "IP", "JSON", "QPS", "RAM", "RPC", "SLA", "SMTP", "SQL", "SSH", "TCP", "TLS", "TTL", "UDP", "UI", "GID", "UID", "UUID", "URI", "URL", "UTF8", "VM", "XML", "XMPP", "XSRF", "XSS", "SIP", "RTP", "AMQP", "DB", "TS"]

  misspell:
    locale: US

issues:
  uniq-by-line: true
  exclude-dirs:
    - api/proto/listings/v1  # Skip protobuf directory (generated code)
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - gocritic

    # Exclude known issues in generated code
    - path: pkg/grpc/.*\.pb\.go
      linters:
        - all

    # Exclude some staticcheck messages
    - linters:
        - staticcheck
      text: "SA9003:"  # Empty branch

    # Exclude lll issues for long lines with go:generate
    - linters:
        - lll
      source: "^//go:generate "

  # Maximum issues count per linter. Set to 0 to disable.
  max-issues-per-linter: 0

  # Maximum count of issues with the same text. Set to 0 to disable.
  max-same-issues: 0

  # Show only new issues created in git patch with specific commits range
  new: false

  # Fix found issues (if it's supported by the linter)
  fix: false
