# golangci-lint v2 configuration
# Documentation: https://golangci-lint.run/docs/configuration/

version: "2"

run:
  timeout: 5m
  build-tags:
    - integration

linters:
  default: none
  enable:
    - ineffassign
    - unused
  exclusions:
    paths:
      - "api/proto/.*"
