version: "2"

run:
  timeout: 5m
  go: "1.23"

linters:
  enable:
    - govet        # Go vet
    - revive       # Go lint replacement
    - misspell     # Spelling mistakes
    - lll          # Line length limit
    - unused       # Unused code
    - ineffassign  # Ineffectual assignments
    - goconst      # Repeated strings that could be constants
    - gocritic     # Go code critic
    - gosec        # Security issues
    - errcheck     # Unchecked errors

  disable: []

  settings:
    govet:
      enable:
        - assign
        - atomic
        - bools
        - buildtag
        - cgocall
        - composites
        - copylocks
        - errorsas
        - httpresponse
        - loopclosure
        - lostcancel
        - nilfunc
        - printf
        - shift
        - stdmethods
        - structtag
        - tests
        - unmarshal
        - unreachable
        - unsafeptr
        - unusedresult

    revive:
      confidence: 0.8

    misspell:
      locale: US
      ignore-rules:
        - Industrija

    lll:
      line-length: 120

  exclusions:
    paths:
      - testing
    rules:
      # Exclude some linters from running on tests files
      - path: _test\\.go
        linters:
          - gosec
          - lll

      # Exclude generated files
      - path: ".*\\.pb\\.go"
        linters:
          - all

      # Exclude misspell for Serbian word "Industrija" (Industry)
      - text: "`Industrija` is a misspelling of `Industrial`"
        linters:
          - misspell

formatters:
  enable:
    - gofumpt
    - goimports

  settings:
    gofumpt:
      extra-rules: true

    goimports:
      local-prefixes:
        - github.com/sveturs/svetu


