// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: api/proto/variants/v1/variants.proto

package variantspb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VariantService_CreateVariant_FullMethodName           = "/vondi.variants.v1.VariantService/CreateVariant"
	VariantService_GetVariant_FullMethodName              = "/vondi.variants.v1.VariantService/GetVariant"
	VariantService_UpdateVariant_FullMethodName           = "/vondi.variants.v1.VariantService/UpdateVariant"
	VariantService_DeleteVariant_FullMethodName           = "/vondi.variants.v1.VariantService/DeleteVariant"
	VariantService_ListVariants_FullMethodName            = "/vondi.variants.v1.VariantService/ListVariants"
	VariantService_GetVariantBySku_FullMethodName         = "/vondi.variants.v1.VariantService/GetVariantBySku"
	VariantService_FindVariantByAttributes_FullMethodName = "/vondi.variants.v1.VariantService/FindVariantByAttributes"
	VariantService_ReserveStock_FullMethodName            = "/vondi.variants.v1.VariantService/ReserveStock"
	VariantService_ReleaseStock_FullMethodName            = "/vondi.variants.v1.VariantService/ReleaseStock"
	VariantService_ConfirmStockDeduction_FullMethodName   = "/vondi.variants.v1.VariantService/ConfirmStockDeduction"
)

// VariantServiceClient is the client API for VariantService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// VariantService manages product variants and stock operations
type VariantServiceClient interface {
	// CRUD operations
	CreateVariant(ctx context.Context, in *CreateVariantRequest, opts ...grpc.CallOption) (*VariantResponse, error)
	GetVariant(ctx context.Context, in *GetVariantRequest, opts ...grpc.CallOption) (*VariantResponse, error)
	UpdateVariant(ctx context.Context, in *UpdateVariantRequest, opts ...grpc.CallOption) (*VariantResponse, error)
	DeleteVariant(ctx context.Context, in *DeleteVariantRequest, opts ...grpc.CallOption) (*DeleteVariantResponse, error)
	// Query operations
	ListVariants(ctx context.Context, in *ListVariantsRequest, opts ...grpc.CallOption) (*ListVariantsResponse, error)
	GetVariantBySku(ctx context.Context, in *GetVariantBySkuRequest, opts ...grpc.CallOption) (*VariantResponse, error)
	FindVariantByAttributes(ctx context.Context, in *FindVariantByAttributesRequest, opts ...grpc.CallOption) (*VariantResponse, error)
	// Stock operations
	ReserveStock(ctx context.Context, in *ReserveStockRequest, opts ...grpc.CallOption) (*ReserveStockResponse, error)
	ReleaseStock(ctx context.Context, in *ReleaseStockRequest, opts ...grpc.CallOption) (*ReleaseStockResponse, error)
	ConfirmStockDeduction(ctx context.Context, in *ConfirmStockDeductionRequest, opts ...grpc.CallOption) (*ConfirmStockDeductionResponse, error)
}

type variantServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVariantServiceClient(cc grpc.ClientConnInterface) VariantServiceClient {
	return &variantServiceClient{cc}
}

func (c *variantServiceClient) CreateVariant(ctx context.Context, in *CreateVariantRequest, opts ...grpc.CallOption) (*VariantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VariantResponse)
	err := c.cc.Invoke(ctx, VariantService_CreateVariant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *variantServiceClient) GetVariant(ctx context.Context, in *GetVariantRequest, opts ...grpc.CallOption) (*VariantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VariantResponse)
	err := c.cc.Invoke(ctx, VariantService_GetVariant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *variantServiceClient) UpdateVariant(ctx context.Context, in *UpdateVariantRequest, opts ...grpc.CallOption) (*VariantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VariantResponse)
	err := c.cc.Invoke(ctx, VariantService_UpdateVariant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *variantServiceClient) DeleteVariant(ctx context.Context, in *DeleteVariantRequest, opts ...grpc.CallOption) (*DeleteVariantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteVariantResponse)
	err := c.cc.Invoke(ctx, VariantService_DeleteVariant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *variantServiceClient) ListVariants(ctx context.Context, in *ListVariantsRequest, opts ...grpc.CallOption) (*ListVariantsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListVariantsResponse)
	err := c.cc.Invoke(ctx, VariantService_ListVariants_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *variantServiceClient) GetVariantBySku(ctx context.Context, in *GetVariantBySkuRequest, opts ...grpc.CallOption) (*VariantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VariantResponse)
	err := c.cc.Invoke(ctx, VariantService_GetVariantBySku_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *variantServiceClient) FindVariantByAttributes(ctx context.Context, in *FindVariantByAttributesRequest, opts ...grpc.CallOption) (*VariantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VariantResponse)
	err := c.cc.Invoke(ctx, VariantService_FindVariantByAttributes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *variantServiceClient) ReserveStock(ctx context.Context, in *ReserveStockRequest, opts ...grpc.CallOption) (*ReserveStockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReserveStockResponse)
	err := c.cc.Invoke(ctx, VariantService_ReserveStock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *variantServiceClient) ReleaseStock(ctx context.Context, in *ReleaseStockRequest, opts ...grpc.CallOption) (*ReleaseStockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseStockResponse)
	err := c.cc.Invoke(ctx, VariantService_ReleaseStock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *variantServiceClient) ConfirmStockDeduction(ctx context.Context, in *ConfirmStockDeductionRequest, opts ...grpc.CallOption) (*ConfirmStockDeductionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfirmStockDeductionResponse)
	err := c.cc.Invoke(ctx, VariantService_ConfirmStockDeduction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VariantServiceServer is the server API for VariantService service.
// All implementations must embed UnimplementedVariantServiceServer
// for forward compatibility.
//
// VariantService manages product variants and stock operations
type VariantServiceServer interface {
	// CRUD operations
	CreateVariant(context.Context, *CreateVariantRequest) (*VariantResponse, error)
	GetVariant(context.Context, *GetVariantRequest) (*VariantResponse, error)
	UpdateVariant(context.Context, *UpdateVariantRequest) (*VariantResponse, error)
	DeleteVariant(context.Context, *DeleteVariantRequest) (*DeleteVariantResponse, error)
	// Query operations
	ListVariants(context.Context, *ListVariantsRequest) (*ListVariantsResponse, error)
	GetVariantBySku(context.Context, *GetVariantBySkuRequest) (*VariantResponse, error)
	FindVariantByAttributes(context.Context, *FindVariantByAttributesRequest) (*VariantResponse, error)
	// Stock operations
	ReserveStock(context.Context, *ReserveStockRequest) (*ReserveStockResponse, error)
	ReleaseStock(context.Context, *ReleaseStockRequest) (*ReleaseStockResponse, error)
	ConfirmStockDeduction(context.Context, *ConfirmStockDeductionRequest) (*ConfirmStockDeductionResponse, error)
	mustEmbedUnimplementedVariantServiceServer()
}

// UnimplementedVariantServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVariantServiceServer struct{}

func (UnimplementedVariantServiceServer) CreateVariant(context.Context, *CreateVariantRequest) (*VariantResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateVariant not implemented")
}
func (UnimplementedVariantServiceServer) GetVariant(context.Context, *GetVariantRequest) (*VariantResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVariant not implemented")
}
func (UnimplementedVariantServiceServer) UpdateVariant(context.Context, *UpdateVariantRequest) (*VariantResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateVariant not implemented")
}
func (UnimplementedVariantServiceServer) DeleteVariant(context.Context, *DeleteVariantRequest) (*DeleteVariantResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteVariant not implemented")
}
func (UnimplementedVariantServiceServer) ListVariants(context.Context, *ListVariantsRequest) (*ListVariantsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListVariants not implemented")
}
func (UnimplementedVariantServiceServer) GetVariantBySku(context.Context, *GetVariantBySkuRequest) (*VariantResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVariantBySku not implemented")
}
func (UnimplementedVariantServiceServer) FindVariantByAttributes(context.Context, *FindVariantByAttributesRequest) (*VariantResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FindVariantByAttributes not implemented")
}
func (UnimplementedVariantServiceServer) ReserveStock(context.Context, *ReserveStockRequest) (*ReserveStockResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReserveStock not implemented")
}
func (UnimplementedVariantServiceServer) ReleaseStock(context.Context, *ReleaseStockRequest) (*ReleaseStockResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReleaseStock not implemented")
}
func (UnimplementedVariantServiceServer) ConfirmStockDeduction(context.Context, *ConfirmStockDeductionRequest) (*ConfirmStockDeductionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfirmStockDeduction not implemented")
}
func (UnimplementedVariantServiceServer) mustEmbedUnimplementedVariantServiceServer() {}
func (UnimplementedVariantServiceServer) testEmbeddedByValue()                        {}

// UnsafeVariantServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VariantServiceServer will
// result in compilation errors.
type UnsafeVariantServiceServer interface {
	mustEmbedUnimplementedVariantServiceServer()
}

func RegisterVariantServiceServer(s grpc.ServiceRegistrar, srv VariantServiceServer) {
	// If the following call panics, it indicates UnimplementedVariantServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VariantService_ServiceDesc, srv)
}

func _VariantService_CreateVariant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVariantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VariantServiceServer).CreateVariant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VariantService_CreateVariant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VariantServiceServer).CreateVariant(ctx, req.(*CreateVariantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VariantService_GetVariant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVariantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VariantServiceServer).GetVariant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VariantService_GetVariant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VariantServiceServer).GetVariant(ctx, req.(*GetVariantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VariantService_UpdateVariant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateVariantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VariantServiceServer).UpdateVariant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VariantService_UpdateVariant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VariantServiceServer).UpdateVariant(ctx, req.(*UpdateVariantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VariantService_DeleteVariant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteVariantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VariantServiceServer).DeleteVariant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VariantService_DeleteVariant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VariantServiceServer).DeleteVariant(ctx, req.(*DeleteVariantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VariantService_ListVariants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVariantsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VariantServiceServer).ListVariants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VariantService_ListVariants_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VariantServiceServer).ListVariants(ctx, req.(*ListVariantsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VariantService_GetVariantBySku_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVariantBySkuRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VariantServiceServer).GetVariantBySku(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VariantService_GetVariantBySku_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VariantServiceServer).GetVariantBySku(ctx, req.(*GetVariantBySkuRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VariantService_FindVariantByAttributes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindVariantByAttributesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VariantServiceServer).FindVariantByAttributes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VariantService_FindVariantByAttributes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VariantServiceServer).FindVariantByAttributes(ctx, req.(*FindVariantByAttributesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VariantService_ReserveStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReserveStockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VariantServiceServer).ReserveStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VariantService_ReserveStock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VariantServiceServer).ReserveStock(ctx, req.(*ReserveStockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VariantService_ReleaseStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseStockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VariantServiceServer).ReleaseStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VariantService_ReleaseStock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VariantServiceServer).ReleaseStock(ctx, req.(*ReleaseStockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VariantService_ConfirmStockDeduction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmStockDeductionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VariantServiceServer).ConfirmStockDeduction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VariantService_ConfirmStockDeduction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VariantServiceServer).ConfirmStockDeduction(ctx, req.(*ConfirmStockDeductionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VariantService_ServiceDesc is the grpc.ServiceDesc for VariantService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VariantService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vondi.variants.v1.VariantService",
	HandlerType: (*VariantServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateVariant",
			Handler:    _VariantService_CreateVariant_Handler,
		},
		{
			MethodName: "GetVariant",
			Handler:    _VariantService_GetVariant_Handler,
		},
		{
			MethodName: "UpdateVariant",
			Handler:    _VariantService_UpdateVariant_Handler,
		},
		{
			MethodName: "DeleteVariant",
			Handler:    _VariantService_DeleteVariant_Handler,
		},
		{
			MethodName: "ListVariants",
			Handler:    _VariantService_ListVariants_Handler,
		},
		{
			MethodName: "GetVariantBySku",
			Handler:    _VariantService_GetVariantBySku_Handler,
		},
		{
			MethodName: "FindVariantByAttributes",
			Handler:    _VariantService_FindVariantByAttributes_Handler,
		},
		{
			MethodName: "ReserveStock",
			Handler:    _VariantService_ReserveStock_Handler,
		},
		{
			MethodName: "ReleaseStock",
			Handler:    _VariantService_ReleaseStock_Handler,
		},
		{
			MethodName: "ConfirmStockDeduction",
			Handler:    _VariantService_ConfirmStockDeduction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/variants/v1/variants.proto",
}
