COMMENT ON TABLE public.category_detections IS 'Tracking детекций категорий для анализа и улучшения алгоритма';
COMMENT ON TABLE public.category_variant_attributes IS 'Variant-specific attribute configurations per category';
COMMENT ON TABLE public.chat_attachments IS 'File attachments for chat messages (images, videos, documents)';
COMMENT ON COLUMN public.chat_attachments.id IS 'Primary key';
COMMENT ON COLUMN public.chat_attachments.message_id IS 'Reference to parent message';
COMMENT ON COLUMN public.chat_attachments.file_type IS 'Type of file: image, video, or document';
COMMENT ON COLUMN public.chat_attachments.file_name IS 'Original filename (max 255 chars)';
COMMENT ON COLUMN public.chat_attachments.file_size IS 'File size in bytes (limits: 10MB images, 50MB videos, 20MB docs)';
COMMENT ON COLUMN public.chat_attachments.content_type IS 'MIME type (e.g., image/jpeg, application/pdf)';
COMMENT ON COLUMN public.chat_attachments.storage_type IS 'Storage backend: minio, s3, or local';
COMMENT ON COLUMN public.chat_attachments.storage_bucket IS 'Storage bucket/container name';
COMMENT ON COLUMN public.chat_attachments.file_path IS 'Path to file in storage (max 500 chars)';
COMMENT ON COLUMN public.chat_attachments.public_url IS 'Public URL to access file (if available)';
COMMENT ON COLUMN public.chat_attachments.thumbnail_url IS 'Thumbnail URL for images/videos (if generated)';
COMMENT ON COLUMN public.chat_attachments.metadata IS 'Additional metadata in JSON format (dimensions, duration, etc.)';
COMMENT ON COLUMN public.chat_attachments.created_at IS 'When attachment was uploaded';
COMMENT ON TABLE public.chats IS 'Conversations between buyers and sellers. Can be about a specific listing, storefront product, or direct chat';
COMMENT ON COLUMN public.chats.id IS 'Primary key';
COMMENT ON COLUMN public.chats.buyer_id IS 'User who initiated the chat (references users in Auth Service)';
COMMENT ON COLUMN public.chats.seller_id IS 'User who receives the chat (references users in Auth Service)';
COMMENT ON COLUMN public.chats.listing_id IS 'Optional: Marketplace listing being discussed (references listings table)';
COMMENT ON COLUMN public.chats.storefront_product_id IS 'Optional: Storefront product being discussed (references storefront_products table)';
COMMENT ON COLUMN public.chats.status IS 'Chat status: active, archived, or blocked';
COMMENT ON COLUMN public.chats.is_archived IS 'Whether chat is archived by current user (UI state)';
COMMENT ON COLUMN public.chats.last_message_at IS 'Timestamp of last message (for sorting)';
COMMENT ON COLUMN public.chats.created_at IS 'When chat was created';
COMMENT ON COLUMN public.chats.updated_at IS 'Last update timestamp';
COMMENT ON TABLE public.inventory_reservations IS 'Temporary stock holds for pending orders. Prevents overselling during checkout. Auto-expires after 30 min.
Available stock calculation:
  available = listings.stock - SUM(reservations.quantity WHERE status = ''active'' AND expires_at > NOW())
Example cleanup job (run every 5 minutes):
  UPDATE inventory_reservations
COMMENT ON COLUMN public.inventory_reservations.listing_id IS 'Product listing being reserved. Always required.';
COMMENT ON COLUMN public.inventory_reservations.variant_id IS 'Product variant (optional). For products with size/color/etc variants. NULL for simple products.';
COMMENT ON COLUMN public.inventory_reservations.reference_id IS 'Order this reservation belongs to. NULL until order created. SET NULL if order deleted.';
COMMENT ON COLUMN public.inventory_reservations.quantity IS 'Number of items reserved. Must be > 0. Deducted from available stock.';
COMMENT ON COLUMN public.inventory_reservations.status IS 'Lifecycle: active (pending) → committed (paid) or released (timeout/cancel) or expired (cleanup job).';
COMMENT ON COLUMN public.inventory_reservations.expires_at IS 'When reservation expires. Default: NOW() + 30 minutes. Cleanup job runs every 5 minutes.';
COMMENT ON COLUMN public.inventory_reservations.created_at IS 'When reservation was created (e.g., when user starts checkout).';
COMMENT ON COLUMN public.inventory_reservations.updated_at IS 'Last status change (active → committed/released/expired).';
COMMENT ON COLUMN public.inventory_reservations.committed_at IS 'Timestamp when reservation was committed (order confirmed)';
COMMENT ON COLUMN public.inventory_reservations.released_at IS 'Timestamp when reservation was released (order cancelled or expired)';
COMMENT ON TABLE public.listing_attribute_values IS 'Attribute values for listings - polymorphic storage';
COMMENT ON TABLE public.listing_variants IS 'Product variants for listings (size, color, etc.)';
COMMENT ON COLUMN public.listing_variants.attributes IS 'JSON object with variant attributes, e.g., {"color": "red", "size": "M"}';
COMMENT ON COLUMN public.listing_variants.price IS 'Variant-specific price, NULL means use listing base price';
COMMENT ON COLUMN public.listing_variants.stock IS 'Available stock for this specific variant';
COMMENT ON COLUMN public.listing_variants.image_url IS 'Optional variant-specific image';
COMMENT ON TABLE public.messages IS 'Individual messages in chats between buyers and sellers';
COMMENT ON COLUMN public.messages.id IS 'Primary key, used for cursor pagination';
COMMENT ON COLUMN public.messages.chat_id IS 'Reference to parent chat';
COMMENT ON COLUMN public.messages.sender_id IS 'User who sent the message (references users in Auth Service)';
COMMENT ON COLUMN public.messages.receiver_id IS 'User who receives the message (references users in Auth Service)';
COMMENT ON COLUMN public.messages.content IS 'Message text (1-10000 characters)';
COMMENT ON COLUMN public.messages.original_language IS 'ISO 639-1 language code (en, ru, sr, etc.)';
COMMENT ON COLUMN public.messages.listing_id IS 'Optional: Listing being discussed (if different from chat context)';
COMMENT ON COLUMN public.messages.storefront_product_id IS 'Optional: Product being discussed (if different from chat context)';
COMMENT ON COLUMN public.messages.status IS 'Delivery status: sent, delivered, read, or failed';
COMMENT ON COLUMN public.messages.is_read IS 'Whether message has been read by receiver';
COMMENT ON COLUMN public.messages.has_attachments IS 'Quick check if message has attachments';
COMMENT ON COLUMN public.messages.attachments_count IS 'Number of attachments (for UI display)';
COMMENT ON COLUMN public.messages.created_at IS 'When message was created';
COMMENT ON COLUMN public.messages.updated_at IS 'Last update timestamp';
COMMENT ON COLUMN public.messages.read_at IS 'When message was read by receiver (null if unread)';
COMMENT ON COLUMN public.messages.is_system IS 'Flag indicating if message is from the marketplace system (e.g., order notifications)';
COMMENT ON TABLE public.order_items IS 'Snapshot of purchased products. Immutable historical record preserved even if listing is deleted.';
COMMENT ON COLUMN public.order_items.order_id IS 'Order this item belongs to. Items cascade-deleted when order is deleted.';
COMMENT ON COLUMN public.order_items.listing_id IS 'Reference to listing (for analytics). Listing may be deleted, rely on snapshot data.';
COMMENT ON COLUMN public.order_items.variant_id IS 'ID варианта товара из listings microservice (UUID string)';
COMMENT ON COLUMN public.order_items.listing_name IS 'Product name at order time. Preserved even if listing renamed or deleted.';
COMMENT ON COLUMN public.order_items.sku IS 'Product SKU at order time. For inventory reconciliation and seller tracking.';
COMMENT ON COLUMN public.order_items.variant_data IS 'JSONB snapshot of variant attributes: { size: "L", color: "Red", material: "Cotton", ... }';
COMMENT ON COLUMN public.order_items.attributes IS 'JSONB snapshot of full product attributes at order time. Preserves exact product state.';
COMMENT ON COLUMN public.order_items.quantity IS 'Number of items purchased. Immutable after order creation.';
COMMENT ON COLUMN public.order_items.price IS 'Price per unit at order time. Frozen at checkout, not affected by future price changes.';
COMMENT ON COLUMN public.order_items.total IS 'Total for this line item: price * quantity. Immutable after order creation.';
COMMENT ON COLUMN public.order_items.created_at IS 'When order item was created. No updated_at - order items never change after creation.';
COMMENT ON COLUMN public.order_items.subtotal IS 'Subtotal before discount (quantity * unit_price)';
COMMENT ON COLUMN public.order_items.discount IS 'Item-level discount amount';
COMMENT ON COLUMN public.order_items.image_url IS 'Snapshot of primary image URL at purchase time';
COMMENT ON COLUMN public.order_items.stock_reservation_id IS 'ID резервации стока для данного item (UUID string)';
COMMENT ON TABLE public.product_variants IS 'Product variants with unique SKU, pricing, and inventory';
COMMENT ON COLUMN public.product_variants.product_id IS 'Reference to parent product (foreign key added later)';
COMMENT ON COLUMN public.product_variants.sku IS 'Stock Keeping Unit - unique identifier for this variant';
COMMENT ON COLUMN public.product_variants.price IS 'Variant-specific price (NULL = use product base_price)';
COMMENT ON COLUMN public.product_variants.compare_at_price IS 'Original price for discount display';
COMMENT ON COLUMN public.product_variants.stock_quantity IS 'Total available stock';
COMMENT ON COLUMN public.product_variants.reserved_quantity IS 'Stock reserved in active orders';
COMMENT ON COLUMN public.product_variants.low_stock_alert IS 'Threshold for low stock notifications';
COMMENT ON COLUMN public.product_variants.weight_grams IS 'Variant weight in grams';
COMMENT ON COLUMN public.product_variants.barcode IS 'EAN/UPC barcode';
COMMENT ON COLUMN public.product_variants.is_default IS 'Default variant for product (only one allowed)';
COMMENT ON COLUMN public.product_variants."position" IS 'Display order for variant selector';
COMMENT ON COLUMN public.product_variants.status IS 'Variant status: active, out_of_stock, discontinued';
COMMENT ON TABLE public.search_queries IS 'Analytics tracking for all search queries. Used for trending searches, user history, and CTR analysis. No soft delete (append-only log).';
COMMENT ON COLUMN public.search_queries.query_text IS 'Search query text entered by user. Max 500 chars. Indexed for aggregations and full-text similarity.';
COMMENT ON COLUMN public.search_queries.category_id IS 'Optional category context. NULL means global search. Used for category-specific trending queries.';
COMMENT ON COLUMN public.search_queries.user_id IS 'Authenticated user ID (FK to auth service). Mutually exclusive with session_id (or both for migration).';
COMMENT ON COLUMN public.search_queries.session_id IS 'Anonymous user session ID (UUID from cookie). Mutually exclusive with user_id (or both for migration).';
COMMENT ON COLUMN public.search_queries.results_count IS 'Number of results returned by search. Used to filter out empty searches from trending calculations.';
COMMENT ON COLUMN public.search_queries.clicked_listing_id IS 'ID of listing clicked from search results. NULL if no click. Used for CTR (Click-Through Rate) analysis.';
COMMENT ON COLUMN public.search_queries.created_at IS 'Timestamp when search was performed. Primary field for time-based aggregations and retention policy.';
COMMENT ON TABLE public.shopping_carts IS 'Shopping carts for authenticated and anonymous users. One cart per user/session per storefront.';
COMMENT ON COLUMN public.shopping_carts.user_id IS 'Authenticated user ID (FK to auth service). Mutually exclusive with session_id.';
