CREATE INDEX idx_attribute_values_attribute_id ON public.attribute_values USING btree (attribute_id);
CREATE INDEX idx_attribute_values_label_gin ON public.attribute_values USING gin (label);
CREATE INDEX idx_attribute_values_metadata_gin ON public.attribute_values USING gin (metadata);
CREATE INDEX idx_attribute_values_sort ON public.attribute_values USING btree (attribute_id, sort_order, value);
CREATE INDEX idx_attributes_active ON public.attributes USING btree (is_active) WHERE (is_active = true);
CREATE INDEX idx_attributes_active_filterable ON public.attributes USING btree (is_active, is_filterable) WHERE ((is_active = true) AND (is_filterable = true));
CREATE INDEX idx_attributes_active_searchable ON public.attributes USING btree (is_active, is_searchable) WHERE ((is_active = true) AND (is_searchable = true));
CREATE INDEX idx_attributes_active_sort ON public.attributes USING btree (is_active, sort_order, ((name ->> 'en'::text))) WHERE (is_active = true);
CREATE INDEX idx_attributes_code ON public.attributes USING btree (code);
CREATE INDEX idx_attributes_purpose ON public.attributes USING btree (purpose);
CREATE INDEX idx_attributes_search_vector ON public.attributes USING gin (search_vector);
CREATE INDEX idx_attributes_show_in_card ON public.attributes USING btree (show_in_card) WHERE (show_in_card = true);
CREATE INDEX idx_brand_mapping_aliases ON public.brand_category_mapping USING gin (brand_aliases);
CREATE INDEX idx_brand_mapping_name ON public.brand_category_mapping USING btree (lower((brand_name)::text));
CREATE INDEX idx_brand_mapping_verified ON public.brand_category_mapping USING btree (is_verified) WHERE (is_verified = true);
CREATE INDEX idx_cart_items_cart_id ON public.cart_items USING btree (cart_id);
CREATE INDEX idx_cart_items_listing_id ON public.cart_items USING btree (listing_id);
CREATE UNIQUE INDEX idx_cart_items_unique_per_cart ON public.cart_items USING btree (cart_id, listing_id, COALESCE(variant_id, (0)::bigint));
CREATE INDEX idx_cart_items_variant_id ON public.cart_items USING btree (variant_id) WHERE (variant_id IS NOT NULL);
CREATE INDEX idx_categories_description_gin ON public.categories USING gin (description jsonb_path_ops);
CREATE INDEX idx_categories_level ON public.categories USING btree (level);
CREATE INDEX idx_categories_meta_keywords_en_fts ON public.categories USING gin (to_tsvector('simple'::regconfig, COALESCE((meta_keywords ->> 'en'::text), ''::text)));
CREATE INDEX idx_categories_meta_keywords_ru_fts ON public.categories USING gin (to_tsvector('simple'::regconfig, COALESCE((meta_keywords ->> 'ru'::text), ''::text)));
CREATE INDEX idx_categories_meta_keywords_sr_fts ON public.categories USING gin (to_tsvector('simple'::regconfig, COALESCE((meta_keywords ->> 'sr'::text), ''::text)));
CREATE INDEX idx_categories_name_en_trgm ON public.categories USING gin (((name ->> 'en'::text)) public.gin_trgm_ops);
CREATE INDEX idx_categories_name_gin ON public.categories USING gin (name jsonb_path_ops);
CREATE INDEX idx_categories_name_sr_trgm ON public.categories USING gin (((name ->> 'sr'::text)) public.gin_trgm_ops);
CREATE INDEX idx_categories_parent_id ON public.categories USING btree (parent_id) WHERE (parent_id IS NOT NULL);
CREATE INDEX idx_categories_slug ON public.categories USING btree (slug);
CREATE INDEX idx_categories_sort_order ON public.categories USING btree (parent_id, sort_order) WHERE (parent_id IS NOT NULL);
CREATE INDEX idx_category_attributes_attribute ON public.category_attributes USING btree (attribute_id);
CREATE INDEX idx_category_attributes_category ON public.category_attributes USING btree (category_id);
CREATE INDEX idx_category_attributes_enabled ON public.category_attributes USING btree (is_enabled);
CREATE INDEX idx_category_attributes_filterable ON public.category_attributes USING btree (category_id, is_filterable) WHERE (is_filterable = true);
CREATE INDEX idx_category_attributes_searchable ON public.category_attributes USING btree (category_id, is_searchable) WHERE (is_searchable = true);
CREATE INDEX idx_category_attrs_composite ON public.category_attributes USING btree (category_id, attribute_id, is_enabled, sort_order) WHERE (is_enabled = true);
CREATE INDEX idx_category_attrs_covering ON public.category_attributes USING btree (category_id, is_enabled, attribute_id, sort_order, is_required) WHERE (is_enabled = true);
CREATE INDEX idx_category_detections_created_at ON public.category_detections USING btree (created_at DESC);
CREATE INDEX idx_category_detections_detected_category ON public.category_detections USING btree (detected_category_id);
CREATE INDEX idx_category_detections_method ON public.category_detections USING btree (detection_method);
CREATE INDEX idx_category_detections_user_confirmed ON public.category_detections USING btree (user_confirmed) WHERE (user_confirmed IS NOT NULL);
CREATE INDEX idx_category_variant_attrs_active ON public.category_variant_attributes USING btree (is_active, category_id) WHERE (is_active = true);
CREATE INDEX idx_category_variant_attrs_attribute ON public.category_variant_attributes USING btree (attribute_id);
CREATE INDEX idx_category_variant_attrs_category ON public.category_variant_attributes USING btree (category_id);
CREATE INDEX idx_chats_buyer_active_recent ON public.chats USING btree (buyer_id, last_message_at DESC) WHERE ((NOT is_archived) AND ((status)::text = 'active'::text));
CREATE INDEX idx_chats_buyer_id ON public.chats USING btree (buyer_id);
CREATE UNIQUE INDEX idx_chats_direct_participants_unique ON public.chats USING btree (LEAST(buyer_id, seller_id), GREATEST(buyer_id, seller_id)) WHERE ((listing_id IS NULL) AND (storefront_product_id IS NULL));
CREATE INDEX idx_chats_is_archived ON public.chats USING btree (is_archived) WHERE (NOT is_archived);
CREATE INDEX idx_chats_last_message_at ON public.chats USING btree (last_message_at DESC) WHERE (NOT is_archived);
CREATE INDEX idx_chats_listing_id ON public.chats USING btree (listing_id) WHERE (listing_id IS NOT NULL);
CREATE INDEX idx_chats_seller_active_recent ON public.chats USING btree (seller_id, last_message_at DESC) WHERE ((NOT is_archived) AND ((status)::text = 'active'::text));
CREATE INDEX idx_chats_seller_id ON public.chats USING btree (seller_id);
CREATE INDEX idx_chats_storefront_product_id ON public.chats USING btree (storefront_product_id) WHERE (storefront_product_id IS NOT NULL);
CREATE INDEX idx_indexing_queue_created_at ON public.indexing_queue USING btree (created_at);
CREATE UNIQUE INDEX idx_indexing_queue_listing_id_pending ON public.indexing_queue USING btree (listing_id) WHERE ((status)::text = 'pending'::text);
CREATE INDEX idx_indexing_queue_status ON public.indexing_queue USING btree (status) WHERE ((status)::text <> 'completed'::text);
CREATE INDEX idx_inventory_movements_created_at ON public.inventory_movements USING btree (created_at DESC);
CREATE INDEX idx_inventory_movements_listing_id ON public.inventory_movements USING btree (listing_id);
CREATE INDEX idx_inventory_movements_movement_type ON public.inventory_movements USING btree (movement_type);
CREATE INDEX idx_inventory_movements_user_id ON public.inventory_movements USING btree (user_id) WHERE (user_id IS NOT NULL);
CREATE INDEX idx_inventory_reservations_committed_at ON public.inventory_reservations USING btree (committed_at) WHERE (committed_at IS NOT NULL);
CREATE INDEX idx_inventory_reservations_expires_at ON public.inventory_reservations USING btree (expires_at, status) WHERE ((status)::text = 'active'::text);
CREATE INDEX idx_inventory_reservations_listing_id ON public.inventory_reservations USING btree (listing_id);
CREATE INDEX idx_inventory_reservations_listing_status ON public.inventory_reservations USING btree (listing_id, status) WHERE ((status)::text = 'active'::text);
CREATE INDEX idx_inventory_reservations_ref_status ON public.inventory_reservations USING btree (reference_type, reference_id, status) WHERE ((status)::text = 'active'::text);
CREATE INDEX idx_inventory_reservations_reference ON public.inventory_reservations USING btree (reference_type, reference_id);
CREATE INDEX idx_inventory_reservations_released_at ON public.inventory_reservations USING btree (released_at) WHERE (released_at IS NOT NULL);
CREATE INDEX idx_inventory_reservations_variant_status ON public.inventory_reservations USING btree (variant_id, status) WHERE (((status)::text = 'active'::text) AND (variant_id IS NOT NULL));
CREATE INDEX idx_listing_attr_values_attribute ON public.listing_attribute_values USING btree (attribute_id);
CREATE INDEX idx_listing_attr_values_entity_with_type ON public.listing_attribute_values USING btree (listing_id, attribute_id) INCLUDE (value_text, value_number, value_boolean, value_date);
CREATE INDEX idx_listing_attr_values_listing ON public.listing_attribute_values USING btree (listing_id);
CREATE INDEX idx_listing_attr_values_number ON public.listing_attribute_values USING btree (value_number) WHERE (value_number IS NOT NULL);
CREATE INDEX idx_listing_attr_values_numeric_ranges ON public.listing_attribute_values USING btree (attribute_id, value_number) WHERE (value_number IS NOT NULL);
CREATE INDEX idx_listing_attr_values_text ON public.listing_attribute_values USING btree (value_text) WHERE (value_text IS NOT NULL);
CREATE INDEX idx_listing_attributes_key ON public.listing_attributes USING btree (attribute_key);
CREATE INDEX idx_listing_attributes_listing_id ON public.listing_attributes USING btree (listing_id);
CREATE INDEX idx_listing_favorites_listing_id ON public.listing_favorites USING btree (listing_id);
CREATE INDEX idx_listing_favorites_user_id ON public.listing_favorites USING btree (user_id);
CREATE INDEX idx_listing_images_display_order ON public.listing_images USING btree (listing_id, display_order);
CREATE INDEX idx_listing_images_listing_id ON public.listing_images USING btree (listing_id);
CREATE INDEX idx_listing_locations_geo ON public.listing_locations USING btree (latitude, longitude) WHERE ((latitude IS NOT NULL) AND (longitude IS NOT NULL));
CREATE INDEX idx_listing_tags_listing_id ON public.listing_tags USING btree (listing_id);
CREATE INDEX idx_listing_tags_tag ON public.listing_tags USING btree (tag);
CREATE INDEX idx_listing_variants_active ON public.listing_variants USING btree (listing_id) WHERE (is_active = true);
CREATE INDEX idx_listing_variants_attributes ON public.listing_variants USING gin (attributes);
CREATE INDEX idx_listing_variants_listing ON public.listing_variants USING btree (listing_id);
CREATE INDEX idx_listing_variants_sku ON public.listing_variants USING btree (sku) WHERE (sku IS NOT NULL);
CREATE UNIQUE INDEX idx_listing_variants_unique_attrs ON public.listing_variants USING btree (listing_id, md5((attributes)::text));
CREATE INDEX idx_listings_attributes ON public.listings USING gin (attributes);
CREATE INDEX idx_listings_category_id ON public.listings USING btree (category_id) WHERE ((category_id IS NOT NULL) AND (is_deleted = false));
CREATE INDEX idx_listings_created_at ON public.listings USING btree (created_at DESC) WHERE (is_deleted = false);
CREATE INDEX idx_listings_description_translations ON public.listings USING gin (description_translations);
CREATE INDEX idx_listings_expires_at ON public.listings USING btree (expires_at) WHERE ((expires_at IS NOT NULL) AND (is_deleted = false));
CREATE INDEX idx_listings_has_variants ON public.listings USING btree (has_variants) WHERE (has_variants = true);
CREATE INDEX idx_listings_original_language ON public.listings USING btree (original_language);
CREATE INDEX idx_listings_price ON public.listings USING btree (price) WHERE (is_deleted = false);
CREATE INDEX idx_listings_search ON public.listings USING gin (to_tsvector('english'::regconfig, (((title)::text || ' '::text) || COALESCE(description, ''::text))));
CREATE UNIQUE INDEX idx_listings_slug ON public.listings USING btree (slug) WHERE (is_deleted = false);
CREATE INDEX idx_listings_sold_count ON public.listings USING btree (sold_count DESC) WHERE (is_deleted = false);
CREATE INDEX idx_listings_source_type ON public.listings USING btree (source_type) WHERE (is_deleted = false);
