CREATE INDEX idx_listings_status ON public.listings USING btree (status) WHERE (is_deleted = false);
CREATE INDEX idx_listings_status_expires_at ON public.listings USING btree (status, expires_at) WHERE ((is_deleted = false) AND (expires_at IS NOT NULL));
CREATE INDEX idx_listings_stock_status ON public.listings USING btree (stock_status) WHERE (is_deleted = false);
CREATE INDEX idx_listings_storefront_id ON public.listings USING btree (storefront_id) WHERE (is_deleted = false);
CREATE INDEX idx_listings_title_translations ON public.listings USING gin (title_translations);
CREATE INDEX idx_listings_user_id ON public.listings USING btree (user_id) WHERE (is_deleted = false);
CREATE INDEX idx_listings_view_count ON public.listings USING btree (view_count DESC) WHERE (is_deleted = false);
CREATE INDEX idx_messages_chat_id_created ON public.messages USING btree (chat_id, created_at DESC);
CREATE INDEX idx_messages_chat_id_id ON public.messages USING btree (chat_id, id DESC);
CREATE INDEX idx_messages_chat_receiver_unread ON public.messages USING btree (chat_id, receiver_id) WHERE (NOT is_read);
CREATE INDEX idx_messages_created_at ON public.messages USING btree (created_at);
CREATE INDEX idx_messages_has_attachments ON public.messages USING btree (chat_id, has_attachments) WHERE (has_attachments = true);
CREATE INDEX idx_messages_is_system ON public.messages USING btree (is_system) WHERE (is_system = true);
CREATE INDEX idx_messages_receiver_id ON public.messages USING btree (receiver_id);
CREATE INDEX idx_messages_receiver_unread ON public.messages USING btree (receiver_id, is_read) WHERE (NOT is_read);
CREATE INDEX idx_messages_sender_id ON public.messages USING btree (sender_id);
CREATE INDEX idx_order_items_listing_id ON public.order_items USING btree (listing_id);
CREATE INDEX idx_order_items_listing_name ON public.order_items USING gin (to_tsvector('simple'::regconfig, (listing_name)::text));
CREATE INDEX idx_order_items_order_id ON public.order_items USING btree (order_id);
CREATE INDEX idx_order_items_reservation_id ON public.order_items USING btree (stock_reservation_id) WHERE (stock_reservation_id IS NOT NULL);
CREATE INDEX idx_order_items_variant_id ON public.order_items USING btree (variant_id) WHERE (variant_id IS NOT NULL);
CREATE INDEX idx_orders_accepted_at ON public.orders USING btree (accepted_at) WHERE (accepted_at IS NOT NULL);
CREATE INDEX idx_orders_confirmed_at ON public.orders USING btree (confirmed_at) WHERE (confirmed_at IS NOT NULL);
CREATE INDEX idx_orders_created_at_desc ON public.orders USING btree (created_at DESC);
CREATE INDEX idx_orders_customer_email ON public.orders USING btree (customer_email) WHERE (customer_email IS NOT NULL);
CREATE INDEX idx_orders_customer_phone ON public.orders USING btree (customer_phone) WHERE (customer_phone IS NOT NULL);
CREATE INDEX idx_orders_delivered_at ON public.orders USING btree (delivered_at) WHERE (delivered_at IS NOT NULL);
CREATE INDEX idx_orders_escrow_release_date ON public.orders USING btree (escrow_release_date) WHERE ((escrow_release_date IS NOT NULL) AND ((payment_status)::text = 'paid'::text));
CREATE UNIQUE INDEX idx_orders_idempotency_key ON public.orders USING btree (payment_idempotency_key) WHERE (payment_idempotency_key IS NOT NULL);
CREATE INDEX idx_orders_payment_completed_at ON public.orders USING btree (payment_completed_at) WHERE (payment_completed_at IS NOT NULL);
CREATE INDEX idx_orders_payment_intent ON public.orders USING btree (payment_intent_id) WHERE (payment_intent_id IS NOT NULL);
CREATE INDEX idx_orders_payment_status ON public.orders USING btree (payment_status);
CREATE INDEX idx_orders_shipment_id ON public.orders USING btree (shipment_id) WHERE (shipment_id IS NOT NULL);
CREATE INDEX idx_orders_shipped_at ON public.orders USING btree (shipped_at) WHERE (shipped_at IS NOT NULL);
CREATE INDEX idx_orders_shipping_details ON public.orders USING gin (shipping_details);
CREATE INDEX idx_orders_shipping_method_id ON public.orders USING btree (shipping_method_id) WHERE (shipping_method_id IS NOT NULL);
CREATE INDEX idx_orders_shipping_provider ON public.orders USING btree (shipping_provider) WHERE (shipping_provider IS NOT NULL);
CREATE INDEX idx_orders_status ON public.orders USING btree (status);
CREATE INDEX idx_orders_storefront_created_at ON public.orders USING btree (storefront_id, created_at DESC);
CREATE INDEX idx_orders_storefront_id ON public.orders USING btree (storefront_id);
CREATE INDEX idx_orders_user_created_at ON public.orders USING btree (user_id, created_at DESC) WHERE (user_id IS NOT NULL);
CREATE INDEX idx_orders_user_id ON public.orders USING btree (user_id) WHERE (user_id IS NOT NULL);
CREATE INDEX idx_reservations_active ON public.stock_reservations USING btree (variant_id, status, quantity) WHERE ((status)::text = 'active'::text);
CREATE INDEX idx_reservations_composite ON public.stock_reservations USING btree (variant_id, order_id, status);
CREATE INDEX idx_reservations_expires ON public.stock_reservations USING btree (expires_at, status) WHERE ((status)::text = 'active'::text);
CREATE INDEX idx_reservations_order ON public.stock_reservations USING btree (order_id);
CREATE INDEX idx_reservations_variant ON public.stock_reservations USING btree (variant_id, status);
CREATE INDEX idx_search_queries_category_agg ON public.search_queries USING btree (category_id, query_text) WHERE ((category_id IS NOT NULL) AND (results_count > 0));
CREATE INDEX idx_search_queries_created_at ON public.search_queries USING btree (created_at DESC);
CREATE INDEX idx_search_queries_ctr_analysis ON public.search_queries USING btree (clicked_listing_id, created_at DESC) WHERE (clicked_listing_id IS NOT NULL);
CREATE INDEX idx_search_queries_query_text_fts ON public.search_queries USING gin (to_tsvector('english'::regconfig, (query_text)::text));
CREATE INDEX idx_search_queries_session_history ON public.search_queries USING btree (session_id, created_at DESC) WHERE (session_id IS NOT NULL);
CREATE INDEX idx_search_queries_trending ON public.search_queries USING btree (category_id, created_at DESC, query_text) WHERE (results_count > 0);
CREATE INDEX idx_search_queries_user_history ON public.search_queries USING btree (user_id, created_at DESC) WHERE (user_id IS NOT NULL);
CREATE INDEX idx_shopping_carts_storefront_id ON public.shopping_carts USING btree (storefront_id);
CREATE UNIQUE INDEX idx_shopping_carts_unique_session_per_storefront ON public.shopping_carts USING btree (session_id, storefront_id) WHERE (session_id IS NOT NULL);
CREATE UNIQUE INDEX idx_shopping_carts_unique_user_per_storefront ON public.shopping_carts USING btree (user_id, storefront_id) WHERE (user_id IS NOT NULL);
CREATE INDEX idx_shopping_carts_updated_at ON public.shopping_carts USING btree (updated_at);
CREATE INDEX idx_storefront_delivery_options_display_order ON public.storefront_delivery_options USING btree (storefront_id, display_order);
CREATE INDEX idx_storefront_delivery_options_is_active ON public.storefront_delivery_options USING btree (is_active) WHERE (is_active = true);
CREATE INDEX idx_storefront_delivery_options_provider ON public.storefront_delivery_options USING btree (provider) WHERE (provider IS NOT NULL);
CREATE INDEX idx_storefront_delivery_options_storefront_id ON public.storefront_delivery_options USING btree (storefront_id);
CREATE INDEX idx_storefront_events_analytics ON public.storefront_events USING btree (storefront_id, event_type, created_at DESC);
CREATE INDEX idx_storefront_events_created_at ON public.storefront_events USING btree (created_at);
CREATE INDEX idx_storefront_events_event_type ON public.storefront_events USING btree (event_type);
CREATE INDEX idx_storefront_events_session_id ON public.storefront_events USING btree (session_id);
CREATE INDEX idx_storefront_events_storefront_id ON public.storefront_events USING btree (storefront_id);
CREATE INDEX idx_storefront_events_user_id ON public.storefront_events USING btree (user_id) WHERE (user_id IS NOT NULL);
CREATE INDEX idx_storefront_hours_day_of_week ON public.storefront_hours USING btree (day_of_week);
CREATE INDEX idx_storefront_hours_special_date ON public.storefront_hours USING btree (special_date) WHERE (special_date IS NOT NULL);
CREATE INDEX idx_storefront_hours_storefront_id ON public.storefront_hours USING btree (storefront_id);
CREATE INDEX idx_storefront_invitations_email ON public.storefront_invitations USING btree (invited_email) WHERE (invited_email IS NOT NULL);
CREATE INDEX idx_storefront_invitations_expires ON public.storefront_invitations USING btree (expires_at) WHERE ((expires_at IS NOT NULL) AND (status = 'pending'::public.storefront_invitation_status));
CREATE INDEX idx_storefront_invitations_invited_by ON public.storefront_invitations USING btree (invited_by_id);
CREATE INDEX idx_storefront_invitations_status ON public.storefront_invitations USING btree (status);
CREATE INDEX idx_storefront_invitations_storefront ON public.storefront_invitations USING btree (storefront_id);
CREATE INDEX idx_storefront_invitations_user ON public.storefront_invitations USING btree (invited_user_id) WHERE (invited_user_id IS NOT NULL);
CREATE INDEX idx_storefront_payment_methods_is_enabled ON public.storefront_payment_methods USING btree (is_enabled) WHERE (is_enabled = true);
CREATE INDEX idx_storefront_payment_methods_method_type ON public.storefront_payment_methods USING btree (method_type);
CREATE INDEX idx_storefront_payment_methods_storefront_id ON public.storefront_payment_methods USING btree (storefront_id);
CREATE INDEX idx_storefront_staff_role ON public.storefront_staff USING btree (role);
CREATE INDEX idx_storefront_staff_storefront_id ON public.storefront_staff USING btree (storefront_id);
CREATE UNIQUE INDEX idx_storefront_staff_unique_user_per_store ON public.storefront_staff USING btree (storefront_id, user_id);
CREATE INDEX idx_storefront_staff_user_id ON public.storefront_staff USING btree (user_id);
CREATE INDEX idx_storefronts_city ON public.storefronts USING btree (city) WHERE (city IS NOT NULL);
CREATE INDEX idx_storefronts_deleted_at ON public.storefronts USING btree (deleted_at) WHERE (deleted_at IS NULL);
CREATE INDEX idx_storefronts_is_active ON public.storefronts USING btree (is_active) WHERE (is_active = true);
CREATE INDEX idx_storefronts_is_verified ON public.storefronts USING btree (is_verified) WHERE (is_verified = true);
CREATE INDEX idx_storefronts_user_id ON public.storefronts USING btree (user_id);
CREATE INDEX idx_variant_attr_values_attribute ON public.variant_attribute_values USING btree (attribute_id);
CREATE INDEX idx_variant_attr_values_number ON public.variant_attribute_values USING btree (value_number) WHERE (value_number IS NOT NULL);
CREATE INDEX idx_variant_attr_values_text ON public.variant_attribute_values USING btree (value_text) WHERE (value_text IS NOT NULL);
CREATE INDEX idx_variant_attr_values_variant ON public.variant_attribute_values USING btree (variant_id);
CREATE INDEX idx_variant_attrs_composite ON public.variant_attribute_values USING btree (variant_id, attribute_id) INCLUDE (value_text, value_number, value_boolean, value_date);
CREATE INDEX idx_variants_available ON public.product_variants USING btree (product_id, ((stock_quantity - reserved_quantity))) WHERE (((status)::text = 'active'::text) AND ((stock_quantity - reserved_quantity) > 0));
CREATE INDEX idx_variants_barcode ON public.product_variants USING btree (barcode) WHERE (barcode IS NOT NULL);
CREATE INDEX idx_variants_default ON public.product_variants USING btree (product_id) WHERE (is_default = true);
CREATE INDEX idx_variants_low_stock ON public.product_variants USING btree (product_id, stock_quantity, low_stock_alert) WHERE (((status)::text = 'active'::text) AND (stock_quantity <= low_stock_alert));
CREATE INDEX idx_variants_product ON public.product_variants USING btree (product_id, "position");
CREATE INDEX idx_variants_sku ON public.product_variants USING btree (sku);
