COMMENT ON COLUMN public.shopping_carts.session_id IS 'Anonymous user session ID (UUID from cookie/localStorage). Mutually exclusive with user_id.';
COMMENT ON COLUMN public.shopping_carts.storefront_id IS 'Storefront this cart belongs to. Multi-storefront shopping requires multiple carts.';
COMMENT ON COLUMN public.shopping_carts.updated_at IS 'Auto-updated on any cart modification. Used for cleanup of old anonymous carts (e.g., >30 days).';
COMMENT ON TABLE public.stock_reservations IS 'Temporary stock reservations for order processing';
COMMENT ON COLUMN public.stock_reservations.variant_id IS 'Reference to product_variants.id';
COMMENT ON COLUMN public.stock_reservations.order_id IS 'Reference to order (UUID)';
COMMENT ON COLUMN public.stock_reservations.quantity IS 'Reserved quantity (must be positive)';
COMMENT ON COLUMN public.stock_reservations.expires_at IS 'Reservation expiration timestamp';
COMMENT ON COLUMN public.stock_reservations.status IS 'Reservation status: active, confirmed, cancelled, expired';
COMMENT ON TABLE public.storefront_delivery_options IS 'Delivery options configured by storefront';
COMMENT ON COLUMN public.storefront_delivery_options.zones IS 'JSON array of delivery zones with pricing';
COMMENT ON COLUMN public.storefront_delivery_options.available_days IS 'JSON array of weekdays (1=Monday, 5=Friday)';
COMMENT ON COLUMN public.storefront_delivery_options.cutoff_time IS 'Order cutoff time for same-day delivery';
COMMENT ON COLUMN public.storefront_delivery_options.provider IS 'Values: posta_srbije, aks, bex, d_express, city_express, self_pickup, own_delivery';
COMMENT ON COLUMN public.storefront_delivery_options.display_order IS 'Display order in frontend (lower = higher priority)';
COMMENT ON TABLE public.storefront_events IS 'События витрин для аналитики (page_view, product_view, add_to_cart, checkout, order)';
COMMENT ON COLUMN public.storefront_events.event_type IS 'Тип события: page_view, product_view, add_to_cart, checkout, order';
COMMENT ON COLUMN public.storefront_events.event_data IS 'Дополнительные данные события в формате JSON';
COMMENT ON TABLE public.storefront_hours IS 'Storefront working hours (regular and special dates)';
COMMENT ON COLUMN public.storefront_hours.day_of_week IS '0=Sunday, 1=Monday, ..., 6=Saturday';
COMMENT ON COLUMN public.storefront_hours.is_closed IS 'If true, store is closed on this day/date';
COMMENT ON COLUMN public.storefront_hours.special_date IS 'For special hours on specific dates (holidays, etc)';
COMMENT ON TABLE public.storefront_invitations IS 'Staff invitation system for storefronts';
COMMENT ON COLUMN public.storefront_invitations.role IS 'Role to assign after accepting: owner, manager, staff, cashier';
COMMENT ON COLUMN public.storefront_invitations.type IS 'Invitation type: email (one-time) or link (shareable)';
COMMENT ON COLUMN public.storefront_invitations.invite_code IS 'Unique code for shareable link invitations (sf-XXXXXXXX)';
COMMENT ON COLUMN public.storefront_invitations.max_uses IS 'Max number of uses for link invitations (NULL = unlimited)';
COMMENT ON COLUMN public.storefront_invitations.invited_by_id IS 'User ID who created the invitation';
COMMENT ON COLUMN public.storefront_invitations.status IS 'Current status: pending, accepted, declined, expired, revoked';
COMMENT ON TABLE public.storefront_payment_methods IS 'Payment methods supported by storefront';
COMMENT ON COLUMN public.storefront_payment_methods.method_type IS 'Values: cash, cod, card, bank_transfer, paypal, crypto, postanska, keks_pay, ips';
COMMENT ON COLUMN public.storefront_payment_methods.provider IS 'Payment provider name (e.g., stripe, paypal)';
COMMENT ON COLUMN public.storefront_payment_methods.transaction_fee IS 'Transaction fee in percent';
COMMENT ON TABLE public.storefront_staff IS 'Storefront staff members (owners, managers, cashiers)';
COMMENT ON COLUMN public.storefront_staff.role IS 'Values: owner, manager, cashier, support, moderator';
COMMENT ON COLUMN public.storefront_staff.permissions IS 'JSON with detailed permissions';
COMMENT ON TABLE public.variant_attribute_values IS 'Attribute values for product variants with price modifiers';
COMMENT ON COLUMN public.variant_attribute_values.variant_id IS 'Reference to product_variants.id';
COMMENT ON COLUMN public.variant_attribute_values.attribute_id IS 'Reference to attributes.id';
COMMENT ON COLUMN public.variant_attribute_values.value_text IS 'Text value (for text, select, color, size attributes)';
COMMENT ON COLUMN public.variant_attribute_values.value_number IS 'Numeric value (for number attributes)';
COMMENT ON COLUMN public.variant_attribute_values.value_boolean IS 'Boolean value (for boolean attributes)';
COMMENT ON COLUMN public.variant_attribute_values.value_date IS 'Date value (for date attributes)';
COMMENT ON COLUMN public.variant_attribute_values.value_json IS 'JSON value (for multiselect, complex attributes)';
