-- +goose Up
-- Исправление ключевых слов для категорий со специальными символами в slug
-- Дата: 2025-12-27

-- ============================================================
-- САМОНАДУВАЮЩИЙСЯ МАТРАС (с диакритикой š)
-- ============================================================

UPDATE categories SET meta_keywords = '{"en": "self inflating mattress, self inflating pad, self inflating sleeping mat, camping mattress, camping pad, camping sleeping mat, foam sleeping pad, air mattress camping, inflatable mattress, sleeping mat outdoor, hiking mattress, backpacking pad, ultralight sleeping pad, compact sleeping pad, insulated sleeping mat, r-value pad, thermarest, sea to summit, exped, klymit, nemo sleeping pad, big agnes pad, camping comfort, car camping mattress, tent mattress, single sleeping mat, double sleeping mat, camping gear", "ru": "самонадувающийся матрас, самонадувающийся коврик, самонадувающийся спальный коврик, походный матрас, походный коврик, спальный коврик для кемпинга, пенный спальный коврик, надувной матрас для кемпинга, надувной матрас, спальный коврик для улицы, матрас для хайкинга, коврик для бэкпекинга, ультралёгкий спальный коврик, компактный спальный коврик, утеплённый спальный коврик, коврик r-value, thermarest, sea to summit, exped, klymit, nemo спальный коврик, big agnes коврик, комфорт для кемпинга, автокемпинг матрас, матрас для палатки, одноместный спальный коврик, двухместный спальный коврик, снаряжение для кемпинга", "sr": "samonaduvajući dušek, samonaduvajuća podloga, samonaduvajuća prostirka za spavanje, kamp dušek, kamp podloga, kamp prostirka za spavanje, pena prostirka za spavanje, vazdušni dušek kamp, naduvajući dušek, prostirka za spavanje napolju, dušek za planinarenje, podloga za backpacking, ultralaka prostirka za spavanje, kompaktna prostirka za spavanje, izolovana prostirka za spavanje, r-value podloga, thermarest, sea to summit, exped, klymit, nemo prostirka za spavanje, big agnes podloga, kamp komfor, auto kamp dušek, dušek za šator, pojedinačna prostirka za spavanje, dupla prostirka za spavanje, kamp oprema"}' WHERE slug = 'samoduvajuci-dušek';

-- ============================================================
-- СПАЛЬНЫЙ МЕШОК (с диакритикой ć)
-- ============================================================

UPDATE categories SET meta_keywords = '{"en": "sleeping bag, camping sleeping bag, outdoor sleeping bag, mummy sleeping bag, rectangular sleeping bag, down sleeping bag, synthetic sleeping bag, winter sleeping bag, summer sleeping bag, 3-season sleeping bag, 4-season sleeping bag, ultralight sleeping bag, compact sleeping bag, backpacking sleeping bag, cold weather sleeping bag, warm sleeping bag, insulated sleeping bag, waterproof sleeping bag, sleeping bag liner, double sleeping bag, kids sleeping bag, north face sleeping bag, marmot sleeping bag, rab sleeping bag, mountain hardwear sleeping bag, western mountaineering sleeping bag, camping gear", "ru": "спальный мешок, спальник, кемпинговый спальник, уличный спальный мешок, кокон спальник, прямоугольный спальный мешок, пуховый спальный мешок, синтетический спальный мешок, зимний спальный мешок, летний спальный мешок, трёхсезонный спальный мешок, четырёхсезонный спальный мешок, ультралёгкий спальный мешок, компактный спальный мешок, туристический спальник, холодостойкий спальник, тёплый спальный мешок, утеплённый спальный мешок, водонепроницаемый спальный мешок, вкладыш для спального мешка, двухместный спальный мешок, детский спальный мешок, north face спальный мешок, marmot спальник, rab спальник, снаряжение для кемпинга", "sr": "vreća za spavanje, kamp vreća za spavanje, spoljna vreća za spavanje, mumija vreća za spavanje, pravougaona vreća za spavanje, paperje vreća za spavanje, sintetička vreća za spavanje, zimska vreća za spavanje, letnja vreća za spavanje, trosеzonska vreća za spavanje, četvorosеzonska vreća za spavanje, ultralaka vreća za spavanje, kompaktna vreća za spavanje, vreća za spavanje za backpacking, vreća za spavanje za hladne vremenske uslove, topla vreća za spavanje, izolovana vreća za spavanje, vodootporna vreća za spavanje, podstava za vreću za spavanje, dupla vreća za spavanje, dečija vreća za spavanje, north face vreća za spavanje, marmot vreća za spavanje, rab vreća za spavanje, kamp oprema"}' WHERE slug = 'spavaca-vreća';

-- ============================================================
-- ПРОТЕИНОВЫЕ БАТОНЧИКИ (с диакритикой č)
-- ============================================================

UPDATE categories SET meta_keywords = '{"en": "protein bars, protein snacks, energy bars, nutrition bars, meal replacement bars, whey protein bars, high protein bars, low carb protein bars, keto protein bars, vegan protein bars, organic protein bars, chocolate protein bars, peanut butter protein bars, quest bars, rxbar, kind bars, clif bars, one bars, think protein bars, pure protein bars, met-rx bars, grenade carb killa, bsn protein crisp, muscle pharm combat crisp, fitness snacks, gym snacks, post workout snacks, pre workout bars", "ru": "протеиновые батончики, белковые батончики, энергетические батончики, питательные батончики, батончики заменители еды, сывороточные протеиновые батончики, высокобелковые батончики, низкоуглеводные протеиновые батончики, кето протеиновые батончики, веганские протеиновые батончики, органические протеиновые батончики, шоколадные протеиновые батончики, арахисовые протеиновые батончики, quest батончики, rxbar, kind батончики, clif батончики, one батончики, think протеиновые батончики, pure protein батончики, met-rx батончики, grenade carb killa, bsn protein crisp, фитнес снэки, перекус для спортзала, снэк после тренировки, батончик перед тренировкой, спортивное питание", "sr": "proteinske pločice, proteinski snekovi, energetske pločice, nutritivne pločice, pločice zamena obroka, whey proteinske pločice, visoko proteinske pločice, nisko ugljeno hidratne proteinske pločice, keto proteinske pločice, veganske proteinske pločice, organske proteinske pločice, čokoladne proteinske pločice, kikiriki proteinske pločice, quest pločice, rxbar, kind pločice, clif pločice, one pločice, think proteinske pločice, pure protein pločice, met-rx pločice, grenade carb killa, bsn protein crisp, fitnes snekovi, snekovi za teretanu, snekovi posle treninga, pločice pre treninga, sportska ishrana"}' WHERE slug = 'protein-pločice';

-- ============================================================
-- ДЕТСКОЕ ПИТАНИЕ
-- ============================================================

UPDATE categories SET meta_keywords = '{"en": "baby food, infant food, baby formula, baby puree, organic baby food, baby cereal, baby snacks, baby teething biscuits, baby rice cereal, baby oatmeal, baby fruit puree, baby vegetable puree, baby meat puree, stage 1 baby food, stage 2 baby food, stage 3 baby food, gerber baby food, hipp baby food, holle baby food, earths best baby food, plum organics, happy baby, ella''s kitchen, beech-nut baby food, baby food pouches, homemade baby food, baby led weaning food, toddler food, finger foods for babies", "ru": "детское питание, питание для младенцев, детская смесь, детское пюре, органическое детское питание, детская каша, детские снэки, детское печенье для зубов, детская рисовая каша, детская овсяная каша, детское фруктовое пюре, детское овощное пюре, детское мясное пюре, питание первой ступени, питание второй ступени, питание третьей ступени, gerber детское питание, hipp детское питание, holle детское питание, earths best детское питание, plum organics, happy baby, ella''s kitchen, beech-nut детское питание, детское питание в пауч, домашнее детское питание, blw питание, питание для малышей, фингерфуд для детей, первый прикорм", "sr": "hrana za bebe, hrana za odojčad, formula za bebe, pire za bebe, organska hrana za bebe, kaša za bebe, snekovi za bebe, biskviti za nicanje zuba, pirinčana kaša za bebe, ovsena kaša za bebe, voćni pire za bebe, povrtni pire za bebe, mesni pire za bebe, hrana za bebe faza 1, hrana za bebe faza 2, hrana za bebe faza 3, gerber hrana za bebe, hipp hrana za bebe, holle hrana za bebe, earths best hrana za bebe, plum organics, happy baby, ella''s kitchen, beech-nut hrana za bebe, kese sa hranom za bebe, domaća hrana za bebe, blw hrana, hrana za malu decu, finger food za bebe, prvi obrok"}' WHERE slug = 'hrana-za-bebe';

-- ============================================================
-- СКЛАДНАЯ ВАННОЧКА ДЛЯ ДЕТЕЙ (с пробелом в slug)
-- ============================================================

UPDATE categories SET meta_keywords = '{"en": "foldable baby bath, collapsible baby bathtub, portable baby bath, folding infant tub, space-saving baby bath, travel baby bath, compact baby bathtub, baby bath seat, baby bath support, newborn bath tub, baby spa tub, baby bath bucket, baby wash tub, baby bath with stand, baby bath thermometer, anti-slip baby bath, ergonomic baby bath, baby bathing accessories, stokke flexi bath, summer infant bath, skip hop bath, munchkin baby bath, primo eurobath, 4moms baby bath, boon naked bathtub, puj tub, angelcare bath support", "ru": "складная ванночка для купания, складная детская ванночка, портативная ванночка для ребёнка, складная ванна для младенца, компактная детская ванночка, дорожная ванночка для ребёнка, ванночка-стульчик, подставка для купания, ванночка для новорождённого, спа ванночка для ребёнка, ванночка ведро, ванночка для мытья, ванночка на подставке, термометр для ванночки, противоскользящая ванночка, эргономичная детская ванночка, аксессуары для купания, stokke flexi bath, summer infant ванночка, skip hop ванночка, munchkin ванночка, primo eurobath, 4moms ванночка, boon naked ванночка, puj ванночка, angelcare подставка для купания", "sr": "sklopiva kadica za bebe, sklopljiva kadica za bebe, prenosiva kadica za bebe, sklopiva kadica za odojčad, kompaktna kadica za bebe, putna kadica za bebe, kadica sa sedištem za bebe, podrška za kupanje bebe, kadica za novorođenče, spa kadica za bebe, kadica kofa za bebe, kadica za pranje bebe, kadica sa postoljem, termometar za kadicu, neklizajuća kadica za bebe, ergonomska kadica za bebe, oprema za kupanje bebe, stokke flexi bath, summer infant kadica, skip hop kadica, munchkin kadica, primo eurobath, 4moms kadica, boon naked kadica, puj kadica, angelcare podrška za kupanje"}' WHERE slug = 'kada-bebe-sklop ljiva';

-- ============================================================
-- ДОМАШНИЕ ХАЛАТЫ (с кириллической љ)
-- ============================================================

UPDATE categories SET meta_keywords = '{"en": "house dress, loungewear dress, casual dress home, comfort dress, relaxed home dress, everyday home dress, cotton house dress, linen house dress, summer house dress, sleeveless house dress, long sleeve house dress, button front house dress, zip front house dress, mumu dress, caftan dress, shift dress home, a-line house dress, plus size house dress, petite house dress, floral house dress, solid house dress, striped house dress, printed house dress, lightweight house dress, breathable house dress, easy care house dress, machine washable dress", "ru": "домашнее платье, халат-платье, кафтан домашний, свободное домашнее платье, удобное домашнее платье, повседневное домашнее платье, хлопковое домашнее платье, льняное домашнее платье, летнее домашнее платье, домашнее платье без рукавов, домашнее платье с длинным рукавом, домашнее платье на пуговицах, домашнее платье на молнии, муму платье, кафтан платье, свободного кроя домашнее платье, а-силуэт домашнее платье, домашнее платье большого размера, домашнее платье маленького размера, цветочное домашнее платье, однотонное домашнее платье, полосатое домашнее платье, домашнее платье с принтом, лёгкое домашнее платье, дышащее домашнее платье, домашнее платье лёгкого ухода", "sr": "kućna haljina, haljina za opuštanje, ležerna kućna haljina, udobna haljina, opuštena kućna haljina, svakodnevna kućna haljina, pamučna kućna haljina, lanena kućna haljina, letnja kućna haljina, kućna haljina bez rukava, kućna haljina dugih rukava, kućna haljina sa dugmićima, kućna haljina sa rajsferšlusom, mumu haljina, kaftan haljina, shift kućna haljina, a-linija kućna haljina, kućna haljina za veće brojeve, kućna haljina za manje brojeve, cvetna kućna haljina, jednobojna kućna haljina, prugasta kućna haljina, štampana kućna haljina, lagana kućna haljina, prozračna kućna haljina, haljina lakog održavanja"}' WHERE slug = 'kucne-halјine';

-- ============================================================
-- НАБОР КУХОННЫХ НОЖЕЙ
-- ============================================================

UPDATE categories SET meta_keywords = '{"en": "kitchen knife set, knife block set, chef knife set, professional knife set, cooking knife set, japanese knife set, german knife set, stainless steel knife set, carbon steel knife set, damascus knife set, forged knife set, stamped knife set, knife set with block, knife set with magnetic strip, starter knife set, complete knife set, essential knife set, wusthof knife set, zwilling knife set, shun knife set, global knife set, victorinox knife set, henckels knife set, cuisinart knife set, calphalon knife set, kitchen cutlery set", "ru": "набор кухонных ножей, набор ножей в блоке, набор ножей шеф-повара, профессиональный набор ножей, набор ножей для готовки, японский набор ножей, немецкий набор ножей, набор ножей из нержавеющей стали, набор ножей из углеродистой стали, дамасский набор ножей, кованый набор ножей, штампованный набор ножей, набор ножей с подставкой, набор ножей с магнитной полосой, стартовый набор ножей, полный набор ножей, базовый набор ножей, wusthof набор ножей, zwilling набор ножей, shun набор ножей, global набор ножей, victorinox набор ножей, henckels набор ножей, cuisinart набор ножей, calphalon набор ножей, кухонные столовые приборы", "sr": "set kuhinjskih noževa, set noževa sa blokom, set šef noževa, profesionalni set noževa, set noževa za kuvanje, japanski set noževa, nemački set noževa, set noževa od nerđajućeg čelika, set noževa od ugljeničnog čelika, damask set noževa, kovani set noževa, štampani set noževa, set noževa sa postoljem, set noževa sa magnetnom trakom, početni set noževa, kompletan set noževa, osnovni set noževa, wusthof set noževa, zwilling set noževa, shun set noževa, global set noževa, victorinox set noževa, henckels set noževa, cuisinart set noževa, calphalon set noževa, kuhinjski escajg"}' WHERE slug = 'kuhinjski-set-nozeva';

-- ============================================================
-- КУПАЛЬНЫЕ КОСТЮМЫ
-- ============================================================

UPDATE categories SET meta_keywords = '{"en": "swimsuit, bathing suit, swimming costume, one piece swimsuit, two piece swimsuit, bikini swimsuit, tankini swimsuit, high waisted swimsuit, push up swimsuit, padded swimsuit, underwire swimsuit, supportive swimsuit, athletic swimsuit, competitive swimsuit, modest swimsuit, plus size swimsuit, maternity swimsuit, teen swimsuit, girls swimsuit, boys swimsuit, swim shorts, swim trunks, speedo swimsuit, arena swimsuit, tyr swimsuit, nike swimsuit, adidas swimsuit, chlorine resistant swimsuit, sun protection swimsuit, rash guard", "ru": "купальник, купальный костюм, цельный купальник, раздельный купальник, бикини купальник, танкини купальник, высокий купальник, пуш-ап купальник, купальник с чашечками, купальник на косточках, поддерживающий купальник, спортивный купальник, соревновательный купальник, закрытый купальник, купальник большого размера, купальник для беременных, подростковый купальник, девичий купальник, мальчиковый купальник, плавательные шорты, плавки, speedo купальник, arena купальник, tyr купальник, nike купальник, adidas купальник, хлоростойкий купальник, купальник с защитой от солнца, рашгард, плавки мужские", "sr": "kupaći kostim, jednodelni kupaći kostim, dvodelni kupaći kostim, bikini kupaći kostim, tankini kupaći kostim, visokostruki kupaći kostim, push up kupaći kostim, kupaći kostim sa jastučićima, kupaći kostim sa žicama, podržavajući kupaći kostim, atletski kupaći kostim, takmičarski kupaći kostim, skromni kupaći kostim, kupaći kostim za veće brojeve, kupaći kostim za trudnice, tinejdžerski kupaći kostim, devojački kupaći kostim, dečački kupaći kostim, šorc za plivanje, kupaće gaćice, speedo kupaći kostim, arena kupaći kostim, tyr kupaći kostim, nike kupaći kostim, adidas kupaći kostim, kupaći kostim otporan na hlor, kupaći kostim sa zaštitom od sunca, rash guard"}' WHERE slug = 'kupaci-kostimi';

-- ============================================================
-- UV ЗАЩИТНЫЕ КУПАЛЬНЫЕ МАЙКИ (с диакритикой ć и š)
-- ============================================================

UPDATE categories SET meta_keywords = '{"en": "uv protection swim shirt, sun protection swim shirt, rash guard, rash vest, swim shirt upf 50, long sleeve swim shirt, short sleeve swim shirt, kids uv swim shirt, womens uv swim shirt, mens uv swim shirt, uv50 plus swim shirt, sun blocking swim shirt, anti uv swim shirt, surfing rash guard, snorkeling swim shirt, water sports shirt, beach swim shirt, pool swim shirt, quick dry swim shirt, chlorine resistant swim shirt, fitted rash guard, loose fit swim shirt, printed rash guard, solid color swim shirt, zip front rash guard, crew neck swim shirt", "ru": "солнцезащитная футболка для плавания, uv защитная футболка для плавания, рашгард, рашвест, футболка для плавания upf 50, футболка для плавания с длинным рукавом, футболка для плавания с коротким рукавом, детская uv футболка для плавания, женская uv футболка для плавания, мужская uv футболка для плавания, uv50 плюс футболка для плавания, солнцезащитная футболка, анти uv футболка для плавания, рашгард для сёрфинга, футболка для снорклинга, футболка для водных видов спорта, пляжная футболка, футболка для бассейна, быстросохнущая футболка, хлоростойкая футболка, облегающий рашгард, свободный крой футболка, рашгард с принтом, однотонная футболка для плавания, рашгард на молнии, футболка с круглым вырезом", "sr": "uv zaštitna majica za plivanje, zaštitna majica od sunca za plivanje, rash guard, rash prsluk, majica za plivanje upf 50, majica za plivanje dugih rukava, majica za plivanje kratkih rukava, dečija uv majica za plivanje, ženska uv majica za plivanje, muška uv majica za plivanje, uv50 plus majica za plivanje, majica za blokiranje sunca, anti uv majica za plivanje, rash guard za surfovanje, majica za ronjenje sa maskom, majica za vodene sportove, plaža majica za plivanje, bazen majica za plivanje, brzo sušeća majica za plivanje, majica otporna na hlor, pripijena rash guard, slobodan kroj majica za plivanje, štampana rash guard, jednobojna majica za plivanje, rash guard sa rajsferšlusom, majica sa okruglim izrezom"}' WHERE slug = 'kupaći-majice-uv-zaštita';

-- ============================================================
-- УНИЧТОЖИТЕЛИ ДОКУМЕНТОВ (с диакритикой č)
-- ============================================================

UPDATE categories SET meta_keywords = '{"en": "document shredder, paper shredder, office shredder, cross cut shredder, micro cut shredder, strip cut shredder, high security shredder, personal shredder, heavy duty shredder, commercial shredder, industrial shredder, electric shredder, automatic shredder, credit card shredder, cd dvd shredder, staple shredder, quiet shredder, jam proof shredder, continuous run shredder, 10 sheet shredder, 20 sheet shredder, fellowes shredder, rexel shredder, gbc shredder, bonsaii shredder, amazonbasics shredder, confidential document destruction", "ru": "уничтожитель документов, шредер, офисный шредер, перекрёстная резка шредер, микрорезка шредер, прямая резка шредер, шредер высокой безопасности, персональный шредер, шредер для больших объёмов, коммерческий шредер, промышленный шредер, электрический шредер, автоматический шредер, уничтожитель кредитных карт, уничтожитель cd dvd, шредер для скоб, тихий шредер, шредер без заминания, непрерывный шредер, шредер на 10 листов, шредер на 20 листов, fellowes шредер, rexel шредер, gbc шредер, bonsaii шредер, amazonbasics шредер, уничтожение конфиденциальных документов", "sr": "uništavač dokumenata, šreder za papir, kancelarijski šreder, unakrsno sečenje šreder, mikro sečenje šreder, trakasto sečenje šreder, visoko bezbednosni šreder, lični šreder, teški šreder, komercijalni šreder, industrijski šreder, električni šreder, automatski šreder, uništavač kreditnih kartica, uništavač cd dvd, šreder za klamerice, tihi šreder, šreder bez zaglavljivanja, neprekidni šreder, šreder za 10 listova, šreder za 20 listova, fellowes šreder, rexel šreder, gbc šreder, bonsaii šreder, amazonbasics šreder, uništavanje poverljivih dokumenata"}' WHERE slug = 'lomači-dokumenta';

-- ============================================================
-- ПОСУДОМОЕЧНЫЕ МАШИНЫ (с кириллической е)
-- ============================================================

UPDATE categories SET meta_keywords = '{"en": "dishwasher, dishwashing machine, built in dishwasher, freestanding dishwasher, integrated dishwasher, slimline dishwasher, compact dishwasher, countertop dishwasher, portable dishwasher, drawer dishwasher, 60cm dishwasher, 45cm dishwasher, energy efficient dishwasher, quiet dishwasher, smart dishwasher, wifi dishwasher, stainless steel dishwasher, white dishwasher, black dishwasher, bosch dishwasher, siemens dishwasher, miele dishwasher, samsung dishwasher, lg dishwasher, whirlpool dishwasher, electrolux dishwasher, beko dishwasher, aeg dishwasher, kitchen appliances", "ru": "посудомоечная машина, посудомойка, встраиваемая посудомоечная машина, отдельностоящая посудомойка, интегрированная посудомоечная машина, узкая посудомоечная машина, компактная посудомоечная машина, настольная посудомойка, портативная посудомойка, посудомойка ящичная, посудомойка 60 см, посудомойка 45 см, энергоэффективная посудомойка, тихая посудомойка, умная посудомойка, wifi посудомойка, посудомойка из нержавеющей стали, белая посудомойка, чёрная посудомойка, bosch посудомойка, siemens посудомойка, miele посудомойка, samsung посудомойка, lg посудомойка, whirlpool посудомойка, electrolux посудомойка, beko посудомойка, aeg посудомойка, кухонная техника", "sr": "mašina za pranje sudova, sudopera, ugradbena mašina za sudove, samostojeća mašina za sudove, integrisana mašina za sudove, uska mašina za sudove, kompaktna mašina za sudove, stona mašina za sudove, prenosiva mašina za sudove, fioka mašina za sudove, mašina za sudove 60cm, mašina za sudove 45cm, energetski efikasna mašina za sudove, tiha mašina za sudove, pametna mašina za sudove, wifi mašina za sudove, mašina za sudove od nerđajućeg čelika, bela mašina za sudove, crna mašina za sudove, bosch mašina za sudove, siemens mašina za sudove, miele mašina za sudove, samsung mašina za sudove, lg mašina za sudove, whirlpool mašina za sudove, electrolux mašina za sudove, beko mašina za sudove, aeg mašina za sudove, kuhinjski aparati"}' WHERE slug = 'masine-sudjе';

-- ============================================================
-- МИКРОФОНЫ
-- ============================================================

UPDATE categories SET meta_keywords = '{"en": "microphone, condenser microphone, dynamic microphone, usb microphone, xlr microphone, wireless microphone, lavalier microphone, shotgun microphone, podcast microphone, streaming microphone, gaming microphone, studio microphone, vocal microphone, instrument microphone, ribbon microphone, cardioid microphone, omnidirectional microphone, figure 8 microphone, stereo microphone, karaoke microphone, handheld microphone, desktop microphone, boom microphone, headset microphone, shure microphone, rode microphone, audio technica microphone, blue microphone, sennheiser microphone, neumann microphone, akg microphone, beyerdynamic microphone", "ru": "микрофон, конденсаторный микрофон, динамический микрофон, usb микрофон, xlr микрофон, беспроводной микрофон, петличный микрофон, направленный микрофон, подкаст микрофон, стриминг микрофон, игровой микрофон, студийный микрофон, вокальный микрофон, инструментальный микрофон, ленточный микрофон, кардиоидный микрофон, всенаправленный микрофон, восьмёрка микрофон, стерео микрофон, караоке микрофон, ручной микрофон, настольный микрофон, микрофон пушка, гарнитура микрофон, shure микрофон, rode микрофон, audio technica микрофон, blue микрофон, sennheiser микрофон, neumann микрофон, akg микрофон, beyerdynamic микрофон", "sr": "mikrofon, kondenzatorski mikrofon, dinamički mikrofon, usb mikrofon, xlr mikrofon, bežični mikrofon, lavalijеr mikrofon, shotgun mikrofon, podcast mikrofon, streaming mikrofon, gaming mikrofon, studijski mikrofon, vokalni mikrofon, instrumentalni mikrofon, trakasti mikrofon, kardioidni mikrofon, svesmerni mikrofon, osmica mikrofon, stereo mikrofon, karaoke mikrofon, ručni mikrofon, stoni mikrofon, boom mikrofon, slušalice mikrofon, shure mikrofon, rode mikrofon, audio technica mikrofon, blue mikrofon, sennheiser mikrofon, neumann mikrofon, akg mikrofon, beyerdynamic mikrofon"}' WHERE slug = 'mikrofoni';

-- ============================================================
-- МУЖСКИЕ ДЖЕМПЕРЫ (с пробелом и диакритикой)
-- ============================================================

UPDATE categories SET meta_keywords = '{"en": "mens jumper, mens sweater, mens pullover, mens knitwear, crew neck jumper, v neck jumper, roll neck jumper, turtleneck sweater, quarter zip jumper, half zip sweater, cable knit jumper, ribbed jumper, chunky knit sweater, lightweight jumper, merino wool jumper, cashmere jumper, cotton jumper, lambswool jumper, wool blend jumper, fitted jumper, relaxed fit jumper, oversized jumper, slim fit sweater, designer jumper, casual jumper, smart jumper, winter jumper, christmas jumper, fair isle jumper, argyle jumper, mens knitwear brands", "ru": "мужской джемпер, мужской свитер, мужской пуловер, мужской трикотаж, джемпер с круглым вырезом, джемпер с v-вырезом, джемпер с высоким воротником, свитер водолазка, джемпер на молнии четверть, свитер на полумолнии, джемпер косичка, ребристый джемпер, крупной вязки свитер, лёгкий джемпер, джемпер из мериноса, кашемировый джемпер, хлопковый джемпер, джемпер из овечьей шерсти, джемпер из смесовой шерсти, приталенный джемпер, свободного кроя джемпер, оверсайз джемпер, slim fit свитер, дизайнерский джемпер, повседневный джемпер, элегантный джемпер, зимний джемпер, новогодний свитер, джемпер fair isle, джемпер аргайл, мужские бренды трикотажа", "sr": "muški džemper, muški sviter, muški pulover, muška pletena odeća, džemper sa okruglim izrezom, džemper sa v izrezom, rolka džemper, dolčevita sviter, džemper sa četvrt rajsferšlusom, sviter sa pola rajsferšlusom, kablasto pleteni džemper, rebrasti džemper, krupno pleteni sviter, lagan džemper, merino vuneni džemper, kašmir džemper, pamučni džemper, džemper od jagnjеće vune, džemper od mešavine vune, pripiјen džemper, opušten kroj džemper, oversized džemper, slim fit sviter, dizajnerski džemper, casual džemper, elegantan džemper, zimski džemper, božićni džemper, fair isle džemper, argyle džemper, muški brendovi pletene odeće"}' WHERE slug = 'muski-dž emperi';

-- ============================================================
-- НОЧНЫЕ РУБАШКИ И ПЕНЬЮАРЫ (с пробелом в slug)
-- ============================================================

UPDATE categories SET meta_keywords = '{"en": "negligee, nightgown, nightdress, sleepwear, nightie, silk nightgown, satin nightgown, lace nightgown, cotton nightgown, modal nightgown, long nightgown, short nightgown, sleeveless nightgown, long sleeve nightgown, chemise, babydoll nightgown, slip nightgown, v neck nightgown, round neck nightgown, luxury nightgown, comfortable nightgown, lightweight nightgown, breathable nightgown, bridal nightgown, honeymoon lingerie, romantic sleepwear, elegant nightwear, plus size nightgown, petite nightgown, vintage nightgown", "ru": "ночная рубашка, пеньюар, ночная сорочка, ночное бельё, ночнушка, шёлковая ночная рубашка, атласная ночная рубашка, кружевная ночная рубашка, хлопковая ночная рубашка, модальная ночная рубашка, длинная ночная рубашка, короткая ночная рубашка, ночная рубашка без рукавов, ночная рубашка с длинным рукавом, комбинация, беби долл ночная рубашка, ночная рубашка комбинация, ночная рубашка v вырез, ночная рубашка с круглым вырезом, роскошная ночная рубашка, удобная ночная рубашка, лёгкая ночная рубашка, дышащая ночная рубашка, свадебная ночная рубашка, медовый месяц бельё, романтическая одежда для сна, элегантная ночная одежда, ночная рубашка большого размера, ночная рубашка маленького размера, винтажная ночная рубашка", "sr": "negliže, spavaćica, noćna haljina, odeća za spavanje, spavaćica svilena, satenski spavaćica, čipkasta spavaćica, pamučna spavaćica, modalna spavaćica, duga spavaćica, kratka spavaćica, spavaćica bez rukava, spavaćica dugih rukava, kombiné, baby doll spavaćica, slip spavaćica, v izrez spavaćica, okrugli izrez spavaćica, luksuzna spavaćica, udobna spavaćica, lagana spavaćica, prozračna spavaćica, svadbena spavaćica, medeni mesec donje rublje, romantična odeća za spavanje, elegantna noćna odeća, spavaćica za veće brojeve, spavaćica za manje brojeve, vintage spavaćica"}' WHERE slug = 'negl ize-i-spavacice';

-- ============================================================
-- БЕСПРОВОДНЫЕ ЗАРЯДНЫЕ УСТРОЙСТВА (с диакритикой ž)
-- ============================================================

UPDATE categories SET meta_keywords = '{"en": "wireless charger, qi charger, inductive charger, wireless charging pad, wireless charging stand, fast wireless charger, 15w wireless charger, 10w wireless charger, magsafe charger, apple wireless charger, samsung wireless charger, iphone wireless charger, android wireless charger, dual wireless charger, 3 in 1 wireless charger, bedside wireless charger, desk wireless charger, car wireless charger, portable wireless charger, travel wireless charger, anker wireless charger, belkin wireless charger, mophie wireless charger, spigen wireless charger, wireless charging station, airpods wireless charger, apple watch wireless charger", "ru": "беспроводное зарядное устройство, qi зарядка, индуктивная зарядка, беспроводная зарядная площадка, беспроводная зарядная подставка, быстрая беспроводная зарядка, беспроводная зарядка 15w, беспроводная зарядка 10w, magsafe зарядка, apple беспроводная зарядка, samsung беспроводная зарядка, iphone беспроводная зарядка, android беспроводная зарядка, двойная беспроводная зарядка, 3 в 1 беспроводная зарядка, прикроватная беспроводная зарядка, настольная беспроводная зарядка, автомобильная беспроводная зарядка, портативная беспроводная зарядка, дорожная беспроводная зарядка, anker беспроводная зарядка, belkin беспроводная зарядка, mophie беспроводная зарядка, spigen беспроводная зарядка, беспроводная зарядная станция, airpods беспроводная зарядка, apple watch беспроводная зарядка", "sr": "bežični punjač, qi punjač, induktivni punjač, bežična podloga za punjenje, bežični stalak za punjenje, brzi bežični punjač, 15w bežični punjač, 10w bežični punjač, magsafe punjač, apple bežični punjač, samsung bežični punjač, iphone bežični punjač, android bežični punjač, dupli bežični punjač, 3 u 1 bežični punjač, bežični punjač za noćni sto, bežični punjač za sto, bežični punjač za auto, prenosivi bežični punjač, putni bežični punjač, anker bežični punjač, belkin bežični punjač, mophie bežični punjač, spigen bežični punjač, bežična stanica za punjenje, airpods bežični punjač, apple watch bežični punjač"}' WHERE slug = 'punjaci-bežicni';

-- ============================================================
-- НАСТЕННЫЕ ЧАСЫ (с пробелом в slug)
-- ============================================================

UPDATE categories SET meta_keywords = '{"en": "wall clock, analog wall clock, digital wall clock, decorative wall clock, modern wall clock, vintage wall clock, retro wall clock, minimalist wall clock, oversized wall clock, large wall clock, small wall clock, silent wall clock, ticking wall clock, pendulum wall clock, cuckoo clock, grandfather clock style, atomic wall clock, radio controlled clock, led wall clock, wooden wall clock, metal wall clock, glass wall clock, plastic wall clock, kitchen wall clock, living room wall clock, office wall clock, bedroom wall clock, designer wall clock, smart wall clock", "ru": "настенные часы, аналоговые настенные часы, цифровые настенные часы, декоративные настенные часы, современные настенные часы, винтажные настенные часы, ретро настенные часы, минималистичные настенные часы, большие настенные часы, крупные настенные часы, маленькие настенные часы, бесшумные настенные часы, тикающие настенные часы, маятниковые настенные часы, часы с кукушкой, стиль напольные часы, атомные настенные часы, радиоуправляемые часы, led настенные часы, деревянные настенные часы, металлические настенные часы, стеклянные настенные часы, пластиковые настенные часы, кухонные настенные часы, настенные часы для гостиной, офисные настенные часы, настенные часы для спальни, дизайнерские настенные часы, умные настенные часы", "sr": "zidni sat, analogni zidni sat, digitalni zidni sat, dekorativni zidni sat, moderan zidni sat, vintage zidni sat, retro zidni sat, minimalistički zidni sat, preveliki zidni sat, veliki zidni sat, mali zidni sat, tihi zidni sat, sat koji otkucava, klatno zidni sat, kukavica sat, stil podnog sata, atomski zidni sat, radio kontrolisani sat, led zidni sat, drveni zidni sat, metalni zidni sat, stakleni zidni sat, plastični zidni sat, kuhinjski zidni sat, zidni sat za dnevnu sobu, kancelarijski zidni sat, zidni sat za spavaću sobu, dizajnerski zidni sat, pametni zidni sat"}' WHERE slug = 'sat i-za-zid';

-- ============================================================
-- СЕРВИРОВОЧНЫЕ ПОДНОСЫ
-- ============================================================

UPDATE categories SET meta_keywords = '{"en": "serving tray, decorative tray, ottoman tray, coffee table tray, breakfast tray, bed tray, lap tray, butler tray, bar tray, cocktail tray, tea tray, vanity tray, bathroom tray, kitchen tray, wooden serving tray, metal serving tray, bamboo tray, acrylic tray, marble tray, leather tray, rattan tray, wicker tray, lacquer tray, round serving tray, rectangular tray, oval tray, tray with handles, nesting trays, stackable trays, decorative bowl", "ru": "сервировочный поднос, декоративный поднос, поднос для оттоманки, поднос для журнального столика, поднос для завтрака, поднос для кровати, поднос на колени, поднос батлер, барный поднос, коктейльный поднос, чайный поднос, поднос для косметики, поднос для ванной, кухонный поднос, деревянный сервировочный поднос, металлический сервировочный поднос, бамбуковый поднос, акриловый поднос, мраморный поднос, кожаный поднос, ротанговый поднос, плетёный поднос, лаковый поднос, круглый сервировочный поднос, прямоугольный поднос, овальный поднос, поднос с ручками, вложенные подносы, штабелируемые подносы, декоративная миска", "sr": "poslužavnik, dekorativni poslužavnik, poslužavnik za tabure, poslužavnik za klub sto, poslužavnik za doručak, poslužavnik za krevet, poslužavnik za krilo, batler poslužavnik, bar poslužavnik, koktel poslužavnik, čaj poslužavnik, kozmetički poslužavnik, kupatilo poslužavnik, kuhinjski poslužavnik, drveni poslužavnik, metalni poslužavnik, bambus poslužavnik, akrilni poslužavnik, mermer poslužavnik, kožni poslužavnik, ratan poslužavnik, pleteni poslužavnik, lakirani poslužavnik, okrugli poslužavnik, pravougaoni poslužavnik, ovalni poslužavnik, poslužavnik sa ručkama, ugneždeni poslužavnici, poslužavnici za slaganje, dekorativna činija"}' WHERE slug = 'tacne-posluzavnici';

-- ============================================================
-- ДОМАШНИЙ ТЕКСТИЛЬ
-- ============================================================

UPDATE categories SET meta_keywords = '{"en": "home textile, household textile, home fabric, soft furnishings, home linen, bedding textile, curtain fabric, upholstery fabric, cushion covers, throw pillows, blankets, throws, tablecloths, napkins, placemats, table runners, kitchen textiles, bathroom textiles, towels, bath mats, shower curtains, duvet covers, bed sheets, pillowcases, comforters, quilts, bedspreads, decorative textile, cotton textile, linen fabric, silk fabric, velvet fabric, jacquard fabric", "ru": "домашний текстиль, бытовой текстиль, ткань для дома, мягкая обстановка, домашнее бельё, постельный текстиль, ткань для штор, обивочная ткань, чехлы на подушки, декоративные подушки, одеяла, пледы, скатерти, салфетки, подтарельники, дорожки на стол, кухонный текстиль, текстиль для ванной, полотенца, коврики для ванной, шторы для душа, пододеяльники, простыни, наволочки, одеяла стёганые, покрывала, покрывала на кровать, декоративный текстиль, хлопковый текстиль, льняная ткань, шёлковая ткань, бархатная ткань, жаккардовая ткань", "sr": "kućni tekstil, domaći tekstil, tkanina za dom, meka oprema, domaće rublje, tekstil za posteljinu, tkanina za zavese, tkanina za tapaciranje, navlake za jastuke, ukrasni jastuci, ćebad, pleteni prekrivači, stolnjaci, salvete, podmetači, staze za sto, kuhinjski tekstil, tekstil za kupatilo, peškiri, tepisi za kupatilo, zavese za tuš, jorganske navlake, čaršafi, jastučnice, jorgani, prošiveni prekrivači, prekrivači za krevet, dekorativni tekstil, pamučni tekstil, lanena tkanina, svilena tkanina, baršunasta tkanina, žakard tkanina"}' WHERE slug = 'tekstil-za-dom';

-- ============================================================
-- ЖЕНСКАЯ ДЕЛОВАЯ ОДЕЖДА
-- ============================================================

UPDATE categories SET meta_keywords = '{"en": "womens business wear, womens office wear, womens work clothes, professional women clothing, corporate women fashion, business casual women, formal women attire, executive women clothing, power dressing women, interview outfit women, business suits women, pencil skirts, dress pants women, blazers women, business blouses, work dresses, sheath dresses, midi dresses office, tailored women clothes, smart casual women, dressy casual women, boardroom outfit, women office style, investment dressing, capsule work wardrobe, business separates, women career wear, professional outfits women, officewear brands", "ru": "женская деловая одежда, женская офисная одежда, женская рабочая одежда, профессиональная женская одежда, корпоративная женская мода, бизнес кэжуал женщины, формальный женский наряд, руководящая женская одежда, стиль власти женщины, наряд для собеседования женщины, деловые костюмы женские, юбки карандаш, брюки женские классические, блейзеры женские, деловые блузки, платья для работы, платья футляр, миди платья офис, приталенная женская одежда, смарт кэжуал женщины, нарядный кэжуал женщины, наряд для зала заседаний, женский офисный стиль, инвестиционный дресс-код, капсульный рабочий гардероб, деловые комплекты, женская карьерная одежда, профессиональные наряды женщины, бренды офисной одежды", "sr": "ženska poslovna odeća, ženska kancelarijska odeća, ženska radna odeća, profesionalna ženska odeća, korporativna ženska moda, business casual žene, formalna ženska odeća, izvršna ženska odeća, power dressing žene, intervju outfit žene, poslovni kostimi žene, suknje olovke, pantalone za posao žene, ženski blejzeri, poslovne bluze, radne haljine, haljine futrole, midi haljine kancelarija, krojena ženska odeća, smart casual žene, svečani casual žene, odelo za sastanke, ženski kancelarijski stil, investment dressing, kapsulna radna garderoba, poslovni kompleti, ženska karijerna odeća, profesionalni outfiti žene, brendovi kancelarijske odeće"}' WHERE slug = 'zenska-poslovna-odeca';

-- +goose Down
-- Данные ключевых слов не критичны, откат не требуется
