COMMENT ON COLUMN public.listings.attributes IS 'JSONB attributes for flexible product metadata. Note: listing_attributes table also exists for key-value storage.';
COMMENT ON COLUMN public.listings.stock_status IS 'Inventory status: in_stock (available), out_of_stock (no stock), low_stock (below threshold), discontinued (no longer available)';
COMMENT ON COLUMN public.listings.sold_count IS 'Number of times this listing has been sold';
COMMENT ON COLUMN public.listings.has_individual_location IS 'If true, product has its own location independent of storefront';
COMMENT ON COLUMN public.listings.individual_address IS 'Individual address for products with custom location';
COMMENT ON COLUMN public.listings.individual_latitude IS 'Latitude for individual product location';
COMMENT ON COLUMN public.listings.individual_longitude IS 'Longitude for individual product location';
COMMENT ON COLUMN public.listings.location_privacy IS 'Privacy level for location display (exact, approximate, hidden)';
COMMENT ON COLUMN public.listings.show_on_map IS 'Whether to show this listing on map interface';
COMMENT ON COLUMN public.listings.has_variants IS 'Whether this product has variants (sizes, colors, etc.)';
COMMENT ON COLUMN public.listings.slug IS 'SEO-friendly URL slug, unique across active listings';
COMMENT ON COLUMN public.listings.expires_at IS 'Optional expiration timestamp for C2C listings (auto-archive after this time)';
COMMENT ON COLUMN public.listings.title_translations IS 'JSONB map of language codes to translated titles, e.g., {"en": "Title", "ru": "Заголовок", "sr": "Наслов"}';
COMMENT ON COLUMN public.listings.description_translations IS 'JSONB map of language codes to translated descriptions';
COMMENT ON COLUMN public.listings.location_translations IS 'JSONB map of language codes to translated location';
COMMENT ON COLUMN public.listings.city_translations IS 'JSONB map of language codes to translated city names';
COMMENT ON COLUMN public.listings.country_translations IS 'JSONB map of language codes to translated country names';
COMMENT ON COLUMN public.listings.original_language IS 'Original language code (sr, en, ru) in which the listing was created';
COMMENT ON COLUMN public.listings.category_id IS 'UUID reference to categories.id (changed from bigint in migration 20251217150000)';
COMMENT ON TABLE public.orders IS 'Completed purchase orders. Supports authenticated and guest checkout, escrow, shipping tracking.';
COMMENT ON COLUMN public.orders.order_number IS 'Unique order identifier shown to customer (e.g., ORD-2025-001234).';
COMMENT ON COLUMN public.orders.user_id IS 'Authenticated user ID (FK to auth service). NULL for guest checkout.';
COMMENT ON COLUMN public.orders.status IS 'Order lifecycle: pending → confirmed → processing → shipped → delivered (or cancelled/refunded/failed).';
COMMENT ON COLUMN public.orders.payment_status IS 'Payment tracking: pending → paid/completed/cod_pending (or failed/refunded/partially_refunded). ''cod_pending'' is for COD orders awaiting payment at delivery.';
COMMENT ON COLUMN public.orders.commission IS 'Platform commission (marketplace fee). Deducted from seller_amount.';
COMMENT ON COLUMN public.orders.seller_amount IS 'Amount seller receives: total - commission. Released after escrow period.';
COMMENT ON COLUMN public.orders.shipping_address IS 'JSONB: { name, street, city, postal_code, country, phone, ... }. Flexible schema.';
COMMENT ON COLUMN public.orders.billing_address IS 'JSONB: { name, street, city, postal_code, country, phone, ... }. Flexible schema.';
COMMENT ON COLUMN public.orders.escrow_release_date IS 'When to release payment to seller. Calculated as: order created_at + escrow_days.';
COMMENT ON COLUMN public.orders.escrow_days IS 'Number of days to hold payment (default: 3). Protects buyer, allows returns/disputes.';
COMMENT ON COLUMN public.orders.shipment_id IS 'FK to Delivery Service microservice. NULL if not using delivery service.';
COMMENT ON COLUMN public.orders.cancelled_at IS 'When order was cancelled. NULL if not cancelled.';
COMMENT ON COLUMN public.orders.cancellation_reason IS 'Why order was cancelled (customer request, out of stock, fraud, etc).';
COMMENT ON COLUMN public.orders.payment_completed_at IS 'Timestamp when payment was completed';
COMMENT ON COLUMN public.orders.customer_name IS 'Customer full name from shipping address';
COMMENT ON COLUMN public.orders.customer_email IS 'Customer email for order notifications';
COMMENT ON COLUMN public.orders.customer_phone IS 'Customer phone for delivery coordination';
COMMENT ON COLUMN public.orders.customer_notes IS 'Notes/instructions from customer';
COMMENT ON COLUMN public.orders.admin_notes IS 'Internal admin notes about the order';
COMMENT ON COLUMN public.orders.confirmed_at IS 'Timestamp when order was confirmed';
COMMENT ON COLUMN public.orders.shipped_at IS 'Timestamp when order was shipped';
COMMENT ON COLUMN public.orders.delivered_at IS 'Timestamp when order was delivered';
COMMENT ON COLUMN public.orders.seller_notes IS 'Notes from seller about the order';
COMMENT ON COLUMN public.orders.accepted_at IS 'Timestamp when seller accepted the order';
COMMENT ON COLUMN public.orders.label_url IS 'URL to the shipping label PDF';
COMMENT ON COLUMN public.orders.shipping_cost_cents IS 'Shipping cost in cents (1 RSD = 100 cents) for precise calculations';
COMMENT ON COLUMN public.orders.shipping_method_id IS 'ID of selected delivery method (e.g., post_express_office, bex_courier)';
COMMENT ON COLUMN public.orders.shipping_details IS 'Provider-specific shipping details: {pickup_point_id, estimated_days, provider_order_id}';
COMMENT ON COLUMN public.orders.delivery_address_id IS 'Reference to user_addresses.id in svetubd (external FK)';
COMMENT ON COLUMN public.orders.delivery_address_snapshot IS 'Immutable copy of delivery address at order creation time';
COMMENT ON COLUMN public.orders.payment_provider IS 'Payment gateway provider: stripe, allsecure, or null for offline/COD';
COMMENT ON COLUMN public.orders.payment_session_id IS 'Checkout session ID from payment gateway (e.g., Stripe checkout session)';
COMMENT ON COLUMN public.orders.payment_intent_id IS 'Payment intent ID from gateway after successful payment';
COMMENT ON COLUMN public.orders.payment_idempotency_key IS 'Idempotency key for duplicate payment prevention';
COMMENT ON TABLE public.storefronts IS 'B2C storefronts (business stores) for marketplace';
COMMENT ON COLUMN public.storefronts.geo_strategy IS 'Location strategy: storefront_location, product_locations, or both';
COMMENT ON COLUMN public.storefronts.default_privacy_level IS 'Default privacy level for location: exact, approximate, or hidden';
COMMENT ON COLUMN public.storefronts.deleted_at IS 'Timestamp when storefront was soft deleted (NULL = active)';
COMMENT ON TABLE public.attribute_options IS 'Predefined options for select/multiselect attributes';
COMMENT ON TABLE public.attribute_search_cache IS 'Denormalized attribute cache for OpenSearch integration';
COMMENT ON TABLE public.attribute_values IS 'Predefined values for select/multiselect attributes';
COMMENT ON COLUMN public.attribute_values.attribute_id IS 'Foreign key to attributes table';
COMMENT ON COLUMN public.attribute_values.value IS 'Value identifier (e.g., "black", "xl", "new")';
COMMENT ON COLUMN public.attribute_values.label IS 'Localized labels: {"sr": "Crna", "en": "Black", "ru": "Чёрный"}';
COMMENT ON COLUMN public.attribute_values.metadata IS 'Optional metadata (e.g., {"hex": "#000000"})';
COMMENT ON TABLE public.attributes IS 'Unified attributes metadata - core definitions for all attribute types';
COMMENT ON TABLE public.brand_category_mapping IS 'Маппинг брендов на категории для автоматической детекции';
COMMENT ON COLUMN public.brand_category_mapping.brand_name IS 'Основное название бренда (нормализованное)';
COMMENT ON COLUMN public.brand_category_mapping.brand_aliases IS 'Альтернативные написания бренда (массив)';
COMMENT ON COLUMN public.brand_category_mapping.category_slug IS 'Slug категории из таблицы categories';
COMMENT ON COLUMN public.brand_category_mapping.confidence IS 'Уверенность маппинга (0.0-1.0, default 0.95)';
COMMENT ON COLUMN public.brand_category_mapping.is_verified IS 'Подтверждён ли маппинг вручную';
COMMENT ON TABLE public.cart_items IS 'Individual items in shopping carts. Supports both simple listings and variant-based products.';
COMMENT ON COLUMN public.cart_items.cart_id IS 'Shopping cart this item belongs to. Items cascade-deleted when cart is deleted.';
COMMENT ON COLUMN public.cart_items.listing_id IS 'Product listing. Always required.';
COMMENT ON COLUMN public.cart_items.variant_id IS 'Product variant (optional). For products with size/color/etc variants. NULL for simple products.';
COMMENT ON COLUMN public.cart_items.quantity IS 'Number of items. Must be > 0. Updated when user changes quantity.';
COMMENT ON COLUMN public.cart_items.price_snapshot IS 'Price per unit at add-to-cart time. Used to detect price changes before checkout.';
COMMENT ON COLUMN public.cart_items.updated_at IS 'Auto-updated when quantity or price changes. Last modification timestamp.';
COMMENT ON TABLE public.categories IS 'Marketplace categories with multilingual JSONB support (sr/en/ru)';
COMMENT ON COLUMN public.categories.level IS 'Hierarchy level: 1 (L1 top), 2 (L2 subcategory), 3 (L3 leaf)';
COMMENT ON COLUMN public.categories.path IS 'Full hierarchical path (slug-based): clothing/mens/tshirts';
COMMENT ON COLUMN public.categories.name IS 'Multilingual category name: {"sr": "...", "en": "...", "ru": "..."}';
COMMENT ON COLUMN public.categories.description IS 'Multilingual category description: {"sr": "...", "en": "...", "ru": "..."}';
COMMENT ON COLUMN public.categories.meta_title IS 'SEO meta title per locale: {"sr": "...", "en": "...", "ru": "..."}';
COMMENT ON COLUMN public.categories.meta_description IS 'SEO meta description per locale: {"sr": "...", "en": "...", "ru": "..."}';
COMMENT ON COLUMN public.categories.has_custom_ui IS 'Whether category has custom UI component';
COMMENT ON COLUMN public.categories.custom_ui_component IS 'Name of custom UI component for this category';
COMMENT ON TABLE public.category_ai_mapping IS 'Mapping table for AI-detected category names to database category IDs';
COMMENT ON COLUMN public.category_ai_mapping.ai_category_name IS 'Category name as returned by Claude AI (e.g., Fashion, Electronics)';
COMMENT ON COLUMN public.category_ai_mapping.target_category_id IS 'Target category ID in categories table';
COMMENT ON COLUMN public.category_ai_mapping.confidence_boost IS 'Confidence score boost (0.0-1.0) to add to detection';
COMMENT ON COLUMN public.category_ai_mapping.priority IS 'Priority for conflict resolution (higher = preferred)';
COMMENT ON TABLE public.category_attributes IS 'Category-specific attribute configurations and overrides';
COMMENT ON COLUMN public.category_attributes.category_id IS 'Foreign key to categories.id (UUID)';
COMMENT ON COLUMN public.category_attributes.is_searchable IS 'Is this attribute searchable in this category?';
COMMENT ON COLUMN public.category_attributes.is_filterable IS 'Is this attribute filterable in this category?';
COMMENT ON COLUMN public.category_attributes.category_options IS 'Category-specific options override (NULL = use global)';
COMMENT ON COLUMN public.category_attributes.custom_validation IS 'Category-specific validation rules';
COMMENT ON COLUMN public.category_attributes.custom_ui_settings IS 'Category-specific UI settings';
