-- Rollback: L3 Elektronika Categories

DELETE FROM categories WHERE slug IN (
  -- Pametni telefoni (5)
  'google-pixel-telefoni',
  'oneplus-telefoni',
  'realme-telefoni',
  'oppo-telefoni',
  'telefoni-budget-do-200e',

  -- Laptop racunari (7)
  'laptop-2-u-1',
  'laptop-chromebook',
  'laptop-macbook',
  'laptop-lenovo-thinkpad',
  'laptop-dell-xps',
  'laptop-hp-pavilion',
  'laptop-asus-rog',

  -- TV i video (15)
  'led-tv-32-43-inca',
  'led-tv-50-55-inca',
  'led-tv-65-75-inca',
  'oled-tv',
  'qled-tv',
  'smart-tv-android',
  'smart-tv-tizen',
  'soundbar-2-1',
  'soundbar-5-1',
  'bluetooth-zvucnici',
  'hi-fi-sistemi',
  'projektori-full-hd',
  'projektori-4k',
  'av-resiveri',
  'kucni-bioskop',

  -- Racunarske komponente (20)
  'graficke-rtx-4000',
  'graficke-rtx-3000',
  'graficke-gtx-1000',
  'graficke-amd-rx-7000',
  'graficke-amd-rx-6000',
  'procesor-intel-i9',
  'procesor-intel-i7',
  'procesor-intel-i5',
  'procesor-amd-ryzen-9',
  'procesor-amd-ryzen-7',
  'procesor-amd-ryzen-5',
  'ram-ddr5-32gb',
  'ram-ddr5-16gb',
  'ram-ddr4-16gb',
  'ram-ddr4-8gb',
  'ssd-nvme-1tb',
  'ssd-nvme-500gb',
  'ssd-sata-1tb',
  'maticna-ploca-intel-z790',
  'maticna-ploca-amd-x670',

  -- Gaming oprema (15)
  'playstation-5',
  'playstation-5-igre',
  'xbox-series-x',
  'xbox-series-s',
  'xbox-igre',
  'nintendo-switch',
  'nintendo-igre',
  'gejmpad-ps5',
  'gejmpad-xbox',
  'gaming-slusalice',
  'gaming-monitor-144hz',
  'gaming-monitor-240hz',
  'gaming-stolice',
  'rgb-rasveta',
  'streaming-mikrofon',

  -- Foto i video kamere (12)
  'dslr-canon',
  'dslr-nikon',
  'mirrorless-sony',
  'mirrorless-fujifilm',
  'action-kamera-gopro',
  'action-kamera-dji',
  'dron-sa-kamerom',
  '4k-video-kamera',
  'objektiv-za-canon',
  'objektiv-za-nikon',
  'stativ-foto-video',
  'foto-rasveta',

  -- Pametni satovi (8)
  'apple-watch-series',
  'apple-watch-ultra',
  'samsung-galaxy-watch',
  'garmin-fitness-sat',
  'xiaomi-mi-band',
  'xiaomi-watch',
  'huawei-watch-gt',
  'pametni-satovi-budget'
) AND level = 3;
