-- Migration: L3 Categories
-- Date: 2025-12-17

INSERT INTO categories (slug, name, description, meta_title, meta_description, parent_id, level, path, sort_order, icon, is_active)
VALUES
  (
    'samsung-galaxy-s',
    '{"sr": "Samsung Galaxy S serija", "en": "Samsung Galaxy S Series", "ru": "Samsung Galaxy S серия"}',
    '{"sr": "Samsung Galaxy S serija - najbolja ponuda", "en": "Samsung Galaxy S Series - best selection", "ru": "Samsung Galaxy S серия - лучший выбор"}',
    '{"sr": "Samsung Galaxy S serija | Vondi", "en": "Samsung Galaxy S Series | Vondi", "ru": "Samsung Galaxy S серия | Vondi"}',
    '{"sr": "Kupite Samsung Galaxy S serija na Vondi", "en": "Buy Samsung Galaxy S Series on Vondi", "ru": "Купите Samsung Galaxy S серия на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'pametni-telefoni' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'pametni-telefoni' AND level = 2) || '/samsung-galaxy-s',
    2,
    '📱',
    true
  ),
  (
    'samsung-galaxy-a',
    '{"sr": "Samsung Galaxy A serija", "en": "Samsung Galaxy A Series", "ru": "Samsung Galaxy A серия"}',
    '{"sr": "Samsung Galaxy A serija - najbolja ponuda", "en": "Samsung Galaxy A Series - best selection", "ru": "Samsung Galaxy A серия - лучший выбор"}',
    '{"sr": "Samsung Galaxy A serija | Vondi", "en": "Samsung Galaxy A Series | Vondi", "ru": "Samsung Galaxy A серия | Vondi"}',
    '{"sr": "Kupite Samsung Galaxy A serija na Vondi", "en": "Buy Samsung Galaxy A Series on Vondi", "ru": "Купите Samsung Galaxy A серия на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'pametni-telefoni' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'pametni-telefoni' AND level = 2) || '/samsung-galaxy-a',
    3,
    '📱',
    true
  ),
  (
    'apple-iphone-14-15',
    '{"sr": "Apple iPhone 14-15 incha, "en": "Apple iPhone 14-15 incha, "ru": "Apple iPhone 14-15 incha}',
    '{"sr": "Apple iPhone 14-15 - najbolja ponuda", "en": "Apple iPhone 14-15 - best selection", "ru": "Apple iPhone 14-15 - лучший выбор"}',
    '{"sr": "Apple iPhone 14-15 | Vondi", "en": "Apple iPhone 14-15 | Vondi", "ru": "Apple iPhone 14-15 | Vondi"}',
    '{"sr": "Kupite Apple iPhone 14-15 na Vondi", "en": "Buy Apple iPhone 14-15 on Vondi", "ru": "Купите Apple iPhone 14-15 на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'pametni-telefoni' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'pametni-telefoni' AND level = 2) || '/apple-iphone-14-15',
    4,
    '📱',
    true
  ),
  (
    'apple-iphone-11-12-13',
    '{"sr": "Apple iPhone 11-12-13 incha, "en": "Apple iPhone 11-12-13 incha, "ru": "Apple iPhone 11-12-13 incha}',
    '{"sr": "Apple iPhone 11-12-13 - najbolja ponuda", "en": "Apple iPhone 11-12-13 - best selection", "ru": "Apple iPhone 11-12-13 - лучший выбор"}',
    '{"sr": "Apple iPhone 11-12-13 | Vondi", "en": "Apple iPhone 11-12-13 | Vondi", "ru": "Apple iPhone 11-12-13 | Vondi"}',
    '{"sr": "Kupite Apple iPhone 11-12-13 na Vondi", "en": "Buy Apple iPhone 11-12-13 on Vondi", "ru": "Купите Apple iPhone 11-12-13 на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'pametni-telefoni' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'pametni-telefoni' AND level = 2) || '/apple-iphone-11-12-13',
    5,
    '📱',
    true
  ),
  (
    'xiaomi-redmi',
    '{"sr": "Xiaomi Redmi", "en": "Xiaomi Redmi", "ru": "Xiaomi Redmi"}',
    '{"sr": "Xiaomi Redmi - najbolja ponuda", "en": "Xiaomi Redmi - best selection", "ru": "Xiaomi Redmi - лучший выбор"}',
    '{"sr": "Xiaomi Redmi | Vondi", "en": "Xiaomi Redmi | Vondi", "ru": "Xiaomi Redmi | Vondi"}',
    '{"sr": "Kupite Xiaomi Redmi na Vondi", "en": "Buy Xiaomi Redmi on Vondi", "ru": "Купите Xiaomi Redmi на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'pametni-telefoni' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'pametni-telefoni' AND level = 2) || '/xiaomi-redmi',
    6,
    '📱',
    true
  ),
  (
    'xiaomi-poco',
    '{"sr": "Xiaomi POCO", "en": "Xiaomi POCO", "ru": "Xiaomi POCO"}',
    '{"sr": "Xiaomi POCO - najbolja ponuda", "en": "Xiaomi POCO - best selection", "ru": "Xiaomi POCO - лучший выбор"}',
    '{"sr": "Xiaomi POCO | Vondi", "en": "Xiaomi POCO | Vondi", "ru": "Xiaomi POCO | Vondi"}',
    '{"sr": "Kupite Xiaomi POCO na Vondi", "en": "Buy Xiaomi POCO on Vondi", "ru": "Купите Xiaomi POCO на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'pametni-telefoni' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'pametni-telefoni' AND level = 2) || '/xiaomi-poco',
    7,
    '📱',
    true
  ),
  (
    'huawei-p-serija',
    '{"sr": "Huawei P serija", "en": "Huawei P Series", "ru": "Huawei P серия"}',
    '{"sr": "Huawei P serija - najbolja ponuda", "en": "Huawei P Series - best selection", "ru": "Huawei P серия - лучший выбор"}',
    '{"sr": "Huawei P serija | Vondi", "en": "Huawei P Series | Vondi", "ru": "Huawei P серия | Vondi"}',
    '{"sr": "Kupite Huawei P serija na Vondi", "en": "Buy Huawei P Series on Vondi", "ru": "Купите Huawei P серия на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'pametni-telefoni' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'pametni-telefoni' AND level = 2) || '/huawei-p-serija',
    8,
    '📱',
    true
  ),
  (
    'oneplus-telefoni',
    '{"sr": "OnePlus telefoni", "en": "OnePlus Phones", "ru": "OnePlus телефоны"}',
    '{"sr": "OnePlus telefoni - najbolja ponuda", "en": "OnePlus Phones - best selection", "ru": "OnePlus телефоны - лучший выбор"}',
    '{"sr": "OnePlus telefoni | Vondi", "en": "OnePlus Phones | Vondi", "ru": "OnePlus телефоны | Vondi"}',
    '{"sr": "Kupite OnePlus telefoni na Vondi", "en": "Buy OnePlus Phones on Vondi", "ru": "Купите OnePlus телефоны на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'pametni-telefoni' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'pametni-telefoni' AND level = 2) || '/oneplus-telefoni',
    9,
    '📱',
    true
  ),
  (
    'google-pixel',
    '{"sr": "Google Pixel", "en": "Google Pixel", "ru": "Google Pixel"}',
    '{"sr": "Google Pixel - najbolja ponuda", "en": "Google Pixel - best selection", "ru": "Google Pixel - лучший выбор"}',
    '{"sr": "Google Pixel | Vondi", "en": "Google Pixel | Vondi", "ru": "Google Pixel | Vondi"}',
    '{"sr": "Kupite Google Pixel na Vondi", "en": "Buy Google Pixel on Vondi", "ru": "Купите Google Pixel на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'pametni-telefoni' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'pametni-telefoni' AND level = 2) || '/google-pixel',
    10,
    '📱',
    true
  ),
  (
    'telefoni-do-150eur',
    '{"sr": "Telefoni do 150 EUR", "en": "Phones under 150 EUR", "ru": "Телефоны до 150 EUR"}',
    '{"sr": "Telefoni do 150 EUR - najbolja ponuda", "en": "Phones under 150 EUR - best selection", "ru": "Телефоны до 150 EUR - лучший выбор"}',
    '{"sr": "Telefoni do 150 EUR | Vondi", "en": "Phones under 150 EUR | Vondi", "ru": "Телефоны до 150 EUR | Vondi"}',
    '{"sr": "Kupite Telefoni do 150 EUR na Vondi", "en": "Buy Phones under 150 EUR on Vondi", "ru": "Купите Телефоны до 150 EUR на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'pametni-telefoni' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'pametni-telefoni' AND level = 2) || '/telefoni-do-150eur',
    11,
    '💰',
    true
  ),
  (
    'telefoni-150-300eur',
    '{"sr": "Telefoni 150-300 EUR", "en": "Phones 150-300 EUR", "ru": "Телефоны 150-300 EUR"}',
    '{"sr": "Telefoni 150-300 EUR - najbolja ponuda", "en": "Phones 150-300 EUR - best selection", "ru": "Телефоны 150-300 EUR - лучший выбор"}',
    '{"sr": "Telefoni 150-300 EUR | Vondi", "en": "Phones 150-300 EUR | Vondi", "ru": "Телефоны 150-300 EUR | Vondi"}',
    '{"sr": "Kupite Telefoni 150-300 EUR na Vondi", "en": "Buy Phones 150-300 EUR on Vondi", "ru": "Купите Телефоны 150-300 EUR на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'pametni-telefoni' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'pametni-telefoni' AND level = 2) || '/telefoni-150-300eur',
    12,
    '💰',
    true
  ),
  (
    'telefoni-preko-300eur',
    '{"sr": "Telefoni preko 300 EUR", "en": "Phones over 300 EUR", "ru": "Телефоны свыше 300 EUR"}',
    '{"sr": "Telefoni preko 300 EUR - najbolja ponuda", "en": "Phones over 300 EUR - best selection", "ru": "Телефоны свыше 300 EUR - лучший выбор"}',
    '{"sr": "Telefoni preko 300 EUR | Vondi", "en": "Phones over 300 EUR | Vondi", "ru": "Телефоны свыше 300 EUR | Vondi"}',
    '{"sr": "Kupite Telefoni preko 300 EUR na Vondi", "en": "Buy Phones over 300 EUR on Vondi", "ru": "Купите Телефоны свыше 300 EUR на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'pametni-telefoni' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'pametni-telefoni' AND level = 2) || '/telefoni-preko-300eur',
    13,
    '💰',
    true
  ),
  (
    'maske-samsung',
    '{"sr": "Maske za Samsung", "en": "Samsung Cases", "ru": "Чехлы для Samsung"}',
    '{"sr": "Maske za Samsung - najbolja ponuda", "en": "Samsung Cases - best selection", "ru": "Чехлы для Samsung - лучший выбор"}',
    '{"sr": "Maske za Samsung | Vondi", "en": "Samsung Cases | Vondi", "ru": "Чехлы для Samsung | Vondi"}',
    '{"sr": "Kupite Maske za Samsung na Vondi", "en": "Buy Samsung Cases on Vondi", "ru": "Купите Чехлы для Samsung на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'pametni-telefoni' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'pametni-telefoni' AND level = 2) || '/maske-samsung',
    14,
    '📱',
    true
  ),
  (
    'maske-iphone',
    '{"sr": "Maske za iPhone", "en": "iPhone Cases", "ru": "Чехлы для iPhone"}',
    '{"sr": "Maske za iPhone - najbolja ponuda", "en": "iPhone Cases - best selection", "ru": "Чехлы для iPhone - лучший выбор"}',
    '{"sr": "Maske za iPhone | Vondi", "en": "iPhone Cases | Vondi", "ru": "Чехлы для iPhone | Vondi"}',
    '{"sr": "Kupite Maske za iPhone na Vondi", "en": "Buy iPhone Cases on Vondi", "ru": "Купите Чехлы для iPhone на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'pametni-telefoni' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'pametni-telefoni' AND level = 2) || '/maske-iphone',
    15,
    '📱',
    true
  ),
  (
    'zastitno-staklo',
    '{"sr": "Zaštitno staklo", "en": "Screen Protectors", "ru": "Защитные стекла"}',
    '{"sr": "Zaštitno staklo - najbolja ponuda", "en": "Screen Protectors - best selection", "ru": "Защитные стекла - лучший выбор"}',
    '{"sr": "Zaštitno staklo | Vondi", "en": "Screen Protectors | Vondi", "ru": "Защитные стекла | Vondi"}',
    '{"sr": "Kupite Zaštitno staklo na Vondi", "en": "Buy Screen Protectors on Vondi", "ru": "Купите Защитные стекла на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'pametni-telefoni' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'pametni-telefoni' AND level = 2) || '/zastitno-staklo',
    16,
    '🛡️',
    true
  ),
  (
    'laptop-gejming',
    '{"sr": "Gejming laptopovi", "en": "Gaming Laptops", "ru": "Игровые ноутбуки"}',
    '{"sr": "Gejming laptopovi - najbolja ponuda", "en": "Gaming Laptops - best selection", "ru": "Игровые ноутбуки - лучший выбор"}',
    '{"sr": "Gejming laptopovi | Vondi", "en": "Gaming Laptops | Vondi", "ru": "Игровые ноутбуки | Vondi"}',
    '{"sr": "Kupite Gejming laptopovi na Vondi", "en": "Buy Gaming Laptops on Vondi", "ru": "Купите Игровые ноутбуки на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'laptop-racunari' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'laptop-racunari' AND level = 2) || '/laptop-gejming',
    17,
    '🎮',
    true
  ),
  (
    'laptop-poslovni',
    '{"sr": "Poslovni laptopovi", "en": "Business Laptops", "ru": "Бизнес ноутбуки"}',
    '{"sr": "Poslovni laptopovi - najbolja ponuda", "en": "Business Laptops - best selection", "ru": "Бизнес ноутбуки - лучший выбор"}',
    '{"sr": "Poslovni laptopovi | Vondi", "en": "Business Laptops | Vondi", "ru": "Бизнес ноутбуки | Vondi"}',
    '{"sr": "Kupite Poslovni laptopovi na Vondi", "en": "Buy Business Laptops on Vondi", "ru": "Купите Бизнес ноутбуки на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'laptop-racunari' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'laptop-racunari' AND level = 2) || '/laptop-poslovni',
    18,
    '💼',
    true
  ),
  (
    'ultrabook',
    '{"sr": "Ultrabukovi", "en": "Ultrabooks", "ru": "Ультрабуки"}',
    '{"sr": "Ultrabukovi - najbolja ponuda", "en": "Ultrabooks - best selection", "ru": "Ультрабуки - лучший выбор"}',
    '{"sr": "Ultrabukovi | Vondi", "en": "Ultrabooks | Vondi", "ru": "Ультрабуки | Vondi"}',
    '{"sr": "Kupite Ultrabukovi na Vondi", "en": "Buy Ultrabooks on Vondi", "ru": "Купите Ультрабуки на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'laptop-racunari' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'laptop-racunari' AND level = 2) || '/ultrabook',
    19,
    '💻',
    true
  ),
  (
    'macbook',
    '{"sr": "MacBook", "en": "MacBook", "ru": "MacBook"}',
    '{"sr": "MacBook - najbolja ponuda", "en": "MacBook - best selection", "ru": "MacBook - лучший выбор"}',
    '{"sr": "MacBook | Vondi", "en": "MacBook | Vondi", "ru": "MacBook | Vondi"}',
    '{"sr": "Kupite MacBook na Vondi", "en": "Buy MacBook on Vondi", "ru": "Купите MacBook на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'laptop-racunari' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'laptop-racunari' AND level = 2) || '/macbook',
    20,
    '🍎',
    true
  ),
  (
    'laptop-15-inch',
    '{"sr": "Laptopovi 15 incha", "en": "Laptops 15 incha", "ru": "Ноутбуки 15 incha"}',
    '{"sr": "Laptopovi 15 incha - najbolja ponuda", "en": "Laptops 15 incha - best selection", "ru": "Ноутбуки 15 incha - лучший выбор"}',
    '{"sr": "Laptopovi 15 incha | Vondi", "en": "Laptops 15 incha | Vondi", "ru": "Ноутбуки 15 incha | Vondi"}',
    '{"sr": "Kupite Laptopovi 15 incha na Vondi", "en": "Buy Laptops 15 incha on Vondi", "ru": "Купите Ноутбуки 15 incha на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'laptop-racunari' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'laptop-racunari' AND level = 2) || '/laptop-15-inch',
    21,
    '💻',
    true
  ),
  (
    'laptop-17-inch',
    '{"sr": "Laptopovi 17 incha", "en": "Laptops 17 incha", "ru": "Ноутбуки 17 incha"}',
    '{"sr": "Laptopovi 17 incha - najbolja ponuda", "en": "Laptops 17 incha - best selection", "ru": "Ноутбуки 17 incha - лучший выбор"}',
    '{"sr": "Laptopovi 17 incha | Vondi", "en": "Laptops 17 incha | Vondi", "ru": "Ноутбуки 17 incha | Vondi"}',
    '{"sr": "Kupite Laptopovi 17 incha na Vondi", "en": "Buy Laptops 17 incha on Vondi", "ru": "Купите Ноутбуки 17 incha на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'laptop-racunari' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'laptop-racunari' AND level = 2) || '/laptop-17-inch',
    22,
    '💻',
    true
  ),
  (
    'laptop-do-500eur',
    '{"sr": "Laptopovi do 500 EUR", "en": "Laptops under 500 EUR", "ru": "Ноутбуки до 500 EUR"}',
    '{"sr": "Laptopovi do 500 EUR - najbolja ponuda", "en": "Laptops under 500 EUR - best selection", "ru": "Ноутбуки до 500 EUR - лучший выбор"}',
    '{"sr": "Laptopovi do 500 EUR | Vondi", "en": "Laptops under 500 EUR | Vondi", "ru": "Ноутбуки до 500 EUR | Vondi"}',
    '{"sr": "Kupite Laptopovi do 500 EUR na Vondi", "en": "Buy Laptops under 500 EUR on Vondi", "ru": "Купите Ноутбуки до 500 EUR на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'laptop-racunari' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'laptop-racunari' AND level = 2) || '/laptop-do-500eur',
    23,
    '💰',
    true
  ),
  (
    'laptop-500-1000eur',
    '{"sr": "Laptopovi 500-1000 EUR", "en": "Laptops 500-1000 EUR", "ru": "Ноутбуки 500-1000 EUR"}',
    '{"sr": "Laptopovi 500-1000 EUR - najbolja ponuda", "en": "Laptops 500-1000 EUR - best selection", "ru": "Ноутбуки 500-1000 EUR - лучший выбор"}',
    '{"sr": "Laptopovi 500-1000 EUR | Vondi", "en": "Laptops 500-1000 EUR | Vondi", "ru": "Ноутбуки 500-1000 EUR | Vondi"}',
    '{"sr": "Kupite Laptopovi 500-1000 EUR na Vondi", "en": "Buy Laptops 500-1000 EUR on Vondi", "ru": "Купите Ноутбуки 500-1000 EUR на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'laptop-racunari' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'laptop-racunari' AND level = 2) || '/laptop-500-1000eur',
    24,
    '💰',
    true
  ),
  (
    'laptop-preko-1000eur',
    '{"sr": "Laptopovi preko 1000 EUR", "en": "Laptops over 1000 EUR", "ru": "Ноутбуки свыше 1000 EUR"}',
    '{"sr": "Laptopovi preko 1000 EUR - najbolja ponuda", "en": "Laptops over 1000 EUR - best selection", "ru": "Ноутбуки свыше 1000 EUR - лучший выбор"}',
    '{"sr": "Laptopovi preko 1000 EUR | Vondi", "en": "Laptops over 1000 EUR | Vondi", "ru": "Ноутбуки свыше 1000 EUR | Vondi"}',
    '{"sr": "Kupite Laptopovi preko 1000 EUR na Vondi", "en": "Buy Laptops over 1000 EUR on Vondi", "ru": "Купите Ноутбуки свыше 1000 EUR на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'laptop-racunari' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'laptop-racunari' AND level = 2) || '/laptop-preko-1000eur',
    25,
    '💰',
    true
  ),
  (
    'laptop-dodaci',
    '{"sr": "Dodaci za laptop", "en": "Laptop Accessories", "ru": "Аксессуары для ноутбуков"}',
    '{"sr": "Dodaci za laptop - najbolja ponuda", "en": "Laptop Accessories - best selection", "ru": "Аксессуары для ноутбуков - лучший выбор"}',
    '{"sr": "Dodaci za laptop | Vondi", "en": "Laptop Accessories | Vondi", "ru": "Аксессуары для ноутбуков | Vondi"}',
    '{"sr": "Kupite Dodaci za laptop na Vondi", "en": "Buy Laptop Accessories on Vondi", "ru": "Купите Аксессуары для ноутбуков на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'laptop-racunari' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'laptop-racunari' AND level = 2) || '/laptop-dodaci',
    26,
    '💼',
    true
  ),
  (
    'torbe-laptop',
    '{"sr": "Torbe za laptop", "en": "Laptop Bags", "ru": "Сумки для ноутбуков"}',
    '{"sr": "Torbe za laptop - najbolja ponuda", "en": "Laptop Bags - best selection", "ru": "Сумки для ноутбуков - лучший выбор"}',
    '{"sr": "Torbe za laptop | Vondi", "en": "Laptop Bags | Vondi", "ru": "Сумки для ноутбуков | Vondi"}',
    '{"sr": "Kupite Torbe za laptop na Vondi", "en": "Buy Laptop Bags on Vondi", "ru": "Купите Сумки для ноутбуков на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'laptop-racunari' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'laptop-racunari' AND level = 2) || '/torbe-laptop',
    27,
    '👜',
    true
  ),
  (
    'hladnjaci-laptop',
    '{"sr": "Hladnjaci za laptop", "en": "Laptop Cooling Pads", "ru": "Охлаждение для ноутбуков"}',
    '{"sr": "Hladnjaci za laptop - najbolja ponuda", "en": "Laptop Cooling Pads - best selection", "ru": "Охлаждение для ноутбуков - лучший выбор"}',
    '{"sr": "Hladnjaci za laptop | Vondi", "en": "Laptop Cooling Pads | Vondi", "ru": "Охлаждение для ноутбуков | Vondi"}',
    '{"sr": "Kupite Hladnjaci za laptop na Vondi", "en": "Buy Laptop Cooling Pads on Vondi", "ru": "Купите Охлаждение для ноутбуков на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'laptop-racunari' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'laptop-racunari' AND level = 2) || '/hladnjaci-laptop',
    28,
    '❄️',
    true
  ),
  (
    'smart-tv-55',
    '{"sr": "Smart TV 55 incha", "en": "Smart TV 55 incha", "ru": "Smart TV 55 incha"}',
    '{"sr": "Smart TV 55 incha - najbolja ponuda", "en": "Smart TV 55 incha - best selection", "ru": "Smart TV 55 incha - лучший выбор"}',
    '{"sr": "Smart TV 55 incha | Vondi", "en": "Smart TV 55 incha | Vondi", "ru": "Smart TV 55 incha | Vondi"}',
    '{"sr": "Kupite Smart TV 55 incha na Vondi", "en": "Buy Smart TV 55 incha on Vondi", "ru": "Купите Smart TV 55 incha на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'tv-i-video' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'tv-i-video' AND level = 2) || '/smart-tv-55',
    29,
    '📺',
    true
  ),
  (
    'smart-tv-65',
    '{"sr": "Smart TV 65 incha", "en": "Smart TV 65 incha", "ru": "Smart TV 65 incha"}',
    '{"sr": "Smart TV 65 incha - najbolja ponuda", "en": "Smart TV 65 incha - best selection", "ru": "Smart TV 65 incha - лучший выбор"}',
    '{"sr": "Smart TV 65 incha | Vondi", "en": "Smart TV 65 incha | Vondi", "ru": "Smart TV 65 incha | Vondi"}',
    '{"sr": "Kupite Smart TV 65 incha na Vondi", "en": "Buy Smart TV 65 incha on Vondi", "ru": "Купите Smart TV 65 incha на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'tv-i-video' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'tv-i-video' AND level = 2) || '/smart-tv-65',
    30,
    '📺',
    true
  ),
  (
    'smart-tv-75',
    '{"sr": "Smart TV 75 incha", "en": "Smart TV 75 incha", "ru": "Smart TV 75 incha"}',
    '{"sr": "Smart TV 75 incha - najbolja ponuda", "en": "Smart TV 75 incha - best selection", "ru": "Smart TV 75 incha - лучший выбор"}',
    '{"sr": "Smart TV 75 incha | Vondi", "en": "Smart TV 75 incha | Vondi", "ru": "Smart TV 75 incha | Vondi"}',
    '{"sr": "Kupite Smart TV 75 incha na Vondi", "en": "Buy Smart TV 75 incha on Vondi", "ru": "Купите Smart TV 75 incha на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'tv-i-video' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'tv-i-video' AND level = 2) || '/smart-tv-75',
    31,
    '📺',
    true
  ),
  (
    'oled-tv',
    '{"sr": "OLED TV", "en": "OLED TV", "ru": "OLED TV"}',
    '{"sr": "OLED TV - najbolja ponuda", "en": "OLED TV - best selection", "ru": "OLED TV - лучший выбор"}',
    '{"sr": "OLED TV | Vondi", "en": "OLED TV | Vondi", "ru": "OLED TV | Vondi"}',
    '{"sr": "Kupite OLED TV na Vondi", "en": "Buy OLED TV on Vondi", "ru": "Купите OLED TV на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'tv-i-video' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'tv-i-video' AND level = 2) || '/oled-tv',
    32,
    '📺',
    true
  ),
  (
    'qled-tv',
    '{"sr": "QLED TV", "en": "QLED TV", "ru": "QLED TV"}',
    '{"sr": "QLED TV - najbolja ponuda", "en": "QLED TV - best selection", "ru": "QLED TV - лучший выбор"}',
    '{"sr": "QLED TV | Vondi", "en": "QLED TV | Vondi", "ru": "QLED TV | Vondi"}',
    '{"sr": "Kupite QLED TV na Vondi", "en": "Buy QLED TV on Vondi", "ru": "Купите QLED TV на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'tv-i-video' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'tv-i-video' AND level = 2) || '/qled-tv',
    33,
    '📺',
    true
  ),
  (
    '4k-tv',
    '{"sr": "4K Ultra HD TV", "en": "4K Ultra HD TV", "ru": "4K Ultra HD TV"}',
    '{"sr": "4K Ultra HD TV - najbolja ponuda", "en": "4K Ultra HD TV - best selection", "ru": "4K Ultra HD TV - лучший выбор"}',
    '{"sr": "4K Ultra HD TV | Vondi", "en": "4K Ultra HD TV | Vondi", "ru": "4K Ultra HD TV | Vondi"}',
    '{"sr": "Kupite 4K Ultra HD TV na Vondi", "en": "Buy 4K Ultra HD TV on Vondi", "ru": "Купите 4K Ultra HD TV на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'tv-i-video' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'tv-i-video' AND level = 2) || '/4k-tv',
    34,
    '📺',
    true
  ),
  (
    '8k-tv',
    '{"sr": "8K TV", "en": "8K TV", "ru": "8K TV"}',
    '{"sr": "8K TV - najbolja ponuda", "en": "8K TV - best selection", "ru": "8K TV - лучший выбор"}',
    '{"sr": "8K TV | Vondi", "en": "8K TV | Vondi", "ru": "8K TV | Vondi"}',
    '{"sr": "Kupite 8K TV na Vondi", "en": "Buy 8K TV on Vondi", "ru": "Купите 8K TV на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'tv-i-video' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'tv-i-video' AND level = 2) || '/8k-tv',
    35,
    '📺',
    true
  ),
  (
    'projektori-4k',
    '{"sr": "Projektori 4K", "en": "4K Projectors", "ru": "Проекторы 4K"}',
    '{"sr": "Projektori 4K - najbolja ponuda", "en": "4K Projectors - best selection", "ru": "Проекторы 4K - лучший выбор"}',
    '{"sr": "Projektori 4K | Vondi", "en": "4K Projectors | Vondi", "ru": "Проекторы 4K | Vondi"}',
    '{"sr": "Kupite Projektori 4K na Vondi", "en": "Buy 4K Projectors on Vondi", "ru": "Купите Проекторы 4K на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'tv-i-video' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'tv-i-video' AND level = 2) || '/projektori-4k',
    36,
    '🎬',
    true
  ),
  (
    'soundbar',
    '{"sr": "Soundbar sistemi", "en": "Soundbar Systems", "ru": "Саундбары"}',
    '{"sr": "Soundbar sistemi - najbolja ponuda", "en": "Soundbar Systems - best selection", "ru": "Саундбары - лучший выбор"}',
    '{"sr": "Soundbar sistemi | Vondi", "en": "Soundbar Systems | Vondi", "ru": "Саундбары | Vondi"}',
    '{"sr": "Kupite Soundbar sistemi na Vondi", "en": "Buy Soundbar Systems on Vondi", "ru": "Купите Саундбары на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'tv-i-video' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'tv-i-video' AND level = 2) || '/soundbar',
    37,
    '🔊',
    true
  ),
  (
    'home-cinema',
    '{"sr": "Home cinema sistemi", "en": "Home Cinema Systems", "ru": "Домашний кинотеатр"}',
    '{"sr": "Home cinema sistemi - najbolja ponuda", "en": "Home Cinema Systems - best selection", "ru": "Домашний кинотеатр - лучший выбор"}',
    '{"sr": "Home cinema sistemi | Vondi", "en": "Home Cinema Systems | Vondi", "ru": "Домашний кинотеатр | Vondi"}',
    '{"sr": "Kupite Home cinema sistemi na Vondi", "en": "Buy Home Cinema Systems on Vondi", "ru": "Купите Домашний кинотеатр на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'tv-i-video' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'tv-i-video' AND level = 2) || '/home-cinema',
    38,
    '🎭',
    true
  ),
  (
    'streaming-box',
    '{"sr": "Streaming box uređaji", "en": "Streaming Boxes", "ru": "Стриминг-приставки"}',
    '{"sr": "Streaming box uređaji - najbolja ponuda", "en": "Streaming Boxes - best selection", "ru": "Стриминг-приставки - лучший выбор"}',
    '{"sr": "Streaming box uređaji | Vondi", "en": "Streaming Boxes | Vondi", "ru": "Стриминг-приставки | Vondi"}',
    '{"sr": "Kupite Streaming box uređaji na Vondi", "en": "Buy Streaming Boxes on Vondi", "ru": "Купите Стриминг-приставки на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'tv-i-video' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'tv-i-video' AND level = 2) || '/streaming-box',
    39,
    '📦',
    true
  ),
  (
    'bluetooth-zvucnici',
    '{"sr": "Bluetooth zvučnici", "en": "Bluetooth Speakers", "ru": "Bluetooth колонки"}',
    '{"sr": "Bluetooth zvučnici - najbolja ponuda", "en": "Bluetooth Speakers - best selection", "ru": "Bluetooth колонки - лучший выбор"}',
    '{"sr": "Bluetooth zvučnici | Vondi", "en": "Bluetooth Speakers | Vondi", "ru": "Bluetooth колонки | Vondi"}',
    '{"sr": "Kupite Bluetooth zvučnici na Vondi", "en": "Buy Bluetooth Speakers on Vondi", "ru": "Купите Bluetooth колонки на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'audio-oprema' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'audio-oprema' AND level = 2) || '/bluetooth-zvucnici',
    40,
    '🔊',
    true
  ),
  (
    'slusalice-wireless',
    '{"sr": "Wireless slušalice", "en": "Wireless Headphones", "ru": "Беспроводные наушники"}',
    '{"sr": "Wireless slušalice - najbolja ponuda", "en": "Wireless Headphones - best selection", "ru": "Беспроводные наушники - лучший выбор"}',
    '{"sr": "Wireless slušalice | Vondi", "en": "Wireless Headphones | Vondi", "ru": "Беспроводные наушники | Vondi"}',
    '{"sr": "Kupite Wireless slušalice na Vondi", "en": "Buy Wireless Headphones on Vondi", "ru": "Купите Беспроводные наушники на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'audio-oprema' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'audio-oprema' AND level = 2) || '/slusalice-wireless',
    41,
    '🎧',
    true
  ),
  (
    'slusalice-anc',
    '{"sr": "Slušalice sa ANC", "en": "ANC Headphones", "ru": "Наушники с ANC"}',
    '{"sr": "Slušalice sa ANC - najbolja ponuda", "en": "ANC Headphones - best selection", "ru": "Наушники с ANC - лучший выбор"}',
    '{"sr": "Slušalice sa ANC | Vondi", "en": "ANC Headphones | Vondi", "ru": "Наушники с ANC | Vondi"}',
    '{"sr": "Kupite Slušalice sa ANC na Vondi", "en": "Buy ANC Headphones on Vondi", "ru": "Купите Наушники с ANC на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'audio-oprema' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'audio-oprema' AND level = 2) || '/slusalice-anc',
    42,
    '🎧',
    true
  ),
  (
    'slusalice-gaming',
    '{"sr": "Gaming slušalice", "en": "Gaming Headsets", "ru": "Игровые наушники"}',
    '{"sr": "Gaming slušalice - najbolja ponuda", "en": "Gaming Headsets - best selection", "ru": "Игровые наушники - лучший выбор"}',
    '{"sr": "Gaming slušalice | Vondi", "en": "Gaming Headsets | Vondi", "ru": "Игровые наушники | Vondi"}',
    '{"sr": "Kupite Gaming slušalice na Vondi", "en": "Buy Gaming Headsets on Vondi", "ru": "Купите Игровые наушники на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'audio-oprema' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'audio-oprema' AND level = 2) || '/slusalice-gaming',
    43,
    '🎮',
    true
  ),
  (
    'slusalice-in-ear',
    '{"sr": "In-ear slušalice", "en": "In-ear Headphones", "ru": "Внутриканальные наушники"}',
    '{"sr": "In-ear slušalice - najbolja ponuda", "en": "In-ear Headphones - best selection", "ru": "Внутриканальные наушники - лучший выбор"}',
    '{"sr": "In-ear slušalice | Vondi", "en": "In-ear Headphones | Vondi", "ru": "Внутриканальные наушники | Vondi"}',
    '{"sr": "Kupite In-ear slušalice na Vondi", "en": "Buy In-ear Headphones on Vondi", "ru": "Купите Внутриканальные наушники на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'audio-oprema' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'audio-oprema' AND level = 2) || '/slusalice-in-ear',
    44,
    '🎧',
    true
  ),
  (
    'zvucnici-polica',
    '{"sr": "Zvučnici za policu", "en": "Bookshelf Speakers", "ru": "Полочные колонки"}',
    '{"sr": "Zvučnici za policu - najbolja ponuda", "en": "Bookshelf Speakers - best selection", "ru": "Полочные колонки - лучший выбор"}',
    '{"sr": "Zvučnici za policu | Vondi", "en": "Bookshelf Speakers | Vondi", "ru": "Полочные колонки | Vondi"}',
    '{"sr": "Kupite Zvučnici za policu na Vondi", "en": "Buy Bookshelf Speakers on Vondi", "ru": "Купите Полочные колонки на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'audio-oprema' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'audio-oprema' AND level = 2) || '/zvucnici-polica',
    45,
    '🔊',
    true
  ),
  (
    'karaoke-sistemi',
    '{"sr": "Karaoke sistemi", "en": "Karaoke Systems", "ru": "Караоке системы"}',
    '{"sr": "Karaoke sistemi - najbolja ponuda", "en": "Karaoke Systems - best selection", "ru": "Караоке системы - лучший выбор"}',
    '{"sr": "Karaoke sistemi | Vondi", "en": "Karaoke Systems | Vondi", "ru": "Караоке системы | Vondi"}',
    '{"sr": "Kupite Karaoke sistemi na Vondi", "en": "Buy Karaoke Systems on Vondi", "ru": "Купите Караоке системы на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'audio-oprema' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'audio-oprema' AND level = 2) || '/karaoke-sistemi',
    46,
    '🎤',
    true
  ),
  (
    'cd-plejeri',
    '{"sr": "CD plejeri", "en": "CD Players", "ru": "CD плееры"}',
    '{"sr": "CD plejeri - najbolja ponuda", "en": "CD Players - best selection", "ru": "CD плееры - лучший выбор"}',
    '{"sr": "CD plejeri | Vondi", "en": "CD Players | Vondi", "ru": "CD плееры | Vondi"}',
    '{"sr": "Kupite CD plejeri na Vondi", "en": "Buy CD Players on Vondi", "ru": "Купите CD плееры на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'audio-oprema' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'audio-oprema' AND level = 2) || '/cd-plejeri',
    47,
    '💿',
    true
  ),
  (
    'vinilploce-plejeri',
    '{"sr": "Plejeri za vinilploče", "en": "Turntables", "ru": "Проигрыватели винила"}',
    '{"sr": "Plejeri za vinilploče - najbolja ponuda", "en": "Turntables - best selection", "ru": "Проигрыватели винила - лучший выбор"}',
    '{"sr": "Plejeri za vinilploče | Vondi", "en": "Turntables | Vondi", "ru": "Проигрыватели винила | Vondi"}',
    '{"sr": "Kupite Plejeri za vinilploče na Vondi", "en": "Buy Turntables on Vondi", "ru": "Купите Проигрыватели винила на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'audio-oprema' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'audio-oprema' AND level = 2) || '/vinilploce-plejeri',
    48,
    '🎵',
    true
  ),
  (
    'dslr-kamere',
    '{"sr": "DSLR kamere", "en": "DSLR Cameras", "ru": "DSLR камеры"}',
    '{"sr": "DSLR kamere - najbolja ponuda", "en": "DSLR Cameras - best selection", "ru": "DSLR камеры - лучший выбор"}',
    '{"sr": "DSLR kamere | Vondi", "en": "DSLR Cameras | Vondi", "ru": "DSLR камеры | Vondi"}',
    '{"sr": "Kupite DSLR kamere na Vondi", "en": "Buy DSLR Cameras on Vondi", "ru": "Купите DSLR камеры на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'foto-i-video-kamere' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'foto-i-video-kamere' AND level = 2) || '/dslr-kamere',
    49,
    '📷',
    true
  ),
  (
    'mirrorless-kamere',
    '{"sr": "Mirrorless kamere", "en": "Mirrorless Cameras", "ru": "Беззеркальные камеры"}',
    '{"sr": "Mirrorless kamere - najbolja ponuda", "en": "Mirrorless Cameras - best selection", "ru": "Беззеркальные камеры - лучший выбор"}',
    '{"sr": "Mirrorless kamere | Vondi", "en": "Mirrorless Cameras | Vondi", "ru": "Беззеркальные камеры | Vondi"}',
    '{"sr": "Kupite Mirrorless kamere na Vondi", "en": "Buy Mirrorless Cameras on Vondi", "ru": "Купите Беззеркальные камеры на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'foto-i-video-kamere' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'foto-i-video-kamere' AND level = 2) || '/mirrorless-kamere',
    50,
    '📷',
    true
  ),
  (
    'akcione-kamere',
    '{"sr": "Akcione kamere", "en": "Action Cameras", "ru": "Экшн-камеры"}',
    '{"sr": "Akcione kamere - najbolja ponuda", "en": "Action Cameras - best selection", "ru": "Экшн-камеры - лучший выбор"}',
    '{"sr": "Akcione kamere | Vondi", "en": "Action Cameras | Vondi", "ru": "Экшн-камеры | Vondi"}',
    '{"sr": "Kupite Akcione kamere na Vondi", "en": "Buy Action Cameras on Vondi", "ru": "Купите Экшн-камеры на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'foto-i-video-kamere' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'foto-i-video-kamere' AND level = 2) || '/akcione-kamere',
    51,
    '🎬',
    true
  ),
  (
    'gopro',
    '{"sr": "GoPro", "en": "GoPro", "ru": "GoPro"}',
    '{"sr": "GoPro - najbolja ponuda", "en": "GoPro - best selection", "ru": "GoPro - лучший выбор"}',
    '{"sr": "GoPro | Vondi", "en": "GoPro | Vondi", "ru": "GoPro | Vondi"}',
    '{"sr": "Kupite GoPro na Vondi", "en": "Buy GoPro on Vondi", "ru": "Купите GoPro на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'foto-i-video-kamere' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'foto-i-video-kamere' AND level = 2) || '/gopro',
    52,
    '📹',
    true
  ),
  (
    'video-kamere-4k',
    '{"sr": "Video kamere 4K", "en": "4K Video Cameras", "ru": "Видеокамеры 4K"}',
    '{"sr": "Video kamere 4K - najbolja ponuda", "en": "4K Video Cameras - best selection", "ru": "Видеокамеры 4K - лучший выбор"}',
    '{"sr": "Video kamere 4K | Vondi", "en": "4K Video Cameras | Vondi", "ru": "Видеокамеры 4K | Vondi"}',
    '{"sr": "Kupite Video kamere 4K na Vondi", "en": "Buy 4K Video Cameras on Vondi", "ru": "Купите Видеокамеры 4K на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'foto-i-video-kamere' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'foto-i-video-kamere' AND level = 2) || '/video-kamere-4k',
    53,
    '🎥',
    true
  ),
  (
    'objektivi-canon',
    '{"sr": "Objektivi za Canon", "en": "Canon Lenses", "ru": "Объективы Canon"}',
    '{"sr": "Objektivi za Canon - najbolja ponuda", "en": "Canon Lenses - best selection", "ru": "Объективы Canon - лучший выбор"}',
    '{"sr": "Objektivi za Canon | Vondi", "en": "Canon Lenses | Vondi", "ru": "Объективы Canon | Vondi"}',
    '{"sr": "Kupite Objektivi za Canon na Vondi", "en": "Buy Canon Lenses on Vondi", "ru": "Купите Объективы Canon на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'foto-i-video-kamere' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'foto-i-video-kamere' AND level = 2) || '/objektivi-canon',
    54,
    '🔍',
    true
  ),
  (
    'objektivi-nikon',
    '{"sr": "Objektivi za Nikon", "en": "Nikon Lenses", "ru": "Объективы Nikon"}',
    '{"sr": "Objektivi za Nikon - najbolja ponuda", "en": "Nikon Lenses - best selection", "ru": "Объективы Nikon - лучший выбор"}',
    '{"sr": "Objektivi za Nikon | Vondi", "en": "Nikon Lenses | Vondi", "ru": "Объективы Nikon | Vondi"}',
    '{"sr": "Kupite Objektivi za Nikon na Vondi", "en": "Buy Nikon Lenses on Vondi", "ru": "Купите Объективы Nikon на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'foto-i-video-kamere' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'foto-i-video-kamere' AND level = 2) || '/objektivi-nikon',
    55,
    '🔍',
    true
  ),
  (
    'objektivi-sony',
    '{"sr": "Objektivi za Sony", "en": "Sony Lenses", "ru": "Объективы Sony"}',
    '{"sr": "Objektivi za Sony - najbolja ponuda", "en": "Sony Lenses - best selection", "ru": "Объективы Sony - лучший выбор"}',
    '{"sr": "Objektivi za Sony | Vondi", "en": "Sony Lenses | Vondi", "ru": "Объективы Sony | Vondi"}',
    '{"sr": "Kupite Objektivi za Sony na Vondi", "en": "Buy Sony Lenses on Vondi", "ru": "Купите Объективы Sony на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'foto-i-video-kamere' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'foto-i-video-kamere' AND level = 2) || '/objektivi-sony',
    56,
    '🔍',
    true
  ),
  (
    'tronošci',
    '{"sr": "Tronošci", "en": "Tripods", "ru": "Штативы"}',
    '{"sr": "Tronošci - najbolja ponuda", "en": "Tripods - best selection", "ru": "Штативы - лучший выбор"}',
    '{"sr": "Tronošci | Vondi", "en": "Tripods | Vondi", "ru": "Штативы | Vondi"}',
    '{"sr": "Kupite Tronošci na Vondi", "en": "Buy Tripods on Vondi", "ru": "Купите Штативы на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'foto-i-video-kamere' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'foto-i-video-kamere' AND level = 2) || '/tronošci',
    57,
    '📷',
    true
  ),
  (
    'foto-blicevi',
    '{"sr": "Foto blicevi", "en": "Camera Flashes", "ru": "Вспышки для камеры"}',
    '{"sr": "Foto blicevi - najbolja ponuda", "en": "Camera Flashes - best selection", "ru": "Вспышки для камеры - лучший выбор"}',
    '{"sr": "Foto blicevi | Vondi", "en": "Camera Flashes | Vondi", "ru": "Вспышки для камеры | Vondi"}',
    '{"sr": "Kupite Foto blicevi na Vondi", "en": "Buy Camera Flashes on Vondi", "ru": "Купите Вспышки для камеры на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'foto-i-video-kamere' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'foto-i-video-kamere' AND level = 2) || '/foto-blicevi',
    58,
    '💡',
    true
  ),
  (
    'apple-watch',
    '{"sr": "Apple Watch", "en": "Apple Watch", "ru": "Apple Watch"}',
    '{"sr": "Apple Watch - najbolja ponuda", "en": "Apple Watch - best selection", "ru": "Apple Watch - лучший выбор"}',
    '{"sr": "Apple Watch | Vondi", "en": "Apple Watch | Vondi", "ru": "Apple Watch | Vondi"}',
    '{"sr": "Kupite Apple Watch na Vondi", "en": "Buy Apple Watch on Vondi", "ru": "Купите Apple Watch на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'pametni-satovi' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'pametni-satovi' AND level = 2) || '/apple-watch',
    59,
    '⌚',
    true
  ),
  (
    'samsung-galaxy-watch',
    '{"sr": "Samsung Galaxy Watch", "en": "Samsung Galaxy Watch", "ru": "Samsung Galaxy Watch"}',
    '{"sr": "Samsung Galaxy Watch - najbolja ponuda", "en": "Samsung Galaxy Watch - best selection", "ru": "Samsung Galaxy Watch - лучший выбор"}',
    '{"sr": "Samsung Galaxy Watch | Vondi", "en": "Samsung Galaxy Watch | Vondi", "ru": "Samsung Galaxy Watch | Vondi"}',
    '{"sr": "Kupite Samsung Galaxy Watch na Vondi", "en": "Buy Samsung Galaxy Watch on Vondi", "ru": "Купите Samsung Galaxy Watch на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'pametni-satovi' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'pametni-satovi' AND level = 2) || '/samsung-galaxy-watch',
    60,
    '⌚',
    true
  ),
  (
    'xiaomi-mi-watch',
    '{"sr": "Xiaomi Mi Watch", "en": "Xiaomi Mi Watch", "ru": "Xiaomi Mi Watch"}',
    '{"sr": "Xiaomi Mi Watch - najbolja ponuda", "en": "Xiaomi Mi Watch - best selection", "ru": "Xiaomi Mi Watch - лучший выбор"}',
    '{"sr": "Xiaomi Mi Watch | Vondi", "en": "Xiaomi Mi Watch | Vondi", "ru": "Xiaomi Mi Watch | Vondi"}',
    '{"sr": "Kupite Xiaomi Mi Watch na Vondi", "en": "Buy Xiaomi Mi Watch on Vondi", "ru": "Купите Xiaomi Mi Watch на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'pametni-satovi' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'pametni-satovi' AND level = 2) || '/xiaomi-mi-watch',
    61,
    '⌚',
    true
  ),
  (
    'garmin-satovi',
    '{"sr": "Garmin satovi", "en": "Garmin Watches", "ru": "Часы Garmin"}',
    '{"sr": "Garmin satovi - najbolja ponuda", "en": "Garmin Watches - best selection", "ru": "Часы Garmin - лучший выбор"}',
    '{"sr": "Garmin satovi | Vondi", "en": "Garmin Watches | Vondi", "ru": "Часы Garmin | Vondi"}',
    '{"sr": "Kupite Garmin satovi na Vondi", "en": "Buy Garmin Watches on Vondi", "ru": "Купите Часы Garmin на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'pametni-satovi' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'pametni-satovi' AND level = 2) || '/garmin-satovi',
    62,
    '⌚',
    true
  ),
  (
    'huawei-watch',
    '{"sr": "Huawei Watch", "en": "Huawei Watch", "ru": "Huawei Watch"}',
    '{"sr": "Huawei Watch - najbolja ponuda", "en": "Huawei Watch - best selection", "ru": "Huawei Watch - лучший выбор"}',
    '{"sr": "Huawei Watch | Vondi", "en": "Huawei Watch | Vondi", "ru": "Huawei Watch | Vondi"}',
    '{"sr": "Kupite Huawei Watch na Vondi", "en": "Buy Huawei Watch on Vondi", "ru": "Купите Huawei Watch на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'pametni-satovi' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'pametni-satovi' AND level = 2) || '/huawei-watch',
    63,
    '⌚',
    true
  ),
  (
    'gaming-tastature',
    '{"sr": "Gaming tastature", "en": "Gaming Keyboards", "ru": "Игровые клавиатуры"}',
    '{"sr": "Gaming tastature - najbolja ponuda", "en": "Gaming Keyboards - best selection", "ru": "Игровые клавиатуры - лучший выбор"}',
    '{"sr": "Gaming tastature | Vondi", "en": "Gaming Keyboards | Vondi", "ru": "Игровые клавиатуры | Vondi"}',
    '{"sr": "Kupite Gaming tastature na Vondi", "en": "Buy Gaming Keyboards on Vondi", "ru": "Купите Игровые клавиатуры на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'gaming-oprema' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'gaming-oprema' AND level = 2) || '/gaming-tastature',
    64,
    '⌨️',
    true
  ),
  (
    'gaming-misevi',
    '{"sr": "Gaming miševi", "en": "Gaming Mice", "ru": "Игровые мыши"}',
    '{"sr": "Gaming miševi - najbolja ponuda", "en": "Gaming Mice - best selection", "ru": "Игровые мыши - лучший выбор"}',
    '{"sr": "Gaming miševi | Vondi", "en": "Gaming Mice | Vondi", "ru": "Игровые мыши | Vondi"}',
    '{"sr": "Kupite Gaming miševi na Vondi", "en": "Buy Gaming Mice on Vondi", "ru": "Купите Игровые мыши на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'gaming-oprema' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'gaming-oprema' AND level = 2) || '/gaming-misevi',
    65,
    '🖱️',
    true
  ),
  (
    'gaming-slusalice',
    '{"sr": "Gaming slušalice", "en": "Gaming Headsets", "ru": "Игровые наушники"}',
    '{"sr": "Gaming slušalice - najbolja ponuda", "en": "Gaming Headsets - best selection", "ru": "Игровые наушники - лучший выбор"}',
    '{"sr": "Gaming slušalice | Vondi", "en": "Gaming Headsets | Vondi", "ru": "Игровые наушники | Vondi"}',
    '{"sr": "Kupite Gaming slušalice na Vondi", "en": "Buy Gaming Headsets on Vondi", "ru": "Купите Игровые наушники на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'gaming-oprema' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'gaming-oprema' AND level = 2) || '/gaming-slusalice',
    66,
    '🎧',
    true
  ),
  (
    'gaming-stolice',
    '{"sr": "Gaming stolice", "en": "Gaming Chairs", "ru": "Игровые кресла"}',
    '{"sr": "Gaming stolice - najbolja ponuda", "en": "Gaming Chairs - best selection", "ru": "Игровые кресла - лучший выбор"}',
    '{"sr": "Gaming stolice | Vondi", "en": "Gaming Chairs | Vondi", "ru": "Игровые кресла | Vondi"}',
    '{"sr": "Kupite Gaming stolice na Vondi", "en": "Buy Gaming Chairs on Vondi", "ru": "Купите Игровые кресла на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'gaming-oprema' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'gaming-oprema' AND level = 2) || '/gaming-stolice',
    67,
    '🪑',
    true
  ),
  (
    'gaming-monitori',
    '{"sr": "Gaming monitori", "en": "Gaming Monitors", "ru": "Игровые мониторы"}',
    '{"sr": "Gaming monitori - najbolja ponuda", "en": "Gaming Monitors - best selection", "ru": "Игровые мониторы - лучший выбор"}',
    '{"sr": "Gaming monitori | Vondi", "en": "Gaming Monitors | Vondi", "ru": "Игровые мониторы | Vondi"}',
    '{"sr": "Kupite Gaming monitori na Vondi", "en": "Buy Gaming Monitors on Vondi", "ru": "Купите Игровые мониторы на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'gaming-oprema' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'gaming-oprema' AND level = 2) || '/gaming-monitori',
    68,
    '🖥️',
    true
  ),
  (
    'racing-volani',
    '{"sr": "Racing volani", "en": "Racing Wheels", "ru": "Рулевые системы"}',
    '{"sr": "Racing volani - najbolja ponuda", "en": "Racing Wheels - best selection", "ru": "Рулевые системы - лучший выбор"}',
    '{"sr": "Racing volani | Vondi", "en": "Racing Wheels | Vondi", "ru": "Рулевые системы | Vondi"}',
    '{"sr": "Kupite Racing volani na Vondi", "en": "Buy Racing Wheels on Vondi", "ru": "Купите Рулевые системы на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'gaming-oprema' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'gaming-oprema' AND level = 2) || '/racing-volani',
    69,
    '🎮',
    true
  ),
  (
    'joystick',
    '{"sr": "Joystick-ovi", "en": "Joysticks", "ru": "Джойстики"}',
    '{"sr": "Joystick-ovi - najbolja ponuda", "en": "Joysticks - best selection", "ru": "Джойстики - лучший выбор"}',
    '{"sr": "Joystick-ovi | Vondi", "en": "Joysticks | Vondi", "ru": "Джойстики | Vondi"}',
    '{"sr": "Kupite Joystick-ovi na Vondi", "en": "Buy Joysticks on Vondi", "ru": "Купите Джойстики на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'gaming-oprema' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'gaming-oprema' AND level = 2) || '/joystick',
    70,
    '🕹️',
    true
  ),
  (
    'vr-naocari',
    '{"sr": "VR naočari", "en": "VR Headsets", "ru": "VR гарнитуры"}',
    '{"sr": "VR naočari - najbolja ponuda", "en": "VR Headsets - best selection", "ru": "VR гарнитуры - лучший выбор"}',
    '{"sr": "VR naočari | Vondi", "en": "VR Headsets | Vondi", "ru": "VR гарнитуры | Vondi"}',
    '{"sr": "Kupite VR naočari na Vondi", "en": "Buy VR Headsets on Vondi", "ru": "Купите VR гарнитуры на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'gaming-oprema' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'gaming-oprema' AND level = 2) || '/vr-naocari',
    71,
    '🥽',
    true
  )
;

-- Verification
DO $$
DECLARE
  duplicate_count INT;
BEGIN
  SELECT COUNT(*) INTO duplicate_count FROM (
    SELECT slug, COUNT(*) FROM categories GROUP BY slug HAVING COUNT(*) > 1
  ) dup;
  IF duplicate_count > 0 THEN
    RAISE EXCEPTION 'Found % duplicate slugs!', duplicate_count;
  END IF;
  RAISE NOTICE 'No duplicates found ✅';
  RAISE NOTICE 'Successfully added L3 categories';
END $$;