-- Migration: Add accepted status and related columns for shipment workflow
-- This migration supports the seller shipment workflow:
-- pending → confirmed → accepted → processing → shipped → delivered

-- Add accepted_at timestamp for when seller confirms the order
ALTER TABLE orders
ADD COLUMN IF NOT EXISTS accepted_at TIMESTAMP WITH TIME ZONE;

-- Add label_url for shipping label PDF
ALTER TABLE orders
ADD COLUMN IF NOT EXISTS label_url TEXT;

-- Add seller_notes for seller comments during workflow
ALTER TABLE orders
ADD COLUMN IF NOT EXISTS seller_notes TEXT;

-- Create index for efficient queries on accepted orders
CREATE INDEX IF NOT EXISTS idx_orders_accepted_at
ON orders(accepted_at)
WHERE accepted_at IS NOT NULL;

-- Update CHECK constraint for status to include 'accepted'
-- First drop the existing constraint, then add new one
ALTER TABLE orders DROP CONSTRAINT IF EXISTS orders_status_check;
ALTER TABLE orders ADD CONSTRAINT orders_status_check
CHECK (status IN ('unspecified', 'pending', 'confirmed', 'accepted', 'processing', 'shipped', 'delivered', 'cancelled', 'refunded', 'failed'));

-- Add comment for documentation
COMMENT ON COLUMN orders.accepted_at IS 'Timestamp when seller accepted the order (status: accepted)';
COMMENT ON COLUMN orders.label_url IS 'URL to the shipping label PDF generated by delivery service';
COMMENT ON COLUMN orders.seller_notes IS 'Notes from seller about the order';
