-- Migration: L3 Categories
-- Date: 2025-12-17

INSERT INTO categories (slug, name, description, meta_title, meta_description, parent_id, level, path, sort_order, icon, is_active)
VALUES
  (
    'majice-polo',
    '{"sr": "Polo majice", "en": "Polo Shirts", "ru": "Поло футболки"}',
    '{"sr": "Polo majice - najbolja ponuda", "en": "Polo Shirts - best selection", "ru": "Поло футболки - лучший выбор"}',
    '{"sr": "Polo majice | Vondi", "en": "Polo Shirts | Vondi", "ru": "Поло футболки | Vondi"}',
    '{"sr": "Kupite Polo majice na Vondi", "en": "Buy Polo Shirts on Vondi", "ru": "Купите Поло футболки на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'muska-odeca' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'muska-odeca' AND level = 2) || '/majice-polo',
    1001,
    '👕',
    true
  ),
  (
    'majice-kratkih-rukava',
    '{"sr": "Majice kratkih rukava", "en": "Short Sleeve Shirts", "ru": "Футболки с коротким рукавом"}',
    '{"sr": "Majice kratkih rukava - najbolja ponuda", "en": "Short Sleeve Shirts - best selection", "ru": "Футболки с коротким рукавом - лучший выбор"}',
    '{"sr": "Majice kratkih rukava | Vondi", "en": "Short Sleeve Shirts | Vondi", "ru": "Футболки с коротким рукавом | Vondi"}',
    '{"sr": "Kupite Majice kratkih rukava na Vondi", "en": "Buy Short Sleeve Shirts on Vondi", "ru": "Купите Футболки с коротким рукавом на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'muska-odeca' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'muska-odeca' AND level = 2) || '/majice-kratkih-rukava',
    1002,
    '👕',
    true
  ),
  (
    'kosulje-dugi-rukav',
    '{"sr": "Košulje dugi rukav", "en": "Long Sleeve Shirts", "ru": "Рубашки с длинным рукавом"}',
    '{"sr": "Košulje dugi rukav - najbolja ponuda", "en": "Long Sleeve Shirts - best selection", "ru": "Рубашки с длинным рукавом - лучший выбор"}',
    '{"sr": "Košulje dugi rukav | Vondi", "en": "Long Sleeve Shirts | Vondi", "ru": "Рубашки с длинным рукавом | Vondi"}',
    '{"sr": "Kupite Košulje dugi rukav na Vondi", "en": "Buy Long Sleeve Shirts on Vondi", "ru": "Купите Рубашки с длинным рукавом на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'muska-odeca' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'muska-odeca' AND level = 2) || '/kosulje-dugi-rukav',
    1003,
    '👔',
    true
  ),
  (
    'kosulje-kratki-rukav',
    '{"sr": "Košulje kratki rukav", "en": "Short Sleeve Shirts", "ru": "Рубашки с коротким рукавом"}',
    '{"sr": "Košulje kratki rukav - najbolja ponuda", "en": "Short Sleeve Shirts - best selection", "ru": "Рубашки с коротким рукавом - лучший выбор"}',
    '{"sr": "Košulje kratki rukav | Vondi", "en": "Short Sleeve Shirts | Vondi", "ru": "Рубашки с коротким рукавом | Vondi"}',
    '{"sr": "Kupite Košulje kratki rukav na Vondi", "en": "Buy Short Sleeve Shirts on Vondi", "ru": "Купите Рубашки с коротким рукавом на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'muska-odeca' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'muska-odeca' AND level = 2) || '/kosulje-kratki-rukav',
    1004,
    '👔',
    true
  ),
  (
    'farmerke-slim',
    '{"sr": "Farmerke slim", "en": "Slim Jeans", "ru": "Джинсы slim"}',
    '{"sr": "Farmerke slim - najbolja ponuda", "en": "Slim Jeans - best selection", "ru": "Джинсы slim - лучший выбор"}',
    '{"sr": "Farmerke slim | Vondi", "en": "Slim Jeans | Vondi", "ru": "Джинсы slim | Vondi"}',
    '{"sr": "Kupite Farmerke slim na Vondi", "en": "Buy Slim Jeans on Vondi", "ru": "Купите Джинсы slim на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'muska-odeca' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'muska-odeca' AND level = 2) || '/farmerke-slim',
    1005,
    '👖',
    true
  ),
  (
    'farmerke-regular',
    '{"sr": "Farmerke regular", "en": "Regular Jeans", "ru": "Джинсы regular"}',
    '{"sr": "Farmerke regular - najbolja ponuda", "en": "Regular Jeans - best selection", "ru": "Джинсы regular - лучший выбор"}',
    '{"sr": "Farmerke regular | Vondi", "en": "Regular Jeans | Vondi", "ru": "Джинсы regular | Vondi"}',
    '{"sr": "Kupite Farmerke regular na Vondi", "en": "Buy Regular Jeans on Vondi", "ru": "Купите Джинсы regular на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'muska-odeca' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'muska-odeca' AND level = 2) || '/farmerke-regular',
    1006,
    '👖',
    true
  ),
  (
    'pantalone-elegantne',
    '{"sr": "Elegantne pantalone", "en": "Dress Pants", "ru": "Классические брюки"}',
    '{"sr": "Elegantne pantalone - najbolja ponuda", "en": "Dress Pants - best selection", "ru": "Классические брюки - лучший выбор"}',
    '{"sr": "Elegantne pantalone | Vondi", "en": "Dress Pants | Vondi", "ru": "Классические брюки | Vondi"}',
    '{"sr": "Kupite Elegantne pantalone na Vondi", "en": "Buy Dress Pants on Vondi", "ru": "Купите Классические брюки на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'muska-odeca' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'muska-odeca' AND level = 2) || '/pantalone-elegantne',
    1007,
    '👔',
    true
  ),
  (
    'trenerke',
    '{"sr": "Trenerke", "en": "Track Suits", "ru": "Спортивные костюмы"}',
    '{"sr": "Trenerke - najbolja ponuda", "en": "Track Suits - best selection", "ru": "Спортивные костюмы - лучший выбор"}',
    '{"sr": "Trenerke | Vondi", "en": "Track Suits | Vondi", "ru": "Спортивные костюмы | Vondi"}',
    '{"sr": "Kupite Trenerke na Vondi", "en": "Buy Track Suits on Vondi", "ru": "Купите Спортивные костюмы на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'muska-odeca' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'muska-odeca' AND level = 2) || '/trenerke',
    1008,
    '🏃',
    true
  ),
  (
    'dzemperi-vuneni',
    '{"sr": "Džemperi vuneni", "en": "Wool Sweaters", "ru": "Шерстяные свитеры"}',
    '{"sr": "Džemperi vuneni - najbolja ponuda", "en": "Wool Sweaters - best selection", "ru": "Шерстяные свитеры - лучший выбор"}',
    '{"sr": "Džemperi vuneni | Vondi", "en": "Wool Sweaters | Vondi", "ru": "Шерстяные свитеры | Vondi"}',
    '{"sr": "Kupite Džemperi vuneni na Vondi", "en": "Buy Wool Sweaters on Vondi", "ru": "Купите Шерстяные свитеры на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'muska-odeca' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'muska-odeca' AND level = 2) || '/dzemperi-vuneni',
    1009,
    '🧶',
    true
  ),
  (
    'jakne-kožne',
    '{"sr": "Kožne jakne", "en": "Leather Jackets", "ru": "Кожаные куртки"}',
    '{"sr": "Kožne jakne - najbolja ponuda", "en": "Leather Jackets - best selection", "ru": "Кожаные куртки - лучший выбор"}',
    '{"sr": "Kožne jakne | Vondi", "en": "Leather Jackets | Vondi", "ru": "Кожаные куртки | Vondi"}',
    '{"sr": "Kupite Kožne jakne na Vondi", "en": "Buy Leather Jackets on Vondi", "ru": "Купите Кожаные куртки на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'muska-odeca' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'muska-odeca' AND level = 2) || '/jakne-kožne',
    1010,
    '🧥',
    true
  ),
  (
    'perjane-jakne',
    '{"sr": "Perjane jakne", "en": "Down Jackets", "ru": "Пуховики"}',
    '{"sr": "Perjane jakne - najbolja ponuda", "en": "Down Jackets - best selection", "ru": "Пуховики - лучший выбор"}',
    '{"sr": "Perjane jakne | Vondi", "en": "Down Jackets | Vondi", "ru": "Пуховики | Vondi"}',
    '{"sr": "Kupite Perjane jakne na Vondi", "en": "Buy Down Jackets on Vondi", "ru": "Купите Пуховики на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'muska-odeca' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'muska-odeca' AND level = 2) || '/perjane-jakne',
    1011,
    '🧥',
    true
  ),
  (
    'odela-muska',
    '{"sr": "Muška odela", "en": "Mens Suits", "ru": "Мужские костюмы"}',
    '{"sr": "Muška odela - najbolja ponuda", "en": "Mens Suits - best selection", "ru": "Мужские костюмы - лучший выбор"}',
    '{"sr": "Muška odela | Vondi", "en": "Mens Suits | Vondi", "ru": "Мужские костюмы | Vondi"}',
    '{"sr": "Kupite Muška odela na Vondi", "en": "Buy Mens Suits on Vondi", "ru": "Купите Мужские костюмы на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'muska-odeca' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'muska-odeca' AND level = 2) || '/odela-muska',
    1012,
    '🤵',
    true
  ),
  (
    'smokingzi',
    '{"sr": "Smokingzi", "en": "Tuxedos", "ru": "Смокинги"}',
    '{"sr": "Smokingzi - najbolja ponuda", "en": "Tuxedos - best selection", "ru": "Смокинги - лучший выбор"}',
    '{"sr": "Smokingzi | Vondi", "en": "Tuxedos | Vondi", "ru": "Смокинги | Vondi"}',
    '{"sr": "Kupite Smokingzi na Vondi", "en": "Buy Tuxedos on Vondi", "ru": "Купите Смокинги на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'muska-odeca' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'muska-odeca' AND level = 2) || '/smokingzi',
    1013,
    '🎩',
    true
  ),
  (
    'sako-muski',
    '{"sr": "Muški sako", "en": "Mens Blazers", "ru": "Мужские пиджаки"}',
    '{"sr": "Muški sako - najbolja ponuda", "en": "Mens Blazers - best selection", "ru": "Мужские пиджаки - лучший выбор"}',
    '{"sr": "Muški sako | Vondi", "en": "Mens Blazers | Vondi", "ru": "Мужские пиджаки | Vondi"}',
    '{"sr": "Kupite Muški sako na Vondi", "en": "Buy Mens Blazers on Vondi", "ru": "Купите Мужские пиджаки на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'muska-odeca' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'muska-odeca' AND level = 2) || '/sako-muski',
    1014,
    '🧥',
    true
  ),
  (
    'sorc-muski',
    '{"sr": "Muški šortsevi", "en": "Mens Shorts", "ru": "Мужские шорты"}',
    '{"sr": "Muški šortsevi - najbolja ponuda", "en": "Mens Shorts - best selection", "ru": "Мужские шорты - лучший выбор"}',
    '{"sr": "Muški šortsevi | Vondi", "en": "Mens Shorts | Vondi", "ru": "Мужские шорты | Vondi"}',
    '{"sr": "Kupite Muški šortsevi na Vondi", "en": "Buy Mens Shorts on Vondi", "ru": "Купите Мужские шорты на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'muska-odeca' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'muska-odeca' AND level = 2) || '/sorc-muski',
    1015,
    '🩳',
    true
  ),
  (
    'haljine-svecane',
    '{"sr": "Svečane haljine", "en": "Evening Dresses", "ru": "Вечерние платья"}',
    '{"sr": "Svečane haljine - najbolja ponuda", "en": "Evening Dresses - best selection", "ru": "Вечерние платья - лучший выбор"}',
    '{"sr": "Svečane haljine | Vondi", "en": "Evening Dresses | Vondi", "ru": "Вечерние платья | Vondi"}',
    '{"sr": "Kupite Svečane haljine na Vondi", "en": "Buy Evening Dresses on Vondi", "ru": "Купите Вечерние платья на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'zenska-odeca' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'zenska-odeca' AND level = 2) || '/haljine-svecane',
    1016,
    '👗',
    true
  ),
  (
    'haljine-letnje',
    '{"sr": "Letnje haljine", "en": "Summer Dresses", "ru": "Летние платья"}',
    '{"sr": "Letnje haljine - najbolja ponuda", "en": "Summer Dresses - best selection", "ru": "Летние платья - лучший выбор"}',
    '{"sr": "Letnje haljine | Vondi", "en": "Summer Dresses | Vondi", "ru": "Летние платья | Vondi"}',
    '{"sr": "Kupite Letnje haljine na Vondi", "en": "Buy Summer Dresses on Vondi", "ru": "Купите Летние платья на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'zenska-odeca' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'zenska-odeca' AND level = 2) || '/haljine-letnje',
    1017,
    '👗',
    true
  ),
  (
    'haljine-kokteli',
    '{"sr": "Kokteil haljine", "en": "Cocktail Dresses", "ru": "Коктейльные платья"}',
    '{"sr": "Kokteil haljine - najbolja ponuda", "en": "Cocktail Dresses - best selection", "ru": "Коктейльные платья - лучший выбор"}',
    '{"sr": "Kokteil haljine | Vondi", "en": "Cocktail Dresses | Vondi", "ru": "Коктейльные платья | Vondi"}',
    '{"sr": "Kupite Kokteil haljine na Vondi", "en": "Buy Cocktail Dresses on Vondi", "ru": "Купите Коктейльные платья на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'zenska-odeca' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'zenska-odeca' AND level = 2) || '/haljine-kokteli',
    1018,
    '👗',
    true
  ),
  (
    'bluze-svilene',
    '{"sr": "Svilene bluze", "en": "Silk Blouses", "ru": "Шелковые блузы"}',
    '{"sr": "Svilene bluze - najbolja ponuda", "en": "Silk Blouses - best selection", "ru": "Шелковые блузы - лучший выбор"}',
    '{"sr": "Svilene bluze | Vondi", "en": "Silk Blouses | Vondi", "ru": "Шелковые блузы | Vondi"}',
    '{"sr": "Kupite Svilene bluze na Vondi", "en": "Buy Silk Blouses on Vondi", "ru": "Купите Шелковые блузы на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'zenska-odeca' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'zenska-odeca' AND level = 2) || '/bluze-svilene',
    1019,
    '👚',
    true
  ),
  (
    'majice-zenske',
    '{"sr": "Ženske majice", "en": "Womens T-shirts", "ru": "Женские футболки"}',
    '{"sr": "Ženske majice - najbolja ponuda", "en": "Womens T-shirts - best selection", "ru": "Женские футболки - лучший выбор"}',
    '{"sr": "Ženske majice | Vondi", "en": "Womens T-shirts | Vondi", "ru": "Женские футболки | Vondi"}',
    '{"sr": "Kupite Ženske majice na Vondi", "en": "Buy Womens T-shirts on Vondi", "ru": "Купите Женские футболки на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'zenska-odeca' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'zenska-odeca' AND level = 2) || '/majice-zenske',
    1020,
    '👕',
    true
  ),
  (
    'farmerke-zenske-skinny',
    '{"sr": "Ženske farmerke skinny", "en": "Womens Skinny Jeans", "ru": "Женские джинсы скинни"}',
    '{"sr": "Ženske farmerke skinny - najbolja ponuda", "en": "Womens Skinny Jeans - best selection", "ru": "Женские джинсы скинни - лучший выбор"}',
    '{"sr": "Ženske farmerke skinny | Vondi", "en": "Womens Skinny Jeans | Vondi", "ru": "Женские джинсы скинни | Vondi"}',
    '{"sr": "Kupite Ženske farmerke skinny na Vondi", "en": "Buy Womens Skinny Jeans on Vondi", "ru": "Купите Женские джинсы скинни на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'zenska-odeca' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'zenska-odeca' AND level = 2) || '/farmerke-zenske-skinny',
    1021,
    '👖',
    true
  ),
  (
    'farmerke-zenske-mom',
    '{"sr": "Ženske farmerke mom", "en": "Womens Mom Jeans", "ru": "Женские джинсы mom"}',
    '{"sr": "Ženske farmerke mom - najbolja ponuda", "en": "Womens Mom Jeans - best selection", "ru": "Женские джинсы mom - лучший выбор"}',
    '{"sr": "Ženske farmerke mom | Vondi", "en": "Womens Mom Jeans | Vondi", "ru": "Женские джинсы mom | Vondi"}',
    '{"sr": "Kupite Ženske farmerke mom na Vondi", "en": "Buy Womens Mom Jeans on Vondi", "ru": "Купите Женские джинсы mom на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'zenska-odeca' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'zenska-odeca' AND level = 2) || '/farmerke-zenske-mom',
    1022,
    '👖',
    true
  ),
  (
    'suknje-mini',
    '{"sr": "Mini suknje", "en": "Mini Skirts", "ru": "Мини юбки"}',
    '{"sr": "Mini suknje - najbolja ponuda", "en": "Mini Skirts - best selection", "ru": "Мини юбки - лучший выбор"}',
    '{"sr": "Mini suknje | Vondi", "en": "Mini Skirts | Vondi", "ru": "Мини юбки | Vondi"}',
    '{"sr": "Kupite Mini suknje na Vondi", "en": "Buy Mini Skirts on Vondi", "ru": "Купите Мини юбки на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'zenska-odeca' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'zenska-odeca' AND level = 2) || '/suknje-mini',
    1023,
    '👗',
    true
  ),
  (
    'suknje-midi',
    '{"sr": "Midi suknje", "en": "Midi Skirts", "ru": "Миди юбки"}',
    '{"sr": "Midi suknje - najbolja ponuda", "en": "Midi Skirts - best selection", "ru": "Миди юбки - лучший выбор"}',
    '{"sr": "Midi suknje | Vondi", "en": "Midi Skirts | Vondi", "ru": "Миди юбки | Vondi"}',
    '{"sr": "Kupite Midi suknje na Vondi", "en": "Buy Midi Skirts on Vondi", "ru": "Купите Миди юбки на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'zenska-odeca' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'zenska-odeca' AND level = 2) || '/suknje-midi',
    1024,
    '👗',
    true
  ),
  (
    'suknje-duge',
    '{"sr": "Duge suknje", "en": "Long Skirts", "ru": "Длинные юбки"}',
    '{"sr": "Duge suknje - najbolja ponuda", "en": "Long Skirts - best selection", "ru": "Длинные юбки - лучший выбор"}',
    '{"sr": "Duge suknje | Vondi", "en": "Long Skirts | Vondi", "ru": "Длинные юбки | Vondi"}',
    '{"sr": "Kupite Duge suknje na Vondi", "en": "Buy Long Skirts on Vondi", "ru": "Купите Длинные юбки на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'zenska-odeca' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'zenska-odeca' AND level = 2) || '/suknje-duge',
    1025,
    '👗',
    true
  ),
  (
    'pantalone-zenske',
    '{"sr": "Ženske pantalone", "en": "Womens Pants", "ru": "Женские брюки"}',
    '{"sr": "Ženske pantalone - najbolja ponuda", "en": "Womens Pants - best selection", "ru": "Женские брюки - лучший выбор"}',
    '{"sr": "Ženske pantalone | Vondi", "en": "Womens Pants | Vondi", "ru": "Женские брюки | Vondi"}',
    '{"sr": "Kupite Ženske pantalone na Vondi", "en": "Buy Womens Pants on Vondi", "ru": "Купите Женские брюки на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'zenska-odeca' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'zenska-odeca' AND level = 2) || '/pantalone-zenske',
    1026,
    '👖',
    true
  ),
  (
    'zenske-jakne',
    '{"sr": "Ženske jakne", "en": "Womens Jackets", "ru": "Женские куртки"}',
    '{"sr": "Ženske jakne - najbolja ponuda", "en": "Womens Jackets - best selection", "ru": "Женские куртки - лучший выбор"}',
    '{"sr": "Ženske jakne | Vondi", "en": "Womens Jackets | Vondi", "ru": "Женские куртки | Vondi"}',
    '{"sr": "Kupite Ženske jakne na Vondi", "en": "Buy Womens Jackets on Vondi", "ru": "Купите Женские куртки на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'zenska-odeca' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'zenska-odeca' AND level = 2) || '/zenske-jakne',
    1027,
    '🧥',
    true
  ),
  (
    'kardigani',
    '{"sr": "Kardigani", "en": "Cardigans", "ru": "Кардиганы"}',
    '{"sr": "Kardigani - najbolja ponuda", "en": "Cardigans - best selection", "ru": "Кардиганы - лучший выбор"}',
    '{"sr": "Kardigani | Vondi", "en": "Cardigans | Vondi", "ru": "Кардиганы | Vondi"}',
    '{"sr": "Kupite Kardigani na Vondi", "en": "Buy Cardigans on Vondi", "ru": "Купите Кардиганы на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'zenska-odeca' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'zenska-odeca' AND level = 2) || '/kardigani',
    1028,
    '🧶',
    true
  ),
  (
    'blejzeri-zenske',
    '{"sr": "Ženski blejzeri", "en": "Womens Blazers", "ru": "Женские пиджаки"}',
    '{"sr": "Ženski blejzeri - najbolja ponuda", "en": "Womens Blazers - best selection", "ru": "Женские пиджаки - лучший выбор"}',
    '{"sr": "Ženski blejzeri | Vondi", "en": "Womens Blazers | Vondi", "ru": "Женские пиджаки | Vondi"}',
    '{"sr": "Kupite Ženski blejzeri na Vondi", "en": "Buy Womens Blazers on Vondi", "ru": "Купите Женские пиджаки на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'zenska-odeca' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'zenska-odeca' AND level = 2) || '/blejzeri-zenske',
    1029,
    '🧥',
    true
  ),
  (
    'kombinezoni',
    '{"sr": "Kombinezoni", "en": "Jumpsuits", "ru": "Комбинезоны"}',
    '{"sr": "Kombinezoni - najbolja ponuda", "en": "Jumpsuits - best selection", "ru": "Комбинезоны - лучший выбор"}',
    '{"sr": "Kombinezoni | Vondi", "en": "Jumpsuits | Vondi", "ru": "Комбинезоны | Vondi"}',
    '{"sr": "Kupite Kombinezoni na Vondi", "en": "Buy Jumpsuits on Vondi", "ru": "Купите Комбинезоны на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'zenska-odeca' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'zenska-odeca' AND level = 2) || '/kombinezoni',
    1030,
    '👗',
    true
  ),
  (
    'odeca-bebe-0-2',
    '{"sr": "Odeća za bebe 0-2 god", "en": "Baby Clothing 0-2 years", "ru": "Одежда для малышей 0-2 года"}',
    '{"sr": "Odeća za bebe 0-2 god - najbolja ponuda", "en": "Baby Clothing 0-2 years - best selection", "ru": "Одежда для малышей 0-2 года - лучший выбор"}',
    '{"sr": "Odeća za bebe 0-2 god | Vondi", "en": "Baby Clothing 0-2 years | Vondi", "ru": "Одежда для малышей 0-2 года | Vondi"}',
    '{"sr": "Kupite Odeća za bebe 0-2 god na Vondi", "en": "Buy Baby Clothing 0-2 years on Vondi", "ru": "Купите Одежда для малышей 0-2 года на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'decija-odeca' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'decija-odeca' AND level = 2) || '/odeca-bebe-0-2',
    1031,
    '👶',
    true
  ),
  (
    'odeca-devojcice-3-6',
    '{"sr": "Odeća za devojčice 3-6 god", "en": "Girls Clothing 3-6 years", "ru": "Одежда для девочек 3-6 лет"}',
    '{"sr": "Odeća za devojčice 3-6 god - najbolja ponuda", "en": "Girls Clothing 3-6 years - best selection", "ru": "Одежда для девочек 3-6 лет - лучший выбор"}',
    '{"sr": "Odeća za devojčice 3-6 god | Vondi", "en": "Girls Clothing 3-6 years | Vondi", "ru": "Одежда для девочек 3-6 лет | Vondi"}',
    '{"sr": "Kupite Odeća za devojčice 3-6 god na Vondi", "en": "Buy Girls Clothing 3-6 years on Vondi", "ru": "Купите Одежда для девочек 3-6 лет на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'decija-odeca' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'decija-odeca' AND level = 2) || '/odeca-devojcice-3-6',
    1032,
    '👧',
    true
  ),
  (
    'odeca-devojcice-7-12',
    '{"sr": "Odeća za devojčice 7-12 god", "en": "Girls Clothing 7-12 years", "ru": "Одежда для девочек 7-12 лет"}',
    '{"sr": "Odeća za devojčice 7-12 god - najbolja ponuda", "en": "Girls Clothing 7-12 years - best selection", "ru": "Одежда для девочек 7-12 лет - лучший выбор"}',
    '{"sr": "Odeća za devojčice 7-12 god | Vondi", "en": "Girls Clothing 7-12 years | Vondi", "ru": "Одежда для девочек 7-12 лет | Vondi"}',
    '{"sr": "Kupite Odeća za devojčice 7-12 god na Vondi", "en": "Buy Girls Clothing 7-12 years on Vondi", "ru": "Купите Одежда для девочек 7-12 лет на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'decija-odeca' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'decija-odeca' AND level = 2) || '/odeca-devojcice-7-12',
    1033,
    '👧',
    true
  ),
  (
    'odeca-decaci-3-6',
    '{"sr": "Odeća za dečake 3-6 god", "en": "Boys Clothing 3-6 years", "ru": "Одежда для мальчиков 3-6 лет"}',
    '{"sr": "Odeća za dečake 3-6 god - najbolja ponuda", "en": "Boys Clothing 3-6 years - best selection", "ru": "Одежда для мальчиков 3-6 лет - лучший выбор"}',
    '{"sr": "Odeća za dečake 3-6 god | Vondi", "en": "Boys Clothing 3-6 years | Vondi", "ru": "Одежда для мальчиков 3-6 лет | Vondi"}',
    '{"sr": "Kupite Odeća za dečake 3-6 god na Vondi", "en": "Buy Boys Clothing 3-6 years on Vondi", "ru": "Купите Одежда для мальчиков 3-6 лет на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'decija-odeca' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'decija-odeca' AND level = 2) || '/odeca-decaci-3-6',
    1034,
    '👦',
    true
  ),
  (
    'odeca-decaci-7-12',
    '{"sr": "Odeća za dečake 7-12 god", "en": "Boys Clothing 7-12 years", "ru": "Одежда для мальчиков 7-12 лет"}',
    '{"sr": "Odeća za dečake 7-12 god - najbolja ponuda", "en": "Boys Clothing 7-12 years - best selection", "ru": "Одежда для мальчиков 7-12 лет - лучший выбор"}',
    '{"sr": "Odeća za dečake 7-12 god | Vondi", "en": "Boys Clothing 7-12 years | Vondi", "ru": "Одежда для мальчиков 7-12 лет | Vondi"}',
    '{"sr": "Kupite Odeća za dečake 7-12 god na Vondi", "en": "Buy Boys Clothing 7-12 years on Vondi", "ru": "Купите Одежда для мальчиков 7-12 лет на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'decija-odeca' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'decija-odeca' AND level = 2) || '/odeca-decaci-7-12',
    1035,
    '👦',
    true
  ),
  (
    'skolske-uniforme',
    '{"sr": "Školske uniforme", "en": "School Uniforms", "ru": "Школьная форма"}',
    '{"sr": "Školske uniforme - najbolja ponuda", "en": "School Uniforms - best selection", "ru": "Школьная форма - лучший выбор"}',
    '{"sr": "Školske uniforme | Vondi", "en": "School Uniforms | Vondi", "ru": "Школьная форма | Vondi"}',
    '{"sr": "Kupite Školske uniforme na Vondi", "en": "Buy School Uniforms on Vondi", "ru": "Купите Школьная форма на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'decija-odeca' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'decija-odeca' AND level = 2) || '/skolske-uniforme',
    1036,
    '🎒',
    true
  ),
  (
    'decije-trenerke',
    '{"sr": "Dečije trenerke", "en": "Kids Track Suits", "ru": "Детские спортивные костюмы"}',
    '{"sr": "Dečije trenerke - najbolja ponuda", "en": "Kids Track Suits - best selection", "ru": "Детские спортивные костюмы - лучший выбор"}',
    '{"sr": "Dečije trenerke | Vondi", "en": "Kids Track Suits | Vondi", "ru": "Детские спортивные костюмы | Vondi"}',
    '{"sr": "Kupite Dečije trenerke na Vondi", "en": "Buy Kids Track Suits on Vondi", "ru": "Купите Детские спортивные костюмы на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'decija-odeca' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'decija-odeca' AND level = 2) || '/decije-trenerke',
    1037,
    '🏃',
    true
  ),
  (
    'decije-jakne',
    '{"sr": "Dečije jakne", "en": "Kids Jackets", "ru": "Детские куртки"}',
    '{"sr": "Dečije jakne - najbolja ponuda", "en": "Kids Jackets - best selection", "ru": "Детские куртки - лучший выбор"}',
    '{"sr": "Dečije jakne | Vondi", "en": "Kids Jackets | Vondi", "ru": "Детские куртки | Vondi"}',
    '{"sr": "Kupite Dečije jakne na Vondi", "en": "Buy Kids Jackets on Vondi", "ru": "Купите Детские куртки на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'decija-odeca' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'decija-odeca' AND level = 2) || '/decije-jakne',
    1038,
    '🧥',
    true
  ),
  (
    'decije-kupace-kostimi',
    '{"sr": "Dečiji kupaći kostimi", "en": "Kids Swimwear", "ru": "Детские купальники"}',
    '{"sr": "Dečiji kupaći kostimi - najbolja ponuda", "en": "Kids Swimwear - best selection", "ru": "Детские купальники - лучший выбор"}',
    '{"sr": "Dečiji kupaći kostimi | Vondi", "en": "Kids Swimwear | Vondi", "ru": "Детские купальники | Vondi"}',
    '{"sr": "Kupite Dečiji kupaći kostimi na Vondi", "en": "Buy Kids Swimwear on Vondi", "ru": "Купите Детские купальники на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'decija-odeca' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'decija-odeca' AND level = 2) || '/decije-kupace-kostimi',
    1039,
    '🏊',
    true
  ),
  (
    'cipele-kožne',
    '{"sr": "Kožne cipele", "en": "Leather Shoes", "ru": "Кожаные туфли"}',
    '{"sr": "Kožne cipele - najbolja ponuda", "en": "Leather Shoes - best selection", "ru": "Кожаные туфли - лучший выбор"}',
    '{"sr": "Kožne cipele | Vondi", "en": "Leather Shoes | Vondi", "ru": "Кожаные туфли | Vondi"}',
    '{"sr": "Kupite Kožne cipele na Vondi", "en": "Buy Leather Shoes on Vondi", "ru": "Купите Кожаные туфли на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'muska-obuca' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'muska-obuca' AND level = 2) || '/cipele-kožne',
    1040,
    '👞',
    true
  ),
  (
    'cipele-sportske',
    '{"sr": "Sportske cipele", "en": "Sports Shoes", "ru": "Спортивная обувь"}',
    '{"sr": "Sportske cipele - najbolja ponuda", "en": "Sports Shoes - best selection", "ru": "Спортивная обувь - лучший выбор"}',
    '{"sr": "Sportske cipele | Vondi", "en": "Sports Shoes | Vondi", "ru": "Спортивная обувь | Vondi"}',
    '{"sr": "Kupite Sportske cipele na Vondi", "en": "Buy Sports Shoes on Vondi", "ru": "Купите Спортивная обувь на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'muska-obuca' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'muska-obuca' AND level = 2) || '/cipele-sportske',
    1041,
    '👟',
    true
  ),
  (
    'patike-running',
    '{"sr": "Patike za trčanje", "en": "Running Shoes", "ru": "Беговые кроссовки"}',
    '{"sr": "Patike za trčanje - najbolja ponuda", "en": "Running Shoes - best selection", "ru": "Беговые кроссовки - лучший выбор"}',
    '{"sr": "Patike za trčanje | Vondi", "en": "Running Shoes | Vondi", "ru": "Беговые кроссовки | Vondi"}',
    '{"sr": "Kupite Patike za trčanje na Vondi", "en": "Buy Running Shoes on Vondi", "ru": "Купите Беговые кроссовки на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'muska-obuca' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'muska-obuca' AND level = 2) || '/patike-running',
    1042,
    '👟',
    true
  ),
  (
    'patike-lifestyle',
    '{"sr": "Lifestyle patike", "en": "Lifestyle Sneakers", "ru": "Lifestyle кроссовки"}',
    '{"sr": "Lifestyle patike - najbolja ponuda", "en": "Lifestyle Sneakers - best selection", "ru": "Lifestyle кроссовки - лучший выбор"}',
    '{"sr": "Lifestyle patike | Vondi", "en": "Lifestyle Sneakers | Vondi", "ru": "Lifestyle кроссовки | Vondi"}',
    '{"sr": "Kupite Lifestyle patike na Vondi", "en": "Buy Lifestyle Sneakers on Vondi", "ru": "Купите Lifestyle кроссовки на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'muska-obuca' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'muska-obuca' AND level = 2) || '/patike-lifestyle',
    1043,
    '👟',
    true
  ),
  (
    'cizme-muske',
    '{"sr": "Muške čizme", "en": "Mens Boots", "ru": "Мужские ботинки"}',
    '{"sr": "Muške čizme - najbolja ponuda", "en": "Mens Boots - best selection", "ru": "Мужские ботинки - лучший выбор"}',
    '{"sr": "Muške čizme | Vondi", "en": "Mens Boots | Vondi", "ru": "Мужские ботинки | Vondi"}',
    '{"sr": "Kupite Muške čizme na Vondi", "en": "Buy Mens Boots on Vondi", "ru": "Купите Мужские ботинки на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'muska-obuca' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'muska-obuca' AND level = 2) || '/cizme-muske',
    1044,
    '🥾',
    true
  ),
  (
    'sandale-muske',
    '{"sr": "Muške sandale", "en": "Mens Sandals", "ru": "Мужские сандалии"}',
    '{"sr": "Muške sandale - najbolja ponuda", "en": "Mens Sandals - best selection", "ru": "Мужские сандалии - лучший выбор"}',
    '{"sr": "Muške sandale | Vondi", "en": "Mens Sandals | Vondi", "ru": "Мужские сандалии | Vondi"}',
    '{"sr": "Kupite Muške sandale na Vondi", "en": "Buy Mens Sandals on Vondi", "ru": "Купите Мужские сандалии на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'muska-obuca' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'muska-obuca' AND level = 2) || '/sandale-muske',
    1045,
    '👡',
    true
  ),
  (
    'papuce-muske',
    '{"sr": "Muške papuče", "en": "Mens Slippers", "ru": "Мужские тапочки"}',
    '{"sr": "Muške papuče - najbolja ponuda", "en": "Mens Slippers - best selection", "ru": "Мужские тапочки - лучший выбор"}',
    '{"sr": "Muške papuče | Vondi", "en": "Mens Slippers | Vondi", "ru": "Мужские тапочки | Vondi"}',
    '{"sr": "Kupite Muške papuče na Vondi", "en": "Buy Mens Slippers on Vondi", "ru": "Купите Мужские тапочки на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'muska-obuca' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'muska-obuca' AND level = 2) || '/papuce-muske',
    1046,
    '🩴',
    true
  ),
  (
    'cipele-stikla',
    '{"sr": "Cipele na štiklu", "en": "High Heels", "ru": "Туфли на каблуке"}',
    '{"sr": "Cipele na štiklu - najbolja ponuda", "en": "High Heels - best selection", "ru": "Туфли на каблуке - лучший выбор"}',
    '{"sr": "Cipele na štiklu | Vondi", "en": "High Heels | Vondi", "ru": "Туфли на каблуке | Vondi"}',
    '{"sr": "Kupite Cipele na štiklu na Vondi", "en": "Buy High Heels on Vondi", "ru": "Купите Туфли на каблуке на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'zenska-obuca' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'zenska-obuca' AND level = 2) || '/cipele-stikla',
    1047,
    '👠',
    true
  ),
  (
    'cipele-ravne',
    '{"sr": "Ravne cipele", "en": "Flat Shoes", "ru": "Балетки"}',
    '{"sr": "Ravne cipele - najbolja ponuda", "en": "Flat Shoes - best selection", "ru": "Балетки - лучший выбор"}',
    '{"sr": "Ravne cipele | Vondi", "en": "Flat Shoes | Vondi", "ru": "Балетки | Vondi"}',
    '{"sr": "Kupite Ravne cipele na Vondi", "en": "Buy Flat Shoes on Vondi", "ru": "Купите Балетки на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'zenska-obuca' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'zenska-obuca' AND level = 2) || '/cipele-ravne',
    1048,
    '🥿',
    true
  ),
  (
    'baletanke',
    '{"sr": "Baletanke", "en": "Ballet Flats", "ru": "Балетки"}',
    '{"sr": "Baletanke - najbolja ponuda", "en": "Ballet Flats - best selection", "ru": "Балетки - лучший выбор"}',
    '{"sr": "Baletanke | Vondi", "en": "Ballet Flats | Vondi", "ru": "Балетки | Vondi"}',
    '{"sr": "Kupite Baletanke na Vondi", "en": "Buy Ballet Flats on Vondi", "ru": "Купите Балетки на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'zenska-obuca' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'zenska-obuca' AND level = 2) || '/baletanke',
    1049,
    '🥿',
    true
  ),
  (
    'patike-zenske',
    '{"sr": "Ženske patike", "en": "Womens Sneakers", "ru": "Женские кроссовки"}',
    '{"sr": "Ženske patike - najbolja ponuda", "en": "Womens Sneakers - best selection", "ru": "Женские кроссовки - лучший выбор"}',
    '{"sr": "Ženske patike | Vondi", "en": "Womens Sneakers | Vondi", "ru": "Женские кроссовки | Vondi"}',
    '{"sr": "Kupite Ženske patike na Vondi", "en": "Buy Womens Sneakers on Vondi", "ru": "Купите Женские кроссовки на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'zenska-obuca' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'zenska-obuca' AND level = 2) || '/patike-zenske',
    1050,
    '👟',
    true
  ),
  (
    'cizme-zenske',
    '{"sr": "Ženske čizme", "en": "Womens Boots", "ru": "Женские сапоги"}',
    '{"sr": "Ženske čizme - najbolja ponuda", "en": "Womens Boots - best selection", "ru": "Женские сапоги - лучший выбор"}',
    '{"sr": "Ženske čizme | Vondi", "en": "Womens Boots | Vondi", "ru": "Женские сапоги | Vondi"}',
    '{"sr": "Kupite Ženske čizme na Vondi", "en": "Buy Womens Boots on Vondi", "ru": "Купите Женские сапоги на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'zenska-obuca' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'zenska-obuca' AND level = 2) || '/cizme-zenske',
    1051,
    '👢',
    true
  ),
  (
    'cizme-iznad-kolena',
    '{"sr": "Čizme iznad kolena", "en": "Over-the-Knee Boots", "ru": "Ботфорты"}',
    '{"sr": "Čizme iznad kolena - najbolja ponuda", "en": "Over-the-Knee Boots - best selection", "ru": "Ботфорты - лучший выбор"}',
    '{"sr": "Čizme iznad kolena | Vondi", "en": "Over-the-Knee Boots | Vondi", "ru": "Ботфорты | Vondi"}',
    '{"sr": "Kupite Čizme iznad kolena na Vondi", "en": "Buy Over-the-Knee Boots on Vondi", "ru": "Купите Ботфорты на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'zenska-obuca' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'zenska-obuca' AND level = 2) || '/cizme-iznad-kolena',
    1052,
    '👢',
    true
  ),
  (
    'gležnjace',
    '{"sr": "Gležnjače", "en": "Ankle Boots", "ru": "Ботильоны"}',
    '{"sr": "Gležnjače - najbolja ponuda", "en": "Ankle Boots - best selection", "ru": "Ботильоны - лучший выбор"}',
    '{"sr": "Gležnjače | Vondi", "en": "Ankle Boots | Vondi", "ru": "Ботильоны | Vondi"}',
    '{"sr": "Kupite Gležnjače na Vondi", "en": "Buy Ankle Boots on Vondi", "ru": "Купите Ботильоны на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'zenska-obuca' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'zenska-obuca' AND level = 2) || '/gležnjace',
    1053,
    '👢',
    true
  ),
  (
    'sandale-zenske',
    '{"sr": "Ženske sandale", "en": "Womens Sandals", "ru": "Женские сандалии"}',
    '{"sr": "Ženske sandale - najbolja ponuda", "en": "Womens Sandals - best selection", "ru": "Женские сандалии - лучший выбор"}',
    '{"sr": "Ženske sandale | Vondi", "en": "Womens Sandals | Vondi", "ru": "Женские сандалии | Vondi"}',
    '{"sr": "Kupite Ženske sandale na Vondi", "en": "Buy Womens Sandals on Vondi", "ru": "Купите Женские сандалии на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'zenska-obuca' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'zenska-obuca' AND level = 2) || '/sandale-zenske',
    1054,
    '👡',
    true
  ),
  (
    'espadrile',
    '{"sr": "Espadrile", "en": "Espadrilles", "ru": "Эспадрильи"}',
    '{"sr": "Espadrile - najbolja ponuda", "en": "Espadrilles - best selection", "ru": "Эспадрильи - лучший выбор"}',
    '{"sr": "Espadrile | Vondi", "en": "Espadrilles | Vondi", "ru": "Эспадрильи | Vondi"}',
    '{"sr": "Kupite Espadrile na Vondi", "en": "Buy Espadrilles on Vondi", "ru": "Купите Эспадрильи на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'zenska-obuca' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'zenska-obuca' AND level = 2) || '/espadrile',
    1055,
    '👟',
    true
  ),
  (
    'patike-decije-0-2',
    '{"sr": "Dečije patike 0-2 god", "en": "Baby Shoes 0-2 years", "ru": "Детская обувь 0-2 года"}',
    '{"sr": "Dečije patike 0-2 god - najbolja ponuda", "en": "Baby Shoes 0-2 years - best selection", "ru": "Детская обувь 0-2 года - лучший выбор"}',
    '{"sr": "Dečije patike 0-2 god | Vondi", "en": "Baby Shoes 0-2 years | Vondi", "ru": "Детская обувь 0-2 года | Vondi"}',
    '{"sr": "Kupite Dečije patike 0-2 god na Vondi", "en": "Buy Baby Shoes 0-2 years on Vondi", "ru": "Купите Детская обувь 0-2 года на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'decija-obuca' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'decija-obuca' AND level = 2) || '/patike-decije-0-2',
    1056,
    '👶',
    true
  ),
  (
    'patike-decije-3-6',
    '{"sr": "Dečije patike 3-6 god", "en": "Kids Shoes 3-6 years", "ru": "Детская обувь 3-6 лет"}',
    '{"sr": "Dečije patike 3-6 god - najbolja ponuda", "en": "Kids Shoes 3-6 years - best selection", "ru": "Детская обувь 3-6 лет - лучший выбор"}',
    '{"sr": "Dečije patike 3-6 god | Vondi", "en": "Kids Shoes 3-6 years | Vondi", "ru": "Детская обувь 3-6 лет | Vondi"}',
    '{"sr": "Kupite Dečije patike 3-6 god na Vondi", "en": "Buy Kids Shoes 3-6 years on Vondi", "ru": "Купите Детская обувь 3-6 лет на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'decija-obuca' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'decija-obuca' AND level = 2) || '/patike-decije-3-6',
    1057,
    '👧',
    true
  ),
  (
    'patike-decije-7-12',
    '{"sr": "Dečije patike 7-12 god", "en": "Kids Shoes 7-12 years", "ru": "Детская обувь 7-12 лет"}',
    '{"sr": "Dečije patike 7-12 god - najbolja ponuda", "en": "Kids Shoes 7-12 years - best selection", "ru": "Детская обувь 7-12 лет - лучший выбор"}',
    '{"sr": "Dečije patike 7-12 god | Vondi", "en": "Kids Shoes 7-12 years | Vondi", "ru": "Детская обувь 7-12 лет | Vondi"}',
    '{"sr": "Kupite Dečije patike 7-12 god na Vondi", "en": "Buy Kids Shoes 7-12 years on Vondi", "ru": "Купите Детская обувь 7-12 лет на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'decija-obuca' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'decija-obuca' AND level = 2) || '/patike-decije-7-12',
    1058,
    '👦',
    true
  ),
  (
    'sandale-decije',
    '{"sr": "Dečije sandale", "en": "Kids Sandals", "ru": "Детские сандалии"}',
    '{"sr": "Dečije sandale - najbolja ponuda", "en": "Kids Sandals - best selection", "ru": "Детские сандалии - лучший выбор"}',
    '{"sr": "Dečije sandale | Vondi", "en": "Kids Sandals | Vondi", "ru": "Детские сандалии | Vondi"}',
    '{"sr": "Kupite Dečije sandale na Vondi", "en": "Buy Kids Sandals on Vondi", "ru": "Купите Детские сандалии на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'decija-obuca' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'decija-obuca' AND level = 2) || '/sandale-decije',
    1059,
    '👡',
    true
  ),
  (
    'cizme-decije',
    '{"sr": "Dečije čizme", "en": "Kids Boots", "ru": "Детские ботинки"}',
    '{"sr": "Dečije čizme - najbolja ponuda", "en": "Kids Boots - best selection", "ru": "Детские ботинки - лучший выбор"}',
    '{"sr": "Dečije čizme | Vondi", "en": "Kids Boots | Vondi", "ru": "Детские ботинки | Vondi"}',
    '{"sr": "Kupite Dečije čizme na Vondi", "en": "Buy Kids Boots on Vondi", "ru": "Купите Детские ботинки на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'decija-obuca' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'decija-obuca' AND level = 2) || '/cizme-decije',
    1060,
    '🥾',
    true
  ),
  (
    'papuce-decije',
    '{"sr": "Dečije papuče", "en": "Kids Slippers", "ru": "Детские тапочки"}',
    '{"sr": "Dečije papuče - najbolja ponuda", "en": "Kids Slippers - best selection", "ru": "Детские тапочки - лучший выбор"}',
    '{"sr": "Dečije papuče | Vondi", "en": "Kids Slippers | Vondi", "ru": "Детские тапочки | Vondi"}',
    '{"sr": "Kupite Dečije papuče na Vondi", "en": "Buy Kids Slippers on Vondi", "ru": "Купите Детские тапочки на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'decija-obuca' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'decija-obuca' AND level = 2) || '/papuce-decije',
    1061,
    '🩴',
    true
  )
;

-- Verification
DO $$
DECLARE
  duplicate_count INT;
BEGIN
  SELECT COUNT(*) INTO duplicate_count FROM (
    SELECT slug, COUNT(*) FROM categories GROUP BY slug HAVING COUNT(*) > 1
  ) dup;
  IF duplicate_count > 0 THEN
    RAISE EXCEPTION 'Found % duplicate slugs!', duplicate_count;
  END IF;
  RAISE NOTICE 'No duplicates found ✅';
  RAISE NOTICE 'Successfully added L3 categories';
END $$;