-- Migration: L3 Categories
-- Date: 2025-12-17

INSERT INTO categories (slug, name, description, meta_title, meta_description, parent_id, level, path, sort_order, icon, is_active)
VALUES
  (
    'trosed-kauci',
    '{"sr": "Trosed kauči", "en": "Three-Seater Sofas", "ru": "Трехместные диваны"}',
    '{"sr": "Trosed kauči - najbolja ponuda", "en": "Three-Seater Sofas - best selection", "ru": "Трехместные диваны - лучший выбор"}',
    '{"sr": "Trosed kauči | Vondi", "en": "Three-Seater Sofas | Vondi", "ru": "Трехместные диваны | Vondi"}',
    '{"sr": "Kupite Trosed kauči na Vondi", "en": "Buy Three-Seater Sofas on Vondi", "ru": "Купите Трехместные диваны на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'namestaj-dnevna-soba' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'namestaj-dnevna-soba' AND level = 2) || '/trosed-kauci',
    2001,
    '🛋️',
    true
  ),
  (
    'dvosed-kauci',
    '{"sr": "Dvosed kauči", "en": "Two-Seater Sofas", "ru": "Двухместные диваны"}',
    '{"sr": "Dvosed kauči - najbolja ponuda", "en": "Two-Seater Sofas - best selection", "ru": "Двухместные диваны - лучший выбор"}',
    '{"sr": "Dvosed kauči | Vondi", "en": "Two-Seater Sofas | Vondi", "ru": "Двухместные диваны | Vondi"}',
    '{"sr": "Kupite Dvosed kauči na Vondi", "en": "Buy Two-Seater Sofas on Vondi", "ru": "Купите Двухместные диваны на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'namestaj-dnevna-soba' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'namestaj-dnevna-soba' AND level = 2) || '/dvosed-kauci',
    2002,
    '🛋️',
    true
  ),
  (
    'ugaone-garniture',
    '{"sr": "Ugaone garniture", "en": "Corner Sofas", "ru": "Угловые диваны"}',
    '{"sr": "Ugaone garniture - najbolja ponuda", "en": "Corner Sofas - best selection", "ru": "Угловые диваны - лучший выбор"}',
    '{"sr": "Ugaone garniture | Vondi", "en": "Corner Sofas | Vondi", "ru": "Угловые диваны | Vondi"}',
    '{"sr": "Kupite Ugaone garniture na Vondi", "en": "Buy Corner Sofas on Vondi", "ru": "Купите Угловые диваны на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'namestaj-dnevna-soba' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'namestaj-dnevna-soba' AND level = 2) || '/ugaone-garniture',
    2003,
    '🛋️',
    true
  ),
  (
    'fotelje',
    '{"sr": "Fotelje", "en": "Armchairs", "ru": "Кресла"}',
    '{"sr": "Fotelje - najbolja ponuda", "en": "Armchairs - best selection", "ru": "Кресла - лучший выбор"}',
    '{"sr": "Fotelje | Vondi", "en": "Armchairs | Vondi", "ru": "Кресла | Vondi"}',
    '{"sr": "Kupite Fotelje na Vondi", "en": "Buy Armchairs on Vondi", "ru": "Купите Кресла на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'namestaj-dnevna-soba' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'namestaj-dnevna-soba' AND level = 2) || '/fotelje',
    2004,
    '🪑',
    true
  ),
  (
    'klupa-za-hodnik',
    '{"sr": "Klupe za hodnik", "en": "Hallway Benches", "ru": "Скамейки для прихожей"}',
    '{"sr": "Klupe za hodnik - najbolja ponuda", "en": "Hallway Benches - best selection", "ru": "Скамейки для прихожей - лучший выбор"}',
    '{"sr": "Klupe za hodnik | Vondi", "en": "Hallway Benches | Vondi", "ru": "Скамейки для прихожей | Vondi"}',
    '{"sr": "Kupite Klupe za hodnik na Vondi", "en": "Buy Hallway Benches on Vondi", "ru": "Купите Скамейки для прихожей на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'namestaj-dnevna-soba' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'namestaj-dnevna-soba' AND level = 2) || '/klupa-za-hodnik',
    2005,
    '🪑',
    true
  ),
  (
    'tv-komode',
    '{"sr": "TV komode", "en": "TV Stands", "ru": "ТВ тумбы"}',
    '{"sr": "TV komode - najbolja ponuda", "en": "TV Stands - best selection", "ru": "ТВ тумбы - лучший выбор"}',
    '{"sr": "TV komode | Vondi", "en": "TV Stands | Vondi", "ru": "ТВ тумбы | Vondi"}',
    '{"sr": "Kupite TV komode na Vondi", "en": "Buy TV Stands on Vondi", "ru": "Купите ТВ тумбы на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'namestaj-dnevna-soba' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'namestaj-dnevna-soba' AND level = 2) || '/tv-komode',
    2006,
    '📺',
    true
  ),
  (
    'police-za-knjige',
    '{"sr": "Police za knjige", "en": "Bookshelves", "ru": "Книжные полки"}',
    '{"sr": "Police za knjige - najbolja ponuda", "en": "Bookshelves - best selection", "ru": "Книжные полки - лучший выбор"}',
    '{"sr": "Police za knjige | Vondi", "en": "Bookshelves | Vondi", "ru": "Книжные полки | Vondi"}',
    '{"sr": "Kupite Police za knjige na Vondi", "en": "Buy Bookshelves on Vondi", "ru": "Купите Книжные полки на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'namestaj-dnevna-soba' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'namestaj-dnevna-soba' AND level = 2) || '/police-za-knjige',
    2007,
    '📚',
    true
  ),
  (
    'vitrini',
    '{"sr": "Vitrini", "en": "Display Cabinets", "ru": "Витрины"}',
    '{"sr": "Vitrini - najbolja ponuda", "en": "Display Cabinets - best selection", "ru": "Витрины - лучший выбор"}',
    '{"sr": "Vitrini | Vondi", "en": "Display Cabinets | Vondi", "ru": "Витрины | Vondi"}',
    '{"sr": "Kupite Vitrini na Vondi", "en": "Buy Display Cabinets on Vondi", "ru": "Купите Витрины на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'namestaj-dnevna-soba' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'namestaj-dnevna-soba' AND level = 2) || '/vitrini',
    2008,
    '🏛️',
    true
  ),
  (
    'stolici-za-trpezariju',
    '{"sr": "Stolice za trpezariju", "en": "Dining Chairs", "ru": "Стулья для столовой"}',
    '{"sr": "Stolice za trpezariju - najbolja ponuda", "en": "Dining Chairs - best selection", "ru": "Стулья для столовой - лучший выбор"}',
    '{"sr": "Stolice za trpezariju | Vondi", "en": "Dining Chairs | Vondi", "ru": "Стулья для столовой | Vondi"}',
    '{"sr": "Kupite Stolice za trpezariju na Vondi", "en": "Buy Dining Chairs on Vondi", "ru": "Купите Стулья для столовой на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'namestaj-dnevna-soba' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'namestaj-dnevna-soba' AND level = 2) || '/stolici-za-trpezariju',
    2009,
    '🪑',
    true
  ),
  (
    'trpezarijski-stolovi',
    '{"sr": "Trpezarijski stolovi", "en": "Dining Tables", "ru": "Обеденные столы"}',
    '{"sr": "Trpezarijski stolovi - najbolja ponuda", "en": "Dining Tables - best selection", "ru": "Обеденные столы - лучший выбор"}',
    '{"sr": "Trpezarijski stolovi | Vondi", "en": "Dining Tables | Vondi", "ru": "Обеденные столы | Vondi"}',
    '{"sr": "Kupite Trpezarijski stolovi na Vondi", "en": "Buy Dining Tables on Vondi", "ru": "Купите Обеденные столы на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'namestaj-dnevna-soba' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'namestaj-dnevna-soba' AND level = 2) || '/trpezarijski-stolovi',
    2010,
    '🍽️',
    true
  ),
  (
    'bracni-kreveti',
    '{"sr": "Bračni kreveti", "en": "Double Beds", "ru": "Двуспальные кровати"}',
    '{"sr": "Bračni kreveti - najbolja ponuda", "en": "Double Beds - best selection", "ru": "Двуспальные кровати - лучший выбор"}',
    '{"sr": "Bračni kreveti | Vondi", "en": "Double Beds | Vondi", "ru": "Двуспальные кровати | Vondi"}',
    '{"sr": "Kupite Bračni kreveti na Vondi", "en": "Buy Double Beds on Vondi", "ru": "Купите Двуспальные кровати на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'namestaj-spavaca-soba' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'namestaj-spavaca-soba' AND level = 2) || '/bracni-kreveti',
    2011,
    '🛏️',
    true
  ),
  (
    'boks-kreveti',
    '{"sr": "Box kreveti", "en": "Box Spring Beds", "ru": "Кровати с боксом"}',
    '{"sr": "Box kreveti - najbolja ponuda", "en": "Box Spring Beds - best selection", "ru": "Кровати с боксом - лучший выбор"}',
    '{"sr": "Box kreveti | Vondi", "en": "Box Spring Beds | Vondi", "ru": "Кровати с боксом | Vondi"}',
    '{"sr": "Kupite Box kreveti na Vondi", "en": "Buy Box Spring Beds on Vondi", "ru": "Купите Кровати с боксом на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'namestaj-spavaca-soba' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'namestaj-spavaca-soba' AND level = 2) || '/boks-kreveti',
    2012,
    '🛏️',
    true
  ),
  (
    'kreveti-jednostruki',
    '{"sr": "Jednostruki kreveti", "en": "Single Beds", "ru": "Односпальные кровати"}',
    '{"sr": "Jednostruki kreveti - najbolja ponuda", "en": "Single Beds - best selection", "ru": "Односпальные кровати - лучший выбор"}',
    '{"sr": "Jednostruki kreveti | Vondi", "en": "Single Beds | Vondi", "ru": "Односпальные кровати | Vondi"}',
    '{"sr": "Kupite Jednostruki kreveti na Vondi", "en": "Buy Single Beds on Vondi", "ru": "Купите Односпальные кровати на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'namestaj-spavaca-soba' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'namestaj-spavaca-soba' AND level = 2) || '/kreveti-jednostruki',
    2013,
    '🛏️',
    true
  ),
  (
    'ormani-garderoberi',
    '{"sr": "Ormani garderoberi", "en": "Wardrobes", "ru": "Шкафы"}',
    '{"sr": "Ormani garderoberi - najbolja ponuda", "en": "Wardrobes - best selection", "ru": "Шкафы - лучший выбор"}',
    '{"sr": "Ormani garderoberi | Vondi", "en": "Wardrobes | Vondi", "ru": "Шкафы | Vondi"}',
    '{"sr": "Kupite Ormani garderoberi na Vondi", "en": "Buy Wardrobes on Vondi", "ru": "Купите Шкафы на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'namestaj-spavaca-soba' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'namestaj-spavaca-soba' AND level = 2) || '/ormani-garderoberi',
    2014,
    '🚪',
    true
  ),
  (
    'nocni-ormancici',
    '{"sr": "Noćni ormarići", "en": "Nightstands", "ru": "Прикроватные тумбочки"}',
    '{"sr": "Noćni ormarići - najbolja ponuda", "en": "Nightstands - best selection", "ru": "Прикроватные тумбочки - лучший выбор"}',
    '{"sr": "Noćni ormarići | Vondi", "en": "Nightstands | Vondi", "ru": "Прикроватные тумбочки | Vondi"}',
    '{"sr": "Kupite Noćni ormarići na Vondi", "en": "Buy Nightstands on Vondi", "ru": "Купите Прикроватные тумбочки на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'namestaj-spavaca-soba' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'namestaj-spavaca-soba' AND level = 2) || '/nocni-ormancici',
    2015,
    '🛋️',
    true
  ),
  (
    'toaletni-stolovi',
    '{"sr": "Toaletni stolovi", "en": "Vanity Tables", "ru": "Туалетные столики"}',
    '{"sr": "Toaletni stolovi - najbolja ponuda", "en": "Vanity Tables - best selection", "ru": "Туалетные столики - лучший выбор"}',
    '{"sr": "Toaletni stolovi | Vondi", "en": "Vanity Tables | Vondi", "ru": "Туалетные столики | Vondi"}',
    '{"sr": "Kupite Toaletni stolovi na Vondi", "en": "Buy Vanity Tables on Vondi", "ru": "Купите Туалетные столики на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'namestaj-spavaca-soba' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'namestaj-spavaca-soba' AND level = 2) || '/toaletni-stolovi',
    2016,
    '💄',
    true
  ),
  (
    'lavaboi',
    '{"sr": "Lavaboi", "en": "Sinks", "ru": "Раковины"}',
    '{"sr": "Lavaboi - najbolja ponuda", "en": "Sinks - best selection", "ru": "Раковины - лучший выбор"}',
    '{"sr": "Lavaboi | Vondi", "en": "Sinks | Vondi", "ru": "Раковины | Vondi"}',
    '{"sr": "Kupite Lavaboi na Vondi", "en": "Buy Sinks on Vondi", "ru": "Купите Раковины на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'kupatilo' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'kupatilo' AND level = 2) || '/lavaboi',
    2017,
    '🚰',
    true
  ),
  (
    'kadе-kupatilo',
    '{"sr": "Kade", "en": "Bathtubs", "ru": "Ванны"}',
    '{"sr": "Kade - najbolja ponuda", "en": "Bathtubs - best selection", "ru": "Ванны - лучший выбор"}',
    '{"sr": "Kade | Vondi", "en": "Bathtubs | Vondi", "ru": "Ванны | Vondi"}',
    '{"sr": "Kupite Kade na Vondi", "en": "Buy Bathtubs on Vondi", "ru": "Купите Ванны на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'kupatilo' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'kupatilo' AND level = 2) || '/kadе-kupatilo',
    2018,
    '🛁',
    true
  ),
  (
    'tus-kabine',
    '{"sr": "Tuš kabine", "en": "Shower Cabins", "ru": "Душевые кабины"}',
    '{"sr": "Tuš kabine - najbolja ponuda", "en": "Shower Cabins - best selection", "ru": "Душевые кабины - лучший выбор"}',
    '{"sr": "Tuš kabine | Vondi", "en": "Shower Cabins | Vondi", "ru": "Душевые кабины | Vondi"}',
    '{"sr": "Kupite Tuš kabine na Vondi", "en": "Buy Shower Cabins on Vondi", "ru": "Купите Душевые кабины на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'kupatilo' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'kupatilo' AND level = 2) || '/tus-kabine',
    2019,
    '🚿',
    true
  ),
  (
    'toalet-skoljke',
    '{"sr": "Toalet školjke", "en": "Toilets", "ru": "Унитазы"}',
    '{"sr": "Toalet školjke - najbolja ponuda", "en": "Toilets - best selection", "ru": "Унитазы - лучший выбор"}',
    '{"sr": "Toalet školjke | Vondi", "en": "Toilets | Vondi", "ru": "Унитазы | Vondi"}',
    '{"sr": "Kupite Toalet školjke na Vondi", "en": "Buy Toilets on Vondi", "ru": "Купите Унитазы на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'kupatilo' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'kupatilo' AND level = 2) || '/toalet-skoljke',
    2020,
    '🚽',
    true
  ),
  (
    'ogledala-kupatilo',
    '{"sr": "Ogledala za kupatilo", "en": "Bathroom Mirrors", "ru": "Зеркала для ванной"}',
    '{"sr": "Ogledala za kupatilo - najbolja ponuda", "en": "Bathroom Mirrors - best selection", "ru": "Зеркала для ванной - лучший выбор"}',
    '{"sr": "Ogledala za kupatilo | Vondi", "en": "Bathroom Mirrors | Vondi", "ru": "Зеркала для ванной | Vondi"}',
    '{"sr": "Kupite Ogledala za kupatilo na Vondi", "en": "Buy Bathroom Mirrors on Vondi", "ru": "Купите Зеркала для ванной на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'kupatilo' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'kupatilo' AND level = 2) || '/ogledala-kupatilo',
    2021,
    '🪞',
    true
  ),
  (
    'ormarici-kupatilo',
    '{"sr": "Ormarići za kupatilo", "en": "Bathroom Cabinets", "ru": "Шкафы для ванной"}',
    '{"sr": "Ormarići za kupatilo - najbolja ponuda", "en": "Bathroom Cabinets - best selection", "ru": "Шкафы для ванной - лучший выбор"}',
    '{"sr": "Ormarići za kupatilo | Vondi", "en": "Bathroom Cabinets | Vondi", "ru": "Шкафы для ванной | Vondi"}',
    '{"sr": "Kupite Ormarići za kupatilo na Vondi", "en": "Buy Bathroom Cabinets on Vondi", "ru": "Купите Шкафы для ванной на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'kupatilo' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'kupatilo' AND level = 2) || '/ormarici-kupatilo',
    2022,
    '🚪',
    true
  ),
  (
    'slavine',
    '{"sr": "Slavine", "en": "Faucets", "ru": "Смесители"}',
    '{"sr": "Slavine - najbolja ponuda", "en": "Faucets - best selection", "ru": "Смесители - лучший выбор"}',
    '{"sr": "Slavine | Vondi", "en": "Faucets | Vondi", "ru": "Смесители | Vondi"}',
    '{"sr": "Kupite Slavine na Vondi", "en": "Buy Faucets on Vondi", "ru": "Купите Смесители на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'kupatilo' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'kupatilo' AND level = 2) || '/slavine',
    2023,
    '🚰',
    true
  ),
  (
    'plafonijere-led',
    '{"sr": "LED plafonijere", "en": "LED Ceiling Lights", "ru": "LED потолочные светильники"}',
    '{"sr": "LED plafonijere - najbolja ponuda", "en": "LED Ceiling Lights - best selection", "ru": "LED потолочные светильники - лучший выбор"}',
    '{"sr": "LED plafonijere | Vondi", "en": "LED Ceiling Lights | Vondi", "ru": "LED потолочные светильники | Vondi"}',
    '{"sr": "Kupite LED plafonijere na Vondi", "en": "Buy LED Ceiling Lights on Vondi", "ru": "Купите LED потолочные светильники на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'rasveta' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'rasveta' AND level = 2) || '/plafonijere-led',
    2024,
    '💡',
    true
  ),
  (
    'lusteri',
    '{"sr": "Lusteri", "en": "Chandeliers", "ru": "Люстры"}',
    '{"sr": "Lusteri - najbolja ponuda", "en": "Chandeliers - best selection", "ru": "Люстры - лучший выбор"}',
    '{"sr": "Lusteri | Vondi", "en": "Chandeliers | Vondi", "ru": "Люстры | Vondi"}',
    '{"sr": "Kupite Lusteri na Vondi", "en": "Buy Chandeliers on Vondi", "ru": "Купите Люстры на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'rasveta' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'rasveta' AND level = 2) || '/lusteri',
    2025,
    '✨',
    true
  ),
  (
    'podne-lampe-moderne',
    '{"sr": "Moderne podne lampe", "en": "Modern Floor Lamps", "ru": "Современные напольные лампы"}',
    '{"sr": "Moderne podne lampe - najbolja ponuda", "en": "Modern Floor Lamps - best selection", "ru": "Современные напольные лампы - лучший выбор"}',
    '{"sr": "Moderne podne lampe | Vondi", "en": "Modern Floor Lamps | Vondi", "ru": "Современные напольные лампы | Vondi"}',
    '{"sr": "Kupite Moderne podne lampe na Vondi", "en": "Buy Modern Floor Lamps on Vondi", "ru": "Купите Современные напольные лампы на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'rasveta' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'rasveta' AND level = 2) || '/podne-lampe-moderne',
    2026,
    '🕯️',
    true
  ),
  (
    'stone-lampe-nocne',
    '{"sr": "Noćne stone lampe", "en": "Night Table Lamps", "ru": "Ночные настольные лампы"}',
    '{"sr": "Noćne stone lampe - najbolja ponuda", "en": "Night Table Lamps - best selection", "ru": "Ночные настольные лампы - лучший выбор"}',
    '{"sr": "Noćne stone lampe | Vondi", "en": "Night Table Lamps | Vondi", "ru": "Ночные настольные лампы | Vondi"}',
    '{"sr": "Kupite Noćne stone lampe na Vondi", "en": "Buy Night Table Lamps on Vondi", "ru": "Купите Ночные настольные лампы на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'rasveta' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'rasveta' AND level = 2) || '/stone-lampe-nocne',
    2027,
    '🛋️',
    true
  ),
  (
    'led-trake',
    '{"sr": "LED trake", "en": "LED Strips", "ru": "LED ленты"}',
    '{"sr": "LED trake - najbolja ponuda", "en": "LED Strips - best selection", "ru": "LED ленты - лучший выбор"}',
    '{"sr": "LED trake | Vondi", "en": "LED Strips | Vondi", "ru": "LED ленты | Vondi"}',
    '{"sr": "Kupite LED trake na Vondi", "en": "Buy LED Strips on Vondi", "ru": "Купите LED ленты на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'rasveta' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'rasveta' AND level = 2) || '/led-trake',
    2028,
    '💡',
    true
  ),
  (
    'spoljna-rasveta-led',
    '{"sr": "LED spoljna rasveta", "en": "LED Outdoor Lighting", "ru": "LED уличное освещение"}',
    '{"sr": "LED spoljna rasveta - najbolja ponuda", "en": "LED Outdoor Lighting - best selection", "ru": "LED уличное освещение - лучший выбор"}',
    '{"sr": "LED spoljna rasveta | Vondi", "en": "LED Outdoor Lighting | Vondi", "ru": "LED уличное освещение | Vondi"}',
    '{"sr": "Kupite LED spoljna rasveta na Vondi", "en": "Buy LED Outdoor Lighting on Vondi", "ru": "Купите LED уличное освещение на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'rasveta' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'rasveta' AND level = 2) || '/spoljna-rasveta-led',
    2029,
    '💡',
    true
  ),
  (
    'tegovi-bučice',
    '{"sr": "Tegovi i bučice", "en": "Weights and Dumbbells", "ru": "Гантели и гири"}',
    '{"sr": "Tegovi i bučice - najbolja ponuda", "en": "Weights and Dumbbells - best selection", "ru": "Гантели и гири - лучший выбор"}',
    '{"sr": "Tegovi i bučice | Vondi", "en": "Weights and Dumbbells | Vondi", "ru": "Гантели и гири | Vondi"}',
    '{"sr": "Kupite Tegovi i bučice na Vondi", "en": "Buy Weights and Dumbbells on Vondi", "ru": "Купите Гантели и гири на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'fitnes-i-teretana' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'fitnes-i-teretana' AND level = 2) || '/tegovi-bučice',
    2030,
    '🏋️',
    true
  ),
  (
    'tegovi-tegovi-disk',
    '{"sr": "Tegovi disk", "en": "Weight Plates", "ru": "Диски для штанги"}',
    '{"sr": "Tegovi disk - najbolja ponuda", "en": "Weight Plates - best selection", "ru": "Диски для штанги - лучший выбор"}',
    '{"sr": "Tegovi disk | Vondi", "en": "Weight Plates | Vondi", "ru": "Диски для штанги | Vondi"}',
    '{"sr": "Kupite Tegovi disk na Vondi", "en": "Buy Weight Plates on Vondi", "ru": "Купите Диски для штанги на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'fitnes-i-teretana' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'fitnes-i-teretana' AND level = 2) || '/tegovi-tegovi-disk',
    2031,
    '⚖️',
    true
  ),
  (
    'bencevi',
    '{"sr": "Bencevi za vežbanje", "en": "Weight Benches", "ru": "Скамьи для жима"}',
    '{"sr": "Bencevi za vežbanje - najbolja ponuda", "en": "Weight Benches - best selection", "ru": "Скамьи для жима - лучший выбор"}',
    '{"sr": "Bencevi za vežbanje | Vondi", "en": "Weight Benches | Vondi", "ru": "Скамьи для жима | Vondi"}',
    '{"sr": "Kupite Bencevi za vežbanje na Vondi", "en": "Buy Weight Benches on Vondi", "ru": "Купите Скамьи для жима на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'fitnes-i-teretana' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'fitnes-i-teretana' AND level = 2) || '/bencevi',
    2032,
    '🛋️',
    true
  ),
  (
    'tred-milin',
    '{"sr": "Traka za trčanje", "en": "Treadmills", "ru": "Беговые дорожки"}',
    '{"sr": "Traka za trčanje - najbolja ponuda", "en": "Treadmills - best selection", "ru": "Беговые дорожки - лучший выбор"}',
    '{"sr": "Traka za trčanje | Vondi", "en": "Treadmills | Vondi", "ru": "Беговые дорожки | Vondi"}',
    '{"sr": "Kupite Traka za trčanje na Vondi", "en": "Buy Treadmills on Vondi", "ru": "Купите Беговые дорожки на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'fitnes-i-teretana' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'fitnes-i-teretana' AND level = 2) || '/tred-milin',
    2033,
    '🏃',
    true
  ),
  (
    'bicikl-sobni',
    '{"sr": "Sobni bicikl", "en": "Exercise Bikes", "ru": "Велотренажеры"}',
    '{"sr": "Sobni bicikl - najbolja ponuda", "en": "Exercise Bikes - best selection", "ru": "Велотренажеры - лучший выбор"}',
    '{"sr": "Sobni bicikl | Vondi", "en": "Exercise Bikes | Vondi", "ru": "Велотренажеры | Vondi"}',
    '{"sr": "Kupite Sobni bicikl na Vondi", "en": "Buy Exercise Bikes on Vondi", "ru": "Купите Велотренажеры на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'fitnes-i-teretana' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'fitnes-i-teretana' AND level = 2) || '/bicikl-sobni',
    2034,
    '🚴',
    true
  ),
  (
    'veslacki-masine',
    '{"sr": "Veslački mašine", "en": "Rowing Machines", "ru": "Гребные тренажеры"}',
    '{"sr": "Veslački mašine - najbolja ponuda", "en": "Rowing Machines - best selection", "ru": "Гребные тренажеры - лучший выбор"}',
    '{"sr": "Veslački mašine | Vondi", "en": "Rowing Machines | Vondi", "ru": "Гребные тренажеры | Vondi"}',
    '{"sr": "Kupite Veslački mašine na Vondi", "en": "Buy Rowing Machines on Vondi", "ru": "Купите Гребные тренажеры на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'fitnes-i-teretana' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'fitnes-i-teretana' AND level = 2) || '/veslacki-masine',
    2035,
    '🚣',
    true
  ),
  (
    'elipticne-masine',
    '{"sr": "Eliptične mašine", "en": "Elliptical Machines", "ru": "Эллиптические тренажеры"}',
    '{"sr": "Eliptične mašine - najbolja ponuda", "en": "Elliptical Machines - best selection", "ru": "Эллиптические тренажеры - лучший выбор"}',
    '{"sr": "Eliptične mašine | Vondi", "en": "Elliptical Machines | Vondi", "ru": "Эллиптические тренажеры | Vondi"}',
    '{"sr": "Kupite Eliptične mašine na Vondi", "en": "Buy Elliptical Machines on Vondi", "ru": "Купите Эллиптические тренажеры на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'fitnes-i-teretana' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'fitnes-i-teretana' AND level = 2) || '/elipticne-masine',
    2036,
    '🏃',
    true
  ),
  (
    'joga-strunjace',
    '{"sr": "Joga strunjače", "en": "Yoga Mats", "ru": "Йога коврики"}',
    '{"sr": "Joga strunjače - najbolja ponuda", "en": "Yoga Mats - best selection", "ru": "Йога коврики - лучший выбор"}',
    '{"sr": "Joga strunjače | Vondi", "en": "Yoga Mats | Vondi", "ru": "Йога коврики | Vondi"}',
    '{"sr": "Kupite Joga strunjače na Vondi", "en": "Buy Yoga Mats on Vondi", "ru": "Купите Йога коврики на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'fitnes-i-teretana' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'fitnes-i-teretana' AND level = 2) || '/joga-strunjace',
    2037,
    '🧘',
    true
  ),
  (
    'pilates-lopte',
    '{"sr": "Pilates lopte", "en": "Pilates Balls", "ru": "Пилатес мячи"}',
    '{"sr": "Pilates lopte - najbolja ponuda", "en": "Pilates Balls - best selection", "ru": "Пилатес мячи - лучший выбор"}',
    '{"sr": "Pilates lopte | Vondi", "en": "Pilates Balls | Vondi", "ru": "Пилатес мячи | Vondi"}',
    '{"sr": "Kupite Pilates lopte na Vondi", "en": "Buy Pilates Balls on Vondi", "ru": "Купите Пилатес мячи на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'fitnes-i-teretana' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'fitnes-i-teretana' AND level = 2) || '/pilates-lopte',
    2038,
    '⚽',
    true
  ),
  (
    'mtb-bicikli',
    '{"sr": "MTB bicikli", "en": "Mountain Bikes", "ru": "Горные велосипеды"}',
    '{"sr": "MTB bicikli - najbolja ponuda", "en": "Mountain Bikes - best selection", "ru": "Горные велосипеды - лучший выбор"}',
    '{"sr": "MTB bicikli | Vondi", "en": "Mountain Bikes | Vondi", "ru": "Горные велосипеды | Vondi"}',
    '{"sr": "Kupite MTB bicikli na Vondi", "en": "Buy Mountain Bikes on Vondi", "ru": "Купите Горные велосипеды на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'bicikli-i-trotineti' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'bicikli-i-trotineti' AND level = 2) || '/mtb-bicikli',
    2039,
    '🚵',
    true
  ),
  (
    'drumski-bicikli',
    '{"sr": "Drumski bicikli", "en": "Road Bikes", "ru": "Шоссейные велосипеды"}',
    '{"sr": "Drumski bicikli - najbolja ponuda", "en": "Road Bikes - best selection", "ru": "Шоссейные велосипеды - лучший выбор"}',
    '{"sr": "Drumski bicikli | Vondi", "en": "Road Bikes | Vondi", "ru": "Шоссейные велосипеды | Vondi"}',
    '{"sr": "Kupite Drumski bicikli na Vondi", "en": "Buy Road Bikes on Vondi", "ru": "Купите Шоссейные велосипеды на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'bicikli-i-trotineti' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'bicikli-i-trotineti' AND level = 2) || '/drumski-bicikli',
    2040,
    '🚴',
    true
  ),
  (
    'gradski-bicikli',
    '{"sr": "Gradski bicikli", "en": "City Bikes", "ru": "Городские велосипеды"}',
    '{"sr": "Gradski bicikli - najbolja ponuda", "en": "City Bikes - best selection", "ru": "Городские велосипеды - лучший выбор"}',
    '{"sr": "Gradski bicikli | Vondi", "en": "City Bikes | Vondi", "ru": "Городские велосипеды | Vondi"}',
    '{"sr": "Kupite Gradski bicikli na Vondi", "en": "Buy City Bikes on Vondi", "ru": "Купите Городские велосипеды на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'bicikli-i-trotineti' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'bicikli-i-trotineti' AND level = 2) || '/gradski-bicikli',
    2041,
    '🚲',
    true
  ),
  (
    'bmx-bicikli',
    '{"sr": "BMX bicikli", "en": "BMX Bikes", "ru": "BMX велосипеды"}',
    '{"sr": "BMX bicikli - najbolja ponuda", "en": "BMX Bikes - best selection", "ru": "BMX велосипеды - лучший выбор"}',
    '{"sr": "BMX bicikli | Vondi", "en": "BMX Bikes | Vondi", "ru": "BMX велосипеды | Vondi"}',
    '{"sr": "Kupite BMX bicikli na Vondi", "en": "Buy BMX Bikes on Vondi", "ru": "Купите BMX велосипеды на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'bicikli-i-trotineti' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'bicikli-i-trotineti' AND level = 2) || '/bmx-bicikli',
    2042,
    '🚴',
    true
  ),
  (
    'deciji-bicikli',
    '{"sr": "Dečiji bicikli", "en": "Kids Bikes", "ru": "Детские велосипеды"}',
    '{"sr": "Dečiji bicikli - najbolja ponuda", "en": "Kids Bikes - best selection", "ru": "Детские велосипеды - лучший выбор"}',
    '{"sr": "Dečiji bicikli | Vondi", "en": "Kids Bikes | Vondi", "ru": "Детские велосипеды | Vondi"}',
    '{"sr": "Kupite Dečiji bicikli na Vondi", "en": "Buy Kids Bikes on Vondi", "ru": "Купите Детские велосипеды на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'bicikli-i-trotineti' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'bicikli-i-trotineti' AND level = 2) || '/deciji-bicikli',
    2043,
    '🚲',
    true
  ),
  (
    'elektricni-bicikli',
    '{"sr": "Električni bicikli", "en": "Electric Bikes", "ru": "Электровелосипеды"}',
    '{"sr": "Električni bicikli - najbolja ponuda", "en": "Electric Bikes - best selection", "ru": "Электровелосипеды - лучший выбор"}',
    '{"sr": "Električni bicikli | Vondi", "en": "Electric Bikes | Vondi", "ru": "Электровелосипеды | Vondi"}',
    '{"sr": "Kupite Električni bicikli na Vondi", "en": "Buy Electric Bikes on Vondi", "ru": "Купите Электровелосипеды на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'bicikli-i-trotineti' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'bicikli-i-trotineti' AND level = 2) || '/elektricni-bicikli',
    2044,
    '⚡',
    true
  ),
  (
    'elektricni-trotineti',
    '{"sr": "Električni trotineti", "en": "Electric Scooters", "ru": "Электросамокаты"}',
    '{"sr": "Električni trotineti - najbolja ponuda", "en": "Electric Scooters - best selection", "ru": "Электросамокаты - лучший выбор"}',
    '{"sr": "Električni trotineti | Vondi", "en": "Electric Scooters | Vondi", "ru": "Электросамокаты | Vondi"}',
    '{"sr": "Kupite Električni trotineti na Vondi", "en": "Buy Electric Scooters on Vondi", "ru": "Купите Электросамокаты на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'bicikli-i-trotineti' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'bicikli-i-trotineti' AND level = 2) || '/elektricni-trotineti',
    2045,
    '🛴',
    true
  ),
  (
    'trotineti-deca',
    '{"sr": "Trotineti za decu", "en": "Kids Scooters", "ru": "Детские самокаты"}',
    '{"sr": "Trotineti za decu - najbolja ponuda", "en": "Kids Scooters - best selection", "ru": "Детские самокаты - лучший выбор"}',
    '{"sr": "Trotineti za decu | Vondi", "en": "Kids Scooters | Vondi", "ru": "Детские самокаты | Vondi"}',
    '{"sr": "Kupite Trotineti za decu na Vondi", "en": "Buy Kids Scooters on Vondi", "ru": "Купите Детские самокаты на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'bicikli-i-trotineti' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'bicikli-i-trotineti' AND level = 2) || '/trotineti-deca',
    2046,
    '🛴',
    true
  ),
  (
    'bicikl-delovi',
    '{"sr": "Delovi za bicikl", "en": "Bicycle Parts", "ru": "Запчасти для велосипедов"}',
    '{"sr": "Delovi za bicikl - najbolja ponuda", "en": "Bicycle Parts - best selection", "ru": "Запчасти для велосипедов - лучший выбор"}',
    '{"sr": "Delovi za bicikl | Vondi", "en": "Bicycle Parts | Vondi", "ru": "Запчасти для велосипедов | Vondi"}',
    '{"sr": "Kupite Delovi za bicikl na Vondi", "en": "Buy Bicycle Parts on Vondi", "ru": "Купите Запчасти для велосипедов на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'bicikli-i-trotineti' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'bicikli-i-trotineti' AND level = 2) || '/bicikl-delovi',
    2047,
    '🔧',
    true
  ),
  (
    'satori-2-osobe',
    '{"sr": "Šatori za 2 osobe", "en": "2-Person Tents", "ru": "Палатки на 2 человека"}',
    '{"sr": "Šatori za 2 osobe - najbolja ponuda", "en": "2-Person Tents - best selection", "ru": "Палатки на 2 человека - лучший выбор"}',
    '{"sr": "Šatori za 2 osobe | Vondi", "en": "2-Person Tents | Vondi", "ru": "Палатки на 2 человека | Vondi"}',
    '{"sr": "Kupite Šatori za 2 osobe na Vondi", "en": "Buy 2-Person Tents on Vondi", "ru": "Купите Палатки на 2 человека на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'kampovanje' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'kampovanje' AND level = 2) || '/satori-2-osobe',
    2048,
    '⛺',
    true
  ),
  (
    'satori-4-osobe',
    '{"sr": "Šatori za 4 osobe", "en": "4-Person Tents", "ru": "Палатки на 4 человека"}',
    '{"sr": "Šatori za 4 osobe - najbolja ponuda", "en": "4-Person Tents - best selection", "ru": "Палатки на 4 человека - лучший выбор"}',
    '{"sr": "Šatori za 4 osobe | Vondi", "en": "4-Person Tents | Vondi", "ru": "Палатки на 4 человека | Vondi"}',
    '{"sr": "Kupite Šatori za 4 osobe na Vondi", "en": "Buy 4-Person Tents on Vondi", "ru": "Купите Палатки на 4 человека на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'kampovanje' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'kampovanje' AND level = 2) || '/satori-4-osobe',
    2049,
    '⛺',
    true
  ),
  (
    'satori-porodicni',
    '{"sr": "Porodični šatori", "en": "Family Tents", "ru": "Семейные палатки"}',
    '{"sr": "Porodični šatori - najbolja ponuda", "en": "Family Tents - best selection", "ru": "Семейные палатки - лучший выбор"}',
    '{"sr": "Porodični šatori | Vondi", "en": "Family Tents | Vondi", "ru": "Семейные палатки | Vondi"}',
    '{"sr": "Kupite Porodični šatori na Vondi", "en": "Buy Family Tents on Vondi", "ru": "Купите Семейные палатки на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'kampovanje' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'kampovanje' AND level = 2) || '/satori-porodicni',
    2050,
    '⛺',
    true
  ),
  (
    'vrece-spavanja',
    '{"sr": "Vreće za spavanje", "en": "Sleeping Bags", "ru": "Спальные мешки"}',
    '{"sr": "Vreće za spavanje - najbolja ponuda", "en": "Sleeping Bags - best selection", "ru": "Спальные мешки - лучший выбор"}',
    '{"sr": "Vreće za spavanje | Vondi", "en": "Sleeping Bags | Vondi", "ru": "Спальные мешки | Vondi"}',
    '{"sr": "Kupite Vreće za spavanje na Vondi", "en": "Buy Sleeping Bags on Vondi", "ru": "Купите Спальные мешки на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'kampovanje' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'kampovanje' AND level = 2) || '/vrece-spavanja',
    2051,
    '😴',
    true
  ),
  (
    'prostirke-kamp',
    '{"sr": "Kamp prostirke", "en": "Camping Mats", "ru": "Туристические коврики"}',
    '{"sr": "Kamp prostirke - najbolja ponuda", "en": "Camping Mats - best selection", "ru": "Туристические коврики - лучший выбор"}',
    '{"sr": "Kamp prostirke | Vondi", "en": "Camping Mats | Vondi", "ru": "Туристические коврики | Vondi"}',
    '{"sr": "Kupite Kamp prostirke na Vondi", "en": "Buy Camping Mats on Vondi", "ru": "Купите Туристические коврики на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'kampovanje' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'kampovanje' AND level = 2) || '/prostirke-kamp',
    2052,
    '🏕️',
    true
  ),
  (
    'kamp-stolice',
    '{"sr": "Kamp stolice", "en": "Camping Chairs", "ru": "Кемпинговые стулья"}',
    '{"sr": "Kamp stolice - najbolja ponuda", "en": "Camping Chairs - best selection", "ru": "Кемпинговые стулья - лучший выбор"}',
    '{"sr": "Kamp stolice | Vondi", "en": "Camping Chairs | Vondi", "ru": "Кемпинговые стулья | Vondi"}',
    '{"sr": "Kupite Kamp stolice na Vondi", "en": "Buy Camping Chairs on Vondi", "ru": "Купите Кемпинговые стулья на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'kampovanje' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'kampovanje' AND level = 2) || '/kamp-stolice',
    2053,
    '🪑',
    true
  ),
  (
    'kamp-stolovi',
    '{"sr": "Kamp stolovi", "en": "Camping Tables", "ru": "Кемпинговые столы"}',
    '{"sr": "Kamp stolovi - najbolja ponuda", "en": "Camping Tables - best selection", "ru": "Кемпинговые столы - лучший выбор"}',
    '{"sr": "Kamp stolovi | Vondi", "en": "Camping Tables | Vondi", "ru": "Кемпинговые столы | Vondi"}',
    '{"sr": "Kupite Kamp stolovi na Vondi", "en": "Buy Camping Tables on Vondi", "ru": "Купите Кемпинговые столы на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'kampovanje' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'kampovanje' AND level = 2) || '/kamp-stolovi',
    2054,
    '🍽️',
    true
  ),
  (
    'dzepne-lampe',
    '{"sr": "Džepne lampe", "en": "Flashlights", "ru": "Фонарики"}',
    '{"sr": "Džepne lampe - najbolja ponuda", "en": "Flashlights - best selection", "ru": "Фонарики - лучший выбор"}',
    '{"sr": "Džepne lampe | Vondi", "en": "Flashlights | Vondi", "ru": "Фонарики | Vondi"}',
    '{"sr": "Kupite Džepne lampe na Vondi", "en": "Buy Flashlights on Vondi", "ru": "Купите Фонарики на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'kampovanje' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'kampovanje' AND level = 2) || '/dzepne-lampe',
    2055,
    '🔦',
    true
  ),
  (
    'prenosne-rostilji',
    '{"sr": "Prenosni roštilji", "en": "Portable Grills", "ru": "Портативные грили"}',
    '{"sr": "Prenosni roštilji - najbolja ponuda", "en": "Portable Grills - best selection", "ru": "Портативные грили - лучший выбор"}',
    '{"sr": "Prenosni roštilji | Vondi", "en": "Portable Grills | Vondi", "ru": "Портативные грили | Vondi"}',
    '{"sr": "Kupite Prenosni roštilji na Vondi", "en": "Buy Portable Grills on Vondi", "ru": "Купите Портативные грили на Vondi"}',
    (SELECT id FROM categories WHERE slug = 'kampovanje' AND level = 2),
    3,
    (SELECT path FROM categories WHERE slug = 'kampovanje' AND level = 2) || '/prenosne-rostilji',
    2056,
    '🔥',
    true
  )
;

-- Verification
DO $$
DECLARE
  duplicate_count INT;
BEGIN
  SELECT COUNT(*) INTO duplicate_count FROM (
    SELECT slug, COUNT(*) FROM categories GROUP BY slug HAVING COUNT(*) > 1
  ) dup;
  IF duplicate_count > 0 THEN
    RAISE EXCEPTION 'Found % duplicate slugs!', duplicate_count;
  END IF;
  RAISE NOTICE 'No duplicates found ✅';
  RAISE NOTICE 'Successfully added L3 categories';
END $$;