-- Migration: Complete L2 Categories - добавить 81 новых L2 категорий
-- Date: 2025-12-17
-- Target: Увеличить L2 до 400

INSERT INTO categories (slug, name, description, meta_title, meta_description, parent_id, level, path, sort_order, icon, is_active)
VALUES
  (
    'kosmeticke-uniforme',
    '{"sr": "Kozmetičke uniforme", "en": "Cosmetic Uniforms", "ru": "Косметическая униформа"}',
    '{"sr": "Kozmetičke uniforme - širok asortiman", "en": "Cosmetic Uniforms - wide range", "ru": "Косметическая униформа - широкий ассортимент"}',
    '{"sr": "Kozmetičke uniforme | Vondi", "en": "Cosmetic Uniforms | Vondi", "ru": "Косметическая униформа | Vondi"}',
    '{"sr": "Pronađite najbolje Kozmetičke uniforme na Vondi marketplace", "en": "Find the best Cosmetic Uniforms on Vondi marketplace", "ru": "Найдите лучшие Косметическая униформа на Vondi marketplace"}',
    (SELECT id FROM categories WHERE slug = 'odeca-i-obuca' AND level = 1),
    2,
    'odeca-i-obuca/kosmeticke-uniforme',
    301,
    '👗',
    true
  ),
  (
    'pidzhame-svila',
    '{"sr": "Pidžame od svile", "en": "Silk Pajamas", "ru": "Шелковые пижамы"}',
    '{"sr": "Pidžame od svile - širok asortiman", "en": "Silk Pajamas - wide range", "ru": "Шелковые пижамы - широкий ассортимент"}',
    '{"sr": "Pidžame od svile | Vondi", "en": "Silk Pajamas | Vondi", "ru": "Шелковые пижамы | Vondi"}',
    '{"sr": "Pronađite najbolje Pidžame od svile na Vondi marketplace", "en": "Find the best Silk Pajamas on Vondi marketplace", "ru": "Найдите лучшие Шелковые пижамы на Vondi marketplace"}',
    (SELECT id FROM categories WHERE slug = 'odeca-i-obuca' AND level = 1),
    2,
    'odeca-i-obuca/pidzhame-svila',
    302,
    '💤',
    true
  ),
  (
    'kucne-halјine',
    '{"sr": "Kućne haljine", "en": "House Dresses", "ru": "Домашние платья"}',
    '{"sr": "Kućne haljine - širok asortiman", "en": "House Dresses - wide range", "ru": "Домашние платья - широкий ассортимент"}',
    '{"sr": "Kućne haljine | Vondi", "en": "House Dresses | Vondi", "ru": "Домашние платья | Vondi"}',
    '{"sr": "Pronađite najbolje Kućne haljine na Vondi marketplace", "en": "Find the best House Dresses on Vondi marketplace", "ru": "Найдите лучшие Домашние платья на Vondi marketplace"}',
    (SELECT id FROM categories WHERE slug = 'odeca-i-obuca' AND level = 1),
    2,
    'odeca-i-obuca/kucne-halјine',
    303,
    '🏡',
    true
  ),
  (
    'bade-mantili',
    '{"sr": "Bade mantili", "en": "Bathrobes", "ru": "Халаты"}',
    '{"sr": "Bade mantili - širok asortiman", "en": "Bathrobes - wide range", "ru": "Халаты - широкий ассортимент"}',
    '{"sr": "Bade mantili | Vondi", "en": "Bathrobes | Vondi", "ru": "Халаты | Vondi"}',
    '{"sr": "Pronađite najbolje Bade mantili na Vondi marketplace", "en": "Find the best Bathrobes on Vondi marketplace", "ru": "Найдите лучшие Халаты на Vondi marketplace"}',
    (SELECT id FROM categories WHERE slug = 'odeca-i-obuca' AND level = 1),
    2,
    'odeca-i-obuca/bade-mantili',
    304,
    '🛁',
    true
  ),
  (
    'negl ize-i-spavacice',
    '{"sr": "Negliže i spavaćice", "en": "Negligees and Nightgowns", "ru": "Неглиже и ночные рубашки"}',
    '{"sr": "Negliže i spavaćice - širok asortiman", "en": "Negligees and Nightgowns - wide range", "ru": "Неглиже и ночные рубашки - широкий ассортимент"}',
    '{"sr": "Negliže i spavaćice | Vondi", "en": "Negligees and Nightgowns | Vondi", "ru": "Неглиже и ночные рубашки | Vondi"}',
    '{"sr": "Pronađite najbolje Negliže i spavaćice na Vondi marketplace", "en": "Find the best Negligees and Nightgowns on Vondi marketplace", "ru": "Найдите лучшие Неглиже и ночные рубашки на Vondi marketplace"}',
    (SELECT id FROM categories WHERE slug = 'odeca-i-obuca' AND level = 1),
    2,
    'odeca-i-obuca/negl ize-i-spavacice',
    305,
    '😴',
    true
  ),
  (
    'odeca-trudnice-svecana',
    '{"sr": "Svečana odeća za trudnice", "en": "Formal Maternity Wear", "ru": "Вечерняя одежда для беременных"}',
    '{"sr": "Svečana odeća za trudnice - širok asortiman", "en": "Formal Maternity Wear - wide range", "ru": "Вечерняя одежда для беременных - широкий ассортимент"}',
    '{"sr": "Svečana odeća za trudnice | Vondi", "en": "Formal Maternity Wear | Vondi", "ru": "Вечерняя одежда для беременных | Vondi"}',
    '{"sr": "Pronađite najbolje Svečana odeća za trudnice na Vondi marketplace", "en": "Find the best Formal Maternity Wear on Vondi marketplace", "ru": "Найдите лучшие Вечерняя одежда для беременных на Vondi marketplace"}',
    (SELECT id FROM categories WHERE slug = 'odeca-i-obuca' AND level = 1),
    2,
    'odeca-i-obuca/odeca-trudnice-svecana',
    306,
    '🤰',
    true
  ),
  (
    'muske-velike-velicine',
    '{"sr": "Muške velike veličine", "en": "Mens Plus Size", "ru": "Мужские большие размеры"}',
    '{"sr": "Muške velike veličine - širok asortiman", "en": "Mens Plus Size - wide range", "ru": "Мужские большие размеры - широкий ассортимент"}',
    '{"sr": "Muške velike veličine | Vondi", "en": "Mens Plus Size | Vondi", "ru": "Мужские большие размеры | Vondi"}',
    '{"sr": "Pronađite najbolje Muške velike veličine na Vondi marketplace", "en": "Find the best Mens Plus Size on Vondi marketplace", "ru": "Найдите лучшие Мужские большие размеры на Vondi marketplace"}',
    (SELECT id FROM categories WHERE slug = 'odeca-i-obuca' AND level = 1),
    2,
    'odeca-i-obuca/muske-velike-velicine',
    307,
    '👔',
    true
  ),
  (
    'zenske-velike-velicine',
    '{"sr": "Ženske velike veličine", "en": "Womens Plus Size", "ru": "Женские большие размеры"}',
    '{"sr": "Ženske velike veličine - širok asortiman", "en": "Womens Plus Size - wide range", "ru": "Женские большие размеры - широкий ассортимент"}',
    '{"sr": "Ženske velike veličine | Vondi", "en": "Womens Plus Size | Vondi", "ru": "Женские большие размеры | Vondi"}',
    '{"sr": "Pronađite najbolje Ženske velike veličine na Vondi marketplace", "en": "Find the best Womens Plus Size on Vondi marketplace", "ru": "Найдите лучшие Женские большие размеры на Vondi marketplace"}',
    (SELECT id FROM categories WHERE slug = 'odeca-i-obuca' AND level = 1),
    2,
    'odeca-i-obuca/zenske-velike-velicine',
    308,
    '👗',
    true
  ),
  (
    'termo-ves',
    '{"sr": "Termo veš", "en": "Thermal Underwear", "ru": "Термобелье"}',
    '{"sr": "Termo veš - širok asortiman", "en": "Thermal Underwear - wide range", "ru": "Термобелье - широкий ассортимент"}',
    '{"sr": "Termo veš | Vondi", "en": "Thermal Underwear | Vondi", "ru": "Термобелье | Vondi"}',
    '{"sr": "Pronađite najbolje Termo veš na Vondi marketplace", "en": "Find the best Thermal Underwear on Vondi marketplace", "ru": "Найдите лучшие Термобелье на Vondi marketplace"}',
    (SELECT id FROM categories WHERE slug = 'odeca-i-obuca' AND level = 1),
    2,
    'odeca-i-obuca/termo-ves',
    309,
    '🥶',
    true
  ),
  (
    'odeca-ronjenje',
    '{"sr": "Odeća za ronjenje", "en": "Diving Wear", "ru": "Одежда для дайвинга"}',
    '{"sr": "Odeća za ronjenje - širok asortiman", "en": "Diving Wear - wide range", "ru": "Одежда для дайвинга - широкий ассортимент"}',
    '{"sr": "Odeća za ronjenje | Vondi", "en": "Diving Wear | Vondi", "ru": "Одежда для дайвинга | Vondi"}',
    '{"sr": "Pronađite najbolje Odeća za ronjenje na Vondi marketplace", "en": "Find the best Diving Wear on Vondi marketplace", "ru": "Найдите лучшие Одежда для дайвинга на Vondi marketplace"}',
    (SELECT id FROM categories WHERE slug = 'odeca-i-obuca' AND level = 1),
    2,
    'odeca-i-obuca/odeca-ronjenje',
    310,
    '🤿',
    true
  ),
  (
    'kuhinjski-set-nozeva',
    '{"sr": "Kuhinjski set noževa", "en": "Kitchen Knife Sets", "ru": "Кухонные наборы ножей"}',
    '{"sr": "Kuhinjski set noževa - širok asortiman", "en": "Kitchen Knife Sets - wide range", "ru": "Кухонные наборы ножей - широкий ассортимент"}',
    '{"sr": "Kuhinjski set noževa | Vondi", "en": "Kitchen Knife Sets | Vondi", "ru": "Кухонные наборы ножей | Vondi"}',
    '{"sr": "Pronađite najbolje Kuhinjski set noževa na Vondi marketplace", "en": "Find the best Kitchen Knife Sets on Vondi marketplace", "ru": "Найдите лучшие Кухонные наборы ножей на Vondi marketplace"}',
    (SELECT id FROM categories WHERE slug = 'dom-i-basta' AND level = 1),
    2,
    'dom-i-basta/kuhinjski-set-nozeva',
    311,
    '🔪',
    true
  ),
  (
    'drveno-posude-kuhinja',
    '{"sr": "Drveno posuđe za kuhinju", "en": "Wooden Kitchenware", "ru": "Деревянная посуда"}',
    '{"sr": "Drveno posuđe za kuhinju - širok asortiman", "en": "Wooden Kitchenware - wide range", "ru": "Деревянная посуда - широкий ассортимент"}',
    '{"sr": "Drveno posuđe za kuhinju | Vondi", "en": "Wooden Kitchenware | Vondi", "ru": "Деревянная посуда | Vondi"}',
    '{"sr": "Pronađite najbolje Drveno posuđe za kuhinju na Vondi marketplace", "en": "Find the best Wooden Kitchenware on Vondi marketplace", "ru": "Найдите лучшие Деревянная посуда на Vondi marketplace"}',
    (SELECT id FROM categories WHERE slug = 'dom-i-basta' AND level = 1),
    2,
    'dom-i-basta/drveno-posude-kuhinja',
    312,
    '🥄',
    true
  ),
  (
    'keramika-posude-rucno',
    '{"sr": "Keramičko posuđe ručno rađeno", "en": "Handmade Ceramic Dishes", "ru": "Керамическая посуда ручной работы"}',
    '{"sr": "Keramičko posuđe ručno rađeno - širok asortiman", "en": "Handmade Ceramic Dishes - wide range", "ru": "Керамическая посуда ручной работы - широкий ассортимент"}',
    '{"sr": "Keramičko posuđe ručno rađeno | Vondi", "en": "Handmade Ceramic Dishes | Vondi", "ru": "Керамическая посуда ручной работы | Vondi"}',
    '{"sr": "Pronađite najbolje Keramičko posuđe ručno rađeno na Vondi marketplace", "en": "Find the best Handmade Ceramic Dishes on Vondi marketplace", "ru": "Найдите лучшие Керамическая посуда ручной работы на Vondi marketplace"}',
    (SELECT id FROM categories WHERE slug = 'dom-i-basta' AND level = 1),
    2,
    'dom-i-basta/keramika-posude-rucno',
    313,
    '🏺',
    true
  ),
  (
    'staklo-kristal-posude',
    '{"sr": "Staklo i kristal posuđe", "en": "Glass and Crystal Dishes", "ru": "Стеклянная и хрустальная посуда"}',
    '{"sr": "Staklo i kristal posuđe - širok asortiman", "en": "Glass and Crystal Dishes - wide range", "ru": "Стеклянная и хрустальная посуда - широкий ассортимент"}',
    '{"sr": "Staklo i kristal posuđe | Vondi", "en": "Glass and Crystal Dishes | Vondi", "ru": "Стеклянная и хрустальная посуда | Vondi"}',
    '{"sr": "Pronađite najbolje Staklo i kristal posuđe na Vondi marketplace", "en": "Find the best Glass and Crystal Dishes on Vondi marketplace", "ru": "Найдите лучшие Стеклянная и хрустальная посуда на Vondi marketplace"}',
    (SELECT id FROM categories WHERE slug = 'dom-i-basta' AND level = 1),
    2,
    'dom-i-basta/staklo-kristal-posude',
    314,
    '🍷',
    true
  ),
  (
    'tacne-posluzavnici',
    '{"sr": "Tacne i poslužavnici", "en": "Trays and Serving Platters", "ru": "Подносы и сервировочные блюда"}',
    '{"sr": "Tacne i poslužavnici - širok asortiman", "en": "Trays and Serving Platters - wide range", "ru": "Подносы и сервировочные блюда - широкий ассортимент"}',
    '{"sr": "Tacne i poslužavnici | Vondi", "en": "Trays and Serving Platters | Vondi", "ru": "Подносы и сервировочные блюда | Vondi"}',
    '{"sr": "Pronađite najbolje Tacne i poslužavnici na Vondi marketplace", "en": "Find the best Trays and Serving Platters on Vondi marketplace", "ru": "Найдите лучшие Подносы и сервировочные блюда на Vondi marketplace"}',
    (SELECT id FROM categories WHERE slug = 'dom-i-basta' AND level = 1),
    2,
    'dom-i-basta/tacne-posluzavnici',
    315,
    '🍽️',
    true
  ),
  (
    'kozarci-case-luksuz',
    '{"sr": "Kozarci i čaše luksuzni", "en": "Luxury Glasses", "ru": "Роскошные бокалы"}',
    '{"sr": "Kozarci i čaše luksuzni - širok asortiman", "en": "Luxury Glasses - wide range", "ru": "Роскошные бокалы - широкий ассортимент"}',
    '{"sr": "Kozarci i čaše luksuzni | Vondi", "en": "Luxury Glasses | Vondi", "ru": "Роскошные бокалы | Vondi"}',
    '{"sr": "Pronađite najbolje Kozarci i čaše luksuzni na Vondi marketplace", "en": "Find the best Luxury Glasses on Vondi marketplace", "ru": "Найдите лучшие Роскошные бокалы на Vondi marketplace"}',
    (SELECT id FROM categories WHERE slug = 'dom-i-basta' AND level = 1),
    2,
    'dom-i-basta/kozarci-case-luksuz',
    316,
    '🥂',
    true
  ),
  (
    'kafe-servisi',
    '{"sr": "Servisi za kafu", "en": "Coffee Sets", "ru": "Кофейные сервизы"}',
    '{"sr": "Servisi za kafu - širok asortiman", "en": "Coffee Sets - wide range", "ru": "Кофейные сервизы - широкий ассортимент"}',
    '{"sr": "Servisi za kafu | Vondi", "en": "Coffee Sets | Vondi", "ru": "Кофейные сервизы | Vondi"}',
    '{"sr": "Pronađite najbolje Servisi za kafu na Vondi marketplace", "en": "Find the best Coffee Sets on Vondi marketplace", "ru": "Найдите лучшие Кофейные сервизы на Vondi marketplace"}',
    (SELECT id FROM categories WHERE slug = 'dom-i-basta' AND level = 1),
    2,
    'dom-i-basta/kafe-servisi',
    317,
    '☕',
    true
  ),
  (
    'caj-servisi',
    '{"sr": "Servisi za čaj", "en": "Tea Sets", "ru": "Чайные сервизы"}',
    '{"sr": "Servisi za čaj - širok asortiman", "en": "Tea Sets - wide range", "ru": "Чайные сервизы - широкий ассортимент"}',
    '{"sr": "Servisi za čaj | Vondi", "en": "Tea Sets | Vondi", "ru": "Чайные сервизы | Vondi"}',
    '{"sr": "Pronađite najbolje Servisi za čaj na Vondi marketplace", "en": "Find the best Tea Sets on Vondi marketplace", "ru": "Найдите лучшие Чайные сервизы на Vondi marketplace"}',
    (SELECT id FROM categories WHERE slug = 'dom-i-basta' AND level = 1),
    2,
    'dom-i-basta/caj-servisi',
    318,
    '🍵',
    true
  ),
  (
    'zamrzivaci-vertikalni',
    '{"sr": "Zamrzivači vertikalni", "en": "Upright Freezers", "ru": "Вертикальные морозильники"}',
    '{"sr": "Zamrzivači vertikalni - širok asortiman", "en": "Upright Freezers - wide range", "ru": "Вертикальные морозильники - широкий ассортимент"}',
    '{"sr": "Zamrzivači vertikalni | Vondi", "en": "Upright Freezers | Vondi", "ru": "Вертикальные морозильники | Vondi"}',
    '{"sr": "Pronađite najbolje Zamrzivači vertikalni na Vondi marketplace", "en": "Find the best Upright Freezers on Vondi marketplace", "ru": "Найдите лучшие Вертикальные морозильники на Vondi marketplace"}',
    (SELECT id FROM categories WHERE slug = 'dom-i-basta' AND level = 1),
    2,
    'dom-i-basta/zamrzivaci-vertikalni',
    319,
    '🧊',
    true
  ),
  (
    'vinske-vitrine',
    '{"sr": "Vinske vitrine", "en": "Wine Coolers", "ru": "Винные холодильники"}',
    '{"sr": "Vinske vitrine - širok asortiman", "en": "Wine Coolers - wide range", "ru": "Винные холодильники - широкий ассортимент"}',
    '{"sr": "Vinske vitrine | Vondi", "en": "Wine Coolers | Vondi", "ru": "Винные холодильники | Vondi"}',
    '{"sr": "Pronađite najbolje Vinske vitrine na Vondi marketplace", "en": "Find the best Wine Coolers on Vondi marketplace", "ru": "Найдите лучшие Винные холодильники на Vondi marketplace"}',
    (SELECT id FROM categories WHERE slug = 'dom-i-basta' AND level = 1),
    2,
    'dom-i-basta/vinske-vitrine',
    320,
    '🍷',
    true
  ),
  (
    'bar-oprema-dom',
    '{"sr": "Bar oprema za dom", "en": "Home Bar Equipment", "ru": "Барное оборудование для дома"}',
    '{"sr": "Bar oprema za dom - širok asortiman", "en": "Home Bar Equipment - wide range", "ru": "Барное оборудование для дома - широкий ассортимент"}',
    '{"sr": "Bar oprema za dom | Vondi", "en": "Home Bar Equipment | Vondi", "ru": "Барное оборудование для дома | Vondi"}',
    '{"sr": "Pronađite najbolje Bar oprema za dom na Vondi marketplace", "en": "Find the best Home Bar Equipment on Vondi marketplace", "ru": "Найдите лучшие Барное оборудование для дома на Vondi marketplace"}',
    (SELECT id FROM categories WHERE slug = 'dom-i-basta' AND level = 1),
    2,
    'dom-i-basta/bar-oprema-dom',
    321,
    '🍸',
    true
  ),
  (
    'joga-blokovi',
    '{"sr": "Joga blokovi", "en": "Yoga Blocks", "ru": "Блоки для йоги"}',
    '{"sr": "Joga blokovi - širok asortiman", "en": "Yoga Blocks - wide range", "ru": "Блоки для йоги - широкий ассортимент"}',
    '{"sr": "Joga blokovi | Vondi", "en": "Yoga Blocks | Vondi", "ru": "Блоки для йоги | Vondi"}',
    '{"sr": "Pronađite najbolje Joga blokovi na Vondi marketplace", "en": "Find the best Yoga Blocks on Vondi marketplace", "ru": "Найдите лучшие Блоки для йоги на Vondi marketplace"}',
    (SELECT id FROM categories WHERE slug = 'sport-i-turizam' AND level = 1),
    2,
    'sport-i-turizam/joga-blokovi',
    322,
    '🧘',
    true
  ),
  (
    'pilates-lopte',
    '{"sr": "Pilates lopte", "en": "Pilates Balls", "ru": "Мячи для пилатеса"}',
    '{"sr": "Pilates lopte - širok asortiman", "en": "Pilates Balls - wide range", "ru": "Мячи для пилатеса - широкий ассортимент"}',
    '{"sr": "Pilates lopte | Vondi", "en": "Pilates Balls | Vondi", "ru": "Мячи для пилатеса | Vondi"}',
    '{"sr": "Pronađite najbolje Pilates lopte na Vondi marketplace", "en": "Find the best Pilates Balls on Vondi marketplace", "ru": "Найдите лучшие Мячи для пилатеса на Vondi marketplace"}',
    (SELECT id FROM categories WHERE slug = 'sport-i-turizam' AND level = 1),
    2,
    'sport-i-turizam/pilates-lopte',
    323,
    '⚽',
    true
  ),
  (
    'trake-istezanje',
    '{"sr": "Trake za istezanje", "en": "Resistance Bands", "ru": "Эластичные ленты"}',
    '{"sr": "Trake za istezanje - širok asortiman", "en": "Resistance Bands - wide range", "ru": "Эластичные ленты - широкий ассортимент"}',
    '{"sr": "Trake za istezanje | Vondi", "en": "Resistance Bands | Vondi", "ru": "Эластичные ленты | Vondi"}',
    '{"sr": "Pronađite najbolje Trake za istezanje na Vondi marketplace", "en": "Find the best Resistance Bands on Vondi marketplace", "ru": "Найдите лучшие Эластичные ленты на Vondi marketplace"}',
    (SELECT id FROM categories WHERE slug = 'sport-i-turizam' AND level = 1),
    2,
    'sport-i-turizam/trake-istezanje',
    324,
    '🏋️',
    true
  ),
  (
    'tenis-reketi-pro',
    '{"sr": "Tenis reketi profesionalni", "en": "Professional Tennis Rackets", "ru": "Профессиональные теннисные ракетки"}',
    '{"sr": "Tenis reketi profesionalni - širok asortiman", "en": "Professional Tennis Rackets - wide range", "ru": "Профессиональные теннисные ракетки - широкий ассортимент"}',
    '{"sr": "Tenis reketi profesionalni | Vondi", "en": "Professional Tennis Rackets | Vondi", "ru": "Профессиональные теннисные ракетки | Vondi"}',
    '{"sr": "Pronađite najbolje Tenis reketi profesionalni na Vondi marketplace", "en": "Find the best Professional Tennis Rackets on Vondi marketplace", "ru": "Найдите лучшие Профессиональные теннисные ракетки на Vondi marketplace"}',
    (SELECT id FROM categories WHERE slug = 'sport-i-turizam' AND level = 1),
    2,
    'sport-i-turizam/tenis-reketi-pro',
    325,
    '🎾',
    true
  ),
  (
    'badminton-oprema',
    '{"sr": "Badminton oprema", "en": "Badminton Equipment", "ru": "Оборудование для бадминтона"}',
    '{"sr": "Badminton oprema - širok asortiman", "en": "Badminton Equipment - wide range", "ru": "Оборудование для бадминтона - широкий ассортимент"}',
    '{"sr": "Badminton oprema | Vondi", "en": "Badminton Equipment | Vondi", "ru": "Оборудование для бадминтона | Vondi"}',
    '{"sr": "Pronađite najbolje Badminton oprema na Vondi marketplace", "en": "Find the best Badminton Equipment on Vondi marketplace", "ru": "Найдите лучшие Оборудование для бадминтона на Vondi marketplace"}',
    (SELECT id FROM categories WHERE slug = 'sport-i-turizam' AND level = 1),
    2,
    'sport-i-turizam/badminton-oprema',
    326,
    '🏸',
    true
  ),
  (
    'stoni-tenis-reketi',
    '{"sr": "Stoni tenis reketi", "en": "Table Tennis Rackets", "ru": "Ракетки для настольного тенниса"}',
    '{"sr": "Stoni tenis reketi - širok asortiman", "en": "Table Tennis Rackets - wide range", "ru": "Ракетки для настольного тенниса - широкий ассортимент"}',
    '{"sr": "Stoni tenis reketi | Vondi", "en": "Table Tennis Rackets | Vondi", "ru": "Ракетки для настольного тенниса | Vondi"}',
    '{"sr": "Pronađite najbolje Stoni tenis reketi na Vondi marketplace", "en": "Find the best Table Tennis Rackets on Vondi marketplace", "ru": "Найдите лучшие Ракетки для настольного тенниса на Vondi marketplace"}',
    (SELECT id FROM categories WHERE slug = 'sport-i-turizam' AND level = 1),
    2,
    'sport-i-turizam/stoni-tenis-reketi',
    327,
    '🏓',
    true
  ),
  (
    'borilacke-vestine-zastita',
    '{"sr": "Borilačke veštine zaštita", "en": "Martial Arts Protective Gear", "ru": "Защита для боевых искусств"}',
    '{"sr": "Borilačke veštine zaštita - širok asortiman", "en": "Martial Arts Protective Gear - wide range", "ru": "Защита для боевых искусств - широкий ассортимент"}',
    '{"sr": "Borilačke veštine zaštita | Vondi", "en": "Martial Arts Protective Gear | Vondi", "ru": "Защита для боевых искусств | Vondi"}',
    '{"sr": "Pronađite najbolje Borilačke veštine zaštita na Vondi marketplace", "en": "Find the best Martial Arts Protective Gear on Vondi marketplace", "ru": "Найдите лучшие Защита для боевых искусств на Vondi marketplace"}',
    (SELECT id FROM categories WHERE slug = 'sport-i-turizam' AND level = 1),
    2,
    'sport-i-turizam/borilacke-vestine-zastita',
    328,
    '🥋',
    true
  ),
  (
    'ronilacka-oprema-profesionalna',
    '{"sr": "Ronilačka oprema profesionalna", "en": "Professional Diving Equipment", "ru": "Профессиональное оборудование для дайвинга"}',
    '{"sr": "Ronilačka oprema profesionalna - širok asortiman", "en": "Professional Diving Equipment - wide range", "ru": "Профессиональное оборудование для дайвинга - широкий ассортимент"}',
    '{"sr": "Ronilačka oprema profesionalna | Vondi", "en": "Professional Diving Equipment | Vondi", "ru": "Профессиональное оборудование для дайвинга | Vondi"}',
    '{"sr": "Pronađite najbolje Ronilačka oprema profesionalna na Vondi marketplace", "en": "Find the best Professional Diving Equipment on Vondi marketplace", "ru": "Найдите лучшие Профессиональное оборудование для дайвинга на Vondi marketplace"}',
    (SELECT id FROM categories WHERE slug = 'sport-i-turizam' AND level = 1),
    2,
    'sport-i-turizam/ronilacka-oprema-profesionalna',
    329,
    '🤿',
    true
  ),
  (
    'surfovanje-daske',
    '{"sr": "Surfovanje daske", "en": "Surfboards", "ru": "Доски для серфинга"}',
    '{"sr": "Surfovanje daske - širok asortiman", "en": "Surfboards - wide range", "ru": "Доски для серфинга - широкий ассортимент"}',
    '{"sr": "Surfovanje daske | Vondi", "en": "Surfboards | Vondi", "ru": "Доски для серфинга | Vondi"}',
    '{"sr": "Pronađite najbolje Surfovanje daske na Vondi marketplace", "en": "Find the best Surfboards on Vondi marketplace", "ru": "Найдите лучшие Доски для серфинга на Vondi marketplace"}',
    (SELECT id FROM categories WHERE slug = 'sport-i-turizam' AND level = 1),
    2,
    'sport-i-turizam/surfovanje-daske',
    330,
    '🏄',
    true
  ),
  (
    'kajak-kanu-oprema',
    '{"sr": "Kajak i kanu oprema", "en": "Kayak and Canoe Equipment", "ru": "Оборудование для каяка и каноэ"}',
    '{"sr": "Kajak i kanu oprema - širok asortiman", "en": "Kayak and Canoe Equipment - wide range", "ru": "Оборудование для каяка и каноэ - широкий ассортимент"}',
    '{"sr": "Kajak i kanu oprema | Vondi", "en": "Kayak and Canoe Equipment | Vondi", "ru": "Оборудование для каяка и каноэ | Vondi"}',
    '{"sr": "Pronađite najbolje Kajak i kanu oprema na Vondi marketplace", "en": "Find the best Kayak and Canoe Equipment on Vondi marketplace", "ru": "Найдите лучшие Оборудование для каяка и каноэ на Vondi marketplace"}',
    (SELECT id FROM categories WHERE slug = 'sport-i-turizam' AND level = 1),
    2,
    'sport-i-turizam/kajak-kanu-oprema',
    331,
    '🛶',
    true
  ),
  (
    'auto-sedista-bebe',
    '{"sr": "Auto sedišta za bebe", "en": "Baby Car Seats", "ru": "Детские автокресла"}',
    '{"sr": "Auto sedišta za bebe - širok asortiman", "en": "Baby Car Seats - wide range", "ru": "Детские автокресла - широкий ассортимент"}',
    '{"sr": "Auto sedišta za bebe | Vondi", "en": "Baby Car Seats | Vondi", "ru": "Детские автокресла | Vondi"}',
    '{"sr": "Pronađite najbolje Auto sedišta za bebe na Vondi marketplace", "en": "Find the best Baby Car Seats on Vondi marketplace", "ru": "Найдите лучшие Детские автокресла на Vondi marketplace"}',
    (SELECT id FROM categories WHERE slug = 'automobilizam' AND level = 1),
    2,
    'automobilizam/auto-sedista-bebe',
    332,
    '👶',
    true
  ),
  (
    'auto-organizatori',
    '{"sr": "Auto organizatori", "en": "Car Organizers", "ru": "Автомобильные органайзеры"}',
    '{"sr": "Auto organizatori - širok asortiman", "en": "Car Organizers - wide range", "ru": "Автомобильные органайзеры - широкий ассортимент"}',
    '{"sr": "Auto organizatori | Vondi", "en": "Car Organizers | Vondi", "ru": "Автомобильные органайзеры | Vondi"}',
    '{"sr": "Pronađite najbolje Auto organizatori na Vondi marketplace", "en": "Find the best Car Organizers on Vondi marketplace", "ru": "Найдите лучшие Автомобильные органайзеры на Vondi marketplace"}',
    (SELECT id FROM categories WHERE slug = 'automobilizam' AND level = 1),
    2,
    'automobilizam/auto-organizatori',
    333,
    '📦',
    true
  ),
  (
    'ambijentalno-osvetljenje',
    '{"sr": "Ambijentalno osvetljenje", "en": "Ambient Lighting", "ru": "Ambient освещение"}',
    '{"sr": "Ambijentalno osvetljenje - širok asortiman", "en": "Ambient Lighting - wide range", "ru": "Ambient освещение - широкий ассортимент"}',
    '{"sr": "Ambijentalno osvetljenje | Vondi", "en": "Ambient Lighting | Vondi", "ru": "Ambient освещение | Vondi"}',
    '{"sr": "Pronađite najbolje Ambijentalno osvetljenje na Vondi marketplace", "en": "Find the best Ambient Lighting on Vondi marketplace", "ru": "Найдите лучшие Ambient освещение на Vondi marketplace"}',
    (SELECT id FROM categories WHERE slug = 'automobilizam' AND level = 1),
    2,
    'automobilizam/ambijentalno-osvetljenje',
    334,
    '💡',
    true
  ),
  (
    'drzaci-telefona-auto',
    '{"sr": "Držači telefona za auto", "en": "Car Phone Holders", "ru": "Держатели телефонов для авто"}',
    '{"sr": "Držači telefona za auto - širok asortiman", "en": "Car Phone Holders - wide range", "ru": "Держатели телефонов для авто - широкий ассортимент"}',
    '{"sr": "Držači telefona za auto | Vondi", "en": "Car Phone Holders | Vondi", "ru": "Держатели телефонов для авто | Vondi"}',
    '{"sr": "Pronađite najbolje Držači telefona za auto na Vondi marketplace", "en": "Find the best Car Phone Holders on Vondi marketplace", "ru": "Найдите лучшие Держатели телефонов для авто на Vondi marketplace"}',
    (SELECT id FROM categories WHERE slug = 'automobilizam' AND level = 1),
    2,
    'automobilizam/drzaci-telefona-auto',
    335,
    '📱',
    true
  ),
  (
    'auto-pokrivaci',
    '{"sr": "Auto pokrivači", "en": "Car Covers", "ru": "Автомобильные чехлы"}',
    '{"sr": "Auto pokrivači - širok asortiman", "en": "Car Covers - wide range", "ru": "Автомобильные чехлы - широкий ассортимент"}',
    '{"sr": "Auto pokrivači | Vondi", "en": "Car Covers | Vondi", "ru": "Автомобильные чехлы | Vondi"}',
    '{"sr": "Pronađite najbolje Auto pokrivači na Vondi marketplace", "en": "Find the best Car Covers on Vondi marketplace", "ru": "Найдите лучшие Автомобильные чехлы на Vondi marketplace"}',
    (SELECT id FROM categories WHERE slug = 'automobilizam' AND level = 1),
    2,
    'automobilizam/auto-pokrivaci',
    336,
    '🚗',
    true
  ),
  (
    'klime-uređaji-prenosni',
    '{"sr": "Klima uređaji prenosni", "en": "Portable Air Conditioners", "ru": "Портативные кондиционеры"}',
    '{"sr": "Klima uređaji prenosni - širok asortiman", "en": "Portable Air Conditioners - wide range", "ru": "Портативные кондиционеры - широкий ассортимент"}',
    '{"sr": "Klima uređaji prenosni | Vondi", "en": "Portable Air Conditioners | Vondi", "ru": "Портативные кондиционеры | Vondi"}',
    '{"sr": "Pronađite najbolje Klima uređaji prenosni na Vondi marketplace", "en": "Find the best Portable Air Conditioners on Vondi marketplace", "ru": "Найдите лучшие Портативные кондиционеры на Vondi marketplace"}',
    (SELECT id FROM categories WHERE slug = 'automobilizam' AND level = 1),
    2,
    'automobilizam/klime-uređaji-prenosni',
    337,
    '❄️',
    true
  ),
  (
    'gps-trekeri-auto',
    '{"sr": "GPS trekeri za auto", "en": "GPS Trackers for Cars", "ru": "GPS трекеры для авто"}',
    '{"sr": "GPS trekeri za auto - širok asortiman", "en": "GPS Trackers for Cars - wide range", "ru": "GPS трекеры для авто - широкий ассортимент"}',
    '{"sr": "GPS trekeri za auto | Vondi", "en": "GPS Trackers for Cars | Vondi", "ru": "GPS трекеры для авто | Vondi"}',
    '{"sr": "Pronađite najbolje GPS trekeri za auto na Vondi marketplace", "en": "Find the best GPS Trackers for Cars on Vondi marketplace", "ru": "Найдите лучшие GPS трекеры для авто на Vondi marketplace"}',
    (SELECT id FROM categories WHERE slug = 'automobilizam' AND level = 1),
    2,
    'automobilizam/gps-trekeri-auto',
    338,
    '📍',
    true
  ),
  (
    'punjaci-elektricni-auto',
    '{"sr": "Punjači za električne auto", "en": "EV Chargers", "ru": "Зарядки для электромобилей"}',
    '{"sr": "Punjači za električne auto - širok asortiman", "en": "EV Chargers - wide range", "ru": "Зарядки для электромобилей - широкий ассортимент"}',
    '{"sr": "Punjači za električne auto | Vondi", "en": "EV Chargers | Vondi", "ru": "Зарядки для электромобилей | Vondi"}',
    '{"sr": "Pronađite najbolje Punjači za električne auto na Vondi marketplace", "en": "Find the best EV Chargers on Vondi marketplace", "ru": "Найдите лучшие Зарядки для электромобилей на Vondi marketplace"}',
    (SELECT id FROM categories WHERE slug = 'automobilizam' AND level = 1),
    2,
    'automobilizam/punjaci-elektricni-auto',
    339,
    '🔌',
    true
  ),
  (
    'auto-aspiratori',
    '{"sr": "Auto aspiratori", "en": "Car Vacuum Cleaners", "ru": "Автомобильные пылесосы"}',
    '{"sr": "Auto aspiratori - širok asortiman", "en": "Car Vacuum Cleaners - wide range", "ru": "Автомобильные пылесосы - широкий ассортимент"}',
    '{"sr": "Auto aspiratori | Vondi", "en": "Car Vacuum Cleaners | Vondi", "ru": "Автомобильные пылесосы | Vondi"}',
    '{"sr": "Pronađite najbolje Auto aspiratori na Vondi marketplace", "en": "Find the best Car Vacuum Cleaners on Vondi marketplace", "ru": "Найдите лучшие Автомобильные пылесосы на Vondi marketplace"}',
    (SELECT id FROM categories WHERE slug = 'automobilizam' AND level = 1),
    2,
    'automobilizam/auto-aspiratori',
    340,
    '💨',
    true
  ),
  (
    'led-trake-auto',
    '{"sr": "LED trake za auto", "en": "LED Strips for Cars", "ru": "LED ленты для авто"}',
    '{"sr": "LED trake za auto - širok asortiman", "en": "LED Strips for Cars - wide range", "ru": "LED ленты для авто - широкий ассортимент"}',
    '{"sr": "LED trake za auto | Vondi", "en": "LED Strips for Cars | Vondi", "ru": "LED ленты для авто | Vondi"}',
    '{"sr": "Pronađite najbolje LED trake za auto na Vondi marketplace", "en": "Find the best LED Strips for Cars on Vondi marketplace", "ru": "Найдите лучшие LED ленты для авто на Vondi marketplace"}',
    (SELECT id FROM categories WHERE slug = 'automobilizam' AND level = 1),
    2,
    'automobilizam/led-trake-auto',
    341,
    '💡',
    true
  ),
  (
    'indukcionе-ploce',
    '{"sr": "Indukcione ploče", "en": "Induction Cooktops", "ru": "Индукционные плиты"}',
    '{"sr": "Indukcione ploče - širok asortiman", "en": "Induction Cooktops - wide range", "ru": "Индукционные плиты - широкий ассортимент"}',
    '{"sr": "Indukcione ploče | Vondi", "en": "Induction Cooktops | Vondi", "ru": "Индукционные плиты | Vondi"}',
    '{"sr": "Pronađite najbolje Indukcione ploče na Vondi marketplace", "en": "Find the best Induction Cooktops on Vondi marketplace", "ru": "Найдите лучшие Индукционные плиты на Vondi marketplace"}',
    (SELECT id FROM categories WHERE slug = 'kucni-aparati' AND level = 1),
    2,
    'kucni-aparati/indukcionе-ploce',
    342,
    '🔥',
    true
  ),
  (
    'parne-rerne',
    '{"sr": "Parne rerne", "en": "Steam Ovens", "ru": "Паровые духовки"}',
    '{"sr": "Parne rerne - širok asortiman", "en": "Steam Ovens - wide range", "ru": "Паровые духовки - широкий ассортимент"}',
    '{"sr": "Parne rerne | Vondi", "en": "Steam Ovens | Vondi", "ru": "Паровые духовки | Vondi"}',
    '{"sr": "Pronađite najbolje Parne rerne na Vondi marketplace", "en": "Find the best Steam Ovens on Vondi marketplace", "ru": "Найдите лучшие Паровые духовки на Vondi marketplace"}',
    (SELECT id FROM categories WHERE slug = 'kucni-aparati' AND level = 1),
    2,
    'kucni-aparati/parne-rerne',
    343,
    '♨️',
    true
  ),
  (
    'aspiratori-bez-kesice',
    '{"sr": "Aspiratori bez kesice", "en": "Bagless Vacuum Cleaners", "ru": "Пылесосы без мешков"}',
    '{"sr": "Aspiratori bez kesice - širok asortiman", "en": "Bagless Vacuum Cleaners - wide range", "ru": "Пылесосы без мешков - широкий ассортимент"}',
    '{"sr": "Aspiratori bez kesice | Vondi", "en": "Bagless Vacuum Cleaners | Vondi", "ru": "Пылесосы без мешков | Vondi"}',
    '{"sr": "Pronađite najbolje Aspiratori bez kesice na Vondi marketplace", "en": "Find the best Bagless Vacuum Cleaners on Vondi marketplace", "ru": "Найдите лучшие Пылесосы без мешков на Vondi marketplace"}',
    (SELECT id FROM categories WHERE slug = 'kucni-aparati' AND level = 1),
    2,
    'kucni-aparati/aspiratori-bez-kesice',
    344,
    '🌪️',
    true
  ),
  (
    'roboti-usisivaci',
    '{"sr": "Roboti usisivači", "en": "Robot Vacuum Cleaners", "ru": "Роботы-пылесосы"}',
    '{"sr": "Roboti usisivači - širok asortiman", "en": "Robot Vacuum Cleaners - wide range", "ru": "Роботы-пылесосы - широкий ассортимент"}',
    '{"sr": "Roboti usisivači | Vondi", "en": "Robot Vacuum Cleaners | Vondi", "ru": "Роботы-пылесосы | Vondi"}',
    '{"sr": "Pronađite najbolje Roboti usisivači na Vondi marketplace", "en": "Find the best Robot Vacuum Cleaners on Vondi marketplace", "ru": "Найдите лучшие Роботы-пылесосы на Vondi marketplace"}',
    (SELECT id FROM categories WHERE slug = 'kucni-aparati' AND level = 1),
    2,
    'kucni-aparati/roboti-usisivaci',
    345,
    '🤖',
    true
  ),
  (
    'masine-pranje-susenje',
    '{"sr": "Mašine za pranje i sušenje", "en": "Washer-Dryer Combos", "ru": "Стирально-сушильные машины"}',
    '{"sr": "Mašine za pranje i sušenje - širok asortiman", "en": "Washer-Dryer Combos - wide range", "ru": "Стирально-сушильные машины - широкий ассортимент"}',
    '{"sr": "Mašine za pranje i sušenje | Vondi", "en": "Washer-Dryer Combos | Vondi", "ru": "Стирально-сушильные машины | Vondi"}',
    '{"sr": "Pronađite najbolje Mašine za pranje i sušenje na Vondi marketplace", "en": "Find the best Washer-Dryer Combos on Vondi marketplace", "ru": "Найдите лучшие Стирально-сушильные машины на Vondi marketplace"}',
    (SELECT id FROM categories WHERE slug = 'kucni-aparati' AND level = 1),
    2,
    'kucni-aparati/masine-pranje-susenje',
    346,
    '🧺',
    true
  ),
  (
    'masine-sudjе',
    '{"sr": "Mašine za suđe", "en": "Dishwashers", "ru": "Посудомоечные машины"}',
    '{"sr": "Mašine za suđe - širok asortiman", "en": "Dishwashers - wide range", "ru": "Посудомоечные машины - широкий ассортимент"}',
    '{"sr": "Mašine za suđe | Vondi", "en": "Dishwashers | Vondi", "ru": "Посудомоечные машины | Vondi"}',
    '{"sr": "Pronađite najbolje Mašine za suđe na Vondi marketplace", "en": "Find the best Dishwashers on Vondi marketplace", "ru": "Найдите лучшие Посудомоечные машины на Vondi marketplace"}',
    (SELECT id FROM categories WHERE slug = 'kucni-aparati' AND level = 1),
    2,
    'kucni-aparati/masine-sudjе',
    347,
    '🍽️',
    true
  ),
  (
    'friteze-sa-vrucim-vazduhom',
    '{"sr": "Friteze sa vrućim vazduhom", "en": "Air Fryers", "ru": "Аэрофритюрницы"}',
    '{"sr": "Friteze sa vrućim vazduhom - širok asortiman", "en": "Air Fryers - wide range", "ru": "Аэрофритюрницы - широкий ассортимент"}',
    '{"sr": "Friteze sa vrućim vazduhom | Vondi", "en": "Air Fryers | Vondi", "ru": "Аэрофритюрницы | Vondi"}',
    '{"sr": "Pronađite najbolje Friteze sa vrućim vazduhom na Vondi marketplace", "en": "Find the best Air Fryers on Vondi marketplace", "ru": "Найдите лучшие Аэрофритюрницы на Vondi marketplace"}',
    (SELECT id FROM categories WHERE slug = 'kucni-aparati' AND level = 1),
    2,
    'kucni-aparati/friteze-sa-vrucim-vazduhom',
    348,
    '🍟',
    true
  ),
  (
    'instant-lonci',
    '{"sr": "Instant lonci", "en": "Instant Pots", "ru": "Мультиварки Instant Pot"}',
    '{"sr": "Instant lonci - širok asortiman", "en": "Instant Pots - wide range", "ru": "Мультиварки Instant Pot - широкий ассортимент"}',
    '{"sr": "Instant lonci | Vondi", "en": "Instant Pots | Vondi", "ru": "Мультиварки Instant Pot | Vondi"}',
    '{"sr": "Pronađite najbolje Instant lonci na Vondi marketplace", "en": "Find the best Instant Pots on Vondi marketplace", "ru": "Найдите лучшие Мультиварки Instant Pot на Vondi marketplace"}',
    (SELECT id FROM categories WHERE slug = 'kucni-aparati' AND level = 1),
    2,
    'kucni-aparati/instant-lonci',
    349,
    '🍲',
    true
  ),
  (
    'multi-kukeri',
    '{"sr": "Multi kukeri", "en": "Multi-Cookers", "ru": "Мультиварки"}',
    '{"sr": "Multi kukeri - širok asortiman", "en": "Multi-Cookers - wide range", "ru": "Мультиварки - широкий ассортимент"}',
    '{"sr": "Multi kukeri | Vondi", "en": "Multi-Cookers | Vondi", "ru": "Мультиварки | Vondi"}',
    '{"sr": "Pronađite najbolje Multi kukeri na Vondi marketplace", "en": "Find the best Multi-Cookers on Vondi marketplace", "ru": "Найдите лучшие Мультиварки на Vondi marketplace"}',
    (SELECT id FROM categories WHERE slug = 'kucni-aparati' AND level = 1),
    2,
    'kucni-aparati/multi-kukeri',
    350,
    '👨‍🍳',
    true
  ),
  (
    'blenderi-profesionalni',
    '{"sr": "Blenderi profesionalni", "en": "Professional Blenders", "ru": "Профессиональные блендеры"}',
    '{"sr": "Blenderi profesionalni - širok asortiman", "en": "Professional Blenders - wide range", "ru": "Профессиональные блендеры - широкий ассортимент"}',
    '{"sr": "Blenderi profesionalni | Vondi", "en": "Professional Blenders | Vondi", "ru": "Профессиональные блендеры | Vondi"}',
    '{"sr": "Pronađite najbolje Blenderi profesionalni na Vondi marketplace", "en": "Find the best Professional Blenders on Vondi marketplace", "ru": "Найдите лучшие Профессиональные блендеры на Vondi marketplace"}',
    (SELECT id FROM categories WHERE slug = 'kucni-aparati' AND level = 1),
    2,
    'kucni-aparati/blenderi-profesionalni',
    351,
    '🥤',
    true
  ),
  (
    'led-maske-lice',
    '{"sr": "LED maske za lice", "en": "LED Face Masks", "ru": "LED маски для лица"}',
    '{"sr": "LED maske za lice - širok asortiman", "en": "LED Face Masks - wide range", "ru": "LED маски для лица - широкий ассортимент"}',
    '{"sr": "LED maske za lice | Vondi", "en": "LED Face Masks | Vondi", "ru": "LED маски для лица | Vondi"}',
    '{"sr": "Pronađite najbolje LED maske za lice na Vondi marketplace", "en": "Find the best LED Face Masks on Vondi marketplace", "ru": "Найдите лучшие LED маски для лица на Vondi marketplace"}',
    (SELECT id FROM categories WHERE slug = 'lepota-i-zdravlje' AND level = 1),
    2,
    'lepota-i-zdravlje/led-maske-lice',
    352,
    '💡',
    true
  ),
  (
    'dermaroller-mikronedling',
    '{"sr": "Dermaroller mikroneedling", "en": "Dermaroller Microneedling", "ru": "Дермароллер микронидлинг"}',
    '{"sr": "Dermaroller mikroneedling - širok asortiman", "en": "Dermaroller Microneedling - wide range", "ru": "Дермароллер микронидлинг - широкий ассортимент"}',
    '{"sr": "Dermaroller mikroneedling | Vondi", "en": "Dermaroller Microneedling | Vondi", "ru": "Дермароллер микронидлинг | Vondi"}',
    '{"sr": "Pronađite najbolje Dermaroller mikroneedling na Vondi marketplace", "en": "Find the best Dermaroller Microneedling on Vondi marketplace", "ru": "Найдите лучшие Дермароллер микронидлинг на Vondi marketplace"}',
    (SELECT id FROM categories WHERE slug = 'lepota-i-zdravlje' AND level = 1),
    2,
    'lepota-i-zdravlje/dermaroller-mikronedling',
    353,
    '💉',
    true
  ),
  (
    'ultrazvucni-cistaci',
    '{"sr": "Ultrazvučni čistači", "en": "Ultrasonic Cleansers", "ru": "Ультразвуковые очистители"}',
    '{"sr": "Ultrazvučni čistači - širok asortiman", "en": "Ultrasonic Cleansers - wide range", "ru": "Ультразвуковые очистители - широкий ассортимент"}',
    '{"sr": "Ultrazvučni čistači | Vondi", "en": "Ultrasonic Cleansers | Vondi", "ru": "Ультразвуковые очистители | Vondi"}',
    '{"sr": "Pronađite najbolje Ultrazvučni čistači na Vondi marketplace", "en": "Find the best Ultrasonic Cleansers on Vondi marketplace", "ru": "Найдите лучшие Ультразвуковые очистители на Vondi marketplace"}',
    (SELECT id FROM categories WHERE slug = 'lepota-i-zdravlje' AND level = 1),
    2,
    'lepota-i-zdravlje/ultrazvucni-cistaci',
    354,
    '🔊',
    true
  ),
  (
    'ionske-cetkice-kosa',
    '{"sr": "Jonske četkice za kosu", "en": "Ionic Hair Brushes", "ru": "Ионные щетки для волос"}',
    '{"sr": "Jonske četkice za kosu - širok asortiman", "en": "Ionic Hair Brushes - wide range", "ru": "Ионные щетки для волос - широкий ассортимент"}',
    '{"sr": "Jonske četkice za kosu | Vondi", "en": "Ionic Hair Brushes | Vondi", "ru": "Ионные щетки для волос | Vondi"}',
    '{"sr": "Pronađite najbolje Jonske četkice za kosu na Vondi marketplace", "en": "Find the best Ionic Hair Brushes on Vondi marketplace", "ru": "Найдите лучшие Ионные щетки для волос на Vondi marketplace"}',
    (SELECT id FROM categories WHERE slug = 'lepota-i-zdravlje' AND level = 1),
    2,
    'lepota-i-zdravlje/ionske-cetkice-kosa',
    355,
    '💇',
    true
  ),
  (
    'laseri-uklanjanje-dlaka',
    '{"sr": "Laseri za uklanjanje dlaka", "en": "Laser Hair Removal", "ru": "Лазеры для удаления волос"}',
    '{"sr": "Laseri za uklanjanje dlaka - širok asortiman", "en": "Laser Hair Removal - wide range", "ru": "Лазеры для удаления волос - широкий ассортимент"}',
    '{"sr": "Laseri za uklanjanje dlaka | Vondi", "en": "Laser Hair Removal | Vondi", "ru": "Лазеры для удаления волос | Vondi"}',
    '{"sr": "Pronađite najbolje Laseri za uklanjanje dlaka na Vondi marketplace", "en": "Find the best Laser Hair Removal on Vondi marketplace", "ru": "Найдите лучшие Лазеры для удаления волос на Vondi marketplace"}',
    (SELECT id FROM categories WHERE slug = 'lepota-i-zdravlje' AND level = 1),
    2,
    'lepota-i-zdravlje/laseri-uklanjanje-dlaka',
    356,
    '✨',
    true
  ),
  (
    'fene-profesionalni',
    '{"sr": "Fēnovi profesionalni", "en": "Professional Hair Dryers", "ru": "Профессиональные фены"}',
    '{"sr": "Fēnovi profesionalni - širok asortiman", "en": "Professional Hair Dryers - wide range", "ru": "Профессиональные фены - широкий ассортимент"}',
    '{"sr": "Fēnovi profesionalni | Vondi", "en": "Professional Hair Dryers | Vondi", "ru": "Профессиональные фены | Vondi"}',
    '{"sr": "Pronađite najbolje Fēnovi profesionalni na Vondi marketplace", "en": "Find the best Professional Hair Dryers on Vondi marketplace", "ru": "Найдите лучшие Профессиональные фены на Vondi marketplace"}',
    (SELECT id FROM categories WHERE slug = 'lepota-i-zdravlje' AND level = 1),
    2,
    'lepota-i-zdravlje/fene-profesionalni',
    357,
    '💨',
    true
  ),
  (
    'pegla-kosa-turmalin',
    '{"sr": "Pegle za kosu turmalin", "en": "Tourmaline Hair Straighteners", "ru": "Турмалиновые утюжки для волос"}',
    '{"sr": "Pegle za kosu turmalin - širok asortiman", "en": "Tourmaline Hair Straighteners - wide range", "ru": "Турмалиновые утюжки для волос - широкий ассортимент"}',
    '{"sr": "Pegle za kosu turmalin | Vondi", "en": "Tourmaline Hair Straighteners | Vondi", "ru": "Турмалиновые утюжки для волос | Vondi"}',
    '{"sr": "Pronađite najbolje Pegle za kosu turmalin na Vondi marketplace", "en": "Find the best Tourmaline Hair Straighteners on Vondi marketplace", "ru": "Найдите лучшие Турмалиновые утюжки для волос на Vondi marketplace"}',
    (SELECT id FROM categories WHERE slug = 'lepota-i-zdravlje' AND level = 1),
    2,
    'lepota-i-zdravlje/pegla-kosa-turmalin',
    358,
    '🦱',
    true
  ),
  (
    'biotin-kompleksi',
    '{"sr": "Biotin kompleksi", "en": "Biotin Complexes", "ru": "Биотиновые комплексы"}',
    '{"sr": "Biotin kompleksi - širok asortiman", "en": "Biotin Complexes - wide range", "ru": "Биотиновые комплексы - широкий ассортимент"}',
    '{"sr": "Biotin kompleksi | Vondi", "en": "Biotin Complexes | Vondi", "ru": "Биотиновые комплексы | Vondi"}',
    '{"sr": "Pronađite najbolje Biotin kompleksi na Vondi marketplace", "en": "Find the best Biotin Complexes on Vondi marketplace", "ru": "Найдите лучшие Биотиновые комплексы на Vondi marketplace"}',
    (SELECT id FROM categories WHERE slug = 'lepota-i-zdravlje' AND level = 1),
    2,
    'lepota-i-zdravlje/biotin-kompleksi',
    359,
    '💊',
    true
  ),
  (
    'kolagen-preparati',
    '{"sr": "Kolagen preparati", "en": "Collagen Supplements", "ru": "Коллагеновые добавки"}',
    '{"sr": "Kolagen preparati - širok asortiman", "en": "Collagen Supplements - wide range", "ru": "Коллагеновые добавки - широкий ассортимент"}',
    '{"sr": "Kolagen preparati | Vondi", "en": "Collagen Supplements | Vondi", "ru": "Коллагеновые добавки | Vondi"}',
    '{"sr": "Pronađite najbolje Kolagen preparati na Vondi marketplace", "en": "Find the best Collagen Supplements on Vondi marketplace", "ru": "Найдите лучшие Коллагеновые добавки на Vondi marketplace"}',
    (SELECT id FROM categories WHERE slug = 'lepota-i-zdravlje' AND level = 1),
    2,
    'lepota-i-zdravlje/kolagen-preparati',
    360,
    '✨',
    true
  ),
  (
    'terapije-svetlom',
    '{"sr": "Terapije svetlom", "en": "Light Therapy", "ru": "Светотерапия"}',
    '{"sr": "Terapije svetlom - širok asortiman", "en": "Light Therapy - wide range", "ru": "Светотерапия - широкий ассортимент"}',
    '{"sr": "Terapije svetlom | Vondi", "en": "Light Therapy | Vondi", "ru": "Светотерапия | Vondi"}',
    '{"sr": "Pronađite najbolje Terapije svetlom na Vondi marketplace", "en": "Find the best Light Therapy on Vondi marketplace", "ru": "Найдите лучшие Светотерапия на Vondi marketplace"}',
    (SELECT id FROM categories WHERE slug = 'lepota-i-zdravlje' AND level = 1),
    2,
    'lepota-i-zdravlje/terapije-svetlom',
    361,
    '💡',
    true
  ),
  (
    'bebi-monitori-video',
    '{"sr": "Bebi monitori video", "en": "Video Baby Monitors", "ru": "Видеоняни"}',
    '{"sr": "Bebi monitori video - širok asortiman", "en": "Video Baby Monitors - wide range", "ru": "Видеоняни - широкий ассортимент"}',
    '{"sr": "Bebi monitori video | Vondi", "en": "Video Baby Monitors | Vondi", "ru": "Видеоняни | Vondi"}',
    '{"sr": "Pronađite najbolje Bebi monitori video na Vondi marketplace", "en": "Find the best Video Baby Monitors on Vondi marketplace", "ru": "Найдите лучшие Видеоняни на Vondi marketplace"}',
    (SELECT id FROM categories WHERE slug = 'za-bebe-i-decu' AND level = 1),
    2,
    'za-bebe-i-decu/bebi-monitori-video',
    362,
    '📹',
    true
  ),
  (
    'nosiljke-ergonomske',
    '{"sr": "Nosiljke ergonomske", "en": "Ergonomic Baby Carriers", "ru": "Эргономичные переноски"}',
    '{"sr": "Nosiljke ergonomske - širok asortiman", "en": "Ergonomic Baby Carriers - wide range", "ru": "Эргономичные переноски - широкий ассортимент"}',
    '{"sr": "Nosiljke ergonomske | Vondi", "en": "Ergonomic Baby Carriers | Vondi", "ru": "Эргономичные переноски | Vondi"}',
    '{"sr": "Pronađite najbolje Nosiljke ergonomske na Vondi marketplace", "en": "Find the best Ergonomic Baby Carriers on Vondi marketplace", "ru": "Найдите лучшие Эргономичные переноски на Vondi marketplace"}',
    (SELECT id FROM categories WHERE slug = 'za-bebe-i-decu' AND level = 1),
    2,
    'za-bebe-i-decu/nosiljke-ergonomske',
    363,
    '👶',
    true
  ),
  (
    'kolevke-automatske',
    '{"sr": "Kolevke automatske", "en": "Automatic Cradles", "ru": "Автоматические колыбели"}',
    '{"sr": "Kolevke automatske - širok asortiman", "en": "Automatic Cradles - wide range", "ru": "Автоматические колыбели - широкий ассортимент"}',
    '{"sr": "Kolevke automatske | Vondi", "en": "Automatic Cradles | Vondi", "ru": "Автоматические колыбели | Vondi"}',
    '{"sr": "Pronađite najbolje Kolevke automatske na Vondi marketplace", "en": "Find the best Automatic Cradles on Vondi marketplace", "ru": "Найдите лучшие Автоматические колыбели на Vondi marketplace"}',
    (SELECT id FROM categories WHERE slug = 'za-bebe-i-decu' AND level = 1),
    2,
    'za-bebe-i-decu/kolevke-automatske',
    364,
    '😴',
    true
  ),
  (
    'sterilizatori',
    '{"sr": "Sterilizatori", "en": "Sterilizers", "ru": "Стерилизаторы"}',
    '{"sr": "Sterilizatori - širok asortiman", "en": "Sterilizers - wide range", "ru": "Стерилизаторы - широкий ассортимент"}',
    '{"sr": "Sterilizatori | Vondi", "en": "Sterilizers | Vondi", "ru": "Стерилизаторы | Vondi"}',
    '{"sr": "Pronađite najbolje Sterilizatori na Vondi marketplace", "en": "Find the best Sterilizers on Vondi marketplace", "ru": "Найдите лучшие Стерилизаторы на Vondi marketplace"}',
    (SELECT id FROM categories WHERE slug = 'za-bebe-i-decu' AND level = 1),
    2,
    'za-bebe-i-decu/sterilizatori',
    365,
    '🧼',
    true
  ),
  (
    'grejaci-flasica',
    '{"sr": "Grejači flašica", "en": "Bottle Warmers", "ru": "Подогреватели бутылочек"}',
    '{"sr": "Grejači flašica - širok asortiman", "en": "Bottle Warmers - wide range", "ru": "Подогреватели бутылочек - широкий ассортимент"}',
    '{"sr": "Grejači flašica | Vondi", "en": "Bottle Warmers | Vondi", "ru": "Подогреватели бутылочек | Vondi"}',
    '{"sr": "Pronađite najbolje Grejači flašica na Vondi marketplace", "en": "Find the best Bottle Warmers on Vondi marketplace", "ru": "Найдите лучшие Подогреватели бутылочек на Vondi marketplace"}',
    (SELECT id FROM categories WHERE slug = 'za-bebe-i-decu' AND level = 1),
    2,
    'za-bebe-i-decu/grejaci-flasica',
    366,
    '🍼',
    true
  ),
  (
    'kada-bebe-sklop ljiva',
    '{"sr": "Kade za bebe sklopljive", "en": "Foldable Baby Bathtubs", "ru": "Складные детские ванночки"}',
    '{"sr": "Kade za bebe sklopljive - širok asortiman", "en": "Foldable Baby Bathtubs - wide range", "ru": "Складные детские ванночки - широкий ассортимент"}',
    '{"sr": "Kade za bebe sklopljive | Vondi", "en": "Foldable Baby Bathtubs | Vondi", "ru": "Складные детские ванночки | Vondi"}',
    '{"sr": "Pronađite najbolje Kade za bebe sklopljive na Vondi marketplace", "en": "Find the best Foldable Baby Bathtubs on Vondi marketplace", "ru": "Найдите лучшие Складные детские ванночки на Vondi marketplace"}',
    (SELECT id FROM categories WHERE slug = 'za-bebe-i-decu' AND level = 1),
    2,
    'za-bebe-i-decu/kada-bebe-sklop ljiva',
    367,
    '🛁',
    true
  ),
  (
    'nocnici',
    '{"sr": "Noćnici", "en": "Potty Chairs", "ru": "Детские горшки"}',
    '{"sr": "Noćnici - širok asortiman", "en": "Potty Chairs - wide range", "ru": "Детские горшки - широкий ассортимент"}',
    '{"sr": "Noćnici | Vondi", "en": "Potty Chairs | Vondi", "ru": "Детские горшки | Vondi"}',
    '{"sr": "Pronađite najbolje Noćnici na Vondi marketplace", "en": "Find the best Potty Chairs on Vondi marketplace", "ru": "Найдите лучшие Детские горшки на Vondi marketplace"}',
    (SELECT id FROM categories WHERE slug = 'za-bebe-i-decu' AND level = 1),
    2,
    'za-bebe-i-decu/nocnici',
    368,
    '🚽',
    true
  ),
  (
    'zaštitne-ograde',
    '{"sr": "Zaštitne ograde", "en": "Safety Gates", "ru": "Защитные ограждения"}',
    '{"sr": "Zaštitne ograde - širok asortiman", "en": "Safety Gates - wide range", "ru": "Защитные ограждения - широкий ассортимент"}',
    '{"sr": "Zaštitne ograde | Vondi", "en": "Safety Gates | Vondi", "ru": "Защитные ограждения | Vondi"}',
    '{"sr": "Pronađite najbolje Zaštitne ograde na Vondi marketplace", "en": "Find the best Safety Gates on Vondi marketplace", "ru": "Найдите лучшие Защитные ограждения на Vondi marketplace"}',
    (SELECT id FROM categories WHERE slug = 'za-bebe-i-decu' AND level = 1),
    2,
    'za-bebe-i-decu/zaštitne-ograde',
    369,
    '🚪',
    true
  ),
  (
    'bebi-jumperoo',
    '{"sr": "Bebi jumperoo", "en": "Baby Jumpers", "ru": "Детские прыгунки"}',
    '{"sr": "Bebi jumperoo - širok asortiman", "en": "Baby Jumpers - wide range", "ru": "Детские прыгунки - широкий ассортимент"}',
    '{"sr": "Bebi jumperoo | Vondi", "en": "Baby Jumpers | Vondi", "ru": "Детские прыгунки | Vondi"}',
    '{"sr": "Pronađite najbolje Bebi jumperoo na Vondi marketplace", "en": "Find the best Baby Jumpers on Vondi marketplace", "ru": "Найдите лучшие Детские прыгунки на Vondi marketplace"}',
    (SELECT id FROM categories WHERE slug = 'za-bebe-i-decu' AND level = 1),
    2,
    'za-bebe-i-decu/bebi-jumperoo',
    370,
    '🦘',
    true
  ),
  (
    'edukativni-tepisi',
    '{"sr": "Edukativni tepisi", "en": "Educational Play Mats", "ru": "Развивающие коврики"}',
    '{"sr": "Edukativni tepisi - širok asortiman", "en": "Educational Play Mats - wide range", "ru": "Развивающие коврики - широкий ассортимент"}',
    '{"sr": "Edukativni tepisi | Vondi", "en": "Educational Play Mats | Vondi", "ru": "Развивающие коврики | Vondi"}',
    '{"sr": "Pronađite najbolje Edukativni tepisi na Vondi marketplace", "en": "Find the best Educational Play Mats on Vondi marketplace", "ru": "Найдите лучшие Развивающие коврики на Vondi marketplace"}',
    (SELECT id FROM categories WHERE slug = 'za-bebe-i-decu' AND level = 1),
    2,
    'za-bebe-i-decu/edukativni-tepisi',
    371,
    '🧸',
    true
  ),
  (
    'prstenje-veridba-dijamant',
    '{"sr": "Prstenje za veridbu dijamant", "en": "Diamond Engagement Rings", "ru": "Помолвочные кольца с бриллиантами"}',
    '{"sr": "Prstenje za veridbu dijamant - širok asortiman", "en": "Diamond Engagement Rings - wide range", "ru": "Помолвочные кольца с бриллиантами - широкий ассортимент"}',
    '{"sr": "Prstenje za veridbu dijamant | Vondi", "en": "Diamond Engagement Rings | Vondi", "ru": "Помолвочные кольца с бриллиантами | Vondi"}',
    '{"sr": "Pronađite najbolje Prstenje za veridbu dijamant na Vondi marketplace", "en": "Find the best Diamond Engagement Rings on Vondi marketplace", "ru": "Найдите лучшие Помолвочные кольца с бриллиантами на Vondi marketplace"}',
    (SELECT id FROM categories WHERE slug = 'nakit-i-satovi' AND level = 1),
    2,
    'nakit-i-satovi/prstenje-veridba-dijamant',
    372,
    '💍',
    true
  ),
  (
    'luksuzni-satovi-swiss',
    '{"sr": "Luksuzni satovi švajcarski", "en": "Swiss Luxury Watches", "ru": "Швейцарские люкс часы"}',
    '{"sr": "Luksuzni satovi švajcarski - širok asortiman", "en": "Swiss Luxury Watches - wide range", "ru": "Швейцарские люкс часы - широкий ассортимент"}',
    '{"sr": "Luksuzni satovi švajcarski | Vondi", "en": "Swiss Luxury Watches | Vondi", "ru": "Швейцарские люкс часы | Vondi"}',
    '{"sr": "Pronađite najbolje Luksuzni satovi švajcarski na Vondi marketplace", "en": "Find the best Swiss Luxury Watches on Vondi marketplace", "ru": "Найдите лучшие Швейцарские люкс часы на Vondi marketplace"}',
    (SELECT id FROM categories WHERE slug = 'nakit-i-satovi' AND level = 1),
    2,
    'nakit-i-satovi/luksuzni-satovi-swiss',
    373,
    '⌚',
    true
  ),
  (
    'pametni-satovi-fitness',
    '{"sr": "Pametni satovi fitness", "en": "Fitness Smartwatches", "ru": "Фитнес-часы"}',
    '{"sr": "Pametni satovi fitness - širok asortiman", "en": "Fitness Smartwatches - wide range", "ru": "Фитнес-часы - широкий ассортимент"}',
    '{"sr": "Pametni satovi fitness | Vondi", "en": "Fitness Smartwatches | Vondi", "ru": "Фитнес-часы | Vondi"}',
    '{"sr": "Pronađite najbolje Pametni satovi fitness na Vondi marketplace", "en": "Find the best Fitness Smartwatches on Vondi marketplace", "ru": "Найдите лучшие Фитнес-часы на Vondi marketplace"}',
    (SELECT id FROM categories WHERE slug = 'nakit-i-satovi' AND level = 1),
    2,
    'nakit-i-satovi/pametni-satovi-fitness',
    374,
    '⌚',
    true
  ),
  (
    'perlice-narukvice',
    '{"sr": "Perlice narukvice", "en": "Pearl Bracelets", "ru": "Жемчужные браслеты"}',
    '{"sr": "Perlice narukvice - širok asortiman", "en": "Pearl Bracelets - wide range", "ru": "Жемчужные браслеты - широкий ассортимент"}',
    '{"sr": "Perlice narukvice | Vondi", "en": "Pearl Bracelets | Vondi", "ru": "Жемчужные браслеты | Vondi"}',
    '{"sr": "Pronađite najbolje Perlice narukvice na Vondi marketplace", "en": "Find the best Pearl Bracelets on Vondi marketplace", "ru": "Найдите лучшие Жемчужные браслеты на Vondi marketplace"}',
    (SELECT id FROM categories WHERE slug = 'nakit-i-satovi' AND level = 1),
    2,
    'nakit-i-satovi/perlice-narukvice',
    375,
    '📿',
    true
  ),
  (
    'zlatne-ogrlice',
    '{"sr": "Zlatne ogrlice", "en": "Gold Necklaces", "ru": "Золотые ожерелья"}',
    '{"sr": "Zlatne ogrlice - širok asortiman", "en": "Gold Necklaces - wide range", "ru": "Золотые ожерелья - широкий ассортимент"}',
    '{"sr": "Zlatne ogrlice | Vondi", "en": "Gold Necklaces | Vondi", "ru": "Золотые ожерелья | Vondi"}',
    '{"sr": "Pronađite najbolje Zlatne ogrlice na Vondi marketplace", "en": "Find the best Gold Necklaces on Vondi marketplace", "ru": "Найдите лучшие Золотые ожерелья на Vondi marketplace"}',
    (SELECT id FROM categories WHERE slug = 'nakit-i-satovi' AND level = 1),
    2,
    'nakit-i-satovi/zlatne-ogrlice',
    376,
    '✨',
    true
  ),
  (
    'srebrne-minđuše',
    '{"sr": "Srebrne minđuše", "en": "Silver Earrings", "ru": "Серебряные серьги"}',
    '{"sr": "Srebrne minđuše - širok asortiman", "en": "Silver Earrings - wide range", "ru": "Серебряные серьги - широкий ассортимент"}',
    '{"sr": "Srebrne minđuše | Vondi", "en": "Silver Earrings | Vondi", "ru": "Серебряные серьги | Vondi"}',
    '{"sr": "Pronađite najbolje Srebrne minđuše na Vondi marketplace", "en": "Find the best Silver Earrings on Vondi marketplace", "ru": "Найдите лучшие Серебряные серьги на Vondi marketplace"}',
    (SELECT id FROM categories WHERE slug = 'nakit-i-satovi' AND level = 1),
    2,
    'nakit-i-satovi/srebrne-minđuše',
    377,
    '💎',
    true
  ),
  (
    'broše-vintage',
    '{"sr": "Broševi vintage", "en": "Vintage Brooches", "ru": "Винтажные броши"}',
    '{"sr": "Broševi vintage - širok asortiman", "en": "Vintage Brooches - wide range", "ru": "Винтажные броши - широкий ассортимент"}',
    '{"sr": "Broševi vintage | Vondi", "en": "Vintage Brooches | Vondi", "ru": "Винтажные броши | Vondi"}',
    '{"sr": "Pronađite najbolje Broševi vintage na Vondi marketplace", "en": "Find the best Vintage Brooches on Vondi marketplace", "ru": "Найдите лучшие Винтажные броши на Vondi marketplace"}',
    (SELECT id FROM categories WHERE slug = 'nakit-i-satovi' AND level = 1),
    2,
    'nakit-i-satovi/broše-vintage',
    378,
    '🌹',
    true
  ),
  (
    'privesci-lanci',
    '{"sr": "Privesci i lanci", "en": "Pendants and Chains", "ru": "Кулоны и цепочки"}',
    '{"sr": "Privesci i lanci - širok asortiman", "en": "Pendants and Chains - wide range", "ru": "Кулоны и цепочки - широкий ассортимент"}',
    '{"sr": "Privesci i lanci | Vondi", "en": "Pendants and Chains | Vondi", "ru": "Кулоны и цепочки | Vondi"}',
    '{"sr": "Pronađite najbolje Privesci i lanci na Vondi marketplace", "en": "Find the best Pendants and Chains on Vondi marketplace", "ru": "Найдите лучшие Кулоны и цепочки на Vondi marketplace"}',
    (SELECT id FROM categories WHERE slug = 'nakit-i-satovi' AND level = 1),
    2,
    'nakit-i-satovi/privesci-lanci',
    379,
    '⛓️',
    true
  ),
  (
    'autobiografije',
    '{"sr": "Autobiografije", "en": "Autobiographies", "ru": "Автобиографии"}',
    '{"sr": "Autobiografije - širok asortiman", "en": "Autobiographies - wide range", "ru": "Автобиографии - широкий ассортимент"}',
    '{"sr": "Autobiografije | Vondi", "en": "Autobiographies | Vondi", "ru": "Автобиографии | Vondi"}',
    '{"sr": "Pronađite najbolje Autobiografije na Vondi marketplace", "en": "Find the best Autobiographies on Vondi marketplace", "ru": "Найдите лучшие Автобиографии на Vondi marketplace"}',
    (SELECT id FROM categories WHERE slug = 'knjige-i-mediji' AND level = 1),
    2,
    'knjige-i-mediji/autobiografije',
    380,
    '📚',
    true
  ),
  (
    'kuvari-recepti',
    '{"sr": "Kuvari i recepti", "en": "Cookbooks and Recipes", "ru": "Кулинарные книги"}',
    '{"sr": "Kuvari i recepti - širok asortiman", "en": "Cookbooks and Recipes - wide range", "ru": "Кулинарные книги - широкий ассортимент"}',
    '{"sr": "Kuvari i recepti | Vondi", "en": "Cookbooks and Recipes | Vondi", "ru": "Кулинарные книги | Vondi"}',
    '{"sr": "Pronađite najbolje Kuvari i recepti na Vondi marketplace", "en": "Find the best Cookbooks and Recipes on Vondi marketplace", "ru": "Найдите лучшие Кулинарные книги на Vondi marketplace"}',
    (SELECT id FROM categories WHERE slug = 'knjige-i-mediji' AND level = 1),
    2,
    'knjige-i-mediji/kuvari-recepti',
    381,
    '👨‍🍳',
    true
  )
;

-- Verification: проверка на дубликаты
DO $$
DECLARE
  duplicate_count INT;
BEGIN
  SELECT COUNT(*) INTO duplicate_count FROM (
    SELECT slug, COUNT(*) FROM categories GROUP BY slug HAVING COUNT(*) > 1
  ) dup;
  IF duplicate_count > 0 THEN
    RAISE EXCEPTION 'Found % duplicate slugs!', duplicate_count;
  END IF;
  RAISE NOTICE 'No duplicates found ✅';
  RAISE NOTICE 'Successfully added new L2 categories';
END $$;