-- Rollback: L3 Odeca i Obuca Categories

DELETE FROM categories WHERE slug IN (
  -- Muska odeca (12)
  'muski-dzemperi',
  'muski-duksevi',
  'muska-sportska-odeca',
  'muske-trenerke',
  'muski-sorcevi',
  'muski-kaputi',
  'muski-prsluci',
  'muska-odela',
  'muski-smokingzi',
  'muske-kravate',
  'muski-kaisevi',
  'muski-salovi',

  -- Zenska odeca (11)
  'zenske-pantalone-jeans',
  'zenske-pantalone-elegantne',
  'zenski-dzemperi',
  'zenski-duksevi',
  'zenska-sportska-odeca',
  'zenske-trenerke',
  'zenski-sorcevi',
  'zenski-kaputi',
  'zenske-mantile',
  'zenska-vecernja-garderoba',
  'zenska-poslovna-garderoba',

  -- Decija odeca (15)
  'bebe-odeca-0-3-meseca',
  'bebe-odeca-3-6-meseci',
  'bebe-odeca-6-12-meseci',
  'decaci-odeca-1-3-godine',
  'decaci-odeca-4-7-godina',
  'decaci-odeca-8-12-godina',
  'devojcice-odeca-1-3-godine',
  'devojcice-odeca-4-7-godina',
  'devojcice-odeca-8-12-godina',
  'decije-jakne',
  'deciji-duksevi',
  'decije-trenerke',
  'decije-kaputi',
  'skolska-uniforma',
  'svecana-decija-odeca',

  -- Muska obuca (15)
  'muske-patike-casual',
  'muske-patike-running',
  'muske-patike-basketball',
  'muske-patike-football',
  'muske-cipele-koza',
  'muske-cipele-oxford',
  'muske-cipele-derby',
  'muske-cizme-duboke',
  'muske-cizme-chelsea',
  'muske-cizme-radne',
  'muske-sandale',
  'muske-papuce',
  'muske-mokasine',
  'muske-espadrile',
  'muske-cipele-brodske',

  -- Zenska obuca (15)
  'zenske-patike-casual',
  'zenske-patike-running',
  'zenske-patike-fitness',
  'zenske-stikle',
  'zenske-cipele-potpetica',
  'zenske-balerinke',
  'zenske-mokasine',
  'zenske-cizme-duboke',
  'zenske-cizme-gleznjace',
  'zenske-cizme-preko-kolena',
  'zenske-sandale',
  'zenske-papuce',
  'zenske-espadrile',
  'zenske-cipele-platforme',
  'zenske-natikace',

  -- Decija obuca (15)
  'bebe-obuca-0-6-meseci',
  'bebe-obuca-6-12-meseci',
  'decija-obuca-prve-korake',
  'decije-patike-1-3-godine',
  'decije-patike-4-7-godina',
  'decije-patike-8-12-godina',
  'decije-sportske-patike',
  'decije-fudbalske-kopacke',
  'decije-cizme-gumene',
  'decije-cizme-zimske',
  'decije-cizme-duboke',
  'decije-sandale',
  'decije-papuce',
  'decije-cipele-skolske',
  'decije-baletanke',

  -- Kupaci kostimi (7)
  'muski-kupaci-sorcevi',
  'muski-kupaci-slip',
  'zenski-tankini',
  'zenski-monokini',
  'deciji-kupaci-kostimi',
  'kupaci-majice-uv-zastita',
  'pareo-tunike'
) AND level = 3;
