-- Rollback: L3 Dom i Sport Categories

DELETE FROM categories WHERE slug IN (
  -- Namestaj (15)
  'trosed-dvosed',
  'ugaona-garnitura',
  'fotelja',
  'tv-komoda',
  'sto-za-dnevnu-sobu',
  'bracni-krevet',
  'samacki-krevet',
  'sprat-krevet',
  'orman',
  'komode',
  'nocni-stocic',
  'trpezarijski-sto',
  'trpezarijske-stolice',
  'kancelarijski-sto',
  'kancelarijska-stolica',

  -- Kupatilo (12)
  'lavabo',
  'ugradni-lavabo',
  'kada',
  'hidromasazna-kada',
  'tus-kabina',
  'tus-set',
  'wc-solja',
  'bide',
  'slavina-za-lavabo',
  'slavina-za-kadu',
  'ogledalo-sa-ormarićem',
  'kupatilski-namestaj',

  -- Kuhinja (13)
  'kuhinjski-elementi',
  'kuhinjska-radna-ploca',
  'kuhinjska-sudopera',
  'kuhinjska-slavina',
  'aspirator',
  'stednjak',
  'ugradna-rerna',
  'ploca-za-kuvanje',
  'masina-za-pranje-sudova',
  'frizider',
  'zamrzivac',
  'mikrotalasna-rerna',
  'mini-bojler',

  -- Rasveta (10)
  'luster',
  'plafonjera',
  'ugradna-led-rasveta',
  'zidna-lampa',
  'stojeca-lampa',
  'stonalampa',
  'spoljna-rasveta',
  'led-sijalice',
  'pametna-rasveta',
  'dekorativna-rasveta',

  -- Fitnes oprema (10)
  'traka-za-trcanje',
  'bicikl-sobni',
  'elipticni-trenazer',
  'veslo-masina',
  'bucice',
  'sipka-i-tegovi',
  'klupa-za-vezbanje',
  'podloga-za-jogu',
  'lopta-za-pilates',
  'trx-trake',

  -- Bicikli (10)
  'brdski-bicikl',
  'drumski-bicikl',
  'gradski-bicikl',
  'elektricni-bicikl',
  'sklopivi-bicikl',
  'deciji-bicikl',
  'bmx-bicikl',
  'kaciga-za-bicikl',
  'biciklisticke-rukavice',
  'biciklisticka-torba',

  -- Kampovanje (10)
  'sator-2-3-osobe',
  'sator-4-6-osoba',
  'spavaca-vreca',
  'samoduvajuci-dusek',
  'kamp-ranac',
  'kamp-rostilj',
  'gas-reaud',
  'kamp-lampa',
  'prenosivi-frizider',
  'kamp-stolica'
) AND level = 3;
