-- Migration: Expand L2 categories (Part 7)
-- Date: 2025-12-17
-- Purpose: Add 60 L2 categories - Food, Art, Industry expansion
-- Expanding: Hrana i pice (22), Umetnost (15), Industrija (23)

-- =============================================================================
-- L2 for: Hrana i pice (22 new categories)
-- =============================================================================

INSERT INTO categories (slug, parent_id, level, path, sort_order, name, description, meta_title, meta_description, icon, is_active) VALUES

('organsko-voce', (SELECT id FROM categories WHERE slug = 'hrana-i-pice' AND level = 1), 2, 'hrana-i-pice/organsko-voce', 100,
 '{"sr": "Organsko voće", "en": "Organic fruits", "ru": "Органические фрукты"}'::jsonb,
 '{"sr": "Sertifikovano organsko voće, bez hemikalija", "en": "Certified organic fruits, chemical-free", "ru": "Сертифицированные органические фрукты, без химикатов"}'::jsonb,
 '{"sr": "Organsko voće | Vondi", "en": "Organic fruits | Vondi", "ru": "Органические фрукты | Vondi"}'::jsonb,
 '{"sr": "Kupite organsko voće online - zdrava ishrana", "en": "Buy organic fruits online", "ru": "Купить органические фрукты онлайн"}'::jsonb,
 '🍎', true),

('organsko-povrce', (SELECT id FROM categories WHERE slug = 'hrana-i-pice' AND level = 1), 2, 'hrana-i-pice/organsko-povrce', 101,
 '{"sr": "Organsko povrće", "en": "Organic vegetables", "ru": "Органические овощи"}'::jsonb,
 '{"sr": "Sertifikovano organsko povrće, bez pesticida", "en": "Certified organic vegetables, pesticide-free", "ru": "Сертифицированные органические овощи, без пестицидов"}'::jsonb,
 '{"sr": "Organsko povrće | Vondi", "en": "Organic vegetables | Vondi", "ru": "Органические овощи | Vondi"}'::jsonb,
 '{"sr": "Kupite organsko povrće - zdrava hrana", "en": "Buy organic vegetables online", "ru": "Купить органические овощи онлайн"}'::jsonb,
 '🥕', true),

('mlecni-proizvodi-organik', (SELECT id FROM categories WHERE slug = 'hrana-i-pice' AND level = 1), 2, 'hrana-i-pice/mlecni-proizvodi-organik', 102,
 '{"sr": "Organski mlečni proizvodi", "en": "Organic dairy products", "ru": "Органические молочные продукты"}'::jsonb,
 '{"sr": "Organski sir, mleko, jogurt, kajmak", "en": "Organic cheese, milk, yogurt, cream", "ru": "Органический сыр, молоко, йогурт, сливки"}'::jsonb,
 '{"sr": "Organski mlečni proizvodi | Vondi", "en": "Organic dairy | Vondi", "ru": "Органические молочные продукты | Vondi"}'::jsonb,
 '{"sr": "Kupite organske mlečne proizvode online", "en": "Buy organic dairy products online", "ru": "Купить органические молочные продукты онлайн"}'::jsonb,
 '🧀', true),

('veganska-hrana', (SELECT id FROM categories WHERE slug = 'hrana-i-pice' AND level = 1), 2, 'hrana-i-pice/veganska-hrana', 103,
 '{"sr": "Veganska hrana", "en": "Vegan food", "ru": "Веганская еда"}'::jsonb,
 '{"sr": "Biljni proteini, veganski sirevi, mleko, alternativi", "en": "Plant proteins, vegan cheese, milk alternatives", "ru": "Растительные белки, веганский сыр, альтернативы молоку"}'::jsonb,
 '{"sr": "Veganska hrana | Vondi", "en": "Vegan food | Vondi", "ru": "Веганская еда | Vondi"}'::jsonb,
 '{"sr": "Kupite vegansku hranu online - biljni proizvodi", "en": "Buy vegan food online", "ru": "Купить веганскую еду онлайн"}'::jsonb,
 '🌱', true),

('vegetarijanska-hrana', (SELECT id FROM categories WHERE slug = 'hrana-i-pice' AND level = 1), 2, 'hrana-i-pice/vegetarijanska-hrana', 104,
 '{"sr": "Vegetarijanska hrana", "en": "Vegetarian food", "ru": "Вегетарианская еда"}'::jsonb,
 '{"sr": "Namirnice za vegetarijance, sirevi, jaja, mleko", "en": "Vegetarian groceries, cheese, eggs, dairy", "ru": "Вегетарианские продукты, сыр, яйца, молоко"}'::jsonb,
 '{"sr": "Vegetarijanska hrana | Vondi", "en": "Vegetarian food | Vondi", "ru": "Вегетарианская еда | Vondi"}'::jsonb,
 '{"sr": "Kupite vegetarijansku hranu online", "en": "Buy vegetarian food online", "ru": "Купить вегетарианскую еду онлайн"}'::jsonb,
 '🥗', true),

('bezglutenska-hrana', (SELECT id FROM categories WHERE slug = 'hrana-i-pice' AND level = 1), 2, 'hrana-i-pice/bezglutenska-hrana', 105,
 '{"sr": "Bezglutenska hrana", "en": "Gluten-free food", "ru": "Безглютеновая еда"}'::jsonb,
 '{"sr": "Hleb, testenine, grickalice bez glutena", "en": "Bread, pasta, snacks gluten-free", "ru": "Хлеб, паста, закуски без глютена"}'::jsonb,
 '{"sr": "Bezglutenska hrana | Vondi", "en": "Gluten-free food | Vondi", "ru": "Безглютеновая еда | Vondi"}'::jsonb,
 '{"sr": "Kupite bezglutensku hranu online", "en": "Buy gluten-free food online", "ru": "Купить безглютеновую еду онлайн"}'::jsonb,
 '🌾', true),

('hrana-bez-secera', (SELECT id FROM categories WHERE slug = 'hrana-i-pice' AND level = 1), 2, 'hrana-i-pice/hrana-bez-secera', 106,
 '{"sr": "Hrana bez šećera", "en": "Sugar-free food", "ru": "Еда без сахара"}'::jsonb,
 '{"sr": "Slatkiši, napici, deserti bez šećera", "en": "Sweets, drinks, desserts sugar-free", "ru": "Сладости, напитки, десерты без сахара"}'::jsonb,
 '{"sr": "Hrana bez šećera | Vondi", "en": "Sugar-free food | Vondi", "ru": "Еда без сахара | Vondi"}'::jsonb,
 '{"sr": "Kupite hranu bez šećera online - zdrav život", "en": "Buy sugar-free food online", "ru": "Купить еду без сахара онлайн"}'::jsonb,
 '🍬', true),

('bez-laktoze', (SELECT id FROM categories WHERE slug = 'hrana-i-pice' AND level = 1), 2, 'hrana-i-pice/bez-laktoze', 107,
 '{"sr": "Hrana bez laktoze", "en": "Lactose-free food", "ru": "Еда без лактозы"}'::jsonb,
 '{"sr": "Mleko, sir, jogurt bez laktoze", "en": "Milk, cheese, yogurt lactose-free", "ru": "Молоко, сыр, йогурт без лактозы"}'::jsonb,
 '{"sr": "Hrana bez laktoze | Vondi", "en": "Lactose-free food | Vondi", "ru": "Еда без лактозы | Vondi"}'::jsonb,
 '{"sr": "Kupite hranu bez laktoze online", "en": "Buy lactose-free food online", "ru": "Купить еду без лактозы онлайн"}'::jsonb,
 '🥛', true),

('superfood', (SELECT id FROM categories WHERE slug = 'hrana-i-pice' AND level = 1), 2, 'hrana-i-pice/superfood', 108,
 '{"sr": "Superfood", "en": "Superfoods", "ru": "Суперфуды"}'::jsonb,
 '{"sr": "Chia, quinoa, spirulina, goji, acai, maca", "en": "Chia, quinoa, spirulina, goji, acai, maca", "ru": "Чиа, киноа, спирулина, годжи, асаи, мака"}'::jsonb,
 '{"sr": "Superfood | Vondi", "en": "Superfoods | Vondi", "ru": "Суперфуды | Vondi"}'::jsonb,
 '{"sr": "Kupite superfood online - ekstremno zdrava hrana", "en": "Buy superfoods online", "ru": "Купить суперфуды онлайн"}'::jsonb,
 '🌟', true),

('proteini-u-prahu', (SELECT id FROM categories WHERE slug = 'hrana-i-pice' AND level = 1), 2, 'hrana-i-pice/proteini-u-prahu', 109,
 '{"sr": "Proteini u prahu", "en": "Protein powder", "ru": "Протеиновый порошок"}'::jsonb,
 '{"sr": "Whey, kazein, soja, biljni proteini", "en": "Whey, casein, soy, plant proteins", "ru": "Сывороточный, казеиновый, соевый, растительный белок"}'::jsonb,
 '{"sr": "Proteini u prahu | Vondi", "en": "Protein powder | Vondi", "ru": "Протеиновый порошок | Vondi"}'::jsonb,
 '{"sr": "Kupite proteine u prahu - sportska ishrana", "en": "Buy protein powder online", "ru": "Купить протеиновый порошок онлайн"}'::jsonb,
 '💪', true),

('protein-pločice', (SELECT id FROM categories WHERE slug = 'hrana-i-pice' AND level = 1), 2, 'hrana-i-pice/protein-plocice', 110,
 '{"sr": "Protein pločice", "en": "Protein bars", "ru": "Протеиновые батончики"}'::jsonb,
 '{"sr": "Energetske pločice sa visokim proteinima", "en": "Energy bars with high protein content", "ru": "Энергетические батончики с высоким содержанием белка"}'::jsonb,
 '{"sr": "Protein pločice | Vondi", "en": "Protein bars | Vondi", "ru": "Протеиновые батончики | Vondi"}'::jsonb,
 '{"sr": "Kupite protein pločice online - brzi obrok", "en": "Buy protein bars online", "ru": "Купить протеиновые батончики онлайн"}'::jsonb,
 '🍫', true),

('sportska-ishrana-dodaci', (SELECT id FROM categories WHERE slug = 'hrana-i-pice' AND level = 1), 2, 'hrana-i-pice/sportska-ishrana-dodaci', 111,
 '{"sr": "Sportski dodaci ishrani", "en": "Sports nutrition supplements", "ru": "Спортивное питание"}'::jsonb,
 '{"sr": "Kreatin, BCAA, beta-alanin, pre-workout", "en": "Creatine, BCAA, beta-alanine, pre-workout", "ru": "Креатин, BCAA, бета-аланин, предтренировочные комплексы"}'::jsonb,
 '{"sr": "Sportski dodaci ishrani | Vondi", "en": "Sports supplements | Vondi", "ru": "Спортивное питание | Vondi"}'::jsonb,
 '{"sr": "Kupite sportske dodatke ishrani online", "en": "Buy sports nutrition online", "ru": "Купить спортивное питание онлайн"}'::jsonb,
 '🏋️', true),

('zitarice-organik', (SELECT id FROM categories WHERE slug = 'hrana-i-pice' AND level = 1), 2, 'hrana-i-pice/zitarice-organik', 112,
 '{"sr": "Organske žitarice", "en": "Organic grains", "ru": "Органические злаки"}'::jsonb,
 '{"sr": "Ovas, proja, pirinač, quinoa organik", "en": "Oats, millet, rice, quinoa organic", "ru": "Овес, просо, рис, киноа органик"}'::jsonb,
 '{"sr": "Organske žitarice | Vondi", "en": "Organic grains | Vondi", "ru": "Органические злаки | Vondi"}'::jsonb,
 '{"sr": "Kupite organske žitarice online", "en": "Buy organic grains online", "ru": "Купить органические злаки онлайн"}'::jsonb,
 '🌾', true),

('testenine-integralne', (SELECT id FROM categories WHERE slug = 'hrana-i-pice' AND level = 1), 2, 'hrana-i-pice/testenine-integralne', 113,
 '{"sr": "Integralne testenine", "en": "Whole grain pasta", "ru": "Цельнозерновые макароны"}'::jsonb,
 '{"sr": "Testenine od celih zrna, visok sadržaj vlakana", "en": "Whole wheat pasta, high fiber content", "ru": "Паста из цельнозерновой муки, высокое содержание клетчатки"}'::jsonb,
 '{"sr": "Integralne testenine | Vondi", "en": "Whole grain pasta | Vondi", "ru": "Цельнозерновые макароны | Vondi"}'::jsonb,
 '{"sr": "Kupite integralne testenine online", "en": "Buy whole grain pasta online", "ru": "Купить цельнозерновые макароны онлайн"}'::jsonb,
 '🍝', true),

('keto-dijeta', (SELECT id FROM categories WHERE slug = 'hrana-i-pice' AND level = 1), 2, 'hrana-i-pice/keto-dijeta', 114,
 '{"sr": "Keto dijeta", "en": "Keto diet", "ru": "Кето диета"}'::jsonb,
 '{"sr": "Namirnice za ketogenu dijetu, nisko ugljikohidratne", "en": "Ketogenic diet foods, low-carb", "ru": "Продукты для кетогенной диеты, низкоуглеводные"}'::jsonb,
 '{"sr": "Keto dijeta | Vondi", "en": "Keto diet | Vondi", "ru": "Кето диета | Vondi"}'::jsonb,
 '{"sr": "Kupite keto hranu online - ketogena dijeta", "en": "Buy keto food online", "ru": "Купить кето продукты онлайн"}'::jsonb,
 '🥑', true),

('paleo-dijeta', (SELECT id FROM categories WHERE slug = 'hrana-i-pice' AND level = 1), 2, 'hrana-i-pice/paleo-dijeta', 115,
 '{"sr": "Paleo dijeta", "en": "Paleo diet", "ru": "Палео диета"}'::jsonb,
 '{"sr": "Prirodna hrana, meso, riba, voće, povrće, bez prerade", "en": "Natural foods, meat, fish, fruits, vegetables, unprocessed", "ru": "Натуральная еда, мясо, рыба, фрукты, овощи, необработанные"}'::jsonb,
 '{"sr": "Paleo dijeta | Vondi", "en": "Paleo diet | Vondi", "ru": "Палео диета | Vondi"}'::jsonb,
 '{"sr": "Kupite paleo hranu online - prirodna ishrana", "en": "Buy paleo food online", "ru": "Купить палео продукты онлайн"}'::jsonb,
 '🍗', true),

('zdrave-grickalice', (SELECT id FROM categories WHERE slug = 'hrana-i-pice' AND level = 1), 2, 'hrana-i-pice/zdrave-grickalice', 116,
 '{"sr": "Zdrave grickalice", "en": "Healthy snacks", "ru": "Здоровые снеки"}'::jsonb,
 '{"sr": "Orahasti, sušeno voće, protein grickalice", "en": "Nuts, dried fruits, protein snacks", "ru": "Орехи, сушеные фрукты, протеиновые снеки"}'::jsonb,
 '{"sr": "Zdrave grickalice | Vondi", "en": "Healthy snacks | Vondi", "ru": "Здоровые снеки | Vondi"}'::jsonb,
 '{"sr": "Kupite zdrave grickalice online", "en": "Buy healthy snacks online", "ru": "Купить здоровые снеки онлайн"}'::jsonb,
 '🥜', true),

('organski-sokovi', (SELECT id FROM categories WHERE slug = 'hrana-i-pice' AND level = 1), 2, 'hrana-i-pice/organski-sokovi', 117,
 '{"sr": "Organski sokovi", "en": "Organic juices", "ru": "Органические соки"}'::jsonb,
 '{"sr": "Sveži sokovi, cold-pressed, bez konzervansa", "en": "Fresh juices, cold-pressed, preservative-free", "ru": "Свежие соки, холодного отжима, без консервантов"}'::jsonb,
 '{"sr": "Organski sokovi | Vondi", "en": "Organic juices | Vondi", "ru": "Органические соки | Vondi"}'::jsonb,
 '{"sr": "Kupite organske sokove online - zdrav napitak", "en": "Buy organic juices online", "ru": "Купить органические соки онлайн"}'::jsonb,
 '🥤', true),

('kafa-premium', (SELECT id FROM categories WHERE slug = 'hrana-i-pice' AND level = 1), 2, 'hrana-i-pice/kafa-premium', 118,
 '{"sr": "Premium kafa", "en": "Premium coffee", "ru": "Премиум кофе"}'::jsonb,
 '{"sr": "Kafa u zrnu, arabika, specialty coffee, micro-lot", "en": "Coffee beans, arabica, specialty, micro-lot", "ru": "Кофе в зернах, арабика, specialty, микро-лот"}'::jsonb,
 '{"sr": "Premium kafa | Vondi", "en": "Premium coffee | Vondi", "ru": "Премиум кофе | Vondi"}'::jsonb,
 '{"sr": "Kupite premium kafu online - u zrnu i mlevena", "en": "Buy premium coffee online", "ru": "Купить премиум кофе онлайн"}'::jsonb,
 '☕', true),

('caj-premium', (SELECT id FROM categories WHERE slug = 'hrana-i-pice' AND level = 1), 2, 'hrana-i-pice/caj-premium', 119,
 '{"sr": "Premium čaj", "en": "Premium tea", "ru": "Премиум чай"}'::jsonb,
 '{"sr": "Zeleni, crni, beli, oolong, matcha čaj", "en": "Green, black, white, oolong, matcha tea", "ru": "Зеленый, черный, белый, улун, матча чай"}'::jsonb,
 '{"sr": "Premium čaj | Vondi", "en": "Premium tea | Vondi", "ru": "Премиум чай | Vondi"}'::jsonb,
 '{"sr": "Kupite premium čaj online - visokokvalitetan", "en": "Buy premium tea online", "ru": "Купить премиум чай онлайн"}'::jsonb,
 '🍵', true),

('med-organski', (SELECT id FROM categories WHERE slug = 'hrana-i-pice' AND level = 1), 2, 'hrana-i-pice/med-organski', 120,
 '{"sr": "Organski med", "en": "Organic honey", "ru": "Органический мед"}'::jsonb,
 '{"sr": "Prirodan med, bez šećera, različite vrste", "en": "Natural honey, no sugar added, various types", "ru": "Натуральный мед, без добавления сахара, различные виды"}'::jsonb,
 '{"sr": "Organski med | Vondi", "en": "Organic honey | Vondi", "ru": "Органический мед | Vondi"}'::jsonb,
 '{"sr": "Kupite organski med online - 100% prirodan", "en": "Buy organic honey online", "ru": "Купить органический мед онлайн"}'::jsonb,
 '🍯', true),

('maslinovo-ulje-premium', (SELECT id FROM categories WHERE slug = 'hrana-i-pice' AND level = 1), 2, 'hrana-i-pice/maslinovo-ulje-premium', 121,
 '{"sr": "Premium maslinovo ulje", "en": "Premium olive oil", "ru": "Премиум оливковое масло"}'::jsonb,
 '{"sr": "Extra virgin, hladno ceđeno, vrhunski kvalitet", "en": "Extra virgin, cold-pressed, top quality", "ru": "Экстра вирджин, холодного отжима, премиум качество"}'::jsonb,
 '{"sr": "Premium maslinovo ulje | Vondi", "en": "Premium olive oil | Vondi", "ru": "Премиум оливковое масло | Vondi"}'::jsonb,
 '{"sr": "Kupite premium maslinovo ulje online", "en": "Buy premium olive oil online", "ru": "Купить премиум оливковое масло онлайн"}'::jsonb,
 '🫒', true);

-- =============================================================================
-- L2 for: Umetnost i rukotvorine (15 new categories)
-- =============================================================================

INSERT INTO categories (slug, parent_id, level, path, sort_order, name, description, meta_title, meta_description, icon, is_active) VALUES

('boje-akrilne', (SELECT id FROM categories WHERE slug = 'umetnost-i-rukotvorine' AND level = 1), 2, 'umetnost-i-rukotvorine/boje-akrilne', 100,
 '{"sr": "Akrilne boje", "en": "Acrylic paints", "ru": "Акриловые краски"}'::jsonb,
 '{"sr": "Profesionalne i amaterske akrilne boje za umetnost", "en": "Professional and amateur acrylic paints", "ru": "Профессиональные и любительские акриловые краски"}'::jsonb,
 '{"sr": "Akrilne boje | Vondi", "en": "Acrylic paints | Vondi", "ru": "Акриловые краски | Vondi"}'::jsonb,
 '{"sr": "Kupite akrilne boje online - sve boje i setovi", "en": "Buy acrylic paints online", "ru": "Купить акриловые краски онлайн"}'::jsonb,
 '🎨', true),

('boje-uljane', (SELECT id FROM categories WHERE slug = 'umetnost-i-rukotvorine' AND level = 1), 2, 'umetnost-i-rukotvorine/boje-uljane', 101,
 '{"sr": "Uljane boje", "en": "Oil paints", "ru": "Масляные краски"}'::jsonb,
 '{"sr": "Uljane boje za slikanje, profesionalni kvalitet", "en": "Oil paints for painting, professional quality", "ru": "Масляные краски для живописи, профессиональное качество"}'::jsonb,
 '{"sr": "Uljane boje | Vondi", "en": "Oil paints | Vondi", "ru": "Масляные краски | Vondi"}'::jsonb,
 '{"sr": "Kupite uljane boje online - vrhunski kvalitet", "en": "Buy oil paints online", "ru": "Купить масляные краски онлайн"}'::jsonb,
 '🖌️', true),

('boje-vodene', (SELECT id FROM categories WHERE slug = 'umetnost-i-rukotvorine' AND level = 1), 2, 'umetnost-i-rukotvorine/boje-vodene', 102,
 '{"sr": "Vodene boje", "en": "Watercolors", "ru": "Акварельные краски"}'::jsonb,
 '{"sr": "Vodene boje, akvarelne boje, setovi", "en": "Watercolors, aquarelle paints, sets", "ru": "Акварель, акварельные краски, наборы"}'::jsonb,
 '{"sr": "Vodene boje | Vondi", "en": "Watercolors | Vondi", "ru": "Акварельные краски | Vondi"}'::jsonb,
 '{"sr": "Kupite vodene boje online - svi tonovi", "en": "Buy watercolors online", "ru": "Купить акварельные краски онлайн"}'::jsonb,
 '💧', true),

('cetkice-za-slikanje', (SELECT id FROM categories WHERE slug = 'umetnost-i-rukotvorine' AND level = 1), 2, 'umetnost-i-rukotvorine/cetkice-za-slikanje', 103,
 '{"sr": "Četkice za slikanje", "en": "Paint brushes", "ru": "Кисти для рисования"}'::jsonb,
 '{"sr": "Profesionalne četkice, prirodna i sintetička dlaka", "en": "Professional brushes, natural and synthetic bristles", "ru": "Профессиональные кисти, натуральный и синтетический ворс"}'::jsonb,
 '{"sr": "Četkice za slikanje | Vondi", "en": "Paint brushes | Vondi", "ru": "Кисти для рисования | Vondi"}'::jsonb,
 '{"sr": "Kupite četkice za slikanje online - sve veličine", "en": "Buy paint brushes online", "ru": "Купить кисти для рисования онлайн"}'::jsonb,
 '🖌️', true),

('platna-za-slikanje', (SELECT id FROM categories WHERE slug = 'umetnost-i-rukotvorine' AND level = 1), 2, 'umetnost-i-rukotvorine/platna-za-slikanje', 104,
 '{"sr": "Platna za slikanje", "en": "Canvas for painting", "ru": "Холсты для живописи"}'::jsonb,
 '{"sr": "Napeta platna, canvas paneli, različite dimenzije", "en": "Stretched canvas, canvas panels, various sizes", "ru": "Натянутые холсты, холст панели, различные размеры"}'::jsonb,
 '{"sr": "Platna za slikanje | Vondi", "en": "Canvas for painting | Vondi", "ru": "Холсты для живописи | Vondi"}'::jsonb,
 '{"sr": "Kupite platna za slikanje online - sve dimenzije", "en": "Buy canvas for painting online", "ru": "Купить холсты для живописи онлайн"}'::jsonb,
 '🖼️', true),

('molberti', (SELECT id FROM categories WHERE slug = 'umetnost-i-rukotvorine' AND level = 1), 2, 'umetnost-i-rukotvorine/molberti', 105,
 '{"sr": "Molberti", "en": "Easels", "ru": "Мольберты"}'::jsonb,
 '{"sr": "Studio, field, table easels, različite veličine", "en": "Studio, field, table easels, various sizes", "ru": "Студийные, полевые, настольные мольберты, различные размеры"}'::jsonb,
 '{"sr": "Molberti | Vondi", "en": "Easels | Vondi", "ru": "Мольберты | Vondi"}'::jsonb,
 '{"sr": "Kupite molberte online - studio i portable", "en": "Buy easels online", "ru": "Купить мольберты онлайн"}'::jsonb,
 '🎨', true),

('olovke-za-crtanje', (SELECT id FROM categories WHERE slug = 'umetnost-i-rukotvorine' AND level = 1), 2, 'umetnost-i-rukotvorine/olovke-za-crtanje', 106,
 '{"sr": "Olovke za crtanje", "en": "Drawing pencils", "ru": "Карандаши для рисования"}'::jsonb,
 '{"sr": "Grafitne olovke, ugalj, sketching setovi", "en": "Graphite pencils, charcoal, sketching sets", "ru": "Графитные карандаши, уголь, наборы для скетчинга"}'::jsonb,
 '{"sr": "Olovke za crtanje | Vondi", "en": "Drawing pencils | Vondi", "ru": "Карандаши для рисования | Vondi"}'::jsonb,
 '{"sr": "Kupite olovke za crtanje online - svi tonovi", "en": "Buy drawing pencils online", "ru": "Купить карандаши для рисования онлайн"}'::jsonb,
 '✏️', true),

('boje-u-olovci', (SELECT id FROM categories WHERE slug = 'umetnost-i-rukotvorine' AND level = 1), 2, 'umetnost-i-rukotvorine/boje-u-olovci', 107,
 '{"sr": "Olovke u boji", "en": "Colored pencils", "ru": "Цветные карандаши"}'::jsonb,
 '{"sr": "Profesionalne olovke u boji, setovi za umetnost", "en": "Professional colored pencils, art sets", "ru": "Профессиональные цветные карандаши, наборы для художников"}'::jsonb,
 '{"sr": "Olovke u boji | Vondi", "en": "Colored pencils | Vondi", "ru": "Цветные карандаши | Vondi"}'::jsonb,
 '{"sr": "Kupite olovke u boji online - profesionalni setovi", "en": "Buy colored pencils online", "ru": "Купить цветные карандаши онлайн"}'::jsonb,
 '🖍️', true),

('konac-za-vez', (SELECT id FROM categories WHERE slug = 'umetnost-i-rukotvorine' AND level = 1), 2, 'umetnost-i-rukotvorine/konac-za-vez', 108,
 '{"sr": "Konac za vez", "en": "Embroidery thread", "ru": "Нитки для вышивания"}'::jsonb,
 '{"sr": "DMC, muline, konci u svim bojama za vez", "en": "DMC, mouline, threads in all colors for embroidery", "ru": "DMC, мулине, нитки во всех цветах для вышивания"}'::jsonb,
 '{"sr": "Konac za vez | Vondi", "en": "Embroidery thread | Vondi", "ru": "Нитки для вышивания | Vondi"}'::jsonb,
 '{"sr": "Kupite konac za vez online - sve boje DMC", "en": "Buy embroidery thread online", "ru": "Купить нитки для вышивания онлайн"}'::jsonb,
 '🧵', true),

('platno-za-vez', (SELECT id FROM categories WHERE slug = 'umetnost-i-rukotvorine' AND level = 1), 2, 'umetnost-i-rukotvorine/platno-za-vez', 109,
 '{"sr": "Platno za vez", "en": "Embroidery fabric", "ru": "Канва для вышивания"}'::jsonb,
 '{"sr": "Kanva, aida, evenweave, linen za vez", "en": "Canvas, aida, evenweave, linen for embroidery", "ru": "Канва, аида, ровное переплетение, лен для вышивания"}'::jsonb,
 '{"sr": "Platno za vez | Vondi", "en": "Embroidery fabric | Vondi", "ru": "Канва для вышивания | Vondi"}'::jsonb,
 '{"sr": "Kupite platno za vez online - različiti tipovi", "en": "Buy embroidery fabric online", "ru": "Купить канву для вышивания онлайн"}'::jsonb,
 '🪡', true),

('perle-za-nakit', (SELECT id FROM categories WHERE slug = 'umetnost-i-rukotvorine' AND level = 1), 2, 'umetnost-i-rukotvorine/perle-za-nakit', 110,
 '{"sr": "Perle za nakit", "en": "Beads for jewelry", "ru": "Бусины для украшений"}'::jsonb,
 '{"sr": "Staklene, kristalne, drvene perle za izradu nakita", "en": "Glass, crystal, wooden beads for jewelry making", "ru": "Стеклянные, хрустальные, деревянные бусины для изготовления украшений"}'::jsonb,
 '{"sr": "Perle za nakit | Vondi", "en": "Beads for jewelry | Vondi", "ru": "Бусины для украшений | Vondi"}'::jsonb,
 '{"sr": "Kupite perle za nakit online - različite vrste", "en": "Buy beads for jewelry online", "ru": "Купить бусины для украшений онлайн"}'::jsonb,
 '📿', true),

('biser', (SELECT id FROM categories WHERE slug = 'umetnost-i-rukotvorine' AND level = 1), 2, 'umetnost-i-rukotvorine/biser', 111,
 '{"sr": "Biser", "en": "Beads", "ru": "Бисер"}'::jsonb,
 '{"sr": "Sitni biser za izradu nakita i ukrasa", "en": "Small beads for jewelry and decorations", "ru": "Мелкий бисер для изготовления украшений и декора"}'::jsonb,
 '{"sr": "Biser | Vondi", "en": "Beads | Vondi", "ru": "Бисер | Vondi"}'::jsonb,
 '{"sr": "Kupite biser online - sve boje i veličine", "en": "Buy beads online", "ru": "Купить бисер онлайн"}'::jsonb,
 '✨', true),

('glina-za-modelovanje', (SELECT id FROM categories WHERE slug = 'umetnost-i-rukotvorine' AND level = 1), 2, 'umetnost-i-rukotvorine/glina-za-modelovanje', 112,
 '{"sr": "Glina za modelovanje", "en": "Modeling clay", "ru": "Глина для лепки"}'::jsonb,
 '{"sr": "Polimerna glina, plastelina, self-hardening clay", "en": "Polymer clay, plasticine, self-hardening clay", "ru": "Полимерная глина, пластилин, самозатвердевающая глина"}'::jsonb,
 '{"sr": "Glina za modelovanje | Vondi", "en": "Modeling clay | Vondi", "ru": "Глина для лепки | Vondi"}'::jsonb,
 '{"sr": "Kupite glinu za modelovanje online", "en": "Buy modeling clay online", "ru": "Купить глину для лепки онлайн"}'::jsonb,
 '🏺', true),

('gips', (SELECT id FROM categories WHERE slug = 'umetnost-i-rukotvorine' AND level = 1), 2, 'umetnost-i-rukotvorine/gips', 113,
 '{"sr": "Gips", "en": "Plaster", "ru": "Гипс"}'::jsonb,
 '{"sr": "Gips za kalupe, skulpture, rukotvorine", "en": "Plaster for molds, sculptures, crafts", "ru": "Гипс для форм, скульптур, поделок"}'::jsonb,
 '{"sr": "Gips | Vondi", "en": "Plaster | Vondi", "ru": "Гипс | Vondi"}'::jsonb,
 '{"sr": "Kupite gips online - za sve vrste radova", "en": "Buy plaster online", "ru": "Купить гипс онлайн"}'::jsonb,
 '🗿', true),

('decoupage-setovi', (SELECT id FROM categories WHERE slug = 'umetnost-i-rukotvorine' AND level = 1), 2, 'umetnost-i-rukotvorine/decoupage-setovi', 114,
 '{"sr": "Decoupage setovi", "en": "Decoupage sets", "ru": "Наборы для декупажа"}'::jsonb,
 '{"sr": "Salvete, lepkovi, četkice za decoupage", "en": "Napkins, glues, brushes for decoupage", "ru": "Салфетки, клей, кисти для декупажа"}'::jsonb,
 '{"sr": "Decoupage setovi | Vondi", "en": "Decoupage sets | Vondi", "ru": "Наборы для декупажа | Vondi"}'::jsonb,
 '{"sr": "Kupite decoupage setove online - kompletna oprema", "en": "Buy decoupage sets online", "ru": "Купить наборы для декупажа онлайн"}'::jsonb,
 '🎀', true);

-- =============================================================================
-- L2 for: Industrija i alati (23 new categories)
-- =============================================================================

INSERT INTO categories (slug, parent_id, level, path, sort_order, name, description, meta_title, meta_description, icon, is_active) VALUES

('busilice-profesionalne', (SELECT id FROM categories WHERE slug = 'industrija-i-alati' AND level = 1), 2, 'industrija-i-alati/busilice-profesionalne', 100,
 '{"sr": "Profesionalne bušilice", "en": "Professional drills", "ru": "Профессиональные дрели"}'::jsonb,
 '{"sr": "Udarne, bezudarne, akumulatorske bušilice za profesionalce", "en": "Hammer, non-hammer, cordless drills for professionals", "ru": "Ударные, безударные, аккумуляторные дрели для профессионалов"}'::jsonb,
 '{"sr": "Profesionalne bušilice | Vondi", "en": "Professional drills | Vondi", "ru": "Профессиональные дрели | Vondi"}'::jsonb,
 '{"sr": "Kupite profesionalne bušilice online - vrhunski kvalitet", "en": "Buy professional drills online", "ru": "Купить профессиональные дрели онлайн"}'::jsonb,
 '🔨', true),

('brusilice-ugaone', (SELECT id FROM categories WHERE slug = 'industrija-i-alati' AND level = 1), 2, 'industrija-i-alati/brusilice-ugaone', 101,
 '{"sr": "Ugaone brusilice", "en": "Angle grinders", "ru": "Угловые шлифмашины"}'::jsonb,
 '{"sr": "Profesionalne ugaone brusilice, različite snage", "en": "Professional angle grinders, various powers", "ru": "Профессиональные угловые шлифмашины, различная мощность"}'::jsonb,
 '{"sr": "Ugaone brusilice | Vondi", "en": "Angle grinders | Vondi", "ru": "Угловые шлифмашины | Vondi"}'::jsonb,
 '{"sr": "Kupite ugaone brusilice online - profesionalne", "en": "Buy angle grinders online", "ru": "Купить угловые шлифмашины онлайн"}'::jsonb,
 '⚙️', true),

('brusilice-vibracione', (SELECT id FROM categories WHERE slug = 'industrija-i-alati' AND level = 1), 2, 'industrija-i-alati/brusilice-vibracione', 102,
 '{"sr": "Vibracione brusilice", "en": "Orbital sanders", "ru": "Вибрационные шлифмашины"}'::jsonb,
 '{"sr": "Oscilacione brusilice, delta brusilice, za fino brušenje", "en": "Oscillating sanders, delta sanders, for fine sanding", "ru": "Осцилляционные шлифмашины, дельта шлифмашины, для тонкой шлифовки"}'::jsonb,
 '{"sr": "Vibracione brusilice | Vondi", "en": "Orbital sanders | Vondi", "ru": "Вибрационные шлифмашины | Vondi"}'::jsonb,
 '{"sr": "Kupite vibracione brusilice online", "en": "Buy orbital sanders online", "ru": "Купить вибрационные шлифмашины онлайн"}'::jsonb,
 '🪛', true),

('testeri-kruzne', (SELECT id FROM categories WHERE slug = 'industrija-i-alati' AND level = 1), 2, 'industrija-i-alati/testeri-kruzne', 103,
 '{"sr": "Kružne testere", "en": "Circular saws", "ru": "Циркулярные пилы"}'::jsonb,
 '{"sr": "Profesionalne kružne testere za drvo i metal", "en": "Professional circular saws for wood and metal", "ru": "Профессиональные циркулярные пилы для дерева и металла"}'::jsonb,
 '{"sr": "Kružne testere | Vondi", "en": "Circular saws | Vondi", "ru": "Циркулярные пилы | Vondi"}'::jsonb,
 '{"sr": "Kupite kružne testere online - profesionalne", "en": "Buy circular saws online", "ru": "Купить циркулярные пилы онлайн"}'::jsonb,
 '🪚', true),

('testeri-lancane', (SELECT id FROM categories WHERE slug = 'industrija-i-alati' AND level = 1), 2, 'industrija-i-alati/testeri-lancane', 104,
 '{"sr": "Lančane testere", "en": "Chainsaws", "ru": "Бензопилы"}'::jsonb,
 '{"sr": "Motorne, električne, akumulatorske lančane testere", "en": "Gas, electric, cordless chainsaws", "ru": "Бензиновые, электрические, аккумуляторные бензопилы"}'::jsonb,
 '{"sr": "Lančane testere | Vondi", "en": "Chainsaws | Vondi", "ru": "Бензопилы | Vondi"}'::jsonb,
 '{"sr": "Kupite lančane testere online - sve vrste", "en": "Buy chainsaws online", "ru": "Купить бензопилы онлайн"}'::jsonb,
 '⛓️', true),

('cirkular', (SELECT id FROM categories WHERE slug = 'industrija-i-alati' AND level = 1), 2, 'industrija-i-alati/cirkular', 105,
 '{"sr": "Cirkular", "en": "Table saw", "ru": "Циркулярный станок"}'::jsonb,
 '{"sr": "Stoni cirkular za profesionalne radove", "en": "Table saw for professional work", "ru": "Циркулярный станок для профессиональных работ"}'::jsonb,
 '{"sr": "Cirkular | Vondi", "en": "Table saw | Vondi", "ru": "Циркулярный станок | Vondi"}'::jsonb,
 '{"sr": "Kupite cirkular online - profesionalni alat", "en": "Buy table saw online", "ru": "Купить циркулярный станок онлайн"}'::jsonb,
 '🛠️', true),

('rende-elektricne', (SELECT id FROM categories WHERE slug = 'industrija-i-alati' AND level = 1), 2, 'industrija-i-alati/rende-elektricne', 106,
 '{"sr": "Električne rende", "en": "Electric planers", "ru": "Электрорубанки"}'::jsonb,
 '{"sr": "Rende za blanjanje drveta, profesionalni alat", "en": "Planers for wood planing, professional tools", "ru": "Рубанки для строгания дерева, профессиональный инструмент"}'::jsonb,
 '{"sr": "Električne rende | Vondi", "en": "Electric planers | Vondi", "ru": "Электрорубанки | Vondi"}'::jsonb,
 '{"sr": "Kupite električne rende online", "en": "Buy electric planers online", "ru": "Купить электрорубанки онлайн"}'::jsonb,
 '🪚', true),

('odvijaci-akumulatorski', (SELECT id FROM categories WHERE slug = 'industrija-i-alati' AND level = 1), 2, 'industrija-i-alati/odvijaci-akumulatorski', 107,
 '{"sr": "Akumulatorski odvijači", "en": "Cordless screwdrivers", "ru": "Аккумуляторные отвертки"}'::jsonb,
 '{"sr": "Bežični odvijači sa Li-Ion baterijama", "en": "Cordless screwdrivers with Li-Ion batteries", "ru": "Беспроводные отвертки с Li-Ion батареями"}'::jsonb,
 '{"sr": "Akumulatorski odvijači | Vondi", "en": "Cordless screwdrivers | Vondi", "ru": "Аккумуляторные отвертки | Vondi"}'::jsonb,
 '{"sr": "Kupite akumulatorske odvijače online", "en": "Buy cordless screwdrivers online", "ru": "Купить аккумуляторные отвертки онлайн"}'::jsonb,
 '🔧', true),

('udarni-odvijaci', (SELECT id FROM categories WHERE slug = 'industrija-i-alati' AND level = 1), 2, 'industrija-i-alati/udarni-odvijaci', 108,
 '{"sr": "Udarni odvijači", "en": "Impact drivers", "ru": "Ударные отвертки"}'::jsonb,
 '{"sr": "Profesionalni udarni odvijači sa visokim momentom", "en": "Professional impact drivers with high torque", "ru": "Профессиональные ударные отвертки с высоким моментом"}'::jsonb,
 '{"sr": "Udarni odvijači | Vondi", "en": "Impact drivers | Vondi", "ru": "Ударные отвертки | Vondi"}'::jsonb,
 '{"sr": "Kupite udarne odvijače online - profesionalne", "en": "Buy impact drivers online", "ru": "Купить ударные отвертки онлайн"}'::jsonb,
 '💥', true),

('akumulatori-profesionalni', (SELECT id FROM categories WHERE slug = 'industrija-i-alati' AND level = 1), 2, 'industrija-i-alati/akumulatori-profesionalni', 109,
 '{"sr": "Profesionalni akumulatori", "en": "Professional batteries", "ru": "Профессиональные аккумуляторы"}'::jsonb,
 '{"sr": "Li-Ion akumulatori za električne alate, različiti kapaciteti", "en": "Li-Ion batteries for power tools, various capacities", "ru": "Li-Ion аккумуляторы для электроинструментов, различные емкости"}'::jsonb,
 '{"sr": "Profesionalni akumulatori | Vondi", "en": "Professional batteries | Vondi", "ru": "Профессиональные аккумуляторы | Vondi"}'::jsonb,
 '{"sr": "Kupite profesionalne akumulatore online", "en": "Buy professional batteries online", "ru": "Купить профессиональные аккумуляторы онлайн"}'::jsonb,
 '🔋', true),

('kompresori-klipni', (SELECT id FROM categories WHERE slug = 'industrija-i-alati' AND level = 1), 2, 'industrija-i-alati/kompresori-klipni', 110,
 '{"sr": "Klipni kompresori", "en": "Piston compressors", "ru": "Поршневые компрессоры"}'::jsonb,
 '{"sr": "Profesionalni klipni kompresori za vazduh", "en": "Professional piston air compressors", "ru": "Профессиональные поршневые воздушные компрессоры"}'::jsonb,
 '{"sr": "Klipni kompresori | Vondi", "en": "Piston compressors | Vondi", "ru": "Поршневые компрессоры | Vondi"}'::jsonb,
 '{"sr": "Kupite klipne kompresore online - profesionalni", "en": "Buy piston compressors online", "ru": "Купить поршневые компрессоры онлайн"}'::jsonb,
 '💨', true),

('kompresori-ventilatorski', (SELECT id FROM categories WHERE slug = 'industrija-i-alati' AND level = 1), 2, 'industrija-i-alati/kompresori-ventilatorski', 111,
 '{"sr": "Ventilatorski kompresori", "en": "Scroll compressors", "ru": "Винтовые компрессоры"}'::jsonb,
 '{"sr": "Tihiji kompresori sa kontinualnim radom", "en": "Quieter compressors with continuous operation", "ru": "Более тихие компрессоры с непрерывной работой"}'::jsonb,
 '{"sr": "Ventilatorski kompresori | Vondi", "en": "Scroll compressors | Vondi", "ru": "Винтовые компрессоры | Vondi"}'::jsonb,
 '{"sr": "Kupite ventilatorske kompresore online", "en": "Buy scroll compressors online", "ru": "Купить винтовые компрессоры онлайн"}'::jsonb,
 '🌬️', true),

('generatori-benzin', (SELECT id FROM categories WHERE slug = 'industrija-i-alati' AND level = 1), 2, 'industrija-i-alati/generatori-benzin', 112,
 '{"sr": "Benzinski generatori", "en": "Gas generators", "ru": "Бензиновые генераторы"}'::jsonb,
 '{"sr": "Agregati na benzin, različite snage", "en": "Gas-powered generators, various powers", "ru": "Бензиновые генераторы, различная мощность"}'::jsonb,
 '{"sr": "Benzinski generatori | Vondi", "en": "Gas generators | Vondi", "ru": "Бензиновые генераторы | Vondi"}'::jsonb,
 '{"sr": "Kupite benzinske generatore online", "en": "Buy gas generators online", "ru": "Купить бензиновые генераторы онлайн"}'::jsonb,
 '⚡', true),

('generatori-dizel', (SELECT id FROM categories WHERE slug = 'industrija-i-alati' AND level = 1), 2, 'industrija-i-alati/generatori-dizel', 113,
 '{"sr": "Dizel generatori", "en": "Diesel generators", "ru": "Дизельные генераторы"}'::jsonb,
 '{"sr": "Profesionalni dizel agregati, visoka snaga", "en": "Professional diesel generators, high power", "ru": "Профессиональные дизельные генераторы, высокая мощность"}'::jsonb,
 '{"sr": "Dizel generatori | Vondi", "en": "Diesel generators | Vondi", "ru": "Дизельные генераторы | Vondi"}'::jsonb,
 '{"sr": "Kupite dizel generatore online - profesionalni", "en": "Buy diesel generators online", "ru": "Купить дизельные генераторы онлайн"}'::jsonb,
 '🔌', true),

('zavarivaci-inverter', (SELECT id FROM categories WHERE slug = 'industrija-i-alati' AND level = 1), 2, 'industrija-i-alati/zavarivaci-inverter', 114,
 '{"sr": "Inverter zavarivači", "en": "Inverter welders", "ru": "Инверторные сварочные аппараты"}'::jsonb,
 '{"sr": "Električni inverter aparati za zavarivanje", "en": "Electric inverter welding machines", "ru": "Электрические инверторные сварочные аппараты"}'::jsonb,
 '{"sr": "Inverter zavarivači | Vondi", "en": "Inverter welders | Vondi", "ru": "Инверторные сварочные аппараты | Vondi"}'::jsonb,
 '{"sr": "Kupite inverter zavarivače online", "en": "Buy inverter welders online", "ru": "Купить инверторные сварочные аппараты онлайн"}'::jsonb,
 '🔥', true),

('zavarivaci-tig', (SELECT id FROM categories WHERE slug = 'industrija-i-alati' AND level = 1), 2, 'industrija-i-alati/zavarivaci-tig', 115,
 '{"sr": "TIG zavarivači", "en": "TIG welders", "ru": "TIG сварочные аппараты"}'::jsonb,
 '{"sr": "Aparati za TIG zavarivanje, visoka preciznost", "en": "TIG welding machines, high precision", "ru": "Аппараты для TIG сварки, высокая точность"}'::jsonb,
 '{"sr": "TIG zavarivači | Vondi", "en": "TIG welders | Vondi", "ru": "TIG сварочные аппараты | Vondi"}'::jsonb,
 '{"sr": "Kupite TIG zavarivače online - profesionalni", "en": "Buy TIG welders online", "ru": "Купить TIG сварочные аппараты онлайн"}'::jsonb,
 '⚡', true),

('zavarivaci-mig', (SELECT id FROM categories WHERE slug = 'industrija-i-alati' AND level = 1), 2, 'industrija-i-alati/zavarivaci-mig', 116,
 '{"sr": "MIG/MAG zavarivači", "en": "MIG/MAG welders", "ru": "MIG/MAG сварочные аппараты"}'::jsonb,
 '{"sr": "Poluautomatski aparati za zavarivanje sa žicom", "en": "Semi-automatic wire welding machines", "ru": "Полуавтоматические сварочные аппараты с проволокой"}'::jsonb,
 '{"sr": "MIG/MAG zavarivači | Vondi", "en": "MIG/MAG welders | Vondi", "ru": "MIG/MAG сварочные аппараты | Vondi"}'::jsonb,
 '{"sr": "Kupite MIG/MAG zavarivače online", "en": "Buy MIG/MAG welders online", "ru": "Купить MIG/MAG сварочные аппараты онлайн"}'::jsonb,
 '🛠️', true),

('meraci-laserni', (SELECT id FROM categories WHERE slug = 'industrija-i-alati' AND level = 1), 2, 'industrija-i-alati/meraci-laserni', 117,
 '{"sr": "Laserski merači", "en": "Laser meters", "ru": "Лазерные дальномеры"}'::jsonb,
 '{"sr": "Laserski daljinomeri, precizno merenje razdaljine", "en": "Laser distance meters, precise measurements", "ru": "Лазерные дальномеры, точное измерение расстояний"}'::jsonb,
 '{"sr": "Laserski merači | Vondi", "en": "Laser meters | Vondi", "ru": "Лазерные дальномеры | Vondi"}'::jsonb,
 '{"sr": "Kupite laserske merače online - precizni", "en": "Buy laser meters online", "ru": "Купить лазерные дальномеры онлайн"}'::jsonb,
 '📏', true),

('vodopasi', (SELECT id FROM categories WHERE slug = 'industrija-i-alati' AND level = 1), 2, 'industrija-i-alati/vodopasi', 118,
 '{"sr": "Vodopasi", "en": "Spirit levels", "ru": "Уровни"}'::jsonb,
 '{"sr": "Profesionalni vodopasi, različite dužine", "en": "Professional spirit levels, various lengths", "ru": "Профессиональные уровни, различные длины"}'::jsonb,
 '{"sr": "Vodopasi | Vondi", "en": "Spirit levels | Vondi", "ru": "Уровни | Vondi"}'::jsonb,
 '{"sr": "Kupite vodopase online - profesionalni alat", "en": "Buy spirit levels online", "ru": "Купить уровни онлайн"}'::jsonb,
 '📐', true),

('niveliri', (SELECT id FROM categories WHERE slug = 'industrija-i-alati' AND level = 1), 2, 'industrija-i-alati/niveliri', 119,
 '{"sr": "Niveliri", "en": "Levels", "ru": "Нивелиры"}'::jsonb,
 '{"sr": "Optički i laserski niveliri za geodetske radove", "en": "Optical and laser levels for surveying", "ru": "Оптические и лазерные нивелиры для геодезических работ"}'::jsonb,
 '{"sr": "Niveliri | Vondi", "en": "Levels | Vondi", "ru": "Нивелиры | Vondi"}'::jsonb,
 '{"sr": "Kupite niveline online - geodetski alat", "en": "Buy levels online", "ru": "Купить нивелиры онлайн"}'::jsonb,
 '🔭', true),

('merila-digitalna', (SELECT id FROM categories WHERE slug = 'industrija-i-alati' AND level = 1), 2, 'industrija-i-alati/merila-digitalna', 120,
 '{"sr": "Digitalna merila", "en": "Digital measuring tools", "ru": "Цифровые измерительные инструменты"}'::jsonb,
 '{"sr": "Digitalni pomak, mikrometri, kutomeri", "en": "Digital calipers, micrometers, protractors", "ru": "Цифровые штангенциркули, микрометры, угломеры"}'::jsonb,
 '{"sr": "Digitalna merila | Vondi", "en": "Digital measuring tools | Vondi", "ru": "Цифровые измерительные инструменты | Vondi"}'::jsonb,
 '{"sr": "Kupite digitalna merila online - precizna", "en": "Buy digital measuring tools online", "ru": "Купить цифровые измерительные инструменты онлайн"}'::jsonb,
 '🔬', true),

('stege', (SELECT id FROM categories WHERE slug = 'industrija-i-alati' AND level = 1), 2, 'industrija-i-alati/stege', 121,
 '{"sr": "Stege", "en": "Clamps", "ru": "Струбцины"}'::jsonb,
 '{"sr": "Profesionalne stege za fiksiranje materijala", "en": "Professional clamps for material fixing", "ru": "Профессиональные струбцины для фиксации материалов"}'::jsonb,
 '{"sr": "Stege | Vondi", "en": "Clamps | Vondi", "ru": "Струбцины | Vondi"}'::jsonb,
 '{"sr": "Kupite stege online - različiti tipovi", "en": "Buy clamps online", "ru": "Купить струбцины онлайн"}'::jsonb,
 '🗜️', true),

('tesle', (SELECT id FROM categories WHERE slug = 'industrija-i-alati' AND level = 1), 2, 'industrija-i-alati/tesle', 122,
 '{"sr": "Tesle", "en": "Adzes", "ru": "Тёсла"}'::jsonb,
 '{"sr": "Profesionalne tesle za obradu drveta", "en": "Professional adzes for woodworking", "ru": "Профессиональные тёсла для обработки дерева"}'::jsonb,
 '{"sr": "Tesle | Vondi", "en": "Adzes | Vondi", "ru": "Тёсла | Vondi"}'::jsonb,
 '{"sr": "Kupite tesle online - alat za drvo", "en": "Buy adzes online", "ru": "Купить тёсла онлайн"}'::jsonb,
 '🪓', true);
