-- Drop table: marketplace_listings
DROP SEQUENCE IF EXISTS public.marketplace_listings_id_seq;
DROP TABLE IF EXISTS public.marketplace_listings;
DROP INDEX IF EXISTS public.idx_listings_metadata_discount;
DROP INDEX IF EXISTS public.idx_marketplace_listings_category_status;
DROP INDEX IF EXISTS public.idx_marketplace_listings_city;
DROP INDEX IF EXISTS public.idx_marketplace_listings_external_id;
DROP INDEX IF EXISTS public.idx_marketplace_listings_external_id_storefront_id;
DROP INDEX IF EXISTS public.idx_marketplace_listings_location;
DROP INDEX IF EXISTS public.idx_marketplace_listings_price;
DROP INDEX IF EXISTS public.idx_marketplace_listings_status;
DROP INDEX IF EXISTS public.idx_marketplace_listings_status_created;
DROP INDEX IF EXISTS public.idx_marketplace_listings_storefront;
DROP INDEX IF EXISTS public.idx_marketplace_listings_title_gin;
DROP INDEX IF EXISTS public.idx_marketplace_listings_user_status;
DROP TRIGGER IF EXISTS preserve_review_origin_trigger ON public.marketplace_listings;
DROP TRIGGER IF EXISTS refresh_category_counts_delete ON public.marketplace_listings;
DROP TRIGGER IF EXISTS refresh_category_counts_insert ON public.marketplace_listings;
DROP TRIGGER IF EXISTS refresh_category_counts_update ON public.marketplace_listings;
DROP TRIGGER IF EXISTS trg_new_listing_price_history ON public.marketplace_listings;
DROP TRIGGER IF EXISTS trg_update_listing_price_history ON public.marketplace_listings;
DROP TRIGGER IF EXISTS trigger_marketplace_listings_cache_refresh ON public.marketplace_listings;