CREATE INDEX idx_car_makes_popularity ON public.car_makes USING btree (popularity_rs DESC);
CREATE INDEX idx_car_makes_slug ON public.car_makes USING btree (slug);
CREATE INDEX idx_car_models_battery_capacity ON public.car_models USING btree (battery_capacity_kwh) WHERE (battery_capacity_kwh IS NOT NULL);
CREATE INDEX idx_car_models_body_type ON public.car_models USING btree (body_type);
CREATE INDEX idx_car_models_drive_type ON public.car_models USING btree (drive_type);
CREATE INDEX idx_car_models_engine_type ON public.car_models USING btree (engine_type);
CREATE INDEX idx_car_models_external_id ON public.car_models USING btree (external_id);
CREATE INDEX idx_car_models_fuel_type ON public.car_models USING btree (fuel_type);
CREATE INDEX idx_car_models_is_electric ON public.car_models USING btree (is_electric) WHERE (is_electric = true);
CREATE INDEX idx_car_models_make_slug ON public.car_models USING btree (make_id, slug);
CREATE INDEX idx_car_models_search ON public.car_models USING gin (to_tsvector('simple'::regconfig, (name)::text));
CREATE INDEX idx_car_models_serbia_popularity ON public.car_models USING btree (serbia_popularity_score DESC);
CREATE INDEX idx_car_models_transmission_type ON public.car_models USING btree (transmission_type);
CREATE INDEX idx_category_attr_mapping ON public.category_attribute_mapping USING btree (category_id, is_enabled) WHERE (is_enabled = true);
CREATE INDEX idx_category_attribute_groups_category ON public.category_attribute_groups USING btree (category_id);
CREATE INDEX idx_category_attribute_groups_component ON public.category_attribute_groups USING btree (component_id);
CREATE INDEX idx_category_attribute_groups_group ON public.category_attribute_groups USING btree (group_id);
CREATE INDEX idx_category_attribute_map_attr_id ON public.category_attribute_mapping USING btree (attribute_id);
CREATE INDEX idx_category_attribute_map_cat_id ON public.category_attribute_mapping USING btree (category_id);
CREATE INDEX idx_category_attribute_mapping_custom_component ON public.category_attribute_mapping USING btree (custom_component);
CREATE INDEX idx_category_variant_attributes_category_id ON public.category_variant_attributes USING btree (category_id);
CREATE INDEX idx_category_variant_attributes_variant_name ON public.category_variant_attributes USING btree (variant_attribute_name);
CREATE INDEX idx_category_weight ON public.category_keywords USING btree (category_id, weight DESC);
CREATE INDEX idx_chat_attachments_created_at ON public.chat_attachments USING btree (created_at);
CREATE INDEX idx_chat_attachments_file_type ON public.chat_attachments USING btree (file_type);
CREATE INDEX idx_chat_attachments_message ON public.chat_attachments USING btree (message_id);
CREATE INDEX idx_chat_attachments_message_id ON public.chat_attachments USING btree (message_id);
CREATE INDEX idx_cities_boundary ON public.cities USING gist (boundary);
CREATE INDEX idx_cities_center ON public.cities USING gist (center_point);
CREATE INDEX idx_cities_country ON public.cities USING btree (country_code);
CREATE INDEX idx_cities_has_districts ON public.cities USING btree (has_districts);
CREATE INDEX idx_cities_name ON public.cities USING btree (name);
CREATE INDEX idx_cities_priority ON public.cities USING btree (priority);
CREATE INDEX idx_cities_slug ON public.cities USING btree (slug);
CREATE INDEX idx_component_templates_cat ON public.component_templates USING btree (category_id);
CREATE INDEX idx_component_templates_comp ON public.component_templates USING btree (component_id);
CREATE INDEX idx_couriers_online_available ON public.couriers USING btree (is_online, is_available) WHERE ((is_online = true) AND (is_available = true));
CREATE INDEX idx_couriers_user_id ON public.couriers USING btree (user_id);
CREATE INDEX idx_custom_ui_components_active ON public.custom_ui_components USING btree (is_active);
CREATE INDEX idx_custom_ui_components_name ON public.custom_ui_components USING btree (name);
CREATE INDEX idx_custom_ui_components_type ON public.custom_ui_components USING btree (component_type);
CREATE INDEX idx_custom_ui_templates_name ON public.custom_ui_templates USING btree (name);
CREATE INDEX idx_deliveries_courier ON public.deliveries USING btree (courier_id, status);
CREATE INDEX idx_deliveries_order ON public.deliveries USING btree (order_id);
CREATE INDEX idx_deliveries_status ON public.deliveries USING btree (status) WHERE ((status)::text = ANY ((ARRAY['assigned'::character varying, 'accepted'::character varying, 'picked_up'::character varying, 'in_transit'::character varying])::text[]));
CREATE INDEX idx_deliveries_tracking_token ON public.deliveries USING btree (tracking_token);
CREATE INDEX idx_delivery_is_active ON public.storefront_delivery_options USING btree (is_active);
CREATE INDEX idx_delivery_storefront_id ON public.storefront_delivery_options USING btree (storefront_id);
CREATE INDEX idx_density_grid_cell ON public.gis_listing_density_grid USING gist (cell);
CREATE INDEX idx_density_grid_density ON public.gis_listing_density_grid USING btree (density);
CREATE INDEX idx_disputes_review_id ON public.review_disputes USING btree (review_id);
CREATE INDEX idx_disputes_status ON public.review_disputes USING btree (status);
CREATE INDEX idx_districts_boundary ON public.districts USING gist (boundary);
CREATE INDEX idx_districts_center ON public.districts USING gist (center_point);
CREATE INDEX idx_districts_city_id ON public.districts USING btree (city_id);
CREATE INDEX idx_districts_country ON public.districts USING btree (country_code);
CREATE INDEX idx_districts_name ON public.districts USING btree (name);
CREATE INDEX idx_escrow_payments_buyer_id ON public.escrow_payments USING btree (buyer_id);
CREATE INDEX idx_escrow_payments_payment_transaction_id ON public.escrow_payments USING btree (payment_transaction_id);
CREATE INDEX idx_escrow_payments_seller_id ON public.escrow_payments USING btree (seller_id);
CREATE INDEX idx_escrow_payments_status ON public.escrow_payments USING btree (status);
CREATE INDEX idx_filter_analytics_created ON public.gis_filter_analytics USING btree (created_at);
CREATE INDEX idx_filter_analytics_type ON public.gis_filter_analytics USING btree (filter_type);
CREATE INDEX idx_filter_analytics_user ON public.gis_filter_analytics USING btree (user_id);
CREATE INDEX idx_geocoding_cache_address_components ON public.geocoding_cache USING gin (address_components);
CREATE INDEX idx_geocoding_cache_cache_hits ON public.geocoding_cache USING btree (cache_hits);
CREATE INDEX idx_geocoding_cache_confidence ON public.geocoding_cache USING btree (confidence);
CREATE INDEX idx_geocoding_cache_country_lang ON public.geocoding_cache USING btree (country_code, language);
CREATE INDEX idx_geocoding_cache_expires_at ON public.geocoding_cache USING btree (expires_at);
CREATE INDEX idx_geocoding_cache_input_address ON public.geocoding_cache USING btree (input_address);
CREATE INDEX idx_geocoding_cache_normalized ON public.geocoding_cache USING btree (normalized_address);
CREATE INDEX idx_geocoding_cache_provider ON public.geocoding_cache USING btree (provider);
CREATE INDEX idx_hours_storefront_id ON public.storefront_hours USING btree (storefront_id);
CREATE INDEX idx_import_history_source ON public.import_history USING btree (source_id);
CREATE INDEX idx_import_sources_storefront ON public.import_sources USING btree (storefront_id);
CREATE INDEX idx_imported_categories_source_id ON public.imported_categories USING btree (source_id);
CREATE INDEX idx_inventory_reservations_expires_at ON public.inventory_reservations USING btree (expires_at);
CREATE INDEX idx_inventory_reservations_order_id ON public.inventory_reservations USING btree (order_id);
CREATE INDEX idx_inventory_reservations_product_id ON public.inventory_reservations USING btree (product_id);
CREATE INDEX idx_inventory_reservations_status ON public.inventory_reservations USING btree (status);
CREATE INDEX idx_inventory_reservations_variant_id ON public.inventory_reservations USING btree (variant_id);
CREATE INDEX idx_isochrone_cache_center ON public.gis_isochrone_cache USING gist (center_point);
CREATE INDEX idx_isochrone_cache_expires ON public.gis_isochrone_cache USING btree (expires_at);
CREATE INDEX idx_isochrone_cache_lookup ON public.gis_isochrone_cache USING btree (transport_mode, max_minutes);
CREATE INDEX idx_item_performance_metrics_conversions ON public.item_performance_metrics USING btree (conversions DESC);
CREATE INDEX idx_item_performance_metrics_ctr ON public.item_performance_metrics USING btree (ctr DESC);
CREATE INDEX idx_item_performance_metrics_impressions ON public.item_performance_metrics USING btree (impressions DESC);
CREATE INDEX idx_item_performance_metrics_item ON public.item_performance_metrics USING btree (item_id, item_type);
CREATE INDEX idx_item_performance_metrics_period ON public.item_performance_metrics USING btree (period_start, period_end);
CREATE UNIQUE INDEX idx_item_performance_metrics_unique ON public.item_performance_metrics USING btree (item_id, period_start);
CREATE INDEX idx_keyword_lower ON public.category_keywords USING btree (lower((keyword)::text));
CREATE INDEX idx_keyword_type ON public.category_keywords USING btree (keyword_type);
CREATE INDEX idx_language ON public.category_keywords USING btree (language);
CREATE INDEX idx_listing_attribute_values_attribute ON public.listing_attribute_values USING btree (attribute_id);
CREATE INDEX idx_listing_attribute_values_listing ON public.listing_attribute_values USING btree (listing_id);
CREATE INDEX idx_listing_attribute_values_numeric ON public.listing_attribute_values USING btree (numeric_value) WHERE (numeric_value IS NOT NULL);
CREATE INDEX idx_listing_attribute_values_text ON public.listing_attribute_values USING btree (text_value) WHERE (text_value IS NOT NULL);
CREATE INDEX idx_listing_attribute_values_unit ON public.listing_attribute_values USING btree (unit) WHERE (unit IS NOT NULL);
CREATE INDEX idx_listing_views_listing_ip ON public.listing_views USING btree (listing_id, ip_hash);
CREATE INDEX idx_listing_views_listing_user ON public.listing_views USING btree (listing_id, user_id);
