CREATE INDEX idx_marketplace_categories_parent ON public.marketplace_categories USING btree (parent_id);
CREATE INDEX idx_marketplace_categories_slug ON public.marketplace_categories USING btree (slug);
CREATE INDEX idx_marketplace_chats_active_sorted ON public.marketplace_chats USING btree (last_message_at DESC) WHERE (NOT is_archived);
CREATE INDEX idx_marketplace_chats_archived ON public.marketplace_chats USING btree (is_archived) WHERE (NOT is_archived);
CREATE INDEX idx_marketplace_chats_buyer ON public.marketplace_chats USING btree (buyer_id);
CREATE INDEX idx_marketplace_chats_listing ON public.marketplace_chats USING btree (listing_id) WHERE (listing_id IS NOT NULL);
CREATE INDEX idx_marketplace_chats_listing_participants ON public.marketplace_chats USING btree (listing_id, buyer_id, seller_id) WHERE (listing_id IS NOT NULL);
CREATE INDEX idx_marketplace_chats_participants ON public.marketplace_chats USING btree (LEAST(buyer_id, seller_id), GREATEST(buyer_id, seller_id));
CREATE INDEX idx_marketplace_chats_seller ON public.marketplace_chats USING btree (seller_id);
CREATE INDEX idx_marketplace_chats_storefront_product_id ON public.marketplace_chats USING btree (storefront_product_id);
CREATE INDEX idx_marketplace_chats_updated ON public.marketplace_chats USING btree (updated_at);
CREATE INDEX idx_marketplace_chats_user_lookup ON public.marketplace_chats USING btree (buyer_id, seller_id, last_message_at DESC);
CREATE INDEX idx_marketplace_favorites_listing ON public.marketplace_favorites USING btree (listing_id);
CREATE INDEX idx_marketplace_favorites_user_count ON public.marketplace_favorites USING btree (user_id, created_at DESC);
CREATE INDEX idx_marketplace_images_listing_main ON public.marketplace_images USING btree (listing_id, is_main) WHERE (is_main = true);
CREATE INDEX idx_marketplace_listing_variants_attributes ON public.marketplace_listing_variants USING gin (attributes);
CREATE INDEX idx_marketplace_listing_variants_is_active ON public.marketplace_listing_variants USING btree (is_active);
CREATE INDEX idx_marketplace_listing_variants_listing_id ON public.marketplace_listing_variants USING btree (listing_id);
CREATE INDEX idx_marketplace_listing_variants_sku ON public.marketplace_listing_variants USING btree (sku);
CREATE INDEX idx_marketplace_listings_address_multilingual ON public.marketplace_listings USING gin (address_multilingual);
CREATE INDEX idx_marketplace_listings_category_status ON public.marketplace_listings USING btree (category_id, status) WHERE ((status)::text = 'active'::text);
CREATE INDEX idx_marketplace_listings_city ON public.marketplace_listings USING btree (address_city) WHERE (address_city IS NOT NULL);
CREATE INDEX idx_marketplace_listings_created_at_desc ON public.marketplace_listings USING btree (created_at DESC) WHERE ((status)::text = 'active'::text);
CREATE INDEX idx_marketplace_listings_description_trgm ON public.marketplace_listings USING gin (description public.gin_trgm_ops);
CREATE INDEX idx_marketplace_listings_external_id ON public.marketplace_listings USING btree (external_id);
CREATE INDEX idx_marketplace_listings_external_id_storefront_id ON public.marketplace_listings USING btree (external_id, storefront_id);
CREATE INDEX idx_marketplace_listings_price ON public.marketplace_listings USING btree (price) WHERE ((price IS NOT NULL) AND ((status)::text = 'active'::text));
CREATE INDEX idx_marketplace_listings_status ON public.marketplace_listings USING btree (status);
CREATE INDEX idx_marketplace_listings_status_category ON public.marketplace_listings USING btree (status, category_id) WHERE ((status)::text = 'active'::text);
CREATE INDEX idx_marketplace_listings_status_created ON public.marketplace_listings USING btree (status, created_at DESC) WHERE ((status)::text = 'active'::text);
CREATE INDEX idx_marketplace_listings_storefront ON public.marketplace_listings USING btree (storefront_id);
CREATE INDEX idx_marketplace_listings_title_gin ON public.marketplace_listings USING gin (to_tsvector('simple'::regconfig, (title)::text));
CREATE INDEX idx_marketplace_listings_title_trgm ON public.marketplace_listings USING gin (title public.gin_trgm_ops);
CREATE INDEX idx_marketplace_listings_user_status ON public.marketplace_listings USING btree (user_id, status, created_at DESC);
CREATE INDEX idx_marketplace_messages_chat ON public.marketplace_messages USING btree (chat_id);
CREATE INDEX idx_marketplace_messages_chat_last ON public.marketplace_messages USING btree (chat_id, id DESC);
CREATE INDEX idx_marketplace_messages_chat_ordered ON public.marketplace_messages USING btree (chat_id, created_at DESC);
CREATE INDEX idx_marketplace_messages_chat_unread ON public.marketplace_messages USING btree (chat_id, receiver_id) WHERE (NOT is_read);
CREATE INDEX idx_marketplace_messages_created ON public.marketplace_messages USING btree (created_at);
CREATE INDEX idx_marketplace_messages_listing ON public.marketplace_messages USING btree (listing_id);
CREATE INDEX idx_marketplace_messages_receiver ON public.marketplace_messages USING btree (receiver_id);
CREATE INDEX idx_marketplace_messages_receiver_unread_count ON public.marketplace_messages USING btree (receiver_id, chat_id) WHERE (NOT is_read);
CREATE INDEX idx_marketplace_messages_sender ON public.marketplace_messages USING btree (sender_id);
CREATE INDEX idx_marketplace_messages_storefront_product_id ON public.marketplace_messages USING btree (storefront_product_id) WHERE (storefront_product_id IS NOT NULL);
CREATE INDEX idx_marketplace_messages_translations ON public.marketplace_messages USING gin (translations);
CREATE INDEX idx_marketplace_messages_unread ON public.marketplace_messages USING btree (receiver_id, is_read) WHERE (NOT is_read);
CREATE INDEX idx_marketplace_orders_buyer ON public.marketplace_orders USING btree (buyer_id);
CREATE INDEX idx_marketplace_orders_buyer_id ON public.marketplace_orders USING btree (buyer_id);
CREATE INDEX idx_marketplace_orders_created_at ON public.marketplace_orders USING btree (created_at DESC);
CREATE INDEX idx_marketplace_orders_listing ON public.marketplace_orders USING btree (listing_id);
CREATE INDEX idx_marketplace_orders_listing_id ON public.marketplace_orders USING btree (listing_id);
CREATE INDEX idx_marketplace_orders_payment_transaction_id ON public.marketplace_orders USING btree (payment_transaction_id);
CREATE INDEX idx_marketplace_orders_protection_expires_at ON public.marketplace_orders USING btree (protection_expires_at) WHERE (protection_expires_at IS NOT NULL);
CREATE INDEX idx_marketplace_orders_seller ON public.marketplace_orders USING btree (seller_id);
CREATE INDEX idx_marketplace_orders_seller_id ON public.marketplace_orders USING btree (seller_id);
CREATE INDEX idx_marketplace_orders_status ON public.marketplace_orders USING btree (status);
CREATE INDEX idx_merchant_payouts_gateway_payout_id ON public.merchant_payouts USING btree (gateway_payout_id);
CREATE INDEX idx_merchant_payouts_seller_id ON public.merchant_payouts USING btree (seller_id);
CREATE INDEX idx_merchant_payouts_status ON public.merchant_payouts USING btree (status);
CREATE INDEX idx_municipalities_boundary ON public.municipalities USING gist (boundary);
CREATE INDEX idx_municipalities_center ON public.municipalities USING gist (center_point);
CREATE INDEX idx_municipalities_district ON public.municipalities USING btree (district_id);
CREATE INDEX idx_municipalities_name ON public.municipalities USING btree (name);
CREATE UNIQUE INDEX idx_mv_category_statistics_id ON public.mv_category_statistics USING btree (category_id);
CREATE UNIQUE INDEX idx_mv_popular_category_attrs_pk ON public.mv_popular_category_attributes USING btree (category_id, attribute_id);
CREATE INDEX idx_notifications_created ON public.notifications USING btree (created_at);
CREATE INDEX idx_notifications_type ON public.notifications USING btree (type);
CREATE INDEX idx_notifications_user ON public.notifications USING btree (user_id);
CREATE INDEX idx_notifications_user_unread ON public.notifications USING btree (user_id, created_at DESC) WHERE (NOT is_read);
CREATE INDEX idx_payment_is_enabled ON public.storefront_payment_methods USING btree (is_enabled);
CREATE INDEX idx_payment_storefront_id ON public.storefront_payment_methods USING btree (storefront_id);
CREATE INDEX idx_payment_transactions_auto_capture ON public.payment_transactions USING btree (auto_capture_at, status) WHERE (((status)::text = 'authorized'::text) AND ((capture_mode)::text = 'auto'::text));
CREATE INDEX idx_payment_transactions_created_at ON public.payment_transactions USING btree (created_at);
CREATE INDEX idx_payment_transactions_gateway_transaction_id ON public.payment_transactions USING btree (gateway_transaction_id);
CREATE INDEX idx_payment_transactions_listing_id ON public.payment_transactions USING btree (listing_id);
CREATE INDEX idx_payment_transactions_order_reference ON public.payment_transactions USING btree (order_reference);
CREATE INDEX idx_payment_transactions_source ON public.payment_transactions USING btree (source_type, source_id);
CREATE INDEX idx_payment_transactions_status ON public.payment_transactions USING btree (status);
CREATE INDEX idx_payment_transactions_user_id ON public.payment_transactions USING btree (user_id);
CREATE INDEX idx_poi_cache_expires ON public.gis_poi_cache USING btree (expires_at);
CREATE INDEX idx_poi_cache_type ON public.gis_poi_cache USING btree (poi_type);
CREATE INDEX idx_post_express_locations_name ON public.post_express_locations USING btree (name);
CREATE INDEX idx_post_express_locations_postal_code ON public.post_express_locations USING btree (postal_code);
CREATE INDEX idx_post_express_offices_is_active ON public.post_express_offices USING btree (is_active);
CREATE INDEX idx_post_express_offices_location_id ON public.post_express_offices USING btree (location_id);
CREATE INDEX idx_post_express_shipments_marketplace_order_id ON public.post_express_shipments USING btree (marketplace_order_id);
CREATE INDEX idx_post_express_shipments_status ON public.post_express_shipments USING btree (status);
CREATE INDEX idx_post_express_shipments_storefront_order_id ON public.post_express_shipments USING btree (storefront_order_id);
CREATE INDEX idx_post_express_shipments_tracking_number ON public.post_express_shipments USING btree (tracking_number);
CREATE INDEX idx_post_express_tracking_events_shipment_id ON public.post_express_tracking_events USING btree (shipment_id);
CREATE INDEX idx_post_express_tracking_events_timestamp ON public.post_express_tracking_events USING btree (event_timestamp);
CREATE INDEX idx_price_history_current ON public.price_history USING btree (listing_id, effective_from DESC) WHERE (effective_to IS NULL);
CREATE INDEX idx_price_history_effective ON public.price_history USING btree (listing_id, effective_to);
CREATE INDEX idx_price_history_listing_id ON public.price_history USING btree (listing_id);
CREATE INDEX idx_product_variant_attribute_values_attribute_id ON public.product_variant_attribute_values USING btree (attribute_id);
CREATE INDEX idx_product_variant_attribute_values_value ON public.product_variant_attribute_values USING btree (value);
CREATE INDEX idx_product_variant_attributes_affects_stock ON public.product_variant_attributes USING btree (affects_stock) WHERE (affects_stock = true);
CREATE INDEX idx_product_variant_attributes_name ON public.product_variant_attributes USING btree (name);
CREATE INDEX idx_providers_active ON public.translation_providers USING btree (is_active, priority) WHERE (is_active = true);
CREATE INDEX idx_quality_metrics_issues ON public.translation_quality_metrics USING btree (has_placeholders, has_html_tags);
