CREATE INDEX idx_ai_decisions_entity_type ON public.ai_category_decisions USING btree (entity_type, created_at DESC);
CREATE INDEX idx_ai_decisions_title_hash ON public.ai_category_decisions USING btree (title_hash);
CREATE UNIQUE INDEX idx_ai_decisions_unique_title_hash ON public.ai_category_decisions USING btree (title_hash);
CREATE INDEX idx_ai_decisions_user_confirmed ON public.ai_category_decisions USING btree (user_confirmed) WHERE (user_confirmed = true);
CREATE INDEX idx_ai_mappings_active ON public.category_ai_mappings USING btree (is_active) WHERE (is_active = true);
CREATE INDEX idx_ai_mappings_category ON public.category_ai_mappings USING btree (category_id);
CREATE INDEX idx_ai_mappings_domain_type ON public.category_ai_mappings USING btree (ai_domain, product_type);
CREATE INDEX idx_attribute_group_items_attribute ON public.attribute_group_items USING btree (attribute_id);
CREATE INDEX idx_attribute_group_items_group ON public.attribute_group_items USING btree (group_id);
CREATE INDEX idx_attribute_option_translations ON public.attribute_option_translations USING btree (attribute_name, option_value);
CREATE INDEX idx_audit_log_entity ON public.translation_audit_log USING btree (entity_type, entity_id);
CREATE INDEX idx_audit_log_user_date ON public.translation_audit_log USING btree (user_id, created_at DESC);
CREATE INDEX idx_bex_shipments_created_at ON public.bex_shipments USING btree (created_at DESC);
CREATE INDEX idx_bex_shipments_marketplace_order_id ON public.bex_shipments USING btree (marketplace_order_id);
CREATE INDEX idx_bex_shipments_order_id ON public.bex_shipments USING btree (order_id);
CREATE INDEX idx_bex_shipments_storefront_order_id ON public.bex_shipments USING btree (storefront_order_id);
CREATE INDEX idx_bex_shipments_tracking_number ON public.bex_shipments USING btree (tracking_number);
CREATE INDEX idx_bex_tracking_events_date ON public.bex_tracking_events USING btree (event_date DESC);
CREATE INDEX idx_bex_tracking_events_shipment_id ON public.bex_tracking_events USING btree (shipment_id);
CREATE INDEX idx_car_generations_active ON public.car_generations USING btree (is_active) WHERE (is_active = true);
CREATE INDEX idx_car_generations_model_id ON public.car_generations USING btree (model_id);
CREATE INDEX idx_car_generations_slug ON public.car_generations USING btree (slug);
CREATE INDEX idx_car_generations_years ON public.car_generations USING btree (year_start, year_end);
CREATE INDEX idx_car_makes_external_id ON public.car_makes USING btree (external_id);
CREATE INDEX idx_car_makes_is_domestic ON public.car_makes USING btree (is_domestic);
CREATE INDEX idx_car_makes_popularity ON public.car_makes USING btree (popularity_rs DESC);
CREATE INDEX idx_car_makes_slug ON public.car_makes USING btree (slug);
CREATE INDEX idx_car_models_battery_capacity ON public.car_models USING btree (battery_capacity_kwh) WHERE (battery_capacity_kwh IS NOT NULL);
CREATE INDEX idx_car_models_body_type ON public.car_models USING btree (body_type);
CREATE INDEX idx_car_models_drive_type ON public.car_models USING btree (drive_type);
CREATE INDEX idx_car_models_engine_type ON public.car_models USING btree (engine_type);
CREATE INDEX idx_car_models_external_id ON public.car_models USING btree (external_id);
CREATE INDEX idx_car_models_fuel_type ON public.car_models USING btree (fuel_type);
CREATE INDEX idx_car_models_is_electric ON public.car_models USING btree (is_electric) WHERE (is_electric = true);
CREATE INDEX idx_car_models_make_slug ON public.car_models USING btree (make_id, slug);
CREATE INDEX idx_car_models_search ON public.car_models USING gin (to_tsvector('simple'::regconfig, (name)::text));
CREATE INDEX idx_car_models_serbia_popularity ON public.car_models USING btree (serbia_popularity_score DESC);
CREATE INDEX idx_car_models_transmission_type ON public.car_models USING btree (transmission_type);
CREATE INDEX idx_category_ai_mappings_domain_type ON public.category_ai_mappings USING btree (ai_domain, product_type);
CREATE INDEX idx_category_attr_mapping ON public.category_attribute_mapping USING btree (category_id, is_enabled) WHERE (is_enabled = true);
CREATE INDEX idx_category_attribute_groups_category ON public.category_attribute_groups USING btree (category_id);
CREATE INDEX idx_category_attribute_groups_component ON public.category_attribute_groups USING btree (component_id);
CREATE INDEX idx_category_attribute_groups_group ON public.category_attribute_groups USING btree (group_id);
CREATE INDEX idx_category_attribute_map_attr_id ON public.category_attribute_mapping USING btree (attribute_id);
CREATE INDEX idx_category_attribute_map_cat_id ON public.category_attribute_mapping USING btree (category_id);
CREATE INDEX idx_category_attribute_mapping_custom_component ON public.category_attribute_mapping USING btree (custom_component);
CREATE INDEX idx_category_keyword_weights_keyword_lang ON public.category_keyword_weights USING btree (keyword, language);
CREATE INDEX idx_category_variant_attributes_category_id ON public.category_variant_attributes USING btree (category_id);
CREATE INDEX idx_category_variant_attributes_variant_name ON public.category_variant_attributes USING btree (variant_attribute_name);
CREATE INDEX idx_category_weight ON public.category_keywords USING btree (category_id, weight DESC);
CREATE INDEX idx_chat_attachments_created_at ON public.chat_attachments USING btree (created_at);
CREATE INDEX idx_chat_attachments_file_type ON public.chat_attachments USING btree (file_type);
CREATE INDEX idx_chat_attachments_message ON public.chat_attachments USING btree (message_id);
CREATE INDEX idx_chat_attachments_message_id ON public.chat_attachments USING btree (message_id);
CREATE INDEX idx_cities_boundary ON public.cities USING gist (boundary);
CREATE INDEX idx_cities_center ON public.cities USING gist (center_point);
CREATE INDEX idx_cities_country ON public.cities USING btree (country_code);
CREATE INDEX idx_cities_has_districts ON public.cities USING btree (has_districts);
CREATE INDEX idx_cities_name ON public.cities USING btree (name);
CREATE INDEX idx_cities_priority ON public.cities USING btree (priority);
CREATE INDEX idx_cities_slug ON public.cities USING btree (slug);
CREATE INDEX idx_component_templates_cat ON public.component_templates USING btree (category_id);
CREATE INDEX idx_component_templates_comp ON public.component_templates USING btree (component_id);
CREATE INDEX idx_couriers_online_available ON public.couriers USING btree (is_online, is_available) WHERE ((is_online = true) AND (is_available = true));
CREATE INDEX idx_couriers_user_id ON public.couriers USING btree (user_id);
CREATE INDEX idx_custom_ui_components_active ON public.custom_ui_components USING btree (is_active);
CREATE INDEX idx_custom_ui_components_name ON public.custom_ui_components USING btree (name);
CREATE INDEX idx_custom_ui_components_type ON public.custom_ui_components USING btree (component_type);
CREATE INDEX idx_custom_ui_templates_name ON public.custom_ui_templates USING btree (name);
CREATE INDEX idx_deliveries_courier ON public.deliveries USING btree (courier_id, status);
CREATE INDEX idx_deliveries_order ON public.deliveries USING btree (order_id);
CREATE INDEX idx_deliveries_status ON public.deliveries USING btree (status) WHERE ((status)::text = ANY ((ARRAY['assigned'::character varying, 'accepted'::character varying, 'picked_up'::character varying, 'in_transit'::character varying])::text[]));
CREATE INDEX idx_deliveries_tracking_token ON public.deliveries USING btree (tracking_token);
CREATE INDEX idx_delivery_category_defaults_category ON public.delivery_category_defaults USING btree (category_id);
CREATE INDEX idx_delivery_is_active ON public.storefront_delivery_options USING btree (is_active);
CREATE INDEX idx_delivery_notifications_channel ON public.delivery_notifications USING btree (channel);
CREATE INDEX idx_delivery_notifications_created ON public.delivery_notifications USING btree (created_at);
CREATE INDEX idx_delivery_notifications_shipment ON public.delivery_notifications USING btree (shipment_id);
CREATE INDEX idx_delivery_notifications_status ON public.delivery_notifications USING btree (status);
CREATE INDEX idx_delivery_notifications_user ON public.delivery_notifications USING btree (user_id);
CREATE INDEX idx_delivery_pricing_rules_active ON public.delivery_pricing_rules USING btree (is_active) WHERE (is_active = true);
CREATE INDEX idx_delivery_pricing_rules_provider ON public.delivery_pricing_rules USING btree (provider_id);
CREATE INDEX idx_delivery_shipments_order ON public.delivery_shipments USING btree (order_id);
CREATE INDEX idx_delivery_shipments_status ON public.delivery_shipments USING btree (status);
CREATE INDEX idx_delivery_shipments_tracking ON public.delivery_shipments USING btree (tracking_number);
CREATE INDEX idx_delivery_storefront_id ON public.storefront_delivery_options USING btree (storefront_id);
CREATE INDEX idx_delivery_tracking_events_shipment ON public.delivery_tracking_events USING btree (shipment_id);
CREATE INDEX idx_delivery_tracking_events_time ON public.delivery_tracking_events USING btree (event_time);
CREATE INDEX idx_delivery_zones_boundary ON public.delivery_zones USING gist (boundary);
CREATE INDEX idx_delivery_zones_center ON public.delivery_zones USING gist (center_point);
CREATE INDEX idx_density_grid_cell ON public.gis_listing_density_grid USING gist (cell);
CREATE INDEX idx_density_grid_density ON public.gis_listing_density_grid USING btree (density);
CREATE INDEX idx_detection_cache_expires ON public.category_detection_cache USING btree (expires_at);
CREATE INDEX idx_detection_cache_key ON public.category_detection_cache USING btree (cache_key);
CREATE INDEX idx_disputes_review_id ON public.review_disputes USING btree (review_id);
CREATE INDEX idx_disputes_status ON public.review_disputes USING btree (status);
CREATE INDEX idx_districts_boundary ON public.districts USING gist (boundary);
CREATE INDEX idx_districts_center ON public.districts USING gist (center_point);
CREATE INDEX idx_districts_city_id ON public.districts USING btree (city_id);
CREATE INDEX idx_districts_country ON public.districts USING btree (country_code);
