CREATE INDEX idx_bex_places_postal_code ON public.bex_places USING btree (postal_code);
CREATE INDEX idx_bex_rates_active ON public.bex_rates USING btree (is_active) WHERE (is_active = true);
CREATE INDEX idx_bex_rates_weight ON public.bex_rates USING btree (weight_from, weight_to);
CREATE INDEX idx_bex_shipments_bex_id ON public.bex_shipments USING btree (bex_shipment_id);
CREATE INDEX idx_bex_shipments_created ON public.bex_shipments USING btree (created_at DESC);
CREATE INDEX idx_bex_shipments_marketplace_order ON public.bex_shipments USING btree (marketplace_order_id);
CREATE INDEX idx_bex_shipments_recipient_phone ON public.bex_shipments USING btree (recipient_phone);
CREATE INDEX idx_bex_shipments_status ON public.bex_shipments USING btree (status);
CREATE INDEX idx_bex_shipments_storefront_order ON public.bex_shipments USING btree (storefront_order_id);
CREATE INDEX idx_bex_shipments_tracking ON public.bex_shipments USING btree (tracking_number);
CREATE INDEX idx_bex_streets_active ON public.bex_streets USING btree (is_active) WHERE (is_active = true);
CREATE INDEX idx_bex_streets_bex_id ON public.bex_streets USING btree (bex_id);
CREATE INDEX idx_bex_streets_name ON public.bex_streets USING btree (name);
CREATE INDEX idx_bex_streets_name_cyrillic ON public.bex_streets USING btree (name_cyrillic);
CREATE INDEX idx_bex_streets_name_cyrillic_trgm ON public.bex_streets USING gin (name_cyrillic public.gin_trgm_ops);
CREATE INDEX idx_bex_streets_name_trgm ON public.bex_streets USING gin (name public.gin_trgm_ops);
CREATE INDEX idx_bex_streets_place_id ON public.bex_streets USING btree (place_id);
CREATE INDEX idx_bex_tracking_shipment ON public.bex_tracking_events USING btree (shipment_id);
CREATE INDEX idx_bex_tracking_timestamp ON public.bex_tracking_events USING btree (event_timestamp DESC);
CREATE INDEX idx_car_generations_active ON public.car_generations USING btree (is_active) WHERE (is_active = true);
CREATE INDEX idx_car_generations_model_id ON public.car_generations USING btree (model_id);
CREATE INDEX idx_car_generations_slug ON public.car_generations USING btree (slug);
CREATE INDEX idx_car_generations_years ON public.car_generations USING btree (year_start, year_end);
CREATE INDEX idx_car_makes_external_id ON public.car_makes USING btree (external_id);
CREATE INDEX idx_car_makes_is_domestic ON public.car_makes USING btree (is_domestic);
CREATE INDEX idx_car_makes_popularity ON public.car_makes USING btree (popularity_rs DESC);
CREATE INDEX idx_car_makes_slug ON public.car_makes USING btree (slug);
CREATE INDEX idx_car_models_battery_capacity ON public.car_models USING btree (battery_capacity_kwh) WHERE (battery_capacity_kwh IS NOT NULL);
CREATE INDEX idx_car_models_body_type ON public.car_models USING btree (body_type);
CREATE INDEX idx_car_models_drive_type ON public.car_models USING btree (drive_type);
CREATE INDEX idx_car_models_engine_type ON public.car_models USING btree (engine_type);
CREATE INDEX idx_car_models_external_id ON public.car_models USING btree (external_id);
CREATE INDEX idx_car_models_fuel_type ON public.car_models USING btree (fuel_type);
CREATE INDEX idx_car_models_is_electric ON public.car_models USING btree (is_electric) WHERE (is_electric = true);
CREATE INDEX idx_car_models_make_slug ON public.car_models USING btree (make_id, slug);
CREATE INDEX idx_car_models_search ON public.car_models USING gin (to_tsvector('simple'::regconfig, (name)::text));
CREATE INDEX idx_car_models_serbia_popularity ON public.car_models USING btree (serbia_popularity_score DESC);
CREATE INDEX idx_car_models_transmission_type ON public.car_models USING btree (transmission_type);
CREATE INDEX idx_category_attr_mapping ON public.category_attribute_mapping USING btree (category_id, is_enabled) WHERE (is_enabled = true);
CREATE INDEX idx_category_attribute_groups_category ON public.category_attribute_groups USING btree (category_id);
CREATE INDEX idx_category_attribute_groups_component ON public.category_attribute_groups USING btree (component_id);
CREATE INDEX idx_category_attribute_groups_group ON public.category_attribute_groups USING btree (group_id);
CREATE INDEX idx_category_attribute_map_attr_id ON public.category_attribute_mapping USING btree (attribute_id);
CREATE INDEX idx_category_attribute_map_cat_id ON public.category_attribute_mapping USING btree (category_id);
CREATE INDEX idx_category_attribute_mapping_custom_component ON public.category_attribute_mapping USING btree (custom_component);
CREATE INDEX idx_category_attributes_data_source ON public.category_attributes USING btree (data_source);
CREATE INDEX idx_category_attributes_name ON public.category_attributes USING btree (name);
CREATE INDEX idx_category_attributes_variant_compatible ON public.category_attributes USING btree (is_variant_compatible) WHERE (is_variant_compatible = true);
CREATE INDEX idx_category_variant_attributes_category_id ON public.category_variant_attributes USING btree (category_id);
CREATE INDEX idx_category_variant_attributes_variant_name ON public.category_variant_attributes USING btree (variant_attribute_name);
CREATE INDEX idx_category_weight ON public.category_keywords USING btree (category_id, weight DESC);
CREATE INDEX idx_chat_attachments_created_at ON public.chat_attachments USING btree (created_at);
CREATE INDEX idx_chat_attachments_file_type ON public.chat_attachments USING btree (file_type);
CREATE INDEX idx_chat_attachments_message ON public.chat_attachments USING btree (message_id);
CREATE INDEX idx_chat_attachments_message_id ON public.chat_attachments USING btree (message_id);
CREATE INDEX idx_cities_boundary ON public.cities USING gist (boundary);
CREATE INDEX idx_cities_center ON public.cities USING gist (center_point);
CREATE INDEX idx_cities_country ON public.cities USING btree (country_code);
CREATE INDEX idx_cities_has_districts ON public.cities USING btree (has_districts);
CREATE INDEX idx_cities_name ON public.cities USING btree (name);
CREATE INDEX idx_cities_priority ON public.cities USING btree (priority);
CREATE INDEX idx_cities_slug ON public.cities USING btree (slug);
CREATE INDEX idx_component_templates_cat ON public.component_templates USING btree (category_id);
CREATE INDEX idx_component_templates_comp ON public.component_templates USING btree (component_id);
CREATE INDEX idx_custom_ui_components_active ON public.custom_ui_components USING btree (is_active);
CREATE INDEX idx_custom_ui_components_name ON public.custom_ui_components USING btree (name);
CREATE INDEX idx_custom_ui_components_type ON public.custom_ui_components USING btree (component_type);
CREATE INDEX idx_custom_ui_templates_name ON public.custom_ui_templates USING btree (name);
CREATE INDEX idx_delivery_is_active ON public.storefront_delivery_options USING btree (is_active);
CREATE INDEX idx_delivery_storefront_id ON public.storefront_delivery_options USING btree (storefront_id);
CREATE INDEX idx_density_grid_cell ON public.gis_listing_density_grid USING gist (cell);
CREATE INDEX idx_density_grid_density ON public.gis_listing_density_grid USING btree (density);
CREATE INDEX idx_disputes_review_id ON public.review_disputes USING btree (review_id);
CREATE INDEX idx_disputes_status ON public.review_disputes USING btree (status);
CREATE INDEX idx_districts_boundary ON public.districts USING gist (boundary);
CREATE INDEX idx_districts_center ON public.districts USING gist (center_point);
CREATE INDEX idx_districts_city_id ON public.districts USING btree (city_id);
CREATE INDEX idx_districts_country ON public.districts USING btree (country_code);
CREATE INDEX idx_districts_name ON public.districts USING btree (name);
CREATE INDEX idx_escrow_payments_buyer_id ON public.escrow_payments USING btree (buyer_id);
CREATE INDEX idx_escrow_payments_payment_transaction_id ON public.escrow_payments USING btree (payment_transaction_id);
CREATE INDEX idx_escrow_payments_seller_id ON public.escrow_payments USING btree (seller_id);
CREATE INDEX idx_escrow_payments_status ON public.escrow_payments USING btree (status);
CREATE INDEX idx_failed_webhooks_created_at ON public.failed_webhooks USING btree (created_at);
CREATE INDEX idx_failed_webhooks_next_retry_at ON public.failed_webhooks USING btree (next_retry_at) WHERE ((status)::text = ANY ((ARRAY['pending'::character varying, 'retrying'::character varying])::text[]));
CREATE INDEX idx_failed_webhooks_status ON public.failed_webhooks USING btree (status);
CREATE INDEX idx_failed_webhooks_webhook_type ON public.failed_webhooks USING btree (webhook_type);
CREATE INDEX idx_filter_analytics_created ON public.gis_filter_analytics USING btree (created_at);
CREATE INDEX idx_filter_analytics_type ON public.gis_filter_analytics USING btree (filter_type);
CREATE INDEX idx_filter_analytics_user ON public.gis_filter_analytics USING btree (user_id);
CREATE INDEX idx_geocoding_cache_address_components ON public.geocoding_cache USING gin (address_components);
CREATE INDEX idx_geocoding_cache_cache_hits ON public.geocoding_cache USING btree (cache_hits);
CREATE INDEX idx_geocoding_cache_confidence ON public.geocoding_cache USING btree (confidence);
CREATE INDEX idx_geocoding_cache_country_lang ON public.geocoding_cache USING btree (country_code, language);
CREATE INDEX idx_geocoding_cache_expires_at ON public.geocoding_cache USING btree (expires_at);
CREATE INDEX idx_geocoding_cache_input_address ON public.geocoding_cache USING btree (input_address);
CREATE INDEX idx_geocoding_cache_normalized ON public.geocoding_cache USING btree (normalized_address);
CREATE INDEX idx_geocoding_cache_provider ON public.geocoding_cache USING btree (provider);
CREATE INDEX idx_hours_storefront_id ON public.storefront_hours USING btree (storefront_id);
CREATE INDEX idx_import_history_source ON public.import_history USING btree (source_id);
