CREATE INDEX idx_search_weights_history_weight_id ON public.search_weights_history USING btree (weight_id);
CREATE INDEX idx_search_weights_is_active ON public.search_weights USING btree (is_active) WHERE (is_active = true);
CREATE INDEX idx_search_weights_item_type ON public.search_weights USING btree (item_type);
CREATE UNIQUE INDEX idx_search_weights_unique_category ON public.search_weights USING btree (field_name, item_type, search_type, category_id) WHERE (category_id IS NOT NULL);
CREATE UNIQUE INDEX idx_search_weights_unique_global ON public.search_weights USING btree (field_name, item_type, search_type) WHERE (category_id IS NULL);
CREATE INDEX idx_shopping_cart_items_cart_id ON public.shopping_cart_items USING btree (cart_id);
CREATE INDEX idx_shopping_cart_items_product_id ON public.shopping_cart_items USING btree (product_id);
CREATE INDEX idx_shopping_carts_session_id ON public.shopping_carts USING btree (session_id);
CREATE INDEX idx_shopping_carts_storefront_id ON public.shopping_carts USING btree (storefront_id);
CREATE INDEX idx_shopping_carts_user_id ON public.shopping_carts USING btree (user_id);
CREATE INDEX idx_storefront_import_errors_job_id ON public.import_errors USING btree (job_id);
CREATE INDEX idx_storefront_import_jobs_created_at ON public.import_jobs USING btree (created_at DESC);
CREATE INDEX idx_storefront_import_jobs_status ON public.import_jobs USING btree (status);
CREATE INDEX idx_storefront_import_jobs_storefront_id ON public.import_jobs USING btree (storefront_id);
CREATE INDEX idx_storefront_import_jobs_user_id ON public.import_jobs USING btree (user_id);
CREATE INDEX idx_sync_conflicts_dates ON public.translation_sync_conflicts USING btree (created_at DESC);
CREATE INDEX idx_sync_conflicts_unresolved ON public.translation_sync_conflicts USING btree (resolved) WHERE (resolved = false);
CREATE INDEX idx_tracking_sessions_active ON public.viber_tracking_sessions USING btree (delivery_id, is_active) WHERE (is_active = true);
CREATE INDEX idx_transactions_created ON public.balance_transactions USING btree (created_at);
CREATE INDEX idx_transactions_status ON public.balance_transactions USING btree (status);
CREATE INDEX idx_transactions_user ON public.balance_transactions USING btree (user_id);
CREATE INDEX idx_translation_tasks_assigned ON public.translation_tasks USING btree (assigned_to, status);
CREATE INDEX idx_translation_tasks_status ON public.translation_tasks USING btree (status, created_at) WHERE ((status)::text <> 'completed'::text);
CREATE INDEX idx_translations_composite ON public.translations USING btree (entity_type, entity_id, language, field_name) WHERE (is_verified = true);
CREATE INDEX idx_translations_entity_lang_field ON public.translations USING btree (entity_type, language, field_name);
CREATE INDEX idx_translations_listing_all ON public.translations USING btree (entity_id, language) WHERE ((entity_type)::text = 'listing'::text);
CREATE INDEX idx_translations_lookup ON public.translations USING btree (entity_type, entity_id, language);
CREATE INDEX idx_translations_type_lang ON public.translations USING btree (entity_type, language);
CREATE INDEX idx_transliteration_rules_active ON public.transliteration_rules USING btree (language, enabled, priority DESC);
CREATE INDEX idx_transliteration_rules_enabled ON public.transliteration_rules USING btree (enabled);
CREATE INDEX idx_transliteration_rules_language ON public.transliteration_rules USING btree (language);
CREATE INDEX idx_transliteration_rules_priority ON public.transliteration_rules USING btree (priority DESC);
CREATE INDEX idx_transliteration_rules_type ON public.transliteration_rules USING btree (rule_type);
CREATE INDEX idx_unified_attr_stats_attr_id ON public.unified_attribute_stats USING btree (attribute_id);
CREATE INDEX idx_unified_attr_stats_category_id ON public.unified_attribute_stats USING btree (category_id);
CREATE INDEX idx_unified_attr_stats_usage ON public.unified_attribute_stats USING btree (usage_count DESC);
CREATE INDEX idx_unified_attr_values_numeric_ranges ON public.unified_attribute_values USING btree (attribute_id, numeric_value) WHERE (numeric_value IS NOT NULL);
CREATE INDEX idx_unified_attribute_values_attribute ON public.unified_attribute_values USING btree (attribute_id);
CREATE INDEX idx_unified_attribute_values_entity ON public.unified_attribute_values USING btree (entity_type, entity_id);
CREATE INDEX idx_unified_attribute_values_entity_with_type ON public.unified_attribute_values USING btree (entity_type, entity_id, attribute_id) INCLUDE (text_value, numeric_value, boolean_value, date_value);
CREATE INDEX idx_unified_attribute_values_numeric ON public.unified_attribute_values USING btree (numeric_value) WHERE (numeric_value IS NOT NULL);
CREATE INDEX idx_unified_attribute_values_text ON public.unified_attribute_values USING btree (text_value) WHERE (text_value IS NOT NULL);
CREATE INDEX idx_unified_attributes_active ON public.unified_attributes USING btree (is_active);
CREATE INDEX idx_unified_attributes_active_filterable ON public.unified_attributes USING btree (is_active, is_filterable) WHERE ((is_active = true) AND (is_filterable = true));
CREATE INDEX idx_unified_attributes_active_searchable ON public.unified_attributes USING btree (is_active, is_searchable) WHERE ((is_active = true) AND (is_searchable = true));
CREATE INDEX idx_unified_attributes_active_sort ON public.unified_attributes USING btree (is_active, sort_order, name) WHERE (is_active = true);
CREATE INDEX idx_unified_attributes_purpose ON public.unified_attributes USING btree (purpose);
CREATE INDEX idx_unified_attributes_search_vector ON public.unified_attributes USING gin (search_vector);
CREATE INDEX idx_unified_attributes_show_in_card ON public.unified_attributes USING btree (show_in_card) WHERE (show_in_card = true);
CREATE INDEX idx_unified_cat_attrs_composite ON public.unified_category_attributes USING btree (category_id, attribute_id, is_enabled, sort_order) WHERE (is_enabled = true);
CREATE INDEX idx_unified_category_attributes_category ON public.unified_category_attributes USING btree (category_id);
CREATE INDEX idx_unified_category_attributes_enabled ON public.unified_category_attributes USING btree (is_enabled);
CREATE INDEX idx_unified_category_attrs_category_enabled_covering ON public.unified_category_attributes USING btree (category_id, is_enabled, attribute_id, sort_order, is_required) WHERE (is_enabled = true);
CREATE INDEX idx_unified_geo_composite ON public.unified_geo USING btree (source_type, source_id);
CREATE INDEX idx_unified_geo_geohash ON public.unified_geo USING btree (geohash);
CREATE INDEX idx_unified_geo_location_bounds ON public.unified_geo USING gist (location) WHERE (location IS NOT NULL);
CREATE INDEX idx_unified_geo_marketplace_active ON public.unified_geo USING btree (source_id) WHERE (source_type = 'marketplace_listing'::public.geo_source_type);
CREATE INDEX idx_unified_geo_source_id ON public.unified_geo USING btree (source_id);
CREATE INDEX idx_unified_geo_source_type ON public.unified_geo USING btree (source_type);
CREATE INDEX idx_unified_geo_storefront_active ON public.unified_geo USING btree (source_id) WHERE (source_type = 'storefront_product'::public.geo_source_type);
CREATE UNIQUE INDEX idx_unique_keyword_category ON public.category_keywords USING btree (category_id, keyword, language);
CREATE INDEX idx_user_behavior_events_created_at ON public.user_behavior_events USING btree (created_at);
CREATE INDEX idx_user_behavior_events_event_type ON public.user_behavior_events USING btree (event_type);
CREATE INDEX idx_user_behavior_events_item ON public.user_behavior_events USING btree (item_id, item_type) WHERE (item_id IS NOT NULL);
CREATE INDEX idx_user_behavior_events_search_query_type ON public.user_behavior_events USING btree (search_query, event_type) WHERE (search_query IS NOT NULL);
CREATE INDEX idx_user_behavior_events_session_id ON public.user_behavior_events USING btree (session_id);
CREATE INDEX idx_user_behavior_events_user_id ON public.user_behavior_events USING btree (user_id) WHERE (user_id IS NOT NULL);
CREATE INDEX idx_user_car_view_history_listing_id ON public.user_car_view_history USING btree (listing_id);
CREATE INDEX idx_user_car_view_history_session_id ON public.user_car_view_history USING btree (session_id) WHERE (session_id IS NOT NULL);
CREATE INDEX idx_user_car_view_history_user_id ON public.user_car_view_history USING btree (user_id) WHERE (user_id IS NOT NULL);
CREATE INDEX idx_user_car_view_history_viewed_at ON public.user_car_view_history USING btree (viewed_at DESC);
CREATE INDEX idx_user_contacts_contact_user_id ON public.user_contacts USING btree (contact_user_id);
CREATE INDEX idx_user_contacts_created_at ON public.user_contacts USING btree (created_at);
CREATE INDEX idx_user_contacts_status ON public.user_contacts USING btree (status);
CREATE INDEX idx_user_contacts_user_id ON public.user_contacts USING btree (user_id);
CREATE INDEX idx_user_notification_contacts_user ON public.user_notification_contacts USING btree (user_id);
CREATE INDEX idx_user_notification_preferences_user ON public.user_notification_preferences USING btree (user_id);
CREATE INDEX idx_user_privacy_settings_settings ON public.user_privacy_settings USING gin (settings);
CREATE INDEX idx_user_privacy_settings_user_id ON public.user_privacy_settings USING btree (user_id);
CREATE INDEX idx_user_ratings_average ON public.user_ratings USING btree (average_rating DESC);
CREATE INDEX idx_user_ratings_total ON public.user_ratings USING btree (total_reviews DESC);
CREATE INDEX idx_user_subscriptions_user_status ON public.user_subscriptions USING btree (user_id, status);
CREATE INDEX idx_user_view_history_analytics ON public.user_view_history USING btree (source, medium, viewed_at DESC);
CREATE INDEX idx_user_view_history_category_id ON public.user_view_history USING btree (category_id);
CREATE INDEX idx_user_view_history_category_time ON public.user_view_history USING btree (category_id, viewed_at DESC);
CREATE INDEX idx_user_view_history_device_type ON public.user_view_history USING btree (device_type);
CREATE INDEX idx_user_view_history_interaction_type ON public.user_view_history USING btree (interaction_type);
CREATE INDEX idx_user_view_history_listing_id ON public.user_view_history USING btree (listing_id);
CREATE INDEX idx_user_view_history_popular ON public.user_view_history USING btree (listing_id, viewed_at DESC);
CREATE INDEX idx_user_view_history_session_id ON public.user_view_history USING btree (session_id);
CREATE INDEX idx_user_view_history_user_id ON public.user_view_history USING btree (user_id);
CREATE INDEX idx_user_view_history_user_listing ON public.user_view_history USING btree (user_id, listing_id, viewed_at DESC);
CREATE INDEX idx_user_view_history_viewed_at ON public.user_view_history USING btree (viewed_at DESC);
CREATE INDEX idx_variant_mappings_attribute ON public.variant_attribute_mappings USING btree (variant_attribute_id);
CREATE INDEX idx_variant_mappings_category ON public.variant_attribute_mappings USING btree (category_id);
CREATE INDEX idx_viber_sessions_active ON public.viber_sessions USING btree (viber_user_id, active) WHERE (active = true);
CREATE INDEX idx_viber_sessions_expires ON public.viber_sessions USING btree (expires_at) WHERE (active = true);
CREATE INDEX idx_viber_users_user_id ON public.viber_users USING btree (user_id);
CREATE INDEX idx_view_statistics_category_date ON public.view_statistics USING btree (category_id, date DESC);
CREATE INDEX idx_view_statistics_listing_date ON public.view_statistics USING btree (listing_id, date DESC);
