CREATE INDEX idx_user_subscriptions_user_status ON public.user_subscriptions USING btree (user_id, status);
CREATE INDEX idx_users_active ON public.users USING btree (last_seen DESC) WHERE ((account_status)::text = 'active'::text);
CREATE INDEX idx_users_email ON public.users USING btree (email);
CREATE INDEX idx_users_email_lower ON public.users USING btree (lower((email)::text));
CREATE INDEX idx_users_phone ON public.users USING btree (phone);
CREATE INDEX idx_users_preferred_language ON public.users USING btree (preferred_language);
CREATE INDEX idx_users_provider ON public.users USING btree (provider);
CREATE INDEX idx_users_role_id ON public.users USING btree (role_id);
CREATE INDEX idx_users_status ON public.users USING btree (account_status);
CREATE INDEX idx_variant_mappings_attribute ON public.variant_attribute_mappings USING btree (variant_attribute_id);
CREATE INDEX idx_variant_mappings_category ON public.variant_attribute_mappings USING btree (category_id);
CREATE UNIQUE INDEX storefront_rating_distribution_storefront_id_idx ON public.storefront_rating_distribution USING btree (storefront_id);
CREATE UNIQUE INDEX storefront_rating_summary_storefront_id_idx ON public.storefront_rating_summary USING btree (storefront_id);
CREATE UNIQUE INDEX storefront_ratings_storefront_id_idx ON public.storefront_ratings USING btree (storefront_id);
CREATE UNIQUE INDEX unique_storefront_product_barcode ON public.storefront_products USING btree (storefront_id, barcode) WHERE (barcode IS NOT NULL);
CREATE UNIQUE INDEX unique_storefront_product_sku ON public.storefront_products USING btree (storefront_id, sku) WHERE (sku IS NOT NULL);
CREATE UNIQUE INDEX user_rating_distribution_user_id_idx ON public.user_rating_distribution USING btree (user_id);
CREATE UNIQUE INDEX user_rating_summary_user_id_idx ON public.user_rating_summary USING btree (user_id);
CREATE UNIQUE INDEX user_ratings_user_id_idx ON public.user_ratings USING btree (user_id);
SELECT pg_catalog.setval('public.address_change_log_id_seq', 1, false);
SELECT pg_catalog.setval('public.admin_users_id_seq', 25, true);
SELECT pg_catalog.setval('public.attribute_group_items_id_seq', 1, false);
SELECT pg_catalog.setval('public.attribute_option_translations_id_seq', 3699, true);
SELECT pg_catalog.setval('public.balance_transactions_id_seq', 26, false);
SELECT pg_catalog.setval('public.car_generations_id_seq', 1, false);
SELECT pg_catalog.setval('public.car_makes_id_seq', 115, true);
SELECT pg_catalog.setval('public.car_market_analysis_id_seq', 250, true);
SELECT pg_catalog.setval('public.car_models_id_seq', 3862, true);
SELECT pg_catalog.setval('public.category_attribute_groups_id_seq', 1, false);
SELECT pg_catalog.setval('public.category_keywords_id_seq', 337, true);
SELECT pg_catalog.setval('public.category_variant_attributes_id_seq', 12, true);
SELECT pg_catalog.setval('public.chat_attachments_id_seq', 144, true);
SELECT pg_catalog.setval('public.component_templates_id_seq', 1, false);
SELECT pg_catalog.setval('public.custom_ui_component_usage_id_seq', 1, false);
SELECT pg_catalog.setval('public.custom_ui_components_id_seq', 2, false);
SELECT pg_catalog.setval('public.custom_ui_templates_id_seq', 1, false);
SELECT pg_catalog.setval('public.escrow_payments_id_seq', 1, false);
SELECT pg_catalog.setval('public.geocoding_cache_id_seq', 12, true);
SELECT pg_catalog.setval('public.gis_filter_analytics_id_seq', 1, false);
SELECT pg_catalog.setval('public.gis_isochrone_cache_id_seq', 1, false);
SELECT pg_catalog.setval('public.gis_poi_cache_id_seq', 1, false);
SELECT pg_catalog.setval('public.global_product_id_seq', 294, true);
SELECT pg_catalog.setval('public.import_history_id_seq', 1, false);
SELECT pg_catalog.setval('public.import_sources_id_seq', 1, false);
SELECT pg_catalog.setval('public.imported_categories_id_seq', 1, false);
SELECT pg_catalog.setval('public.inventory_reservations_id_seq', 20, true);
SELECT pg_catalog.setval('public.item_performance_metrics_id_seq', 1, false);
SELECT pg_catalog.setval('public.listing_views_id_seq', 2, true);
SELECT pg_catalog.setval('public.listings_geo_id_seq', 1, false);
SELECT pg_catalog.setval('public.map_items_cache_id_seq', 1, false);
SELECT pg_catalog.setval('public.marketplace_categories_id_seq', 10001, true);
SELECT pg_catalog.setval('public.marketplace_chats_id_seq', 16, true);
SELECT pg_catalog.setval('public.marketplace_images_id_seq', 665, true);
SELECT pg_catalog.setval('public.marketplace_listing_variants_id_seq', 1, false);
SELECT pg_catalog.setval('public.marketplace_messages_id_seq', 53, true);
SELECT pg_catalog.setval('public.marketplace_orders_id_seq', 1, false);
SELECT pg_catalog.setval('public.merchant_payouts_id_seq', 1, false);
SELECT pg_catalog.setval('public.notifications_id_seq', 63, true);
SELECT pg_catalog.setval('public.payment_gateways_id_seq', 2, false);
SELECT pg_catalog.setval('public.payment_methods_id_seq', 27, false);
SELECT pg_catalog.setval('public.payment_transactions_id_seq', 1, false);
SELECT pg_catalog.setval('public.permissions_id_seq', 86, true);
SELECT pg_catalog.setval('public.price_history_id_seq', 166, true);
SELECT pg_catalog.setval('public.product_variant_attribute_values_id_seq', 37, true);
SELECT pg_catalog.setval('public.product_variant_attributes_id_seq', 36, true);
SELECT pg_catalog.setval('public.query_cache_id_seq', 1, false);
SELECT pg_catalog.setval('public.refresh_tokens_id_seq', 5292, true);
SELECT pg_catalog.setval('public.review_confirmations_id_seq', 1, false);
SELECT pg_catalog.setval('public.review_disputes_id_seq', 1, false);
SELECT pg_catalog.setval('public.review_responses_id_seq', 1, false);
SELECT pg_catalog.setval('public.reviews_id_seq', 13, true);
SELECT pg_catalog.setval('public.role_audit_log_id_seq', 3, true);
SELECT pg_catalog.setval('public.roles_id_seq', 30, true);
SELECT pg_catalog.setval('public.search_behavior_metrics_id_seq', 1, false);
SELECT pg_catalog.setval('public.search_config_id_seq', 2, false);
SELECT pg_catalog.setval('public.search_optimization_sessions_id_seq', 1, false);
SELECT pg_catalog.setval('public.search_queries_id_seq', 219, true);
SELECT pg_catalog.setval('public.search_statistics_id_seq', 1, false);
SELECT pg_catalog.setval('public.search_synonyms_config_id_seq', 8, false);
SELECT pg_catalog.setval('public.search_synonyms_id_seq', 41, false);
SELECT pg_catalog.setval('public.search_weights_history_id_seq', 1, false);
SELECT pg_catalog.setval('public.search_weights_id_seq', 17, false);
SELECT pg_catalog.setval('public.shopping_cart_items_id_seq', 57, true);
SELECT pg_catalog.setval('public.shopping_carts_id_seq', 11, true);
SELECT pg_catalog.setval('public.storefront_delivery_options_id_seq', 1, true);
SELECT pg_catalog.setval('public.storefront_hours_id_seq', 45, true);
SELECT pg_catalog.setval('public.storefront_inventory_movements_id_seq', 1, true);
SELECT pg_catalog.setval('public.storefront_order_items_id_seq', 19, true);
SELECT pg_catalog.setval('public.storefront_orders_id_seq', 58, true);
SELECT pg_catalog.setval('public.storefront_payment_methods_id_seq', 27, true);
SELECT pg_catalog.setval('public.storefront_product_attributes_id_seq', 1, true);
SELECT pg_catalog.setval('public.storefront_product_images_id_seq', 66, true);
SELECT pg_catalog.setval('public.storefront_product_variant_images_id_seq', 1, false);
SELECT pg_catalog.setval('public.storefront_product_variants_id_seq', 97, true);
SELECT pg_catalog.setval('public.storefront_staff_id_seq', 17, true);
SELECT pg_catalog.setval('public.storefronts_id_seq', 37, true);
SELECT pg_catalog.setval('public.subscription_history_id_seq', 1, false);
SELECT pg_catalog.setval('public.subscription_payments_id_seq', 1, false);
SELECT pg_catalog.setval('public.subscription_plans_id_seq', 4, true);
SELECT pg_catalog.setval('public.subscription_usage_id_seq', 1, false);
