CREATE TRIGGER trigger_marketplace_listings_cache_refresh AFTER INSERT OR DELETE OR UPDATE ON public.marketplace_listings FOR EACH ROW EXECUTE FUNCTION public.trigger_refresh_map_cache();
CREATE TRIGGER trigger_refresh_rating_distributions AFTER INSERT OR DELETE OR UPDATE ON public.reviews FOR EACH STATEMENT EXECUTE FUNCTION public.refresh_rating_distributions();
CREATE TRIGGER trigger_shopping_cart_items_updated_at BEFORE UPDATE ON public.shopping_cart_items FOR EACH ROW EXECUTE FUNCTION public.update_shopping_cart_updated_at();
CREATE TRIGGER trigger_shopping_carts_updated_at BEFORE UPDATE ON public.shopping_carts FOR EACH ROW EXECUTE FUNCTION public.update_shopping_cart_updated_at();
CREATE TRIGGER trigger_storefront_products_cache_refresh AFTER INSERT OR DELETE OR UPDATE ON public.storefront_products FOR EACH ROW EXECUTE FUNCTION public.trigger_refresh_map_cache();
CREATE TRIGGER trigger_unified_geo_cache_refresh AFTER INSERT OR DELETE OR UPDATE ON public.unified_geo FOR EACH ROW EXECUTE FUNCTION public.trigger_refresh_map_cache();
CREATE TRIGGER trigger_update_ai_category_decisions_updated_at BEFORE UPDATE ON public.ai_category_decisions FOR EACH ROW EXECUTE FUNCTION public.update_ai_category_decisions_updated_at();
CREATE TRIGGER trigger_update_inventory_reservations_updated_at BEFORE UPDATE ON public.inventory_reservations FOR EACH ROW EXECUTE FUNCTION public.update_inventory_reservations_updated_at();
CREATE TRIGGER trigger_update_item_performance_metrics_updated_at BEFORE UPDATE ON public.item_performance_metrics FOR EACH ROW EXECUTE FUNCTION public.update_item_performance_metrics_updated_at();
CREATE TRIGGER trigger_update_listings_geo_updated_at BEFORE UPDATE ON public.listings_geo FOR EACH ROW EXECUTE FUNCTION public.update_listings_geo_updated_at();
CREATE TRIGGER trigger_update_product_variant_attribute_values_updated_at BEFORE UPDATE ON public.product_variant_attribute_values FOR EACH ROW EXECUTE FUNCTION public.update_product_variants_updated_at();
CREATE TRIGGER trigger_update_product_variant_attributes_updated_at BEFORE UPDATE ON public.product_variant_attributes FOR EACH ROW EXECUTE FUNCTION public.update_product_variants_updated_at();
CREATE TRIGGER trigger_update_search_behavior_metrics_updated_at BEFORE UPDATE ON public.search_behavior_metrics FOR EACH ROW EXECUTE FUNCTION public.update_search_behavior_metrics_updated_at();
CREATE TRIGGER trigger_update_search_optimization_sessions_updated_at BEFORE UPDATE ON public.search_optimization_sessions FOR EACH ROW EXECUTE FUNCTION public.update_search_optimization_sessions_updated_at();
CREATE TRIGGER trigger_update_search_synonyms_updated_at BEFORE UPDATE ON public.search_synonyms FOR EACH ROW EXECUTE FUNCTION public.update_search_synonyms_updated_at();
CREATE TRIGGER trigger_update_search_weights_updated_at BEFORE UPDATE ON public.search_weights FOR EACH ROW EXECUTE FUNCTION public.update_search_weights_updated_at();
CREATE TRIGGER trigger_update_storefront_product_variants_updated_at BEFORE UPDATE ON public.storefront_product_variants FOR EACH ROW EXECUTE FUNCTION public.update_product_variants_updated_at();
CREATE TRIGGER trigger_update_storefront_products_count AFTER INSERT OR DELETE OR UPDATE ON public.storefront_products FOR EACH ROW EXECUTE FUNCTION public.update_storefront_products_count();
CREATE TRIGGER trigger_update_storefront_products_geo AFTER UPDATE ON public.storefronts FOR EACH ROW EXECUTE FUNCTION public.update_storefront_products_geo();
CREATE TRIGGER trigger_update_transliteration_rules_updated_at BEFORE UPDATE ON public.transliteration_rules FOR EACH ROW EXECUTE FUNCTION public.update_transliteration_rules_updated_at();
CREATE TRIGGER trigger_update_unified_geo_updated_at BEFORE UPDATE ON public.unified_geo FOR EACH ROW EXECUTE FUNCTION public.update_unified_geo_updated_at();
CREATE TRIGGER update_bex_configuration_updated_at BEFORE UPDATE ON public.bex_configuration FOR EACH ROW EXECUTE FUNCTION public.update_bex_updated_at();
CREATE TRIGGER update_bex_shipments_updated_at BEFORE UPDATE ON public.bex_shipments FOR EACH ROW EXECUTE FUNCTION public.update_bex_updated_at();
CREATE TRIGGER update_car_generations_updated_at BEFORE UPDATE ON public.car_generations FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER update_car_makes_updated_at BEFORE UPDATE ON public.car_makes FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER update_car_models_updated_at BEFORE UPDATE ON public.car_models FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER update_category_ai_mappings_updated_at BEFORE UPDATE ON public.category_ai_mappings FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER update_category_detection_feedback_updated_at BEFORE UPDATE ON public.category_detection_feedback FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER update_category_keyword_weights_updated_at BEFORE UPDATE ON public.category_keyword_weights FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER update_category_keywords_updated_at BEFORE UPDATE ON public.category_keywords FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER update_category_variant_attributes_updated_at BEFORE UPDATE ON public.category_variant_attributes FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER update_couriers_updated_at BEFORE UPDATE ON public.couriers FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER update_custom_ui_component_usage_updated_at BEFORE UPDATE ON public.custom_ui_component_usage FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER update_deliveries_updated_at BEFORE UPDATE ON public.deliveries FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER update_delivery_category_defaults_updated_at BEFORE UPDATE ON public.delivery_category_defaults FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER update_delivery_notifications_updated_at BEFORE UPDATE ON public.delivery_notifications FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER update_delivery_pricing_rules_updated_at BEFORE UPDATE ON public.delivery_pricing_rules FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER update_delivery_providers_updated_at BEFORE UPDATE ON public.delivery_providers FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER update_delivery_shipments_updated_at BEFORE UPDATE ON public.delivery_shipments FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER update_has_variants_trigger AFTER INSERT OR DELETE ON public.storefront_product_variants FOR EACH ROW EXECUTE FUNCTION public.update_product_has_variants();
CREATE TRIGGER update_listings_on_attribute_translation_change AFTER INSERT OR UPDATE ON public.attribute_option_translations FOR EACH ROW EXECUTE FUNCTION public.trigger_update_listings_on_attribute_translation_change();
CREATE TRIGGER update_marketplace_chats_timestamp BEFORE UPDATE ON public.marketplace_chats FOR EACH ROW EXECUTE FUNCTION public.update_marketplace_chats_updated_at();
CREATE TRIGGER update_marketplace_messages_timestamp BEFORE UPDATE ON public.marketplace_messages FOR EACH ROW EXECUTE FUNCTION public.update_marketplace_chats_updated_at();
CREATE TRIGGER update_notification_settings_timestamp BEFORE UPDATE ON public.notification_settings FOR EACH ROW EXECUTE FUNCTION public.update_notification_settings_updated_at();
CREATE TRIGGER update_notification_templates_updated_at BEFORE UPDATE ON public.notification_templates FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER update_ratings_after_review_change AFTER INSERT OR DELETE OR UPDATE ON public.reviews FOR EACH ROW EXECUTE FUNCTION public.refresh_rating_views();
CREATE TRIGGER update_review_responses_updated_at BEFORE UPDATE ON public.review_responses FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER update_reviews_updated_at BEFORE UPDATE ON public.reviews FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER update_search_queries_updated_at_trigger BEFORE UPDATE ON public.search_queries FOR EACH ROW EXECUTE FUNCTION public.update_search_queries_updated_at();
CREATE TRIGGER update_stock_status_trigger BEFORE INSERT OR UPDATE OF stock_quantity ON public.storefront_products FOR EACH ROW EXECUTE FUNCTION public.update_product_stock_status();
CREATE TRIGGER update_storefront_order_items_updated_at BEFORE UPDATE ON public.storefront_order_items FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER update_storefront_usage AFTER INSERT OR DELETE ON public.storefronts FOR EACH ROW EXECUTE FUNCTION public.update_subscription_usage();
CREATE TRIGGER update_storefront_views_count_trigger AFTER INSERT OR DELETE OR UPDATE OF view_count, storefront_id ON public.storefront_products FOR EACH ROW EXECUTE FUNCTION public.update_storefront_views_count();
CREATE TRIGGER update_translation_providers_timestamp BEFORE UPDATE ON public.translation_providers FOR EACH ROW EXECUTE FUNCTION public.update_translation_providers_updated_at();
CREATE TRIGGER update_translations_timestamp BEFORE UPDATE ON public.translations FOR EACH ROW EXECUTE FUNCTION public.update_translations_updated_at();
CREATE TRIGGER update_unified_attribute_values_updated_at BEFORE UPDATE ON public.unified_attribute_values FOR EACH ROW EXECUTE FUNCTION public.update_unified_attributes_updated_at();
CREATE TRIGGER update_unified_attributes_updated_at BEFORE UPDATE ON public.unified_attributes FOR EACH ROW EXECUTE FUNCTION public.update_unified_attributes_updated_at();
CREATE TRIGGER update_unified_category_attributes_updated_at BEFORE UPDATE ON public.unified_category_attributes FOR EACH ROW EXECUTE FUNCTION public.update_unified_attributes_updated_at();
CREATE TRIGGER update_user_contacts_updated_at BEFORE UPDATE ON public.user_contacts FOR EACH ROW EXECUTE FUNCTION public.update_user_contacts_updated_at();
CREATE TRIGGER update_user_notification_preferences_updated_at BEFORE UPDATE ON public.user_notification_preferences FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER update_user_privacy_settings_updated_at BEFORE UPDATE ON public.user_privacy_settings FOR EACH ROW EXECUTE FUNCTION public.update_user_privacy_settings_updated_at();
CREATE TRIGGER update_users_updated_at BEFORE UPDATE ON public.users FOR EACH ROW EXECUTE FUNCTION public.update_user_updated_at();
CREATE TRIGGER update_viber_users_updated_at BEFORE UPDATE ON public.viber_users FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
ALTER SEQUENCE public.address_change_log_id_seq OWNED BY public.address_change_log.id;
ALTER SEQUENCE public.admin_users_id_seq OWNED BY public.admin_users.id;
ALTER SEQUENCE public.ai_category_decisions_id_seq OWNED BY public.ai_category_decisions.id;
ALTER SEQUENCE public.attribute_group_items_id_seq OWNED BY public.attribute_group_items.id;
ALTER SEQUENCE public.attribute_groups_id_seq OWNED BY public.attribute_groups.id;
ALTER SEQUENCE public.attribute_option_translations_id_seq OWNED BY public.attribute_option_translations.id;
ALTER SEQUENCE public.balance_transactions_id_seq OWNED BY public.balance_transactions.id;
ALTER SEQUENCE public.bex_configuration_id_seq OWNED BY public.bex_configuration.id;
ALTER SEQUENCE public.bex_shipments_id_seq OWNED BY public.bex_shipments.id;
ALTER SEQUENCE public.bex_tracking_events_id_seq OWNED BY public.bex_tracking_events.id;
ALTER SEQUENCE public.car_generations_id_seq OWNED BY public.car_generations.id;
ALTER SEQUENCE public.car_makes_id_seq OWNED BY public.car_makes.id;
ALTER SEQUENCE public.car_market_analysis_id_seq OWNED BY public.car_market_analysis.id;
ALTER SEQUENCE public.car_models_id_seq OWNED BY public.car_models.id;
ALTER SEQUENCE public.category_ai_mappings_id_seq OWNED BY public.category_ai_mappings.id;
ALTER SEQUENCE public.category_attribute_groups_id_seq OWNED BY public.category_attribute_groups.id;
ALTER SEQUENCE public.category_detection_cache_id_seq OWNED BY public.category_detection_cache.id;
ALTER SEQUENCE public.category_detection_feedback_id_seq OWNED BY public.category_detection_feedback.id;
ALTER SEQUENCE public.category_keyword_weights_id_seq OWNED BY public.category_keyword_weights.id;
ALTER SEQUENCE public.category_keywords_id_seq OWNED BY public.category_keywords.id;
ALTER SEQUENCE public.category_variant_attributes_id_seq OWNED BY public.category_variant_attributes.id;
ALTER SEQUENCE public.chat_attachments_id_seq OWNED BY public.chat_attachments.id;
ALTER SEQUENCE public.component_templates_id_seq OWNED BY public.component_templates.id;
ALTER SEQUENCE public.courier_location_history_id_seq OWNED BY public.courier_location_history.id;
ALTER SEQUENCE public.courier_zones_id_seq OWNED BY public.courier_zones.id;
ALTER SEQUENCE public.couriers_id_seq OWNED BY public.couriers.id;
ALTER SEQUENCE public.custom_ui_component_usage_id_seq OWNED BY public.custom_ui_component_usage.id;
ALTER SEQUENCE public.custom_ui_components_id_seq OWNED BY public.custom_ui_components.id;
ALTER SEQUENCE public.custom_ui_templates_id_seq OWNED BY public.custom_ui_templates.id;
ALTER SEQUENCE public.deliveries_id_seq OWNED BY public.deliveries.id;
ALTER SEQUENCE public.delivery_category_defaults_id_seq OWNED BY public.delivery_category_defaults.id;
ALTER SEQUENCE public.delivery_notifications_id_seq OWNED BY public.delivery_notifications.id;
ALTER SEQUENCE public.delivery_pricing_rules_id_seq OWNED BY public.delivery_pricing_rules.id;
ALTER SEQUENCE public.delivery_providers_id_seq OWNED BY public.delivery_providers.id;
ALTER SEQUENCE public.delivery_shipments_id_seq OWNED BY public.delivery_shipments.id;
ALTER SEQUENCE public.delivery_tracking_events_id_seq OWNED BY public.delivery_tracking_events.id;
ALTER SEQUENCE public.delivery_zones_id_seq OWNED BY public.delivery_zones.id;
