CREATE INDEX c2c_categories_parent_id_idx ON public.c2c_categories USING btree (parent_id);
CREATE INDEX c2c_categories_slug_idx ON public.c2c_categories USING btree (slug);
CREATE INDEX c2c_chats_buyer_id_idx ON public.c2c_chats USING btree (buyer_id);
CREATE INDEX c2c_chats_buyer_id_seller_id_last_message_at_idx ON public.c2c_chats USING btree (buyer_id, seller_id, last_message_at DESC);
CREATE INDEX c2c_chats_is_archived_idx ON public.c2c_chats USING btree (is_archived) WHERE (NOT is_archived);
CREATE INDEX c2c_chats_last_message_at_idx ON public.c2c_chats USING btree (last_message_at DESC) WHERE (NOT is_archived);
CREATE INDEX c2c_chats_least_greatest_idx ON public.c2c_chats USING btree (LEAST(buyer_id, seller_id), GREATEST(buyer_id, seller_id));
CREATE UNIQUE INDEX c2c_chats_least_greatest_idx1 ON public.c2c_chats USING btree (LEAST(buyer_id, seller_id), GREATEST(buyer_id, seller_id)) WHERE ((listing_id IS NULL) AND (storefront_product_id IS NULL));
CREATE INDEX c2c_chats_listing_id_buyer_id_seller_id_idx ON public.c2c_chats USING btree (listing_id, buyer_id, seller_id) WHERE (listing_id IS NOT NULL);
CREATE INDEX c2c_chats_listing_id_idx ON public.c2c_chats USING btree (listing_id) WHERE (listing_id IS NOT NULL);
CREATE INDEX c2c_chats_seller_id_idx ON public.c2c_chats USING btree (seller_id);
CREATE INDEX c2c_chats_storefront_product_id_idx ON public.c2c_chats USING btree (storefront_product_id);
CREATE INDEX c2c_chats_updated_at_idx ON public.c2c_chats USING btree (updated_at);
CREATE INDEX c2c_favorites_listing_id_idx ON public.c2c_favorites USING btree (listing_id);
CREATE INDEX c2c_favorites_user_id_created_at_idx ON public.c2c_favorites USING btree (user_id, created_at DESC);
CREATE INDEX c2c_images_listing_id_is_main_idx ON public.c2c_images USING btree (listing_id, is_main) WHERE (is_main = true);
CREATE INDEX c2c_listing_variants_attributes_idx ON public.c2c_listing_variants USING gin (attributes);
CREATE INDEX c2c_listing_variants_is_active_idx ON public.c2c_listing_variants USING btree (is_active);
CREATE INDEX c2c_listing_variants_listing_id_idx ON public.c2c_listing_variants USING btree (listing_id);
CREATE INDEX c2c_listing_variants_sku_idx ON public.c2c_listing_variants USING btree (sku);
CREATE INDEX c2c_listings_address_city_idx ON public.c2c_listings USING btree (address_city) WHERE (address_city IS NOT NULL);
CREATE INDEX c2c_listings_address_city_status_idx ON public.c2c_listings USING btree (address_city, status) WHERE ((status)::text = 'active'::text);
CREATE INDEX c2c_listings_address_multilingual_idx ON public.c2c_listings USING gin (address_multilingual);
CREATE INDEX c2c_listings_category_id_status_idx ON public.c2c_listings USING btree (category_id, status) WHERE ((status)::text = 'active'::text);
CREATE INDEX c2c_listings_category_id_status_price_idx ON public.c2c_listings USING btree (category_id, status, price) WHERE ((status)::text = 'active'::text);
CREATE INDEX c2c_listings_created_at_idx ON public.c2c_listings USING btree (created_at DESC) WHERE (((status)::text = 'active'::text) AND ((metadata ->> 'is_featured'::text) = 'true'::text));
CREATE INDEX c2c_listings_created_at_idx1 ON public.c2c_listings USING btree (created_at DESC) WHERE ((status)::text = 'active'::text);
CREATE INDEX c2c_listings_expr_idx ON public.c2c_listings USING gin (((metadata -> 'discount'::text)));
CREATE INDEX c2c_listings_external_id_idx ON public.c2c_listings USING btree (external_id);
CREATE INDEX c2c_listings_external_id_storefront_id_idx ON public.c2c_listings USING btree (external_id, storefront_id);
CREATE INDEX c2c_listings_latitude_longitude_idx ON public.c2c_listings USING btree (latitude, longitude) WHERE ((latitude IS NOT NULL) AND (longitude IS NOT NULL));
CREATE INDEX c2c_listings_price_idx ON public.c2c_listings USING btree (price) WHERE ((price IS NOT NULL) AND ((status)::text = 'active'::text));
CREATE INDEX c2c_listings_status_category_id_idx ON public.c2c_listings USING btree (status, category_id) WHERE ((status)::text = 'active'::text);
CREATE INDEX c2c_listings_status_created_at_idx ON public.c2c_listings USING btree (status, created_at DESC) WHERE ((status)::text = 'active'::text);
CREATE INDEX c2c_listings_status_created_at_views_count_idx ON public.c2c_listings USING btree (status, created_at DESC, views_count DESC) WHERE ((status)::text = 'active'::text);
CREATE INDEX c2c_listings_status_idx ON public.c2c_listings USING btree (status);
CREATE INDEX c2c_listings_storefront_id_idx ON public.c2c_listings USING btree (storefront_id);
CREATE INDEX c2c_listings_user_id_status_created_at_idx ON public.c2c_listings USING btree (user_id, status, created_at DESC);
CREATE INDEX c2c_listings_views_count_idx ON public.c2c_listings USING btree (views_count DESC) WHERE (((status)::text = 'active'::text) AND (views_count > 10));
CREATE INDEX c2c_messages_chat_id_created_at_idx ON public.c2c_messages USING btree (chat_id, created_at DESC);
CREATE INDEX c2c_messages_chat_id_id_idx ON public.c2c_messages USING btree (chat_id, id DESC);
CREATE INDEX c2c_messages_chat_id_idx ON public.c2c_messages USING btree (chat_id);
CREATE INDEX c2c_messages_chat_id_receiver_id_idx ON public.c2c_messages USING btree (chat_id, receiver_id) WHERE (NOT is_read);
CREATE INDEX c2c_messages_created_at_idx ON public.c2c_messages USING btree (created_at);
CREATE INDEX c2c_messages_listing_id_idx ON public.c2c_messages USING btree (listing_id);
CREATE INDEX c2c_messages_receiver_id_chat_id_idx ON public.c2c_messages USING btree (receiver_id, chat_id) WHERE (NOT is_read);
CREATE INDEX c2c_messages_receiver_id_idx ON public.c2c_messages USING btree (receiver_id);
CREATE INDEX c2c_messages_receiver_id_is_read_idx ON public.c2c_messages USING btree (receiver_id, is_read) WHERE (NOT is_read);
CREATE INDEX c2c_messages_sender_id_idx ON public.c2c_messages USING btree (sender_id);
CREATE INDEX c2c_messages_storefront_product_id_idx ON public.c2c_messages USING btree (storefront_product_id) WHERE (storefront_product_id IS NOT NULL);
CREATE INDEX c2c_orders_buyer_id_idx ON public.c2c_orders USING btree (buyer_id);
CREATE INDEX c2c_orders_buyer_id_idx1 ON public.c2c_orders USING btree (buyer_id);
CREATE INDEX c2c_orders_created_at_idx ON public.c2c_orders USING btree (created_at DESC);
CREATE INDEX c2c_orders_listing_id_idx ON public.c2c_orders USING btree (listing_id);
CREATE INDEX c2c_orders_listing_id_idx1 ON public.c2c_orders USING btree (listing_id);
CREATE INDEX c2c_orders_payment_transaction_id_idx ON public.c2c_orders USING btree (payment_transaction_id);
CREATE INDEX c2c_orders_protection_expires_at_idx ON public.c2c_orders USING btree (protection_expires_at) WHERE ((status)::text = ANY (ARRAY[('delivered'::character varying)::text, ('shipped'::character varying)::text]));
CREATE INDEX c2c_orders_protection_expires_at_idx1 ON public.c2c_orders USING btree (protection_expires_at) WHERE (protection_expires_at IS NOT NULL);
CREATE INDEX c2c_orders_seller_id_idx ON public.c2c_orders USING btree (seller_id);
CREATE INDEX c2c_orders_seller_id_idx1 ON public.c2c_orders USING btree (seller_id);
CREATE INDEX c2c_orders_status_idx ON public.c2c_orders USING btree (status);
CREATE INDEX idx_ai_decisions_category_confidence ON public.ai_category_decisions USING btree (category_id, confidence DESC);
CREATE INDEX idx_ai_decisions_created_at ON public.ai_category_decisions USING btree (created_at DESC);
CREATE INDEX idx_ai_decisions_domain_type ON public.ai_category_decisions USING btree (ai_domain, ai_product_type);
CREATE INDEX idx_ai_decisions_entity_type ON public.ai_category_decisions USING btree (entity_type, created_at DESC);
CREATE INDEX idx_ai_decisions_title_hash ON public.ai_category_decisions USING btree (title_hash);
CREATE UNIQUE INDEX idx_ai_decisions_unique_title_hash ON public.ai_category_decisions USING btree (title_hash);
CREATE INDEX idx_ai_decisions_user_confirmed ON public.ai_category_decisions USING btree (user_confirmed) WHERE (user_confirmed = true);
CREATE INDEX idx_ai_mappings_active ON public.category_ai_mappings USING btree (is_active) WHERE (is_active = true);
CREATE INDEX idx_ai_mappings_category ON public.category_ai_mappings USING btree (category_id);
CREATE INDEX idx_ai_mappings_domain_type ON public.category_ai_mappings USING btree (ai_domain, product_type);
CREATE INDEX idx_attribute_group_items_attribute ON public.attribute_group_items USING btree (attribute_id);
CREATE INDEX idx_attribute_group_items_group ON public.attribute_group_items USING btree (group_id);
CREATE INDEX idx_attribute_option_translations ON public.attribute_option_translations USING btree (attribute_name, option_value);
CREATE INDEX idx_audit_log_entity ON public.translation_audit_log USING btree (entity_type, entity_id);
CREATE INDEX idx_audit_log_user_date ON public.translation_audit_log USING btree (user_id, created_at DESC);
CREATE INDEX idx_b2c_images_product_main ON public.b2c_product_images USING btree (storefront_product_id, is_default DESC, display_order);
CREATE INDEX idx_b2c_products_active_created ON public.b2c_products USING btree (is_active, created_at DESC) WHERE (is_active = true);
CREATE INDEX idx_b2c_products_category_active ON public.b2c_products USING btree (category_id, is_active) WHERE (is_active = true);
CREATE INDEX idx_b2c_products_price ON public.b2c_products USING btree (price) WHERE ((is_active = true) AND (price IS NOT NULL));
CREATE INDEX idx_b2c_products_storefront ON public.b2c_products USING btree (storefront_id, is_active) WHERE (is_active = true);
CREATE INDEX idx_bex_shipments_created_at ON public.bex_shipments USING btree (created_at DESC);
CREATE INDEX idx_bex_shipments_marketplace_order_id ON public.bex_shipments USING btree (marketplace_order_id);
CREATE INDEX idx_bex_shipments_order_id ON public.bex_shipments USING btree (order_id);
CREATE INDEX idx_bex_shipments_storefront_order_id ON public.bex_shipments USING btree (storefront_order_id);
CREATE INDEX idx_bex_tracking_events_date ON public.bex_tracking_events USING btree (event_date DESC);
CREATE INDEX idx_bex_tracking_events_shipment_id ON public.bex_tracking_events USING btree (shipment_id);
CREATE INDEX idx_c2c_images_listing_main ON public.c2c_images USING btree (listing_id, is_main DESC);
CREATE INDEX idx_c2c_listings_active_created ON public.c2c_listings USING btree (status, created_at DESC) WHERE ((status)::text = 'active'::text);
CREATE INDEX idx_c2c_listings_category_active ON public.c2c_listings USING btree (category_id, status) WHERE ((status)::text = 'active'::text);
CREATE INDEX idx_c2c_listings_price ON public.c2c_listings USING btree (price) WHERE (((status)::text = 'active'::text) AND (price IS NOT NULL));
CREATE INDEX idx_car_generations_active ON public.car_generations USING btree (is_active) WHERE (is_active = true);
CREATE INDEX idx_car_generations_model_id ON public.car_generations USING btree (model_id);
CREATE INDEX idx_car_generations_slug ON public.car_generations USING btree (slug);
CREATE INDEX idx_car_generations_years ON public.car_generations USING btree (year_start, year_end);
CREATE INDEX idx_car_makes_external_id ON public.car_makes USING btree (external_id);
CREATE INDEX idx_car_makes_is_domestic ON public.car_makes USING btree (is_domestic);
CREATE INDEX idx_car_makes_popularity ON public.car_makes USING btree (popularity_rs DESC);
CREATE INDEX idx_car_models_battery_capacity ON public.car_models USING btree (battery_capacity_kwh) WHERE (battery_capacity_kwh IS NOT NULL);
CREATE INDEX idx_car_models_body_type ON public.car_models USING btree (body_type);
