CREATE INDEX idx_language ON public.category_keywords USING btree (language);
CREATE INDEX idx_listing_attribute_values_attribute ON public.listing_attribute_values USING btree (attribute_id);
CREATE INDEX idx_listing_attribute_values_listing ON public.listing_attribute_values USING btree (listing_id);
CREATE INDEX idx_listing_attribute_values_numeric ON public.listing_attribute_values USING btree (numeric_value) WHERE (numeric_value IS NOT NULL);
CREATE INDEX idx_listing_attribute_values_text ON public.listing_attribute_values USING btree (text_value) WHERE (text_value IS NOT NULL);
CREATE INDEX idx_listing_attribute_values_unit ON public.listing_attribute_values USING btree (unit) WHERE (unit IS NOT NULL);
CREATE INDEX idx_listing_attribute_values_value_type ON public.listing_attribute_values USING btree (value_type);
CREATE INDEX idx_listing_views_listing_ip ON public.listing_views USING btree (listing_id, ip_hash);
CREATE INDEX idx_listing_views_listing_user ON public.listing_views USING btree (listing_id, user_id);
CREATE INDEX idx_listing_views_time ON public.listing_views USING btree (view_time);
CREATE INDEX idx_location_history_courier ON public.courier_location_history USING btree (courier_id, recorded_at DESC);
CREATE INDEX idx_location_history_delivery ON public.courier_location_history USING btree (delivery_id, recorded_at DESC);
CREATE INDEX idx_location_history_key_points ON public.courier_location_history USING btree (delivery_id, is_key_point) WHERE (is_key_point = true);
CREATE INDEX idx_map_items_cache_category ON public.map_items_cache USING btree (category_id) WHERE (category_id IS NOT NULL);
CREATE INDEX idx_map_items_cache_expires ON public.map_items_cache USING btree (expires_at) WHERE (expires_at IS NOT NULL);
CREATE INDEX idx_map_items_cache_type_id ON public.map_items_cache USING btree (item_type, item_id);
CREATE UNIQUE INDEX idx_map_items_cache_unique ON public.map_items_cache USING btree (item_type, item_id);
CREATE INDEX idx_merchant_payouts_gateway_payout_id ON public.merchant_payouts USING btree (gateway_payout_id);
CREATE INDEX idx_merchant_payouts_seller_id ON public.merchant_payouts USING btree (seller_id);
CREATE INDEX idx_merchant_payouts_status ON public.merchant_payouts USING btree (status);
CREATE INDEX idx_municipalities_boundary ON public.municipalities USING gist (boundary);
CREATE INDEX idx_municipalities_center ON public.municipalities USING gist (center_point);
CREATE INDEX idx_municipalities_district ON public.municipalities USING btree (district_id);
CREATE INDEX idx_municipalities_name ON public.municipalities USING btree (name);
CREATE INDEX idx_notifications_created ON public.notifications USING btree (created_at);
CREATE INDEX idx_notifications_type ON public.notifications USING btree (type);
CREATE INDEX idx_notifications_user ON public.notifications USING btree (user_id);
CREATE INDEX idx_notifications_user_unread ON public.notifications USING btree (user_id, created_at DESC) WHERE (NOT is_read);
CREATE INDEX idx_payment_transactions_auto_capture ON public.payment_transactions USING btree (auto_capture_at, status) WHERE (((status)::text = 'authorized'::text) AND ((capture_mode)::text = 'auto'::text));
CREATE INDEX idx_payment_transactions_created_at ON public.payment_transactions USING btree (created_at);
CREATE INDEX idx_payment_transactions_gateway_transaction_id ON public.payment_transactions USING btree (gateway_transaction_id);
CREATE INDEX idx_payment_transactions_listing_id ON public.payment_transactions USING btree (listing_id);
CREATE INDEX idx_payment_transactions_source ON public.payment_transactions USING btree (source_type, source_id);
CREATE INDEX idx_payment_transactions_status ON public.payment_transactions USING btree (status);
CREATE INDEX idx_payment_transactions_user_id ON public.payment_transactions USING btree (user_id);
CREATE INDEX idx_post_express_locations_name ON public.post_express_locations USING btree (name);
CREATE INDEX idx_post_express_locations_postal_code ON public.post_express_locations USING btree (postal_code);
CREATE INDEX idx_post_express_offices_is_active ON public.post_express_offices USING btree (is_active);
CREATE INDEX idx_post_express_offices_location_id ON public.post_express_offices USING btree (location_id);
CREATE INDEX idx_post_express_shipments_marketplace_order_id ON public.post_express_shipments USING btree (marketplace_order_id);
CREATE INDEX idx_post_express_shipments_status ON public.post_express_shipments USING btree (status);
CREATE INDEX idx_post_express_shipments_storefront_order_id ON public.post_express_shipments USING btree (storefront_order_id);
CREATE INDEX idx_post_express_tracking_events_shipment_id ON public.post_express_tracking_events USING btree (shipment_id);
CREATE INDEX idx_post_express_tracking_events_timestamp ON public.post_express_tracking_events USING btree (event_timestamp);
CREATE INDEX idx_price_history_current ON public.price_history USING btree (listing_id, effective_from DESC) WHERE (effective_to IS NULL);
CREATE INDEX idx_price_history_effective ON public.price_history USING btree (listing_id, effective_to);
CREATE INDEX idx_price_history_listing_id ON public.price_history USING btree (listing_id);
CREATE INDEX idx_product_variant_attribute_values_attribute_id ON public.product_variant_attribute_values USING btree (attribute_id);
CREATE INDEX idx_product_variant_attribute_values_value ON public.product_variant_attribute_values USING btree (value);
CREATE INDEX idx_product_variant_attributes_affects_stock ON public.product_variant_attributes USING btree (affects_stock) WHERE (affects_stock = true);
CREATE INDEX idx_product_variant_attributes_name ON public.product_variant_attributes USING btree (name);
CREATE INDEX idx_providers_active ON public.translation_providers USING btree (is_active, priority) WHERE (is_active = true);
CREATE INDEX idx_quality_metrics_issues ON public.translation_quality_metrics USING btree (has_placeholders, has_html_tags);
CREATE INDEX idx_quality_metrics_score ON public.translation_quality_metrics USING btree (quality_score);
CREATE INDEX idx_query_cache_hash ON public.query_cache USING btree (query_hash);
CREATE INDEX idx_rating_cache_type_rating ON public.rating_cache USING btree (entity_type, average_rating DESC);
CREATE INDEX idx_rating_cache_updated ON public.rating_cache USING btree (calculated_at);
CREATE INDEX idx_review_responses_review ON public.review_responses USING btree (review_id);
CREATE INDEX idx_reviews_entity ON public.reviews USING btree (entity_type, entity_id);
CREATE INDEX idx_reviews_entity_origin ON public.reviews USING btree (entity_origin_type, entity_origin_id);
CREATE INDEX idx_reviews_has_dispute ON public.reviews USING btree (has_active_dispute) WHERE (has_active_dispute = true);
CREATE INDEX idx_reviews_rating ON public.reviews USING btree (rating);
CREATE INDEX idx_reviews_seller_confirmed ON public.reviews USING btree (seller_confirmed) WHERE (seller_confirmed = true);
CREATE INDEX idx_reviews_status ON public.reviews USING btree (status);
CREATE INDEX idx_reviews_user ON public.reviews USING btree (user_id);
CREATE UNIQUE INDEX idx_reviews_user_entity_unique ON public.reviews USING btree (user_id, entity_type, entity_id) WHERE ((status)::text <> 'deleted'::text);
CREATE INDEX idx_role_audit_log_created_at ON public.role_audit_log USING btree (created_at DESC);
CREATE INDEX idx_role_audit_log_target_user_id ON public.role_audit_log USING btree (target_user_id);
CREATE INDEX idx_role_audit_log_user_id ON public.role_audit_log USING btree (user_id);
CREATE INDEX idx_role_permissions_permission_id ON public.role_permissions USING btree (permission_id);
CREATE INDEX idx_role_permissions_role ON public.role_permissions USING btree (role_id);
CREATE INDEX idx_role_permissions_role_id ON public.role_permissions USING btree (role_id);
CREATE INDEX idx_saved_search_notifications_created_at ON public.saved_search_notifications USING btree (created_at DESC);
CREATE INDEX idx_saved_search_notifications_saved_search_id ON public.saved_search_notifications USING btree (saved_search_id);
CREATE INDEX idx_saved_searches_created_at ON public.saved_searches USING btree (created_at DESC);
CREATE INDEX idx_saved_searches_filters ON public.saved_searches USING gin (filters);
CREATE INDEX idx_saved_searches_notify_enabled ON public.saved_searches USING btree (notify_enabled) WHERE (notify_enabled = true);
CREATE INDEX idx_saved_searches_search_type ON public.saved_searches USING btree (search_type);
CREATE INDEX idx_saved_searches_user_id ON public.saved_searches USING btree (user_id);
CREATE INDEX idx_search_behavior_metrics_conversions ON public.search_behavior_metrics USING btree (conversions DESC);
CREATE INDEX idx_search_behavior_metrics_ctr ON public.search_behavior_metrics USING btree (ctr DESC);
CREATE INDEX idx_search_behavior_metrics_period ON public.search_behavior_metrics USING btree (period_start, period_end);
CREATE INDEX idx_search_behavior_metrics_query ON public.search_behavior_metrics USING btree (search_query);
CREATE UNIQUE INDEX idx_search_behavior_metrics_unique ON public.search_behavior_metrics USING btree (search_query, period_start);
CREATE INDEX idx_search_optimization_sessions_created_by ON public.search_optimization_sessions USING btree (created_by);
CREATE INDEX idx_search_optimization_sessions_start_time ON public.search_optimization_sessions USING btree (start_time);
CREATE INDEX idx_search_optimization_sessions_status ON public.search_optimization_sessions USING btree (status);
CREATE INDEX idx_search_queries_language ON public.search_queries USING btree (language);
CREATE INDEX idx_search_queries_normalized_query ON public.search_queries USING btree (normalized_query);
CREATE INDEX idx_search_queries_search_count ON public.search_queries USING btree (search_count DESC);
CREATE INDEX idx_search_synonyms_active ON public.search_synonyms USING btree (is_active) WHERE (is_active = true);
CREATE INDEX idx_search_synonyms_config_term ON public.search_synonyms_config USING btree (term);
CREATE INDEX idx_search_synonyms_language ON public.search_synonyms USING btree (language);
CREATE INDEX idx_search_synonyms_synonym ON public.search_synonyms USING btree (synonym);
CREATE INDEX idx_search_synonyms_term ON public.search_synonyms USING btree (term);
CREATE UNIQUE INDEX idx_search_synonyms_unique ON public.search_synonyms USING btree (term, synonym, language) WHERE (is_active = true);
CREATE INDEX idx_search_weights_category_id ON public.search_weights USING btree (category_id) WHERE (category_id IS NOT NULL);
CREATE INDEX idx_search_weights_field_name ON public.search_weights USING btree (field_name);
CREATE INDEX idx_search_weights_history_changed_at ON public.search_weights_history USING btree (changed_at);
CREATE INDEX idx_search_weights_history_changed_by ON public.search_weights_history USING btree (changed_by);
