CREATE INDEX idx_search_weights_history_weight_id ON public.search_weights_history USING btree (weight_id);
CREATE INDEX idx_search_weights_is_active ON public.search_weights USING btree (is_active) WHERE (is_active = true);
CREATE INDEX idx_search_weights_item_type ON public.search_weights USING btree (item_type);
CREATE INDEX idx_shopping_cart_items_cart_id ON public.shopping_cart_items USING btree (cart_id);
CREATE INDEX idx_shopping_cart_items_product_id ON public.shopping_cart_items USING btree (product_id);
CREATE INDEX idx_shopping_carts_session_id ON public.shopping_carts USING btree (session_id);
CREATE INDEX idx_shopping_carts_storefront_id ON public.shopping_carts USING btree (storefront_id);
CREATE INDEX idx_shopping_carts_user_id ON public.shopping_carts USING btree (user_id);
CREATE INDEX idx_staff_storefront_id ON public.storefront_staff USING btree (storefront_id);
CREATE INDEX idx_staff_user_id ON public.storefront_staff USING btree (user_id);
CREATE INDEX idx_storefront_inventory_movements_created_at ON public.storefront_inventory_movements USING btree (created_at);
CREATE INDEX idx_storefront_inventory_movements_product_id ON public.storefront_inventory_movements USING btree (storefront_product_id);
CREATE INDEX idx_storefront_inventory_movements_type ON public.storefront_inventory_movements USING btree (type);
CREATE INDEX idx_storefront_inventory_movements_variant_id ON public.storefront_inventory_movements USING btree (variant_id) WHERE (variant_id IS NOT NULL);
CREATE INDEX idx_storefront_order_items_order_id ON public.storefront_order_items USING btree (order_id);
CREATE INDEX idx_storefront_order_items_product_id ON public.storefront_order_items USING btree (product_id);
CREATE INDEX idx_storefront_order_items_variant_id ON public.storefront_order_items USING btree (variant_id);
CREATE INDEX idx_storefront_orders_customer ON public.storefront_orders USING btree (customer_id, created_at DESC);
CREATE INDEX idx_storefront_orders_escrow_date ON public.storefront_orders USING btree (escrow_release_date) WHERE (escrow_release_date IS NOT NULL);
CREATE INDEX idx_storefront_orders_status ON public.storefront_orders USING btree (status);
CREATE INDEX idx_storefront_orders_storefront ON public.storefront_orders USING btree (storefront_id, created_at DESC);
CREATE INDEX idx_storefront_product_attributes_attribute_id ON public.storefront_product_attributes USING btree (attribute_id);
CREATE INDEX idx_storefront_product_attributes_enabled ON public.storefront_product_attributes USING btree (is_enabled);
CREATE INDEX idx_storefront_product_attributes_product_id ON public.storefront_product_attributes USING btree (product_id);
CREATE INDEX idx_storefront_product_images_display_order ON public.storefront_product_images USING btree (display_order);
CREATE INDEX idx_storefront_product_images_product_id ON public.storefront_product_images USING btree (storefront_product_id);
CREATE INDEX idx_storefront_product_variant_images_is_main ON public.storefront_product_variant_images USING btree (is_main);
CREATE INDEX idx_storefront_product_variant_images_variant_id ON public.storefront_product_variant_images USING btree (variant_id);
CREATE INDEX idx_storefront_product_variants_attributes_gin ON public.storefront_product_variants USING gin (variant_attributes);
CREATE INDEX idx_storefront_product_variants_barcode ON public.storefront_product_variants USING btree (barcode) WHERE (barcode IS NOT NULL);
CREATE INDEX idx_storefront_product_variants_is_active ON public.storefront_product_variants USING btree (is_active);
CREATE INDEX idx_storefront_product_variants_is_default ON public.storefront_product_variants USING btree (is_default);
CREATE INDEX idx_storefront_product_variants_product_id ON public.storefront_product_variants USING btree (product_id);
CREATE INDEX idx_storefront_product_variants_sku ON public.storefront_product_variants USING btree (sku) WHERE (sku IS NOT NULL);
CREATE INDEX idx_storefront_products_barcode ON public.storefront_products USING btree (barcode) WHERE (barcode IS NOT NULL);
CREATE INDEX idx_storefront_products_category_id ON public.storefront_products USING btree (category_id);
CREATE INDEX idx_storefront_products_has_variants ON public.storefront_products USING btree (has_variants);
CREATE INDEX idx_storefront_products_is_active ON public.storefront_products USING btree (is_active);
CREATE INDEX idx_storefront_products_name_gin ON public.storefront_products USING gin (to_tsvector('simple'::regconfig, (name)::text));
CREATE INDEX idx_storefront_products_privacy ON public.storefront_products USING btree (location_privacy);
CREATE INDEX idx_storefront_products_show_on_map ON public.storefront_products USING btree (show_on_map);
CREATE INDEX idx_storefront_products_sku ON public.storefront_products USING btree (sku) WHERE (sku IS NOT NULL);
CREATE INDEX idx_storefront_products_stock_status ON public.storefront_products USING btree (stock_status);
CREATE INDEX idx_storefront_products_storefront_id ON public.storefront_products USING btree (storefront_id);
CREATE INDEX idx_storefronts_city ON public.storefronts USING btree (city);
CREATE INDEX idx_storefronts_coordinates ON public.storefronts USING btree (latitude, longitude) WHERE ((latitude IS NOT NULL) AND (longitude IS NOT NULL));
CREATE INDEX idx_storefronts_geo_strategy ON public.storefronts USING btree (geo_strategy);
CREATE INDEX idx_storefronts_is_active ON public.storefronts USING btree (is_active);
CREATE INDEX idx_storefronts_rating ON public.storefronts USING btree (rating DESC);
CREATE INDEX idx_storefronts_slug ON public.storefronts USING btree (slug);
CREATE INDEX idx_storefronts_user_id ON public.storefronts USING btree (user_id);
CREATE INDEX idx_sync_conflicts_dates ON public.translation_sync_conflicts USING btree (created_at DESC);
CREATE INDEX idx_sync_conflicts_unresolved ON public.translation_sync_conflicts USING btree (resolved) WHERE (resolved = false);
CREATE INDEX idx_transactions_created ON public.balance_transactions USING btree (created_at);
CREATE INDEX idx_transactions_status ON public.balance_transactions USING btree (status);
CREATE INDEX idx_transactions_user ON public.balance_transactions USING btree (user_id);
CREATE INDEX idx_translation_tasks_assigned ON public.translation_tasks USING btree (assigned_to, status);
CREATE INDEX idx_translation_tasks_status ON public.translation_tasks USING btree (status, created_at) WHERE ((status)::text <> 'completed'::text);
CREATE INDEX idx_translations_entity_field ON public.translations USING btree (entity_type, entity_id, field_name, language) WHERE ((entity_type)::text = 'listing'::text);
CREATE INDEX idx_translations_listing_all ON public.translations USING btree (entity_id, language) WHERE ((entity_type)::text = 'listing'::text);
CREATE INDEX idx_translations_lookup ON public.translations USING btree (entity_type, entity_id, language);
CREATE INDEX idx_translations_metadata ON public.translations USING gin (metadata);
CREATE INDEX idx_translations_type_lang ON public.translations USING btree (entity_type, language);
CREATE INDEX idx_transliteration_rules_active ON public.transliteration_rules USING btree (language, enabled, priority DESC);
CREATE INDEX idx_transliteration_rules_enabled ON public.transliteration_rules USING btree (enabled);
CREATE INDEX idx_transliteration_rules_language ON public.transliteration_rules USING btree (language);
CREATE INDEX idx_transliteration_rules_priority ON public.transliteration_rules USING btree (priority DESC);
CREATE INDEX idx_transliteration_rules_type ON public.transliteration_rules USING btree (rule_type);
CREATE INDEX idx_ui_comp_usage_active ON public.custom_ui_component_usage USING btree (is_active);
CREATE INDEX idx_ui_comp_usage_category ON public.custom_ui_component_usage USING btree (category_id);
CREATE INDEX idx_ui_comp_usage_component ON public.custom_ui_component_usage USING btree (component_id);
CREATE INDEX idx_ui_comp_usage_context ON public.custom_ui_component_usage USING btree (usage_context);
CREATE INDEX idx_unified_geo_composite ON public.unified_geo USING btree (source_type, source_id);
CREATE INDEX idx_unified_geo_geohash ON public.unified_geo USING btree (geohash);
CREATE INDEX idx_unified_geo_location_bounds ON public.unified_geo USING gist (location) WHERE (location IS NOT NULL);
CREATE INDEX idx_unified_geo_marketplace_active ON public.unified_geo USING btree (source_id) WHERE (source_type = 'marketplace_listing'::public.geo_source_type);
CREATE INDEX idx_unified_geo_source_id ON public.unified_geo USING btree (source_id);
CREATE INDEX idx_unified_geo_source_type ON public.unified_geo USING btree (source_type);
CREATE INDEX idx_unified_geo_storefront_active ON public.unified_geo USING btree (source_id) WHERE (source_type = 'storefront_product'::public.geo_source_type);
CREATE INDEX idx_user_behavior_events_created_at ON public.user_behavior_events USING btree (created_at);
CREATE INDEX idx_user_behavior_events_event_type ON public.user_behavior_events USING btree (event_type);
CREATE INDEX idx_user_behavior_events_item ON public.user_behavior_events USING btree (item_id, item_type) WHERE (item_id IS NOT NULL);
CREATE INDEX idx_user_behavior_events_search_query_type ON public.user_behavior_events USING btree (search_query, event_type) WHERE (search_query IS NOT NULL);
CREATE INDEX idx_user_behavior_events_session_id ON public.user_behavior_events USING btree (session_id);
CREATE INDEX idx_user_behavior_events_user_id ON public.user_behavior_events USING btree (user_id) WHERE (user_id IS NOT NULL);
CREATE INDEX idx_user_contacts_contact_user_id ON public.user_contacts USING btree (contact_user_id);
CREATE INDEX idx_user_contacts_created_at ON public.user_contacts USING btree (created_at);
CREATE INDEX idx_user_contacts_status ON public.user_contacts USING btree (status);
CREATE INDEX idx_user_contacts_user_id ON public.user_contacts USING btree (user_id);
CREATE INDEX idx_user_privacy_settings_user_id ON public.user_privacy_settings USING btree (user_id);
CREATE INDEX idx_user_roles_role_id ON public.user_roles USING btree (role_id);
CREATE INDEX idx_user_roles_user_id ON public.user_roles USING btree (user_id);
CREATE INDEX idx_user_storefronts_status ON public.user_storefronts USING btree (status);
CREATE INDEX idx_user_storefronts_user ON public.user_storefronts USING btree (user_id);
CREATE INDEX idx_users_active ON public.users USING btree (last_seen DESC) WHERE ((account_status)::text = 'active'::text);
CREATE INDEX idx_users_email ON public.users USING btree (email);
CREATE INDEX idx_users_email_lower ON public.users USING btree (lower((email)::text));
CREATE INDEX idx_users_phone ON public.users USING btree (phone);
CREATE INDEX idx_users_preferred_language ON public.users USING btree (preferred_language);
CREATE INDEX idx_users_provider ON public.users USING btree (provider);
