CREATE INDEX idx_quality_metrics_score ON public.translation_quality_metrics USING btree (quality_score);
CREATE INDEX idx_query_cache_hash ON public.query_cache USING btree (query_hash);
CREATE INDEX idx_rating_cache_type_rating ON public.rating_cache USING btree (entity_type, average_rating DESC);
CREATE INDEX idx_rating_cache_updated ON public.rating_cache USING btree (calculated_at);
CREATE INDEX idx_review_responses_review ON public.review_responses USING btree (review_id);
CREATE INDEX idx_reviews_entity ON public.reviews USING btree (entity_type, entity_id);
CREATE INDEX idx_reviews_entity_origin ON public.reviews USING btree (entity_origin_type, entity_origin_id);
CREATE INDEX idx_reviews_has_dispute ON public.reviews USING btree (has_active_dispute) WHERE (has_active_dispute = true);
CREATE INDEX idx_reviews_rating ON public.reviews USING btree (rating);
CREATE INDEX idx_reviews_seller_confirmed ON public.reviews USING btree (seller_confirmed) WHERE (seller_confirmed = true);
CREATE INDEX idx_reviews_status ON public.reviews USING btree (status);
CREATE INDEX idx_reviews_user ON public.reviews USING btree (user_id);
CREATE UNIQUE INDEX idx_reviews_user_entity_unique ON public.reviews USING btree (user_id, entity_type, entity_id) WHERE ((status)::text <> 'deleted'::text);
CREATE INDEX idx_role_audit_log_created_at ON public.role_audit_log USING btree (created_at DESC);
CREATE INDEX idx_role_audit_log_target_user_id ON public.role_audit_log USING btree (target_user_id);
CREATE INDEX idx_role_audit_log_user_id ON public.role_audit_log USING btree (user_id);
CREATE INDEX idx_role_permissions_permission_id ON public.role_permissions USING btree (permission_id);
CREATE INDEX idx_role_permissions_role_id ON public.role_permissions USING btree (role_id);
CREATE INDEX idx_saved_search_notifications_created_at ON public.saved_search_notifications USING btree (created_at DESC);
CREATE INDEX idx_saved_search_notifications_saved_search_id ON public.saved_search_notifications USING btree (saved_search_id);
CREATE INDEX idx_saved_searches_created_at ON public.saved_searches USING btree (created_at DESC);
CREATE INDEX idx_saved_searches_filters ON public.saved_searches USING gin (filters);
CREATE INDEX idx_saved_searches_notify_enabled ON public.saved_searches USING btree (notify_enabled) WHERE (notify_enabled = true);
CREATE INDEX idx_saved_searches_search_type ON public.saved_searches USING btree (search_type);
CREATE INDEX idx_saved_searches_user_id ON public.saved_searches USING btree (user_id);
CREATE INDEX idx_search_behavior_metrics_conversions ON public.search_behavior_metrics USING btree (conversions DESC);
CREATE INDEX idx_search_behavior_metrics_ctr ON public.search_behavior_metrics USING btree (ctr DESC);
CREATE INDEX idx_search_behavior_metrics_period ON public.search_behavior_metrics USING btree (period_start, period_end);
CREATE INDEX idx_search_behavior_metrics_query ON public.search_behavior_metrics USING btree (search_query);
CREATE UNIQUE INDEX idx_search_behavior_metrics_unique ON public.search_behavior_metrics USING btree (search_query, period_start);
CREATE INDEX idx_search_optimization_sessions_created_by ON public.search_optimization_sessions USING btree (created_by);
CREATE INDEX idx_search_optimization_sessions_start_time ON public.search_optimization_sessions USING btree (start_time);
CREATE INDEX idx_search_optimization_sessions_status ON public.search_optimization_sessions USING btree (status);
CREATE INDEX idx_search_queries_language ON public.search_queries USING btree (language);
CREATE INDEX idx_search_queries_normalized_query ON public.search_queries USING btree (normalized_query);
CREATE INDEX idx_search_queries_search_count ON public.search_queries USING btree (search_count DESC);
CREATE INDEX idx_search_synonyms_active ON public.search_synonyms USING btree (is_active) WHERE (is_active = true);
CREATE INDEX idx_search_synonyms_config_term ON public.search_synonyms_config USING btree (term);
CREATE INDEX idx_search_synonyms_language ON public.search_synonyms USING btree (language);
CREATE INDEX idx_search_synonyms_synonym ON public.search_synonyms USING btree (synonym);
CREATE INDEX idx_search_synonyms_term ON public.search_synonyms USING btree (term);
CREATE UNIQUE INDEX idx_search_synonyms_unique ON public.search_synonyms USING btree (term, synonym, language) WHERE (is_active = true);
CREATE INDEX idx_search_weights_category_id ON public.search_weights USING btree (category_id) WHERE (category_id IS NOT NULL);
CREATE INDEX idx_search_weights_field_name ON public.search_weights USING btree (field_name);
CREATE INDEX idx_search_weights_history_changed_at ON public.search_weights_history USING btree (changed_at);
CREATE INDEX idx_search_weights_history_changed_by ON public.search_weights_history USING btree (changed_by);
CREATE INDEX idx_search_weights_history_weight_id ON public.search_weights_history USING btree (weight_id);
CREATE INDEX idx_search_weights_is_active ON public.search_weights USING btree (is_active) WHERE (is_active = true);
CREATE INDEX idx_search_weights_item_type ON public.search_weights USING btree (item_type);
CREATE UNIQUE INDEX idx_search_weights_unique_category ON public.search_weights USING btree (field_name, item_type, search_type, category_id) WHERE (category_id IS NOT NULL);
CREATE UNIQUE INDEX idx_search_weights_unique_global ON public.search_weights USING btree (field_name, item_type, search_type) WHERE (category_id IS NULL);
CREATE INDEX idx_shopping_cart_items_cart_id ON public.shopping_cart_items USING btree (cart_id);
CREATE INDEX idx_shopping_cart_items_product_id ON public.shopping_cart_items USING btree (product_id);
CREATE INDEX idx_shopping_carts_session_id ON public.shopping_carts USING btree (session_id);
CREATE INDEX idx_shopping_carts_storefront_id ON public.shopping_carts USING btree (storefront_id);
CREATE INDEX idx_shopping_carts_user_id ON public.shopping_carts USING btree (user_id);
CREATE INDEX idx_staff_storefront_id ON public.storefront_staff USING btree (storefront_id);
CREATE INDEX idx_staff_user_id ON public.storefront_staff USING btree (user_id);
CREATE INDEX idx_storefront_category_mappings_source_path ON public.storefront_category_mappings USING btree (storefront_id, source_category_path);
CREATE INDEX idx_storefront_category_mappings_storefront ON public.storefront_category_mappings USING btree (storefront_id);
CREATE INDEX idx_storefront_category_mappings_target_category ON public.storefront_category_mappings USING btree (target_category_id);
CREATE INDEX idx_storefront_favorites_created_at ON public.storefront_favorites USING btree (created_at DESC);
CREATE INDEX idx_storefront_favorites_product_id ON public.storefront_favorites USING btree (product_id);
CREATE INDEX idx_storefront_favorites_user_id ON public.storefront_favorites USING btree (user_id);
CREATE INDEX idx_storefront_inventory_movements_created_at ON public.storefront_inventory_movements USING btree (created_at);
CREATE INDEX idx_storefront_inventory_movements_product_id ON public.storefront_inventory_movements USING btree (storefront_product_id);
CREATE INDEX idx_storefront_inventory_movements_type ON public.storefront_inventory_movements USING btree (type);
CREATE INDEX idx_storefront_inventory_movements_variant_id ON public.storefront_inventory_movements USING btree (variant_id) WHERE (variant_id IS NOT NULL);
CREATE INDEX idx_storefront_order_items_order_id ON public.storefront_order_items USING btree (order_id);
CREATE INDEX idx_storefront_order_items_product_id ON public.storefront_order_items USING btree (product_id);
CREATE INDEX idx_storefront_order_items_variant_id ON public.storefront_order_items USING btree (variant_id);
CREATE INDEX idx_storefront_orders_customer ON public.storefront_orders USING btree (customer_id, created_at DESC);
CREATE INDEX idx_storefront_orders_escrow_date ON public.storefront_orders USING btree (escrow_release_date) WHERE (escrow_release_date IS NOT NULL);
CREATE INDEX idx_storefront_orders_status ON public.storefront_orders USING btree (status);
CREATE INDEX idx_storefront_orders_storefront ON public.storefront_orders USING btree (storefront_id, created_at DESC);
CREATE INDEX idx_storefront_product_attributes_attribute_id ON public.storefront_product_attributes USING btree (attribute_id);
CREATE INDEX idx_storefront_product_attributes_enabled ON public.storefront_product_attributes USING btree (is_enabled);
CREATE INDEX idx_storefront_product_attributes_product_id ON public.storefront_product_attributes USING btree (product_id);
CREATE INDEX idx_storefront_product_images_display_order ON public.storefront_product_images USING btree (display_order);
CREATE INDEX idx_storefront_product_images_product_id ON public.storefront_product_images USING btree (storefront_product_id);
CREATE INDEX idx_storefront_product_variant_images_is_main ON public.storefront_product_variant_images USING btree (is_main);
CREATE INDEX idx_storefront_product_variant_images_variant_id ON public.storefront_product_variant_images USING btree (variant_id);
CREATE INDEX idx_storefront_product_variants_attributes_gin ON public.storefront_product_variants USING gin (variant_attributes);
CREATE INDEX idx_storefront_product_variants_barcode ON public.storefront_product_variants USING btree (barcode) WHERE (barcode IS NOT NULL);
CREATE UNIQUE INDEX idx_storefront_product_variants_default_unique ON public.storefront_product_variants USING btree (product_id) WHERE (is_default = true);
CREATE INDEX idx_storefront_product_variants_is_active ON public.storefront_product_variants USING btree (is_active);
CREATE INDEX idx_storefront_product_variants_is_default ON public.storefront_product_variants USING btree (is_default);
CREATE INDEX idx_storefront_product_variants_product_id ON public.storefront_product_variants USING btree (product_id);
CREATE INDEX idx_storefront_product_variants_sku ON public.storefront_product_variants USING btree (sku) WHERE (sku IS NOT NULL);
CREATE INDEX idx_storefront_products_barcode ON public.storefront_products USING btree (barcode) WHERE (barcode IS NOT NULL);
CREATE INDEX idx_storefront_products_category_id ON public.storefront_products USING btree (category_id);
CREATE INDEX idx_storefront_products_has_variants ON public.storefront_products USING btree (has_variants);
CREATE INDEX idx_storefront_products_is_active ON public.storefront_products USING btree (is_active);
CREATE INDEX idx_storefront_products_name_gin ON public.storefront_products USING gin (to_tsvector('simple'::regconfig, (name)::text));
CREATE INDEX idx_storefront_products_privacy ON public.storefront_products USING btree (location_privacy);
CREATE INDEX idx_storefront_products_show_on_map ON public.storefront_products USING btree (show_on_map);
CREATE INDEX idx_storefront_products_sku ON public.storefront_products USING btree (sku) WHERE (sku IS NOT NULL);
CREATE INDEX idx_storefront_products_stock_status ON public.storefront_products USING btree (stock_status);
CREATE INDEX idx_storefront_products_storefront_id ON public.storefront_products USING btree (storefront_id);
CREATE INDEX idx_storefront_products_storefront_id_view_count ON public.storefront_products USING btree (storefront_id, view_count);
