CREATE INDEX idx_vin_accident_history_vin ON public.vin_accident_history USING btree (vin);
CREATE INDEX idx_vin_check_history_checked_at ON public.vin_check_history USING btree (checked_at DESC);
CREATE INDEX idx_vin_check_history_listing_id ON public.vin_check_history USING btree (listing_id);
CREATE INDEX idx_vin_check_history_user_id ON public.vin_check_history USING btree (user_id);
CREATE INDEX idx_vin_check_history_vin ON public.vin_check_history USING btree (vin);
CREATE INDEX idx_vin_decode_cache_make_model ON public.vin_decode_cache USING btree (make, model);
CREATE INDEX idx_vin_decode_cache_year ON public.vin_decode_cache USING btree (year);
CREATE INDEX idx_vin_ownership_history_vin ON public.vin_ownership_history USING btree (vin);
CREATE INDEX idx_vin_recalls_vin ON public.vin_recalls USING btree (vin);
CREATE INDEX idx_websocket_connections_active ON public.tracking_websocket_connections USING btree (delivery_id) WHERE (disconnected_at IS NULL);
CREATE INDEX user_b2c_stores_status_idx ON public.user_b2c_stores USING btree (status);
CREATE INDEX user_b2c_stores_user_id_idx ON public.user_b2c_stores USING btree (user_id);
CREATE UNIQUE INDEX user_rating_summary_user_id_idx ON public.user_rating_summary USING btree (user_id);
CREATE UNIQUE INDEX user_ratings_user_id_idx ON public.user_ratings USING btree (user_id);
SELECT pg_catalog.setval('public.ai_category_decisions_id_seq', 129, true);
SELECT pg_catalog.setval('public.attribute_group_items_id_seq', 2, true);
SELECT pg_catalog.setval('public.attribute_groups_id_seq', 24, true);
SELECT pg_catalog.setval('public.attribute_option_translations_id_seq', 3699, true);
SELECT pg_catalog.setval('public.b2c_delivery_options_id_seq', 1, false);
SELECT pg_catalog.setval('public.b2c_inventory_movements_id_seq', 1, false);
SELECT pg_catalog.setval('public.b2c_order_items_id_seq', 1, false);
SELECT pg_catalog.setval('public.b2c_orders_id_seq', 1, false);
SELECT pg_catalog.setval('public.b2c_payment_methods_id_seq', 40, false);
SELECT pg_catalog.setval('public.b2c_product_attributes_id_seq', 1, false);
SELECT pg_catalog.setval('public.b2c_product_images_id_seq', 11, true);
SELECT pg_catalog.setval('public.b2c_product_variant_images_id_seq', 1, false);
SELECT pg_catalog.setval('public.b2c_product_variants_id_seq', 1, false);
SELECT pg_catalog.setval('public.b2c_store_hours_id_seq', 66, false);
SELECT pg_catalog.setval('public.b2c_store_staff_id_seq', 22, false);
SELECT pg_catalog.setval('public.b2c_stores_id_seq', 44, false);
SELECT pg_catalog.setval('public.balance_transactions_id_seq', 26, false);
SELECT pg_catalog.setval('public.bex_configuration_id_seq', 7, true);
SELECT pg_catalog.setval('public.bex_shipments_id_seq', 1, false);
SELECT pg_catalog.setval('public.bex_tracking_events_id_seq', 1, false);
SELECT pg_catalog.setval('public.c2c_categories_id_seq', 10233, true);
SELECT pg_catalog.setval('public.c2c_chats_id_seq', 22, true);
SELECT pg_catalog.setval('public.c2c_images_id_seq', 4, true);
SELECT pg_catalog.setval('public.c2c_listing_variants_id_seq', 1, false);
SELECT pg_catalog.setval('public.c2c_messages_id_seq', 110, true);
SELECT pg_catalog.setval('public.c2c_orders_id_seq', 1, false);
SELECT pg_catalog.setval('public.car_generations_id_seq', 1, false);
SELECT pg_catalog.setval('public.car_makes_id_seq', 115, true);
SELECT pg_catalog.setval('public.car_market_analysis_id_seq', 250, true);
SELECT pg_catalog.setval('public.car_models_id_seq', 3874, true);
SELECT pg_catalog.setval('public.category_ai_mappings_id_seq', 471, true);
SELECT pg_catalog.setval('public.category_attribute_groups_id_seq', 1, false);
SELECT pg_catalog.setval('public.category_detection_cache_id_seq', 1, false);
SELECT pg_catalog.setval('public.category_detection_feedback_id_seq', 454, true);
SELECT pg_catalog.setval('public.category_keyword_weights_id_seq', 197, true);
SELECT pg_catalog.setval('public.category_keywords_id_seq', 1166, true);
SELECT pg_catalog.setval('public.category_proposals_id_seq', 1, false);
SELECT pg_catalog.setval('public.category_variant_attributes_id_seq', 12, true);
SELECT pg_catalog.setval('public.chat_attachments_id_seq', 147, true);
SELECT pg_catalog.setval('public.component_templates_id_seq', 1, false);
SELECT pg_catalog.setval('public.courier_location_history_id_seq', 1, false);
SELECT pg_catalog.setval('public.courier_zones_id_seq', 1, false);
SELECT pg_catalog.setval('public.couriers_id_seq', 1, true);
SELECT pg_catalog.setval('public.deliveries_id_seq', 3, true);
SELECT pg_catalog.setval('public.delivery_category_defaults_id_seq', 70, true);
SELECT pg_catalog.setval('public.delivery_notifications_id_seq', 1, false);
SELECT pg_catalog.setval('public.delivery_pricing_rules_id_seq', 1, true);
SELECT pg_catalog.setval('public.delivery_providers_id_seq', 6, true);
SELECT pg_catalog.setval('public.delivery_shipments_id_seq', 1, false);
SELECT pg_catalog.setval('public.delivery_tracking_events_id_seq', 1, false);
SELECT pg_catalog.setval('public.delivery_zones_id_seq', 4, true);
SELECT pg_catalog.setval('public.escrow_payments_id_seq', 1, false);
SELECT pg_catalog.setval('public.geocoding_cache_id_seq', 19, true);
SELECT pg_catalog.setval('public.global_product_id_seq', 1076, true);
SELECT pg_catalog.setval('public.import_history_id_seq', 1, false);
SELECT pg_catalog.setval('public.imported_categories_id_seq', 1, false);
SELECT pg_catalog.setval('public.inventory_reservations_id_seq', 20, true);
SELECT pg_catalog.setval('public.item_performance_metrics_id_seq', 1, false);
SELECT pg_catalog.setval('public.listing_attribute_values_id_seq', 81, true);
SELECT pg_catalog.setval('public.listing_views_id_seq', 7, true);
SELECT pg_catalog.setval('public.map_items_cache_id_seq', 1, false);
SELECT pg_catalog.setval('public.merchant_payouts_id_seq', 1, false);
SELECT pg_catalog.setval('public.notification_templates_id_seq', 8, true);
SELECT pg_catalog.setval('public.notifications_id_seq', 186, true);
SELECT pg_catalog.setval('public.payment_gateways_id_seq', 2, false);
SELECT pg_catalog.setval('public.payment_methods_id_seq', 27, false);
SELECT pg_catalog.setval('public.payment_transactions_id_seq', 1, false);
SELECT pg_catalog.setval('public.permissions_id_seq', 86, true);
SELECT pg_catalog.setval('public.post_express_locations_id_seq', 5, true);
SELECT pg_catalog.setval('public.post_express_offices_id_seq', 1, false);
SELECT pg_catalog.setval('public.post_express_rates_id_seq', 5, true);
SELECT pg_catalog.setval('public.post_express_settings_id_seq', 1, true);
SELECT pg_catalog.setval('public.post_express_shipments_id_seq', 3, true);
SELECT pg_catalog.setval('public.post_express_tracking_events_id_seq', 1, false);
SELECT pg_catalog.setval('public.price_history_id_seq', 862, true);
SELECT pg_catalog.setval('public.product_variant_attribute_values_id_seq', 37, true);
SELECT pg_catalog.setval('public.product_variant_attributes_id_seq', 36, true);
SELECT pg_catalog.setval('public.query_cache_id_seq', 1, false);
SELECT pg_catalog.setval('public.review_confirmations_id_seq', 1, false);
SELECT pg_catalog.setval('public.review_disputes_id_seq', 1, false);
SELECT pg_catalog.setval('public.review_responses_id_seq', 1, false);
SELECT pg_catalog.setval('public.reviews_id_seq', 24, true);
SELECT pg_catalog.setval('public.role_audit_log_id_seq', 5, true);
SELECT pg_catalog.setval('public.roles_id_seq', 30, true);
SELECT pg_catalog.setval('public.saved_search_notifications_id_seq', 1, false);
SELECT pg_catalog.setval('public.saved_searches_id_seq', 1, false);
