CREATE INDEX idx_variant_mappings_category ON public.variant_attribute_mappings USING btree (category_id);
CREATE INDEX idx_viber_sessions_active ON public.viber_sessions USING btree (viber_user_id, active) WHERE (active = true);
CREATE INDEX idx_viber_sessions_expires ON public.viber_sessions USING btree (expires_at) WHERE (active = true);
CREATE INDEX idx_viber_users_user_id ON public.viber_users USING btree (user_id);
CREATE INDEX idx_viber_users_viber_id ON public.viber_users USING btree (viber_id);
CREATE INDEX idx_view_statistics_category_date ON public.view_statistics USING btree (category_id, date DESC);
CREATE INDEX idx_view_statistics_listing_date ON public.view_statistics USING btree (listing_id, date DESC);
CREATE INDEX idx_vin_accident_history_vin ON public.vin_accident_history USING btree (vin);
CREATE INDEX idx_vin_check_history_checked_at ON public.vin_check_history USING btree (checked_at DESC);
CREATE INDEX idx_vin_check_history_listing_id ON public.vin_check_history USING btree (listing_id);
CREATE INDEX idx_vin_check_history_user_id ON public.vin_check_history USING btree (user_id);
CREATE INDEX idx_vin_check_history_vin ON public.vin_check_history USING btree (vin);
CREATE INDEX idx_vin_decode_cache_make_model ON public.vin_decode_cache USING btree (make, model);
CREATE INDEX idx_vin_decode_cache_vin ON public.vin_decode_cache USING btree (vin);
CREATE INDEX idx_vin_decode_cache_year ON public.vin_decode_cache USING btree (year);
CREATE INDEX idx_vin_ownership_history_vin ON public.vin_ownership_history USING btree (vin);
CREATE INDEX idx_vin_recalls_vin ON public.vin_recalls USING btree (vin);
CREATE INDEX idx_websocket_connections_active ON public.tracking_websocket_connections USING btree (delivery_id) WHERE (disconnected_at IS NULL);
CREATE UNIQUE INDEX storefront_rating_distribution_storefront_id_idx ON public.storefront_rating_distribution USING btree (storefront_id);
CREATE UNIQUE INDEX storefront_rating_summary_storefront_id_idx ON public.storefront_rating_summary USING btree (storefront_id);
CREATE UNIQUE INDEX storefront_ratings_storefront_id_idx ON public.storefront_ratings USING btree (storefront_id);
CREATE UNIQUE INDEX unique_storefront_product_barcode ON public.storefront_products USING btree (storefront_id, barcode) WHERE (barcode IS NOT NULL);
CREATE UNIQUE INDEX unique_storefront_product_sku ON public.storefront_products USING btree (storefront_id, sku) WHERE (sku IS NOT NULL);
CREATE UNIQUE INDEX user_rating_summary_user_id_idx ON public.user_rating_summary USING btree (user_id);
CREATE UNIQUE INDEX user_ratings_user_id_idx ON public.user_ratings USING btree (user_id);
SELECT pg_catalog.setval('public.address_change_log_id_seq', 1, false);
SELECT pg_catalog.setval('public.ai_category_decisions_id_seq', 121, true);
SELECT pg_catalog.setval('public.attribute_group_items_id_seq', 2, true);
SELECT pg_catalog.setval('public.attribute_groups_id_seq', 24, true);
SELECT pg_catalog.setval('public.attribute_option_translations_id_seq', 3699, true);
SELECT pg_catalog.setval('public.balance_transactions_id_seq', 26, false);
SELECT pg_catalog.setval('public.bex_configuration_id_seq', 7, true);
SELECT pg_catalog.setval('public.bex_shipments_id_seq', 1, false);
SELECT pg_catalog.setval('public.bex_tracking_events_id_seq', 1, false);
SELECT pg_catalog.setval('public.car_generations_id_seq', 1, false);
SELECT pg_catalog.setval('public.car_makes_id_seq', 115, true);
SELECT pg_catalog.setval('public.car_market_analysis_id_seq', 250, true);
SELECT pg_catalog.setval('public.car_models_id_seq', 3874, true);
SELECT pg_catalog.setval('public.category_ai_mappings_id_seq', 471, true);
SELECT pg_catalog.setval('public.category_attribute_groups_id_seq', 1, false);
SELECT pg_catalog.setval('public.category_detection_cache_id_seq', 1, false);
SELECT pg_catalog.setval('public.category_detection_feedback_id_seq', 444, true);
SELECT pg_catalog.setval('public.category_keyword_weights_id_seq', 197, true);
SELECT pg_catalog.setval('public.category_keywords_id_seq', 1166, true);
SELECT pg_catalog.setval('public.category_proposals_id_seq', 9, true);
SELECT pg_catalog.setval('public.category_variant_attributes_id_seq', 12, true);
SELECT pg_catalog.setval('public.chat_attachments_id_seq', 147, true);
SELECT pg_catalog.setval('public.component_templates_id_seq', 1, false);
SELECT pg_catalog.setval('public.courier_location_history_id_seq', 1, false);
SELECT pg_catalog.setval('public.courier_zones_id_seq', 1, false);
SELECT pg_catalog.setval('public.couriers_id_seq', 1, true);
SELECT pg_catalog.setval('public.custom_ui_component_usage_id_seq', 1, false);
SELECT pg_catalog.setval('public.custom_ui_components_id_seq', 2, false);
SELECT pg_catalog.setval('public.custom_ui_templates_id_seq', 1, false);
SELECT pg_catalog.setval('public.deliveries_id_seq', 1, false);
SELECT pg_catalog.setval('public.delivery_category_defaults_id_seq', 70, true);
SELECT pg_catalog.setval('public.delivery_notifications_id_seq', 1, false);
SELECT pg_catalog.setval('public.delivery_pricing_rules_id_seq', 1, true);
SELECT pg_catalog.setval('public.delivery_providers_id_seq', 6, true);
SELECT pg_catalog.setval('public.delivery_shipments_id_seq', 1, false);
SELECT pg_catalog.setval('public.delivery_tracking_events_id_seq', 1, false);
SELECT pg_catalog.setval('public.delivery_zones_id_seq', 4, true);
SELECT pg_catalog.setval('public.escrow_payments_id_seq', 1, false);
SELECT pg_catalog.setval('public.geocoding_cache_id_seq', 19, true);
SELECT pg_catalog.setval('public.gis_filter_analytics_id_seq', 1, false);
SELECT pg_catalog.setval('public.gis_isochrone_cache_id_seq', 1, false);
SELECT pg_catalog.setval('public.gis_poi_cache_id_seq', 1, false);
SELECT pg_catalog.setval('public.global_product_id_seq', 1001, true);
SELECT pg_catalog.setval('public.import_errors_id_seq', 41, true);
SELECT pg_catalog.setval('public.import_history_id_seq', 1, false);
SELECT pg_catalog.setval('public.import_jobs_id_seq', 55, true);
SELECT pg_catalog.setval('public.import_sources_id_seq', 1, false);
SELECT pg_catalog.setval('public.imported_categories_id_seq', 1, false);
SELECT pg_catalog.setval('public.inventory_reservations_id_seq', 20, true);
SELECT pg_catalog.setval('public.item_performance_metrics_id_seq', 1, false);
SELECT pg_catalog.setval('public.listing_attribute_values_id_seq', 79, true);
SELECT pg_catalog.setval('public.listing_views_id_seq', 7, true);
SELECT pg_catalog.setval('public.listings_geo_id_seq', 46, true);
SELECT pg_catalog.setval('public.map_items_cache_id_seq', 1, false);
SELECT pg_catalog.setval('public.marketplace_categories_id_seq', 10232, true);
SELECT pg_catalog.setval('public.marketplace_chats_id_seq', 28, true);
SELECT pg_catalog.setval('public.marketplace_images_id_seq', 714, true);
SELECT pg_catalog.setval('public.marketplace_listing_variants_id_seq', 1, false);
SELECT pg_catalog.setval('public.marketplace_messages_id_seq', 166, true);
SELECT pg_catalog.setval('public.marketplace_orders_id_seq', 1, false);
SELECT pg_catalog.setval('public.merchant_payouts_id_seq', 1, false);
SELECT pg_catalog.setval('public.notification_templates_id_seq', 8, true);
SELECT pg_catalog.setval('public.notifications_id_seq', 180, true);
SELECT pg_catalog.setval('public.payment_gateways_id_seq', 2, false);
SELECT pg_catalog.setval('public.payment_methods_id_seq', 27, false);
SELECT pg_catalog.setval('public.payment_transactions_id_seq', 1, false);
SELECT pg_catalog.setval('public.permissions_id_seq', 86, true);
SELECT pg_catalog.setval('public.post_express_locations_id_seq', 5, true);
SELECT pg_catalog.setval('public.post_express_offices_id_seq', 1, false);
SELECT pg_catalog.setval('public.post_express_rates_id_seq', 5, true);
SELECT pg_catalog.setval('public.post_express_settings_id_seq', 1, true);
SELECT pg_catalog.setval('public.post_express_shipments_id_seq', 3, true);
SELECT pg_catalog.setval('public.post_express_tracking_events_id_seq', 1, false);
SELECT pg_catalog.setval('public.price_history_id_seq', 798, true);
SELECT pg_catalog.setval('public.product_variant_attribute_values_id_seq', 37, true);
