ALTER TABLE public.listings_geo DISABLE TRIGGER trigger_assign_district_municipality;
CREATE TRIGGER trigger_auto_geocode_storefront_product AFTER INSERT OR UPDATE ON public.storefront_products FOR EACH ROW EXECUTE FUNCTION public.auto_geocode_storefront_product();
CREATE TRIGGER trigger_cleanup_geocoding_cache AFTER INSERT ON public.geocoding_cache FOR EACH STATEMENT EXECUTE FUNCTION public.trigger_cleanup_geocoding_cache();
CREATE TRIGGER trigger_cleanup_storefront_product_geo AFTER DELETE ON public.storefront_products FOR EACH ROW EXECUTE FUNCTION public.cleanup_unified_geo();
CREATE TRIGGER trigger_geocoding_cache_updated_at BEFORE UPDATE ON public.geocoding_cache FOR EACH ROW EXECUTE FUNCTION public.update_geocoding_cache_updated_at();
CREATE TRIGGER trigger_listings_geo_updated_at BEFORE UPDATE ON public.listings_geo FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER trigger_log_role_change AFTER UPDATE ON public.users FOR EACH ROW EXECUTE FUNCTION public.log_role_change();
CREATE TRIGGER trigger_log_search_weight_changes AFTER UPDATE ON public.search_weights FOR EACH ROW EXECUTE FUNCTION public.log_search_weight_changes();
CREATE TRIGGER trigger_marketplace_listings_cache_refresh AFTER INSERT OR DELETE OR UPDATE ON public.marketplace_listings FOR EACH ROW EXECUTE FUNCTION public.trigger_refresh_map_cache();
CREATE TRIGGER trigger_refresh_rating_distributions AFTER INSERT OR DELETE OR UPDATE ON public.reviews FOR EACH STATEMENT EXECUTE FUNCTION public.refresh_rating_distributions();
CREATE TRIGGER trigger_shopping_cart_items_updated_at BEFORE UPDATE ON public.shopping_cart_items FOR EACH ROW EXECUTE FUNCTION public.update_shopping_cart_updated_at();
CREATE TRIGGER trigger_shopping_carts_updated_at BEFORE UPDATE ON public.shopping_carts FOR EACH ROW EXECUTE FUNCTION public.update_shopping_cart_updated_at();
CREATE TRIGGER trigger_storefront_products_cache_refresh AFTER INSERT OR DELETE OR UPDATE ON public.storefront_products FOR EACH ROW EXECUTE FUNCTION public.trigger_refresh_map_cache();
CREATE TRIGGER trigger_unified_geo_cache_refresh AFTER INSERT OR DELETE OR UPDATE ON public.unified_geo FOR EACH ROW EXECUTE FUNCTION public.trigger_refresh_map_cache();
CREATE TRIGGER trigger_update_inventory_reservations_updated_at BEFORE UPDATE ON public.inventory_reservations FOR EACH ROW EXECUTE FUNCTION public.update_inventory_reservations_updated_at();
CREATE TRIGGER trigger_update_item_performance_metrics_updated_at BEFORE UPDATE ON public.item_performance_metrics FOR EACH ROW EXECUTE FUNCTION public.update_item_performance_metrics_updated_at();
CREATE TRIGGER trigger_update_listings_geo_updated_at BEFORE UPDATE ON public.listings_geo FOR EACH ROW EXECUTE FUNCTION public.update_listings_geo_updated_at();
CREATE TRIGGER trigger_update_product_variant_attribute_values_updated_at BEFORE UPDATE ON public.product_variant_attribute_values FOR EACH ROW EXECUTE FUNCTION public.update_product_variants_updated_at();
CREATE TRIGGER trigger_update_product_variant_attributes_updated_at BEFORE UPDATE ON public.product_variant_attributes FOR EACH ROW EXECUTE FUNCTION public.update_product_variants_updated_at();
CREATE TRIGGER trigger_update_search_behavior_metrics_updated_at BEFORE UPDATE ON public.search_behavior_metrics FOR EACH ROW EXECUTE FUNCTION public.update_search_behavior_metrics_updated_at();
CREATE TRIGGER trigger_update_search_optimization_sessions_updated_at BEFORE UPDATE ON public.search_optimization_sessions FOR EACH ROW EXECUTE FUNCTION public.update_search_optimization_sessions_updated_at();
CREATE TRIGGER trigger_update_search_synonyms_updated_at BEFORE UPDATE ON public.search_synonyms FOR EACH ROW EXECUTE FUNCTION public.update_search_synonyms_updated_at();
CREATE TRIGGER trigger_update_search_weights_updated_at BEFORE UPDATE ON public.search_weights FOR EACH ROW EXECUTE FUNCTION public.update_search_weights_updated_at();
CREATE TRIGGER trigger_update_storefront_product_variants_updated_at BEFORE UPDATE ON public.storefront_product_variants FOR EACH ROW EXECUTE FUNCTION public.update_product_variants_updated_at();
CREATE TRIGGER trigger_update_storefront_products_geo AFTER UPDATE ON public.storefronts FOR EACH ROW EXECUTE FUNCTION public.update_storefront_products_geo();
CREATE TRIGGER trigger_update_transliteration_rules_updated_at BEFORE UPDATE ON public.transliteration_rules FOR EACH ROW EXECUTE FUNCTION public.update_transliteration_rules_updated_at();
CREATE TRIGGER trigger_update_unified_geo_updated_at BEFORE UPDATE ON public.unified_geo FOR EACH ROW EXECUTE FUNCTION public.update_unified_geo_updated_at();
CREATE TRIGGER update_car_generations_updated_at BEFORE UPDATE ON public.car_generations FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER update_car_makes_updated_at BEFORE UPDATE ON public.car_makes FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER update_car_models_updated_at BEFORE UPDATE ON public.car_models FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER update_category_keywords_updated_at BEFORE UPDATE ON public.category_keywords FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER update_category_variant_attributes_updated_at BEFORE UPDATE ON public.category_variant_attributes FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER update_custom_ui_component_usage_updated_at BEFORE UPDATE ON public.custom_ui_component_usage FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER update_has_variants_trigger AFTER INSERT OR DELETE ON public.storefront_product_variants FOR EACH ROW EXECUTE FUNCTION public.update_product_has_variants();
CREATE TRIGGER update_listings_on_attribute_translation_change AFTER INSERT OR UPDATE ON public.attribute_option_translations FOR EACH ROW EXECUTE FUNCTION public.trigger_update_listings_on_attribute_translation_change();
CREATE TRIGGER update_marketplace_chats_timestamp BEFORE UPDATE ON public.marketplace_chats FOR EACH ROW EXECUTE FUNCTION public.update_marketplace_chats_updated_at();
CREATE TRIGGER update_marketplace_messages_timestamp BEFORE UPDATE ON public.marketplace_messages FOR EACH ROW EXECUTE FUNCTION public.update_marketplace_chats_updated_at();
CREATE TRIGGER update_notification_settings_timestamp BEFORE UPDATE ON public.notification_settings FOR EACH ROW EXECUTE FUNCTION public.update_notification_settings_updated_at();
CREATE TRIGGER update_ratings_after_review_change AFTER INSERT OR DELETE OR UPDATE ON public.reviews FOR EACH ROW EXECUTE FUNCTION public.refresh_rating_views();
CREATE TRIGGER update_review_responses_updated_at BEFORE UPDATE ON public.review_responses FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER update_reviews_updated_at BEFORE UPDATE ON public.reviews FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER update_search_queries_updated_at_trigger BEFORE UPDATE ON public.search_queries FOR EACH ROW EXECUTE FUNCTION public.update_search_queries_updated_at();
CREATE TRIGGER update_stock_status_trigger BEFORE INSERT OR UPDATE OF stock_quantity ON public.storefront_products FOR EACH ROW EXECUTE FUNCTION public.update_product_stock_status();
CREATE TRIGGER update_storefront_order_items_updated_at BEFORE UPDATE ON public.storefront_order_items FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER update_storefront_usage AFTER INSERT OR DELETE ON public.storefronts FOR EACH ROW EXECUTE FUNCTION public.update_subscription_usage();
CREATE TRIGGER update_translation_providers_timestamp BEFORE UPDATE ON public.translation_providers FOR EACH ROW EXECUTE FUNCTION public.update_translation_providers_updated_at();
CREATE TRIGGER update_translations_timestamp BEFORE UPDATE ON public.translations FOR EACH ROW EXECUTE FUNCTION public.update_translations_updated_at();
CREATE TRIGGER update_unified_attribute_values_updated_at BEFORE UPDATE ON public.unified_attribute_values FOR EACH ROW EXECUTE FUNCTION public.update_unified_attributes_updated_at();
CREATE TRIGGER update_unified_attributes_updated_at BEFORE UPDATE ON public.unified_attributes FOR EACH ROW EXECUTE FUNCTION public.update_unified_attributes_updated_at();
CREATE TRIGGER update_unified_category_attributes_updated_at BEFORE UPDATE ON public.unified_category_attributes FOR EACH ROW EXECUTE FUNCTION public.update_unified_attributes_updated_at();
CREATE TRIGGER update_user_contacts_updated_at BEFORE UPDATE ON public.user_contacts FOR EACH ROW EXECUTE FUNCTION public.update_user_contacts_updated_at();
CREATE TRIGGER update_user_privacy_settings_updated_at BEFORE UPDATE ON public.user_privacy_settings FOR EACH ROW EXECUTE FUNCTION public.update_user_privacy_settings_updated_at();
CREATE TRIGGER update_users_updated_at BEFORE UPDATE ON public.users FOR EACH ROW EXECUTE FUNCTION public.update_user_updated_at();
ALTER SEQUENCE public.address_change_log_id_seq OWNED BY public.address_change_log.id;
ALTER SEQUENCE public.admin_users_id_seq OWNED BY public.admin_users.id;
ALTER SEQUENCE public.attribute_group_items_id_seq OWNED BY public.attribute_group_items.id;
ALTER SEQUENCE public.attribute_option_translations_id_seq OWNED BY public.attribute_option_translations.id;
ALTER SEQUENCE public.balance_transactions_id_seq OWNED BY public.balance_transactions.id;
ALTER SEQUENCE public.car_generations_id_seq OWNED BY public.car_generations.id;
ALTER SEQUENCE public.car_makes_id_seq OWNED BY public.car_makes.id;
ALTER SEQUENCE public.car_market_analysis_id_seq OWNED BY public.car_market_analysis.id;
ALTER SEQUENCE public.car_models_id_seq OWNED BY public.car_models.id;
ALTER SEQUENCE public.category_attribute_groups_id_seq OWNED BY public.category_attribute_groups.id;
ALTER SEQUENCE public.category_keywords_id_seq OWNED BY public.category_keywords.id;
ALTER SEQUENCE public.category_variant_attributes_id_seq OWNED BY public.category_variant_attributes.id;
ALTER SEQUENCE public.chat_attachments_id_seq OWNED BY public.chat_attachments.id;
ALTER SEQUENCE public.component_templates_id_seq OWNED BY public.component_templates.id;
ALTER SEQUENCE public.custom_ui_component_usage_id_seq OWNED BY public.custom_ui_component_usage.id;
ALTER SEQUENCE public.custom_ui_components_id_seq OWNED BY public.custom_ui_components.id;
ALTER SEQUENCE public.custom_ui_templates_id_seq OWNED BY public.custom_ui_templates.id;
ALTER SEQUENCE public.escrow_payments_id_seq OWNED BY public.escrow_payments.id;
ALTER SEQUENCE public.geocoding_cache_id_seq OWNED BY public.geocoding_cache.id;
ALTER SEQUENCE public.gis_filter_analytics_id_seq OWNED BY public.gis_filter_analytics.id;
ALTER SEQUENCE public.gis_isochrone_cache_id_seq OWNED BY public.gis_isochrone_cache.id;
ALTER SEQUENCE public.gis_poi_cache_id_seq OWNED BY public.gis_poi_cache.id;
ALTER SEQUENCE public.import_history_id_seq OWNED BY public.import_history.id;
ALTER SEQUENCE public.import_sources_id_seq OWNED BY public.import_sources.id;
ALTER SEQUENCE public.imported_categories_id_seq OWNED BY public.imported_categories.id;
ALTER SEQUENCE public.inventory_reservations_id_seq OWNED BY public.inventory_reservations.id;
ALTER SEQUENCE public.item_performance_metrics_id_seq OWNED BY public.item_performance_metrics.id;
ALTER SEQUENCE public.listing_views_id_seq OWNED BY public.listing_views.id;
ALTER SEQUENCE public.listings_geo_id_seq OWNED BY public.listings_geo.id;
ALTER SEQUENCE public.map_items_cache_id_seq OWNED BY public.map_items_cache.id;
ALTER SEQUENCE public.marketplace_categories_id_seq OWNED BY public.marketplace_categories.id;
ALTER SEQUENCE public.marketplace_chats_id_seq OWNED BY public.marketplace_chats.id;
ALTER SEQUENCE public.marketplace_images_id_seq OWNED BY public.marketplace_images.id;
ALTER SEQUENCE public.marketplace_listing_variants_id_seq OWNED BY public.marketplace_listing_variants.id;
ALTER SEQUENCE public.marketplace_messages_id_seq OWNED BY public.marketplace_messages.id;
ALTER SEQUENCE public.marketplace_orders_id_seq OWNED BY public.marketplace_orders.id;
ALTER SEQUENCE public.merchant_payouts_id_seq OWNED BY public.merchant_payouts.id;
ALTER SEQUENCE public.notifications_id_seq OWNED BY public.notifications.id;
ALTER SEQUENCE public.payment_gateways_id_seq OWNED BY public.payment_gateways.id;
ALTER SEQUENCE public.payment_methods_id_seq OWNED BY public.payment_methods.id;
ALTER SEQUENCE public.payment_transactions_id_seq OWNED BY public.payment_transactions.id;
ALTER SEQUENCE public.permissions_id_seq OWNED BY public.permissions.id;
ALTER SEQUENCE public.price_history_id_seq OWNED BY public.price_history.id;
ALTER SEQUENCE public.product_variant_attribute_values_id_seq OWNED BY public.product_variant_attribute_values.id;
ALTER SEQUENCE public.product_variant_attributes_id_seq OWNED BY public.product_variant_attributes.id;
ALTER SEQUENCE public.query_cache_id_seq OWNED BY public.query_cache.id;
ALTER SEQUENCE public.refresh_tokens_id_seq OWNED BY public.refresh_tokens.id;
