CREATE INDEX idx_storefront_product_attributes_attribute_id ON public.storefront_product_attributes USING btree (attribute_id);
CREATE INDEX idx_storefront_product_attributes_enabled ON public.storefront_product_attributes USING btree (is_enabled);
CREATE INDEX idx_storefront_product_attributes_product_id ON public.storefront_product_attributes USING btree (product_id);
CREATE INDEX idx_storefront_product_images_display_order ON public.storefront_product_images USING btree (display_order);
CREATE INDEX idx_storefront_product_images_product_id ON public.storefront_product_images USING btree (storefront_product_id);
CREATE INDEX idx_storefront_product_variant_images_is_main ON public.storefront_product_variant_images USING btree (is_main);
CREATE INDEX idx_storefront_product_variant_images_variant_id ON public.storefront_product_variant_images USING btree (variant_id);
CREATE INDEX idx_storefront_product_variants_attributes_gin ON public.storefront_product_variants USING gin (variant_attributes);
CREATE INDEX idx_storefront_product_variants_barcode ON public.storefront_product_variants USING btree (barcode) WHERE (barcode IS NOT NULL);
CREATE UNIQUE INDEX idx_storefront_product_variants_default_unique ON public.storefront_product_variants USING btree (product_id) WHERE (is_default = true);
CREATE INDEX idx_storefront_product_variants_is_active ON public.storefront_product_variants USING btree (is_active);
CREATE INDEX idx_storefront_product_variants_is_default ON public.storefront_product_variants USING btree (is_default);
CREATE INDEX idx_storefront_product_variants_product_id ON public.storefront_product_variants USING btree (product_id);
CREATE INDEX idx_storefront_product_variants_sku ON public.storefront_product_variants USING btree (sku) WHERE (sku IS NOT NULL);
CREATE INDEX idx_storefront_products_barcode ON public.storefront_products USING btree (barcode) WHERE (barcode IS NOT NULL);
CREATE INDEX idx_storefront_products_category_id ON public.storefront_products USING btree (category_id);
CREATE INDEX idx_storefront_products_has_variants ON public.storefront_products USING btree (has_variants);
CREATE INDEX idx_storefront_products_is_active ON public.storefront_products USING btree (is_active);
CREATE INDEX idx_storefront_products_name_gin ON public.storefront_products USING gin (to_tsvector('simple'::regconfig, (name)::text));
CREATE INDEX idx_storefront_products_privacy ON public.storefront_products USING btree (location_privacy);
CREATE INDEX idx_storefront_products_show_on_map ON public.storefront_products USING btree (show_on_map);
CREATE INDEX idx_storefront_products_sku ON public.storefront_products USING btree (sku) WHERE (sku IS NOT NULL);
CREATE INDEX idx_storefront_products_stock_status ON public.storefront_products USING btree (stock_status);
CREATE INDEX idx_storefront_products_storefront_id ON public.storefront_products USING btree (storefront_id);
CREATE INDEX idx_storefronts_city ON public.storefronts USING btree (city);
CREATE INDEX idx_storefronts_coordinates ON public.storefronts USING btree (latitude, longitude) WHERE ((latitude IS NOT NULL) AND (longitude IS NOT NULL));
CREATE INDEX idx_storefronts_geo_strategy ON public.storefronts USING btree (geo_strategy);
CREATE INDEX idx_storefronts_is_active ON public.storefronts USING btree (is_active);
CREATE INDEX idx_storefronts_rating ON public.storefronts USING btree (rating DESC);
CREATE INDEX idx_storefronts_slug ON public.storefronts USING btree (slug);
CREATE INDEX idx_storefronts_user_id ON public.storefronts USING btree (user_id);
CREATE INDEX idx_sync_conflicts_dates ON public.translation_sync_conflicts USING btree (created_at DESC);
CREATE INDEX idx_sync_conflicts_unresolved ON public.translation_sync_conflicts USING btree (resolved) WHERE (resolved = false);
CREATE INDEX idx_transactions_created ON public.balance_transactions USING btree (created_at);
CREATE INDEX idx_transactions_status ON public.balance_transactions USING btree (status);
CREATE INDEX idx_transactions_user ON public.balance_transactions USING btree (user_id);
CREATE INDEX idx_translation_tasks_assigned ON public.translation_tasks USING btree (assigned_to, status);
CREATE INDEX idx_translation_tasks_status ON public.translation_tasks USING btree (status, created_at) WHERE ((status)::text <> 'completed'::text);
CREATE INDEX idx_translations_composite ON public.translations USING btree (entity_type, entity_id, language, field_name) WHERE (is_verified = true);
CREATE INDEX idx_translations_entity_field ON public.translations USING btree (entity_type, entity_id, field_name, language) WHERE ((entity_type)::text = 'listing'::text);
CREATE INDEX idx_translations_entity_lang_field ON public.translations USING btree (entity_type, language, field_name);
CREATE INDEX idx_translations_listing_all ON public.translations USING btree (entity_id, language) WHERE ((entity_type)::text = 'listing'::text);
CREATE INDEX idx_translations_lookup ON public.translations USING btree (entity_type, entity_id, language);
CREATE INDEX idx_translations_metadata ON public.translations USING gin (metadata);
CREATE INDEX idx_translations_type_lang ON public.translations USING btree (entity_type, language);
CREATE INDEX idx_transliteration_rules_active ON public.transliteration_rules USING btree (language, enabled, priority DESC);
CREATE INDEX idx_transliteration_rules_enabled ON public.transliteration_rules USING btree (enabled);
CREATE INDEX idx_transliteration_rules_language ON public.transliteration_rules USING btree (language);
CREATE INDEX idx_transliteration_rules_priority ON public.transliteration_rules USING btree (priority DESC);
CREATE INDEX idx_transliteration_rules_type ON public.transliteration_rules USING btree (rule_type);
CREATE INDEX idx_ui_comp_usage_active ON public.custom_ui_component_usage USING btree (is_active);
CREATE INDEX idx_ui_comp_usage_category ON public.custom_ui_component_usage USING btree (category_id);
CREATE INDEX idx_ui_comp_usage_component ON public.custom_ui_component_usage USING btree (component_id);
CREATE INDEX idx_ui_comp_usage_context ON public.custom_ui_component_usage USING btree (usage_context);
CREATE INDEX idx_unified_attr_stats_attr_id ON public.unified_attribute_stats USING btree (attribute_id);
CREATE INDEX idx_unified_attr_stats_category_id ON public.unified_attribute_stats USING btree (category_id);
CREATE INDEX idx_unified_attr_stats_usage ON public.unified_attribute_stats USING btree (usage_count DESC);
CREATE INDEX idx_unified_attr_values_numeric_ranges ON public.unified_attribute_values USING btree (attribute_id, numeric_value) WHERE (numeric_value IS NOT NULL);
CREATE INDEX idx_unified_attr_values_text_trgm ON public.unified_attribute_values USING gin (text_value public.gin_trgm_ops) WHERE (text_value IS NOT NULL);
CREATE INDEX idx_unified_attribute_values_attribute ON public.unified_attribute_values USING btree (attribute_id);
CREATE INDEX idx_unified_attribute_values_entity ON public.unified_attribute_values USING btree (entity_type, entity_id);
CREATE INDEX idx_unified_attribute_values_entity_with_type ON public.unified_attribute_values USING btree (entity_type, entity_id, attribute_id) INCLUDE (text_value, numeric_value, boolean_value, date_value);
CREATE INDEX idx_unified_attribute_values_numeric ON public.unified_attribute_values USING btree (numeric_value) WHERE (numeric_value IS NOT NULL);
CREATE INDEX idx_unified_attribute_values_text ON public.unified_attribute_values USING btree (text_value) WHERE (text_value IS NOT NULL);
CREATE INDEX idx_unified_attributes_active ON public.unified_attributes USING btree (is_active);
CREATE INDEX idx_unified_attributes_active_filterable ON public.unified_attributes USING btree (is_active, is_filterable) WHERE ((is_active = true) AND (is_filterable = true));
CREATE INDEX idx_unified_attributes_active_searchable ON public.unified_attributes USING btree (is_active, is_searchable) WHERE ((is_active = true) AND (is_searchable = true));
CREATE INDEX idx_unified_attributes_active_sort ON public.unified_attributes USING btree (is_active, sort_order, name) WHERE (is_active = true);
CREATE INDEX idx_unified_attributes_code ON public.unified_attributes USING btree (code);
CREATE INDEX idx_unified_attributes_name_trgm ON public.unified_attributes USING gin (name public.gin_trgm_ops);
CREATE INDEX idx_unified_attributes_purpose ON public.unified_attributes USING btree (purpose);
CREATE INDEX idx_unified_attributes_search_vector ON public.unified_attributes USING gin (search_vector);
CREATE INDEX idx_unified_cat_attrs_composite ON public.unified_category_attributes USING btree (category_id, attribute_id, is_enabled, sort_order) WHERE (is_enabled = true);
CREATE INDEX idx_unified_category_attributes_category ON public.unified_category_attributes USING btree (category_id);
CREATE INDEX idx_unified_category_attributes_enabled ON public.unified_category_attributes USING btree (is_enabled);
CREATE INDEX idx_unified_category_attrs_category_enabled_covering ON public.unified_category_attributes USING btree (category_id, is_enabled, attribute_id, sort_order, is_required) WHERE (is_enabled = true);
CREATE INDEX idx_unified_geo_composite ON public.unified_geo USING btree (source_type, source_id);
CREATE INDEX idx_unified_geo_geohash ON public.unified_geo USING btree (geohash);
CREATE INDEX idx_unified_geo_location_bounds ON public.unified_geo USING gist (location) WHERE (location IS NOT NULL);
CREATE INDEX idx_unified_geo_marketplace_active ON public.unified_geo USING btree (source_id) WHERE (source_type = 'marketplace_listing'::public.geo_source_type);
CREATE INDEX idx_unified_geo_source_id ON public.unified_geo USING btree (source_id);
CREATE INDEX idx_unified_geo_source_type ON public.unified_geo USING btree (source_type);
CREATE INDEX idx_unified_geo_storefront_active ON public.unified_geo USING btree (source_id) WHERE (source_type = 'storefront_product'::public.geo_source_type);
CREATE UNIQUE INDEX idx_unique_direct_chat ON public.marketplace_chats USING btree (LEAST(buyer_id, seller_id), GREATEST(buyer_id, seller_id)) WHERE ((listing_id IS NULL) AND (storefront_product_id IS NULL));
CREATE UNIQUE INDEX idx_unique_keyword_category ON public.category_keywords USING btree (category_id, keyword, language);
CREATE INDEX idx_user_behavior_events_created_at ON public.user_behavior_events USING btree (created_at);
CREATE INDEX idx_user_behavior_events_event_type ON public.user_behavior_events USING btree (event_type);
CREATE INDEX idx_user_behavior_events_item ON public.user_behavior_events USING btree (item_id, item_type) WHERE (item_id IS NOT NULL);
CREATE INDEX idx_user_behavior_events_search_query_type ON public.user_behavior_events USING btree (search_query, event_type) WHERE (search_query IS NOT NULL);
CREATE INDEX idx_user_behavior_events_session_id ON public.user_behavior_events USING btree (session_id);
CREATE INDEX idx_user_behavior_events_user_id ON public.user_behavior_events USING btree (user_id) WHERE (user_id IS NOT NULL);
CREATE INDEX idx_user_contacts_contact_user_id ON public.user_contacts USING btree (contact_user_id);
CREATE INDEX idx_user_contacts_created_at ON public.user_contacts USING btree (created_at);
CREATE INDEX idx_user_contacts_status ON public.user_contacts USING btree (status);
CREATE INDEX idx_user_contacts_user_id ON public.user_contacts USING btree (user_id);
CREATE INDEX idx_user_privacy_settings_user_id ON public.user_privacy_settings USING btree (user_id);
CREATE INDEX idx_user_roles_role_id ON public.user_roles USING btree (role_id);
CREATE INDEX idx_user_roles_user_id ON public.user_roles USING btree (user_id);
CREATE INDEX idx_user_storefronts_status ON public.user_storefronts USING btree (status);
CREATE INDEX idx_user_storefronts_user ON public.user_storefronts USING btree (user_id);
