CREATE INDEX idx_listings_geo_blurred_location ON public.listings_geo USING gist (blurred_location);
CREATE INDEX idx_listings_geo_location ON public.listings_geo USING gist (location);
CREATE INDEX idx_map_items_cache_location ON public.map_items_cache USING btree (latitude, longitude);
CREATE INDEX idx_marketplace_listings_location ON public.marketplace_listings USING btree (latitude, longitude) WHERE ((latitude IS NOT NULL) AND (longitude IS NOT NULL));
CREATE INDEX idx_marketplace_orders_protection ON public.marketplace_orders USING btree (protection_expires_at) WHERE ((status)::text = ANY (ARRAY[('delivered'::character varying)::text, ('shipped'::character varying)::text]));
CREATE INDEX idx_poi_cache_location ON public.gis_poi_cache USING gist (location);
CREATE INDEX idx_search_weights_history_reason ON public.search_weights_history USING btree (change_reason);
CREATE INDEX idx_search_weights_version ON public.search_weights USING btree (version);
CREATE INDEX idx_storefront_products_individual_location ON public.storefront_products USING btree (has_individual_location);
CREATE INDEX idx_unified_geo_location ON public.unified_geo USING gist (location);
CREATE INDEX admin_users_email_idx ON public.admin_users USING btree (email);
CREATE INDEX idx_address_log_confidence_after ON public.address_change_log USING btree (confidence_after);
CREATE INDEX idx_address_log_created_at ON public.address_change_log USING btree (created_at);
CREATE INDEX idx_address_log_listing_id ON public.address_change_log USING btree (listing_id);
CREATE INDEX idx_address_log_user_id ON public.address_change_log USING btree (user_id);
CREATE INDEX idx_attr_name_num_val ON public.listing_attribute_values USING btree (attribute_id, numeric_value) WHERE (numeric_value IS NOT NULL);
CREATE INDEX idx_attr_name_text_val ON public.listing_attribute_values USING btree (attribute_id, text_value) WHERE (text_value IS NOT NULL);
CREATE INDEX idx_attr_unit ON public.listing_attribute_values USING btree (unit) WHERE (unit IS NOT NULL);
CREATE INDEX idx_attribute_group_items_attribute ON public.attribute_group_items USING btree (attribute_id);
CREATE INDEX idx_attribute_group_items_group ON public.attribute_group_items USING btree (group_id);
CREATE INDEX idx_attribute_groups_active ON public.attribute_groups USING btree (is_active);
CREATE INDEX idx_attribute_groups_name ON public.attribute_groups USING btree (name);
CREATE INDEX idx_attribute_option_translations ON public.attribute_option_translations USING btree (attribute_name, option_value);
CREATE INDEX idx_audit_log_entity ON public.translation_audit_log USING btree (entity_type, entity_id);
CREATE INDEX idx_audit_log_user_date ON public.translation_audit_log USING btree (user_id, created_at DESC);
CREATE INDEX idx_car_generations_active ON public.car_generations USING btree (is_active) WHERE (is_active = true);
CREATE INDEX idx_car_generations_model_id ON public.car_generations USING btree (model_id);
CREATE INDEX idx_car_generations_slug ON public.car_generations USING btree (slug);
CREATE INDEX idx_car_generations_years ON public.car_generations USING btree (year_start, year_end);
CREATE INDEX idx_car_makes_external_id ON public.car_makes USING btree (external_id);
CREATE INDEX idx_car_makes_is_domestic ON public.car_makes USING btree (is_domestic);
CREATE INDEX idx_car_makes_popularity ON public.car_makes USING btree (popularity_rs DESC);
CREATE INDEX idx_car_makes_slug ON public.car_makes USING btree (slug);
CREATE INDEX idx_car_models_battery_capacity ON public.car_models USING btree (battery_capacity_kwh) WHERE (battery_capacity_kwh IS NOT NULL);
CREATE INDEX idx_car_models_body_type ON public.car_models USING btree (body_type);
CREATE INDEX idx_car_models_drive_type ON public.car_models USING btree (drive_type);
CREATE INDEX idx_car_models_engine_type ON public.car_models USING btree (engine_type);
CREATE INDEX idx_car_models_external_id ON public.car_models USING btree (external_id);
CREATE INDEX idx_car_models_fuel_type ON public.car_models USING btree (fuel_type);
CREATE INDEX idx_car_models_is_electric ON public.car_models USING btree (is_electric) WHERE (is_electric = true);
CREATE INDEX idx_car_models_make_slug ON public.car_models USING btree (make_id, slug);
CREATE INDEX idx_car_models_search ON public.car_models USING gin (to_tsvector('simple'::regconfig, (name)::text));
CREATE INDEX idx_car_models_serbia_popularity ON public.car_models USING btree (serbia_popularity_score DESC);
CREATE INDEX idx_car_models_transmission_type ON public.car_models USING btree (transmission_type);
CREATE INDEX idx_category_attr_mapping ON public.category_attribute_mapping USING btree (category_id, is_enabled) WHERE (is_enabled = true);
CREATE INDEX idx_category_attribute_groups_category ON public.category_attribute_groups USING btree (category_id);
CREATE INDEX idx_category_attribute_groups_component ON public.category_attribute_groups USING btree (component_id);
CREATE INDEX idx_category_attribute_groups_group ON public.category_attribute_groups USING btree (group_id);
CREATE INDEX idx_category_attribute_map_attr_id ON public.category_attribute_mapping USING btree (attribute_id);
CREATE INDEX idx_category_attribute_map_cat_id ON public.category_attribute_mapping USING btree (category_id);
CREATE INDEX idx_category_attribute_mapping_custom_component ON public.category_attribute_mapping USING btree (custom_component);
CREATE INDEX idx_category_attributes_data_source ON public.category_attributes USING btree (data_source);
CREATE INDEX idx_category_attributes_name ON public.category_attributes USING btree (name);
CREATE INDEX idx_category_attributes_variant_compatible ON public.category_attributes USING btree (is_variant_compatible) WHERE (is_variant_compatible = true);
CREATE INDEX idx_category_variant_attributes_category_id ON public.category_variant_attributes USING btree (category_id);
CREATE INDEX idx_category_variant_attributes_variant_name ON public.category_variant_attributes USING btree (variant_attribute_name);
CREATE INDEX idx_category_weight ON public.category_keywords USING btree (category_id, weight DESC);
CREATE INDEX idx_chat_attachments_created_at ON public.chat_attachments USING btree (created_at);
CREATE INDEX idx_chat_attachments_file_type ON public.chat_attachments USING btree (file_type);
CREATE INDEX idx_chat_attachments_message ON public.chat_attachments USING btree (message_id);
CREATE INDEX idx_chat_attachments_message_id ON public.chat_attachments USING btree (message_id);
CREATE INDEX idx_cities_boundary ON public.cities USING gist (boundary);
CREATE INDEX idx_cities_center ON public.cities USING gist (center_point);
CREATE INDEX idx_cities_country ON public.cities USING btree (country_code);
CREATE INDEX idx_cities_has_districts ON public.cities USING btree (has_districts);
CREATE INDEX idx_cities_name ON public.cities USING btree (name);
CREATE INDEX idx_cities_priority ON public.cities USING btree (priority);
CREATE INDEX idx_cities_slug ON public.cities USING btree (slug);
CREATE INDEX idx_component_templates_cat ON public.component_templates USING btree (category_id);
CREATE INDEX idx_component_templates_comp ON public.component_templates USING btree (component_id);
CREATE INDEX idx_custom_ui_components_active ON public.custom_ui_components USING btree (is_active);
CREATE INDEX idx_custom_ui_components_name ON public.custom_ui_components USING btree (name);
CREATE INDEX idx_custom_ui_components_type ON public.custom_ui_components USING btree (component_type);
CREATE INDEX idx_custom_ui_templates_name ON public.custom_ui_templates USING btree (name);
CREATE INDEX idx_delivery_is_active ON public.storefront_delivery_options USING btree (is_active);
CREATE INDEX idx_delivery_storefront_id ON public.storefront_delivery_options USING btree (storefront_id);
CREATE INDEX idx_density_grid_cell ON public.gis_listing_density_grid USING gist (cell);
CREATE INDEX idx_density_grid_density ON public.gis_listing_density_grid USING btree (density);
CREATE INDEX idx_disputes_review_id ON public.review_disputes USING btree (review_id);
CREATE INDEX idx_disputes_status ON public.review_disputes USING btree (status);
CREATE INDEX idx_districts_boundary ON public.districts USING gist (boundary);
CREATE INDEX idx_districts_center ON public.districts USING gist (center_point);
CREATE INDEX idx_districts_city_id ON public.districts USING btree (city_id);
CREATE INDEX idx_districts_country ON public.districts USING btree (country_code);
CREATE INDEX idx_districts_name ON public.districts USING btree (name);
CREATE INDEX idx_escrow_payments_buyer_id ON public.escrow_payments USING btree (buyer_id);
CREATE INDEX idx_escrow_payments_payment_transaction_id ON public.escrow_payments USING btree (payment_transaction_id);
CREATE INDEX idx_escrow_payments_seller_id ON public.escrow_payments USING btree (seller_id);
CREATE INDEX idx_escrow_payments_status ON public.escrow_payments USING btree (status);
CREATE INDEX idx_filter_analytics_created ON public.gis_filter_analytics USING btree (created_at);
CREATE INDEX idx_filter_analytics_type ON public.gis_filter_analytics USING btree (filter_type);
CREATE INDEX idx_filter_analytics_user ON public.gis_filter_analytics USING btree (user_id);
CREATE INDEX idx_geocoding_cache_address_components ON public.geocoding_cache USING gin (address_components);
CREATE INDEX idx_geocoding_cache_cache_hits ON public.geocoding_cache USING btree (cache_hits);
CREATE INDEX idx_geocoding_cache_confidence ON public.geocoding_cache USING btree (confidence);
CREATE INDEX idx_geocoding_cache_country_lang ON public.geocoding_cache USING btree (country_code, language);
CREATE INDEX idx_geocoding_cache_expires_at ON public.geocoding_cache USING btree (expires_at);
CREATE INDEX idx_geocoding_cache_input_address ON public.geocoding_cache USING btree (input_address);
CREATE INDEX idx_geocoding_cache_normalized ON public.geocoding_cache USING btree (normalized_address);
CREATE INDEX idx_geocoding_cache_provider ON public.geocoding_cache USING btree (provider);
