CREATE TRIGGER update_category_keywords_updated_at BEFORE UPDATE ON public.category_keywords FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER update_category_variant_attributes_updated_at BEFORE UPDATE ON public.category_variant_attributes FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER update_couriers_updated_at BEFORE UPDATE ON public.couriers FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER update_deliveries_updated_at BEFORE UPDATE ON public.deliveries FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER update_delivery_category_defaults_updated_at BEFORE UPDATE ON public.delivery_category_defaults FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER update_delivery_notifications_updated_at BEFORE UPDATE ON public.delivery_notifications FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER update_delivery_pricing_rules_updated_at BEFORE UPDATE ON public.delivery_pricing_rules FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER update_delivery_providers_updated_at BEFORE UPDATE ON public.delivery_providers FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER update_delivery_shipments_updated_at BEFORE UPDATE ON public.delivery_shipments FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER update_listings_on_attribute_translation_change AFTER INSERT OR UPDATE ON public.attribute_option_translations FOR EACH ROW EXECUTE FUNCTION public.trigger_update_listings_on_attribute_translation_change();
CREATE TRIGGER update_notification_settings_timestamp BEFORE UPDATE ON public.notification_settings FOR EACH ROW EXECUTE FUNCTION public.update_notification_settings_updated_at();
CREATE TRIGGER update_notification_templates_updated_at BEFORE UPDATE ON public.notification_templates FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER update_ratings_after_review_change AFTER INSERT OR DELETE OR UPDATE ON public.reviews FOR EACH ROW EXECUTE FUNCTION public.refresh_rating_views();
CREATE TRIGGER update_review_responses_updated_at BEFORE UPDATE ON public.review_responses FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER update_reviews_updated_at BEFORE UPDATE ON public.reviews FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER update_saved_searches_updated_at BEFORE UPDATE ON public.saved_searches FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER update_search_queries_updated_at_trigger BEFORE UPDATE ON public.search_queries FOR EACH ROW EXECUTE FUNCTION public.update_search_queries_updated_at();
CREATE TRIGGER update_translation_providers_timestamp BEFORE UPDATE ON public.translation_providers FOR EACH ROW EXECUTE FUNCTION public.update_translation_providers_updated_at();
CREATE TRIGGER update_translations_timestamp BEFORE UPDATE ON public.translations FOR EACH ROW EXECUTE FUNCTION public.update_translations_updated_at();
CREATE TRIGGER update_unified_attribute_values_updated_at BEFORE UPDATE ON public.unified_attribute_values FOR EACH ROW EXECUTE FUNCTION public.update_unified_attributes_updated_at();
CREATE TRIGGER update_unified_attributes_updated_at BEFORE UPDATE ON public.unified_attributes FOR EACH ROW EXECUTE FUNCTION public.update_unified_attributes_updated_at();
CREATE TRIGGER update_unified_category_attributes_updated_at BEFORE UPDATE ON public.unified_category_attributes FOR EACH ROW EXECUTE FUNCTION public.update_unified_attributes_updated_at();
CREATE TRIGGER update_user_contacts_updated_at BEFORE UPDATE ON public.user_contacts FOR EACH ROW EXECUTE FUNCTION public.update_user_contacts_updated_at();
CREATE TRIGGER update_user_notification_preferences_updated_at BEFORE UPDATE ON public.user_notification_preferences FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER update_user_privacy_settings_updated_at BEFORE UPDATE ON public.user_privacy_settings FOR EACH ROW EXECUTE FUNCTION public.update_user_privacy_settings_updated_at();
CREATE TRIGGER update_viber_users_updated_at BEFORE UPDATE ON public.viber_users FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER update_vin_decode_cache_timestamp BEFORE UPDATE ON public.vin_decode_cache FOR EACH ROW EXECUTE FUNCTION public.update_vin_decode_cache_updated_at();
ALTER SEQUENCE public.ai_category_decisions_id_seq OWNED BY public.ai_category_decisions.id;
ALTER SEQUENCE public.attribute_group_items_id_seq OWNED BY public.attribute_group_items.id;
ALTER SEQUENCE public.attribute_groups_id_seq OWNED BY public.attribute_groups.id;
ALTER SEQUENCE public.attribute_option_translations_id_seq OWNED BY public.attribute_option_translations.id;
ALTER SEQUENCE public.b2c_delivery_options_id_seq OWNED BY public.b2c_delivery_options.id;
ALTER SEQUENCE public.b2c_inventory_movements_id_seq OWNED BY public.b2c_inventory_movements.id;
ALTER SEQUENCE public.b2c_order_items_id_seq OWNED BY public.b2c_order_items.id;
ALTER SEQUENCE public.b2c_orders_id_seq OWNED BY public.b2c_orders.id;
ALTER SEQUENCE public.b2c_payment_methods_id_seq OWNED BY public.b2c_payment_methods.id;
ALTER SEQUENCE public.b2c_product_attributes_id_seq OWNED BY public.b2c_product_attributes.id;
ALTER SEQUENCE public.b2c_product_images_id_seq OWNED BY public.b2c_product_images.id;
ALTER SEQUENCE public.b2c_product_variant_images_id_seq OWNED BY public.b2c_product_variant_images.id;
ALTER SEQUENCE public.b2c_product_variants_id_seq OWNED BY public.b2c_product_variants.id;
ALTER SEQUENCE public.b2c_store_hours_id_seq OWNED BY public.b2c_store_hours.id;
ALTER SEQUENCE public.b2c_store_staff_id_seq OWNED BY public.b2c_store_staff.id;
ALTER SEQUENCE public.b2c_stores_id_seq OWNED BY public.b2c_stores.id;
ALTER SEQUENCE public.balance_transactions_id_seq OWNED BY public.balance_transactions.id;
ALTER SEQUENCE public.bex_configuration_id_seq OWNED BY public.bex_configuration.id;
ALTER SEQUENCE public.bex_shipments_id_seq OWNED BY public.bex_shipments.id;
ALTER SEQUENCE public.bex_tracking_events_id_seq OWNED BY public.bex_tracking_events.id;
ALTER SEQUENCE public.c2c_categories_id_seq OWNED BY public.c2c_categories.id;
ALTER SEQUENCE public.c2c_chats_id_seq OWNED BY public.c2c_chats.id;
ALTER SEQUENCE public.c2c_images_id_seq OWNED BY public.c2c_images.id;
ALTER SEQUENCE public.c2c_listing_variants_id_seq OWNED BY public.c2c_listing_variants.id;
ALTER SEQUENCE public.c2c_messages_id_seq OWNED BY public.c2c_messages.id;
ALTER SEQUENCE public.c2c_orders_id_seq OWNED BY public.c2c_orders.id;
ALTER SEQUENCE public.car_generations_id_seq OWNED BY public.car_generations.id;
ALTER SEQUENCE public.car_makes_id_seq OWNED BY public.car_makes.id;
ALTER SEQUENCE public.car_market_analysis_id_seq OWNED BY public.car_market_analysis.id;
ALTER SEQUENCE public.car_models_id_seq OWNED BY public.car_models.id;
ALTER SEQUENCE public.category_ai_mappings_id_seq OWNED BY public.category_ai_mappings.id;
ALTER SEQUENCE public.category_attribute_groups_id_seq OWNED BY public.category_attribute_groups.id;
ALTER SEQUENCE public.category_detection_cache_id_seq OWNED BY public.category_detection_cache.id;
ALTER SEQUENCE public.category_detection_feedback_id_seq OWNED BY public.category_detection_feedback.id;
ALTER SEQUENCE public.category_keyword_weights_id_seq OWNED BY public.category_keyword_weights.id;
ALTER SEQUENCE public.category_keywords_id_seq OWNED BY public.category_keywords.id;
ALTER SEQUENCE public.category_proposals_id_seq OWNED BY public.category_proposals.id;
ALTER SEQUENCE public.category_variant_attributes_id_seq OWNED BY public.category_variant_attributes.id;
ALTER SEQUENCE public.chat_attachments_id_seq OWNED BY public.chat_attachments.id;
ALTER SEQUENCE public.component_templates_id_seq OWNED BY public.component_templates.id;
ALTER SEQUENCE public.courier_location_history_id_seq OWNED BY public.courier_location_history.id;
ALTER SEQUENCE public.courier_zones_id_seq OWNED BY public.courier_zones.id;
ALTER SEQUENCE public.couriers_id_seq OWNED BY public.couriers.id;
ALTER SEQUENCE public.deliveries_id_seq OWNED BY public.deliveries.id;
ALTER SEQUENCE public.delivery_category_defaults_id_seq OWNED BY public.delivery_category_defaults.id;
ALTER SEQUENCE public.delivery_notifications_id_seq OWNED BY public.delivery_notifications.id;
ALTER SEQUENCE public.delivery_pricing_rules_id_seq OWNED BY public.delivery_pricing_rules.id;
ALTER SEQUENCE public.delivery_providers_id_seq OWNED BY public.delivery_providers.id;
ALTER SEQUENCE public.delivery_shipments_id_seq OWNED BY public.delivery_shipments.id;
ALTER SEQUENCE public.delivery_tracking_events_id_seq OWNED BY public.delivery_tracking_events.id;
ALTER SEQUENCE public.delivery_zones_id_seq OWNED BY public.delivery_zones.id;
ALTER SEQUENCE public.escrow_payments_id_seq OWNED BY public.escrow_payments.id;
ALTER SEQUENCE public.geocoding_cache_id_seq OWNED BY public.geocoding_cache.id;
ALTER SEQUENCE public.import_history_id_seq OWNED BY public.import_history.id;
ALTER SEQUENCE public.imported_categories_id_seq OWNED BY public.imported_categories.id;
ALTER SEQUENCE public.inventory_reservations_id_seq OWNED BY public.inventory_reservations.id;
ALTER SEQUENCE public.item_performance_metrics_id_seq OWNED BY public.item_performance_metrics.id;
ALTER SEQUENCE public.listing_attribute_values_id_seq OWNED BY public.listing_attribute_values.id;
ALTER SEQUENCE public.listing_views_id_seq OWNED BY public.listing_views.id;
ALTER SEQUENCE public.map_items_cache_id_seq OWNED BY public.map_items_cache.id;
ALTER SEQUENCE public.merchant_payouts_id_seq OWNED BY public.merchant_payouts.id;
ALTER SEQUENCE public.notification_templates_id_seq OWNED BY public.notification_templates.id;
ALTER SEQUENCE public.notifications_id_seq OWNED BY public.notifications.id;
ALTER SEQUENCE public.payment_gateways_id_seq OWNED BY public.payment_gateways.id;
ALTER SEQUENCE public.payment_methods_id_seq OWNED BY public.payment_methods.id;
ALTER SEQUENCE public.payment_transactions_id_seq OWNED BY public.payment_transactions.id;
ALTER SEQUENCE public.permissions_id_seq OWNED BY public.permissions.id;
ALTER SEQUENCE public.post_express_locations_id_seq OWNED BY public.post_express_locations.id;
ALTER SEQUENCE public.post_express_offices_id_seq OWNED BY public.post_express_offices.id;
ALTER SEQUENCE public.post_express_rates_id_seq OWNED BY public.post_express_rates.id;
ALTER SEQUENCE public.post_express_settings_id_seq OWNED BY public.post_express_settings.id;
ALTER SEQUENCE public.post_express_shipments_id_seq OWNED BY public.post_express_shipments.id;
ALTER SEQUENCE public.post_express_tracking_events_id_seq OWNED BY public.post_express_tracking_events.id;
