CREATE INDEX idx_unified_attributes_active_sort ON public.unified_attributes USING btree (is_active, sort_order, name) WHERE (is_active = true);
CREATE INDEX idx_unified_attributes_code ON public.unified_attributes USING btree (code);
CREATE INDEX idx_unified_attributes_name_trgm ON public.unified_attributes USING gin (name public.gin_trgm_ops);
CREATE INDEX idx_unified_attributes_purpose ON public.unified_attributes USING btree (purpose);
CREATE INDEX idx_unified_attributes_search_vector ON public.unified_attributes USING gin (search_vector);
CREATE INDEX idx_unified_cat_attrs_composite ON public.unified_category_attributes USING btree (category_id, attribute_id, is_enabled, sort_order) WHERE (is_enabled = true);
CREATE INDEX idx_unified_category_attributes_category ON public.unified_category_attributes USING btree (category_id);
CREATE INDEX idx_unified_category_attributes_enabled ON public.unified_category_attributes USING btree (is_enabled);
CREATE INDEX idx_unified_category_attrs_category_enabled_covering ON public.unified_category_attributes USING btree (category_id, is_enabled, attribute_id, sort_order, is_required) WHERE (is_enabled = true);
CREATE INDEX idx_unified_geo_composite ON public.unified_geo USING btree (source_type, source_id);
CREATE INDEX idx_unified_geo_geohash ON public.unified_geo USING btree (geohash);
CREATE INDEX idx_unified_geo_location_bounds ON public.unified_geo USING gist (location) WHERE (location IS NOT NULL);
CREATE INDEX idx_unified_geo_marketplace_active ON public.unified_geo USING btree (source_id) WHERE (source_type = 'marketplace_listing'::public.geo_source_type);
CREATE INDEX idx_unified_geo_source_id ON public.unified_geo USING btree (source_id);
CREATE INDEX idx_unified_geo_source_type ON public.unified_geo USING btree (source_type);
CREATE INDEX idx_unified_geo_storefront_active ON public.unified_geo USING btree (source_id) WHERE (source_type = 'storefront_product'::public.geo_source_type);
CREATE UNIQUE INDEX idx_unique_direct_chat ON public.marketplace_chats USING btree (LEAST(buyer_id, seller_id), GREATEST(buyer_id, seller_id)) WHERE ((listing_id IS NULL) AND (storefront_product_id IS NULL));
CREATE UNIQUE INDEX idx_unique_keyword_category ON public.category_keywords USING btree (category_id, keyword, language);
CREATE INDEX idx_user_behavior_events_created_at ON public.user_behavior_events USING btree (created_at);
CREATE INDEX idx_user_behavior_events_event_type ON public.user_behavior_events USING btree (event_type);
CREATE INDEX idx_user_behavior_events_item ON public.user_behavior_events USING btree (item_id, item_type) WHERE (item_id IS NOT NULL);
CREATE INDEX idx_user_behavior_events_search_query_type ON public.user_behavior_events USING btree (search_query, event_type) WHERE (search_query IS NOT NULL);
CREATE INDEX idx_user_behavior_events_session_id ON public.user_behavior_events USING btree (session_id);
CREATE INDEX idx_user_behavior_events_user_id ON public.user_behavior_events USING btree (user_id) WHERE (user_id IS NOT NULL);
CREATE INDEX idx_user_contacts_contact_user_id ON public.user_contacts USING btree (contact_user_id);
CREATE INDEX idx_user_contacts_created_at ON public.user_contacts USING btree (created_at);
CREATE INDEX idx_user_contacts_status ON public.user_contacts USING btree (status);
CREATE INDEX idx_user_contacts_user_id ON public.user_contacts USING btree (user_id);
CREATE INDEX idx_user_privacy_settings_user_id ON public.user_privacy_settings USING btree (user_id);
CREATE INDEX idx_user_roles_role_id ON public.user_roles USING btree (role_id);
CREATE INDEX idx_user_roles_user_id ON public.user_roles USING btree (user_id);
CREATE INDEX idx_user_storefronts_status ON public.user_storefronts USING btree (status);
CREATE INDEX idx_user_storefronts_user ON public.user_storefronts USING btree (user_id);
CREATE INDEX idx_user_subscriptions_user_status ON public.user_subscriptions USING btree (user_id, status);
CREATE INDEX idx_users_active ON public.users USING btree (last_seen DESC) WHERE ((account_status)::text = 'active'::text);
CREATE INDEX idx_users_email ON public.users USING btree (email);
CREATE INDEX idx_users_email_lower ON public.users USING btree (lower((email)::text));
CREATE INDEX idx_users_phone ON public.users USING btree (phone);
CREATE INDEX idx_users_preferred_language ON public.users USING btree (preferred_language);
CREATE INDEX idx_users_provider ON public.users USING btree (provider);
CREATE INDEX idx_users_role_id ON public.users USING btree (role_id);
CREATE INDEX idx_users_status ON public.users USING btree (account_status);
CREATE INDEX idx_variant_mappings_attribute ON public.variant_attribute_mappings USING btree (variant_attribute_id);
CREATE INDEX idx_variant_mappings_category ON public.variant_attribute_mappings USING btree (category_id);
CREATE UNIQUE INDEX storefront_rating_distribution_storefront_id_idx ON public.storefront_rating_distribution USING btree (storefront_id);
CREATE UNIQUE INDEX storefront_rating_summary_storefront_id_idx ON public.storefront_rating_summary USING btree (storefront_id);
CREATE UNIQUE INDEX storefront_ratings_storefront_id_idx ON public.storefront_ratings USING btree (storefront_id);
CREATE UNIQUE INDEX unique_storefront_product_barcode ON public.storefront_products USING btree (storefront_id, barcode) WHERE (barcode IS NOT NULL);
CREATE UNIQUE INDEX unique_storefront_product_sku ON public.storefront_products USING btree (storefront_id, sku) WHERE (sku IS NOT NULL);
CREATE UNIQUE INDEX user_rating_distribution_user_id_idx ON public.user_rating_distribution USING btree (user_id);
CREATE UNIQUE INDEX user_rating_summary_user_id_idx ON public.user_rating_summary USING btree (user_id);
CREATE UNIQUE INDEX user_ratings_user_id_idx ON public.user_ratings USING btree (user_id);
SELECT pg_catalog.setval('public.address_change_log_id_seq', 1, false);
SELECT pg_catalog.setval('public.admin_users_id_seq', 26, true);
SELECT pg_catalog.setval('public.attribute_group_items_id_seq', 1, false);
SELECT pg_catalog.setval('public.attribute_groups_id_seq', 10, true);
SELECT pg_catalog.setval('public.attribute_option_translations_id_seq', 3699, true);
SELECT pg_catalog.setval('public.balance_transactions_id_seq', 26, false);
SELECT pg_catalog.setval('public.car_generations_id_seq', 1, false);
SELECT pg_catalog.setval('public.car_makes_id_seq', 115, true);
SELECT pg_catalog.setval('public.car_market_analysis_id_seq', 250, true);
SELECT pg_catalog.setval('public.car_models_id_seq', 3862, true);
SELECT pg_catalog.setval('public.category_attribute_groups_id_seq', 1, false);
SELECT pg_catalog.setval('public.category_keywords_id_seq', 878, true);
SELECT pg_catalog.setval('public.category_variant_attributes_id_seq', 12, true);
SELECT pg_catalog.setval('public.chat_attachments_id_seq', 144, true);
SELECT pg_catalog.setval('public.component_templates_id_seq', 1, false);
SELECT pg_catalog.setval('public.custom_ui_component_usage_id_seq', 1, false);
SELECT pg_catalog.setval('public.custom_ui_components_id_seq', 2, false);
SELECT pg_catalog.setval('public.custom_ui_templates_id_seq', 1, false);
SELECT pg_catalog.setval('public.escrow_payments_id_seq', 1, false);
SELECT pg_catalog.setval('public.geocoding_cache_id_seq', 13, true);
SELECT pg_catalog.setval('public.gis_filter_analytics_id_seq', 1, false);
SELECT pg_catalog.setval('public.gis_isochrone_cache_id_seq', 1, false);
SELECT pg_catalog.setval('public.gis_poi_cache_id_seq', 1, false);
SELECT pg_catalog.setval('public.global_product_id_seq', 301, true);
SELECT pg_catalog.setval('public.import_history_id_seq', 1, false);
SELECT pg_catalog.setval('public.import_sources_id_seq', 1, false);
SELECT pg_catalog.setval('public.imported_categories_id_seq', 1, false);
SELECT pg_catalog.setval('public.inventory_reservations_id_seq', 20, true);
SELECT pg_catalog.setval('public.item_performance_metrics_id_seq', 1, false);
SELECT pg_catalog.setval('public.listing_attribute_values_id_seq', 1, false);
SELECT pg_catalog.setval('public.listing_views_id_seq', 2, true);
SELECT pg_catalog.setval('public.listings_geo_id_seq', 1, false);
SELECT pg_catalog.setval('public.map_items_cache_id_seq', 1, false);
SELECT pg_catalog.setval('public.marketplace_categories_id_seq', 10001, true);
SELECT pg_catalog.setval('public.marketplace_chats_id_seq', 16, true);
SELECT pg_catalog.setval('public.marketplace_images_id_seq', 668, true);
SELECT pg_catalog.setval('public.marketplace_listing_variants_id_seq', 1, false);
SELECT pg_catalog.setval('public.marketplace_messages_id_seq', 53, true);
SELECT pg_catalog.setval('public.marketplace_orders_id_seq', 1, false);
SELECT pg_catalog.setval('public.merchant_payouts_id_seq', 1, false);
SELECT pg_catalog.setval('public.notifications_id_seq', 64, true);
SELECT pg_catalog.setval('public.payment_gateways_id_seq', 2, false);
SELECT pg_catalog.setval('public.payment_methods_id_seq', 27, false);
SELECT pg_catalog.setval('public.payment_transactions_id_seq', 1, false);
SELECT pg_catalog.setval('public.permissions_id_seq', 86, true);
SELECT pg_catalog.setval('public.post_express_locations_id_seq', 5, true);
SELECT pg_catalog.setval('public.post_express_offices_id_seq', 1, false);
SELECT pg_catalog.setval('public.post_express_rates_id_seq', 5, true);
