-- Drop table: storefront_product_variants
DROP SEQUENCE IF EXISTS public.storefront_product_variants_id_seq;
DROP TABLE IF EXISTS public.storefront_product_variants;
DROP INDEX IF EXISTS public.idx_storefront_product_variants_attributes_gin;
DROP INDEX IF EXISTS public.idx_storefront_product_variants_barcode;
DROP INDEX IF EXISTS public.idx_storefront_product_variants_default_unique;
DROP INDEX IF EXISTS public.idx_storefront_product_variants_is_active;
DROP INDEX IF EXISTS public.idx_storefront_product_variants_is_default;
DROP INDEX IF EXISTS public.idx_storefront_product_variants_product_id;
DROP INDEX IF EXISTS public.idx_storefront_product_variants_sku;
DROP INDEX IF EXISTS public.idx_storefront_product_variants_stock_status;
DROP TRIGGER IF EXISTS trigger_update_storefront_product_variants_updated_at ON public.storefront_product_variants;