CREATE INDEX idx_cities_country ON public.cities USING btree (country_code);
CREATE INDEX idx_cities_has_districts ON public.cities USING btree (has_districts);
CREATE INDEX idx_cities_name ON public.cities USING btree (name);
CREATE INDEX idx_cities_priority ON public.cities USING btree (priority);
CREATE INDEX idx_cities_slug ON public.cities USING btree (slug);
CREATE INDEX idx_component_templates_cat ON public.component_templates USING btree (category_id);
CREATE INDEX idx_component_templates_comp ON public.component_templates USING btree (component_id);
CREATE INDEX idx_couriers_online_available ON public.couriers USING btree (is_online, is_available) WHERE ((is_online = true) AND (is_available = true));
CREATE INDEX idx_couriers_user_id ON public.couriers USING btree (user_id);
CREATE INDEX idx_custom_ui_components_active ON public.custom_ui_components USING btree (is_active);
CREATE INDEX idx_custom_ui_components_name ON public.custom_ui_components USING btree (name);
CREATE INDEX idx_custom_ui_components_type ON public.custom_ui_components USING btree (component_type);
CREATE INDEX idx_custom_ui_templates_name ON public.custom_ui_templates USING btree (name);
CREATE INDEX idx_deliveries_courier ON public.deliveries USING btree (courier_id, status);
CREATE INDEX idx_deliveries_order ON public.deliveries USING btree (order_id);
CREATE INDEX idx_deliveries_status ON public.deliveries USING btree (status) WHERE ((status)::text = ANY ((ARRAY['assigned'::character varying, 'accepted'::character varying, 'picked_up'::character varying, 'in_transit'::character varying])::text[]));
CREATE INDEX idx_deliveries_tracking_token ON public.deliveries USING btree (tracking_token);
CREATE INDEX idx_delivery_category_defaults_category ON public.delivery_category_defaults USING btree (category_id);
CREATE INDEX idx_delivery_is_active ON public.storefront_delivery_options USING btree (is_active);
CREATE INDEX idx_delivery_notifications_channel ON public.delivery_notifications USING btree (channel);
CREATE INDEX idx_delivery_notifications_created ON public.delivery_notifications USING btree (created_at);
CREATE INDEX idx_delivery_notifications_shipment ON public.delivery_notifications USING btree (shipment_id);
CREATE INDEX idx_delivery_notifications_status ON public.delivery_notifications USING btree (status);
CREATE INDEX idx_delivery_notifications_user ON public.delivery_notifications USING btree (user_id);
CREATE INDEX idx_delivery_pricing_rules_active ON public.delivery_pricing_rules USING btree (is_active) WHERE (is_active = true);
CREATE INDEX idx_delivery_pricing_rules_provider ON public.delivery_pricing_rules USING btree (provider_id);
CREATE INDEX idx_delivery_shipments_order ON public.delivery_shipments USING btree (order_id);
CREATE INDEX idx_delivery_shipments_status ON public.delivery_shipments USING btree (status);
CREATE INDEX idx_delivery_shipments_tracking ON public.delivery_shipments USING btree (tracking_number);
CREATE INDEX idx_delivery_storefront_id ON public.storefront_delivery_options USING btree (storefront_id);
CREATE INDEX idx_delivery_tracking_events_shipment ON public.delivery_tracking_events USING btree (shipment_id);
CREATE INDEX idx_delivery_tracking_events_time ON public.delivery_tracking_events USING btree (event_time);
CREATE INDEX idx_delivery_zones_boundary ON public.delivery_zones USING gist (boundary);
CREATE INDEX idx_delivery_zones_center ON public.delivery_zones USING gist (center_point);
CREATE INDEX idx_density_grid_cell ON public.gis_listing_density_grid USING gist (cell);
CREATE INDEX idx_density_grid_density ON public.gis_listing_density_grid USING btree (density);
CREATE INDEX idx_detection_cache_expires ON public.category_detection_cache USING btree (expires_at);
CREATE INDEX idx_detection_cache_key ON public.category_detection_cache USING btree (cache_key);
CREATE INDEX idx_disputes_review_id ON public.review_disputes USING btree (review_id);
CREATE INDEX idx_disputes_status ON public.review_disputes USING btree (status);
CREATE INDEX idx_districts_boundary ON public.districts USING gist (boundary);
CREATE INDEX idx_districts_center ON public.districts USING gist (center_point);
CREATE INDEX idx_districts_city_id ON public.districts USING btree (city_id);
CREATE INDEX idx_districts_country ON public.districts USING btree (country_code);
CREATE INDEX idx_districts_name ON public.districts USING btree (name);
CREATE INDEX idx_escrow_payments_buyer_id ON public.escrow_payments USING btree (buyer_id);
CREATE INDEX idx_escrow_payments_payment_transaction_id ON public.escrow_payments USING btree (payment_transaction_id);
CREATE INDEX idx_escrow_payments_seller_id ON public.escrow_payments USING btree (seller_id);
CREATE INDEX idx_escrow_payments_status ON public.escrow_payments USING btree (status);
CREATE INDEX idx_feedback_ai_hints ON public.category_detection_feedback USING gin (ai_hints);
CREATE INDEX idx_feedback_created_at ON public.category_detection_feedback USING btree (created_at DESC);
CREATE INDEX idx_feedback_keywords ON public.category_detection_feedback USING gin (keywords);
CREATE INDEX idx_feedback_user_confirmed ON public.category_detection_feedback USING btree (user_confirmed) WHERE (user_confirmed = true);
CREATE INDEX idx_filter_analytics_created ON public.gis_filter_analytics USING btree (created_at);
CREATE INDEX idx_filter_analytics_type ON public.gis_filter_analytics USING btree (filter_type);
CREATE INDEX idx_filter_analytics_user ON public.gis_filter_analytics USING btree (user_id);
CREATE INDEX idx_geocoding_cache_address_components ON public.geocoding_cache USING gin (address_components);
CREATE INDEX idx_geocoding_cache_cache_hits ON public.geocoding_cache USING btree (cache_hits);
CREATE INDEX idx_geocoding_cache_confidence ON public.geocoding_cache USING btree (confidence);
CREATE INDEX idx_geocoding_cache_country_lang ON public.geocoding_cache USING btree (country_code, language);
CREATE INDEX idx_geocoding_cache_expires_at ON public.geocoding_cache USING btree (expires_at);
CREATE INDEX idx_geocoding_cache_input_address ON public.geocoding_cache USING btree (input_address);
CREATE INDEX idx_geocoding_cache_normalized ON public.geocoding_cache USING btree (normalized_address);
CREATE INDEX idx_geocoding_cache_provider ON public.geocoding_cache USING btree (provider);
CREATE INDEX idx_hours_storefront_id ON public.storefront_hours USING btree (storefront_id);
CREATE INDEX idx_import_history_source ON public.import_history USING btree (source_id);
CREATE INDEX idx_import_sources_storefront ON public.import_sources USING btree (storefront_id);
CREATE INDEX idx_imported_categories_source_id ON public.imported_categories USING btree (source_id);
CREATE INDEX idx_inventory_reservations_expires_at ON public.inventory_reservations USING btree (expires_at);
CREATE INDEX idx_inventory_reservations_order_id ON public.inventory_reservations USING btree (order_id);
CREATE INDEX idx_inventory_reservations_product_id ON public.inventory_reservations USING btree (product_id);
CREATE INDEX idx_inventory_reservations_status ON public.inventory_reservations USING btree (status);
CREATE INDEX idx_inventory_reservations_variant_id ON public.inventory_reservations USING btree (variant_id);
CREATE INDEX idx_isochrone_cache_center ON public.gis_isochrone_cache USING gist (center_point);
CREATE INDEX idx_isochrone_cache_expires ON public.gis_isochrone_cache USING btree (expires_at);
CREATE INDEX idx_isochrone_cache_lookup ON public.gis_isochrone_cache USING btree (transport_mode, max_minutes);
CREATE INDEX idx_item_performance_metrics_conversions ON public.item_performance_metrics USING btree (conversions DESC);
CREATE INDEX idx_item_performance_metrics_ctr ON public.item_performance_metrics USING btree (ctr DESC);
CREATE INDEX idx_item_performance_metrics_impressions ON public.item_performance_metrics USING btree (impressions DESC);
CREATE INDEX idx_item_performance_metrics_item ON public.item_performance_metrics USING btree (item_id, item_type);
CREATE INDEX idx_item_performance_metrics_period ON public.item_performance_metrics USING btree (period_start, period_end);
CREATE UNIQUE INDEX idx_item_performance_metrics_unique ON public.item_performance_metrics USING btree (item_id, period_start);
CREATE INDEX idx_keyword_lower ON public.category_keywords USING btree (lower((keyword)::text));
CREATE INDEX idx_keyword_type ON public.category_keywords USING btree (keyword_type);
CREATE INDEX idx_keyword_weights_category ON public.category_keyword_weights USING btree (category_id);
CREATE INDEX idx_keyword_weights_keyword ON public.category_keyword_weights USING btree (keyword);
CREATE INDEX idx_keyword_weights_weight ON public.category_keyword_weights USING btree (weight DESC);
CREATE INDEX idx_language ON public.category_keywords USING btree (language);
CREATE INDEX idx_listing_attribute_values_attribute ON public.listing_attribute_values USING btree (attribute_id);
CREATE INDEX idx_listing_attribute_values_listing ON public.listing_attribute_values USING btree (listing_id);
CREATE INDEX idx_listing_attribute_values_numeric ON public.listing_attribute_values USING btree (numeric_value) WHERE (numeric_value IS NOT NULL);
CREATE INDEX idx_listing_attribute_values_text ON public.listing_attribute_values USING btree (text_value) WHERE (text_value IS NOT NULL);
CREATE INDEX idx_listing_attribute_values_unit ON public.listing_attribute_values USING btree (unit) WHERE (unit IS NOT NULL);
CREATE INDEX idx_listing_views_listing_ip ON public.listing_views USING btree (listing_id, ip_hash);
CREATE INDEX idx_listing_views_listing_user ON public.listing_views USING btree (listing_id, user_id);
CREATE INDEX idx_listing_views_time ON public.listing_views USING btree (view_time);
CREATE INDEX idx_listings_geo_address_components ON public.listings_geo USING gin (address_components);
CREATE INDEX idx_listings_geo_confidence ON public.listings_geo USING btree (geocoding_confidence);
CREATE INDEX idx_listings_geo_district ON public.listings_geo USING btree (district_id);
CREATE INDEX idx_listings_geo_geohash ON public.listings_geo USING btree (geohash);
