CREATE INDEX idx_product_variant_attributes_name ON public.product_variant_attributes USING btree (name);
CREATE INDEX idx_providers_active ON public.translation_providers USING btree (is_active, priority) WHERE (is_active = true);
CREATE INDEX idx_quality_metrics_issues ON public.translation_quality_metrics USING btree (has_placeholders, has_html_tags);
CREATE INDEX idx_quality_metrics_score ON public.translation_quality_metrics USING btree (quality_score);
CREATE INDEX idx_rating_cache_type_rating ON public.rating_cache USING btree (entity_type, average_rating DESC);
CREATE INDEX idx_rating_cache_updated ON public.rating_cache USING btree (calculated_at);
CREATE INDEX idx_refresh_tokens_expires_at ON public.refresh_tokens USING btree (expires_at) WHERE (NOT is_revoked);
CREATE INDEX idx_refresh_tokens_token ON public.refresh_tokens USING btree (token) WHERE (NOT is_revoked);
CREATE INDEX idx_refresh_tokens_user_id ON public.refresh_tokens USING btree (user_id) WHERE (NOT is_revoked);
CREATE INDEX idx_review_responses_review ON public.review_responses USING btree (review_id);
CREATE INDEX idx_reviews_entity ON public.reviews USING btree (entity_type, entity_id);
CREATE INDEX idx_reviews_entity_origin ON public.reviews USING btree (entity_origin_type, entity_origin_id);
CREATE INDEX idx_reviews_has_dispute ON public.reviews USING btree (has_active_dispute) WHERE (has_active_dispute = true);
CREATE INDEX idx_reviews_rating ON public.reviews USING btree (rating);
CREATE INDEX idx_reviews_seller_confirmed ON public.reviews USING btree (seller_confirmed) WHERE (seller_confirmed = true);
CREATE INDEX idx_reviews_status ON public.reviews USING btree (status);
CREATE INDEX idx_reviews_user ON public.reviews USING btree (user_id);
CREATE INDEX idx_role_audit_log_created_at ON public.role_audit_log USING btree (created_at DESC);
CREATE INDEX idx_role_audit_log_target_user_id ON public.role_audit_log USING btree (target_user_id);
CREATE INDEX idx_role_audit_log_user_id ON public.role_audit_log USING btree (user_id);
CREATE INDEX idx_role_permissions_permission_id ON public.role_permissions USING btree (permission_id);
CREATE INDEX idx_role_permissions_role_id ON public.role_permissions USING btree (role_id);
CREATE INDEX idx_search_behavior_metrics_conversions ON public.search_behavior_metrics USING btree (conversions DESC);
CREATE INDEX idx_search_behavior_metrics_ctr ON public.search_behavior_metrics USING btree (ctr DESC);
CREATE INDEX idx_search_behavior_metrics_period ON public.search_behavior_metrics USING btree (period_start, period_end);
CREATE INDEX idx_search_behavior_metrics_query ON public.search_behavior_metrics USING btree (search_query);
CREATE INDEX idx_search_optimization_sessions_created_by ON public.search_optimization_sessions USING btree (created_by);
CREATE INDEX idx_search_optimization_sessions_start_time ON public.search_optimization_sessions USING btree (start_time);
CREATE INDEX idx_search_optimization_sessions_status ON public.search_optimization_sessions USING btree (status);
CREATE INDEX idx_search_queries_language ON public.search_queries USING btree (language);
CREATE INDEX idx_search_queries_normalized_query ON public.search_queries USING btree (normalized_query);
CREATE INDEX idx_search_queries_search_count ON public.search_queries USING btree (search_count DESC);
CREATE INDEX idx_search_synonyms_active ON public.search_synonyms USING btree (is_active) WHERE (is_active = true);
CREATE INDEX idx_search_synonyms_config_term ON public.search_synonyms_config USING btree (term);
CREATE INDEX idx_search_synonyms_language ON public.search_synonyms USING btree (language);
CREATE INDEX idx_search_synonyms_synonym ON public.search_synonyms USING btree (synonym);
CREATE INDEX idx_search_synonyms_term ON public.search_synonyms USING btree (term);
CREATE INDEX idx_search_weights_category_id ON public.search_weights USING btree (category_id) WHERE (category_id IS NOT NULL);
CREATE INDEX idx_search_weights_field_name ON public.search_weights USING btree (field_name);
CREATE INDEX idx_search_weights_history_changed_at ON public.search_weights_history USING btree (changed_at);
CREATE INDEX idx_search_weights_history_changed_by ON public.search_weights_history USING btree (changed_by);
CREATE INDEX idx_search_weights_history_weight_id ON public.search_weights_history USING btree (weight_id);
CREATE INDEX idx_search_weights_is_active ON public.search_weights USING btree (is_active) WHERE (is_active = true);
CREATE INDEX idx_search_weights_item_type ON public.search_weights USING btree (item_type);
CREATE INDEX idx_shopping_cart_items_cart_id ON public.shopping_cart_items USING btree (cart_id);
CREATE INDEX idx_shopping_cart_items_product_id ON public.shopping_cart_items USING btree (product_id);
CREATE INDEX idx_shopping_carts_session_id ON public.shopping_carts USING btree (session_id);
CREATE INDEX idx_shopping_carts_storefront_id ON public.shopping_carts USING btree (storefront_id);
CREATE INDEX idx_shopping_carts_user_id ON public.shopping_carts USING btree (user_id);
CREATE INDEX idx_staff_storefront_id ON public.storefront_staff USING btree (storefront_id);
CREATE INDEX idx_staff_user_id ON public.storefront_staff USING btree (user_id);
CREATE INDEX idx_storefront_inventory_movements_created_at ON public.storefront_inventory_movements USING btree (created_at);
CREATE INDEX idx_storefront_inventory_movements_product_id ON public.storefront_inventory_movements USING btree (storefront_product_id);
CREATE INDEX idx_storefront_inventory_movements_type ON public.storefront_inventory_movements USING btree (type);
CREATE INDEX idx_storefront_inventory_movements_variant_id ON public.storefront_inventory_movements USING btree (variant_id) WHERE (variant_id IS NOT NULL);
CREATE INDEX idx_storefront_order_items_order_id ON public.storefront_order_items USING btree (order_id);
CREATE INDEX idx_storefront_order_items_product_id ON public.storefront_order_items USING btree (product_id);
CREATE INDEX idx_storefront_order_items_variant_id ON public.storefront_order_items USING btree (variant_id);
CREATE INDEX idx_storefront_orders_customer ON public.storefront_orders USING btree (customer_id, created_at DESC);
CREATE INDEX idx_storefront_orders_escrow_date ON public.storefront_orders USING btree (escrow_release_date) WHERE (escrow_release_date IS NOT NULL);
CREATE INDEX idx_storefront_orders_status ON public.storefront_orders USING btree (status);
CREATE INDEX idx_storefront_orders_storefront ON public.storefront_orders USING btree (storefront_id, created_at DESC);
CREATE INDEX idx_storefront_product_attributes_attribute_id ON public.storefront_product_attributes USING btree (attribute_id);
CREATE INDEX idx_storefront_product_attributes_enabled ON public.storefront_product_attributes USING btree (is_enabled);
CREATE INDEX idx_storefront_product_attributes_product_id ON public.storefront_product_attributes USING btree (product_id);
CREATE INDEX idx_storefront_product_images_display_order ON public.storefront_product_images USING btree (display_order);
CREATE INDEX idx_storefront_product_images_product_id ON public.storefront_product_images USING btree (storefront_product_id);
CREATE INDEX idx_storefront_product_variant_images_is_main ON public.storefront_product_variant_images USING btree (is_main);
CREATE INDEX idx_storefront_product_variant_images_variant_id ON public.storefront_product_variant_images USING btree (variant_id);
CREATE INDEX idx_storefront_product_variants_attributes_gin ON public.storefront_product_variants USING gin (variant_attributes);
CREATE INDEX idx_storefront_product_variants_barcode ON public.storefront_product_variants USING btree (barcode) WHERE (barcode IS NOT NULL);
CREATE INDEX idx_storefront_product_variants_is_active ON public.storefront_product_variants USING btree (is_active);
CREATE INDEX idx_storefront_product_variants_is_default ON public.storefront_product_variants USING btree (is_default);
CREATE INDEX idx_storefront_product_variants_product_id ON public.storefront_product_variants USING btree (product_id);
CREATE INDEX idx_storefront_product_variants_sku ON public.storefront_product_variants USING btree (sku) WHERE (sku IS NOT NULL);
CREATE INDEX idx_storefront_products_barcode ON public.storefront_products USING btree (barcode) WHERE (barcode IS NOT NULL);
CREATE INDEX idx_storefront_products_category_id ON public.storefront_products USING btree (category_id);
CREATE INDEX idx_storefront_products_has_variants ON public.storefront_products USING btree (has_variants);
CREATE INDEX idx_storefront_products_is_active ON public.storefront_products USING btree (is_active);
CREATE INDEX idx_storefront_products_name_gin ON public.storefront_products USING gin (to_tsvector('simple'::regconfig, (name)::text));
CREATE INDEX idx_storefront_products_privacy ON public.storefront_products USING btree (location_privacy);
CREATE INDEX idx_storefront_products_show_on_map ON public.storefront_products USING btree (show_on_map);
CREATE INDEX idx_storefront_products_sku ON public.storefront_products USING btree (sku) WHERE (sku IS NOT NULL);
CREATE INDEX idx_storefront_products_stock_status ON public.storefront_products USING btree (stock_status);
CREATE INDEX idx_storefront_products_storefront_id ON public.storefront_products USING btree (storefront_id);
CREATE INDEX idx_storefronts_city ON public.storefronts USING btree (city);
CREATE INDEX idx_storefronts_coordinates ON public.storefronts USING btree (latitude, longitude) WHERE ((latitude IS NOT NULL) AND (longitude IS NOT NULL));
CREATE INDEX idx_storefronts_geo_strategy ON public.storefronts USING btree (geo_strategy);
CREATE INDEX idx_storefronts_is_active ON public.storefronts USING btree (is_active);
CREATE INDEX idx_storefronts_rating ON public.storefronts USING btree (rating DESC);
CREATE INDEX idx_storefronts_slug ON public.storefronts USING btree (slug);
CREATE INDEX idx_storefronts_user_id ON public.storefronts USING btree (user_id);
CREATE INDEX idx_sync_conflicts_dates ON public.translation_sync_conflicts USING btree (created_at DESC);
CREATE INDEX idx_sync_conflicts_unresolved ON public.translation_sync_conflicts USING btree (resolved) WHERE (resolved = false);
CREATE INDEX idx_transactions_created ON public.balance_transactions USING btree (created_at);
CREATE INDEX idx_transactions_status ON public.balance_transactions USING btree (status);
CREATE INDEX idx_transactions_user ON public.balance_transactions USING btree (user_id);
CREATE INDEX idx_translation_tasks_assigned ON public.translation_tasks USING btree (assigned_to, status);
CREATE INDEX idx_translation_tasks_status ON public.translation_tasks USING btree (status, created_at) WHERE ((status)::text <> 'completed'::text);
CREATE INDEX idx_translations_entity_field ON public.translations USING btree (entity_type, entity_id, field_name, language) WHERE ((entity_type)::text = 'listing'::text);
