CREATE INDEX idx_users_role_id ON public.users USING btree (role_id);
CREATE INDEX idx_users_status ON public.users USING btree (account_status);
CREATE INDEX idx_variant_attribute_mappings_category_id ON public.variant_attribute_mappings USING btree (category_attribute_id);
CREATE INDEX idx_variant_attribute_mappings_variant_id ON public.variant_attribute_mappings USING btree (variant_attribute_id);
CREATE INDEX idx_warehouse_inventory_available ON public.warehouse_inventory USING btree (quantity_available);
CREATE INDEX idx_warehouse_inventory_marketplace_listing ON public.warehouse_inventory USING btree (marketplace_listing_id);
CREATE INDEX idx_warehouse_inventory_sku ON public.warehouse_inventory USING btree (sku);
CREATE INDEX idx_warehouse_inventory_storefront_product ON public.warehouse_inventory USING btree (storefront_product_id);
CREATE INDEX idx_warehouse_inventory_warehouse ON public.warehouse_inventory USING btree (warehouse_id);
CREATE INDEX idx_warehouse_invoices_period ON public.warehouse_invoices USING btree (period_start, period_end);
CREATE INDEX idx_warehouse_invoices_status ON public.warehouse_invoices USING btree (status);
CREATE INDEX idx_warehouse_invoices_storefront ON public.warehouse_invoices USING btree (storefront_id);
CREATE INDEX idx_warehouse_movements_created ON public.warehouse_movements USING btree (created_at);
CREATE INDEX idx_warehouse_movements_inventory ON public.warehouse_movements USING btree (inventory_id);
CREATE INDEX idx_warehouse_movements_type ON public.warehouse_movements USING btree (movement_type);
CREATE INDEX idx_warehouse_movements_warehouse ON public.warehouse_movements USING btree (warehouse_id);
CREATE INDEX idx_warehouse_pickup_orders_code ON public.warehouse_pickup_orders USING btree (pickup_code);
CREATE INDEX idx_warehouse_pickup_orders_expires ON public.warehouse_pickup_orders USING btree (expires_at);
CREATE INDEX idx_warehouse_pickup_orders_status ON public.warehouse_pickup_orders USING btree (status);
CREATE INDEX idx_warehouse_pickup_orders_warehouse ON public.warehouse_pickup_orders USING btree (warehouse_id);
SELECT pg_catalog.setval('public.address_change_log_id_seq', 1, false);
SELECT pg_catalog.setval('public.admin_users_id_seq', 24, true);
SELECT pg_catalog.setval('public.attribute_group_items_id_seq', 1, false);
SELECT pg_catalog.setval('public.attribute_groups_id_seq', 1, false);
SELECT pg_catalog.setval('public.attribute_option_translations_id_seq', 3699, true);
SELECT pg_catalog.setval('public.balance_transactions_id_seq', 26, false);
SELECT pg_catalog.setval('public.car_generations_id_seq', 1, false);
SELECT pg_catalog.setval('public.car_makes_id_seq', 115, true);
SELECT pg_catalog.setval('public.car_market_analysis_id_seq', 250, true);
SELECT pg_catalog.setval('public.car_models_id_seq', 3862, true);
SELECT pg_catalog.setval('public.category_attribute_groups_id_seq', 1, false);
SELECT pg_catalog.setval('public.category_attributes_id_seq', 3236, true);
SELECT pg_catalog.setval('public.category_keywords_id_seq', 337, true);
SELECT pg_catalog.setval('public.category_variant_attributes_id_seq', 12, true);
SELECT pg_catalog.setval('public.chat_attachments_id_seq', 141, false);
SELECT pg_catalog.setval('public.component_templates_id_seq', 1, false);
SELECT pg_catalog.setval('public.custom_ui_component_usage_id_seq', 1, false);
SELECT pg_catalog.setval('public.custom_ui_components_id_seq', 2, false);
SELECT pg_catalog.setval('public.custom_ui_templates_id_seq', 1, false);
SELECT pg_catalog.setval('public.escrow_payments_id_seq', 1, false);
SELECT pg_catalog.setval('public.geocoding_cache_id_seq', 12, true);
SELECT pg_catalog.setval('public.gis_filter_analytics_id_seq', 1, false);
SELECT pg_catalog.setval('public.gis_isochrone_cache_id_seq', 1, false);
SELECT pg_catalog.setval('public.gis_poi_cache_id_seq', 1, false);
SELECT pg_catalog.setval('public.global_product_id_seq', 114, true);
SELECT pg_catalog.setval('public.import_history_id_seq', 1, false);
SELECT pg_catalog.setval('public.import_sources_id_seq', 1, false);
SELECT pg_catalog.setval('public.imported_categories_id_seq', 1, false);
SELECT pg_catalog.setval('public.inventory_reservations_id_seq', 17, true);
SELECT pg_catalog.setval('public.item_performance_metrics_id_seq', 1, false);
SELECT pg_catalog.setval('public.listing_attribute_values_id_seq', 177, true);
SELECT pg_catalog.setval('public.listing_views_id_seq', 2, true);
SELECT pg_catalog.setval('public.listings_geo_id_seq', 1, false);
SELECT pg_catalog.setval('public.map_items_cache_id_seq', 1, false);
SELECT pg_catalog.setval('public.marketplace_categories_id_seq', 10001, true);
SELECT pg_catalog.setval('public.marketplace_chats_id_seq', 5, true);
SELECT pg_catalog.setval('public.marketplace_images_id_seq', 55, true);
SELECT pg_catalog.setval('public.marketplace_messages_id_seq', 20, true);
SELECT pg_catalog.setval('public.marketplace_orders_id_seq', 1, false);
SELECT pg_catalog.setval('public.merchant_payouts_id_seq', 1, false);
SELECT pg_catalog.setval('public.notifications_id_seq', 25, true);
SELECT pg_catalog.setval('public.payment_gateways_id_seq', 2, false);
SELECT pg_catalog.setval('public.payment_methods_id_seq', 27, false);
SELECT pg_catalog.setval('public.payment_transactions_id_seq', 1, false);
SELECT pg_catalog.setval('public.permissions_id_seq', 86, true);
SELECT pg_catalog.setval('public.post_express_api_logs_id_seq', 1, false);
SELECT pg_catalog.setval('public.post_express_locations_id_seq', 1, false);
SELECT pg_catalog.setval('public.post_express_offices_id_seq', 1, false);
SELECT pg_catalog.setval('public.post_express_rates_id_seq', 4, true);
SELECT pg_catalog.setval('public.post_express_settings_id_seq', 1, false);
SELECT pg_catalog.setval('public.post_express_shipments_id_seq', 1, false);
SELECT pg_catalog.setval('public.post_express_tracking_events_id_seq', 1, false);
SELECT pg_catalog.setval('public.price_history_id_seq', 48, true);
SELECT pg_catalog.setval('public.product_variant_attribute_values_id_seq', 37, true);
SELECT pg_catalog.setval('public.product_variant_attributes_id_seq', 36, true);
SELECT pg_catalog.setval('public.refresh_tokens_id_seq', 5051, true);
SELECT pg_catalog.setval('public.review_confirmations_id_seq', 1, false);
SELECT pg_catalog.setval('public.review_disputes_id_seq', 1, false);
SELECT pg_catalog.setval('public.review_responses_id_seq', 1, false);
SELECT pg_catalog.setval('public.reviews_id_seq', 12, true);
SELECT pg_catalog.setval('public.role_audit_log_id_seq', 3, true);
SELECT pg_catalog.setval('public.roles_id_seq', 30, true);
SELECT pg_catalog.setval('public.search_behavior_metrics_id_seq', 1, false);
SELECT pg_catalog.setval('public.search_config_id_seq', 2, false);
SELECT pg_catalog.setval('public.search_optimization_sessions_id_seq', 1, false);
SELECT pg_catalog.setval('public.search_queries_id_seq', 99, true);
SELECT pg_catalog.setval('public.search_statistics_id_seq', 1, false);
SELECT pg_catalog.setval('public.search_synonyms_config_id_seq', 8, false);
SELECT pg_catalog.setval('public.search_synonyms_id_seq', 41, false);
SELECT pg_catalog.setval('public.search_weights_history_id_seq', 1, false);
SELECT pg_catalog.setval('public.search_weights_id_seq', 17, false);
SELECT pg_catalog.setval('public.shopping_cart_items_id_seq', 53, true);
SELECT pg_catalog.setval('public.shopping_carts_id_seq', 8, true);
SELECT pg_catalog.setval('public.storefront_delivery_options_id_seq', 1, true);
SELECT pg_catalog.setval('public.storefront_fbs_settings_id_seq', 1, false);
SELECT pg_catalog.setval('public.storefront_hours_id_seq', 25, true);
SELECT pg_catalog.setval('public.storefront_inventory_movements_id_seq', 1, true);
SELECT pg_catalog.setval('public.storefront_order_items_id_seq', 16, true);
SELECT pg_catalog.setval('public.storefront_orders_id_seq', 56, true);
SELECT pg_catalog.setval('public.storefront_payment_methods_id_seq', 15, true);
