CREATE INDEX idx_delivery_storefront_id ON public.storefront_delivery_options USING btree (storefront_id);
CREATE INDEX idx_density_grid_cell ON public.gis_listing_density_grid USING gist (cell);
CREATE INDEX idx_density_grid_density ON public.gis_listing_density_grid USING btree (density);
CREATE INDEX idx_disputes_review_id ON public.review_disputes USING btree (review_id);
CREATE INDEX idx_disputes_status ON public.review_disputes USING btree (status);
CREATE INDEX idx_districts_boundary ON public.districts USING gist (boundary);
CREATE INDEX idx_districts_center ON public.districts USING gist (center_point);
CREATE INDEX idx_districts_city_id ON public.districts USING btree (city_id);
CREATE INDEX idx_districts_country ON public.districts USING btree (country_code);
CREATE INDEX idx_districts_name ON public.districts USING btree (name);
CREATE INDEX idx_escrow_payments_buyer_id ON public.escrow_payments USING btree (buyer_id);
CREATE INDEX idx_escrow_payments_payment_transaction_id ON public.escrow_payments USING btree (payment_transaction_id);
CREATE INDEX idx_escrow_payments_seller_id ON public.escrow_payments USING btree (seller_id);
CREATE INDEX idx_escrow_payments_status ON public.escrow_payments USING btree (status);
CREATE INDEX idx_filter_analytics_created ON public.gis_filter_analytics USING btree (created_at);
CREATE INDEX idx_filter_analytics_type ON public.gis_filter_analytics USING btree (filter_type);
CREATE INDEX idx_filter_analytics_user ON public.gis_filter_analytics USING btree (user_id);
CREATE INDEX idx_geocoding_cache_address_components ON public.geocoding_cache USING gin (address_components);
CREATE INDEX idx_geocoding_cache_cache_hits ON public.geocoding_cache USING btree (cache_hits);
CREATE INDEX idx_geocoding_cache_confidence ON public.geocoding_cache USING btree (confidence);
CREATE INDEX idx_geocoding_cache_country_lang ON public.geocoding_cache USING btree (country_code, language);
CREATE INDEX idx_geocoding_cache_expires_at ON public.geocoding_cache USING btree (expires_at);
CREATE INDEX idx_geocoding_cache_input_address ON public.geocoding_cache USING btree (input_address);
CREATE INDEX idx_geocoding_cache_normalized ON public.geocoding_cache USING btree (normalized_address);
CREATE INDEX idx_geocoding_cache_provider ON public.geocoding_cache USING btree (provider);
CREATE INDEX idx_hours_storefront_id ON public.storefront_hours USING btree (storefront_id);
CREATE INDEX idx_import_history_source ON public.import_history USING btree (source_id);
CREATE INDEX idx_import_sources_storefront ON public.import_sources USING btree (storefront_id);
CREATE INDEX idx_imported_categories_source_id ON public.imported_categories USING btree (source_id);
CREATE INDEX idx_inventory_reservations_expires_at ON public.inventory_reservations USING btree (expires_at);
CREATE INDEX idx_inventory_reservations_order_id ON public.inventory_reservations USING btree (order_id);
CREATE INDEX idx_inventory_reservations_product_id ON public.inventory_reservations USING btree (product_id);
CREATE INDEX idx_inventory_reservations_status ON public.inventory_reservations USING btree (status);
CREATE INDEX idx_inventory_reservations_variant_id ON public.inventory_reservations USING btree (variant_id);
CREATE INDEX idx_isochrone_cache_center ON public.gis_isochrone_cache USING gist (center_point);
CREATE INDEX idx_isochrone_cache_expires ON public.gis_isochrone_cache USING btree (expires_at);
CREATE INDEX idx_isochrone_cache_lookup ON public.gis_isochrone_cache USING btree (transport_mode, max_minutes);
CREATE INDEX idx_item_performance_metrics_conversions ON public.item_performance_metrics USING btree (conversions DESC);
CREATE INDEX idx_item_performance_metrics_ctr ON public.item_performance_metrics USING btree (ctr DESC);
CREATE INDEX idx_item_performance_metrics_impressions ON public.item_performance_metrics USING btree (impressions DESC);
CREATE INDEX idx_item_performance_metrics_item ON public.item_performance_metrics USING btree (item_id, item_type);
CREATE INDEX idx_item_performance_metrics_period ON public.item_performance_metrics USING btree (period_start, period_end);
CREATE UNIQUE INDEX idx_item_performance_metrics_unique ON public.item_performance_metrics USING btree (item_id, period_start);
CREATE INDEX idx_keyword_lower ON public.category_keywords USING btree (lower((keyword)::text));
CREATE INDEX idx_keyword_type ON public.category_keywords USING btree (keyword_type);
CREATE INDEX idx_language ON public.category_keywords USING btree (language);
CREATE INDEX idx_listing_views_listing_ip ON public.listing_views USING btree (listing_id, ip_hash);
CREATE INDEX idx_listing_views_listing_user ON public.listing_views USING btree (listing_id, user_id);
CREATE INDEX idx_listing_views_time ON public.listing_views USING btree (view_time);
CREATE INDEX idx_listings_geo_address_components ON public.listings_geo USING gin (address_components);
CREATE INDEX idx_listings_geo_confidence ON public.listings_geo USING btree (geocoding_confidence);
CREATE INDEX idx_listings_geo_district ON public.listings_geo USING btree (district_id);
CREATE INDEX idx_listings_geo_geohash ON public.listings_geo USING btree (geohash);
CREATE INDEX idx_listings_geo_geohash_precise ON public.listings_geo USING btree (geohash, is_precise);
CREATE INDEX idx_listings_geo_input_method ON public.listings_geo USING btree (input_method);
CREATE INDEX idx_listings_geo_is_precise ON public.listings_geo USING btree (is_precise);
CREATE INDEX idx_listings_geo_municipality ON public.listings_geo USING btree (municipality_id);
CREATE INDEX idx_listings_geo_privacy ON public.listings_geo USING btree (location_privacy);
CREATE INDEX idx_listings_geo_verified ON public.listings_geo USING btree (address_verified);
CREATE INDEX idx_listings_metadata_discount ON public.marketplace_listings USING gin (((metadata -> 'discount'::text)));
CREATE INDEX idx_map_items_cache_category ON public.map_items_cache USING btree (category_id) WHERE (category_id IS NOT NULL);
CREATE INDEX idx_map_items_cache_expires ON public.map_items_cache USING btree (expires_at) WHERE (expires_at IS NOT NULL);
CREATE INDEX idx_map_items_cache_type_id ON public.map_items_cache USING btree (item_type, item_id);
CREATE UNIQUE INDEX idx_map_items_cache_unique ON public.map_items_cache USING btree (item_type, item_id);
CREATE INDEX idx_marketplace_categories_external_id ON public.marketplace_categories USING btree (external_id);
CREATE INDEX idx_marketplace_categories_parent ON public.marketplace_categories USING btree (parent_id);
CREATE INDEX idx_marketplace_categories_slug ON public.marketplace_categories USING btree (slug);
CREATE INDEX idx_marketplace_chats_active_sorted ON public.marketplace_chats USING btree (last_message_at DESC) WHERE (NOT is_archived);
CREATE INDEX idx_marketplace_chats_archived ON public.marketplace_chats USING btree (is_archived) WHERE (NOT is_archived);
CREATE INDEX idx_marketplace_chats_buyer ON public.marketplace_chats USING btree (buyer_id);
CREATE INDEX idx_marketplace_chats_listing ON public.marketplace_chats USING btree (listing_id) WHERE (listing_id IS NOT NULL);
CREATE INDEX idx_marketplace_chats_listing_participants ON public.marketplace_chats USING btree (listing_id, buyer_id, seller_id) WHERE (listing_id IS NOT NULL);
CREATE INDEX idx_marketplace_chats_participants ON public.marketplace_chats USING btree (LEAST(buyer_id, seller_id), GREATEST(buyer_id, seller_id));
CREATE INDEX idx_marketplace_chats_seller ON public.marketplace_chats USING btree (seller_id);
CREATE INDEX idx_marketplace_chats_storefront_product_id ON public.marketplace_chats USING btree (storefront_product_id);
CREATE INDEX idx_marketplace_chats_updated ON public.marketplace_chats USING btree (updated_at);
CREATE INDEX idx_marketplace_chats_user_lookup ON public.marketplace_chats USING btree (buyer_id, seller_id, last_message_at DESC);
CREATE INDEX idx_marketplace_favorites_listing ON public.marketplace_favorites USING btree (listing_id);
CREATE INDEX idx_marketplace_favorites_user_count ON public.marketplace_favorites USING btree (user_id, created_at DESC);
CREATE INDEX idx_marketplace_images_listing_main ON public.marketplace_images USING btree (listing_id, is_main) WHERE (is_main = true);
CREATE INDEX idx_marketplace_listing_variants_attributes ON public.marketplace_listing_variants USING gin (attributes);
CREATE INDEX idx_marketplace_listing_variants_is_active ON public.marketplace_listing_variants USING btree (is_active);
CREATE INDEX idx_marketplace_listing_variants_listing_id ON public.marketplace_listing_variants USING btree (listing_id);
CREATE INDEX idx_marketplace_listing_variants_sku ON public.marketplace_listing_variants USING btree (sku);
CREATE INDEX idx_marketplace_listings_category_status ON public.marketplace_listings USING btree (category_id, status) WHERE ((status)::text = 'active'::text);
CREATE INDEX idx_marketplace_listings_city ON public.marketplace_listings USING btree (address_city) WHERE (address_city IS NOT NULL);
CREATE INDEX idx_marketplace_listings_created_at_desc ON public.marketplace_listings USING btree (created_at DESC) WHERE ((status)::text = 'active'::text);
CREATE INDEX idx_marketplace_listings_description_trgm ON public.marketplace_listings USING gin (description public.gin_trgm_ops);
CREATE INDEX idx_marketplace_listings_external_id ON public.marketplace_listings USING btree (external_id);
CREATE INDEX idx_marketplace_listings_external_id_storefront_id ON public.marketplace_listings USING btree (external_id, storefront_id);
CREATE INDEX idx_marketplace_listings_price ON public.marketplace_listings USING btree (price) WHERE ((price IS NOT NULL) AND ((status)::text = 'active'::text));
CREATE INDEX idx_marketplace_listings_status ON public.marketplace_listings USING btree (status);
CREATE INDEX idx_marketplace_listings_status_category ON public.marketplace_listings USING btree (status, category_id) WHERE ((status)::text = 'active'::text);
CREATE INDEX idx_marketplace_listings_status_created ON public.marketplace_listings USING btree (status, created_at DESC) WHERE ((status)::text = 'active'::text);
CREATE INDEX idx_marketplace_listings_storefront ON public.marketplace_listings USING btree (storefront_id);
CREATE INDEX idx_marketplace_listings_title_gin ON public.marketplace_listings USING gin (to_tsvector('simple'::regconfig, (title)::text));
CREATE INDEX idx_marketplace_listings_title_trgm ON public.marketplace_listings USING gin (title public.gin_trgm_ops);
CREATE INDEX idx_marketplace_listings_user_status ON public.marketplace_listings USING btree (user_id, status, created_at DESC);
CREATE INDEX idx_marketplace_messages_chat ON public.marketplace_messages USING btree (chat_id);
CREATE INDEX idx_marketplace_messages_chat_last ON public.marketplace_messages USING btree (chat_id, id DESC);
