CREATE INDEX idx_marketplace_orders_status ON public.marketplace_orders USING btree (status);
CREATE INDEX idx_merchant_payouts_gateway_payout_id ON public.merchant_payouts USING btree (gateway_payout_id);
CREATE INDEX idx_merchant_payouts_seller_id ON public.merchant_payouts USING btree (seller_id);
CREATE INDEX idx_merchant_payouts_status ON public.merchant_payouts USING btree (status);
CREATE INDEX idx_municipalities_boundary ON public.municipalities USING gist (boundary);
CREATE INDEX idx_municipalities_center ON public.municipalities USING gist (center_point);
CREATE INDEX idx_municipalities_district ON public.municipalities USING btree (district_id);
CREATE INDEX idx_municipalities_name ON public.municipalities USING btree (name);
CREATE UNIQUE INDEX idx_mv_category_statistics_id ON public.mv_category_statistics USING btree (category_id);
CREATE UNIQUE INDEX idx_mv_popular_category_attrs_pk ON public.mv_popular_category_attributes USING btree (category_id, attribute_id);
CREATE INDEX idx_notifications_created ON public.notifications USING btree (created_at);
CREATE INDEX idx_notifications_type ON public.notifications USING btree (type);
CREATE INDEX idx_notifications_user ON public.notifications USING btree (user_id);
CREATE INDEX idx_notifications_user_unread ON public.notifications USING btree (user_id, created_at DESC) WHERE (NOT is_read);
CREATE INDEX idx_payment_is_enabled ON public.storefront_payment_methods USING btree (is_enabled);
CREATE INDEX idx_payment_storefront_id ON public.storefront_payment_methods USING btree (storefront_id);
CREATE INDEX idx_payment_transactions_auto_capture ON public.payment_transactions USING btree (auto_capture_at, status) WHERE (((status)::text = 'authorized'::text) AND ((capture_mode)::text = 'auto'::text));
CREATE INDEX idx_payment_transactions_created_at ON public.payment_transactions USING btree (created_at);
CREATE INDEX idx_payment_transactions_gateway_transaction_id ON public.payment_transactions USING btree (gateway_transaction_id);
CREATE INDEX idx_payment_transactions_listing_id ON public.payment_transactions USING btree (listing_id);
CREATE INDEX idx_payment_transactions_order_reference ON public.payment_transactions USING btree (order_reference);
CREATE INDEX idx_payment_transactions_source ON public.payment_transactions USING btree (source_type, source_id);
CREATE INDEX idx_payment_transactions_status ON public.payment_transactions USING btree (status);
CREATE INDEX idx_payment_transactions_user_id ON public.payment_transactions USING btree (user_id);
CREATE INDEX idx_poi_cache_expires ON public.gis_poi_cache USING btree (expires_at);
CREATE INDEX idx_poi_cache_type ON public.gis_poi_cache USING btree (poi_type);
CREATE INDEX idx_price_history_current ON public.price_history USING btree (listing_id, effective_from DESC) WHERE (effective_to IS NULL);
CREATE INDEX idx_price_history_effective ON public.price_history USING btree (listing_id, effective_to);
CREATE INDEX idx_price_history_listing_id ON public.price_history USING btree (listing_id);
CREATE INDEX idx_product_variant_attribute_values_attribute_id ON public.product_variant_attribute_values USING btree (attribute_id);
CREATE INDEX idx_product_variant_attribute_values_value ON public.product_variant_attribute_values USING btree (value);
CREATE INDEX idx_product_variant_attributes_affects_stock ON public.product_variant_attributes USING btree (affects_stock) WHERE (affects_stock = true);
CREATE INDEX idx_product_variant_attributes_name ON public.product_variant_attributes USING btree (name);
CREATE INDEX idx_providers_active ON public.translation_providers USING btree (is_active, priority) WHERE (is_active = true);
CREATE INDEX idx_quality_metrics_issues ON public.translation_quality_metrics USING btree (has_placeholders, has_html_tags);
CREATE INDEX idx_quality_metrics_score ON public.translation_quality_metrics USING btree (quality_score);
CREATE INDEX idx_query_cache_hash ON public.query_cache USING btree (query_hash);
CREATE INDEX idx_rating_cache_type_rating ON public.rating_cache USING btree (entity_type, average_rating DESC);
CREATE INDEX idx_rating_cache_updated ON public.rating_cache USING btree (calculated_at);
CREATE INDEX idx_refresh_tokens_expires_at ON public.refresh_tokens USING btree (expires_at) WHERE (NOT is_revoked);
CREATE INDEX idx_refresh_tokens_token ON public.refresh_tokens USING btree (token) WHERE (NOT is_revoked);
CREATE INDEX idx_refresh_tokens_user_id ON public.refresh_tokens USING btree (user_id) WHERE (NOT is_revoked);
CREATE INDEX idx_review_responses_review ON public.review_responses USING btree (review_id);
CREATE INDEX idx_reviews_entity ON public.reviews USING btree (entity_type, entity_id);
CREATE INDEX idx_reviews_entity_origin ON public.reviews USING btree (entity_origin_type, entity_origin_id);
CREATE INDEX idx_reviews_has_dispute ON public.reviews USING btree (has_active_dispute) WHERE (has_active_dispute = true);
CREATE INDEX idx_reviews_rating ON public.reviews USING btree (rating);
CREATE INDEX idx_reviews_seller_confirmed ON public.reviews USING btree (seller_confirmed) WHERE (seller_confirmed = true);
CREATE INDEX idx_reviews_status ON public.reviews USING btree (status);
CREATE INDEX idx_reviews_user ON public.reviews USING btree (user_id);
CREATE UNIQUE INDEX idx_reviews_user_entity_unique ON public.reviews USING btree (user_id, entity_type, entity_id) WHERE ((status)::text <> 'deleted'::text);
CREATE INDEX idx_role_audit_log_created_at ON public.role_audit_log USING btree (created_at DESC);
CREATE INDEX idx_role_audit_log_target_user_id ON public.role_audit_log USING btree (target_user_id);
CREATE INDEX idx_role_audit_log_user_id ON public.role_audit_log USING btree (user_id);
CREATE INDEX idx_role_permissions_permission_id ON public.role_permissions USING btree (permission_id);
CREATE INDEX idx_role_permissions_role_id ON public.role_permissions USING btree (role_id);
CREATE INDEX idx_search_behavior_metrics_conversions ON public.search_behavior_metrics USING btree (conversions DESC);
CREATE INDEX idx_search_behavior_metrics_ctr ON public.search_behavior_metrics USING btree (ctr DESC);
CREATE INDEX idx_search_behavior_metrics_period ON public.search_behavior_metrics USING btree (period_start, period_end);
CREATE INDEX idx_search_behavior_metrics_query ON public.search_behavior_metrics USING btree (search_query);
CREATE UNIQUE INDEX idx_search_behavior_metrics_unique ON public.search_behavior_metrics USING btree (search_query, period_start);
CREATE INDEX idx_search_optimization_sessions_created_by ON public.search_optimization_sessions USING btree (created_by);
CREATE INDEX idx_search_optimization_sessions_start_time ON public.search_optimization_sessions USING btree (start_time);
CREATE INDEX idx_search_optimization_sessions_status ON public.search_optimization_sessions USING btree (status);
CREATE INDEX idx_search_queries_language ON public.search_queries USING btree (language);
CREATE INDEX idx_search_queries_normalized_query ON public.search_queries USING btree (normalized_query);
CREATE INDEX idx_search_queries_search_count ON public.search_queries USING btree (search_count DESC);
CREATE INDEX idx_search_synonyms_active ON public.search_synonyms USING btree (is_active) WHERE (is_active = true);
CREATE INDEX idx_search_synonyms_config_term ON public.search_synonyms_config USING btree (term);
CREATE INDEX idx_search_synonyms_language ON public.search_synonyms USING btree (language);
CREATE INDEX idx_search_synonyms_synonym ON public.search_synonyms USING btree (synonym);
CREATE INDEX idx_search_synonyms_term ON public.search_synonyms USING btree (term);
CREATE UNIQUE INDEX idx_search_synonyms_unique ON public.search_synonyms USING btree (term, synonym, language) WHERE (is_active = true);
CREATE INDEX idx_search_weights_category_id ON public.search_weights USING btree (category_id) WHERE (category_id IS NOT NULL);
CREATE INDEX idx_search_weights_field_name ON public.search_weights USING btree (field_name);
CREATE INDEX idx_search_weights_history_changed_at ON public.search_weights_history USING btree (changed_at);
CREATE INDEX idx_search_weights_history_changed_by ON public.search_weights_history USING btree (changed_by);
CREATE INDEX idx_search_weights_history_weight_id ON public.search_weights_history USING btree (weight_id);
CREATE INDEX idx_search_weights_is_active ON public.search_weights USING btree (is_active) WHERE (is_active = true);
CREATE INDEX idx_search_weights_item_type ON public.search_weights USING btree (item_type);
CREATE UNIQUE INDEX idx_search_weights_unique_category ON public.search_weights USING btree (field_name, item_type, search_type, category_id) WHERE (category_id IS NOT NULL);
CREATE UNIQUE INDEX idx_search_weights_unique_global ON public.search_weights USING btree (field_name, item_type, search_type) WHERE (category_id IS NULL);
CREATE INDEX idx_shopping_cart_items_cart_id ON public.shopping_cart_items USING btree (cart_id);
CREATE INDEX idx_shopping_cart_items_product_id ON public.shopping_cart_items USING btree (product_id);
CREATE INDEX idx_shopping_carts_session_id ON public.shopping_carts USING btree (session_id);
CREATE INDEX idx_shopping_carts_storefront_id ON public.shopping_carts USING btree (storefront_id);
CREATE INDEX idx_shopping_carts_user_id ON public.shopping_carts USING btree (user_id);
CREATE INDEX idx_staff_storefront_id ON public.storefront_staff USING btree (storefront_id);
CREATE INDEX idx_staff_user_id ON public.storefront_staff USING btree (user_id);
CREATE INDEX idx_storefront_inventory_movements_created_at ON public.storefront_inventory_movements USING btree (created_at);
CREATE INDEX idx_storefront_inventory_movements_product_id ON public.storefront_inventory_movements USING btree (storefront_product_id);
CREATE INDEX idx_storefront_inventory_movements_type ON public.storefront_inventory_movements USING btree (type);
CREATE INDEX idx_storefront_inventory_movements_variant_id ON public.storefront_inventory_movements USING btree (variant_id) WHERE (variant_id IS NOT NULL);
CREATE INDEX idx_storefront_order_items_order_id ON public.storefront_order_items USING btree (order_id);
CREATE INDEX idx_storefront_order_items_product_id ON public.storefront_order_items USING btree (product_id);
CREATE INDEX idx_storefront_order_items_variant_id ON public.storefront_order_items USING btree (variant_id);
CREATE INDEX idx_storefront_orders_customer ON public.storefront_orders USING btree (customer_id, created_at DESC);
CREATE INDEX idx_storefront_orders_escrow_date ON public.storefront_orders USING btree (escrow_release_date) WHERE (escrow_release_date IS NOT NULL);
CREATE INDEX idx_storefront_orders_status ON public.storefront_orders USING btree (status);
CREATE INDEX idx_storefront_orders_storefront ON public.storefront_orders USING btree (storefront_id, created_at DESC);
