BEGIN;

-- Drop C2C tables
DROP TABLE IF EXISTS c2c_listing_variants CASCADE;
DROP TABLE IF EXISTS c2c_orders CASCADE;
DROP TABLE IF EXISTS c2c_favorites CASCADE;
DROP TABLE IF EXISTS c2c_messages CASCADE;
DROP TABLE IF EXISTS c2c_chats CASCADE;
DROP TABLE IF EXISTS c2c_images CASCADE;
DROP TABLE IF EXISTS c2c_listings CASCADE;
DROP TABLE IF EXISTS c2c_categories CASCADE;

-- Drop B2C tables
DROP TABLE IF EXISTS b2c_product_variant_images CASCADE;
DROP TABLE IF EXISTS user_b2c_stores CASCADE;
DROP TABLE IF EXISTS b2c_inventory_movements CASCADE;
DROP TABLE IF EXISTS b2c_delivery_options CASCADE;
DROP TABLE IF EXISTS b2c_payment_methods CASCADE;
DROP TABLE IF EXISTS b2c_store_staff CASCADE;
DROP TABLE IF EXISTS b2c_store_hours CASCADE;
DROP TABLE IF EXISTS b2c_favorites CASCADE;
DROP TABLE IF EXISTS b2c_order_items CASCADE;
DROP TABLE IF EXISTS b2c_orders CASCADE;
DROP TABLE IF EXISTS b2c_product_attributes CASCADE;
DROP TABLE IF EXISTS b2c_product_variants CASCADE;
DROP TABLE IF EXISTS b2c_product_images CASCADE;
DROP TABLE IF EXISTS b2c_products CASCADE;
DROP TABLE IF EXISTS b2c_stores CASCADE;

COMMIT;
