// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: api/proto/chat/v1/chat.proto

package chatsvcv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ChatStatus represents the state of a chat
type ChatStatus int32

const (
	ChatStatus_CHAT_STATUS_UNSPECIFIED ChatStatus = 0
	ChatStatus_CHAT_STATUS_ACTIVE      ChatStatus = 1 // Chat is active
	ChatStatus_CHAT_STATUS_ARCHIVED    ChatStatus = 2 // Chat archived by user
	ChatStatus_CHAT_STATUS_BLOCKED     ChatStatus = 3 // Chat blocked (spam/abuse)
)

// Enum value maps for ChatStatus.
var (
	ChatStatus_name = map[int32]string{
		0: "CHAT_STATUS_UNSPECIFIED",
		1: "CHAT_STATUS_ACTIVE",
		2: "CHAT_STATUS_ARCHIVED",
		3: "CHAT_STATUS_BLOCKED",
	}
	ChatStatus_value = map[string]int32{
		"CHAT_STATUS_UNSPECIFIED": 0,
		"CHAT_STATUS_ACTIVE":      1,
		"CHAT_STATUS_ARCHIVED":    2,
		"CHAT_STATUS_BLOCKED":     3,
	}
)

func (x ChatStatus) Enum() *ChatStatus {
	p := new(ChatStatus)
	*p = x
	return p
}

func (x ChatStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChatStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_chat_v1_chat_proto_enumTypes[0].Descriptor()
}

func (ChatStatus) Type() protoreflect.EnumType {
	return &file_api_proto_chat_v1_chat_proto_enumTypes[0]
}

func (x ChatStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChatStatus.Descriptor instead.
func (ChatStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_chat_v1_chat_proto_rawDescGZIP(), []int{0}
}

// MessageStatus represents delivery/read status
type MessageStatus int32

const (
	MessageStatus_MESSAGE_STATUS_UNSPECIFIED MessageStatus = 0
	MessageStatus_MESSAGE_STATUS_SENT        MessageStatus = 1 // Message sent successfully
	MessageStatus_MESSAGE_STATUS_DELIVERED   MessageStatus = 2 // Message delivered to recipient
	MessageStatus_MESSAGE_STATUS_READ        MessageStatus = 3 // Message read by recipient
	MessageStatus_MESSAGE_STATUS_FAILED      MessageStatus = 4 // Message failed to send
)

// Enum value maps for MessageStatus.
var (
	MessageStatus_name = map[int32]string{
		0: "MESSAGE_STATUS_UNSPECIFIED",
		1: "MESSAGE_STATUS_SENT",
		2: "MESSAGE_STATUS_DELIVERED",
		3: "MESSAGE_STATUS_READ",
		4: "MESSAGE_STATUS_FAILED",
	}
	MessageStatus_value = map[string]int32{
		"MESSAGE_STATUS_UNSPECIFIED": 0,
		"MESSAGE_STATUS_SENT":        1,
		"MESSAGE_STATUS_DELIVERED":   2,
		"MESSAGE_STATUS_READ":        3,
		"MESSAGE_STATUS_FAILED":      4,
	}
)

func (x MessageStatus) Enum() *MessageStatus {
	p := new(MessageStatus)
	*p = x
	return p
}

func (x MessageStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_chat_v1_chat_proto_enumTypes[1].Descriptor()
}

func (MessageStatus) Type() protoreflect.EnumType {
	return &file_api_proto_chat_v1_chat_proto_enumTypes[1]
}

func (x MessageStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageStatus.Descriptor instead.
func (MessageStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_chat_v1_chat_proto_rawDescGZIP(), []int{1}
}

// AttachmentType represents the type of attachment
type AttachmentType int32

const (
	AttachmentType_ATTACHMENT_TYPE_UNSPECIFIED AttachmentType = 0
	AttachmentType_ATTACHMENT_TYPE_IMAGE       AttachmentType = 1 // Image file (jpg, png, gif, etc.)
	AttachmentType_ATTACHMENT_TYPE_VIDEO       AttachmentType = 2 // Video file (mp4, webm, etc.)
	AttachmentType_ATTACHMENT_TYPE_DOCUMENT    AttachmentType = 3 // Document (pdf, doc, txt, etc.)
)

// Enum value maps for AttachmentType.
var (
	AttachmentType_name = map[int32]string{
		0: "ATTACHMENT_TYPE_UNSPECIFIED",
		1: "ATTACHMENT_TYPE_IMAGE",
		2: "ATTACHMENT_TYPE_VIDEO",
		3: "ATTACHMENT_TYPE_DOCUMENT",
	}
	AttachmentType_value = map[string]int32{
		"ATTACHMENT_TYPE_UNSPECIFIED": 0,
		"ATTACHMENT_TYPE_IMAGE":       1,
		"ATTACHMENT_TYPE_VIDEO":       2,
		"ATTACHMENT_TYPE_DOCUMENT":    3,
	}
)

func (x AttachmentType) Enum() *AttachmentType {
	p := new(AttachmentType)
	*p = x
	return p
}

func (x AttachmentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AttachmentType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_chat_v1_chat_proto_enumTypes[2].Descriptor()
}

func (AttachmentType) Type() protoreflect.EnumType {
	return &file_api_proto_chat_v1_chat_proto_enumTypes[2]
}

func (x AttachmentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AttachmentType.Descriptor instead.
func (AttachmentType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_chat_v1_chat_proto_rawDescGZIP(), []int{2}
}

// Chat represents a conversation between buyer and seller
type Chat struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identification
	Id       int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	BuyerId  int64 `protobuf:"varint,2,opt,name=buyer_id,json=buyerId,proto3" json:"buyer_id,omitempty"`    // User who initiated chat
	SellerId int64 `protobuf:"varint,3,opt,name=seller_id,json=sellerId,proto3" json:"seller_id,omitempty"` // User who receives chat
	// Context (what is being discussed)
	ListingId           *int64 `protobuf:"varint,4,opt,name=listing_id,json=listingId,proto3,oneof" json:"listing_id,omitempty"`                                 // If discussing marketplace listing
	StorefrontProductId *int64 `protobuf:"varint,5,opt,name=storefront_product_id,json=storefrontProductId,proto3,oneof" json:"storefront_product_id,omitempty"` // If discussing B2C product
	// Status
	Status     ChatStatus `protobuf:"varint,6,opt,name=status,proto3,enum=chatsvc.v1.ChatStatus" json:"status,omitempty"` // Active, archived, blocked
	IsArchived bool       `protobuf:"varint,7,opt,name=is_archived,json=isArchived,proto3" json:"is_archived,omitempty"`  // Archived by current user
	// Metadata
	LastMessageAt *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=last_message_at,json=lastMessageAt,proto3" json:"last_message_at,omitempty"` // Last message timestamp
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Relations (loaded on demand)
	LastMessage *Message `protobuf:"bytes,11,opt,name=last_message,json=lastMessage,proto3" json:"last_message,omitempty"`  // Most recent message (for list view)
	UnreadCount int32    `protobuf:"varint,12,opt,name=unread_count,json=unreadCount,proto3" json:"unread_count,omitempty"` // Unread messages count for current user
	// Participant info (denormalized for UI)
	BuyerName       *string `protobuf:"bytes,13,opt,name=buyer_name,json=buyerName,proto3,oneof" json:"buyer_name,omitempty"`
	SellerName      *string `protobuf:"bytes,14,opt,name=seller_name,json=sellerName,proto3,oneof" json:"seller_name,omitempty"`
	ListingTitle    *string `protobuf:"bytes,15,opt,name=listing_title,json=listingTitle,proto3,oneof" json:"listing_title,omitempty"`            // If listing_id present
	ListingImageUrl *string `protobuf:"bytes,16,opt,name=listing_image_url,json=listingImageUrl,proto3,oneof" json:"listing_image_url,omitempty"` // First image of listing
	ListingOwnerId  *int64  `protobuf:"varint,17,opt,name=listing_owner_id,json=listingOwnerId,proto3,oneof" json:"listing_owner_id,omitempty"`   // Owner ID of listing
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Chat) Reset() {
	*x = Chat{}
	mi := &file_api_proto_chat_v1_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chat) ProtoMessage() {}

func (x *Chat) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_chat_v1_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chat.ProtoReflect.Descriptor instead.
func (*Chat) Descriptor() ([]byte, []int) {
	return file_api_proto_chat_v1_chat_proto_rawDescGZIP(), []int{0}
}

func (x *Chat) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Chat) GetBuyerId() int64 {
	if x != nil {
		return x.BuyerId
	}
	return 0
}

func (x *Chat) GetSellerId() int64 {
	if x != nil {
		return x.SellerId
	}
	return 0
}

func (x *Chat) GetListingId() int64 {
	if x != nil && x.ListingId != nil {
		return *x.ListingId
	}
	return 0
}

func (x *Chat) GetStorefrontProductId() int64 {
	if x != nil && x.StorefrontProductId != nil {
		return *x.StorefrontProductId
	}
	return 0
}

func (x *Chat) GetStatus() ChatStatus {
	if x != nil {
		return x.Status
	}
	return ChatStatus_CHAT_STATUS_UNSPECIFIED
}

func (x *Chat) GetIsArchived() bool {
	if x != nil {
		return x.IsArchived
	}
	return false
}

func (x *Chat) GetLastMessageAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastMessageAt
	}
	return nil
}

func (x *Chat) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Chat) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Chat) GetLastMessage() *Message {
	if x != nil {
		return x.LastMessage
	}
	return nil
}

func (x *Chat) GetUnreadCount() int32 {
	if x != nil {
		return x.UnreadCount
	}
	return 0
}

func (x *Chat) GetBuyerName() string {
	if x != nil && x.BuyerName != nil {
		return *x.BuyerName
	}
	return ""
}

func (x *Chat) GetSellerName() string {
	if x != nil && x.SellerName != nil {
		return *x.SellerName
	}
	return ""
}

func (x *Chat) GetListingTitle() string {
	if x != nil && x.ListingTitle != nil {
		return *x.ListingTitle
	}
	return ""
}

func (x *Chat) GetListingImageUrl() string {
	if x != nil && x.ListingImageUrl != nil {
		return *x.ListingImageUrl
	}
	return ""
}

func (x *Chat) GetListingOwnerId() int64 {
	if x != nil && x.ListingOwnerId != nil {
		return *x.ListingOwnerId
	}
	return 0
}

// Message represents a single message in a chat
type Message struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identification
	Id         int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ChatId     int64 `protobuf:"varint,2,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	SenderId   int64 `protobuf:"varint,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`       // Who sent the message
	ReceiverId int64 `protobuf:"varint,4,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"` // Who receives the message
	// Content
	Content          string `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`                                           // Message text (required, max 10000 chars)
	OriginalLanguage string `protobuf:"bytes,6,opt,name=original_language,json=originalLanguage,proto3" json:"original_language,omitempty"` // ISO 639-1 code (en, ru, sr)
	// Context (optional - inherited from chat if not provided)
	ListingId           *int64 `protobuf:"varint,7,opt,name=listing_id,json=listingId,proto3,oneof" json:"listing_id,omitempty"`
	StorefrontProductId *int64 `protobuf:"varint,8,opt,name=storefront_product_id,json=storefrontProductId,proto3,oneof" json:"storefront_product_id,omitempty"`
	// Status
	Status MessageStatus `protobuf:"varint,9,opt,name=status,proto3,enum=chatsvc.v1.MessageStatus" json:"status,omitempty"` // Sent, delivered, read
	IsRead bool          `protobuf:"varint,10,opt,name=is_read,json=isRead,proto3" json:"is_read,omitempty"`                // Read by receiver
	// Attachments
	HasAttachments   bool                 `protobuf:"varint,11,opt,name=has_attachments,json=hasAttachments,proto3" json:"has_attachments,omitempty"`       // Quick check for attachments
	AttachmentsCount int32                `protobuf:"varint,12,opt,name=attachments_count,json=attachmentsCount,proto3" json:"attachments_count,omitempty"` // Number of attachments
	Attachments      []*MessageAttachment `protobuf:"bytes,13,rep,name=attachments,proto3" json:"attachments,omitempty"`                                    // Loaded on demand
	// Timestamps
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ReadAt    *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=read_at,json=readAt,proto3,oneof" json:"read_at,omitempty"` // When read by receiver
	// Denormalized for UI
	SenderName *string `protobuf:"bytes,17,opt,name=sender_name,json=senderName,proto3,oneof" json:"sender_name,omitempty"`
	// System message flag (for marketplace notifications like orders, alerts)
	// System messages are sent by SystemUserID=1 (Svetu Marketplace)
	IsSystem      bool `protobuf:"varint,18,opt,name=is_system,json=isSystem,proto3" json:"is_system,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_api_proto_chat_v1_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_chat_v1_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_api_proto_chat_v1_chat_proto_rawDescGZIP(), []int{1}
}

func (x *Message) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Message) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *Message) GetSenderId() int64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *Message) GetReceiverId() int64 {
	if x != nil {
		return x.ReceiverId
	}
	return 0
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Message) GetOriginalLanguage() string {
	if x != nil {
		return x.OriginalLanguage
	}
	return ""
}

func (x *Message) GetListingId() int64 {
	if x != nil && x.ListingId != nil {
		return *x.ListingId
	}
	return 0
}

func (x *Message) GetStorefrontProductId() int64 {
	if x != nil && x.StorefrontProductId != nil {
		return *x.StorefrontProductId
	}
	return 0
}

func (x *Message) GetStatus() MessageStatus {
	if x != nil {
		return x.Status
	}
	return MessageStatus_MESSAGE_STATUS_UNSPECIFIED
}

func (x *Message) GetIsRead() bool {
	if x != nil {
		return x.IsRead
	}
	return false
}

func (x *Message) GetHasAttachments() bool {
	if x != nil {
		return x.HasAttachments
	}
	return false
}

func (x *Message) GetAttachmentsCount() int32 {
	if x != nil {
		return x.AttachmentsCount
	}
	return 0
}

func (x *Message) GetAttachments() []*MessageAttachment {
	if x != nil {
		return x.Attachments
	}
	return nil
}

func (x *Message) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Message) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Message) GetReadAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ReadAt
	}
	return nil
}

func (x *Message) GetSenderName() string {
	if x != nil && x.SenderName != nil {
		return *x.SenderName
	}
	return ""
}

func (x *Message) GetIsSystem() bool {
	if x != nil {
		return x.IsSystem
	}
	return false
}

// MessageAttachment represents a file attachment
type MessageAttachment struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Id        int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	MessageId int64                  `protobuf:"varint,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	// File metadata
	FileType    AttachmentType `protobuf:"varint,3,opt,name=file_type,json=fileType,proto3,enum=chatsvc.v1.AttachmentType" json:"file_type,omitempty"` // image, video, document
	FileName    string         `protobuf:"bytes,4,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`                                 // Original filename
	FileSize    int64          `protobuf:"varint,5,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`                                // Size in bytes
	ContentType string         `protobuf:"bytes,6,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`                        // MIME type
	// Storage
	StorageType   string  `protobuf:"bytes,7,opt,name=storage_type,json=storageType,proto3" json:"storage_type,omitempty"`           // "minio" (for now)
	StorageBucket string  `protobuf:"bytes,8,opt,name=storage_bucket,json=storageBucket,proto3" json:"storage_bucket,omitempty"`     // MinIO bucket name
	FilePath      string  `protobuf:"bytes,9,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`                    // Path in storage
	PublicUrl     string  `protobuf:"bytes,10,opt,name=public_url,json=publicUrl,proto3" json:"public_url,omitempty"`                // Public URL for download
	ThumbnailUrl  *string `protobuf:"bytes,11,opt,name=thumbnail_url,json=thumbnailUrl,proto3,oneof" json:"thumbnail_url,omitempty"` // Thumbnail for images/videos
	// Metadata
	Metadata      string                 `protobuf:"bytes,12,opt,name=metadata,proto3" json:"metadata,omitempty"` // JSON metadata (dimensions, duration, etc.)
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageAttachment) Reset() {
	*x = MessageAttachment{}
	mi := &file_api_proto_chat_v1_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageAttachment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageAttachment) ProtoMessage() {}

func (x *MessageAttachment) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_chat_v1_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageAttachment.ProtoReflect.Descriptor instead.
func (*MessageAttachment) Descriptor() ([]byte, []int) {
	return file_api_proto_chat_v1_chat_proto_rawDescGZIP(), []int{2}
}

func (x *MessageAttachment) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MessageAttachment) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *MessageAttachment) GetFileType() AttachmentType {
	if x != nil {
		return x.FileType
	}
	return AttachmentType_ATTACHMENT_TYPE_UNSPECIFIED
}

func (x *MessageAttachment) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *MessageAttachment) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *MessageAttachment) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *MessageAttachment) GetStorageType() string {
	if x != nil {
		return x.StorageType
	}
	return ""
}

func (x *MessageAttachment) GetStorageBucket() string {
	if x != nil {
		return x.StorageBucket
	}
	return ""
}

func (x *MessageAttachment) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *MessageAttachment) GetPublicUrl() string {
	if x != nil {
		return x.PublicUrl
	}
	return ""
}

func (x *MessageAttachment) GetThumbnailUrl() string {
	if x != nil && x.ThumbnailUrl != nil {
		return *x.ThumbnailUrl
	}
	return ""
}

func (x *MessageAttachment) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

func (x *MessageAttachment) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// GetOrCreateChatRequest retrieves or creates a chat
// AUTHORIZATION: user_id extracted from JWT metadata (NOT in request)
// VALIDATION:
// - Either listing_id OR storefront_product_id must be provided (not both)
// - Current user must be buyer OR seller (cannot chat with yourself)
// - If listing exists, ensure seller_id matches listing owner
type GetOrCreateChatRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ListingId           *int64                 `protobuf:"varint,1,opt,name=listing_id,json=listingId,proto3,oneof" json:"listing_id,omitempty"`                                 // Marketplace listing
	StorefrontProductId *int64                 `protobuf:"varint,2,opt,name=storefront_product_id,json=storefrontProductId,proto3,oneof" json:"storefront_product_id,omitempty"` // B2C product
	OtherUserId         *int64                 `protobuf:"varint,3,opt,name=other_user_id,json=otherUserId,proto3,oneof" json:"other_user_id,omitempty"`                         // If chatting without specific item (direct message)
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetOrCreateChatRequest) Reset() {
	*x = GetOrCreateChatRequest{}
	mi := &file_api_proto_chat_v1_chat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrCreateChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrCreateChatRequest) ProtoMessage() {}

func (x *GetOrCreateChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_chat_v1_chat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrCreateChatRequest.ProtoReflect.Descriptor instead.
func (*GetOrCreateChatRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_chat_v1_chat_proto_rawDescGZIP(), []int{3}
}

func (x *GetOrCreateChatRequest) GetListingId() int64 {
	if x != nil && x.ListingId != nil {
		return *x.ListingId
	}
	return 0
}

func (x *GetOrCreateChatRequest) GetStorefrontProductId() int64 {
	if x != nil && x.StorefrontProductId != nil {
		return *x.StorefrontProductId
	}
	return 0
}

func (x *GetOrCreateChatRequest) GetOtherUserId() int64 {
	if x != nil && x.OtherUserId != nil {
		return *x.OtherUserId
	}
	return 0
}

type GetOrCreateChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chat          *Chat                  `protobuf:"bytes,1,opt,name=chat,proto3" json:"chat,omitempty"`        // Existing or newly created chat
	Created       bool                   `protobuf:"varint,2,opt,name=created,proto3" json:"created,omitempty"` // True if chat was just created
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrCreateChatResponse) Reset() {
	*x = GetOrCreateChatResponse{}
	mi := &file_api_proto_chat_v1_chat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrCreateChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrCreateChatResponse) ProtoMessage() {}

func (x *GetOrCreateChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_chat_v1_chat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrCreateChatResponse.ProtoReflect.Descriptor instead.
func (*GetOrCreateChatResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_chat_v1_chat_proto_rawDescGZIP(), []int{4}
}

func (x *GetOrCreateChatResponse) GetChat() *Chat {
	if x != nil {
		return x.Chat
	}
	return nil
}

func (x *GetOrCreateChatResponse) GetCreated() bool {
	if x != nil {
		return x.Created
	}
	return false
}

// ListUserChatsRequest retrieves all chats for a user
// AUTHORIZATION: user_id extracted from JWT metadata (NOT in request)
// ADMIN OVERRIDE: Admins can specify user_id to query chats for another user
type ListUserChatsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Filters
	Status       *ChatStatus `protobuf:"varint,1,opt,name=status,proto3,enum=chatsvc.v1.ChatStatus,oneof" json:"status,omitempty"` // Filter by status
	ArchivedOnly bool        `protobuf:"varint,2,opt,name=archived_only,json=archivedOnly,proto3" json:"archived_only,omitempty"`  // Show archived chats
	ListingId    *int64      `protobuf:"varint,3,opt,name=listing_id,json=listingId,proto3,oneof" json:"listing_id,omitempty"`     // Filter by listing
	// Pagination
	Limit  int32 `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`   // Max items per page (default: 20, max: 100)
	Offset int32 `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"` // Offset for pagination
	// Sorting
	SortBy    string `protobuf:"bytes,6,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`          // "last_message_at" (default), "created_at"
	SortOrder string `protobuf:"bytes,7,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"` // "desc" (default), "asc"
	// Admin override: allows admins to query chats for a specific user
	// If set and caller is admin, use this user_id instead of JWT user_id
	// Used for dashboard notifications when admin views storefront owner's data
	UserId        *int64 `protobuf:"varint,8,opt,name=user_id,json=userId,proto3,oneof" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserChatsRequest) Reset() {
	*x = ListUserChatsRequest{}
	mi := &file_api_proto_chat_v1_chat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserChatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserChatsRequest) ProtoMessage() {}

func (x *ListUserChatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_chat_v1_chat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserChatsRequest.ProtoReflect.Descriptor instead.
func (*ListUserChatsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_chat_v1_chat_proto_rawDescGZIP(), []int{5}
}

func (x *ListUserChatsRequest) GetStatus() ChatStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ChatStatus_CHAT_STATUS_UNSPECIFIED
}

func (x *ListUserChatsRequest) GetArchivedOnly() bool {
	if x != nil {
		return x.ArchivedOnly
	}
	return false
}

func (x *ListUserChatsRequest) GetListingId() int64 {
	if x != nil && x.ListingId != nil {
		return *x.ListingId
	}
	return 0
}

func (x *ListUserChatsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListUserChatsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListUserChatsRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *ListUserChatsRequest) GetSortOrder() string {
	if x != nil {
		return x.SortOrder
	}
	return ""
}

func (x *ListUserChatsRequest) GetUserId() int64 {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return 0
}

type ListUserChatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chats         []*Chat                `protobuf:"bytes,1,rep,name=chats,proto3" json:"chats,omitempty"`                                 // List of chats
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`    // Total chats matching filters
	UnreadTotal   int32                  `protobuf:"varint,3,opt,name=unread_total,json=unreadTotal,proto3" json:"unread_total,omitempty"` // Total unread messages across all chats
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserChatsResponse) Reset() {
	*x = ListUserChatsResponse{}
	mi := &file_api_proto_chat_v1_chat_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserChatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserChatsResponse) ProtoMessage() {}

func (x *ListUserChatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_chat_v1_chat_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserChatsResponse.ProtoReflect.Descriptor instead.
func (*ListUserChatsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_chat_v1_chat_proto_rawDescGZIP(), []int{6}
}

func (x *ListUserChatsResponse) GetChats() []*Chat {
	if x != nil {
		return x.Chats
	}
	return nil
}

func (x *ListUserChatsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListUserChatsResponse) GetUnreadTotal() int32 {
	if x != nil {
		return x.UnreadTotal
	}
	return 0
}

// GetChatByIDRequest retrieves a single chat
// AUTHORIZATION: User must be buyer OR seller in the chat (validated via JWT)
type GetChatByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        int64                  `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatByIDRequest) Reset() {
	*x = GetChatByIDRequest{}
	mi := &file_api_proto_chat_v1_chat_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatByIDRequest) ProtoMessage() {}

func (x *GetChatByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_chat_v1_chat_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatByIDRequest.ProtoReflect.Descriptor instead.
func (*GetChatByIDRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_chat_v1_chat_proto_rawDescGZIP(), []int{7}
}

func (x *GetChatByIDRequest) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

type GetChatByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chat          *Chat                  `protobuf:"bytes,1,opt,name=chat,proto3" json:"chat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatByIDResponse) Reset() {
	*x = GetChatByIDResponse{}
	mi := &file_api_proto_chat_v1_chat_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatByIDResponse) ProtoMessage() {}

func (x *GetChatByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_chat_v1_chat_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatByIDResponse.ProtoReflect.Descriptor instead.
func (*GetChatByIDResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_chat_v1_chat_proto_rawDescGZIP(), []int{8}
}

func (x *GetChatByIDResponse) GetChat() *Chat {
	if x != nil {
		return x.Chat
	}
	return nil
}

// ArchiveChatRequest archives/unarchives a chat
// AUTHORIZATION: User must be buyer OR seller in the chat (validated via JWT)
type ArchiveChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        int64                  `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Archived      bool                   `protobuf:"varint,2,opt,name=archived,proto3" json:"archived,omitempty"` // true = archive, false = unarchive
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArchiveChatRequest) Reset() {
	*x = ArchiveChatRequest{}
	mi := &file_api_proto_chat_v1_chat_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArchiveChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchiveChatRequest) ProtoMessage() {}

func (x *ArchiveChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_chat_v1_chat_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchiveChatRequest.ProtoReflect.Descriptor instead.
func (*ArchiveChatRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_chat_v1_chat_proto_rawDescGZIP(), []int{9}
}

func (x *ArchiveChatRequest) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *ArchiveChatRequest) GetArchived() bool {
	if x != nil {
		return x.Archived
	}
	return false
}

// DeleteChatRequest deletes a chat (admin only)
// AUTHORIZATION: Admin role required (validated via JWT)
type DeleteChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        int64                  `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteChatRequest) Reset() {
	*x = DeleteChatRequest{}
	mi := &file_api_proto_chat_v1_chat_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChatRequest) ProtoMessage() {}

func (x *DeleteChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_chat_v1_chat_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChatRequest.ProtoReflect.Descriptor instead.
func (*DeleteChatRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_chat_v1_chat_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteChatRequest) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

// SendMessageRequest sends a new message in a chat
// AUTHORIZATION: User must be buyer OR seller in the chat (validated via JWT)
// VALIDATION:
// - content: required, 1-10000 chars
// - chat must exist and be active
// - sender must be participant
type SendMessageRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ChatId           int64                  `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`                              // Required
	Content          string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`                                           // Message text (required, 1-10000 chars)
	OriginalLanguage string                 `protobuf:"bytes,3,opt,name=original_language,json=originalLanguage,proto3" json:"original_language,omitempty"` // ISO 639-1 code (default: "en")
	AttachmentIds    []int64                `protobuf:"varint,4,rep,packed,name=attachment_ids,json=attachmentIds,proto3" json:"attachment_ids,omitempty"`  // Pre-uploaded attachments (optional)
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_api_proto_chat_v1_chat_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_chat_v1_chat_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_chat_v1_chat_proto_rawDescGZIP(), []int{11}
}

func (x *SendMessageRequest) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *SendMessageRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SendMessageRequest) GetOriginalLanguage() string {
	if x != nil {
		return x.OriginalLanguage
	}
	return ""
}

func (x *SendMessageRequest) GetAttachmentIds() []int64 {
	if x != nil {
		return x.AttachmentIds
	}
	return nil
}

type SendMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *Message               `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"` // Created message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	mi := &file_api_proto_chat_v1_chat_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_chat_v1_chat_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_chat_v1_chat_proto_rawDescGZIP(), []int{12}
}

func (x *SendMessageResponse) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

// GetMessagesRequest retrieves messages in a chat
// AUTHORIZATION: User must be buyer OR seller in the chat (validated via JWT)
// PAGINATION: Cursor-based (message_id) for real-time consistency
type GetMessagesRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	ChatId int64                  `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	// Cursor-based pagination (recommended for chat)
	BeforeMessageId *int64 `protobuf:"varint,2,opt,name=before_message_id,json=beforeMessageId,proto3,oneof" json:"before_message_id,omitempty"` // Get messages before this ID (older)
	AfterMessageId  *int64 `protobuf:"varint,3,opt,name=after_message_id,json=afterMessageId,proto3,oneof" json:"after_message_id,omitempty"`    // Get messages after this ID (newer)
	// Limit
	Limit         int32 `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"` // Max items (default: 50, max: 100)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessagesRequest) Reset() {
	*x = GetMessagesRequest{}
	mi := &file_api_proto_chat_v1_chat_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesRequest) ProtoMessage() {}

func (x *GetMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_chat_v1_chat_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesRequest.ProtoReflect.Descriptor instead.
func (*GetMessagesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_chat_v1_chat_proto_rawDescGZIP(), []int{13}
}

func (x *GetMessagesRequest) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *GetMessagesRequest) GetBeforeMessageId() int64 {
	if x != nil && x.BeforeMessageId != nil {
		return *x.BeforeMessageId
	}
	return 0
}

func (x *GetMessagesRequest) GetAfterMessageId() int64 {
	if x != nil && x.AfterMessageId != nil {
		return *x.AfterMessageId
	}
	return 0
}

func (x *GetMessagesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`                              // Messages in chronological order
	HasMore       bool                   `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`                // True if more messages available
	NextCursor    *int64                 `protobuf:"varint,3,opt,name=next_cursor,json=nextCursor,proto3,oneof" json:"next_cursor,omitempty"` // Next cursor for pagination
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessagesResponse) Reset() {
	*x = GetMessagesResponse{}
	mi := &file_api_proto_chat_v1_chat_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesResponse) ProtoMessage() {}

func (x *GetMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_chat_v1_chat_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesResponse.ProtoReflect.Descriptor instead.
func (*GetMessagesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_chat_v1_chat_proto_rawDescGZIP(), []int{14}
}

func (x *GetMessagesResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *GetMessagesResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *GetMessagesResponse) GetNextCursor() int64 {
	if x != nil && x.NextCursor != nil {
		return *x.NextCursor
	}
	return 0
}

// StreamMessagesRequest streams new messages in real-time
// AUTHORIZATION: User must be buyer OR seller in the chat (validated via JWT)
// STREAMING: Server-side streaming RPC
type StreamMessagesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ChatId         int64                  `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	SinceMessageId *int64                 `protobuf:"varint,2,opt,name=since_message_id,json=sinceMessageId,proto3,oneof" json:"since_message_id,omitempty"` // Stream messages after this ID
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StreamMessagesRequest) Reset() {
	*x = StreamMessagesRequest{}
	mi := &file_api_proto_chat_v1_chat_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamMessagesRequest) ProtoMessage() {}

func (x *StreamMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_chat_v1_chat_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamMessagesRequest.ProtoReflect.Descriptor instead.
func (*StreamMessagesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_chat_v1_chat_proto_rawDescGZIP(), []int{15}
}

func (x *StreamMessagesRequest) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *StreamMessagesRequest) GetSinceMessageId() int64 {
	if x != nil && x.SinceMessageId != nil {
		return *x.SinceMessageId
	}
	return 0
}

type StreamMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *Message               `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"` // New message received
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamMessagesResponse) Reset() {
	*x = StreamMessagesResponse{}
	mi := &file_api_proto_chat_v1_chat_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamMessagesResponse) ProtoMessage() {}

func (x *StreamMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_chat_v1_chat_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamMessagesResponse.ProtoReflect.Descriptor instead.
func (*StreamMessagesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_chat_v1_chat_proto_rawDescGZIP(), []int{16}
}

func (x *StreamMessagesResponse) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

// MarkMessagesAsReadRequest marks messages as read
// AUTHORIZATION: User must be receiver of the messages (validated via JWT)
// SIDE EFFECTS: Updates chat.last_message_at, decrements unread count
type MarkMessagesAsReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        int64                  `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	MessageIds    []int64                `protobuf:"varint,2,rep,packed,name=message_ids,json=messageIds,proto3" json:"message_ids,omitempty"` // Specific messages to mark (optional)
	MarkAll       bool                   `protobuf:"varint,3,opt,name=mark_all,json=markAll,proto3" json:"mark_all,omitempty"`                 // If true, mark all unread messages in chat
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkMessagesAsReadRequest) Reset() {
	*x = MarkMessagesAsReadRequest{}
	mi := &file_api_proto_chat_v1_chat_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkMessagesAsReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkMessagesAsReadRequest) ProtoMessage() {}

func (x *MarkMessagesAsReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_chat_v1_chat_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkMessagesAsReadRequest.ProtoReflect.Descriptor instead.
func (*MarkMessagesAsReadRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_chat_v1_chat_proto_rawDescGZIP(), []int{17}
}

func (x *MarkMessagesAsReadRequest) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *MarkMessagesAsReadRequest) GetMessageIds() []int64 {
	if x != nil {
		return x.MessageIds
	}
	return nil
}

func (x *MarkMessagesAsReadRequest) GetMarkAll() bool {
	if x != nil {
		return x.MarkAll
	}
	return false
}

type MarkMessagesAsReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MarkedCount   int32                  `protobuf:"varint,1,opt,name=marked_count,json=markedCount,proto3" json:"marked_count,omitempty"` // Number of messages marked as read
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkMessagesAsReadResponse) Reset() {
	*x = MarkMessagesAsReadResponse{}
	mi := &file_api_proto_chat_v1_chat_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkMessagesAsReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkMessagesAsReadResponse) ProtoMessage() {}

func (x *MarkMessagesAsReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_chat_v1_chat_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkMessagesAsReadResponse.ProtoReflect.Descriptor instead.
func (*MarkMessagesAsReadResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_chat_v1_chat_proto_rawDescGZIP(), []int{18}
}

func (x *MarkMessagesAsReadResponse) GetMarkedCount() int32 {
	if x != nil {
		return x.MarkedCount
	}
	return 0
}

// GetUnreadCountRequest retrieves unread message count
// AUTHORIZATION: user_id extracted from JWT metadata
type GetUnreadCountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        *int64                 `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3,oneof" json:"chat_id,omitempty"` // If provided, count for specific chat
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUnreadCountRequest) Reset() {
	*x = GetUnreadCountRequest{}
	mi := &file_api_proto_chat_v1_chat_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUnreadCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnreadCountRequest) ProtoMessage() {}

func (x *GetUnreadCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_chat_v1_chat_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnreadCountRequest.ProtoReflect.Descriptor instead.
func (*GetUnreadCountRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_chat_v1_chat_proto_rawDescGZIP(), []int{19}
}

func (x *GetUnreadCountRequest) GetChatId() int64 {
	if x != nil && x.ChatId != nil {
		return *x.ChatId
	}
	return 0
}

type GetUnreadCountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UnreadCount   int32                  `protobuf:"varint,1,opt,name=unread_count,json=unreadCount,proto3" json:"unread_count,omitempty"` // Total unread messages
	ByChat        []*ChatUnreadCount     `protobuf:"bytes,2,rep,name=by_chat,json=byChat,proto3" json:"by_chat,omitempty"`                 // Breakdown by chat
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUnreadCountResponse) Reset() {
	*x = GetUnreadCountResponse{}
	mi := &file_api_proto_chat_v1_chat_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUnreadCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnreadCountResponse) ProtoMessage() {}

func (x *GetUnreadCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_chat_v1_chat_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnreadCountResponse.ProtoReflect.Descriptor instead.
func (*GetUnreadCountResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_chat_v1_chat_proto_rawDescGZIP(), []int{20}
}

func (x *GetUnreadCountResponse) GetUnreadCount() int32 {
	if x != nil {
		return x.UnreadCount
	}
	return 0
}

func (x *GetUnreadCountResponse) GetByChat() []*ChatUnreadCount {
	if x != nil {
		return x.ByChat
	}
	return nil
}

// ChatUnreadCount represents unread count for a specific chat
type ChatUnreadCount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        int64                  `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	UnreadCount   int32                  `protobuf:"varint,2,opt,name=unread_count,json=unreadCount,proto3" json:"unread_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatUnreadCount) Reset() {
	*x = ChatUnreadCount{}
	mi := &file_api_proto_chat_v1_chat_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatUnreadCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatUnreadCount) ProtoMessage() {}

func (x *ChatUnreadCount) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_chat_v1_chat_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatUnreadCount.ProtoReflect.Descriptor instead.
func (*ChatUnreadCount) Descriptor() ([]byte, []int) {
	return file_api_proto_chat_v1_chat_proto_rawDescGZIP(), []int{21}
}

func (x *ChatUnreadCount) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *ChatUnreadCount) GetUnreadCount() int32 {
	if x != nil {
		return x.UnreadCount
	}
	return 0
}

// DeleteMessageRequest deletes a message (soft delete)
// AUTHORIZATION: User must be sender OR admin (validated via JWT)
type DeleteMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     int64                  `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMessageRequest) Reset() {
	*x = DeleteMessageRequest{}
	mi := &file_api_proto_chat_v1_chat_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMessageRequest) ProtoMessage() {}

func (x *DeleteMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_chat_v1_chat_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMessageRequest.ProtoReflect.Descriptor instead.
func (*DeleteMessageRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_chat_v1_chat_proto_rawDescGZIP(), []int{22}
}

func (x *DeleteMessageRequest) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

// UploadAttachmentRequest uploads a file attachment
// AUTHORIZATION: user_id extracted from JWT metadata
// VALIDATION:
// - File size: max 10MB for images, 50MB for videos, 20MB for documents
// - Supported types: jpg, png, gif, mp4, webm, pdf, doc, docx, txt
// NOTE: This is a unary RPC, file content passed as bytes
type UploadAttachmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`                                 // Original filename
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`                        // MIME type
	FileData      []byte                 `protobuf:"bytes,3,opt,name=file_data,json=fileData,proto3" json:"file_data,omitempty"`                                 // File content (max 50MB)
	FileType      AttachmentType         `protobuf:"varint,4,opt,name=file_type,json=fileType,proto3,enum=chatsvc.v1.AttachmentType" json:"file_type,omitempty"` // image, video, document
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadAttachmentRequest) Reset() {
	*x = UploadAttachmentRequest{}
	mi := &file_api_proto_chat_v1_chat_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadAttachmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadAttachmentRequest) ProtoMessage() {}

func (x *UploadAttachmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_chat_v1_chat_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadAttachmentRequest.ProtoReflect.Descriptor instead.
func (*UploadAttachmentRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_chat_v1_chat_proto_rawDescGZIP(), []int{23}
}

func (x *UploadAttachmentRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *UploadAttachmentRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *UploadAttachmentRequest) GetFileData() []byte {
	if x != nil {
		return x.FileData
	}
	return nil
}

func (x *UploadAttachmentRequest) GetFileType() AttachmentType {
	if x != nil {
		return x.FileType
	}
	return AttachmentType_ATTACHMENT_TYPE_UNSPECIFIED
}

type UploadAttachmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attachment    *MessageAttachment     `protobuf:"bytes,1,opt,name=attachment,proto3" json:"attachment,omitempty"`             // Created attachment (not yet linked to message)
	UploadId      string                 `protobuf:"bytes,2,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"` // Temporary ID for linking to message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadAttachmentResponse) Reset() {
	*x = UploadAttachmentResponse{}
	mi := &file_api_proto_chat_v1_chat_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadAttachmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadAttachmentResponse) ProtoMessage() {}

func (x *UploadAttachmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_chat_v1_chat_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadAttachmentResponse.ProtoReflect.Descriptor instead.
func (*UploadAttachmentResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_chat_v1_chat_proto_rawDescGZIP(), []int{24}
}

func (x *UploadAttachmentResponse) GetAttachment() *MessageAttachment {
	if x != nil {
		return x.Attachment
	}
	return nil
}

func (x *UploadAttachmentResponse) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

// GetAttachmentRequest retrieves attachment metadata
// AUTHORIZATION: User must have access to the parent message (validated via JWT)
type GetAttachmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AttachmentId  int64                  `protobuf:"varint,1,opt,name=attachment_id,json=attachmentId,proto3" json:"attachment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAttachmentRequest) Reset() {
	*x = GetAttachmentRequest{}
	mi := &file_api_proto_chat_v1_chat_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAttachmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAttachmentRequest) ProtoMessage() {}

func (x *GetAttachmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_chat_v1_chat_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAttachmentRequest.ProtoReflect.Descriptor instead.
func (*GetAttachmentRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_chat_v1_chat_proto_rawDescGZIP(), []int{25}
}

func (x *GetAttachmentRequest) GetAttachmentId() int64 {
	if x != nil {
		return x.AttachmentId
	}
	return 0
}

type GetAttachmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attachment    *MessageAttachment     `protobuf:"bytes,1,opt,name=attachment,proto3" json:"attachment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAttachmentResponse) Reset() {
	*x = GetAttachmentResponse{}
	mi := &file_api_proto_chat_v1_chat_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAttachmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAttachmentResponse) ProtoMessage() {}

func (x *GetAttachmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_chat_v1_chat_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAttachmentResponse.ProtoReflect.Descriptor instead.
func (*GetAttachmentResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_chat_v1_chat_proto_rawDescGZIP(), []int{26}
}

func (x *GetAttachmentResponse) GetAttachment() *MessageAttachment {
	if x != nil {
		return x.Attachment
	}
	return nil
}

// DeleteAttachmentRequest deletes an attachment
// AUTHORIZATION: User must be sender of the parent message OR admin (validated via JWT)
type DeleteAttachmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AttachmentId  int64                  `protobuf:"varint,1,opt,name=attachment_id,json=attachmentId,proto3" json:"attachment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAttachmentRequest) Reset() {
	*x = DeleteAttachmentRequest{}
	mi := &file_api_proto_chat_v1_chat_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAttachmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAttachmentRequest) ProtoMessage() {}

func (x *DeleteAttachmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_chat_v1_chat_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAttachmentRequest.ProtoReflect.Descriptor instead.
func (*DeleteAttachmentRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_chat_v1_chat_proto_rawDescGZIP(), []int{27}
}

func (x *DeleteAttachmentRequest) GetAttachmentId() int64 {
	if x != nil {
		return x.AttachmentId
	}
	return 0
}

// GetChatStatsRequest retrieves chat statistics
// AUTHORIZATION: Admin only (validated via JWT)
type GetChatStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DateFrom      *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=date_from,json=dateFrom,proto3,oneof" json:"date_from,omitempty"`
	DateTo        *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=date_to,json=dateTo,proto3,oneof" json:"date_to,omitempty"`
	UserId        *int64                 `protobuf:"varint,3,opt,name=user_id,json=userId,proto3,oneof" json:"user_id,omitempty"` // Stats for specific user
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatStatsRequest) Reset() {
	*x = GetChatStatsRequest{}
	mi := &file_api_proto_chat_v1_chat_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatStatsRequest) ProtoMessage() {}

func (x *GetChatStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_chat_v1_chat_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatStatsRequest.ProtoReflect.Descriptor instead.
func (*GetChatStatsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_chat_v1_chat_proto_rawDescGZIP(), []int{28}
}

func (x *GetChatStatsRequest) GetDateFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.DateFrom
	}
	return nil
}

func (x *GetChatStatsRequest) GetDateTo() *timestamppb.Timestamp {
	if x != nil {
		return x.DateTo
	}
	return nil
}

func (x *GetChatStatsRequest) GetUserId() int64 {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return 0
}

type GetChatStatsResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TotalChats         int64                  `protobuf:"varint,1,opt,name=total_chats,json=totalChats,proto3" json:"total_chats,omitempty"`
	ActiveChats        int64                  `protobuf:"varint,2,opt,name=active_chats,json=activeChats,proto3" json:"active_chats,omitempty"`
	TotalMessages      int64                  `protobuf:"varint,3,opt,name=total_messages,json=totalMessages,proto3" json:"total_messages,omitempty"`
	MessagesToday      int64                  `protobuf:"varint,4,opt,name=messages_today,json=messagesToday,proto3" json:"messages_today,omitempty"`
	AvgMessagesPerChat float64                `protobuf:"fixed64,5,opt,name=avg_messages_per_chat,json=avgMessagesPerChat,proto3" json:"avg_messages_per_chat,omitempty"`
	DailyStats         []*DailyChatStats      `protobuf:"bytes,6,rep,name=daily_stats,json=dailyStats,proto3" json:"daily_stats,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetChatStatsResponse) Reset() {
	*x = GetChatStatsResponse{}
	mi := &file_api_proto_chat_v1_chat_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatStatsResponse) ProtoMessage() {}

func (x *GetChatStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_chat_v1_chat_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatStatsResponse.ProtoReflect.Descriptor instead.
func (*GetChatStatsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_chat_v1_chat_proto_rawDescGZIP(), []int{29}
}

func (x *GetChatStatsResponse) GetTotalChats() int64 {
	if x != nil {
		return x.TotalChats
	}
	return 0
}

func (x *GetChatStatsResponse) GetActiveChats() int64 {
	if x != nil {
		return x.ActiveChats
	}
	return 0
}

func (x *GetChatStatsResponse) GetTotalMessages() int64 {
	if x != nil {
		return x.TotalMessages
	}
	return 0
}

func (x *GetChatStatsResponse) GetMessagesToday() int64 {
	if x != nil {
		return x.MessagesToday
	}
	return 0
}

func (x *GetChatStatsResponse) GetAvgMessagesPerChat() float64 {
	if x != nil {
		return x.AvgMessagesPerChat
	}
	return 0
}

func (x *GetChatStatsResponse) GetDailyStats() []*DailyChatStats {
	if x != nil {
		return x.DailyStats
	}
	return nil
}

type DailyChatStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"` // YYYY-MM-DD
	ChatsCreated  int32                  `protobuf:"varint,2,opt,name=chats_created,json=chatsCreated,proto3" json:"chats_created,omitempty"`
	MessagesSent  int32                  `protobuf:"varint,3,opt,name=messages_sent,json=messagesSent,proto3" json:"messages_sent,omitempty"`
	ActiveUsers   int32                  `protobuf:"varint,4,opt,name=active_users,json=activeUsers,proto3" json:"active_users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DailyChatStats) Reset() {
	*x = DailyChatStats{}
	mi := &file_api_proto_chat_v1_chat_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DailyChatStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyChatStats) ProtoMessage() {}

func (x *DailyChatStats) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_chat_v1_chat_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailyChatStats.ProtoReflect.Descriptor instead.
func (*DailyChatStats) Descriptor() ([]byte, []int) {
	return file_api_proto_chat_v1_chat_proto_rawDescGZIP(), []int{30}
}

func (x *DailyChatStats) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *DailyChatStats) GetChatsCreated() int32 {
	if x != nil {
		return x.ChatsCreated
	}
	return 0
}

func (x *DailyChatStats) GetMessagesSent() int32 {
	if x != nil {
		return x.MessagesSent
	}
	return 0
}

func (x *DailyChatStats) GetActiveUsers() int32 {
	if x != nil {
		return x.ActiveUsers
	}
	return 0
}

var File_api_proto_chat_v1_chat_proto protoreflect.FileDescriptor

const file_api_proto_chat_v1_chat_proto_rawDesc = "" +
	"\n" +
	"\x1capi/proto/chat/v1/chat.proto\x12\n" +
	"chatsvc.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xea\x06\n" +
	"\x04Chat\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\bbuyer_id\x18\x02 \x01(\x03R\abuyerId\x12\x1b\n" +
	"\tseller_id\x18\x03 \x01(\x03R\bsellerId\x12\"\n" +
	"\n" +
	"listing_id\x18\x04 \x01(\x03H\x00R\tlistingId\x88\x01\x01\x127\n" +
	"\x15storefront_product_id\x18\x05 \x01(\x03H\x01R\x13storefrontProductId\x88\x01\x01\x12.\n" +
	"\x06status\x18\x06 \x01(\x0e2\x16.chatsvc.v1.ChatStatusR\x06status\x12\x1f\n" +
	"\vis_archived\x18\a \x01(\bR\n" +
	"isArchived\x12B\n" +
	"\x0flast_message_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\rlastMessageAt\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x126\n" +
	"\flast_message\x18\v \x01(\v2\x13.chatsvc.v1.MessageR\vlastMessage\x12!\n" +
	"\funread_count\x18\f \x01(\x05R\vunreadCount\x12\"\n" +
	"\n" +
	"buyer_name\x18\r \x01(\tH\x02R\tbuyerName\x88\x01\x01\x12$\n" +
	"\vseller_name\x18\x0e \x01(\tH\x03R\n" +
	"sellerName\x88\x01\x01\x12(\n" +
	"\rlisting_title\x18\x0f \x01(\tH\x04R\flistingTitle\x88\x01\x01\x12/\n" +
	"\x11listing_image_url\x18\x10 \x01(\tH\x05R\x0flistingImageUrl\x88\x01\x01\x12-\n" +
	"\x10listing_owner_id\x18\x11 \x01(\x03H\x06R\x0elistingOwnerId\x88\x01\x01B\r\n" +
	"\v_listing_idB\x18\n" +
	"\x16_storefront_product_idB\r\n" +
	"\v_buyer_nameB\x0e\n" +
	"\f_seller_nameB\x10\n" +
	"\x0e_listing_titleB\x14\n" +
	"\x12_listing_image_urlB\x13\n" +
	"\x11_listing_owner_id\"\xaf\x06\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\achat_id\x18\x02 \x01(\x03R\x06chatId\x12\x1b\n" +
	"\tsender_id\x18\x03 \x01(\x03R\bsenderId\x12\x1f\n" +
	"\vreceiver_id\x18\x04 \x01(\x03R\n" +
	"receiverId\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12+\n" +
	"\x11original_language\x18\x06 \x01(\tR\x10originalLanguage\x12\"\n" +
	"\n" +
	"listing_id\x18\a \x01(\x03H\x00R\tlistingId\x88\x01\x01\x127\n" +
	"\x15storefront_product_id\x18\b \x01(\x03H\x01R\x13storefrontProductId\x88\x01\x01\x121\n" +
	"\x06status\x18\t \x01(\x0e2\x19.chatsvc.v1.MessageStatusR\x06status\x12\x17\n" +
	"\ais_read\x18\n" +
	" \x01(\bR\x06isRead\x12'\n" +
	"\x0fhas_attachments\x18\v \x01(\bR\x0ehasAttachments\x12+\n" +
	"\x11attachments_count\x18\f \x01(\x05R\x10attachmentsCount\x12?\n" +
	"\vattachments\x18\r \x03(\v2\x1d.chatsvc.v1.MessageAttachmentR\vattachments\x129\n" +
	"\n" +
	"created_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x128\n" +
	"\aread_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampH\x02R\x06readAt\x88\x01\x01\x12$\n" +
	"\vsender_name\x18\x11 \x01(\tH\x03R\n" +
	"senderName\x88\x01\x01\x12\x1b\n" +
	"\tis_system\x18\x12 \x01(\bR\bisSystemB\r\n" +
	"\v_listing_idB\x18\n" +
	"\x16_storefront_product_idB\n" +
	"\n" +
	"\b_read_atB\x0e\n" +
	"\f_sender_name\"\xf1\x03\n" +
	"\x11MessageAttachment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\x03R\tmessageId\x127\n" +
	"\tfile_type\x18\x03 \x01(\x0e2\x1a.chatsvc.v1.AttachmentTypeR\bfileType\x12\x1b\n" +
	"\tfile_name\x18\x04 \x01(\tR\bfileName\x12\x1b\n" +
	"\tfile_size\x18\x05 \x01(\x03R\bfileSize\x12!\n" +
	"\fcontent_type\x18\x06 \x01(\tR\vcontentType\x12!\n" +
	"\fstorage_type\x18\a \x01(\tR\vstorageType\x12%\n" +
	"\x0estorage_bucket\x18\b \x01(\tR\rstorageBucket\x12\x1b\n" +
	"\tfile_path\x18\t \x01(\tR\bfilePath\x12\x1d\n" +
	"\n" +
	"public_url\x18\n" +
	" \x01(\tR\tpublicUrl\x12(\n" +
	"\rthumbnail_url\x18\v \x01(\tH\x00R\fthumbnailUrl\x88\x01\x01\x12\x1a\n" +
	"\bmetadata\x18\f \x01(\tR\bmetadata\x129\n" +
	"\n" +
	"created_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtB\x10\n" +
	"\x0e_thumbnail_url\"\xd9\x01\n" +
	"\x16GetOrCreateChatRequest\x12\"\n" +
	"\n" +
	"listing_id\x18\x01 \x01(\x03H\x00R\tlistingId\x88\x01\x01\x127\n" +
	"\x15storefront_product_id\x18\x02 \x01(\x03H\x01R\x13storefrontProductId\x88\x01\x01\x12'\n" +
	"\rother_user_id\x18\x03 \x01(\x03H\x02R\votherUserId\x88\x01\x01B\r\n" +
	"\v_listing_idB\x18\n" +
	"\x16_storefront_product_idB\x10\n" +
	"\x0e_other_user_id\"Y\n" +
	"\x17GetOrCreateChatResponse\x12$\n" +
	"\x04chat\x18\x01 \x01(\v2\x10.chatsvc.v1.ChatR\x04chat\x12\x18\n" +
	"\acreated\x18\x02 \x01(\bR\acreated\"\xbe\x02\n" +
	"\x14ListUserChatsRequest\x123\n" +
	"\x06status\x18\x01 \x01(\x0e2\x16.chatsvc.v1.ChatStatusH\x00R\x06status\x88\x01\x01\x12#\n" +
	"\rarchived_only\x18\x02 \x01(\bR\farchivedOnly\x12\"\n" +
	"\n" +
	"listing_id\x18\x03 \x01(\x03H\x01R\tlistingId\x88\x01\x01\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x05 \x01(\x05R\x06offset\x12\x17\n" +
	"\asort_by\x18\x06 \x01(\tR\x06sortBy\x12\x1d\n" +
	"\n" +
	"sort_order\x18\a \x01(\tR\tsortOrder\x12\x1c\n" +
	"\auser_id\x18\b \x01(\x03H\x02R\x06userId\x88\x01\x01B\t\n" +
	"\a_statusB\r\n" +
	"\v_listing_idB\n" +
	"\n" +
	"\b_user_id\"\x83\x01\n" +
	"\x15ListUserChatsResponse\x12&\n" +
	"\x05chats\x18\x01 \x03(\v2\x10.chatsvc.v1.ChatR\x05chats\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12!\n" +
	"\funread_total\x18\x03 \x01(\x05R\vunreadTotal\"-\n" +
	"\x12GetChatByIDRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\x03R\x06chatId\";\n" +
	"\x13GetChatByIDResponse\x12$\n" +
	"\x04chat\x18\x01 \x01(\v2\x10.chatsvc.v1.ChatR\x04chat\"I\n" +
	"\x12ArchiveChatRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\x03R\x06chatId\x12\x1a\n" +
	"\barchived\x18\x02 \x01(\bR\barchived\",\n" +
	"\x11DeleteChatRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\x03R\x06chatId\"\x9b\x01\n" +
	"\x12SendMessageRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\x03R\x06chatId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12+\n" +
	"\x11original_language\x18\x03 \x01(\tR\x10originalLanguage\x12%\n" +
	"\x0eattachment_ids\x18\x04 \x03(\x03R\rattachmentIds\"D\n" +
	"\x13SendMessageResponse\x12-\n" +
	"\amessage\x18\x01 \x01(\v2\x13.chatsvc.v1.MessageR\amessage\"\xce\x01\n" +
	"\x12GetMessagesRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\x03R\x06chatId\x12/\n" +
	"\x11before_message_id\x18\x02 \x01(\x03H\x00R\x0fbeforeMessageId\x88\x01\x01\x12-\n" +
	"\x10after_message_id\x18\x03 \x01(\x03H\x01R\x0eafterMessageId\x88\x01\x01\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limitB\x14\n" +
	"\x12_before_message_idB\x13\n" +
	"\x11_after_message_id\"\x97\x01\n" +
	"\x13GetMessagesResponse\x12/\n" +
	"\bmessages\x18\x01 \x03(\v2\x13.chatsvc.v1.MessageR\bmessages\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\x12$\n" +
	"\vnext_cursor\x18\x03 \x01(\x03H\x00R\n" +
	"nextCursor\x88\x01\x01B\x0e\n" +
	"\f_next_cursor\"t\n" +
	"\x15StreamMessagesRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\x03R\x06chatId\x12-\n" +
	"\x10since_message_id\x18\x02 \x01(\x03H\x00R\x0esinceMessageId\x88\x01\x01B\x13\n" +
	"\x11_since_message_id\"G\n" +
	"\x16StreamMessagesResponse\x12-\n" +
	"\amessage\x18\x01 \x01(\v2\x13.chatsvc.v1.MessageR\amessage\"p\n" +
	"\x19MarkMessagesAsReadRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\x03R\x06chatId\x12\x1f\n" +
	"\vmessage_ids\x18\x02 \x03(\x03R\n" +
	"messageIds\x12\x19\n" +
	"\bmark_all\x18\x03 \x01(\bR\amarkAll\"?\n" +
	"\x1aMarkMessagesAsReadResponse\x12!\n" +
	"\fmarked_count\x18\x01 \x01(\x05R\vmarkedCount\"A\n" +
	"\x15GetUnreadCountRequest\x12\x1c\n" +
	"\achat_id\x18\x01 \x01(\x03H\x00R\x06chatId\x88\x01\x01B\n" +
	"\n" +
	"\b_chat_id\"q\n" +
	"\x16GetUnreadCountResponse\x12!\n" +
	"\funread_count\x18\x01 \x01(\x05R\vunreadCount\x124\n" +
	"\aby_chat\x18\x02 \x03(\v2\x1b.chatsvc.v1.ChatUnreadCountR\x06byChat\"M\n" +
	"\x0fChatUnreadCount\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\x03R\x06chatId\x12!\n" +
	"\funread_count\x18\x02 \x01(\x05R\vunreadCount\"5\n" +
	"\x14DeleteMessageRequest\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\x03R\tmessageId\"\xaf\x01\n" +
	"\x17UploadAttachmentRequest\x12\x1b\n" +
	"\tfile_name\x18\x01 \x01(\tR\bfileName\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\x12\x1b\n" +
	"\tfile_data\x18\x03 \x01(\fR\bfileData\x127\n" +
	"\tfile_type\x18\x04 \x01(\x0e2\x1a.chatsvc.v1.AttachmentTypeR\bfileType\"v\n" +
	"\x18UploadAttachmentResponse\x12=\n" +
	"\n" +
	"attachment\x18\x01 \x01(\v2\x1d.chatsvc.v1.MessageAttachmentR\n" +
	"attachment\x12\x1b\n" +
	"\tupload_id\x18\x02 \x01(\tR\buploadId\";\n" +
	"\x14GetAttachmentRequest\x12#\n" +
	"\rattachment_id\x18\x01 \x01(\x03R\fattachmentId\"V\n" +
	"\x15GetAttachmentResponse\x12=\n" +
	"\n" +
	"attachment\x18\x01 \x01(\v2\x1d.chatsvc.v1.MessageAttachmentR\n" +
	"attachment\">\n" +
	"\x17DeleteAttachmentRequest\x12#\n" +
	"\rattachment_id\x18\x01 \x01(\x03R\fattachmentId\"\xd1\x01\n" +
	"\x13GetChatStatsRequest\x12<\n" +
	"\tdate_from\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\bdateFrom\x88\x01\x01\x128\n" +
	"\adate_to\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\x06dateTo\x88\x01\x01\x12\x1c\n" +
	"\auser_id\x18\x03 \x01(\x03H\x02R\x06userId\x88\x01\x01B\f\n" +
	"\n" +
	"_date_fromB\n" +
	"\n" +
	"\b_date_toB\n" +
	"\n" +
	"\b_user_id\"\x98\x02\n" +
	"\x14GetChatStatsResponse\x12\x1f\n" +
	"\vtotal_chats\x18\x01 \x01(\x03R\n" +
	"totalChats\x12!\n" +
	"\factive_chats\x18\x02 \x01(\x03R\vactiveChats\x12%\n" +
	"\x0etotal_messages\x18\x03 \x01(\x03R\rtotalMessages\x12%\n" +
	"\x0emessages_today\x18\x04 \x01(\x03R\rmessagesToday\x121\n" +
	"\x15avg_messages_per_chat\x18\x05 \x01(\x01R\x12avgMessagesPerChat\x12;\n" +
	"\vdaily_stats\x18\x06 \x03(\v2\x1a.chatsvc.v1.DailyChatStatsR\n" +
	"dailyStats\"\x91\x01\n" +
	"\x0eDailyChatStats\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12#\n" +
	"\rchats_created\x18\x02 \x01(\x05R\fchatsCreated\x12#\n" +
	"\rmessages_sent\x18\x03 \x01(\x05R\fmessagesSent\x12!\n" +
	"\factive_users\x18\x04 \x01(\x05R\vactiveUsers*t\n" +
	"\n" +
	"ChatStatus\x12\x1b\n" +
	"\x17CHAT_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12CHAT_STATUS_ACTIVE\x10\x01\x12\x18\n" +
	"\x14CHAT_STATUS_ARCHIVED\x10\x02\x12\x17\n" +
	"\x13CHAT_STATUS_BLOCKED\x10\x03*\x9a\x01\n" +
	"\rMessageStatus\x12\x1e\n" +
	"\x1aMESSAGE_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13MESSAGE_STATUS_SENT\x10\x01\x12\x1c\n" +
	"\x18MESSAGE_STATUS_DELIVERED\x10\x02\x12\x17\n" +
	"\x13MESSAGE_STATUS_READ\x10\x03\x12\x19\n" +
	"\x15MESSAGE_STATUS_FAILED\x10\x04*\x85\x01\n" +
	"\x0eAttachmentType\x12\x1f\n" +
	"\x1bATTACHMENT_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15ATTACHMENT_TYPE_IMAGE\x10\x01\x12\x19\n" +
	"\x15ATTACHMENT_TYPE_VIDEO\x10\x02\x12\x1c\n" +
	"\x18ATTACHMENT_TYPE_DOCUMENT\x10\x032\xf8\t\n" +
	"\vChatService\x12Z\n" +
	"\x0fGetOrCreateChat\x12\".chatsvc.v1.GetOrCreateChatRequest\x1a#.chatsvc.v1.GetOrCreateChatResponse\x12T\n" +
	"\rListUserChats\x12 .chatsvc.v1.ListUserChatsRequest\x1a!.chatsvc.v1.ListUserChatsResponse\x12N\n" +
	"\vGetChatByID\x12\x1e.chatsvc.v1.GetChatByIDRequest\x1a\x1f.chatsvc.v1.GetChatByIDResponse\x12E\n" +
	"\vArchiveChat\x12\x1e.chatsvc.v1.ArchiveChatRequest\x1a\x16.google.protobuf.Empty\x12C\n" +
	"\n" +
	"DeleteChat\x12\x1d.chatsvc.v1.DeleteChatRequest\x1a\x16.google.protobuf.Empty\x12Q\n" +
	"\fGetChatStats\x12\x1f.chatsvc.v1.GetChatStatsRequest\x1a .chatsvc.v1.GetChatStatsResponse\x12N\n" +
	"\vSendMessage\x12\x1e.chatsvc.v1.SendMessageRequest\x1a\x1f.chatsvc.v1.SendMessageResponse\x12N\n" +
	"\vGetMessages\x12\x1e.chatsvc.v1.GetMessagesRequest\x1a\x1f.chatsvc.v1.GetMessagesResponse\x12Y\n" +
	"\x0eStreamMessages\x12!.chatsvc.v1.StreamMessagesRequest\x1a\".chatsvc.v1.StreamMessagesResponse0\x01\x12c\n" +
	"\x12MarkMessagesAsRead\x12%.chatsvc.v1.MarkMessagesAsReadRequest\x1a&.chatsvc.v1.MarkMessagesAsReadResponse\x12W\n" +
	"\x0eGetUnreadCount\x12!.chatsvc.v1.GetUnreadCountRequest\x1a\".chatsvc.v1.GetUnreadCountResponse\x12I\n" +
	"\rDeleteMessage\x12 .chatsvc.v1.DeleteMessageRequest\x1a\x16.google.protobuf.Empty\x12]\n" +
	"\x10UploadAttachment\x12#.chatsvc.v1.UploadAttachmentRequest\x1a$.chatsvc.v1.UploadAttachmentResponse\x12T\n" +
	"\rGetAttachment\x12 .chatsvc.v1.GetAttachmentRequest\x1a!.chatsvc.v1.GetAttachmentResponse\x12O\n" +
	"\x10DeleteAttachment\x12#.chatsvc.v1.DeleteAttachmentRequest\x1a\x16.google.protobuf.EmptyB9Z7github.com/sveturs/listings/api/proto/chat/v1;chatsvcv1b\x06proto3"

var (
	file_api_proto_chat_v1_chat_proto_rawDescOnce sync.Once
	file_api_proto_chat_v1_chat_proto_rawDescData []byte
)

func file_api_proto_chat_v1_chat_proto_rawDescGZIP() []byte {
	file_api_proto_chat_v1_chat_proto_rawDescOnce.Do(func() {
		file_api_proto_chat_v1_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_chat_v1_chat_proto_rawDesc), len(file_api_proto_chat_v1_chat_proto_rawDesc)))
	})
	return file_api_proto_chat_v1_chat_proto_rawDescData
}

var file_api_proto_chat_v1_chat_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_api_proto_chat_v1_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_api_proto_chat_v1_chat_proto_goTypes = []any{
	(ChatStatus)(0),                    // 0: chatsvc.v1.ChatStatus
	(MessageStatus)(0),                 // 1: chatsvc.v1.MessageStatus
	(AttachmentType)(0),                // 2: chatsvc.v1.AttachmentType
	(*Chat)(nil),                       // 3: chatsvc.v1.Chat
	(*Message)(nil),                    // 4: chatsvc.v1.Message
	(*MessageAttachment)(nil),          // 5: chatsvc.v1.MessageAttachment
	(*GetOrCreateChatRequest)(nil),     // 6: chatsvc.v1.GetOrCreateChatRequest
	(*GetOrCreateChatResponse)(nil),    // 7: chatsvc.v1.GetOrCreateChatResponse
	(*ListUserChatsRequest)(nil),       // 8: chatsvc.v1.ListUserChatsRequest
	(*ListUserChatsResponse)(nil),      // 9: chatsvc.v1.ListUserChatsResponse
	(*GetChatByIDRequest)(nil),         // 10: chatsvc.v1.GetChatByIDRequest
	(*GetChatByIDResponse)(nil),        // 11: chatsvc.v1.GetChatByIDResponse
	(*ArchiveChatRequest)(nil),         // 12: chatsvc.v1.ArchiveChatRequest
	(*DeleteChatRequest)(nil),          // 13: chatsvc.v1.DeleteChatRequest
	(*SendMessageRequest)(nil),         // 14: chatsvc.v1.SendMessageRequest
	(*SendMessageResponse)(nil),        // 15: chatsvc.v1.SendMessageResponse
	(*GetMessagesRequest)(nil),         // 16: chatsvc.v1.GetMessagesRequest
	(*GetMessagesResponse)(nil),        // 17: chatsvc.v1.GetMessagesResponse
	(*StreamMessagesRequest)(nil),      // 18: chatsvc.v1.StreamMessagesRequest
	(*StreamMessagesResponse)(nil),     // 19: chatsvc.v1.StreamMessagesResponse
	(*MarkMessagesAsReadRequest)(nil),  // 20: chatsvc.v1.MarkMessagesAsReadRequest
	(*MarkMessagesAsReadResponse)(nil), // 21: chatsvc.v1.MarkMessagesAsReadResponse
	(*GetUnreadCountRequest)(nil),      // 22: chatsvc.v1.GetUnreadCountRequest
	(*GetUnreadCountResponse)(nil),     // 23: chatsvc.v1.GetUnreadCountResponse
	(*ChatUnreadCount)(nil),            // 24: chatsvc.v1.ChatUnreadCount
	(*DeleteMessageRequest)(nil),       // 25: chatsvc.v1.DeleteMessageRequest
	(*UploadAttachmentRequest)(nil),    // 26: chatsvc.v1.UploadAttachmentRequest
	(*UploadAttachmentResponse)(nil),   // 27: chatsvc.v1.UploadAttachmentResponse
	(*GetAttachmentRequest)(nil),       // 28: chatsvc.v1.GetAttachmentRequest
	(*GetAttachmentResponse)(nil),      // 29: chatsvc.v1.GetAttachmentResponse
	(*DeleteAttachmentRequest)(nil),    // 30: chatsvc.v1.DeleteAttachmentRequest
	(*GetChatStatsRequest)(nil),        // 31: chatsvc.v1.GetChatStatsRequest
	(*GetChatStatsResponse)(nil),       // 32: chatsvc.v1.GetChatStatsResponse
	(*DailyChatStats)(nil),             // 33: chatsvc.v1.DailyChatStats
	(*timestamppb.Timestamp)(nil),      // 34: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),              // 35: google.protobuf.Empty
}
var file_api_proto_chat_v1_chat_proto_depIdxs = []int32{
	0,  // 0: chatsvc.v1.Chat.status:type_name -> chatsvc.v1.ChatStatus
	34, // 1: chatsvc.v1.Chat.last_message_at:type_name -> google.protobuf.Timestamp
	34, // 2: chatsvc.v1.Chat.created_at:type_name -> google.protobuf.Timestamp
	34, // 3: chatsvc.v1.Chat.updated_at:type_name -> google.protobuf.Timestamp
	4,  // 4: chatsvc.v1.Chat.last_message:type_name -> chatsvc.v1.Message
	1,  // 5: chatsvc.v1.Message.status:type_name -> chatsvc.v1.MessageStatus
	5,  // 6: chatsvc.v1.Message.attachments:type_name -> chatsvc.v1.MessageAttachment
	34, // 7: chatsvc.v1.Message.created_at:type_name -> google.protobuf.Timestamp
	34, // 8: chatsvc.v1.Message.updated_at:type_name -> google.protobuf.Timestamp
	34, // 9: chatsvc.v1.Message.read_at:type_name -> google.protobuf.Timestamp
	2,  // 10: chatsvc.v1.MessageAttachment.file_type:type_name -> chatsvc.v1.AttachmentType
	34, // 11: chatsvc.v1.MessageAttachment.created_at:type_name -> google.protobuf.Timestamp
	3,  // 12: chatsvc.v1.GetOrCreateChatResponse.chat:type_name -> chatsvc.v1.Chat
	0,  // 13: chatsvc.v1.ListUserChatsRequest.status:type_name -> chatsvc.v1.ChatStatus
	3,  // 14: chatsvc.v1.ListUserChatsResponse.chats:type_name -> chatsvc.v1.Chat
	3,  // 15: chatsvc.v1.GetChatByIDResponse.chat:type_name -> chatsvc.v1.Chat
	4,  // 16: chatsvc.v1.SendMessageResponse.message:type_name -> chatsvc.v1.Message
	4,  // 17: chatsvc.v1.GetMessagesResponse.messages:type_name -> chatsvc.v1.Message
	4,  // 18: chatsvc.v1.StreamMessagesResponse.message:type_name -> chatsvc.v1.Message
	24, // 19: chatsvc.v1.GetUnreadCountResponse.by_chat:type_name -> chatsvc.v1.ChatUnreadCount
	2,  // 20: chatsvc.v1.UploadAttachmentRequest.file_type:type_name -> chatsvc.v1.AttachmentType
	5,  // 21: chatsvc.v1.UploadAttachmentResponse.attachment:type_name -> chatsvc.v1.MessageAttachment
	5,  // 22: chatsvc.v1.GetAttachmentResponse.attachment:type_name -> chatsvc.v1.MessageAttachment
	34, // 23: chatsvc.v1.GetChatStatsRequest.date_from:type_name -> google.protobuf.Timestamp
	34, // 24: chatsvc.v1.GetChatStatsRequest.date_to:type_name -> google.protobuf.Timestamp
	33, // 25: chatsvc.v1.GetChatStatsResponse.daily_stats:type_name -> chatsvc.v1.DailyChatStats
	6,  // 26: chatsvc.v1.ChatService.GetOrCreateChat:input_type -> chatsvc.v1.GetOrCreateChatRequest
	8,  // 27: chatsvc.v1.ChatService.ListUserChats:input_type -> chatsvc.v1.ListUserChatsRequest
	10, // 28: chatsvc.v1.ChatService.GetChatByID:input_type -> chatsvc.v1.GetChatByIDRequest
	12, // 29: chatsvc.v1.ChatService.ArchiveChat:input_type -> chatsvc.v1.ArchiveChatRequest
	13, // 30: chatsvc.v1.ChatService.DeleteChat:input_type -> chatsvc.v1.DeleteChatRequest
	31, // 31: chatsvc.v1.ChatService.GetChatStats:input_type -> chatsvc.v1.GetChatStatsRequest
	14, // 32: chatsvc.v1.ChatService.SendMessage:input_type -> chatsvc.v1.SendMessageRequest
	16, // 33: chatsvc.v1.ChatService.GetMessages:input_type -> chatsvc.v1.GetMessagesRequest
	18, // 34: chatsvc.v1.ChatService.StreamMessages:input_type -> chatsvc.v1.StreamMessagesRequest
	20, // 35: chatsvc.v1.ChatService.MarkMessagesAsRead:input_type -> chatsvc.v1.MarkMessagesAsReadRequest
	22, // 36: chatsvc.v1.ChatService.GetUnreadCount:input_type -> chatsvc.v1.GetUnreadCountRequest
	25, // 37: chatsvc.v1.ChatService.DeleteMessage:input_type -> chatsvc.v1.DeleteMessageRequest
	26, // 38: chatsvc.v1.ChatService.UploadAttachment:input_type -> chatsvc.v1.UploadAttachmentRequest
	28, // 39: chatsvc.v1.ChatService.GetAttachment:input_type -> chatsvc.v1.GetAttachmentRequest
	30, // 40: chatsvc.v1.ChatService.DeleteAttachment:input_type -> chatsvc.v1.DeleteAttachmentRequest
	7,  // 41: chatsvc.v1.ChatService.GetOrCreateChat:output_type -> chatsvc.v1.GetOrCreateChatResponse
	9,  // 42: chatsvc.v1.ChatService.ListUserChats:output_type -> chatsvc.v1.ListUserChatsResponse
	11, // 43: chatsvc.v1.ChatService.GetChatByID:output_type -> chatsvc.v1.GetChatByIDResponse
	35, // 44: chatsvc.v1.ChatService.ArchiveChat:output_type -> google.protobuf.Empty
	35, // 45: chatsvc.v1.ChatService.DeleteChat:output_type -> google.protobuf.Empty
	32, // 46: chatsvc.v1.ChatService.GetChatStats:output_type -> chatsvc.v1.GetChatStatsResponse
	15, // 47: chatsvc.v1.ChatService.SendMessage:output_type -> chatsvc.v1.SendMessageResponse
	17, // 48: chatsvc.v1.ChatService.GetMessages:output_type -> chatsvc.v1.GetMessagesResponse
	19, // 49: chatsvc.v1.ChatService.StreamMessages:output_type -> chatsvc.v1.StreamMessagesResponse
	21, // 50: chatsvc.v1.ChatService.MarkMessagesAsRead:output_type -> chatsvc.v1.MarkMessagesAsReadResponse
	23, // 51: chatsvc.v1.ChatService.GetUnreadCount:output_type -> chatsvc.v1.GetUnreadCountResponse
	35, // 52: chatsvc.v1.ChatService.DeleteMessage:output_type -> google.protobuf.Empty
	27, // 53: chatsvc.v1.ChatService.UploadAttachment:output_type -> chatsvc.v1.UploadAttachmentResponse
	29, // 54: chatsvc.v1.ChatService.GetAttachment:output_type -> chatsvc.v1.GetAttachmentResponse
	35, // 55: chatsvc.v1.ChatService.DeleteAttachment:output_type -> google.protobuf.Empty
	41, // [41:56] is the sub-list for method output_type
	26, // [26:41] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_api_proto_chat_v1_chat_proto_init() }
func file_api_proto_chat_v1_chat_proto_init() {
	if File_api_proto_chat_v1_chat_proto != nil {
		return
	}
	file_api_proto_chat_v1_chat_proto_msgTypes[0].OneofWrappers = []any{}
	file_api_proto_chat_v1_chat_proto_msgTypes[1].OneofWrappers = []any{}
	file_api_proto_chat_v1_chat_proto_msgTypes[2].OneofWrappers = []any{}
	file_api_proto_chat_v1_chat_proto_msgTypes[3].OneofWrappers = []any{}
	file_api_proto_chat_v1_chat_proto_msgTypes[5].OneofWrappers = []any{}
	file_api_proto_chat_v1_chat_proto_msgTypes[13].OneofWrappers = []any{}
	file_api_proto_chat_v1_chat_proto_msgTypes[14].OneofWrappers = []any{}
	file_api_proto_chat_v1_chat_proto_msgTypes[15].OneofWrappers = []any{}
	file_api_proto_chat_v1_chat_proto_msgTypes[19].OneofWrappers = []any{}
	file_api_proto_chat_v1_chat_proto_msgTypes[28].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_chat_v1_chat_proto_rawDesc), len(file_api_proto_chat_v1_chat_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_chat_v1_chat_proto_goTypes,
		DependencyIndexes: file_api_proto_chat_v1_chat_proto_depIdxs,
		EnumInfos:         file_api_proto_chat_v1_chat_proto_enumTypes,
		MessageInfos:      file_api_proto_chat_v1_chat_proto_msgTypes,
	}.Build()
	File_api_proto_chat_v1_chat_proto = out.File
	file_api_proto_chat_v1_chat_proto_goTypes = nil
	file_api_proto_chat_v1_chat_proto_depIdxs = nil
}
