// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: delivery/v1/delivery.proto

package deliveryv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Shipment status enumeration
type ShipmentStatus int32

const (
	ShipmentStatus_SHIPMENT_STATUS_UNSPECIFIED      ShipmentStatus = 0
	ShipmentStatus_SHIPMENT_STATUS_PENDING          ShipmentStatus = 1
	ShipmentStatus_SHIPMENT_STATUS_CONFIRMED        ShipmentStatus = 2
	ShipmentStatus_SHIPMENT_STATUS_IN_TRANSIT       ShipmentStatus = 3
	ShipmentStatus_SHIPMENT_STATUS_OUT_FOR_DELIVERY ShipmentStatus = 4
	ShipmentStatus_SHIPMENT_STATUS_DELIVERED        ShipmentStatus = 5
	ShipmentStatus_SHIPMENT_STATUS_FAILED           ShipmentStatus = 6
	ShipmentStatus_SHIPMENT_STATUS_CANCELLED        ShipmentStatus = 7
	ShipmentStatus_SHIPMENT_STATUS_RETURNED         ShipmentStatus = 8
)

// Enum value maps for ShipmentStatus.
var (
	ShipmentStatus_name = map[int32]string{
		0: "SHIPMENT_STATUS_UNSPECIFIED",
		1: "SHIPMENT_STATUS_PENDING",
		2: "SHIPMENT_STATUS_CONFIRMED",
		3: "SHIPMENT_STATUS_IN_TRANSIT",
		4: "SHIPMENT_STATUS_OUT_FOR_DELIVERY",
		5: "SHIPMENT_STATUS_DELIVERED",
		6: "SHIPMENT_STATUS_FAILED",
		7: "SHIPMENT_STATUS_CANCELLED",
		8: "SHIPMENT_STATUS_RETURNED",
	}
	ShipmentStatus_value = map[string]int32{
		"SHIPMENT_STATUS_UNSPECIFIED":      0,
		"SHIPMENT_STATUS_PENDING":          1,
		"SHIPMENT_STATUS_CONFIRMED":        2,
		"SHIPMENT_STATUS_IN_TRANSIT":       3,
		"SHIPMENT_STATUS_OUT_FOR_DELIVERY": 4,
		"SHIPMENT_STATUS_DELIVERED":        5,
		"SHIPMENT_STATUS_FAILED":           6,
		"SHIPMENT_STATUS_CANCELLED":        7,
		"SHIPMENT_STATUS_RETURNED":         8,
	}
)

func (x ShipmentStatus) Enum() *ShipmentStatus {
	p := new(ShipmentStatus)
	*p = x
	return p
}

func (x ShipmentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ShipmentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_delivery_v1_delivery_proto_enumTypes[0].Descriptor()
}

func (ShipmentStatus) Type() protoreflect.EnumType {
	return &file_delivery_v1_delivery_proto_enumTypes[0]
}

func (x ShipmentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ShipmentStatus.Descriptor instead.
func (ShipmentStatus) EnumDescriptor() ([]byte, []int) {
	return file_delivery_v1_delivery_proto_rawDescGZIP(), []int{0}
}

// Delivery provider enumeration
type DeliveryProvider int32

const (
	DeliveryProvider_DELIVERY_PROVIDER_UNSPECIFIED  DeliveryProvider = 0
	DeliveryProvider_DELIVERY_PROVIDER_POST_EXPRESS DeliveryProvider = 1 // post_express (Post Express)
	DeliveryProvider_DELIVERY_PROVIDER_BEX_EXPRESS  DeliveryProvider = 2 // bex_express (BEX Express)
	DeliveryProvider_DELIVERY_PROVIDER_AKS_EXPRESS  DeliveryProvider = 3 // aks_express (AKS Express)
	DeliveryProvider_DELIVERY_PROVIDER_D_EXPRESS    DeliveryProvider = 4 // d_express (D Express)
	DeliveryProvider_DELIVERY_PROVIDER_CITY_EXPRESS DeliveryProvider = 5 // city_express (City Express)
)

// Enum value maps for DeliveryProvider.
var (
	DeliveryProvider_name = map[int32]string{
		0: "DELIVERY_PROVIDER_UNSPECIFIED",
		1: "DELIVERY_PROVIDER_POST_EXPRESS",
		2: "DELIVERY_PROVIDER_BEX_EXPRESS",
		3: "DELIVERY_PROVIDER_AKS_EXPRESS",
		4: "DELIVERY_PROVIDER_D_EXPRESS",
		5: "DELIVERY_PROVIDER_CITY_EXPRESS",
	}
	DeliveryProvider_value = map[string]int32{
		"DELIVERY_PROVIDER_UNSPECIFIED":  0,
		"DELIVERY_PROVIDER_POST_EXPRESS": 1,
		"DELIVERY_PROVIDER_BEX_EXPRESS":  2,
		"DELIVERY_PROVIDER_AKS_EXPRESS":  3,
		"DELIVERY_PROVIDER_D_EXPRESS":    4,
		"DELIVERY_PROVIDER_CITY_EXPRESS": 5,
	}
)

func (x DeliveryProvider) Enum() *DeliveryProvider {
	p := new(DeliveryProvider)
	*p = x
	return p
}

func (x DeliveryProvider) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeliveryProvider) Descriptor() protoreflect.EnumDescriptor {
	return file_delivery_v1_delivery_proto_enumTypes[1].Descriptor()
}

func (DeliveryProvider) Type() protoreflect.EnumType {
	return &file_delivery_v1_delivery_proto_enumTypes[1]
}

func (x DeliveryProvider) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeliveryProvider.Descriptor instead.
func (DeliveryProvider) EnumDescriptor() ([]byte, []int) {
	return file_delivery_v1_delivery_proto_rawDescGZIP(), []int{1}
}

// Address message
type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Street        string                 `protobuf:"bytes,1,opt,name=street,proto3" json:"street,omitempty"`
	City          string                 `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	PostalCode    string                 `protobuf:"bytes,4,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	Country       string                 `protobuf:"bytes,5,opt,name=country,proto3" json:"country,omitempty"`
	ContactName   string                 `protobuf:"bytes,6,opt,name=contact_name,json=contactName,proto3" json:"contact_name,omitempty"`
	ContactPhone  string                 `protobuf:"bytes,7,opt,name=contact_phone,json=contactPhone,proto3" json:"contact_phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_delivery_v1_delivery_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_v1_delivery_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_delivery_v1_delivery_proto_rawDescGZIP(), []int{0}
}

func (x *Address) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *Address) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Address) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Address) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

func (x *Address) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Address) GetContactName() string {
	if x != nil {
		return x.ContactName
	}
	return ""
}

func (x *Address) GetContactPhone() string {
	if x != nil {
		return x.ContactPhone
	}
	return ""
}

// Package information
type Package struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Weight        string                 `protobuf:"bytes,1,opt,name=weight,proto3" json:"weight,omitempty"` // Weight in kg
	Length        string                 `protobuf:"bytes,2,opt,name=length,proto3" json:"length,omitempty"` // Length in cm
	Width         string                 `protobuf:"bytes,3,opt,name=width,proto3" json:"width,omitempty"`   // Width in cm
	Height        string                 `protobuf:"bytes,4,opt,name=height,proto3" json:"height,omitempty"` // Height in cm
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	DeclaredValue string                 `protobuf:"bytes,6,opt,name=declared_value,json=declaredValue,proto3" json:"declared_value,omitempty"` // Value in currency
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Package) Reset() {
	*x = Package{}
	mi := &file_delivery_v1_delivery_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Package) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Package) ProtoMessage() {}

func (x *Package) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_v1_delivery_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Package.ProtoReflect.Descriptor instead.
func (*Package) Descriptor() ([]byte, []int) {
	return file_delivery_v1_delivery_proto_rawDescGZIP(), []int{1}
}

func (x *Package) GetWeight() string {
	if x != nil {
		return x.Weight
	}
	return ""
}

func (x *Package) GetLength() string {
	if x != nil {
		return x.Length
	}
	return ""
}

func (x *Package) GetWidth() string {
	if x != nil {
		return x.Width
	}
	return ""
}

func (x *Package) GetHeight() string {
	if x != nil {
		return x.Height
	}
	return ""
}

func (x *Package) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Package) GetDeclaredValue() string {
	if x != nil {
		return x.DeclaredValue
	}
	return ""
}

// Shipment message
type Shipment struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // UUID as string
	TrackingNumber    string                 `protobuf:"bytes,2,opt,name=tracking_number,json=trackingNumber,proto3" json:"tracking_number,omitempty"`
	Provider          DeliveryProvider       `protobuf:"varint,3,opt,name=provider,proto3,enum=delivery.v1.DeliveryProvider" json:"provider,omitempty"`
	Status            ShipmentStatus         `protobuf:"varint,4,opt,name=status,proto3,enum=delivery.v1.ShipmentStatus" json:"status,omitempty"`
	FromAddress       *Address               `protobuf:"bytes,5,opt,name=from_address,json=fromAddress,proto3" json:"from_address,omitempty"`
	ToAddress         *Address               `protobuf:"bytes,6,opt,name=to_address,json=toAddress,proto3" json:"to_address,omitempty"`
	Package           *Package               `protobuf:"bytes,7,opt,name=package,proto3" json:"package,omitempty"`
	Cost              string                 `protobuf:"bytes,8,opt,name=cost,proto3" json:"cost,omitempty"` // Cost in currency
	Currency          string                 `protobuf:"bytes,9,opt,name=currency,proto3" json:"currency,omitempty"`
	CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt         *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	EstimatedDelivery *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=estimated_delivery,json=estimatedDelivery,proto3" json:"estimated_delivery,omitempty"`
	ActualDelivery    *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=actual_delivery,json=actualDelivery,proto3" json:"actual_delivery,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Shipment) Reset() {
	*x = Shipment{}
	mi := &file_delivery_v1_delivery_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Shipment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shipment) ProtoMessage() {}

func (x *Shipment) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_v1_delivery_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shipment.ProtoReflect.Descriptor instead.
func (*Shipment) Descriptor() ([]byte, []int) {
	return file_delivery_v1_delivery_proto_rawDescGZIP(), []int{2}
}

func (x *Shipment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Shipment) GetTrackingNumber() string {
	if x != nil {
		return x.TrackingNumber
	}
	return ""
}

func (x *Shipment) GetProvider() DeliveryProvider {
	if x != nil {
		return x.Provider
	}
	return DeliveryProvider_DELIVERY_PROVIDER_UNSPECIFIED
}

func (x *Shipment) GetStatus() ShipmentStatus {
	if x != nil {
		return x.Status
	}
	return ShipmentStatus_SHIPMENT_STATUS_UNSPECIFIED
}

func (x *Shipment) GetFromAddress() *Address {
	if x != nil {
		return x.FromAddress
	}
	return nil
}

func (x *Shipment) GetToAddress() *Address {
	if x != nil {
		return x.ToAddress
	}
	return nil
}

func (x *Shipment) GetPackage() *Package {
	if x != nil {
		return x.Package
	}
	return nil
}

func (x *Shipment) GetCost() string {
	if x != nil {
		return x.Cost
	}
	return ""
}

func (x *Shipment) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Shipment) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Shipment) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Shipment) GetEstimatedDelivery() *timestamppb.Timestamp {
	if x != nil {
		return x.EstimatedDelivery
	}
	return nil
}

func (x *Shipment) GetActualDelivery() *timestamppb.Timestamp {
	if x != nil {
		return x.ActualDelivery
	}
	return nil
}

// CreateShipment messages
type CreateShipmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      DeliveryProvider       `protobuf:"varint,1,opt,name=provider,proto3,enum=delivery.v1.DeliveryProvider" json:"provider,omitempty"`
	FromAddress   *Address               `protobuf:"bytes,2,opt,name=from_address,json=fromAddress,proto3" json:"from_address,omitempty"`
	ToAddress     *Address               `protobuf:"bytes,3,opt,name=to_address,json=toAddress,proto3" json:"to_address,omitempty"`
	Package       *Package               `protobuf:"bytes,4,opt,name=package,proto3" json:"package,omitempty"`
	UserId        string                 `protobuf:"bytes,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // UUID as string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShipmentRequest) Reset() {
	*x = CreateShipmentRequest{}
	mi := &file_delivery_v1_delivery_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShipmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShipmentRequest) ProtoMessage() {}

func (x *CreateShipmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_v1_delivery_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShipmentRequest.ProtoReflect.Descriptor instead.
func (*CreateShipmentRequest) Descriptor() ([]byte, []int) {
	return file_delivery_v1_delivery_proto_rawDescGZIP(), []int{3}
}

func (x *CreateShipmentRequest) GetProvider() DeliveryProvider {
	if x != nil {
		return x.Provider
	}
	return DeliveryProvider_DELIVERY_PROVIDER_UNSPECIFIED
}

func (x *CreateShipmentRequest) GetFromAddress() *Address {
	if x != nil {
		return x.FromAddress
	}
	return nil
}

func (x *CreateShipmentRequest) GetToAddress() *Address {
	if x != nil {
		return x.ToAddress
	}
	return nil
}

func (x *CreateShipmentRequest) GetPackage() *Package {
	if x != nil {
		return x.Package
	}
	return nil
}

func (x *CreateShipmentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CreateShipmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shipment      *Shipment              `protobuf:"bytes,1,opt,name=shipment,proto3" json:"shipment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShipmentResponse) Reset() {
	*x = CreateShipmentResponse{}
	mi := &file_delivery_v1_delivery_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShipmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShipmentResponse) ProtoMessage() {}

func (x *CreateShipmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_v1_delivery_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShipmentResponse.ProtoReflect.Descriptor instead.
func (*CreateShipmentResponse) Descriptor() ([]byte, []int) {
	return file_delivery_v1_delivery_proto_rawDescGZIP(), []int{4}
}

func (x *CreateShipmentResponse) GetShipment() *Shipment {
	if x != nil {
		return x.Shipment
	}
	return nil
}

// GetShipment messages
type GetShipmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // UUID as string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShipmentRequest) Reset() {
	*x = GetShipmentRequest{}
	mi := &file_delivery_v1_delivery_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShipmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShipmentRequest) ProtoMessage() {}

func (x *GetShipmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_v1_delivery_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShipmentRequest.ProtoReflect.Descriptor instead.
func (*GetShipmentRequest) Descriptor() ([]byte, []int) {
	return file_delivery_v1_delivery_proto_rawDescGZIP(), []int{5}
}

func (x *GetShipmentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetShipmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shipment      *Shipment              `protobuf:"bytes,1,opt,name=shipment,proto3" json:"shipment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShipmentResponse) Reset() {
	*x = GetShipmentResponse{}
	mi := &file_delivery_v1_delivery_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShipmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShipmentResponse) ProtoMessage() {}

func (x *GetShipmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_v1_delivery_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShipmentResponse.ProtoReflect.Descriptor instead.
func (*GetShipmentResponse) Descriptor() ([]byte, []int) {
	return file_delivery_v1_delivery_proto_rawDescGZIP(), []int{6}
}

func (x *GetShipmentResponse) GetShipment() *Shipment {
	if x != nil {
		return x.Shipment
	}
	return nil
}

// TrackShipment messages
type TrackShipmentRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TrackingNumber string                 `protobuf:"bytes,1,opt,name=tracking_number,json=trackingNumber,proto3" json:"tracking_number,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TrackShipmentRequest) Reset() {
	*x = TrackShipmentRequest{}
	mi := &file_delivery_v1_delivery_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackShipmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackShipmentRequest) ProtoMessage() {}

func (x *TrackShipmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_v1_delivery_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackShipmentRequest.ProtoReflect.Descriptor instead.
func (*TrackShipmentRequest) Descriptor() ([]byte, []int) {
	return file_delivery_v1_delivery_proto_rawDescGZIP(), []int{7}
}

func (x *TrackShipmentRequest) GetTrackingNumber() string {
	if x != nil {
		return x.TrackingNumber
	}
	return ""
}

type TrackShipmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shipment      *Shipment              `protobuf:"bytes,1,opt,name=shipment,proto3" json:"shipment,omitempty"`
	Events        []*TrackingEvent       `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackShipmentResponse) Reset() {
	*x = TrackShipmentResponse{}
	mi := &file_delivery_v1_delivery_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackShipmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackShipmentResponse) ProtoMessage() {}

func (x *TrackShipmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_v1_delivery_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackShipmentResponse.ProtoReflect.Descriptor instead.
func (*TrackShipmentResponse) Descriptor() ([]byte, []int) {
	return file_delivery_v1_delivery_proto_rawDescGZIP(), []int{8}
}

func (x *TrackShipmentResponse) GetShipment() *Shipment {
	if x != nil {
		return x.Shipment
	}
	return nil
}

func (x *TrackShipmentResponse) GetEvents() []*TrackingEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type TrackingEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        ShipmentStatus         `protobuf:"varint,1,opt,name=status,proto3,enum=delivery.v1.ShipmentStatus" json:"status,omitempty"`
	Location      string                 `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackingEvent) Reset() {
	*x = TrackingEvent{}
	mi := &file_delivery_v1_delivery_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackingEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackingEvent) ProtoMessage() {}

func (x *TrackingEvent) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_v1_delivery_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackingEvent.ProtoReflect.Descriptor instead.
func (*TrackingEvent) Descriptor() ([]byte, []int) {
	return file_delivery_v1_delivery_proto_rawDescGZIP(), []int{9}
}

func (x *TrackingEvent) GetStatus() ShipmentStatus {
	if x != nil {
		return x.Status
	}
	return ShipmentStatus_SHIPMENT_STATUS_UNSPECIFIED
}

func (x *TrackingEvent) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *TrackingEvent) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TrackingEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// CancelShipment messages
type CancelShipmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // UUID as string
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelShipmentRequest) Reset() {
	*x = CancelShipmentRequest{}
	mi := &file_delivery_v1_delivery_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelShipmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelShipmentRequest) ProtoMessage() {}

func (x *CancelShipmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_v1_delivery_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelShipmentRequest.ProtoReflect.Descriptor instead.
func (*CancelShipmentRequest) Descriptor() ([]byte, []int) {
	return file_delivery_v1_delivery_proto_rawDescGZIP(), []int{10}
}

func (x *CancelShipmentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CancelShipmentRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CancelShipmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shipment      *Shipment              `protobuf:"bytes,1,opt,name=shipment,proto3" json:"shipment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelShipmentResponse) Reset() {
	*x = CancelShipmentResponse{}
	mi := &file_delivery_v1_delivery_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelShipmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelShipmentResponse) ProtoMessage() {}

func (x *CancelShipmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_v1_delivery_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelShipmentResponse.ProtoReflect.Descriptor instead.
func (*CancelShipmentResponse) Descriptor() ([]byte, []int) {
	return file_delivery_v1_delivery_proto_rawDescGZIP(), []int{11}
}

func (x *CancelShipmentResponse) GetShipment() *Shipment {
	if x != nil {
		return x.Shipment
	}
	return nil
}

// CalculateRate messages
type CalculateRateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      DeliveryProvider       `protobuf:"varint,1,opt,name=provider,proto3,enum=delivery.v1.DeliveryProvider" json:"provider,omitempty"`
	FromAddress   *Address               `protobuf:"bytes,2,opt,name=from_address,json=fromAddress,proto3" json:"from_address,omitempty"`
	ToAddress     *Address               `protobuf:"bytes,3,opt,name=to_address,json=toAddress,proto3" json:"to_address,omitempty"`
	Package       *Package               `protobuf:"bytes,4,opt,name=package,proto3" json:"package,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateRateRequest) Reset() {
	*x = CalculateRateRequest{}
	mi := &file_delivery_v1_delivery_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateRateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateRateRequest) ProtoMessage() {}

func (x *CalculateRateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_v1_delivery_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateRateRequest.ProtoReflect.Descriptor instead.
func (*CalculateRateRequest) Descriptor() ([]byte, []int) {
	return file_delivery_v1_delivery_proto_rawDescGZIP(), []int{12}
}

func (x *CalculateRateRequest) GetProvider() DeliveryProvider {
	if x != nil {
		return x.Provider
	}
	return DeliveryProvider_DELIVERY_PROVIDER_UNSPECIFIED
}

func (x *CalculateRateRequest) GetFromAddress() *Address {
	if x != nil {
		return x.FromAddress
	}
	return nil
}

func (x *CalculateRateRequest) GetToAddress() *Address {
	if x != nil {
		return x.ToAddress
	}
	return nil
}

func (x *CalculateRateRequest) GetPackage() *Package {
	if x != nil {
		return x.Package
	}
	return nil
}

type CalculateRateResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Cost              string                 `protobuf:"bytes,1,opt,name=cost,proto3" json:"cost,omitempty"` // Cost in currency
	Currency          string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	EstimatedDelivery *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=estimated_delivery,json=estimatedDelivery,proto3" json:"estimated_delivery,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CalculateRateResponse) Reset() {
	*x = CalculateRateResponse{}
	mi := &file_delivery_v1_delivery_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateRateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateRateResponse) ProtoMessage() {}

func (x *CalculateRateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_v1_delivery_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateRateResponse.ProtoReflect.Descriptor instead.
func (*CalculateRateResponse) Descriptor() ([]byte, []int) {
	return file_delivery_v1_delivery_proto_rawDescGZIP(), []int{13}
}

func (x *CalculateRateResponse) GetCost() string {
	if x != nil {
		return x.Cost
	}
	return ""
}

func (x *CalculateRateResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CalculateRateResponse) GetEstimatedDelivery() *timestamppb.Timestamp {
	if x != nil {
		return x.EstimatedDelivery
	}
	return nil
}

var File_delivery_v1_delivery_proto protoreflect.FileDescriptor

const file_delivery_v1_delivery_proto_rawDesc = "" +
	"\n" +
	"\x1adelivery/v1/delivery.proto\x12\vdelivery.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xce\x01\n" +
	"\aAddress\x12\x16\n" +
	"\x06street\x18\x01 \x01(\tR\x06street\x12\x12\n" +
	"\x04city\x18\x02 \x01(\tR\x04city\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12\x1f\n" +
	"\vpostal_code\x18\x04 \x01(\tR\n" +
	"postalCode\x12\x18\n" +
	"\acountry\x18\x05 \x01(\tR\acountry\x12!\n" +
	"\fcontact_name\x18\x06 \x01(\tR\vcontactName\x12#\n" +
	"\rcontact_phone\x18\a \x01(\tR\fcontactPhone\"\xb0\x01\n" +
	"\aPackage\x12\x16\n" +
	"\x06weight\x18\x01 \x01(\tR\x06weight\x12\x16\n" +
	"\x06length\x18\x02 \x01(\tR\x06length\x12\x14\n" +
	"\x05width\x18\x03 \x01(\tR\x05width\x12\x16\n" +
	"\x06height\x18\x04 \x01(\tR\x06height\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12%\n" +
	"\x0edeclared_value\x18\x06 \x01(\tR\rdeclaredValue\"\x87\x05\n" +
	"\bShipment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0ftracking_number\x18\x02 \x01(\tR\x0etrackingNumber\x129\n" +
	"\bprovider\x18\x03 \x01(\x0e2\x1d.delivery.v1.DeliveryProviderR\bprovider\x123\n" +
	"\x06status\x18\x04 \x01(\x0e2\x1b.delivery.v1.ShipmentStatusR\x06status\x127\n" +
	"\ffrom_address\x18\x05 \x01(\v2\x14.delivery.v1.AddressR\vfromAddress\x123\n" +
	"\n" +
	"to_address\x18\x06 \x01(\v2\x14.delivery.v1.AddressR\ttoAddress\x12.\n" +
	"\apackage\x18\a \x01(\v2\x14.delivery.v1.PackageR\apackage\x12\x12\n" +
	"\x04cost\x18\b \x01(\tR\x04cost\x12\x1a\n" +
	"\bcurrency\x18\t \x01(\tR\bcurrency\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12I\n" +
	"\x12estimated_delivery\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\x11estimatedDelivery\x12C\n" +
	"\x0factual_delivery\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\x0eactualDelivery\"\x89\x02\n" +
	"\x15CreateShipmentRequest\x129\n" +
	"\bprovider\x18\x01 \x01(\x0e2\x1d.delivery.v1.DeliveryProviderR\bprovider\x127\n" +
	"\ffrom_address\x18\x02 \x01(\v2\x14.delivery.v1.AddressR\vfromAddress\x123\n" +
	"\n" +
	"to_address\x18\x03 \x01(\v2\x14.delivery.v1.AddressR\ttoAddress\x12.\n" +
	"\apackage\x18\x04 \x01(\v2\x14.delivery.v1.PackageR\apackage\x12\x17\n" +
	"\auser_id\x18\x05 \x01(\tR\x06userId\"K\n" +
	"\x16CreateShipmentResponse\x121\n" +
	"\bshipment\x18\x01 \x01(\v2\x15.delivery.v1.ShipmentR\bshipment\"$\n" +
	"\x12GetShipmentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"H\n" +
	"\x13GetShipmentResponse\x121\n" +
	"\bshipment\x18\x01 \x01(\v2\x15.delivery.v1.ShipmentR\bshipment\"?\n" +
	"\x14TrackShipmentRequest\x12'\n" +
	"\x0ftracking_number\x18\x01 \x01(\tR\x0etrackingNumber\"~\n" +
	"\x15TrackShipmentResponse\x121\n" +
	"\bshipment\x18\x01 \x01(\v2\x15.delivery.v1.ShipmentR\bshipment\x122\n" +
	"\x06events\x18\x02 \x03(\v2\x1a.delivery.v1.TrackingEventR\x06events\"\xbc\x01\n" +
	"\rTrackingEvent\x123\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1b.delivery.v1.ShipmentStatusR\x06status\x12\x1a\n" +
	"\blocation\x18\x02 \x01(\tR\blocation\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"?\n" +
	"\x15CancelShipmentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"K\n" +
	"\x16CancelShipmentResponse\x121\n" +
	"\bshipment\x18\x01 \x01(\v2\x15.delivery.v1.ShipmentR\bshipment\"\xef\x01\n" +
	"\x14CalculateRateRequest\x129\n" +
	"\bprovider\x18\x01 \x01(\x0e2\x1d.delivery.v1.DeliveryProviderR\bprovider\x127\n" +
	"\ffrom_address\x18\x02 \x01(\v2\x14.delivery.v1.AddressR\vfromAddress\x123\n" +
	"\n" +
	"to_address\x18\x03 \x01(\v2\x14.delivery.v1.AddressR\ttoAddress\x12.\n" +
	"\apackage\x18\x04 \x01(\v2\x14.delivery.v1.PackageR\apackage\"\x92\x01\n" +
	"\x15CalculateRateResponse\x12\x12\n" +
	"\x04cost\x18\x01 \x01(\tR\x04cost\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\x12I\n" +
	"\x12estimated_delivery\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x11estimatedDelivery*\xab\x02\n" +
	"\x0eShipmentStatus\x12\x1f\n" +
	"\x1bSHIPMENT_STATUS_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17SHIPMENT_STATUS_PENDING\x10\x01\x12\x1d\n" +
	"\x19SHIPMENT_STATUS_CONFIRMED\x10\x02\x12\x1e\n" +
	"\x1aSHIPMENT_STATUS_IN_TRANSIT\x10\x03\x12$\n" +
	" SHIPMENT_STATUS_OUT_FOR_DELIVERY\x10\x04\x12\x1d\n" +
	"\x19SHIPMENT_STATUS_DELIVERED\x10\x05\x12\x1a\n" +
	"\x16SHIPMENT_STATUS_FAILED\x10\x06\x12\x1d\n" +
	"\x19SHIPMENT_STATUS_CANCELLED\x10\a\x12\x1c\n" +
	"\x18SHIPMENT_STATUS_RETURNED\x10\b*\xe4\x01\n" +
	"\x10DeliveryProvider\x12!\n" +
	"\x1dDELIVERY_PROVIDER_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eDELIVERY_PROVIDER_POST_EXPRESS\x10\x01\x12!\n" +
	"\x1dDELIVERY_PROVIDER_BEX_EXPRESS\x10\x02\x12!\n" +
	"\x1dDELIVERY_PROVIDER_AKS_EXPRESS\x10\x03\x12\x1f\n" +
	"\x1bDELIVERY_PROVIDER_D_EXPRESS\x10\x04\x12\"\n" +
	"\x1eDELIVERY_PROVIDER_CITY_EXPRESS\x10\x052\xc9\x03\n" +
	"\x0fDeliveryService\x12Y\n" +
	"\x0eCreateShipment\x12\".delivery.v1.CreateShipmentRequest\x1a#.delivery.v1.CreateShipmentResponse\x12P\n" +
	"\vGetShipment\x12\x1f.delivery.v1.GetShipmentRequest\x1a .delivery.v1.GetShipmentResponse\x12V\n" +
	"\rTrackShipment\x12!.delivery.v1.TrackShipmentRequest\x1a\".delivery.v1.TrackShipmentResponse\x12Y\n" +
	"\x0eCancelShipment\x12\".delivery.v1.CancelShipmentRequest\x1a#.delivery.v1.CancelShipmentResponse\x12V\n" +
	"\rCalculateRate\x12!.delivery.v1.CalculateRateRequest\x1a\".delivery.v1.CalculateRateResponseB;Z9github.com/sveturs/delivery/gen/go/delivery/v1;deliveryv1b\x06proto3"

var (
	file_delivery_v1_delivery_proto_rawDescOnce sync.Once
	file_delivery_v1_delivery_proto_rawDescData []byte
)

func file_delivery_v1_delivery_proto_rawDescGZIP() []byte {
	file_delivery_v1_delivery_proto_rawDescOnce.Do(func() {
		file_delivery_v1_delivery_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_delivery_v1_delivery_proto_rawDesc), len(file_delivery_v1_delivery_proto_rawDesc)))
	})
	return file_delivery_v1_delivery_proto_rawDescData
}

var file_delivery_v1_delivery_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_delivery_v1_delivery_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_delivery_v1_delivery_proto_goTypes = []any{
	(ShipmentStatus)(0),            // 0: delivery.v1.ShipmentStatus
	(DeliveryProvider)(0),          // 1: delivery.v1.DeliveryProvider
	(*Address)(nil),                // 2: delivery.v1.Address
	(*Package)(nil),                // 3: delivery.v1.Package
	(*Shipment)(nil),               // 4: delivery.v1.Shipment
	(*CreateShipmentRequest)(nil),  // 5: delivery.v1.CreateShipmentRequest
	(*CreateShipmentResponse)(nil), // 6: delivery.v1.CreateShipmentResponse
	(*GetShipmentRequest)(nil),     // 7: delivery.v1.GetShipmentRequest
	(*GetShipmentResponse)(nil),    // 8: delivery.v1.GetShipmentResponse
	(*TrackShipmentRequest)(nil),   // 9: delivery.v1.TrackShipmentRequest
	(*TrackShipmentResponse)(nil),  // 10: delivery.v1.TrackShipmentResponse
	(*TrackingEvent)(nil),          // 11: delivery.v1.TrackingEvent
	(*CancelShipmentRequest)(nil),  // 12: delivery.v1.CancelShipmentRequest
	(*CancelShipmentResponse)(nil), // 13: delivery.v1.CancelShipmentResponse
	(*CalculateRateRequest)(nil),   // 14: delivery.v1.CalculateRateRequest
	(*CalculateRateResponse)(nil),  // 15: delivery.v1.CalculateRateResponse
	(*timestamppb.Timestamp)(nil),  // 16: google.protobuf.Timestamp
}
var file_delivery_v1_delivery_proto_depIdxs = []int32{
	1,  // 0: delivery.v1.Shipment.provider:type_name -> delivery.v1.DeliveryProvider
	0,  // 1: delivery.v1.Shipment.status:type_name -> delivery.v1.ShipmentStatus
	2,  // 2: delivery.v1.Shipment.from_address:type_name -> delivery.v1.Address
	2,  // 3: delivery.v1.Shipment.to_address:type_name -> delivery.v1.Address
	3,  // 4: delivery.v1.Shipment.package:type_name -> delivery.v1.Package
	16, // 5: delivery.v1.Shipment.created_at:type_name -> google.protobuf.Timestamp
	16, // 6: delivery.v1.Shipment.updated_at:type_name -> google.protobuf.Timestamp
	16, // 7: delivery.v1.Shipment.estimated_delivery:type_name -> google.protobuf.Timestamp
	16, // 8: delivery.v1.Shipment.actual_delivery:type_name -> google.protobuf.Timestamp
	1,  // 9: delivery.v1.CreateShipmentRequest.provider:type_name -> delivery.v1.DeliveryProvider
	2,  // 10: delivery.v1.CreateShipmentRequest.from_address:type_name -> delivery.v1.Address
	2,  // 11: delivery.v1.CreateShipmentRequest.to_address:type_name -> delivery.v1.Address
	3,  // 12: delivery.v1.CreateShipmentRequest.package:type_name -> delivery.v1.Package
	4,  // 13: delivery.v1.CreateShipmentResponse.shipment:type_name -> delivery.v1.Shipment
	4,  // 14: delivery.v1.GetShipmentResponse.shipment:type_name -> delivery.v1.Shipment
	4,  // 15: delivery.v1.TrackShipmentResponse.shipment:type_name -> delivery.v1.Shipment
	11, // 16: delivery.v1.TrackShipmentResponse.events:type_name -> delivery.v1.TrackingEvent
	0,  // 17: delivery.v1.TrackingEvent.status:type_name -> delivery.v1.ShipmentStatus
	16, // 18: delivery.v1.TrackingEvent.timestamp:type_name -> google.protobuf.Timestamp
	4,  // 19: delivery.v1.CancelShipmentResponse.shipment:type_name -> delivery.v1.Shipment
	1,  // 20: delivery.v1.CalculateRateRequest.provider:type_name -> delivery.v1.DeliveryProvider
	2,  // 21: delivery.v1.CalculateRateRequest.from_address:type_name -> delivery.v1.Address
	2,  // 22: delivery.v1.CalculateRateRequest.to_address:type_name -> delivery.v1.Address
	3,  // 23: delivery.v1.CalculateRateRequest.package:type_name -> delivery.v1.Package
	16, // 24: delivery.v1.CalculateRateResponse.estimated_delivery:type_name -> google.protobuf.Timestamp
	5,  // 25: delivery.v1.DeliveryService.CreateShipment:input_type -> delivery.v1.CreateShipmentRequest
	7,  // 26: delivery.v1.DeliveryService.GetShipment:input_type -> delivery.v1.GetShipmentRequest
	9,  // 27: delivery.v1.DeliveryService.TrackShipment:input_type -> delivery.v1.TrackShipmentRequest
	12, // 28: delivery.v1.DeliveryService.CancelShipment:input_type -> delivery.v1.CancelShipmentRequest
	14, // 29: delivery.v1.DeliveryService.CalculateRate:input_type -> delivery.v1.CalculateRateRequest
	6,  // 30: delivery.v1.DeliveryService.CreateShipment:output_type -> delivery.v1.CreateShipmentResponse
	8,  // 31: delivery.v1.DeliveryService.GetShipment:output_type -> delivery.v1.GetShipmentResponse
	10, // 32: delivery.v1.DeliveryService.TrackShipment:output_type -> delivery.v1.TrackShipmentResponse
	13, // 33: delivery.v1.DeliveryService.CancelShipment:output_type -> delivery.v1.CancelShipmentResponse
	15, // 34: delivery.v1.DeliveryService.CalculateRate:output_type -> delivery.v1.CalculateRateResponse
	30, // [30:35] is the sub-list for method output_type
	25, // [25:30] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_delivery_v1_delivery_proto_init() }
func file_delivery_v1_delivery_proto_init() {
	if File_delivery_v1_delivery_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_delivery_v1_delivery_proto_rawDesc), len(file_delivery_v1_delivery_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_delivery_v1_delivery_proto_goTypes,
		DependencyIndexes: file_delivery_v1_delivery_proto_depIdxs,
		EnumInfos:         file_delivery_v1_delivery_proto_enumTypes,
		MessageInfos:      file_delivery_v1_delivery_proto_msgTypes,
	}.Build()
	File_delivery_v1_delivery_proto = out.File
	file_delivery_v1_delivery_proto_goTypes = nil
	file_delivery_v1_delivery_proto_depIdxs = nil
}
