// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/proto/search/v1/common.proto

package searchv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Listing represents a marketplace listing in search results
type Listing struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Listing ID
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Listing UUID
	Uuid string `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	// Listing title
	Title string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	// Listing description (optional)
	Description *string `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`
	// Price
	Price float64 `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	// Currency code (e.g., "EUR", "USD")
	Currency string `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	// Category ID
	CategoryId int64 `protobuf:"varint,7,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	// Listing status (e.g., "active", "inactive")
	Status string `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	// Listing images
	Images []*ListingImage `protobuf:"bytes,9,rep,name=images,proto3" json:"images,omitempty"`
	// Creation timestamp (RFC3339 format)
	CreatedAt string `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// User ID (owner)
	UserId int64 `protobuf:"varint,11,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Storefront ID (optional)
	StorefrontId *int64 `protobuf:"varint,12,opt,name=storefront_id,json=storefrontId,proto3,oneof" json:"storefront_id,omitempty"`
	// Stock quantity
	Quantity int32 `protobuf:"varint,13,opt,name=quantity,proto3" json:"quantity,omitempty"`
	// SKU (optional)
	Sku *string `protobuf:"bytes,14,opt,name=sku,proto3,oneof" json:"sku,omitempty"`
	// Source type (c2c or b2c)
	SourceType string `protobuf:"bytes,15,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"`
	// Stock status
	StockStatus   string `protobuf:"bytes,16,opt,name=stock_status,json=stockStatus,proto3" json:"stock_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Listing) Reset() {
	*x = Listing{}
	mi := &file_api_proto_search_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Listing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Listing) ProtoMessage() {}

func (x *Listing) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_search_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Listing.ProtoReflect.Descriptor instead.
func (*Listing) Descriptor() ([]byte, []int) {
	return file_api_proto_search_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *Listing) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Listing) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Listing) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Listing) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Listing) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Listing) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Listing) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *Listing) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Listing) GetImages() []*ListingImage {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *Listing) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Listing) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Listing) GetStorefrontId() int64 {
	if x != nil && x.StorefrontId != nil {
		return *x.StorefrontId
	}
	return 0
}

func (x *Listing) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Listing) GetSku() string {
	if x != nil && x.Sku != nil {
		return *x.Sku
	}
	return ""
}

func (x *Listing) GetSourceType() string {
	if x != nil {
		return x.SourceType
	}
	return ""
}

func (x *Listing) GetStockStatus() string {
	if x != nil {
		return x.StockStatus
	}
	return ""
}

// ListingImage represents an image in search results
type ListingImage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Image ID
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Image URL
	Url string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	// Whether this is the primary image
	IsPrimary bool `protobuf:"varint,3,opt,name=is_primary,json=isPrimary,proto3" json:"is_primary,omitempty"`
	// Display order
	DisplayOrder  int32 `protobuf:"varint,4,opt,name=display_order,json=displayOrder,proto3" json:"display_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListingImage) Reset() {
	*x = ListingImage{}
	mi := &file_api_proto_search_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListingImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListingImage) ProtoMessage() {}

func (x *ListingImage) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_search_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListingImage.ProtoReflect.Descriptor instead.
func (*ListingImage) Descriptor() ([]byte, []int) {
	return file_api_proto_search_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *ListingImage) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ListingImage) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ListingImage) GetIsPrimary() bool {
	if x != nil {
		return x.IsPrimary
	}
	return false
}

func (x *ListingImage) GetDisplayOrder() int32 {
	if x != nil {
		return x.DisplayOrder
	}
	return 0
}

// Filters message (shared across multiple endpoints)
type Filters struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Price range filter
	Price *PriceRange `protobuf:"bytes,1,opt,name=price,proto3,oneof" json:"price,omitempty"`
	// Attribute filters (e.g., {"brand": ["Nike", "Adidas"], "color": ["Red"]})
	Attributes map[string]*AttributeValues `protobuf:"bytes,2,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Geo location filter
	Location *LocationFilter `protobuf:"bytes,3,opt,name=location,proto3,oneof" json:"location,omitempty"`
	// Source type filter ("c2c" or "b2c")
	SourceType *string `protobuf:"bytes,4,opt,name=source_type,json=sourceType,proto3,oneof" json:"source_type,omitempty"`
	// Stock status filter ("in_stock", "out_of_stock", "low_stock")
	StockStatus   *string `protobuf:"bytes,5,opt,name=stock_status,json=stockStatus,proto3,oneof" json:"stock_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Filters) Reset() {
	*x = Filters{}
	mi := &file_api_proto_search_v1_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filters) ProtoMessage() {}

func (x *Filters) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_search_v1_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filters.ProtoReflect.Descriptor instead.
func (*Filters) Descriptor() ([]byte, []int) {
	return file_api_proto_search_v1_common_proto_rawDescGZIP(), []int{2}
}

func (x *Filters) GetPrice() *PriceRange {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *Filters) GetAttributes() map[string]*AttributeValues {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *Filters) GetLocation() *LocationFilter {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *Filters) GetSourceType() string {
	if x != nil && x.SourceType != nil {
		return *x.SourceType
	}
	return ""
}

func (x *Filters) GetStockStatus() string {
	if x != nil && x.StockStatus != nil {
		return *x.StockStatus
	}
	return ""
}

// PriceRange filter
type PriceRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Min           *float64               `protobuf:"fixed64,1,opt,name=min,proto3,oneof" json:"min,omitempty"`
	Max           *float64               `protobuf:"fixed64,2,opt,name=max,proto3,oneof" json:"max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriceRange) Reset() {
	*x = PriceRange{}
	mi := &file_api_proto_search_v1_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceRange) ProtoMessage() {}

func (x *PriceRange) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_search_v1_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceRange.ProtoReflect.Descriptor instead.
func (*PriceRange) Descriptor() ([]byte, []int) {
	return file_api_proto_search_v1_common_proto_rawDescGZIP(), []int{3}
}

func (x *PriceRange) GetMin() float64 {
	if x != nil && x.Min != nil {
		return *x.Min
	}
	return 0
}

func (x *PriceRange) GetMax() float64 {
	if x != nil && x.Max != nil {
		return *x.Max
	}
	return 0
}

// AttributeValues represents list of values for an attribute
type AttributeValues struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttributeValues) Reset() {
	*x = AttributeValues{}
	mi := &file_api_proto_search_v1_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttributeValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributeValues) ProtoMessage() {}

func (x *AttributeValues) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_search_v1_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributeValues.ProtoReflect.Descriptor instead.
func (*AttributeValues) Descriptor() ([]byte, []int) {
	return file_api_proto_search_v1_common_proto_rawDescGZIP(), []int{4}
}

func (x *AttributeValues) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

// LocationFilter for geo distance filtering
type LocationFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lat           float64                `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon           float64                `protobuf:"fixed64,2,opt,name=lon,proto3" json:"lon,omitempty"`
	RadiusKm      float64                `protobuf:"fixed64,3,opt,name=radius_km,json=radiusKm,proto3" json:"radius_km,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocationFilter) Reset() {
	*x = LocationFilter{}
	mi := &file_api_proto_search_v1_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocationFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocationFilter) ProtoMessage() {}

func (x *LocationFilter) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_search_v1_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocationFilter.ProtoReflect.Descriptor instead.
func (*LocationFilter) Descriptor() ([]byte, []int) {
	return file_api_proto_search_v1_common_proto_rawDescGZIP(), []int{5}
}

func (x *LocationFilter) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *LocationFilter) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *LocationFilter) GetRadiusKm() float64 {
	if x != nil {
		return x.RadiusKm
	}
	return 0
}

var File_api_proto_search_v1_common_proto protoreflect.FileDescriptor

const file_api_proto_search_v1_common_proto_rawDesc = "" +
	"\n" +
	" api/proto/search/v1/common.proto\x12\tsearch.v1\"\x89\x04\n" +
	"\aListing\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12%\n" +
	"\vdescription\x18\x04 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x12\x1f\n" +
	"\vcategory_id\x18\a \x01(\x03R\n" +
	"categoryId\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12/\n" +
	"\x06images\x18\t \x03(\v2\x17.search.v1.ListingImageR\x06images\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\tR\tcreatedAt\x12\x17\n" +
	"\auser_id\x18\v \x01(\x03R\x06userId\x12(\n" +
	"\rstorefront_id\x18\f \x01(\x03H\x01R\fstorefrontId\x88\x01\x01\x12\x1a\n" +
	"\bquantity\x18\r \x01(\x05R\bquantity\x12\x15\n" +
	"\x03sku\x18\x0e \x01(\tH\x02R\x03sku\x88\x01\x01\x12\x1f\n" +
	"\vsource_type\x18\x0f \x01(\tR\n" +
	"sourceType\x12!\n" +
	"\fstock_status\x18\x10 \x01(\tR\vstockStatusB\x0e\n" +
	"\f_descriptionB\x10\n" +
	"\x0e_storefront_idB\x06\n" +
	"\x04_sku\"t\n" +
	"\fListingImage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x1d\n" +
	"\n" +
	"is_primary\x18\x03 \x01(\bR\tisPrimary\x12#\n" +
	"\rdisplay_order\x18\x04 \x01(\x05R\fdisplayOrder\"\x9c\x03\n" +
	"\aFilters\x120\n" +
	"\x05price\x18\x01 \x01(\v2\x15.search.v1.PriceRangeH\x00R\x05price\x88\x01\x01\x12B\n" +
	"\n" +
	"attributes\x18\x02 \x03(\v2\".search.v1.Filters.AttributesEntryR\n" +
	"attributes\x12:\n" +
	"\blocation\x18\x03 \x01(\v2\x19.search.v1.LocationFilterH\x01R\blocation\x88\x01\x01\x12$\n" +
	"\vsource_type\x18\x04 \x01(\tH\x02R\n" +
	"sourceType\x88\x01\x01\x12&\n" +
	"\fstock_status\x18\x05 \x01(\tH\x03R\vstockStatus\x88\x01\x01\x1aY\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x120\n" +
	"\x05value\x18\x02 \x01(\v2\x1a.search.v1.AttributeValuesR\x05value:\x028\x01B\b\n" +
	"\x06_priceB\v\n" +
	"\t_locationB\x0e\n" +
	"\f_source_typeB\x0f\n" +
	"\r_stock_status\"J\n" +
	"\n" +
	"PriceRange\x12\x15\n" +
	"\x03min\x18\x01 \x01(\x01H\x00R\x03min\x88\x01\x01\x12\x15\n" +
	"\x03max\x18\x02 \x01(\x01H\x01R\x03max\x88\x01\x01B\x06\n" +
	"\x04_minB\x06\n" +
	"\x04_max\")\n" +
	"\x0fAttributeValues\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\"Q\n" +
	"\x0eLocationFilter\x12\x10\n" +
	"\x03lat\x18\x01 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lon\x18\x02 \x01(\x01R\x03lon\x12\x1b\n" +
	"\tradius_km\x18\x03 \x01(\x01R\bradiusKmB?Z=github.com/vondi-global/listings/api/proto/search/v1;searchv1b\x06proto3"

var (
	file_api_proto_search_v1_common_proto_rawDescOnce sync.Once
	file_api_proto_search_v1_common_proto_rawDescData []byte
)

func file_api_proto_search_v1_common_proto_rawDescGZIP() []byte {
	file_api_proto_search_v1_common_proto_rawDescOnce.Do(func() {
		file_api_proto_search_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_search_v1_common_proto_rawDesc), len(file_api_proto_search_v1_common_proto_rawDesc)))
	})
	return file_api_proto_search_v1_common_proto_rawDescData
}

var file_api_proto_search_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_proto_search_v1_common_proto_goTypes = []any{
	(*Listing)(nil),         // 0: search.v1.Listing
	(*ListingImage)(nil),    // 1: search.v1.ListingImage
	(*Filters)(nil),         // 2: search.v1.Filters
	(*PriceRange)(nil),      // 3: search.v1.PriceRange
	(*AttributeValues)(nil), // 4: search.v1.AttributeValues
	(*LocationFilter)(nil),  // 5: search.v1.LocationFilter
	nil,                     // 6: search.v1.Filters.AttributesEntry
}
var file_api_proto_search_v1_common_proto_depIdxs = []int32{
	1, // 0: search.v1.Listing.images:type_name -> search.v1.ListingImage
	3, // 1: search.v1.Filters.price:type_name -> search.v1.PriceRange
	6, // 2: search.v1.Filters.attributes:type_name -> search.v1.Filters.AttributesEntry
	5, // 3: search.v1.Filters.location:type_name -> search.v1.LocationFilter
	4, // 4: search.v1.Filters.AttributesEntry.value:type_name -> search.v1.AttributeValues
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_api_proto_search_v1_common_proto_init() }
func file_api_proto_search_v1_common_proto_init() {
	if File_api_proto_search_v1_common_proto != nil {
		return
	}
	file_api_proto_search_v1_common_proto_msgTypes[0].OneofWrappers = []any{}
	file_api_proto_search_v1_common_proto_msgTypes[2].OneofWrappers = []any{}
	file_api_proto_search_v1_common_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_search_v1_common_proto_rawDesc), len(file_api_proto_search_v1_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_search_v1_common_proto_goTypes,
		DependencyIndexes: file_api_proto_search_v1_common_proto_depIdxs,
		MessageInfos:      file_api_proto_search_v1_common_proto_msgTypes,
	}.Build()
	File_api_proto_search_v1_common_proto = out.File
	file_api_proto_search_v1_common_proto_goTypes = nil
	file_api_proto_search_v1_common_proto_depIdxs = nil
}
