// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: api/proto/search/v1/facets.proto

package searchv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetSearchFacetsRequest requests aggregations for search filters
type GetSearchFacetsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional search query to pre-filter before aggregating
	Query *string `protobuf:"bytes,1,opt,name=query,proto3,oneof" json:"query,omitempty"`
	// Optional category filter
	CategoryId *int64 `protobuf:"varint,2,opt,name=category_id,json=categoryId,proto3,oneof" json:"category_id,omitempty"`
	// Pre-filters to apply before aggregating
	Filters       *Filters `protobuf:"bytes,3,opt,name=filters,proto3,oneof" json:"filters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSearchFacetsRequest) Reset() {
	*x = GetSearchFacetsRequest{}
	mi := &file_api_proto_search_v1_facets_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSearchFacetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSearchFacetsRequest) ProtoMessage() {}

func (x *GetSearchFacetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_search_v1_facets_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSearchFacetsRequest.ProtoReflect.Descriptor instead.
func (*GetSearchFacetsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_search_v1_facets_proto_rawDescGZIP(), []int{0}
}

func (x *GetSearchFacetsRequest) GetQuery() string {
	if x != nil && x.Query != nil {
		return *x.Query
	}
	return ""
}

func (x *GetSearchFacetsRequest) GetCategoryId() int64 {
	if x != nil && x.CategoryId != nil {
		return *x.CategoryId
	}
	return 0
}

func (x *GetSearchFacetsRequest) GetFilters() *Filters {
	if x != nil {
		return x.Filters
	}
	return nil
}

// GetSearchFacetsResponse contains aggregated facets for filtering
type GetSearchFacetsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Category distribution
	Categories []*CategoryFacet `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	// Price range buckets
	PriceRanges []*PriceRangeFacet `protobuf:"bytes,2,rep,name=price_ranges,json=priceRanges,proto3" json:"price_ranges,omitempty"`
	// Attribute facets (brand, color, size, etc.)
	// Key is attribute key, value contains possible values and counts
	Attributes map[string]*AttributeFacet `protobuf:"bytes,3,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Source type distribution (c2c, b2c)
	SourceTypes []*Facet `protobuf:"bytes,4,rep,name=source_types,json=sourceTypes,proto3" json:"source_types,omitempty"`
	// Stock status distribution
	StockStatuses []*Facet `protobuf:"bytes,5,rep,name=stock_statuses,json=stockStatuses,proto3" json:"stock_statuses,omitempty"`
	// Query execution time in milliseconds
	TookMs int32 `protobuf:"varint,6,opt,name=took_ms,json=tookMs,proto3" json:"took_ms,omitempty"`
	// Whether result was served from cache
	Cached        bool `protobuf:"varint,7,opt,name=cached,proto3" json:"cached,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSearchFacetsResponse) Reset() {
	*x = GetSearchFacetsResponse{}
	mi := &file_api_proto_search_v1_facets_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSearchFacetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSearchFacetsResponse) ProtoMessage() {}

func (x *GetSearchFacetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_search_v1_facets_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSearchFacetsResponse.ProtoReflect.Descriptor instead.
func (*GetSearchFacetsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_search_v1_facets_proto_rawDescGZIP(), []int{1}
}

func (x *GetSearchFacetsResponse) GetCategories() []*CategoryFacet {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *GetSearchFacetsResponse) GetPriceRanges() []*PriceRangeFacet {
	if x != nil {
		return x.PriceRanges
	}
	return nil
}

func (x *GetSearchFacetsResponse) GetAttributes() map[string]*AttributeFacet {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *GetSearchFacetsResponse) GetSourceTypes() []*Facet {
	if x != nil {
		return x.SourceTypes
	}
	return nil
}

func (x *GetSearchFacetsResponse) GetStockStatuses() []*Facet {
	if x != nil {
		return x.StockStatuses
	}
	return nil
}

func (x *GetSearchFacetsResponse) GetTookMs() int32 {
	if x != nil {
		return x.TookMs
	}
	return 0
}

func (x *GetSearchFacetsResponse) GetCached() bool {
	if x != nil {
		return x.Cached
	}
	return false
}

// CategoryFacet represents category count
type CategoryFacet struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Category ID
	CategoryId int64 `protobuf:"varint,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	// Number of listings in this category
	Count         int64 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryFacet) Reset() {
	*x = CategoryFacet{}
	mi := &file_api_proto_search_v1_facets_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryFacet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryFacet) ProtoMessage() {}

func (x *CategoryFacet) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_search_v1_facets_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryFacet.ProtoReflect.Descriptor instead.
func (*CategoryFacet) Descriptor() ([]byte, []int) {
	return file_api_proto_search_v1_facets_proto_rawDescGZIP(), []int{2}
}

func (x *CategoryFacet) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *CategoryFacet) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

// PriceRangeFacet represents price range bucket
type PriceRangeFacet struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Minimum price in range
	Min float64 `protobuf:"fixed64,1,opt,name=min,proto3" json:"min,omitempty"`
	// Maximum price in range
	Max float64 `protobuf:"fixed64,2,opt,name=max,proto3" json:"max,omitempty"`
	// Number of listings in this range
	Count         int64 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriceRangeFacet) Reset() {
	*x = PriceRangeFacet{}
	mi := &file_api_proto_search_v1_facets_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceRangeFacet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceRangeFacet) ProtoMessage() {}

func (x *PriceRangeFacet) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_search_v1_facets_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceRangeFacet.ProtoReflect.Descriptor instead.
func (*PriceRangeFacet) Descriptor() ([]byte, []int) {
	return file_api_proto_search_v1_facets_proto_rawDescGZIP(), []int{3}
}

func (x *PriceRangeFacet) GetMin() float64 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *PriceRangeFacet) GetMax() float64 {
	if x != nil {
		return x.Max
	}
	return 0
}

func (x *PriceRangeFacet) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

// AttributeFacet contains all values for a specific attribute key
type AttributeFacet struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Attribute key (e.g., "brand", "color")
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// All possible values with their counts
	Values        []*AttributeValueCount `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttributeFacet) Reset() {
	*x = AttributeFacet{}
	mi := &file_api_proto_search_v1_facets_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttributeFacet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributeFacet) ProtoMessage() {}

func (x *AttributeFacet) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_search_v1_facets_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributeFacet.ProtoReflect.Descriptor instead.
func (*AttributeFacet) Descriptor() ([]byte, []int) {
	return file_api_proto_search_v1_facets_proto_rawDescGZIP(), []int{4}
}

func (x *AttributeFacet) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *AttributeFacet) GetValues() []*AttributeValueCount {
	if x != nil {
		return x.Values
	}
	return nil
}

// AttributeValueCount represents count for specific attribute value
type AttributeValueCount struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Attribute value (e.g., "Nike", "Red")
	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	// Number of listings with this value
	Count         int64 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttributeValueCount) Reset() {
	*x = AttributeValueCount{}
	mi := &file_api_proto_search_v1_facets_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttributeValueCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributeValueCount) ProtoMessage() {}

func (x *AttributeValueCount) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_search_v1_facets_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributeValueCount.ProtoReflect.Descriptor instead.
func (*AttributeValueCount) Descriptor() ([]byte, []int) {
	return file_api_proto_search_v1_facets_proto_rawDescGZIP(), []int{5}
}

func (x *AttributeValueCount) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *AttributeValueCount) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

// Facet represents generic key-count pair
type Facet struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Facet key (e.g., "c2c", "in_stock")
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Number of items
	Count         int64 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Facet) Reset() {
	*x = Facet{}
	mi := &file_api_proto_search_v1_facets_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Facet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Facet) ProtoMessage() {}

func (x *Facet) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_search_v1_facets_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Facet.ProtoReflect.Descriptor instead.
func (*Facet) Descriptor() ([]byte, []int) {
	return file_api_proto_search_v1_facets_proto_rawDescGZIP(), []int{6}
}

func (x *Facet) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Facet) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_api_proto_search_v1_facets_proto protoreflect.FileDescriptor

const file_api_proto_search_v1_facets_proto_rawDesc = "" +
	"\n" +
	" api/proto/search/v1/facets.proto\x12\tsearch.v1\x1a api/proto/search/v1/common.proto\"\xb2\x01\n" +
	"\x16GetSearchFacetsRequest\x12\x19\n" +
	"\x05query\x18\x01 \x01(\tH\x00R\x05query\x88\x01\x01\x12$\n" +
	"\vcategory_id\x18\x02 \x01(\x03H\x01R\n" +
	"categoryId\x88\x01\x01\x121\n" +
	"\afilters\x18\x03 \x01(\v2\x12.search.v1.FiltersH\x02R\afilters\x88\x01\x01B\b\n" +
	"\x06_queryB\x0e\n" +
	"\f_category_idB\n" +
	"\n" +
	"\b_filters\"\xdf\x03\n" +
	"\x17GetSearchFacetsResponse\x128\n" +
	"\n" +
	"categories\x18\x01 \x03(\v2\x18.search.v1.CategoryFacetR\n" +
	"categories\x12=\n" +
	"\fprice_ranges\x18\x02 \x03(\v2\x1a.search.v1.PriceRangeFacetR\vpriceRanges\x12R\n" +
	"\n" +
	"attributes\x18\x03 \x03(\v22.search.v1.GetSearchFacetsResponse.AttributesEntryR\n" +
	"attributes\x123\n" +
	"\fsource_types\x18\x04 \x03(\v2\x10.search.v1.FacetR\vsourceTypes\x127\n" +
	"\x0estock_statuses\x18\x05 \x03(\v2\x10.search.v1.FacetR\rstockStatuses\x12\x17\n" +
	"\atook_ms\x18\x06 \x01(\x05R\x06tookMs\x12\x16\n" +
	"\x06cached\x18\a \x01(\bR\x06cached\x1aX\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12/\n" +
	"\x05value\x18\x02 \x01(\v2\x19.search.v1.AttributeFacetR\x05value:\x028\x01\"F\n" +
	"\rCategoryFacet\x12\x1f\n" +
	"\vcategory_id\x18\x01 \x01(\x03R\n" +
	"categoryId\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\"K\n" +
	"\x0fPriceRangeFacet\x12\x10\n" +
	"\x03min\x18\x01 \x01(\x01R\x03min\x12\x10\n" +
	"\x03max\x18\x02 \x01(\x01R\x03max\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x03R\x05count\"Z\n" +
	"\x0eAttributeFacet\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x126\n" +
	"\x06values\x18\x02 \x03(\v2\x1e.search.v1.AttributeValueCountR\x06values\"A\n" +
	"\x13AttributeValueCount\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\"/\n" +
	"\x05Facet\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05countB:Z8github.com/vondi-global/listings/api/proto/search/v1;searchv1b\x06proto3"

var (
	file_api_proto_search_v1_facets_proto_rawDescOnce sync.Once
	file_api_proto_search_v1_facets_proto_rawDescData []byte
)

func file_api_proto_search_v1_facets_proto_rawDescGZIP() []byte {
	file_api_proto_search_v1_facets_proto_rawDescOnce.Do(func() {
		file_api_proto_search_v1_facets_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_search_v1_facets_proto_rawDesc), len(file_api_proto_search_v1_facets_proto_rawDesc)))
	})
	return file_api_proto_search_v1_facets_proto_rawDescData
}

var file_api_proto_search_v1_facets_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_proto_search_v1_facets_proto_goTypes = []any{
	(*GetSearchFacetsRequest)(nil),  // 0: search.v1.GetSearchFacetsRequest
	(*GetSearchFacetsResponse)(nil), // 1: search.v1.GetSearchFacetsResponse
	(*CategoryFacet)(nil),           // 2: search.v1.CategoryFacet
	(*PriceRangeFacet)(nil),         // 3: search.v1.PriceRangeFacet
	(*AttributeFacet)(nil),          // 4: search.v1.AttributeFacet
	(*AttributeValueCount)(nil),     // 5: search.v1.AttributeValueCount
	(*Facet)(nil),                   // 6: search.v1.Facet
	nil,                             // 7: search.v1.GetSearchFacetsResponse.AttributesEntry
	(*Filters)(nil),                 // 8: search.v1.Filters
}
var file_api_proto_search_v1_facets_proto_depIdxs = []int32{
	8, // 0: search.v1.GetSearchFacetsRequest.filters:type_name -> search.v1.Filters
	2, // 1: search.v1.GetSearchFacetsResponse.categories:type_name -> search.v1.CategoryFacet
	3, // 2: search.v1.GetSearchFacetsResponse.price_ranges:type_name -> search.v1.PriceRangeFacet
	7, // 3: search.v1.GetSearchFacetsResponse.attributes:type_name -> search.v1.GetSearchFacetsResponse.AttributesEntry
	6, // 4: search.v1.GetSearchFacetsResponse.source_types:type_name -> search.v1.Facet
	6, // 5: search.v1.GetSearchFacetsResponse.stock_statuses:type_name -> search.v1.Facet
	5, // 6: search.v1.AttributeFacet.values:type_name -> search.v1.AttributeValueCount
	4, // 7: search.v1.GetSearchFacetsResponse.AttributesEntry.value:type_name -> search.v1.AttributeFacet
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_api_proto_search_v1_facets_proto_init() }
func file_api_proto_search_v1_facets_proto_init() {
	if File_api_proto_search_v1_facets_proto != nil {
		return
	}
	file_api_proto_search_v1_common_proto_init()
	file_api_proto_search_v1_facets_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_search_v1_facets_proto_rawDesc), len(file_api_proto_search_v1_facets_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_search_v1_facets_proto_goTypes,
		DependencyIndexes: file_api_proto_search_v1_facets_proto_depIdxs,
		MessageInfos:      file_api_proto_search_v1_facets_proto_msgTypes,
	}.Build()
	File_api_proto_search_v1_facets_proto = out.File
	file_api_proto_search_v1_facets_proto_goTypes = nil
	file_api_proto_search_v1_facets_proto_depIdxs = nil
}
