// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.0
// 	protoc        v3.21.12
// source: api/proto/search/v1/facets.proto

package searchv1

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetSearchFacetsRequest requests aggregations for search filters
type GetSearchFacetsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional search query to pre-filter before aggregating
	Query *string `protobuf:"bytes,1,opt,name=query,proto3,oneof" json:"query,omitempty"`
	// Optional category filter
	CategoryId *int64 `protobuf:"varint,2,opt,name=category_id,json=categoryId,proto3,oneof" json:"category_id,omitempty"`
	// Pre-filters to apply before aggregating
	Filters       *Filters `protobuf:"bytes,3,opt,name=filters,proto3,oneof" json:"filters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSearchFacetsRequest) Reset() {
	*x = GetSearchFacetsRequest{}
	mi := &file_api_proto_search_v1_facets_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSearchFacetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSearchFacetsRequest) ProtoMessage() {}

func (x *GetSearchFacetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_search_v1_facets_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSearchFacetsRequest.ProtoReflect.Descriptor instead.
func (*GetSearchFacetsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_search_v1_facets_proto_rawDescGZIP(), []int{0}
}

func (x *GetSearchFacetsRequest) GetQuery() string {
	if x != nil && x.Query != nil {
		return *x.Query
	}
	return ""
}

func (x *GetSearchFacetsRequest) GetCategoryId() int64 {
	if x != nil && x.CategoryId != nil {
		return *x.CategoryId
	}
	return 0
}

func (x *GetSearchFacetsRequest) GetFilters() *Filters {
	if x != nil {
		return x.Filters
	}
	return nil
}

// GetSearchFacetsResponse contains aggregated facets for filtering
type GetSearchFacetsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Category distribution
	Categories []*CategoryFacet `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	// Price range buckets
	PriceRanges []*PriceRangeFacet `protobuf:"bytes,2,rep,name=price_ranges,json=priceRanges,proto3" json:"price_ranges,omitempty"`
	// Attribute facets (brand, color, size, etc.)
	// Key is attribute key, value contains possible values and counts
	Attributes map[string]*AttributeFacet `protobuf:"bytes,3,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Source type distribution (c2c, b2c)
	SourceTypes []*Facet `protobuf:"bytes,4,rep,name=source_types,json=sourceTypes,proto3" json:"source_types,omitempty"`
	// Stock status distribution
	StockStatuses []*Facet `protobuf:"bytes,5,rep,name=stock_statuses,json=stockStatuses,proto3" json:"stock_statuses,omitempty"`
	// Query execution time in milliseconds
	TookMs int32 `protobuf:"varint,6,opt,name=took_ms,json=tookMs,proto3" json:"took_ms,omitempty"`
	// Whether result was served from cache
	Cached        bool `protobuf:"varint,7,opt,name=cached,proto3" json:"cached,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSearchFacetsResponse) Reset() {
	*x = GetSearchFacetsResponse{}
	mi := &file_api_proto_search_v1_facets_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSearchFacetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSearchFacetsResponse) ProtoMessage() {}

func (x *GetSearchFacetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_search_v1_facets_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSearchFacetsResponse.ProtoReflect.Descriptor instead.
func (*GetSearchFacetsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_search_v1_facets_proto_rawDescGZIP(), []int{1}
}

func (x *GetSearchFacetsResponse) GetCategories() []*CategoryFacet {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *GetSearchFacetsResponse) GetPriceRanges() []*PriceRangeFacet {
	if x != nil {
		return x.PriceRanges
	}
	return nil
}

func (x *GetSearchFacetsResponse) GetAttributes() map[string]*AttributeFacet {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *GetSearchFacetsResponse) GetSourceTypes() []*Facet {
	if x != nil {
		return x.SourceTypes
	}
	return nil
}

func (x *GetSearchFacetsResponse) GetStockStatuses() []*Facet {
	if x != nil {
		return x.StockStatuses
	}
	return nil
}

func (x *GetSearchFacetsResponse) GetTookMs() int32 {
	if x != nil {
		return x.TookMs
	}
	return 0
}

func (x *GetSearchFacetsResponse) GetCached() bool {
	if x != nil {
		return x.Cached
	}
	return false
}

// CategoryFacet represents category count
type CategoryFacet struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Category ID
	CategoryId int64 `protobuf:"varint,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	// Number of listings in this category
	Count         int64 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryFacet) Reset() {
	*x = CategoryFacet{}
	mi := &file_api_proto_search_v1_facets_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryFacet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryFacet) ProtoMessage() {}

func (x *CategoryFacet) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_search_v1_facets_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryFacet.ProtoReflect.Descriptor instead.
func (*CategoryFacet) Descriptor() ([]byte, []int) {
	return file_api_proto_search_v1_facets_proto_rawDescGZIP(), []int{2}
}

func (x *CategoryFacet) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *CategoryFacet) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

// PriceRangeFacet represents price range bucket
type PriceRangeFacet struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Minimum price in range
	Min float64 `protobuf:"fixed64,1,opt,name=min,proto3" json:"min,omitempty"`
	// Maximum price in range
	Max float64 `protobuf:"fixed64,2,opt,name=max,proto3" json:"max,omitempty"`
	// Number of listings in this range
	Count         int64 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriceRangeFacet) Reset() {
	*x = PriceRangeFacet{}
	mi := &file_api_proto_search_v1_facets_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceRangeFacet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceRangeFacet) ProtoMessage() {}

func (x *PriceRangeFacet) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_search_v1_facets_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceRangeFacet.ProtoReflect.Descriptor instead.
func (*PriceRangeFacet) Descriptor() ([]byte, []int) {
	return file_api_proto_search_v1_facets_proto_rawDescGZIP(), []int{3}
}

func (x *PriceRangeFacet) GetMin() float64 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *PriceRangeFacet) GetMax() float64 {
	if x != nil {
		return x.Max
	}
	return 0
}

func (x *PriceRangeFacet) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

// AttributeFacet contains all values for a specific attribute key
type AttributeFacet struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Attribute key (e.g., "brand", "color")
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// All possible values with their counts
	Values        []*AttributeValueCount `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttributeFacet) Reset() {
	*x = AttributeFacet{}
	mi := &file_api_proto_search_v1_facets_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttributeFacet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributeFacet) ProtoMessage() {}

func (x *AttributeFacet) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_search_v1_facets_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributeFacet.ProtoReflect.Descriptor instead.
func (*AttributeFacet) Descriptor() ([]byte, []int) {
	return file_api_proto_search_v1_facets_proto_rawDescGZIP(), []int{4}
}

func (x *AttributeFacet) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *AttributeFacet) GetValues() []*AttributeValueCount {
	if x != nil {
		return x.Values
	}
	return nil
}

// AttributeValueCount represents count for specific attribute value
type AttributeValueCount struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Attribute value (e.g., "Nike", "Red")
	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	// Number of listings with this value
	Count         int64 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttributeValueCount) Reset() {
	*x = AttributeValueCount{}
	mi := &file_api_proto_search_v1_facets_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttributeValueCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributeValueCount) ProtoMessage() {}

func (x *AttributeValueCount) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_search_v1_facets_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributeValueCount.ProtoReflect.Descriptor instead.
func (*AttributeValueCount) Descriptor() ([]byte, []int) {
	return file_api_proto_search_v1_facets_proto_rawDescGZIP(), []int{5}
}

func (x *AttributeValueCount) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *AttributeValueCount) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

// Facet represents generic key-count pair
type Facet struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Facet key (e.g., "c2c", "in_stock")
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Number of items
	Count         int64 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Facet) Reset() {
	*x = Facet{}
	mi := &file_api_proto_search_v1_facets_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Facet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Facet) ProtoMessage() {}

func (x *Facet) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_search_v1_facets_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Facet.ProtoReflect.Descriptor instead.
func (*Facet) Descriptor() ([]byte, []int) {
	return file_api_proto_search_v1_facets_proto_rawDescGZIP(), []int{6}
}

func (x *Facet) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Facet) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_api_proto_search_v1_facets_proto protoreflect.FileDescriptor

var file_api_proto_search_v1_facets_proto_rawDesc = []byte{
	0x0a, 0x20, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x2f, 0x76, 0x31, 0x2f, 0x66, 0x61, 0x63, 0x65, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x09, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x2e, 0x76, 0x31, 0x1a, 0x20, 0x61,
	0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x2f,
	0x76, 0x31, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xb2, 0x01, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x46, 0x61, 0x63,
	0x65, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x05, 0x71, 0x75,
	0x65, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x05, 0x71, 0x75, 0x65,
	0x72, 0x79, 0x88, 0x01, 0x01, 0x12, 0x24, 0x0a, 0x0b, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x79, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x48, 0x01, 0x52, 0x0a, 0x63, 0x61,
	0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x88, 0x01, 0x01, 0x12, 0x31, 0x0a, 0x07, 0x66,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x73,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73,
	0x48, 0x02, 0x52, 0x07, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x88, 0x01, 0x01, 0x42, 0x08,
	0x0a, 0x06, 0x5f, 0x71, 0x75, 0x65, 0x72, 0x79, 0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x63, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x79, 0x5f, 0x69, 0x64, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x66, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x73, 0x22, 0xdf, 0x03, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x53, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x46, 0x61, 0x63, 0x65, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x38, 0x0a, 0x0a, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x2e, 0x76, 0x31,
	0x2e, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x46, 0x61, 0x63, 0x65, 0x74, 0x52, 0x0a,
	0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x12, 0x3d, 0x0a, 0x0c, 0x70, 0x72,
	0x69, 0x63, 0x65, 0x5f, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72, 0x69,
	0x63, 0x65, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x46, 0x61, 0x63, 0x65, 0x74, 0x52, 0x0b, 0x70, 0x72,
	0x69, 0x63, 0x65, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x73, 0x12, 0x52, 0x0a, 0x0a, 0x61, 0x74, 0x74,
	0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x32, 0x2e,
	0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x46, 0x61, 0x63, 0x65, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x2e, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x52, 0x0a, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x12, 0x33, 0x0a,
	0x0c, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x18, 0x04, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x2e, 0x76, 0x31, 0x2e,
	0x46, 0x61, 0x63, 0x65, 0x74, 0x52, 0x0b, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x54, 0x79, 0x70,
	0x65, 0x73, 0x12, 0x37, 0x0a, 0x0e, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x5f, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x65, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x73, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x61, 0x63, 0x65, 0x74, 0x52, 0x0d, 0x73, 0x74,
	0x6f, 0x63, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x65, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x74,
	0x6f, 0x6f, 0x6b, 0x5f, 0x6d, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x74, 0x6f,
	0x6f, 0x6b, 0x4d, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x61, 0x63, 0x68, 0x65, 0x64, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x63, 0x61, 0x63, 0x68, 0x65, 0x64, 0x1a, 0x58, 0x0a, 0x0f,
	0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x2f, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x19, 0x2e, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x74, 0x74,
	0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x46, 0x61, 0x63, 0x65, 0x74, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x46, 0x0a, 0x0d, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x79, 0x46, 0x61, 0x63, 0x65, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x61, 0x74, 0x65, 0x67,
	0x6f, 0x72, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x63, 0x61,
	0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x4b,
	0x0a, 0x0f, 0x50, 0x72, 0x69, 0x63, 0x65, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x46, 0x61, 0x63, 0x65,
	0x74, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03,
	0x6d, 0x69, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x61, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x03, 0x6d, 0x61, 0x78, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x5a, 0x0a, 0x0e, 0x41,
	0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x46, 0x61, 0x63, 0x65, 0x74, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x36, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x1e, 0x2e, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x74, 0x74, 0x72,
	0x69, 0x62, 0x75, 0x74, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52,
	0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22, 0x41, 0x0a, 0x13, 0x41, 0x74, 0x74, 0x72, 0x69,
	0x62, 0x75, 0x74, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x2f, 0x0a, 0x05, 0x46, 0x61,
	0x63, 0x65, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x42, 0x3f, 0x5a, 0x3d, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x76, 0x6f, 0x6e, 0x64, 0x69, 0x2d,
	0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x2f, 0x6c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x2f, 0x76, 0x31, 0x3b, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_proto_search_v1_facets_proto_rawDescOnce sync.Once
	file_api_proto_search_v1_facets_proto_rawDescData = file_api_proto_search_v1_facets_proto_rawDesc
)

func file_api_proto_search_v1_facets_proto_rawDescGZIP() []byte {
	file_api_proto_search_v1_facets_proto_rawDescOnce.Do(func() {
		file_api_proto_search_v1_facets_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_search_v1_facets_proto_rawDescData)
	})
	return file_api_proto_search_v1_facets_proto_rawDescData
}

var file_api_proto_search_v1_facets_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_proto_search_v1_facets_proto_goTypes = []any{
	(*GetSearchFacetsRequest)(nil),  // 0: search.v1.GetSearchFacetsRequest
	(*GetSearchFacetsResponse)(nil), // 1: search.v1.GetSearchFacetsResponse
	(*CategoryFacet)(nil),           // 2: search.v1.CategoryFacet
	(*PriceRangeFacet)(nil),         // 3: search.v1.PriceRangeFacet
	(*AttributeFacet)(nil),          // 4: search.v1.AttributeFacet
	(*AttributeValueCount)(nil),     // 5: search.v1.AttributeValueCount
	(*Facet)(nil),                   // 6: search.v1.Facet
	nil,                             // 7: search.v1.GetSearchFacetsResponse.AttributesEntry
	(*Filters)(nil),                 // 8: search.v1.Filters
}
var file_api_proto_search_v1_facets_proto_depIdxs = []int32{
	8, // 0: search.v1.GetSearchFacetsRequest.filters:type_name -> search.v1.Filters
	2, // 1: search.v1.GetSearchFacetsResponse.categories:type_name -> search.v1.CategoryFacet
	3, // 2: search.v1.GetSearchFacetsResponse.price_ranges:type_name -> search.v1.PriceRangeFacet
	7, // 3: search.v1.GetSearchFacetsResponse.attributes:type_name -> search.v1.GetSearchFacetsResponse.AttributesEntry
	6, // 4: search.v1.GetSearchFacetsResponse.source_types:type_name -> search.v1.Facet
	6, // 5: search.v1.GetSearchFacetsResponse.stock_statuses:type_name -> search.v1.Facet
	5, // 6: search.v1.AttributeFacet.values:type_name -> search.v1.AttributeValueCount
	4, // 7: search.v1.GetSearchFacetsResponse.AttributesEntry.value:type_name -> search.v1.AttributeFacet
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_api_proto_search_v1_facets_proto_init() }
func file_api_proto_search_v1_facets_proto_init() {
	if File_api_proto_search_v1_facets_proto != nil {
		return
	}
	file_api_proto_search_v1_common_proto_init()
	file_api_proto_search_v1_facets_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_search_v1_facets_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_search_v1_facets_proto_goTypes,
		DependencyIndexes: file_api_proto_search_v1_facets_proto_depIdxs,
		MessageInfos:      file_api_proto_search_v1_facets_proto_msgTypes,
	}.Build()
	File_api_proto_search_v1_facets_proto = out.File
	file_api_proto_search_v1_facets_proto_rawDesc = nil
	file_api_proto_search_v1_facets_proto_goTypes = nil
	file_api_proto_search_v1_facets_proto_depIdxs = nil
}
