// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: api/proto/search/v1/search.proto

package searchv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SearchListingsRequest contains search parameters
type SearchListingsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Search query text (optional - can search without query)
	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	// Filter by category ID (optional)
	CategoryId *int64 `protobuf:"varint,2,opt,name=category_id,json=categoryId,proto3,oneof" json:"category_id,omitempty"`
	// Results per page (1-100, default: 20)
	Limit int32 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	// Pagination offset (default: 0)
	Offset int32 `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	// Use Redis cache for results (default: true)
	UseCache      bool `protobuf:"varint,5,opt,name=use_cache,json=useCache,proto3" json:"use_cache,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchListingsRequest) Reset() {
	*x = SearchListingsRequest{}
	mi := &file_api_proto_search_v1_search_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchListingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchListingsRequest) ProtoMessage() {}

func (x *SearchListingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_search_v1_search_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchListingsRequest.ProtoReflect.Descriptor instead.
func (*SearchListingsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_search_v1_search_proto_rawDescGZIP(), []int{0}
}

func (x *SearchListingsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchListingsRequest) GetCategoryId() int64 {
	if x != nil && x.CategoryId != nil {
		return *x.CategoryId
	}
	return 0
}

func (x *SearchListingsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchListingsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *SearchListingsRequest) GetUseCache() bool {
	if x != nil {
		return x.UseCache
	}
	return false
}

// SearchListingsResponse contains search results
type SearchListingsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of matching listings
	Listings []*Listing `protobuf:"bytes,1,rep,name=listings,proto3" json:"listings,omitempty"`
	// Total number of matching documents
	Total int64 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	// Search duration in milliseconds
	TookMs int32 `protobuf:"varint,3,opt,name=took_ms,json=tookMs,proto3" json:"took_ms,omitempty"`
	// Whether result was served from cache
	Cached        bool `protobuf:"varint,4,opt,name=cached,proto3" json:"cached,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchListingsResponse) Reset() {
	*x = SearchListingsResponse{}
	mi := &file_api_proto_search_v1_search_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchListingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchListingsResponse) ProtoMessage() {}

func (x *SearchListingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_search_v1_search_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchListingsResponse.ProtoReflect.Descriptor instead.
func (*SearchListingsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_search_v1_search_proto_rawDescGZIP(), []int{1}
}

func (x *SearchListingsResponse) GetListings() []*Listing {
	if x != nil {
		return x.Listings
	}
	return nil
}

func (x *SearchListingsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *SearchListingsResponse) GetTookMs() int32 {
	if x != nil {
		return x.TookMs
	}
	return 0
}

func (x *SearchListingsResponse) GetCached() bool {
	if x != nil {
		return x.Cached
	}
	return false
}

var File_api_proto_search_v1_search_proto protoreflect.FileDescriptor

const file_api_proto_search_v1_search_proto_rawDesc = "" +
	"\n" +
	" api/proto/search/v1/search.proto\x12\tsearch.v1\x1a api/proto/search/v1/common.proto\x1a api/proto/search/v1/facets.proto\x1a!api/proto/search/v1/filters.proto\x1a%api/proto/search/v1/suggestions.proto\x1a!api/proto/search/v1/popular.proto\"\xae\x01\n" +
	"\x15SearchListingsRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12$\n" +
	"\vcategory_id\x18\x02 \x01(\x03H\x00R\n" +
	"categoryId\x88\x01\x01\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\x12\x1b\n" +
	"\tuse_cache\x18\x05 \x01(\bR\buseCacheB\x0e\n" +
	"\f_category_id\"\x8f\x01\n" +
	"\x16SearchListingsResponse\x12.\n" +
	"\blistings\x18\x01 \x03(\v2\x12.search.v1.ListingR\blistings\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x17\n" +
	"\atook_ms\x18\x03 \x01(\x05R\x06tookMs\x12\x16\n" +
	"\x06cached\x18\x04 \x01(\bR\x06cached2\xda\x03\n" +
	"\rSearchService\x12U\n" +
	"\x0eSearchListings\x12 .search.v1.SearchListingsRequest\x1a!.search.v1.SearchListingsResponse\x12X\n" +
	"\x0fGetSearchFacets\x12!.search.v1.GetSearchFacetsRequest\x1a\".search.v1.GetSearchFacetsResponse\x12^\n" +
	"\x11SearchWithFilters\x12#.search.v1.SearchWithFiltersRequest\x1a$.search.v1.SearchWithFiltersResponse\x12U\n" +
	"\x0eGetSuggestions\x12 .search.v1.GetSuggestionsRequest\x1a!.search.v1.GetSuggestionsResponse\x12a\n" +
	"\x12GetPopularSearches\x12$.search.v1.GetPopularSearchesRequest\x1a%.search.v1.GetPopularSearchesResponseB:Z8github.com/sveturs/listings/api/proto/search/v1;searchv1b\x06proto3"

var (
	file_api_proto_search_v1_search_proto_rawDescOnce sync.Once
	file_api_proto_search_v1_search_proto_rawDescData []byte
)

func file_api_proto_search_v1_search_proto_rawDescGZIP() []byte {
	file_api_proto_search_v1_search_proto_rawDescOnce.Do(func() {
		file_api_proto_search_v1_search_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_search_v1_search_proto_rawDesc), len(file_api_proto_search_v1_search_proto_rawDesc)))
	})
	return file_api_proto_search_v1_search_proto_rawDescData
}

var file_api_proto_search_v1_search_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_search_v1_search_proto_goTypes = []any{
	(*SearchListingsRequest)(nil),      // 0: search.v1.SearchListingsRequest
	(*SearchListingsResponse)(nil),     // 1: search.v1.SearchListingsResponse
	(*Listing)(nil),                    // 2: search.v1.Listing
	(*GetSearchFacetsRequest)(nil),     // 3: search.v1.GetSearchFacetsRequest
	(*SearchWithFiltersRequest)(nil),   // 4: search.v1.SearchWithFiltersRequest
	(*GetSuggestionsRequest)(nil),      // 5: search.v1.GetSuggestionsRequest
	(*GetPopularSearchesRequest)(nil),  // 6: search.v1.GetPopularSearchesRequest
	(*GetSearchFacetsResponse)(nil),    // 7: search.v1.GetSearchFacetsResponse
	(*SearchWithFiltersResponse)(nil),  // 8: search.v1.SearchWithFiltersResponse
	(*GetSuggestionsResponse)(nil),     // 9: search.v1.GetSuggestionsResponse
	(*GetPopularSearchesResponse)(nil), // 10: search.v1.GetPopularSearchesResponse
}
var file_api_proto_search_v1_search_proto_depIdxs = []int32{
	2,  // 0: search.v1.SearchListingsResponse.listings:type_name -> search.v1.Listing
	0,  // 1: search.v1.SearchService.SearchListings:input_type -> search.v1.SearchListingsRequest
	3,  // 2: search.v1.SearchService.GetSearchFacets:input_type -> search.v1.GetSearchFacetsRequest
	4,  // 3: search.v1.SearchService.SearchWithFilters:input_type -> search.v1.SearchWithFiltersRequest
	5,  // 4: search.v1.SearchService.GetSuggestions:input_type -> search.v1.GetSuggestionsRequest
	6,  // 5: search.v1.SearchService.GetPopularSearches:input_type -> search.v1.GetPopularSearchesRequest
	1,  // 6: search.v1.SearchService.SearchListings:output_type -> search.v1.SearchListingsResponse
	7,  // 7: search.v1.SearchService.GetSearchFacets:output_type -> search.v1.GetSearchFacetsResponse
	8,  // 8: search.v1.SearchService.SearchWithFilters:output_type -> search.v1.SearchWithFiltersResponse
	9,  // 9: search.v1.SearchService.GetSuggestions:output_type -> search.v1.GetSuggestionsResponse
	10, // 10: search.v1.SearchService.GetPopularSearches:output_type -> search.v1.GetPopularSearchesResponse
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_search_v1_search_proto_init() }
func file_api_proto_search_v1_search_proto_init() {
	if File_api_proto_search_v1_search_proto != nil {
		return
	}
	file_api_proto_search_v1_common_proto_init()
	file_api_proto_search_v1_facets_proto_init()
	file_api_proto_search_v1_filters_proto_init()
	file_api_proto_search_v1_suggestions_proto_init()
	file_api_proto_search_v1_popular_proto_init()
	file_api_proto_search_v1_search_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_search_v1_search_proto_rawDesc), len(file_api_proto_search_v1_search_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_search_v1_search_proto_goTypes,
		DependencyIndexes: file_api_proto_search_v1_search_proto_depIdxs,
		MessageInfos:      file_api_proto_search_v1_search_proto_msgTypes,
	}.Build()
	File_api_proto_search_v1_search_proto = out.File
	file_api_proto_search_v1_search_proto_goTypes = nil
	file_api_proto_search_v1_search_proto_depIdxs = nil
}
