// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/proto/search/v1/suggestions.proto

package searchv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetSuggestionsRequest requests autocomplete suggestions
type GetSuggestionsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Search prefix (minimum 2 characters required)
	Prefix string `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	// Optional category filter (only suggest from this category)
	CategoryId *int64 `protobuf:"varint,2,opt,name=category_id,json=categoryId,proto3,oneof" json:"category_id,omitempty"`
	// Maximum number of suggestions (default: 10, max: 20)
	Limit         int32 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSuggestionsRequest) Reset() {
	*x = GetSuggestionsRequest{}
	mi := &file_api_proto_search_v1_suggestions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSuggestionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSuggestionsRequest) ProtoMessage() {}

func (x *GetSuggestionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_search_v1_suggestions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSuggestionsRequest.ProtoReflect.Descriptor instead.
func (*GetSuggestionsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_search_v1_suggestions_proto_rawDescGZIP(), []int{0}
}

func (x *GetSuggestionsRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *GetSuggestionsRequest) GetCategoryId() int64 {
	if x != nil && x.CategoryId != nil {
		return *x.CategoryId
	}
	return 0
}

func (x *GetSuggestionsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// GetSuggestionsResponse contains autocomplete suggestions
type GetSuggestionsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of suggestions ordered by relevance/score
	Suggestions []*Suggestion `protobuf:"bytes,1,rep,name=suggestions,proto3" json:"suggestions,omitempty"`
	// Query execution time in milliseconds
	TookMs int32 `protobuf:"varint,2,opt,name=took_ms,json=tookMs,proto3" json:"took_ms,omitempty"`
	// Whether result was served from cache
	Cached        bool `protobuf:"varint,3,opt,name=cached,proto3" json:"cached,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSuggestionsResponse) Reset() {
	*x = GetSuggestionsResponse{}
	mi := &file_api_proto_search_v1_suggestions_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSuggestionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSuggestionsResponse) ProtoMessage() {}

func (x *GetSuggestionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_search_v1_suggestions_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSuggestionsResponse.ProtoReflect.Descriptor instead.
func (*GetSuggestionsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_search_v1_suggestions_proto_rawDescGZIP(), []int{1}
}

func (x *GetSuggestionsResponse) GetSuggestions() []*Suggestion {
	if x != nil {
		return x.Suggestions
	}
	return nil
}

func (x *GetSuggestionsResponse) GetTookMs() int32 {
	if x != nil {
		return x.TookMs
	}
	return 0
}

func (x *GetSuggestionsResponse) GetCached() bool {
	if x != nil {
		return x.Cached
	}
	return false
}

// Suggestion represents a single autocomplete suggestion
type Suggestion struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Suggested text (complete phrase)
	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	// Relevance score (higher is better)
	Score float64 `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"`
	// Optional listing ID if suggestion comes from specific listing
	ListingId     *int64 `protobuf:"varint,3,opt,name=listing_id,json=listingId,proto3,oneof" json:"listing_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Suggestion) Reset() {
	*x = Suggestion{}
	mi := &file_api_proto_search_v1_suggestions_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Suggestion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Suggestion) ProtoMessage() {}

func (x *Suggestion) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_search_v1_suggestions_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Suggestion.ProtoReflect.Descriptor instead.
func (*Suggestion) Descriptor() ([]byte, []int) {
	return file_api_proto_search_v1_suggestions_proto_rawDescGZIP(), []int{2}
}

func (x *Suggestion) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Suggestion) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Suggestion) GetListingId() int64 {
	if x != nil && x.ListingId != nil {
		return *x.ListingId
	}
	return 0
}

var File_api_proto_search_v1_suggestions_proto protoreflect.FileDescriptor

const file_api_proto_search_v1_suggestions_proto_rawDesc = "" +
	"\n" +
	"%api/proto/search/v1/suggestions.proto\x12\tsearch.v1\"{\n" +
	"\x15GetSuggestionsRequest\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\tR\x06prefix\x12$\n" +
	"\vcategory_id\x18\x02 \x01(\x03H\x00R\n" +
	"categoryId\x88\x01\x01\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limitB\x0e\n" +
	"\f_category_id\"\x82\x01\n" +
	"\x16GetSuggestionsResponse\x127\n" +
	"\vsuggestions\x18\x01 \x03(\v2\x15.search.v1.SuggestionR\vsuggestions\x12\x17\n" +
	"\atook_ms\x18\x02 \x01(\x05R\x06tookMs\x12\x16\n" +
	"\x06cached\x18\x03 \x01(\bR\x06cached\"i\n" +
	"\n" +
	"Suggestion\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x01R\x05score\x12\"\n" +
	"\n" +
	"listing_id\x18\x03 \x01(\x03H\x00R\tlistingId\x88\x01\x01B\r\n" +
	"\v_listing_idB?Z=github.com/vondi-global/listings/api/proto/search/v1;searchv1b\x06proto3"

var (
	file_api_proto_search_v1_suggestions_proto_rawDescOnce sync.Once
	file_api_proto_search_v1_suggestions_proto_rawDescData []byte
)

func file_api_proto_search_v1_suggestions_proto_rawDescGZIP() []byte {
	file_api_proto_search_v1_suggestions_proto_rawDescOnce.Do(func() {
		file_api_proto_search_v1_suggestions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_search_v1_suggestions_proto_rawDesc), len(file_api_proto_search_v1_suggestions_proto_rawDesc)))
	})
	return file_api_proto_search_v1_suggestions_proto_rawDescData
}

var file_api_proto_search_v1_suggestions_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_proto_search_v1_suggestions_proto_goTypes = []any{
	(*GetSuggestionsRequest)(nil),  // 0: search.v1.GetSuggestionsRequest
	(*GetSuggestionsResponse)(nil), // 1: search.v1.GetSuggestionsResponse
	(*Suggestion)(nil),             // 2: search.v1.Suggestion
}
var file_api_proto_search_v1_suggestions_proto_depIdxs = []int32{
	2, // 0: search.v1.GetSuggestionsResponse.suggestions:type_name -> search.v1.Suggestion
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_search_v1_suggestions_proto_init() }
func file_api_proto_search_v1_suggestions_proto_init() {
	if File_api_proto_search_v1_suggestions_proto != nil {
		return
	}
	file_api_proto_search_v1_suggestions_proto_msgTypes[0].OneofWrappers = []any{}
	file_api_proto_search_v1_suggestions_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_search_v1_suggestions_proto_rawDesc), len(file_api_proto_search_v1_suggestions_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_search_v1_suggestions_proto_goTypes,
		DependencyIndexes: file_api_proto_search_v1_suggestions_proto_depIdxs,
		MessageInfos:      file_api_proto_search_v1_suggestions_proto_msgTypes,
	}.Build()
	File_api_proto_search_v1_suggestions_proto = out.File
	file_api_proto_search_v1_suggestions_proto_goTypes = nil
	file_api_proto_search_v1_suggestions_proto_depIdxs = nil
}
