// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: pkg/proto/listings/v1/listings.proto

package listingsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Listing represents a marketplace listing
type Listing struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Uuid           string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	UserId         int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	StorefrontId   *int64                 `protobuf:"varint,4,opt,name=storefront_id,json=storefrontId,proto3,oneof" json:"storefront_id,omitempty"`
	Title          string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Description    *string                `protobuf:"bytes,6,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Price          float64                `protobuf:"fixed64,7,opt,name=price,proto3" json:"price,omitempty"`
	Currency       string                 `protobuf:"bytes,8,opt,name=currency,proto3" json:"currency,omitempty"`
	CategoryId     int64                  `protobuf:"varint,9,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Status         string                 `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"`
	Visibility     string                 `protobuf:"bytes,11,opt,name=visibility,proto3" json:"visibility,omitempty"`
	Quantity       int32                  `protobuf:"varint,12,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Sku            *string                `protobuf:"bytes,13,opt,name=sku,proto3,oneof" json:"sku,omitempty"`
	ViewsCount     int32                  `protobuf:"varint,14,opt,name=views_count,json=viewsCount,proto3" json:"views_count,omitempty"`
	FavoritesCount int32                  `protobuf:"varint,15,opt,name=favorites_count,json=favoritesCount,proto3" json:"favorites_count,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,16,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      string                 `protobuf:"bytes,17,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	PublishedAt    *string                `protobuf:"bytes,18,opt,name=published_at,json=publishedAt,proto3,oneof" json:"published_at,omitempty"`
	DeletedAt      *string                `protobuf:"bytes,19,opt,name=deleted_at,json=deletedAt,proto3,oneof" json:"deleted_at,omitempty"`
	IsDeleted      bool                   `protobuf:"varint,20,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
	// Relations
	Images        []*ListingImage     `protobuf:"bytes,21,rep,name=images,proto3" json:"images,omitempty"`
	Attributes    []*ListingAttribute `protobuf:"bytes,22,rep,name=attributes,proto3" json:"attributes,omitempty"`
	Tags          []string            `protobuf:"bytes,23,rep,name=tags,proto3" json:"tags,omitempty"`
	Location      *ListingLocation    `protobuf:"bytes,24,opt,name=location,proto3,oneof" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Listing) Reset() {
	*x = Listing{}
	mi := &file_pkg_proto_listings_v1_listings_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Listing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Listing) ProtoMessage() {}

func (x *Listing) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_listings_v1_listings_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Listing.ProtoReflect.Descriptor instead.
func (*Listing) Descriptor() ([]byte, []int) {
	return file_pkg_proto_listings_v1_listings_proto_rawDescGZIP(), []int{0}
}

func (x *Listing) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Listing) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Listing) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Listing) GetStorefrontId() int64 {
	if x != nil && x.StorefrontId != nil {
		return *x.StorefrontId
	}
	return 0
}

func (x *Listing) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Listing) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Listing) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Listing) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Listing) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *Listing) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Listing) GetVisibility() string {
	if x != nil {
		return x.Visibility
	}
	return ""
}

func (x *Listing) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Listing) GetSku() string {
	if x != nil && x.Sku != nil {
		return *x.Sku
	}
	return ""
}

func (x *Listing) GetViewsCount() int32 {
	if x != nil {
		return x.ViewsCount
	}
	return 0
}

func (x *Listing) GetFavoritesCount() int32 {
	if x != nil {
		return x.FavoritesCount
	}
	return 0
}

func (x *Listing) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Listing) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Listing) GetPublishedAt() string {
	if x != nil && x.PublishedAt != nil {
		return *x.PublishedAt
	}
	return ""
}

func (x *Listing) GetDeletedAt() string {
	if x != nil && x.DeletedAt != nil {
		return *x.DeletedAt
	}
	return ""
}

func (x *Listing) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

func (x *Listing) GetImages() []*ListingImage {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *Listing) GetAttributes() []*ListingAttribute {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *Listing) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Listing) GetLocation() *ListingLocation {
	if x != nil {
		return x.Location
	}
	return nil
}

// ListingImage represents an image associated with a listing
type ListingImage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ListingId     int64                  `protobuf:"varint,2,opt,name=listing_id,json=listingId,proto3" json:"listing_id,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	StoragePath   *string                `protobuf:"bytes,4,opt,name=storage_path,json=storagePath,proto3,oneof" json:"storage_path,omitempty"`
	ThumbnailUrl  *string                `protobuf:"bytes,5,opt,name=thumbnail_url,json=thumbnailUrl,proto3,oneof" json:"thumbnail_url,omitempty"`
	DisplayOrder  int32                  `protobuf:"varint,6,opt,name=display_order,json=displayOrder,proto3" json:"display_order,omitempty"`
	IsPrimary     bool                   `protobuf:"varint,7,opt,name=is_primary,json=isPrimary,proto3" json:"is_primary,omitempty"`
	Width         *int32                 `protobuf:"varint,8,opt,name=width,proto3,oneof" json:"width,omitempty"`
	Height        *int32                 `protobuf:"varint,9,opt,name=height,proto3,oneof" json:"height,omitempty"`
	FileSize      *int64                 `protobuf:"varint,10,opt,name=file_size,json=fileSize,proto3,oneof" json:"file_size,omitempty"`
	MimeType      *string                `protobuf:"bytes,11,opt,name=mime_type,json=mimeType,proto3,oneof" json:"mime_type,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListingImage) Reset() {
	*x = ListingImage{}
	mi := &file_pkg_proto_listings_v1_listings_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListingImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListingImage) ProtoMessage() {}

func (x *ListingImage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_listings_v1_listings_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListingImage.ProtoReflect.Descriptor instead.
func (*ListingImage) Descriptor() ([]byte, []int) {
	return file_pkg_proto_listings_v1_listings_proto_rawDescGZIP(), []int{1}
}

func (x *ListingImage) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ListingImage) GetListingId() int64 {
	if x != nil {
		return x.ListingId
	}
	return 0
}

func (x *ListingImage) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ListingImage) GetStoragePath() string {
	if x != nil && x.StoragePath != nil {
		return *x.StoragePath
	}
	return ""
}

func (x *ListingImage) GetThumbnailUrl() string {
	if x != nil && x.ThumbnailUrl != nil {
		return *x.ThumbnailUrl
	}
	return ""
}

func (x *ListingImage) GetDisplayOrder() int32 {
	if x != nil {
		return x.DisplayOrder
	}
	return 0
}

func (x *ListingImage) GetIsPrimary() bool {
	if x != nil {
		return x.IsPrimary
	}
	return false
}

func (x *ListingImage) GetWidth() int32 {
	if x != nil && x.Width != nil {
		return *x.Width
	}
	return 0
}

func (x *ListingImage) GetHeight() int32 {
	if x != nil && x.Height != nil {
		return *x.Height
	}
	return 0
}

func (x *ListingImage) GetFileSize() int64 {
	if x != nil && x.FileSize != nil {
		return *x.FileSize
	}
	return 0
}

func (x *ListingImage) GetMimeType() string {
	if x != nil && x.MimeType != nil {
		return *x.MimeType
	}
	return ""
}

func (x *ListingImage) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ListingImage) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// ListingAttribute represents flexible key-value attributes
type ListingAttribute struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ListingId      int64                  `protobuf:"varint,2,opt,name=listing_id,json=listingId,proto3" json:"listing_id,omitempty"`
	AttributeKey   string                 `protobuf:"bytes,3,opt,name=attribute_key,json=attributeKey,proto3" json:"attribute_key,omitempty"`
	AttributeValue string                 `protobuf:"bytes,4,opt,name=attribute_value,json=attributeValue,proto3" json:"attribute_value,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListingAttribute) Reset() {
	*x = ListingAttribute{}
	mi := &file_pkg_proto_listings_v1_listings_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListingAttribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListingAttribute) ProtoMessage() {}

func (x *ListingAttribute) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_listings_v1_listings_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListingAttribute.ProtoReflect.Descriptor instead.
func (*ListingAttribute) Descriptor() ([]byte, []int) {
	return file_pkg_proto_listings_v1_listings_proto_rawDescGZIP(), []int{2}
}

func (x *ListingAttribute) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ListingAttribute) GetListingId() int64 {
	if x != nil {
		return x.ListingId
	}
	return 0
}

func (x *ListingAttribute) GetAttributeKey() string {
	if x != nil {
		return x.AttributeKey
	}
	return ""
}

func (x *ListingAttribute) GetAttributeValue() string {
	if x != nil {
		return x.AttributeValue
	}
	return ""
}

func (x *ListingAttribute) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

// ListingLocation represents geographic location
type ListingLocation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ListingId     int64                  `protobuf:"varint,2,opt,name=listing_id,json=listingId,proto3" json:"listing_id,omitempty"`
	Country       *string                `protobuf:"bytes,3,opt,name=country,proto3,oneof" json:"country,omitempty"`
	City          *string                `protobuf:"bytes,4,opt,name=city,proto3,oneof" json:"city,omitempty"`
	PostalCode    *string                `protobuf:"bytes,5,opt,name=postal_code,json=postalCode,proto3,oneof" json:"postal_code,omitempty"`
	AddressLine1  *string                `protobuf:"bytes,6,opt,name=address_line1,json=addressLine1,proto3,oneof" json:"address_line1,omitempty"`
	AddressLine2  *string                `protobuf:"bytes,7,opt,name=address_line2,json=addressLine2,proto3,oneof" json:"address_line2,omitempty"`
	Latitude      *float64               `protobuf:"fixed64,8,opt,name=latitude,proto3,oneof" json:"latitude,omitempty"`
	Longitude     *float64               `protobuf:"fixed64,9,opt,name=longitude,proto3,oneof" json:"longitude,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListingLocation) Reset() {
	*x = ListingLocation{}
	mi := &file_pkg_proto_listings_v1_listings_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListingLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListingLocation) ProtoMessage() {}

func (x *ListingLocation) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_listings_v1_listings_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListingLocation.ProtoReflect.Descriptor instead.
func (*ListingLocation) Descriptor() ([]byte, []int) {
	return file_pkg_proto_listings_v1_listings_proto_rawDescGZIP(), []int{3}
}

func (x *ListingLocation) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ListingLocation) GetListingId() int64 {
	if x != nil {
		return x.ListingId
	}
	return 0
}

func (x *ListingLocation) GetCountry() string {
	if x != nil && x.Country != nil {
		return *x.Country
	}
	return ""
}

func (x *ListingLocation) GetCity() string {
	if x != nil && x.City != nil {
		return *x.City
	}
	return ""
}

func (x *ListingLocation) GetPostalCode() string {
	if x != nil && x.PostalCode != nil {
		return *x.PostalCode
	}
	return ""
}

func (x *ListingLocation) GetAddressLine1() string {
	if x != nil && x.AddressLine1 != nil {
		return *x.AddressLine1
	}
	return ""
}

func (x *ListingLocation) GetAddressLine2() string {
	if x != nil && x.AddressLine2 != nil {
		return *x.AddressLine2
	}
	return ""
}

func (x *ListingLocation) GetLatitude() float64 {
	if x != nil && x.Latitude != nil {
		return *x.Latitude
	}
	return 0
}

func (x *ListingLocation) GetLongitude() float64 {
	if x != nil && x.Longitude != nil {
		return *x.Longitude
	}
	return 0
}

func (x *ListingLocation) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ListingLocation) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// GetListing messages
type GetListingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListingRequest) Reset() {
	*x = GetListingRequest{}
	mi := &file_pkg_proto_listings_v1_listings_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListingRequest) ProtoMessage() {}

func (x *GetListingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_listings_v1_listings_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListingRequest.ProtoReflect.Descriptor instead.
func (*GetListingRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_listings_v1_listings_proto_rawDescGZIP(), []int{4}
}

func (x *GetListingRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetListingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Listing       *Listing               `protobuf:"bytes,1,opt,name=listing,proto3" json:"listing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListingResponse) Reset() {
	*x = GetListingResponse{}
	mi := &file_pkg_proto_listings_v1_listings_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListingResponse) ProtoMessage() {}

func (x *GetListingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_listings_v1_listings_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListingResponse.ProtoReflect.Descriptor instead.
func (*GetListingResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_listings_v1_listings_proto_rawDescGZIP(), []int{5}
}

func (x *GetListingResponse) GetListing() *Listing {
	if x != nil {
		return x.Listing
	}
	return nil
}

// CreateListing messages
type CreateListingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	StorefrontId  *int64                 `protobuf:"varint,2,opt,name=storefront_id,json=storefrontId,proto3,oneof" json:"storefront_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   *string                `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Price         float64                `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	Currency      string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	CategoryId    int64                  `protobuf:"varint,7,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,8,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Sku           *string                `protobuf:"bytes,9,opt,name=sku,proto3,oneof" json:"sku,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateListingRequest) Reset() {
	*x = CreateListingRequest{}
	mi := &file_pkg_proto_listings_v1_listings_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateListingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateListingRequest) ProtoMessage() {}

func (x *CreateListingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_listings_v1_listings_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateListingRequest.ProtoReflect.Descriptor instead.
func (*CreateListingRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_listings_v1_listings_proto_rawDescGZIP(), []int{6}
}

func (x *CreateListingRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateListingRequest) GetStorefrontId() int64 {
	if x != nil && x.StorefrontId != nil {
		return *x.StorefrontId
	}
	return 0
}

func (x *CreateListingRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateListingRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *CreateListingRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateListingRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreateListingRequest) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *CreateListingRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CreateListingRequest) GetSku() string {
	if x != nil && x.Sku != nil {
		return *x.Sku
	}
	return ""
}

type CreateListingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Listing       *Listing               `protobuf:"bytes,1,opt,name=listing,proto3" json:"listing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateListingResponse) Reset() {
	*x = CreateListingResponse{}
	mi := &file_pkg_proto_listings_v1_listings_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateListingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateListingResponse) ProtoMessage() {}

func (x *CreateListingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_listings_v1_listings_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateListingResponse.ProtoReflect.Descriptor instead.
func (*CreateListingResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_listings_v1_listings_proto_rawDescGZIP(), []int{7}
}

func (x *CreateListingResponse) GetListing() *Listing {
	if x != nil {
		return x.Listing
	}
	return nil
}

// UpdateListing messages
type UpdateListingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // Required for ownership check
	Title         *string                `protobuf:"bytes,3,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Description   *string                `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Price         *float64               `protobuf:"fixed64,5,opt,name=price,proto3,oneof" json:"price,omitempty"`
	Quantity      *int32                 `protobuf:"varint,6,opt,name=quantity,proto3,oneof" json:"quantity,omitempty"`
	Status        *string                `protobuf:"bytes,7,opt,name=status,proto3,oneof" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateListingRequest) Reset() {
	*x = UpdateListingRequest{}
	mi := &file_pkg_proto_listings_v1_listings_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateListingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateListingRequest) ProtoMessage() {}

func (x *UpdateListingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_listings_v1_listings_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateListingRequest.ProtoReflect.Descriptor instead.
func (*UpdateListingRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_listings_v1_listings_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateListingRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateListingRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateListingRequest) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *UpdateListingRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateListingRequest) GetPrice() float64 {
	if x != nil && x.Price != nil {
		return *x.Price
	}
	return 0
}

func (x *UpdateListingRequest) GetQuantity() int32 {
	if x != nil && x.Quantity != nil {
		return *x.Quantity
	}
	return 0
}

func (x *UpdateListingRequest) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

type UpdateListingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Listing       *Listing               `protobuf:"bytes,1,opt,name=listing,proto3" json:"listing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateListingResponse) Reset() {
	*x = UpdateListingResponse{}
	mi := &file_pkg_proto_listings_v1_listings_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateListingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateListingResponse) ProtoMessage() {}

func (x *UpdateListingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_listings_v1_listings_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateListingResponse.ProtoReflect.Descriptor instead.
func (*UpdateListingResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_listings_v1_listings_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateListingResponse) GetListing() *Listing {
	if x != nil {
		return x.Listing
	}
	return nil
}

// DeleteListing messages
type DeleteListingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // Required for ownership check
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteListingRequest) Reset() {
	*x = DeleteListingRequest{}
	mi := &file_pkg_proto_listings_v1_listings_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteListingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteListingRequest) ProtoMessage() {}

func (x *DeleteListingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_listings_v1_listings_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteListingRequest.ProtoReflect.Descriptor instead.
func (*DeleteListingRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_listings_v1_listings_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteListingRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DeleteListingRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type DeleteListingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteListingResponse) Reset() {
	*x = DeleteListingResponse{}
	mi := &file_pkg_proto_listings_v1_listings_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteListingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteListingResponse) ProtoMessage() {}

func (x *DeleteListingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_listings_v1_listings_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteListingResponse.ProtoReflect.Descriptor instead.
func (*DeleteListingResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_listings_v1_listings_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteListingResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// SearchListings messages
type SearchListingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	CategoryId    *int64                 `protobuf:"varint,2,opt,name=category_id,json=categoryId,proto3,oneof" json:"category_id,omitempty"`
	MinPrice      *float64               `protobuf:"fixed64,3,opt,name=min_price,json=minPrice,proto3,oneof" json:"min_price,omitempty"`
	MaxPrice      *float64               `protobuf:"fixed64,4,opt,name=max_price,json=maxPrice,proto3,oneof" json:"max_price,omitempty"`
	Limit         int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,6,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchListingsRequest) Reset() {
	*x = SearchListingsRequest{}
	mi := &file_pkg_proto_listings_v1_listings_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchListingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchListingsRequest) ProtoMessage() {}

func (x *SearchListingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_listings_v1_listings_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchListingsRequest.ProtoReflect.Descriptor instead.
func (*SearchListingsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_listings_v1_listings_proto_rawDescGZIP(), []int{12}
}

func (x *SearchListingsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchListingsRequest) GetCategoryId() int64 {
	if x != nil && x.CategoryId != nil {
		return *x.CategoryId
	}
	return 0
}

func (x *SearchListingsRequest) GetMinPrice() float64 {
	if x != nil && x.MinPrice != nil {
		return *x.MinPrice
	}
	return 0
}

func (x *SearchListingsRequest) GetMaxPrice() float64 {
	if x != nil && x.MaxPrice != nil {
		return *x.MaxPrice
	}
	return 0
}

func (x *SearchListingsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchListingsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type SearchListingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Listings      []*Listing             `protobuf:"bytes,1,rep,name=listings,proto3" json:"listings,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchListingsResponse) Reset() {
	*x = SearchListingsResponse{}
	mi := &file_pkg_proto_listings_v1_listings_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchListingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchListingsResponse) ProtoMessage() {}

func (x *SearchListingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_listings_v1_listings_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchListingsResponse.ProtoReflect.Descriptor instead.
func (*SearchListingsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_listings_v1_listings_proto_rawDescGZIP(), []int{13}
}

func (x *SearchListingsResponse) GetListings() []*Listing {
	if x != nil {
		return x.Listings
	}
	return nil
}

func (x *SearchListingsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// ListListings messages
type ListListingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        *int64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3,oneof" json:"user_id,omitempty"`
	StorefrontId  *int64                 `protobuf:"varint,2,opt,name=storefront_id,json=storefrontId,proto3,oneof" json:"storefront_id,omitempty"`
	CategoryId    *int64                 `protobuf:"varint,3,opt,name=category_id,json=categoryId,proto3,oneof" json:"category_id,omitempty"`
	Status        *string                `protobuf:"bytes,4,opt,name=status,proto3,oneof" json:"status,omitempty"`
	MinPrice      *float64               `protobuf:"fixed64,5,opt,name=min_price,json=minPrice,proto3,oneof" json:"min_price,omitempty"`
	MaxPrice      *float64               `protobuf:"fixed64,6,opt,name=max_price,json=maxPrice,proto3,oneof" json:"max_price,omitempty"`
	Limit         int32                  `protobuf:"varint,7,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,8,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListListingsRequest) Reset() {
	*x = ListListingsRequest{}
	mi := &file_pkg_proto_listings_v1_listings_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListListingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListListingsRequest) ProtoMessage() {}

func (x *ListListingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_listings_v1_listings_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListListingsRequest.ProtoReflect.Descriptor instead.
func (*ListListingsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_listings_v1_listings_proto_rawDescGZIP(), []int{14}
}

func (x *ListListingsRequest) GetUserId() int64 {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return 0
}

func (x *ListListingsRequest) GetStorefrontId() int64 {
	if x != nil && x.StorefrontId != nil {
		return *x.StorefrontId
	}
	return 0
}

func (x *ListListingsRequest) GetCategoryId() int64 {
	if x != nil && x.CategoryId != nil {
		return *x.CategoryId
	}
	return 0
}

func (x *ListListingsRequest) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

func (x *ListListingsRequest) GetMinPrice() float64 {
	if x != nil && x.MinPrice != nil {
		return *x.MinPrice
	}
	return 0
}

func (x *ListListingsRequest) GetMaxPrice() float64 {
	if x != nil && x.MaxPrice != nil {
		return *x.MaxPrice
	}
	return 0
}

func (x *ListListingsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListListingsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListListingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Listings      []*Listing             `protobuf:"bytes,1,rep,name=listings,proto3" json:"listings,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListListingsResponse) Reset() {
	*x = ListListingsResponse{}
	mi := &file_pkg_proto_listings_v1_listings_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListListingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListListingsResponse) ProtoMessage() {}

func (x *ListListingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_listings_v1_listings_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListListingsResponse.ProtoReflect.Descriptor instead.
func (*ListListingsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_listings_v1_listings_proto_rawDescGZIP(), []int{15}
}

func (x *ListListingsResponse) GetListings() []*Listing {
	if x != nil {
		return x.Listings
	}
	return nil
}

func (x *ListListingsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_pkg_proto_listings_v1_listings_proto protoreflect.FileDescriptor

const file_pkg_proto_listings_v1_listings_proto_rawDesc = "" +
	"\n" +
	"$pkg/proto/listings/v1/listings.proto\x12\vlistings.v1\"\xfa\x06\n" +
	"\aListing\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12(\n" +
	"\rstorefront_id\x18\x04 \x01(\x03H\x00R\fstorefrontId\x88\x01\x01\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12%\n" +
	"\vdescription\x18\x06 \x01(\tH\x01R\vdescription\x88\x01\x01\x12\x14\n" +
	"\x05price\x18\a \x01(\x01R\x05price\x12\x1a\n" +
	"\bcurrency\x18\b \x01(\tR\bcurrency\x12\x1f\n" +
	"\vcategory_id\x18\t \x01(\x03R\n" +
	"categoryId\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\tR\x06status\x12\x1e\n" +
	"\n" +
	"visibility\x18\v \x01(\tR\n" +
	"visibility\x12\x1a\n" +
	"\bquantity\x18\f \x01(\x05R\bquantity\x12\x15\n" +
	"\x03sku\x18\r \x01(\tH\x02R\x03sku\x88\x01\x01\x12\x1f\n" +
	"\vviews_count\x18\x0e \x01(\x05R\n" +
	"viewsCount\x12'\n" +
	"\x0ffavorites_count\x18\x0f \x01(\x05R\x0efavoritesCount\x12\x1d\n" +
	"\n" +
	"created_at\x18\x10 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x11 \x01(\tR\tupdatedAt\x12&\n" +
	"\fpublished_at\x18\x12 \x01(\tH\x03R\vpublishedAt\x88\x01\x01\x12\"\n" +
	"\n" +
	"deleted_at\x18\x13 \x01(\tH\x04R\tdeletedAt\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"is_deleted\x18\x14 \x01(\bR\tisDeleted\x121\n" +
	"\x06images\x18\x15 \x03(\v2\x19.listings.v1.ListingImageR\x06images\x12=\n" +
	"\n" +
	"attributes\x18\x16 \x03(\v2\x1d.listings.v1.ListingAttributeR\n" +
	"attributes\x12\x12\n" +
	"\x04tags\x18\x17 \x03(\tR\x04tags\x12=\n" +
	"\blocation\x18\x18 \x01(\v2\x1c.listings.v1.ListingLocationH\x05R\blocation\x88\x01\x01B\x10\n" +
	"\x0e_storefront_idB\x0e\n" +
	"\f_descriptionB\x06\n" +
	"\x04_skuB\x0f\n" +
	"\r_published_atB\r\n" +
	"\v_deleted_atB\v\n" +
	"\t_location\"\xf3\x03\n" +
	"\fListingImage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"listing_id\x18\x02 \x01(\x03R\tlistingId\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12&\n" +
	"\fstorage_path\x18\x04 \x01(\tH\x00R\vstoragePath\x88\x01\x01\x12(\n" +
	"\rthumbnail_url\x18\x05 \x01(\tH\x01R\fthumbnailUrl\x88\x01\x01\x12#\n" +
	"\rdisplay_order\x18\x06 \x01(\x05R\fdisplayOrder\x12\x1d\n" +
	"\n" +
	"is_primary\x18\a \x01(\bR\tisPrimary\x12\x19\n" +
	"\x05width\x18\b \x01(\x05H\x02R\x05width\x88\x01\x01\x12\x1b\n" +
	"\x06height\x18\t \x01(\x05H\x03R\x06height\x88\x01\x01\x12 \n" +
	"\tfile_size\x18\n" +
	" \x01(\x03H\x04R\bfileSize\x88\x01\x01\x12 \n" +
	"\tmime_type\x18\v \x01(\tH\x05R\bmimeType\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"created_at\x18\f \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\r \x01(\tR\tupdatedAtB\x0f\n" +
	"\r_storage_pathB\x10\n" +
	"\x0e_thumbnail_urlB\b\n" +
	"\x06_widthB\t\n" +
	"\a_heightB\f\n" +
	"\n" +
	"_file_sizeB\f\n" +
	"\n" +
	"_mime_type\"\xae\x01\n" +
	"\x10ListingAttribute\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"listing_id\x18\x02 \x01(\x03R\tlistingId\x12#\n" +
	"\rattribute_key\x18\x03 \x01(\tR\fattributeKey\x12'\n" +
	"\x0fattribute_value\x18\x04 \x01(\tR\x0eattributeValue\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\"\xd8\x03\n" +
	"\x0fListingLocation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"listing_id\x18\x02 \x01(\x03R\tlistingId\x12\x1d\n" +
	"\acountry\x18\x03 \x01(\tH\x00R\acountry\x88\x01\x01\x12\x17\n" +
	"\x04city\x18\x04 \x01(\tH\x01R\x04city\x88\x01\x01\x12$\n" +
	"\vpostal_code\x18\x05 \x01(\tH\x02R\n" +
	"postalCode\x88\x01\x01\x12(\n" +
	"\raddress_line1\x18\x06 \x01(\tH\x03R\faddressLine1\x88\x01\x01\x12(\n" +
	"\raddress_line2\x18\a \x01(\tH\x04R\faddressLine2\x88\x01\x01\x12\x1f\n" +
	"\blatitude\x18\b \x01(\x01H\x05R\blatitude\x88\x01\x01\x12!\n" +
	"\tlongitude\x18\t \x01(\x01H\x06R\tlongitude\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\v \x01(\tR\tupdatedAtB\n" +
	"\n" +
	"\b_countryB\a\n" +
	"\x05_cityB\x0e\n" +
	"\f_postal_codeB\x10\n" +
	"\x0e_address_line1B\x10\n" +
	"\x0e_address_line2B\v\n" +
	"\t_latitudeB\f\n" +
	"\n" +
	"_longitude\"#\n" +
	"\x11GetListingRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"D\n" +
	"\x12GetListingResponse\x12.\n" +
	"\alisting\x18\x01 \x01(\v2\x14.listings.v1.ListingR\alisting\"\xc6\x02\n" +
	"\x14CreateListingRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12(\n" +
	"\rstorefront_id\x18\x02 \x01(\x03H\x00R\fstorefrontId\x88\x01\x01\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12%\n" +
	"\vdescription\x18\x04 \x01(\tH\x01R\vdescription\x88\x01\x01\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x12\x1f\n" +
	"\vcategory_id\x18\a \x01(\x03R\n" +
	"categoryId\x12\x1a\n" +
	"\bquantity\x18\b \x01(\x05R\bquantity\x12\x15\n" +
	"\x03sku\x18\t \x01(\tH\x02R\x03sku\x88\x01\x01B\x10\n" +
	"\x0e_storefront_idB\x0e\n" +
	"\f_descriptionB\x06\n" +
	"\x04_sku\"G\n" +
	"\x15CreateListingResponse\x12.\n" +
	"\alisting\x18\x01 \x01(\v2\x14.listings.v1.ListingR\alisting\"\x96\x02\n" +
	"\x14UpdateListingRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x19\n" +
	"\x05title\x18\x03 \x01(\tH\x00R\x05title\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x04 \x01(\tH\x01R\vdescription\x88\x01\x01\x12\x19\n" +
	"\x05price\x18\x05 \x01(\x01H\x02R\x05price\x88\x01\x01\x12\x1f\n" +
	"\bquantity\x18\x06 \x01(\x05H\x03R\bquantity\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\a \x01(\tH\x04R\x06status\x88\x01\x01B\b\n" +
	"\x06_titleB\x0e\n" +
	"\f_descriptionB\b\n" +
	"\x06_priceB\v\n" +
	"\t_quantityB\t\n" +
	"\a_status\"G\n" +
	"\x15UpdateListingResponse\x12.\n" +
	"\alisting\x18\x01 \x01(\v2\x14.listings.v1.ListingR\alisting\"?\n" +
	"\x14DeleteListingRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"1\n" +
	"\x15DeleteListingResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xf1\x01\n" +
	"\x15SearchListingsRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12$\n" +
	"\vcategory_id\x18\x02 \x01(\x03H\x00R\n" +
	"categoryId\x88\x01\x01\x12 \n" +
	"\tmin_price\x18\x03 \x01(\x01H\x01R\bminPrice\x88\x01\x01\x12 \n" +
	"\tmax_price\x18\x04 \x01(\x01H\x02R\bmaxPrice\x88\x01\x01\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x06 \x01(\x05R\x06offsetB\x0e\n" +
	"\f_category_idB\f\n" +
	"\n" +
	"_min_priceB\f\n" +
	"\n" +
	"_max_price\"`\n" +
	"\x16SearchListingsResponse\x120\n" +
	"\blistings\x18\x01 \x03(\v2\x14.listings.v1.ListingR\blistings\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\xe7\x02\n" +
	"\x13ListListingsRequest\x12\x1c\n" +
	"\auser_id\x18\x01 \x01(\x03H\x00R\x06userId\x88\x01\x01\x12(\n" +
	"\rstorefront_id\x18\x02 \x01(\x03H\x01R\fstorefrontId\x88\x01\x01\x12$\n" +
	"\vcategory_id\x18\x03 \x01(\x03H\x02R\n" +
	"categoryId\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\x04 \x01(\tH\x03R\x06status\x88\x01\x01\x12 \n" +
	"\tmin_price\x18\x05 \x01(\x01H\x04R\bminPrice\x88\x01\x01\x12 \n" +
	"\tmax_price\x18\x06 \x01(\x01H\x05R\bmaxPrice\x88\x01\x01\x12\x14\n" +
	"\x05limit\x18\a \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\b \x01(\x05R\x06offsetB\n" +
	"\n" +
	"\b_user_idB\x10\n" +
	"\x0e_storefront_idB\x0e\n" +
	"\f_category_idB\t\n" +
	"\a_statusB\f\n" +
	"\n" +
	"_min_priceB\f\n" +
	"\n" +
	"_max_price\"^\n" +
	"\x14ListListingsResponse\x120\n" +
	"\blistings\x18\x01 \x03(\v2\x14.listings.v1.ListingR\blistings\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total2\x98\x04\n" +
	"\x0fListingsService\x12M\n" +
	"\n" +
	"GetListing\x12\x1e.listings.v1.GetListingRequest\x1a\x1f.listings.v1.GetListingResponse\x12V\n" +
	"\rCreateListing\x12!.listings.v1.CreateListingRequest\x1a\".listings.v1.CreateListingResponse\x12V\n" +
	"\rUpdateListing\x12!.listings.v1.UpdateListingRequest\x1a\".listings.v1.UpdateListingResponse\x12V\n" +
	"\rDeleteListing\x12!.listings.v1.DeleteListingRequest\x1a\".listings.v1.DeleteListingResponse\x12Y\n" +
	"\x0eSearchListings\x12\".listings.v1.SearchListingsRequest\x1a#.listings.v1.SearchListingsResponse\x12S\n" +
	"\fListListings\x12 .listings.v1.ListListingsRequest\x1a!.listings.v1.ListListingsResponseBCZAgithub.com/sveturs/svetu/backend/pkg/proto/listings/v1;listingsv1b\x06proto3"

var (
	file_pkg_proto_listings_v1_listings_proto_rawDescOnce sync.Once
	file_pkg_proto_listings_v1_listings_proto_rawDescData []byte
)

func file_pkg_proto_listings_v1_listings_proto_rawDescGZIP() []byte {
	file_pkg_proto_listings_v1_listings_proto_rawDescOnce.Do(func() {
		file_pkg_proto_listings_v1_listings_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_listings_v1_listings_proto_rawDesc), len(file_pkg_proto_listings_v1_listings_proto_rawDesc)))
	})
	return file_pkg_proto_listings_v1_listings_proto_rawDescData
}

var file_pkg_proto_listings_v1_listings_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_pkg_proto_listings_v1_listings_proto_goTypes = []any{
	(*Listing)(nil),                // 0: listings.v1.Listing
	(*ListingImage)(nil),           // 1: listings.v1.ListingImage
	(*ListingAttribute)(nil),       // 2: listings.v1.ListingAttribute
	(*ListingLocation)(nil),        // 3: listings.v1.ListingLocation
	(*GetListingRequest)(nil),      // 4: listings.v1.GetListingRequest
	(*GetListingResponse)(nil),     // 5: listings.v1.GetListingResponse
	(*CreateListingRequest)(nil),   // 6: listings.v1.CreateListingRequest
	(*CreateListingResponse)(nil),  // 7: listings.v1.CreateListingResponse
	(*UpdateListingRequest)(nil),   // 8: listings.v1.UpdateListingRequest
	(*UpdateListingResponse)(nil),  // 9: listings.v1.UpdateListingResponse
	(*DeleteListingRequest)(nil),   // 10: listings.v1.DeleteListingRequest
	(*DeleteListingResponse)(nil),  // 11: listings.v1.DeleteListingResponse
	(*SearchListingsRequest)(nil),  // 12: listings.v1.SearchListingsRequest
	(*SearchListingsResponse)(nil), // 13: listings.v1.SearchListingsResponse
	(*ListListingsRequest)(nil),    // 14: listings.v1.ListListingsRequest
	(*ListListingsResponse)(nil),   // 15: listings.v1.ListListingsResponse
}
var file_pkg_proto_listings_v1_listings_proto_depIdxs = []int32{
	1,  // 0: listings.v1.Listing.images:type_name -> listings.v1.ListingImage
	2,  // 1: listings.v1.Listing.attributes:type_name -> listings.v1.ListingAttribute
	3,  // 2: listings.v1.Listing.location:type_name -> listings.v1.ListingLocation
	0,  // 3: listings.v1.GetListingResponse.listing:type_name -> listings.v1.Listing
	0,  // 4: listings.v1.CreateListingResponse.listing:type_name -> listings.v1.Listing
	0,  // 5: listings.v1.UpdateListingResponse.listing:type_name -> listings.v1.Listing
	0,  // 6: listings.v1.SearchListingsResponse.listings:type_name -> listings.v1.Listing
	0,  // 7: listings.v1.ListListingsResponse.listings:type_name -> listings.v1.Listing
	4,  // 8: listings.v1.ListingsService.GetListing:input_type -> listings.v1.GetListingRequest
	6,  // 9: listings.v1.ListingsService.CreateListing:input_type -> listings.v1.CreateListingRequest
	8,  // 10: listings.v1.ListingsService.UpdateListing:input_type -> listings.v1.UpdateListingRequest
	10, // 11: listings.v1.ListingsService.DeleteListing:input_type -> listings.v1.DeleteListingRequest
	12, // 12: listings.v1.ListingsService.SearchListings:input_type -> listings.v1.SearchListingsRequest
	14, // 13: listings.v1.ListingsService.ListListings:input_type -> listings.v1.ListListingsRequest
	5,  // 14: listings.v1.ListingsService.GetListing:output_type -> listings.v1.GetListingResponse
	7,  // 15: listings.v1.ListingsService.CreateListing:output_type -> listings.v1.CreateListingResponse
	9,  // 16: listings.v1.ListingsService.UpdateListing:output_type -> listings.v1.UpdateListingResponse
	11, // 17: listings.v1.ListingsService.DeleteListing:output_type -> listings.v1.DeleteListingResponse
	13, // 18: listings.v1.ListingsService.SearchListings:output_type -> listings.v1.SearchListingsResponse
	15, // 19: listings.v1.ListingsService.ListListings:output_type -> listings.v1.ListListingsResponse
	14, // [14:20] is the sub-list for method output_type
	8,  // [8:14] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_pkg_proto_listings_v1_listings_proto_init() }
func file_pkg_proto_listings_v1_listings_proto_init() {
	if File_pkg_proto_listings_v1_listings_proto != nil {
		return
	}
	file_pkg_proto_listings_v1_listings_proto_msgTypes[0].OneofWrappers = []any{}
	file_pkg_proto_listings_v1_listings_proto_msgTypes[1].OneofWrappers = []any{}
	file_pkg_proto_listings_v1_listings_proto_msgTypes[3].OneofWrappers = []any{}
	file_pkg_proto_listings_v1_listings_proto_msgTypes[6].OneofWrappers = []any{}
	file_pkg_proto_listings_v1_listings_proto_msgTypes[8].OneofWrappers = []any{}
	file_pkg_proto_listings_v1_listings_proto_msgTypes[12].OneofWrappers = []any{}
	file_pkg_proto_listings_v1_listings_proto_msgTypes[14].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_listings_v1_listings_proto_rawDesc), len(file_pkg_proto_listings_v1_listings_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_listings_v1_listings_proto_goTypes,
		DependencyIndexes: file_pkg_proto_listings_v1_listings_proto_depIdxs,
		MessageInfos:      file_pkg_proto_listings_v1_listings_proto_msgTypes,
	}.Build()
	File_pkg_proto_listings_v1_listings_proto = out.File
	file_pkg_proto_listings_v1_listings_proto_goTypes = nil
	file_pkg_proto_listings_v1_listings_proto_depIdxs = nil
}
