#!/usr/bin/env bash

#######################################
# Traffic Split Script
# Manages Blue-Green traffic distribution via Nginx
#
# Usage: ./traffic-split.sh --green-weight WEIGHT [--dry-run]
#
# Examples:
#   ./traffic-split.sh --green-weight 0      # 100% Blue
#   ./traffic-split.sh --green-weight 50     # 50/50 split
#   ./traffic-split.sh --green-weight 100    # 100% Green
#
# Exit codes:
#   0 - Success
#   1 - Failed
#######################################

set -Eeuo pipefail

# Script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Import configuration
if [[ -f "${SCRIPT_DIR}/.env.deploy" ]]; then
    set -a
    source "${SCRIPT_DIR}/.env.deploy"
    set +a
else
    echo "ERROR: .env.deploy not found"
    exit 1
fi

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Flags
DRY_RUN=false
GREEN_WEIGHT=""
BLUE_WEIGHT=""

#######################################
# Logging functions
#######################################

log_info() {
    echo -e "${BLUE}[INFO]${NC} $*"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $*"
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $*"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $*" >&2
}

#######################################
# Parse arguments
#######################################

parse_args() {
    while [[ $# -gt 0 ]]; do
        case $1 in
            --green-weight)
                GREEN_WEIGHT="$2"
                shift 2
                ;;
            --dry-run)
                DRY_RUN=true
                log_warning "DRY RUN MODE - No actual changes will be made"
                shift
                ;;
            *)
                log_error "Unknown option: $1"
                echo "Usage: $0 --green-weight WEIGHT [--dry-run]"
                exit 1
                ;;
        esac
    done

    # Validate green weight
    if [[ -z "${GREEN_WEIGHT}" ]]; then
        log_error "--green-weight is required"
        exit 1
    fi

    if ! [[ "${GREEN_WEIGHT}" =~ ^[0-9]+$ ]] || [[ "${GREEN_WEIGHT}" -lt 0 ]] || [[ "${GREEN_WEIGHT}" -gt 100 ]]; then
        log_error "Green weight must be an integer between 0 and 100"
        exit 1
    fi

    # Calculate blue weight
    BLUE_WEIGHT=$((100 - GREEN_WEIGHT))
}

#######################################
# Generate Nginx upstream configuration
#######################################

generate_nginx_config() {
    log_info "Generating Nginx configuration (Blue: ${BLUE_WEIGHT}%, Green: ${GREEN_WEIGHT}%)..."

    local config_content=$(cat <<EOF
# Auto-generated by traffic-split.sh
# Blue-Green deployment configuration
# Generated at: $(date +'%Y-%m-%d %H:%M:%S')

upstream listings_backend {
    # Blue instance (current stable)
    server ${PROD_HOST}:${BLUE_PORT} weight=${BLUE_WEIGHT} max_fails=3 fail_timeout=30s;

    # Green instance (new version)
    server ${PROD_HOST}:${GREEN_PORT} weight=${GREEN_WEIGHT} max_fails=3 fail_timeout=30s;

    # Load balancing method
    least_conn;

    # Keepalive connections
    keepalive 32;
}

server {
    listen 80;
    server_name ${PROD_DOMAIN:-listings.example.com};

    # Request ID for tracing
    add_header X-Request-ID \$request_id always;

    # Deployment info headers (for monitoring)
    add_header X-Blue-Weight ${BLUE_WEIGHT} always;
    add_header X-Green-Weight ${GREEN_WEIGHT} always;

    # Health check endpoint (bypass load balancer)
    location /health {
        proxy_pass http://127.0.0.1:${BLUE_PORT}/health;
        access_log off;
    }

    # Main application
    location / {
        proxy_pass http://listings_backend;
        proxy_http_version 1.1;

        # Headers
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header X-Request-ID \$request_id;

        # Keepalive
        proxy_set_header Connection "";

        # Timeouts
        proxy_connect_timeout 10s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;

        # Retry logic
        proxy_next_upstream error timeout http_502 http_503 http_504;
        proxy_next_upstream_tries 2;
    }

    # Metrics endpoint
    location /metrics {
        proxy_pass http://listings_backend/metrics;
        allow 127.0.0.1;
        deny all;
    }
}
EOF
)

    echo "${config_content}"
}

#######################################
# Update Nginx configuration
#######################################

update_nginx_config() {
    log_info "Updating Nginx configuration on ${PROD_HOST}..."

    local config=$(generate_nginx_config)

    if [[ "${DRY_RUN}" == "true" ]]; then
        log_info "[DRY RUN] Would update Nginx config:"
        echo "${config}"
        return 0
    fi

    # Upload new config
    echo "${config}" | ssh "${PROD_USER}@${PROD_HOST}" \
        "sudo tee ${NGINX_CONFIG_PATH:-/etc/nginx/sites-available/listings} > /dev/null"

    if [[ $? -ne 0 ]]; then
        log_error "Failed to update Nginx configuration"
        exit 1
    fi

    log_success "Nginx configuration updated"
}

#######################################
# Test Nginx configuration
#######################################

test_nginx_config() {
    log_info "Testing Nginx configuration..."

    if [[ "${DRY_RUN}" == "true" ]]; then
        log_info "[DRY RUN] Would test Nginx config with: sudo nginx -t"
        return 0
    fi

    ssh "${PROD_USER}@${PROD_HOST}" "sudo nginx -t" 2>&1

    if [[ $? -ne 0 ]]; then
        log_error "Nginx configuration test failed"
        log_error "Configuration has syntax errors and was NOT applied"
        exit 1
    fi

    log_success "Nginx configuration is valid"
}

#######################################
# Reload Nginx
#######################################

reload_nginx() {
    log_info "Reloading Nginx (graceful reload, no downtime)..."

    if [[ "${DRY_RUN}" == "true" ]]; then
        log_info "[DRY RUN] Would reload Nginx with: sudo systemctl reload nginx"
        return 0
    fi

    ssh "${PROD_USER}@${PROD_HOST}" "sudo systemctl reload nginx"

    if [[ $? -ne 0 ]]; then
        log_error "Failed to reload Nginx"
        exit 1
    fi

    # Wait for reload to take effect
    sleep 2

    log_success "Nginx reloaded successfully"
}

#######################################
# Verify traffic distribution
#######################################

verify_traffic_distribution() {
    log_info "Verifying traffic distribution..."

    if [[ "${DRY_RUN}" == "true" ]]; then
        log_info "[DRY RUN] Would verify traffic distribution"
        return 0
    fi

    # Make 10 requests and check distribution
    local blue_count=0
    local green_count=0

    for i in {1..10}; do
        local response=$(curl -s -H "Host: ${PROD_DOMAIN}" "http://${PROD_HOST}/" -w "%{http_code}" -o /dev/null 2>/dev/null)

        if [[ "${response}" == "200" ]]; then
            # Try to determine which backend handled the request
            # This would require backend to return a header like X-Instance: blue/green
            # For now, we just count successful responses
            ((blue_count++)) || true
        fi

        sleep 0.1
    done

    log_info "Made 10 test requests, all responded successfully"
}

#######################################
# Monitor traffic
#######################################

monitor_traffic() {
    log_info "Traffic distribution set to Blue: ${BLUE_WEIGHT}%, Green: ${GREEN_WEIGHT}%"
    log_info ""
    log_info "Monitor traffic with:"
    log_info "  - Nginx access logs: sudo tail -f /var/log/nginx/access.log"
    log_info "  - Blue logs: tail -f ${PROD_DIR}/logs/blue.log"
    log_info "  - Green logs: tail -f ${PROD_DIR}/logs/green.log"
    log_info ""
    log_info "Check response headers:"
    log_info "  curl -I http://${PROD_HOST}/ | grep 'X-.*-Weight'"
}

#######################################
# Rollback on failure
#######################################

rollback_on_failure() {
    log_error "Traffic split failed, attempting to restore previous configuration..."

    if [[ -f "/tmp/nginx_backup.conf" ]]; then
        ssh "${PROD_USER}@${PROD_HOST}" \
            "sudo cp /tmp/nginx_backup.conf ${NGINX_CONFIG_PATH:-/etc/nginx/sites-available/listings} && sudo systemctl reload nginx"

        log_warning "Previous configuration restored"
    else
        log_error "No backup configuration found"
    fi

    exit 1
}

trap rollback_on_failure ERR

#######################################
# Main function
#######################################

main() {
    parse_args "$@"

    log_info "========================================="
    log_info "Traffic Split Configuration"
    log_info "========================================="
    log_info "Blue Weight:  ${BLUE_WEIGHT}%"
    log_info "Green Weight: ${GREEN_WEIGHT}%"
    log_info "Target:       ${PROD_HOST}"
    log_info "========================================="
    log_info ""

    # Backup current Nginx config
    if [[ "${DRY_RUN}" == "false" ]]; then
        ssh "${PROD_USER}@${PROD_HOST}" \
            "sudo cp ${NGINX_CONFIG_PATH:-/etc/nginx/sites-available/listings} /tmp/nginx_backup.conf"
        log_info "Current configuration backed up"
    fi

    # Update Nginx configuration
    update_nginx_config

    # Test configuration
    test_nginx_config

    # Reload Nginx
    reload_nginx

    # Verify traffic distribution
    verify_traffic_distribution

    # Show monitoring info
    monitor_traffic

    log_success "========================================="
    log_success "Traffic split completed successfully!"
    log_success "========================================="
}

# Run main function
main "$@"
