// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: api/proto/listings/v1/orders.proto

package listingssvcv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OrderService_AddToCart_FullMethodName           = "/listingssvc.v1.OrderService/AddToCart"
	OrderService_UpdateCartItem_FullMethodName      = "/listingssvc.v1.OrderService/UpdateCartItem"
	OrderService_RemoveFromCart_FullMethodName      = "/listingssvc.v1.OrderService/RemoveFromCart"
	OrderService_GetCart_FullMethodName             = "/listingssvc.v1.OrderService/GetCart"
	OrderService_ClearCart_FullMethodName           = "/listingssvc.v1.OrderService/ClearCart"
	OrderService_GetUserCarts_FullMethodName        = "/listingssvc.v1.OrderService/GetUserCarts"
	OrderService_CreateOrder_FullMethodName         = "/listingssvc.v1.OrderService/CreateOrder"
	OrderService_GetOrder_FullMethodName            = "/listingssvc.v1.OrderService/GetOrder"
	OrderService_ListOrders_FullMethodName          = "/listingssvc.v1.OrderService/ListOrders"
	OrderService_CancelOrder_FullMethodName         = "/listingssvc.v1.OrderService/CancelOrder"
	OrderService_UpdateOrderStatus_FullMethodName   = "/listingssvc.v1.OrderService/UpdateOrderStatus"
	OrderService_GetOrderStats_FullMethodName       = "/listingssvc.v1.OrderService/GetOrderStats"
	OrderService_AcceptOrder_FullMethodName         = "/listingssvc.v1.OrderService/AcceptOrder"
	OrderService_CreateOrderShipment_FullMethodName = "/listingssvc.v1.OrderService/CreateOrderShipment"
	OrderService_MarkOrderShipped_FullMethodName    = "/listingssvc.v1.OrderService/MarkOrderShipped"
	OrderService_GetOrderTracking_FullMethodName    = "/listingssvc.v1.OrderService/GetOrderTracking"
)

// OrderServiceClient is the client API for OrderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// OrderService provides RPC methods for managing shopping carts and orders
type OrderServiceClient interface {
	// AddToCart adds an item to shopping cart
	// Creates cart if doesn't exist
	// Validates: listing exists, storefront matches, stock available
	AddToCart(ctx context.Context, in *AddToCartRequest, opts ...grpc.CallOption) (*AddToCartResponse, error)
	// UpdateCartItem updates quantity or variant for a cart item
	// Validates: ownership, stock availability
	UpdateCartItem(ctx context.Context, in *UpdateCartItemRequest, opts ...grpc.CallOption) (*UpdateCartItemResponse, error)
	// RemoveFromCart removes an item from cart
	// Validates: ownership
	RemoveFromCart(ctx context.Context, in *RemoveFromCartRequest, opts ...grpc.CallOption) (*RemoveFromCartResponse, error)
	// GetCart retrieves user's cart for a storefront
	// Returns: cart with items, prices, stock availability
	GetCart(ctx context.Context, in *GetCartRequest, opts ...grpc.CallOption) (*GetCartResponse, error)
	// ClearCart removes all items from cart
	// Used after order creation or manual clear
	ClearCart(ctx context.Context, in *ClearCartRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// GetUserCarts retrieves all carts for authenticated user
	// Returns: carts across all storefronts
	GetUserCarts(ctx context.Context, in *GetUserCartsRequest, opts ...grpc.CallOption) (*GetUserCartsResponse, error)
	// CreateOrder creates a new order from cart
	// Transaction:
	// 1. Validate cart items (prices, stock)
	// 2. BEGIN TRANSACTION
	// 3. Lock listings (SELECT FOR UPDATE ORDER BY id ASC - prevent deadlocks)
	// 4. Create order + order_items (snapshot data)
	// 5. Reserve inventory (TTL 30 min)
	// 6. Deduct stock
	// 7. Clear cart
	// 8. COMMIT TRANSACTION
	// 9. Publish OrderCreatedEvent → Payment Service
	CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error)
	// GetOrder retrieves a single order by ID
	// Validates: ownership (user can only see own orders)
	GetOrder(ctx context.Context, in *GetOrderRequest, opts ...grpc.CallOption) (*GetOrderResponse, error)
	// ListOrders retrieves orders with filters and pagination
	// Admin: can see all orders
	// User: can only see own orders
	ListOrders(ctx context.Context, in *ListOrdersRequest, opts ...grpc.CallOption) (*ListOrdersResponse, error)
	// CancelOrder cancels an order and releases inventory
	// Validates: order status (only pending/confirmed allowed)
	// Actions:
	// 1. Update order.status = cancelled
	// 2. Release reservations
	// 3. Restore stock
	// 4. Publish OrderCancelledEvent → Payment Service (for refund)
	CancelOrder(ctx context.Context, in *CancelOrderRequest, opts ...grpc.CallOption) (*CancelOrderResponse, error)
	// UpdateOrderStatus updates order status (admin only)
	// Validates: status transition rules (state machine)
	// On status = shipped: requires tracking_number
	// On status = delivered: sets escrow_release_date
	UpdateOrderStatus(ctx context.Context, in *UpdateOrderStatusRequest, opts ...grpc.CallOption) (*UpdateOrderStatusResponse, error)
	// GetOrderStats retrieves order statistics (admin)
	// Returns: aggregated stats, status breakdown, daily trends
	GetOrderStats(ctx context.Context, in *GetOrderStatsRequest, opts ...grpc.CallOption) (*GetOrderStatsResponse, error)
	// AcceptOrder - seller accepts the order for processing
	// Validates: order.status == confirmed, caller is storefront owner
	// Actions: status → accepted, set accepted_at, notify buyer
	AcceptOrder(ctx context.Context, in *AcceptOrderRequest, opts ...grpc.CallOption) (*AcceptOrderResponse, error)
	// CreateOrderShipment - create shipment via Delivery Service
	// Validates: order.status == accepted, caller is storefront owner
	// Actions: call Delivery.CreateShipment, status → processing, set tracking_number, label_url
	CreateOrderShipment(ctx context.Context, in *CreateOrderShipmentRequest, opts ...grpc.CallOption) (*CreateOrderShipmentResponse, error)
	// MarkOrderShipped - seller marks order as shipped
	// Validates: order.status == processing, tracking_number exists
	// Actions: status → shipped, set shipped_at, notify buyer
	MarkOrderShipped(ctx context.Context, in *MarkOrderShippedRequest, opts ...grpc.CallOption) (*MarkOrderShippedResponse, error)
	// GetOrderTracking - get tracking info from Delivery Service
	// Returns: tracking events timeline from delivery provider
	GetOrderTracking(ctx context.Context, in *GetOrderTrackingRequest, opts ...grpc.CallOption) (*GetOrderTrackingResponse, error)
}

type orderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderServiceClient(cc grpc.ClientConnInterface) OrderServiceClient {
	return &orderServiceClient{cc}
}

func (c *orderServiceClient) AddToCart(ctx context.Context, in *AddToCartRequest, opts ...grpc.CallOption) (*AddToCartResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddToCartResponse)
	err := c.cc.Invoke(ctx, OrderService_AddToCart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) UpdateCartItem(ctx context.Context, in *UpdateCartItemRequest, opts ...grpc.CallOption) (*UpdateCartItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateCartItemResponse)
	err := c.cc.Invoke(ctx, OrderService_UpdateCartItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) RemoveFromCart(ctx context.Context, in *RemoveFromCartRequest, opts ...grpc.CallOption) (*RemoveFromCartResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveFromCartResponse)
	err := c.cc.Invoke(ctx, OrderService_RemoveFromCart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) GetCart(ctx context.Context, in *GetCartRequest, opts ...grpc.CallOption) (*GetCartResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCartResponse)
	err := c.cc.Invoke(ctx, OrderService_GetCart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) ClearCart(ctx context.Context, in *ClearCartRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, OrderService_ClearCart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) GetUserCarts(ctx context.Context, in *GetUserCartsRequest, opts ...grpc.CallOption) (*GetUserCartsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserCartsResponse)
	err := c.cc.Invoke(ctx, OrderService_GetUserCarts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateOrderResponse)
	err := c.cc.Invoke(ctx, OrderService_CreateOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) GetOrder(ctx context.Context, in *GetOrderRequest, opts ...grpc.CallOption) (*GetOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOrderResponse)
	err := c.cc.Invoke(ctx, OrderService_GetOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) ListOrders(ctx context.Context, in *ListOrdersRequest, opts ...grpc.CallOption) (*ListOrdersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListOrdersResponse)
	err := c.cc.Invoke(ctx, OrderService_ListOrders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) CancelOrder(ctx context.Context, in *CancelOrderRequest, opts ...grpc.CallOption) (*CancelOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelOrderResponse)
	err := c.cc.Invoke(ctx, OrderService_CancelOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) UpdateOrderStatus(ctx context.Context, in *UpdateOrderStatusRequest, opts ...grpc.CallOption) (*UpdateOrderStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateOrderStatusResponse)
	err := c.cc.Invoke(ctx, OrderService_UpdateOrderStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) GetOrderStats(ctx context.Context, in *GetOrderStatsRequest, opts ...grpc.CallOption) (*GetOrderStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOrderStatsResponse)
	err := c.cc.Invoke(ctx, OrderService_GetOrderStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) AcceptOrder(ctx context.Context, in *AcceptOrderRequest, opts ...grpc.CallOption) (*AcceptOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcceptOrderResponse)
	err := c.cc.Invoke(ctx, OrderService_AcceptOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) CreateOrderShipment(ctx context.Context, in *CreateOrderShipmentRequest, opts ...grpc.CallOption) (*CreateOrderShipmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateOrderShipmentResponse)
	err := c.cc.Invoke(ctx, OrderService_CreateOrderShipment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) MarkOrderShipped(ctx context.Context, in *MarkOrderShippedRequest, opts ...grpc.CallOption) (*MarkOrderShippedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MarkOrderShippedResponse)
	err := c.cc.Invoke(ctx, OrderService_MarkOrderShipped_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) GetOrderTracking(ctx context.Context, in *GetOrderTrackingRequest, opts ...grpc.CallOption) (*GetOrderTrackingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOrderTrackingResponse)
	err := c.cc.Invoke(ctx, OrderService_GetOrderTracking_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderServiceServer is the server API for OrderService service.
// All implementations must embed UnimplementedOrderServiceServer
// for forward compatibility.
//
// OrderService provides RPC methods for managing shopping carts and orders
type OrderServiceServer interface {
	// AddToCart adds an item to shopping cart
	// Creates cart if doesn't exist
	// Validates: listing exists, storefront matches, stock available
	AddToCart(context.Context, *AddToCartRequest) (*AddToCartResponse, error)
	// UpdateCartItem updates quantity or variant for a cart item
	// Validates: ownership, stock availability
	UpdateCartItem(context.Context, *UpdateCartItemRequest) (*UpdateCartItemResponse, error)
	// RemoveFromCart removes an item from cart
	// Validates: ownership
	RemoveFromCart(context.Context, *RemoveFromCartRequest) (*RemoveFromCartResponse, error)
	// GetCart retrieves user's cart for a storefront
	// Returns: cart with items, prices, stock availability
	GetCart(context.Context, *GetCartRequest) (*GetCartResponse, error)
	// ClearCart removes all items from cart
	// Used after order creation or manual clear
	ClearCart(context.Context, *ClearCartRequest) (*emptypb.Empty, error)
	// GetUserCarts retrieves all carts for authenticated user
	// Returns: carts across all storefronts
	GetUserCarts(context.Context, *GetUserCartsRequest) (*GetUserCartsResponse, error)
	// CreateOrder creates a new order from cart
	// Transaction:
	// 1. Validate cart items (prices, stock)
	// 2. BEGIN TRANSACTION
	// 3. Lock listings (SELECT FOR UPDATE ORDER BY id ASC - prevent deadlocks)
	// 4. Create order + order_items (snapshot data)
	// 5. Reserve inventory (TTL 30 min)
	// 6. Deduct stock
	// 7. Clear cart
	// 8. COMMIT TRANSACTION
	// 9. Publish OrderCreatedEvent → Payment Service
	CreateOrder(context.Context, *CreateOrderRequest) (*CreateOrderResponse, error)
	// GetOrder retrieves a single order by ID
	// Validates: ownership (user can only see own orders)
	GetOrder(context.Context, *GetOrderRequest) (*GetOrderResponse, error)
	// ListOrders retrieves orders with filters and pagination
	// Admin: can see all orders
	// User: can only see own orders
	ListOrders(context.Context, *ListOrdersRequest) (*ListOrdersResponse, error)
	// CancelOrder cancels an order and releases inventory
	// Validates: order status (only pending/confirmed allowed)
	// Actions:
	// 1. Update order.status = cancelled
	// 2. Release reservations
	// 3. Restore stock
	// 4. Publish OrderCancelledEvent → Payment Service (for refund)
	CancelOrder(context.Context, *CancelOrderRequest) (*CancelOrderResponse, error)
	// UpdateOrderStatus updates order status (admin only)
	// Validates: status transition rules (state machine)
	// On status = shipped: requires tracking_number
	// On status = delivered: sets escrow_release_date
	UpdateOrderStatus(context.Context, *UpdateOrderStatusRequest) (*UpdateOrderStatusResponse, error)
	// GetOrderStats retrieves order statistics (admin)
	// Returns: aggregated stats, status breakdown, daily trends
	GetOrderStats(context.Context, *GetOrderStatsRequest) (*GetOrderStatsResponse, error)
	// AcceptOrder - seller accepts the order for processing
	// Validates: order.status == confirmed, caller is storefront owner
	// Actions: status → accepted, set accepted_at, notify buyer
	AcceptOrder(context.Context, *AcceptOrderRequest) (*AcceptOrderResponse, error)
	// CreateOrderShipment - create shipment via Delivery Service
	// Validates: order.status == accepted, caller is storefront owner
	// Actions: call Delivery.CreateShipment, status → processing, set tracking_number, label_url
	CreateOrderShipment(context.Context, *CreateOrderShipmentRequest) (*CreateOrderShipmentResponse, error)
	// MarkOrderShipped - seller marks order as shipped
	// Validates: order.status == processing, tracking_number exists
	// Actions: status → shipped, set shipped_at, notify buyer
	MarkOrderShipped(context.Context, *MarkOrderShippedRequest) (*MarkOrderShippedResponse, error)
	// GetOrderTracking - get tracking info from Delivery Service
	// Returns: tracking events timeline from delivery provider
	GetOrderTracking(context.Context, *GetOrderTrackingRequest) (*GetOrderTrackingResponse, error)
	mustEmbedUnimplementedOrderServiceServer()
}

// UnimplementedOrderServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrderServiceServer struct{}

func (UnimplementedOrderServiceServer) AddToCart(context.Context, *AddToCartRequest) (*AddToCartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddToCart not implemented")
}
func (UnimplementedOrderServiceServer) UpdateCartItem(context.Context, *UpdateCartItemRequest) (*UpdateCartItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCartItem not implemented")
}
func (UnimplementedOrderServiceServer) RemoveFromCart(context.Context, *RemoveFromCartRequest) (*RemoveFromCartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveFromCart not implemented")
}
func (UnimplementedOrderServiceServer) GetCart(context.Context, *GetCartRequest) (*GetCartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCart not implemented")
}
func (UnimplementedOrderServiceServer) ClearCart(context.Context, *ClearCartRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClearCart not implemented")
}
func (UnimplementedOrderServiceServer) GetUserCarts(context.Context, *GetUserCartsRequest) (*GetUserCartsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserCarts not implemented")
}
func (UnimplementedOrderServiceServer) CreateOrder(context.Context, *CreateOrderRequest) (*CreateOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOrder not implemented")
}
func (UnimplementedOrderServiceServer) GetOrder(context.Context, *GetOrderRequest) (*GetOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrder not implemented")
}
func (UnimplementedOrderServiceServer) ListOrders(context.Context, *ListOrdersRequest) (*ListOrdersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListOrders not implemented")
}
func (UnimplementedOrderServiceServer) CancelOrder(context.Context, *CancelOrderRequest) (*CancelOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelOrder not implemented")
}
func (UnimplementedOrderServiceServer) UpdateOrderStatus(context.Context, *UpdateOrderStatusRequest) (*UpdateOrderStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateOrderStatus not implemented")
}
func (UnimplementedOrderServiceServer) GetOrderStats(context.Context, *GetOrderStatsRequest) (*GetOrderStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrderStats not implemented")
}
func (UnimplementedOrderServiceServer) AcceptOrder(context.Context, *AcceptOrderRequest) (*AcceptOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AcceptOrder not implemented")
}
func (UnimplementedOrderServiceServer) CreateOrderShipment(context.Context, *CreateOrderShipmentRequest) (*CreateOrderShipmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOrderShipment not implemented")
}
func (UnimplementedOrderServiceServer) MarkOrderShipped(context.Context, *MarkOrderShippedRequest) (*MarkOrderShippedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MarkOrderShipped not implemented")
}
func (UnimplementedOrderServiceServer) GetOrderTracking(context.Context, *GetOrderTrackingRequest) (*GetOrderTrackingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrderTracking not implemented")
}
func (UnimplementedOrderServiceServer) mustEmbedUnimplementedOrderServiceServer() {}
func (UnimplementedOrderServiceServer) testEmbeddedByValue()                      {}

// UnsafeOrderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderServiceServer will
// result in compilation errors.
type UnsafeOrderServiceServer interface {
	mustEmbedUnimplementedOrderServiceServer()
}

func RegisterOrderServiceServer(s grpc.ServiceRegistrar, srv OrderServiceServer) {
	// If the following call pancis, it indicates UnimplementedOrderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrderService_ServiceDesc, srv)
}

func _OrderService_AddToCart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddToCartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).AddToCart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_AddToCart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).AddToCart(ctx, req.(*AddToCartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_UpdateCartItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCartItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).UpdateCartItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_UpdateCartItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).UpdateCartItem(ctx, req.(*UpdateCartItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_RemoveFromCart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveFromCartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).RemoveFromCart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_RemoveFromCart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).RemoveFromCart(ctx, req.(*RemoveFromCartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_GetCart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).GetCart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_GetCart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).GetCart(ctx, req.(*GetCartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_ClearCart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearCartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).ClearCart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_ClearCart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).ClearCart(ctx, req.(*ClearCartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_GetUserCarts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserCartsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).GetUserCarts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_GetUserCarts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).GetUserCarts(ctx, req.(*GetUserCartsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_CreateOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).CreateOrder(ctx, req.(*CreateOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_GetOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).GetOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_GetOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).GetOrder(ctx, req.(*GetOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_ListOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).ListOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_ListOrders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).ListOrders(ctx, req.(*ListOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_CancelOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).CancelOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_CancelOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).CancelOrder(ctx, req.(*CancelOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_UpdateOrderStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateOrderStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).UpdateOrderStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_UpdateOrderStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).UpdateOrderStatus(ctx, req.(*UpdateOrderStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_GetOrderStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).GetOrderStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_GetOrderStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).GetOrderStats(ctx, req.(*GetOrderStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_AcceptOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).AcceptOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_AcceptOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).AcceptOrder(ctx, req.(*AcceptOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_CreateOrderShipment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrderShipmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).CreateOrderShipment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_CreateOrderShipment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).CreateOrderShipment(ctx, req.(*CreateOrderShipmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_MarkOrderShipped_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkOrderShippedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).MarkOrderShipped(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_MarkOrderShipped_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).MarkOrderShipped(ctx, req.(*MarkOrderShippedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_GetOrderTracking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderTrackingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).GetOrderTracking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_GetOrderTracking_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).GetOrderTracking(ctx, req.(*GetOrderTrackingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OrderService_ServiceDesc is the grpc.ServiceDesc for OrderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "listingssvc.v1.OrderService",
	HandlerType: (*OrderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddToCart",
			Handler:    _OrderService_AddToCart_Handler,
		},
		{
			MethodName: "UpdateCartItem",
			Handler:    _OrderService_UpdateCartItem_Handler,
		},
		{
			MethodName: "RemoveFromCart",
			Handler:    _OrderService_RemoveFromCart_Handler,
		},
		{
			MethodName: "GetCart",
			Handler:    _OrderService_GetCart_Handler,
		},
		{
			MethodName: "ClearCart",
			Handler:    _OrderService_ClearCart_Handler,
		},
		{
			MethodName: "GetUserCarts",
			Handler:    _OrderService_GetUserCarts_Handler,
		},
		{
			MethodName: "CreateOrder",
			Handler:    _OrderService_CreateOrder_Handler,
		},
		{
			MethodName: "GetOrder",
			Handler:    _OrderService_GetOrder_Handler,
		},
		{
			MethodName: "ListOrders",
			Handler:    _OrderService_ListOrders_Handler,
		},
		{
			MethodName: "CancelOrder",
			Handler:    _OrderService_CancelOrder_Handler,
		},
		{
			MethodName: "UpdateOrderStatus",
			Handler:    _OrderService_UpdateOrderStatus_Handler,
		},
		{
			MethodName: "GetOrderStats",
			Handler:    _OrderService_GetOrderStats_Handler,
		},
		{
			MethodName: "AcceptOrder",
			Handler:    _OrderService_AcceptOrder_Handler,
		},
		{
			MethodName: "CreateOrderShipment",
			Handler:    _OrderService_CreateOrderShipment_Handler,
		},
		{
			MethodName: "MarkOrderShipped",
			Handler:    _OrderService_MarkOrderShipped_Handler,
		},
		{
			MethodName: "GetOrderTracking",
			Handler:    _OrderService_GetOrderTracking_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/listings/v1/orders.proto",
}
