// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/proto/categories/v2/category_detection.proto

package categoriesv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DetectFromTextRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Title             string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description       string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Language          string                 `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`                                            // "sr" | "en" | "ru"
	Hints             *CategoryHints         `protobuf:"bytes,4,opt,name=hints,proto3" json:"hints,omitempty"`                                                  // Опциональные подсказки
	SuggestedCategory string                 `protobuf:"bytes,5,opt,name=suggested_category,json=suggestedCategory,proto3" json:"suggested_category,omitempty"` // AI-предложенная категория (например "Furniture")
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DetectFromTextRequest) Reset() {
	*x = DetectFromTextRequest{}
	mi := &file_api_proto_categories_v2_category_detection_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectFromTextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectFromTextRequest) ProtoMessage() {}

func (x *DetectFromTextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_categories_v2_category_detection_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectFromTextRequest.ProtoReflect.Descriptor instead.
func (*DetectFromTextRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_categories_v2_category_detection_proto_rawDescGZIP(), []int{0}
}

func (x *DetectFromTextRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *DetectFromTextRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *DetectFromTextRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *DetectFromTextRequest) GetHints() *CategoryHints {
	if x != nil {
		return x.Hints
	}
	return nil
}

func (x *DetectFromTextRequest) GetSuggestedCategory() string {
	if x != nil {
		return x.SuggestedCategory
	}
	return ""
}

type DetectFromKeywordsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keywords      []string               `protobuf:"bytes,1,rep,name=keywords,proto3" json:"keywords,omitempty"`
	Language      string                 `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetectFromKeywordsRequest) Reset() {
	*x = DetectFromKeywordsRequest{}
	mi := &file_api_proto_categories_v2_category_detection_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectFromKeywordsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectFromKeywordsRequest) ProtoMessage() {}

func (x *DetectFromKeywordsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_categories_v2_category_detection_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectFromKeywordsRequest.ProtoReflect.Descriptor instead.
func (*DetectFromKeywordsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_categories_v2_category_detection_proto_rawDescGZIP(), []int{1}
}

func (x *DetectFromKeywordsRequest) GetKeywords() []string {
	if x != nil {
		return x.Keywords
	}
	return nil
}

func (x *DetectFromKeywordsRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type DetectBatchRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Items         []*DetectFromTextRequest `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetectBatchRequest) Reset() {
	*x = DetectBatchRequest{}
	mi := &file_api_proto_categories_v2_category_detection_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectBatchRequest) ProtoMessage() {}

func (x *DetectBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_categories_v2_category_detection_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectBatchRequest.ProtoReflect.Descriptor instead.
func (*DetectBatchRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_categories_v2_category_detection_proto_rawDescGZIP(), []int{2}
}

func (x *DetectBatchRequest) GetItems() []*DetectFromTextRequest {
	if x != nil {
		return x.Items
	}
	return nil
}

type ConfirmSelectionRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	DetectionId        string                 `protobuf:"bytes,1,opt,name=detection_id,json=detectionId,proto3" json:"detection_id,omitempty"`
	SelectedCategoryId string                 `protobuf:"bytes,2,opt,name=selected_category_id,json=selectedCategoryId,proto3" json:"selected_category_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ConfirmSelectionRequest) Reset() {
	*x = ConfirmSelectionRequest{}
	mi := &file_api_proto_categories_v2_category_detection_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmSelectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmSelectionRequest) ProtoMessage() {}

func (x *ConfirmSelectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_categories_v2_category_detection_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmSelectionRequest.ProtoReflect.Descriptor instead.
func (*ConfirmSelectionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_categories_v2_category_detection_proto_rawDescGZIP(), []int{3}
}

func (x *ConfirmSelectionRequest) GetDetectionId() string {
	if x != nil {
		return x.DetectionId
	}
	return ""
}

func (x *ConfirmSelectionRequest) GetSelectedCategoryId() string {
	if x != nil {
		return x.SelectedCategoryId
	}
	return ""
}

type CategoryMatch struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CategoryId      string                 `protobuf:"bytes,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`                  // UUID категории
	CategoryName    string                 `protobuf:"bytes,2,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`            // Локализованное название
	CategorySlug    string                 `protobuf:"bytes,3,opt,name=category_slug,json=categorySlug,proto3" json:"category_slug,omitempty"`            // Slug для URL
	CategoryPath    string                 `protobuf:"bytes,4,opt,name=category_path,json=categoryPath,proto3" json:"category_path,omitempty"`            // "Electronics > Phones > Smartphones"
	ConfidenceScore float64                `protobuf:"fixed64,5,opt,name=confidence_score,json=confidenceScore,proto3" json:"confidence_score,omitempty"` // 0.0 - 1.0
	DetectionMethod string                 `protobuf:"bytes,6,opt,name=detection_method,json=detectionMethod,proto3" json:"detection_method,omitempty"`   // "ai_claude" | "keyword_match" | "similarity"
	MatchedKeywords []string               `protobuf:"bytes,7,rep,name=matched_keywords,json=matchedKeywords,proto3" json:"matched_keywords,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CategoryMatch) Reset() {
	*x = CategoryMatch{}
	mi := &file_api_proto_categories_v2_category_detection_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryMatch) ProtoMessage() {}

func (x *CategoryMatch) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_categories_v2_category_detection_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryMatch.ProtoReflect.Descriptor instead.
func (*CategoryMatch) Descriptor() ([]byte, []int) {
	return file_api_proto_categories_v2_category_detection_proto_rawDescGZIP(), []int{4}
}

func (x *CategoryMatch) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *CategoryMatch) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

func (x *CategoryMatch) GetCategorySlug() string {
	if x != nil {
		return x.CategorySlug
	}
	return ""
}

func (x *CategoryMatch) GetCategoryPath() string {
	if x != nil {
		return x.CategoryPath
	}
	return ""
}

func (x *CategoryMatch) GetConfidenceScore() float64 {
	if x != nil {
		return x.ConfidenceScore
	}
	return 0
}

func (x *CategoryMatch) GetDetectionMethod() string {
	if x != nil {
		return x.DetectionMethod
	}
	return ""
}

func (x *CategoryMatch) GetMatchedKeywords() []string {
	if x != nil {
		return x.MatchedKeywords
	}
	return nil
}

type DetectCategoryResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Primary          *CategoryMatch         `protobuf:"bytes,1,opt,name=primary,proto3" json:"primary,omitempty"`                            // Лучшее совпадение
	Alternatives     []*CategoryMatch       `protobuf:"bytes,2,rep,name=alternatives,proto3" json:"alternatives,omitempty"`                  // Альтернативы (до 5)
	DetectionId      string                 `protobuf:"bytes,3,opt,name=detection_id,json=detectionId,proto3" json:"detection_id,omitempty"` // UUID для tracking
	ProcessingTimeMs int32                  `protobuf:"varint,4,opt,name=processing_time_ms,json=processingTimeMs,proto3" json:"processing_time_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DetectCategoryResponse) Reset() {
	*x = DetectCategoryResponse{}
	mi := &file_api_proto_categories_v2_category_detection_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectCategoryResponse) ProtoMessage() {}

func (x *DetectCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_categories_v2_category_detection_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectCategoryResponse.ProtoReflect.Descriptor instead.
func (*DetectCategoryResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_categories_v2_category_detection_proto_rawDescGZIP(), []int{5}
}

func (x *DetectCategoryResponse) GetPrimary() *CategoryMatch {
	if x != nil {
		return x.Primary
	}
	return nil
}

func (x *DetectCategoryResponse) GetAlternatives() []*CategoryMatch {
	if x != nil {
		return x.Alternatives
	}
	return nil
}

func (x *DetectCategoryResponse) GetDetectionId() string {
	if x != nil {
		return x.DetectionId
	}
	return ""
}

func (x *DetectCategoryResponse) GetProcessingTimeMs() int32 {
	if x != nil {
		return x.ProcessingTimeMs
	}
	return 0
}

type DetectBatchResponse struct {
	state                 protoimpl.MessageState    `protogen:"open.v1"`
	Results               []*DetectCategoryResponse `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	TotalProcessingTimeMs int32                     `protobuf:"varint,2,opt,name=total_processing_time_ms,json=totalProcessingTimeMs,proto3" json:"total_processing_time_ms,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *DetectBatchResponse) Reset() {
	*x = DetectBatchResponse{}
	mi := &file_api_proto_categories_v2_category_detection_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectBatchResponse) ProtoMessage() {}

func (x *DetectBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_categories_v2_category_detection_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectBatchResponse.ProtoReflect.Descriptor instead.
func (*DetectBatchResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_categories_v2_category_detection_proto_rawDescGZIP(), []int{6}
}

func (x *DetectBatchResponse) GetResults() []*DetectCategoryResponse {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *DetectBatchResponse) GetTotalProcessingTimeMs() int32 {
	if x != nil {
		return x.TotalProcessingTimeMs
	}
	return 0
}

type ConfirmSelectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmSelectionResponse) Reset() {
	*x = ConfirmSelectionResponse{}
	mi := &file_api_proto_categories_v2_category_detection_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmSelectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmSelectionResponse) ProtoMessage() {}

func (x *ConfirmSelectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_categories_v2_category_detection_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmSelectionResponse.ProtoReflect.Descriptor instead.
func (*ConfirmSelectionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_categories_v2_category_detection_proto_rawDescGZIP(), []int{7}
}

func (x *ConfirmSelectionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CategoryHints struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`                              // "electronics", "fashion", etc.
	ProductType   string                 `protobuf:"bytes,2,opt,name=product_type,json=productType,proto3" json:"product_type,omitempty"` // "smartphone", "dress", etc.
	Keywords      []string               `protobuf:"bytes,3,rep,name=keywords,proto3" json:"keywords,omitempty"`                          // Дополнительные ключевые слова
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryHints) Reset() {
	*x = CategoryHints{}
	mi := &file_api_proto_categories_v2_category_detection_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryHints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryHints) ProtoMessage() {}

func (x *CategoryHints) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_categories_v2_category_detection_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryHints.ProtoReflect.Descriptor instead.
func (*CategoryHints) Descriptor() ([]byte, []int) {
	return file_api_proto_categories_v2_category_detection_proto_rawDescGZIP(), []int{8}
}

func (x *CategoryHints) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *CategoryHints) GetProductType() string {
	if x != nil {
		return x.ProductType
	}
	return ""
}

func (x *CategoryHints) GetKeywords() []string {
	if x != nil {
		return x.Keywords
	}
	return nil
}

var File_api_proto_categories_v2_category_detection_proto protoreflect.FileDescriptor

const file_api_proto_categories_v2_category_detection_proto_rawDesc = "" +
	"\n" +
	"0api/proto/categories/v2/category_detection.proto\x12\rcategories.v2\"\xce\x01\n" +
	"\x15DetectFromTextRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\x122\n" +
	"\x05hints\x18\x04 \x01(\v2\x1c.categories.v2.CategoryHintsR\x05hints\x12-\n" +
	"\x12suggested_category\x18\x05 \x01(\tR\x11suggestedCategory\"S\n" +
	"\x19DetectFromKeywordsRequest\x12\x1a\n" +
	"\bkeywords\x18\x01 \x03(\tR\bkeywords\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\tR\blanguage\"P\n" +
	"\x12DetectBatchRequest\x12:\n" +
	"\x05items\x18\x01 \x03(\v2$.categories.v2.DetectFromTextRequestR\x05items\"n\n" +
	"\x17ConfirmSelectionRequest\x12!\n" +
	"\fdetection_id\x18\x01 \x01(\tR\vdetectionId\x120\n" +
	"\x14selected_category_id\x18\x02 \x01(\tR\x12selectedCategoryId\"\xa0\x02\n" +
	"\rCategoryMatch\x12\x1f\n" +
	"\vcategory_id\x18\x01 \x01(\tR\n" +
	"categoryId\x12#\n" +
	"\rcategory_name\x18\x02 \x01(\tR\fcategoryName\x12#\n" +
	"\rcategory_slug\x18\x03 \x01(\tR\fcategorySlug\x12#\n" +
	"\rcategory_path\x18\x04 \x01(\tR\fcategoryPath\x12)\n" +
	"\x10confidence_score\x18\x05 \x01(\x01R\x0fconfidenceScore\x12)\n" +
	"\x10detection_method\x18\x06 \x01(\tR\x0fdetectionMethod\x12)\n" +
	"\x10matched_keywords\x18\a \x03(\tR\x0fmatchedKeywords\"\xe3\x01\n" +
	"\x16DetectCategoryResponse\x126\n" +
	"\aprimary\x18\x01 \x01(\v2\x1c.categories.v2.CategoryMatchR\aprimary\x12@\n" +
	"\falternatives\x18\x02 \x03(\v2\x1c.categories.v2.CategoryMatchR\falternatives\x12!\n" +
	"\fdetection_id\x18\x03 \x01(\tR\vdetectionId\x12,\n" +
	"\x12processing_time_ms\x18\x04 \x01(\x05R\x10processingTimeMs\"\x8f\x01\n" +
	"\x13DetectBatchResponse\x12?\n" +
	"\aresults\x18\x01 \x03(\v2%.categories.v2.DetectCategoryResponseR\aresults\x127\n" +
	"\x18total_processing_time_ms\x18\x02 \x01(\x05R\x15totalProcessingTimeMs\"4\n" +
	"\x18ConfirmSelectionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"f\n" +
	"\rCategoryHints\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12!\n" +
	"\fproduct_type\x18\x02 \x01(\tR\vproductType\x12\x1a\n" +
	"\bkeywords\x18\x03 \x03(\tR\bkeywords2\x9b\x03\n" +
	"\x18CategoryDetectionService\x12]\n" +
	"\x0eDetectFromText\x12$.categories.v2.DetectFromTextRequest\x1a%.categories.v2.DetectCategoryResponse\x12e\n" +
	"\x12DetectFromKeywords\x12(.categories.v2.DetectFromKeywordsRequest\x1a%.categories.v2.DetectCategoryResponse\x12T\n" +
	"\vDetectBatch\x12!.categories.v2.DetectBatchRequest\x1a\".categories.v2.DetectBatchResponse\x12c\n" +
	"\x10ConfirmSelection\x12&.categories.v2.ConfirmSelectionRequest\x1a'.categories.v2.ConfirmSelectionResponseBEZCgithub.com/vondi-global/listings/api/gen/categories/v2;categoriesv2b\x06proto3"

var (
	file_api_proto_categories_v2_category_detection_proto_rawDescOnce sync.Once
	file_api_proto_categories_v2_category_detection_proto_rawDescData []byte
)

func file_api_proto_categories_v2_category_detection_proto_rawDescGZIP() []byte {
	file_api_proto_categories_v2_category_detection_proto_rawDescOnce.Do(func() {
		file_api_proto_categories_v2_category_detection_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_categories_v2_category_detection_proto_rawDesc), len(file_api_proto_categories_v2_category_detection_proto_rawDesc)))
	})
	return file_api_proto_categories_v2_category_detection_proto_rawDescData
}

var file_api_proto_categories_v2_category_detection_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_proto_categories_v2_category_detection_proto_goTypes = []any{
	(*DetectFromTextRequest)(nil),     // 0: categories.v2.DetectFromTextRequest
	(*DetectFromKeywordsRequest)(nil), // 1: categories.v2.DetectFromKeywordsRequest
	(*DetectBatchRequest)(nil),        // 2: categories.v2.DetectBatchRequest
	(*ConfirmSelectionRequest)(nil),   // 3: categories.v2.ConfirmSelectionRequest
	(*CategoryMatch)(nil),             // 4: categories.v2.CategoryMatch
	(*DetectCategoryResponse)(nil),    // 5: categories.v2.DetectCategoryResponse
	(*DetectBatchResponse)(nil),       // 6: categories.v2.DetectBatchResponse
	(*ConfirmSelectionResponse)(nil),  // 7: categories.v2.ConfirmSelectionResponse
	(*CategoryHints)(nil),             // 8: categories.v2.CategoryHints
}
var file_api_proto_categories_v2_category_detection_proto_depIdxs = []int32{
	8, // 0: categories.v2.DetectFromTextRequest.hints:type_name -> categories.v2.CategoryHints
	0, // 1: categories.v2.DetectBatchRequest.items:type_name -> categories.v2.DetectFromTextRequest
	4, // 2: categories.v2.DetectCategoryResponse.primary:type_name -> categories.v2.CategoryMatch
	4, // 3: categories.v2.DetectCategoryResponse.alternatives:type_name -> categories.v2.CategoryMatch
	5, // 4: categories.v2.DetectBatchResponse.results:type_name -> categories.v2.DetectCategoryResponse
	0, // 5: categories.v2.CategoryDetectionService.DetectFromText:input_type -> categories.v2.DetectFromTextRequest
	1, // 6: categories.v2.CategoryDetectionService.DetectFromKeywords:input_type -> categories.v2.DetectFromKeywordsRequest
	2, // 7: categories.v2.CategoryDetectionService.DetectBatch:input_type -> categories.v2.DetectBatchRequest
	3, // 8: categories.v2.CategoryDetectionService.ConfirmSelection:input_type -> categories.v2.ConfirmSelectionRequest
	5, // 9: categories.v2.CategoryDetectionService.DetectFromText:output_type -> categories.v2.DetectCategoryResponse
	5, // 10: categories.v2.CategoryDetectionService.DetectFromKeywords:output_type -> categories.v2.DetectCategoryResponse
	6, // 11: categories.v2.CategoryDetectionService.DetectBatch:output_type -> categories.v2.DetectBatchResponse
	7, // 12: categories.v2.CategoryDetectionService.ConfirmSelection:output_type -> categories.v2.ConfirmSelectionResponse
	9, // [9:13] is the sub-list for method output_type
	5, // [5:9] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_api_proto_categories_v2_category_detection_proto_init() }
func file_api_proto_categories_v2_category_detection_proto_init() {
	if File_api_proto_categories_v2_category_detection_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_categories_v2_category_detection_proto_rawDesc), len(file_api_proto_categories_v2_category_detection_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_categories_v2_category_detection_proto_goTypes,
		DependencyIndexes: file_api_proto_categories_v2_category_detection_proto_depIdxs,
		MessageInfos:      file_api_proto_categories_v2_category_detection_proto_msgTypes,
	}.Build()
	File_api_proto_categories_v2_category_detection_proto = out.File
	file_api_proto_categories_v2_category_detection_proto_goTypes = nil
	file_api_proto_categories_v2_category_detection_proto_depIdxs = nil
}
