// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: api/proto/categories/v2/categories_v2.proto

package categoriesv2

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CategoryServiceV2_GetCategoryTreeV2_FullMethodName   = "/categoriessvc.v2.CategoryServiceV2/GetCategoryTreeV2"
	CategoryServiceV2_GetCategoryBySlugV2_FullMethodName = "/categoriessvc.v2.CategoryServiceV2/GetCategoryBySlugV2"
	CategoryServiceV2_GetCategoryByUUID_FullMethodName   = "/categoriessvc.v2.CategoryServiceV2/GetCategoryByUUID"
	CategoryServiceV2_GetBreadcrumb_FullMethodName       = "/categoriessvc.v2.CategoryServiceV2/GetBreadcrumb"
)

// CategoryServiceV2Client is the client API for CategoryServiceV2 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CategoryServiceV2Client interface {
	// GetCategoryTreeV2 retrieves category tree with localization
	GetCategoryTreeV2(ctx context.Context, in *GetCategoryTreeV2Request, opts ...grpc.CallOption) (*GetCategoryTreeV2Response, error)
	// GetCategoryBySlugV2 retrieves a single category by slug with localization
	GetCategoryBySlugV2(ctx context.Context, in *GetCategoryBySlugV2Request, opts ...grpc.CallOption) (*GetCategoryBySlugV2Response, error)
	// GetCategoryByUUID retrieves a single category by UUID with localization
	GetCategoryByUUID(ctx context.Context, in *GetCategoryByUUIDRequest, opts ...grpc.CallOption) (*GetCategoryByUUIDResponse, error)
	// GetBreadcrumb retrieves breadcrumb trail for a category
	GetBreadcrumb(ctx context.Context, in *GetBreadcrumbRequest, opts ...grpc.CallOption) (*GetBreadcrumbResponse, error)
}

type categoryServiceV2Client struct {
	cc grpc.ClientConnInterface
}

func NewCategoryServiceV2Client(cc grpc.ClientConnInterface) CategoryServiceV2Client {
	return &categoryServiceV2Client{cc}
}

func (c *categoryServiceV2Client) GetCategoryTreeV2(ctx context.Context, in *GetCategoryTreeV2Request, opts ...grpc.CallOption) (*GetCategoryTreeV2Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCategoryTreeV2Response)
	err := c.cc.Invoke(ctx, CategoryServiceV2_GetCategoryTreeV2_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoryServiceV2Client) GetCategoryBySlugV2(ctx context.Context, in *GetCategoryBySlugV2Request, opts ...grpc.CallOption) (*GetCategoryBySlugV2Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCategoryBySlugV2Response)
	err := c.cc.Invoke(ctx, CategoryServiceV2_GetCategoryBySlugV2_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoryServiceV2Client) GetCategoryByUUID(ctx context.Context, in *GetCategoryByUUIDRequest, opts ...grpc.CallOption) (*GetCategoryByUUIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCategoryByUUIDResponse)
	err := c.cc.Invoke(ctx, CategoryServiceV2_GetCategoryByUUID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoryServiceV2Client) GetBreadcrumb(ctx context.Context, in *GetBreadcrumbRequest, opts ...grpc.CallOption) (*GetBreadcrumbResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBreadcrumbResponse)
	err := c.cc.Invoke(ctx, CategoryServiceV2_GetBreadcrumb_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CategoryServiceV2Server is the server API for CategoryServiceV2 service.
// All implementations must embed UnimplementedCategoryServiceV2Server
// for forward compatibility.
type CategoryServiceV2Server interface {
	// GetCategoryTreeV2 retrieves category tree with localization
	GetCategoryTreeV2(context.Context, *GetCategoryTreeV2Request) (*GetCategoryTreeV2Response, error)
	// GetCategoryBySlugV2 retrieves a single category by slug with localization
	GetCategoryBySlugV2(context.Context, *GetCategoryBySlugV2Request) (*GetCategoryBySlugV2Response, error)
	// GetCategoryByUUID retrieves a single category by UUID with localization
	GetCategoryByUUID(context.Context, *GetCategoryByUUIDRequest) (*GetCategoryByUUIDResponse, error)
	// GetBreadcrumb retrieves breadcrumb trail for a category
	GetBreadcrumb(context.Context, *GetBreadcrumbRequest) (*GetBreadcrumbResponse, error)
	mustEmbedUnimplementedCategoryServiceV2Server()
}

// UnimplementedCategoryServiceV2Server must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCategoryServiceV2Server struct{}

func (UnimplementedCategoryServiceV2Server) GetCategoryTreeV2(context.Context, *GetCategoryTreeV2Request) (*GetCategoryTreeV2Response, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCategoryTreeV2 not implemented")
}
func (UnimplementedCategoryServiceV2Server) GetCategoryBySlugV2(context.Context, *GetCategoryBySlugV2Request) (*GetCategoryBySlugV2Response, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCategoryBySlugV2 not implemented")
}
func (UnimplementedCategoryServiceV2Server) GetCategoryByUUID(context.Context, *GetCategoryByUUIDRequest) (*GetCategoryByUUIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCategoryByUUID not implemented")
}
func (UnimplementedCategoryServiceV2Server) GetBreadcrumb(context.Context, *GetBreadcrumbRequest) (*GetBreadcrumbResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBreadcrumb not implemented")
}
func (UnimplementedCategoryServiceV2Server) mustEmbedUnimplementedCategoryServiceV2Server() {}
func (UnimplementedCategoryServiceV2Server) testEmbeddedByValue()                           {}

// UnsafeCategoryServiceV2Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CategoryServiceV2Server will
// result in compilation errors.
type UnsafeCategoryServiceV2Server interface {
	mustEmbedUnimplementedCategoryServiceV2Server()
}

func RegisterCategoryServiceV2Server(s grpc.ServiceRegistrar, srv CategoryServiceV2Server) {
	// If the following call panics, it indicates UnimplementedCategoryServiceV2Server was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CategoryServiceV2_ServiceDesc, srv)
}

func _CategoryServiceV2_GetCategoryTreeV2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCategoryTreeV2Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryServiceV2Server).GetCategoryTreeV2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CategoryServiceV2_GetCategoryTreeV2_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryServiceV2Server).GetCategoryTreeV2(ctx, req.(*GetCategoryTreeV2Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _CategoryServiceV2_GetCategoryBySlugV2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCategoryBySlugV2Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryServiceV2Server).GetCategoryBySlugV2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CategoryServiceV2_GetCategoryBySlugV2_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryServiceV2Server).GetCategoryBySlugV2(ctx, req.(*GetCategoryBySlugV2Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _CategoryServiceV2_GetCategoryByUUID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCategoryByUUIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryServiceV2Server).GetCategoryByUUID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CategoryServiceV2_GetCategoryByUUID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryServiceV2Server).GetCategoryByUUID(ctx, req.(*GetCategoryByUUIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CategoryServiceV2_GetBreadcrumb_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBreadcrumbRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryServiceV2Server).GetBreadcrumb(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CategoryServiceV2_GetBreadcrumb_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryServiceV2Server).GetBreadcrumb(ctx, req.(*GetBreadcrumbRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CategoryServiceV2_ServiceDesc is the grpc.ServiceDesc for CategoryServiceV2 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CategoryServiceV2_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "categoriessvc.v2.CategoryServiceV2",
	HandlerType: (*CategoryServiceV2Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCategoryTreeV2",
			Handler:    _CategoryServiceV2_GetCategoryTreeV2_Handler,
		},
		{
			MethodName: "GetCategoryBySlugV2",
			Handler:    _CategoryServiceV2_GetCategoryBySlugV2_Handler,
		},
		{
			MethodName: "GetCategoryByUUID",
			Handler:    _CategoryServiceV2_GetCategoryByUUID_Handler,
		},
		{
			MethodName: "GetBreadcrumb",
			Handler:    _CategoryServiceV2_GetBreadcrumb_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/categories/v2/categories_v2.proto",
}
